### ISSUE TITLE
Comparison/conversion of unix timestamps and literal time values affected by MySQL leap seconds

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#100]
_From [r.wetzlmayr](https://code.google.com/u/r.wetzlmayr/) on December 23, 2010 11:16:44_

==Steps to reproduce==
1. Create an article with a posted date of 2010-12-15 11:24:45
2. The contents of the Posted column is 2010-12-15 11:24:21, a timestamp vlue of 1292408685.
3. Execute SQL:

```
select ID, Posted, unix_timestamp(Posted) from textpattern where unix_timestamp(Posted) = 1292408685;
```

==Expected output==

Posted = '2010-12-15 11:24:45' as entered in step 1

==Actual output==

Posted = '2010-12-15 11:24:21', i.e. 24 seconds off

==Reason==

MySQL 5.1.31+ accounts for leap seconds on capable O/Ss: http://dev.mysql.com/doc/refman/5.1/en/time-zone-leap-seconds.html . A diret comparison or conversion between timestamps and time literals may lead to unexpected effects.

==Impact==

We convert from time literals to timestamps and vice versa on a whole lot of places. e.g. as we save an article.

We compare with results from MysQLs 'now()', 'unix_timestamp()', timestamps and DATETIME columns at various locations (getNeighbour() [ https://code.google.com/p/textpattern/source/browse/development/4.x/textpattern/publish.php?r=3470#1012 ], list_list() [ https://code.google.com/p/textpattern/source/browse/development/4.x/textpattern/include/txp_list.php?r=3470#292 ] et cetera). 

I assume most of these are off  by some seconds.

==Additional reading==

MySQL forum post: http://forums.mysql.com/read.php?10,388911,388911 Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=96_

**Comment by petecooper** [comment]
>Create an article with a posted date of 2010-12-15 11:24:45
>The contents of the Posted column is 2010-12-15 11:24:21

FYI: I've just tried this out of curiosity on Textpattern 4.8.6 on Percona Server 8.0, and the timestamp appears to match as expected (taking into account the `+3600` time offset).

![Screenshot 2021-04-12 at 09 08 28](https://user-images.githubusercontent.com/226578/114362192-fa1f5f80-9b6e-11eb-82b9-f5c5d03b2004.png)
![Screenshot 2021-04-12 at 09 08 38](https://user-images.githubusercontent.com/226578/114362201-fbe92300-9b6e-11eb-83c6-17e9ffd50386.png)
![Screenshot 2021-04-12 at 09 09 39](https://user-images.githubusercontent.com/226578/114362204-fd1a5000-9b6e-11eb-92fb-4585f1db17d2.png)

**Comment by Bloke** [comment]
Maybe this only affected older versions of MySQL and can be closed?

**Comment by petecooper** [comment]
This is what I'm wondering. If we can test on the oldest MySQL we officially support, that would be useful.

**Comment by petecooper** [comment]
Opened https://forum.textpattern.com/viewtopic.php?pid=329785#p329785 to get a few more eyeballs on it.

**Comment by petecooper** [comment]
Feedback so far on the above link has been positive. I'll let it run for a few more replies, and if we're all clear then we can close this issue, I think.

**Comment by petecooper** [comment]
Closing. No longer relevant given feedback to date in linked forum thread.
