### ISSUE TITLE
Broken trace in admin interface

### ISSUE THREAD

**Issue by makss** [textpattern/textpattern#1001]
### Expected behaviour

Production status:
* Live  - No trace log
* Testing - Summary only
* Debug - Full trace log

### Actual behaviour

Production status:
* Live  - Full trace log
* Testing - Full trace log
* Debug - Full trace log

**Comment by petecooper** [comment]
Is this 4.7-dev, @makss? Checking 4.6.2 - production status:

* Live - Full trace log
* Testing - Full trace log
* Debug - Full trace log

For as long as I can remember, there has always been full trace in the admin-side – so I would consider it expected behaviour.

**Comment by makss** [comment]
The output of the trace log was [originally](https://github.com/textpattern/textpattern/pull/498) conceived taking into account the status of the debugging. It seems that this moment was missed when [converting functions to an object](https://github.com/textpattern/textpattern/commit/4dd9b2379b6bc383e033f9904f6603ac75afd8d8#diff-c984cb4de8371ba5582ea16e6ebbc41d). A little later I will fix it.
