### ISSUE TITLE
Textpack format change + language performance gains

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1002]
Any specific reason we have labelled the tag trace text strings as `config.ini`? That could cause confusion for users when we talk of the config file (i.e. `config.php`). Unless there is a technological barrier to naming it differently it would be wise to change the ini filename I think.

**Comment by makss** [comment]
Can be called a file: `/textpattern/lang/debug.msg` ?

**Comment by philwareham** [comment]
I don't intend to open this file up to translators directly (although there is nothing stopping an admin from amending their own text in that file) so although it kind of fits the `lang` directory I'd rather not put it there. Also, can it be a `.txt` file extension as I am conscious of the variety of different file types we already use?

**Comment by Bloke** [comment]
If we drop it in the `lang` directory with a `.txt` or `.textpack` extension, the Languages system will consider it a "language" so we can't do that. Any other file extension will be fine though.

I concur that `config.ini` isn't great but given that @bloatware uncovered issues with using file names that clash with public site sections, introducing _another_ filename at the root level is problematic. If we can shove it cleanly inside `lang` without breaking the language system, that's probably neatest.

**Comment by philwareham** [comment]
OK, shove it in `lang` and call it `debug.ini` and I'm cool with that.

**Comment by bloatware** [comment]
I'm happy with whatever name/extension, but, semantically it *is* `.ini` (i.e. config file), not `.txt` (plain unstructured text). Currently it contains only debug strings, but other sections could be appended later, if necessary. So moving it to `lang` looks a bit restrictive.

**Comment by philwareham** [comment]
Well, now is the time to change the language file extension I guess if we are going to, since we have moved far enough away from the pre 4.7 handling of Textpack installation. @bloke @makss thoughts?

**Comment by bloatware** [comment]
In core we can, old plugins I'm not sure.

**Comment by philwareham** [comment]
Do you mean change just the file type, or the actual format used within the file to store strings?

**Comment by Bloke** [comment]
I'm guessing that PHP's `parse_ini_file()` is faster than us trawling through a `.txt` file line by line, right? In which case, great, with the following notes:

* We often don't need the whole file. A lot of the time we just need the language name, code and direction. See `L10n\Lang.php->fetchMeta()`. Hence, these strings were put near the top of the file for speed. In theory, the lang code should be the same as the filename (minus extension) but it doesn't hurt to have the extra indirection.
* The (currently three) 'meta' rows mentioned above still need to be inserted into the database in the 'common' section. There are a whole slew of other strings in the same section later on. Can an `.ini` file have the same 'section' name in more than one place in the same file?
* The 'setup' section (plus 'common') are the only ones required for the setup process.
* The 'setup' section must be ignored when installing a language.
* The 'common' and 'public' sections are the only ones required when rendering the public site.
* If we could optionally and efficiently pick and choose the sections to read, that'd be great.
* _Any_ file in the `lang` directory with a file extension that is (currently) `.txt` or `.textpack` is treated as _a dedicated entire language pack_. We `glob()` the `lang` directory. If we add the `debug` strings as a file here with the same file extension as regular, full language packs, it'll think the debug strings are a true language and fall over. This will require exceptions in the code to skip any "non-conforming" `.ini` files, which adds processing time. Granted, it's off the critical path so isn't much of an issue, but needs bearing in mind.

If we change the file type, the file format needs to change:

```
[common]
lang_name = English (British)
lang_code = en-GB
lang_dir = ltr

[admin]
account_activation = Please activate your account
account_activation_confirmation = Please use the link below to activate your account and set up a password.
add_new_author = Add new author
...
[common]
active = Active
add = Add
admin = Admin
are_you_sure = Are you sure?
...
```
As far as I know, no plugins access these files directly yet. In theory they shouldn't need to as we are providing a public API in `Lang.php` to handle and process them safely. If the API isn't complete, now's the time to add stuff to it!

**Comment by bloatware** [comment]
@philwareham I mean the actual format, which is not `.ini` valid. Writing an extra converter, though easy, would probably be an overkill.

@Bloke Most PHP (compiled?) core functions are faster than user-defined ones, so I wouldn't be surprised that retrieving the whole structured (by sections) array via `parse_ini_file()` is as fast as `L10n\Lang.php->fetchMeta()`. Needs testing, probably in 4.8?

**Comment by philwareham** [comment]
> Presumably our tools for compiling stuff from Crowdin/GitHub can be altered to accommodate the requirements of the `.ini` format when spitting out language packs?

Yes. In fact `.ini` files would be much better for me, as it's one of the file types Crowdin supports natively (unlike our Textpack format). Currently I have to export from Crowdin as XML then paste the new translations into our GitHub repo manually. Not great.

**Comment by Bloke** [comment]
As long as the caveats in my post above are taken into account, I'm fine with moving our `.txt` files to `.ini` format now. I concur that a built-in PHP function is likely faster than manually doing it. And since it offers a smoother workflow for converting from Crowdin, that's a big plus.

My major concern is that we don't get any choice to only parse a bit of the file, and often we don't need to waste memory loading the whole thing. With 1000+ strings in a file that's a lot of memory just to render the language names in the dropdowns at the top of the Languages panel. Imagine a site that had 8 languages installed. Even with caching, that's 8000+ strings read in, from which we only need 24!

Mind you, I'm not convinced XML is any better: you probably need to read the whole file before you can extract the first element...

**Comment by Bloke** [comment]
What we really need is a way to store rapidly-accessible "metadata" about a language, and then the language strings themselves. And the metadata also needs to become part of the installed language pack too.

What I _don't_ want to do, however, is introduce a new file or built-in structure that holds a directory list of "available" languages. Because that prevents us (or someone else) just dropping a language file in the `lang` directory and immediately installing it.

**Comment by bloatware** [comment]
Agree re metadata, but we could extract them from `.ini` as before, from few first lines.

**Comment by Bloke** [comment]
That's cool. Would we then have to programmatically add those three strings to the 'common' section so they get loaded into the DB in that group? Or can an `.ini` file have the same group heading twice in a file? I think it can but I've never tried.

**Comment by bloatware** [comment]
Not sure it can, but we can call this group `meta` and load it as `common` it in DB?

**Comment by Bloke** [comment]
That would be superb.

**Comment by philwareham** [comment]
OK, I've updated the Textpacks to remove the strings that are now in the `.ini` file.

A couple of things that need to be done, I've found:

1. There are some hard coded English texts in some `trigger_error` functions. If you grep `trigger_error` you'll find them. These should be moved to the `.ini` file as strings instead.
2. Ideally the error messages should be wrapped in `<span dir="auto">...</span>` tags if you possibly can - that way the error messages will display correctly (bidi) when displayed in any language - even RTL.

**Comment by bloatware** [comment]
Great, will investigate when I'm through with fileupload, or @Bloke @makss @NicolasGraph please go ahead.

1. These are one-timers, I thought they can be edited in place, unlike more frequent patterns. Can be moved to `config.ini`, sure.
2. The easiest way would be to amend `trigger_error()` function, but I'm not sure all error messages contain only inline elements.

**Comment by Bloke** [comment]
Actually, you know what, maybe this wasn't such a hot idea after all.

Looking at the amount of translation that has been done for some of the strings (e.g. `error_article_context`) about 75% of the languages have been translated for that string. And seeing error messages in your language is perhaps nicer given the amount of effort that's gone into translation already.

So how about this instead:

* Ditch the idea of separate debug strings.
* Add them back into main language files (including any that were axed as part of recent commits) but _put them in a dedicated `debug` section_.
* For languages that have yet to be translated, keeping them grouped together means it's obvious they're all only for debugging and therefore not as important to be translated.
* Recent language handling changes mean that any untranslated messages will fall back to English anyway.
* We can extract the debug messages from the currently-active language inside load_lang _only_ if production status is not Live (both public and admin sides).

Then investigate moving the lang files to an `.ini` format.

Sound good? Any better ideas?

**Comment by bloatware** [comment]
The move is motivated by the following considerations:

- These debugging messages sometimes appear amidst PHP error messages/warnings, which are (?) in English anyway.
- When asked for help on the Forum, seeing debug messages in English is nicer than Google Translate.
- Even if you don't retrieve the debug messages in Live mode, they are (currently) stored in db and slow things down. I had an idea of separating public/admin lang tables to solve this issue, but it looks complicated. This said, taking 40 strings out of about 1150 does not change anything, so this point is marginal.

**Comment by Bloke** [comment]
All good points. I agree that if PHP messages are in English (which I would expect they will be, but can't say for sure - certainly they'll not be influenced by Txp's lang settings!) then yes it makes sense to follow that tradition.

Some messages - like the `error_article_context` which is specific to Txp and not triggered by an actual PHP code error - could arguably be for "informational purposes" to help you with tag placement and therefore nicer in the target language. But, as you rightly say, it makes things harder for the community to offer assistance.

So let's disregard my above post and continue as planned:

1. Debug messages decoupled (somehow) from the lang files.
2. Investigate moving lang files to a better `.ini` format to aid translation grunt work when merging strings into core.
3. Figure out ways to make the lang string handling more efficient.

**Comment by bloatware** [comment]
Glad we agree, now go verbose in debugging!

If we consider switching to `.ini` format, imo it's better to do it in 4.7, before `.txt` lang files are officially released. If nobody fancies doing that, I can write a parser, but need an example of `.ini` file exported from Crowdin. @philwareham ?

**Comment by philwareham** [comment]
Ok leave it with me for a day or so. I’ll get back to you.

**Comment by philwareham** [comment]
Thinking further about this. There is no reason why we couldn’t split setup strings into individual .ini files. There is no reason for them to be imported into the database is there? As long as we don’t also have them in the Textpack I’m fine with that (you can have multiple files on Crowdin).

**Comment by Bloke** [comment]
If we can do the same with setup as we're planning to do with debug strings, it takes the lang file weight down a bit. And saves 3 lines of code where we test if `event === setup` and skip the row if so :-)

My only reservations are:

* Instead of just one file (like with debug, in English) we'd need a setup file per language. That doubles the number of files in there. And when pophelp gets fleshed out in other languages, that goes up again. I know it's not a massive issue, but if we're doing this we should maybe consider subdirs: either one for each different language, or one for each 'type' of file (strings, help, pophelp, etc).
* Each separate lang file probably needs to have the language markers (metadata: name, code and direction) in it so that if it's read on its own, we still know which language to attribute the content to and how to interpret it. That's duplication of effort. Not much, but it is duplication.
* If the language textpack files use the same file extension as 'special' packs such as `debug` and `setup`, we need to introduce exception processing when finding the files so we don't pick up 'partial' packs and treat them as strings (or use a separate dir structure - see above).
* What do we do with common strings? Setup does actually hold every string for the setup process, but there's no real need to if we ensure that all strings shared by "installed" core and "setup" core are in the `common` group. There's no reason we couldn't separate those out into a separate file too. It complicates matters when we "install" a language because we need to read multiple files and merge them, which increases disk activity, but it's a one-time operation per installation and enables us to possibly cut down the number of duplicate strings in the `setup` group.

Thoughts?

**Comment by philwareham** [comment]
@bloke I was thinking that the setup languages would go into `textpattern/setup/lang` actually - so they are then deleted when you delete the `setup` folder. Not added to the standard `lang` directory.

**Comment by philwareham** [comment]
Also, what strings from common are used in the setup process? I though all strings in setup were from the `@#setup` group alone?

**Comment by Bloke** [comment]
Sure, that makes sense bundling the strings in the setup folder directly. Again, we'd need meta data in each file so we can extract the available languages.

Having such a disconnect between files does slightly run the risk that we have setup strings for a language that we don't have in core, but I guess that's a corner case.

At the moment, no common strings are used in setup. That's the point: there must be some, right? Login, Password, Cancel, Go Back, Admin theme, Site theme, etc? Seems a shame to make translators duplicate them (even if it's just copying and pasting strings into a second file in setup).

**Comment by philwareham** [comment]
The setup strings would still be in our Textpack repo (and on our Crowdin project), just as separate files from the main Textpacks. So in that case no there would not be a risk of having different languages there than in the core.

**Comment by Bloke** [comment]
Cool. If it makes it leaner, then let's pull out the setup strings separately and keep them all self-contained without `common`.

When the debug messages are done and the `.ini` parser has landed to extract meta info, I can yank out the setup strings and move them back to `setup`. Does Crowdin have hooks that would enable us to automate export so we can still maintain one file there but have it spit out:

* Meta info and `[setup]` strings in one file.
* Meta info and all other strings except `[setup]` in another.

Or is it easier to manage them as separate files in Crowdin?

**Comment by bloatware** [comment]
Extracting meta from `.ini` is landed. Now I'm looking at the parser and say to myself what a wond... no, that dynamic `#@owner` and `#@language` wouldn't work with `parse_ini_file()`... Are they of any use?

**Comment by philwareham** [comment]
>  Does Crowdin have hooks that would enable us to automate export so we can still maintain one file there...

They are part of the same project but separate files (as will the pophelp when I re-add that to Crowdin.

I need to test .ini files on Crowdin so if you can extract the the en language setup strings and provide me as an ini file, I can test and supply the resulting export to Oleg.

**Comment by Bloke** [comment]
@bloatware That's a good point. When we paste language strings in, our Textpack format is still the regular `#@` format. And for good reason, because it allows plugin authors to manage their strings more easily. I think the convention going forward is that anything without an owner is a "core" string.

So we can support `.ini` files for file-based import, but for importing strings via the textbox in the Languages panel, we need to retain support for the existing format. If we can accept text pasted in as `.ini` format here too, all the better.

**Comment by bloatware** [comment]
Language and owner can be omitted in `.textpack` files as well, this is not really `.ini`-specific. They are `TEXTPATTERN_DEFAULT_LANG` and `TEXTPATTERN_LANG_OWNER_SITE` by default.

We can allow for `.ini` import via textarea, but I don't think installing multiple `.ini` files this way would be practical. So we must retain `.txt` support and not deprecate it, I guess.

**Comment by makss** [comment]
Perhaps we can develop textpack.ini in a separate branch?

What is the sense to add parsing `.ini` if there is nothing to parse? How can you be sure that parsing works correctly, if it is not checked for a full set of data?

I like the standard data and parsers, but it is advisable to first fully test them. Textpack format is not standard and not convenient. Unfortunately `.ini` format has its limitations, only two levels of nesting and quotation escaping.

**Comment by philwareham** [comment]
Ok, please branch off from dev. I’ll provide Textpacks as ini files by the end of the weekend.

**Comment by philwareham** [comment]
One more question: how are we handling special characters in these ini files? Specifically double quotes - simply change them to single quotes `'`, use the [Joomla method](https://docs.joomla.org/Creating_a_language_definition_file) of `"_QQ_"`, the backslash `\"` or something else? Note the I use curly quotes where possible in language strings (although obviously any HTML tag attributes use double quotes at the moment.

**Comment by makss** [comment]
Single quotes can be used by the language itself, for example in Ukrainian - this is part of the language.
Option with `_QQ_` looks good.

**Comment by bloatware** [comment]
It's backslash, but, the whole point being [this](https://github.com/textpattern/textpattern/issues/1002#issuecomment-344269567), you shouldn't have to care.

I have tested what I could, it works and is ready to go. Once `.ini` files are ready, please branch off and drop them in `lang` folder instead of `.txt`.

**Comment by philwareham** [comment]
Please unzip and review the following file and see if anything further needs escaping, reformatting and/or renaming. If all looks OK I'll try uploading a file to Crowdin. Thanks.
[en.zip](https://github.com/textpattern/textpattern/files/1484557/en.zip)

**Comment by bloatware** [comment]
That's crazy:

>  There are reserved words which must not be used as keys for ini files. These include: `null, yes, no, true, false, on, off, none`.

Which we use, of course.

**Comment by philwareham** [comment]
How about gettext and .po files?

http://php.net/manual/en/intro.gettext.php

**Comment by makss** [comment]
> That's crazy:

+1

I have found out experimentally that these values are parsed normally, if a space is added ahead.
File: [en.ini](http://makss.uaho.net/1/en.ini)

PHP 5.3.27 - OK
PHP 5.4.45 - OK
Need to check other versions of PHP.

**Comment by bloatware** [comment]
I don't know `gettext`, it seems that one has to restart the server every time strings are modified. This can be too restrictive, at least we (me) don't have time to check before Xmas.

@makss yes, that was my first thought (replace `null` with `null_` in textpacks), but that's not very funny for plugin authors. Another possibility is to `preg_replace` them before parsing (and than back), but I would like to see first how Crowdin exports these keys in `.ini` format?

**Comment by philwareham** [comment]
I have to have the base file (en.ini) correct before it’s brought into Crowdin - since that is how it works.

We could simply prefix any reserved words do with `txp` - that would sort the problem out?

**Comment by makss** [comment]
@bloatware , See and parse my file.

Short example:
```
[public]
null="null"
```
Error, but
```
[public]
    null="null"
```

Correct result:
```
Array
(
    [public] => Array
        (
            [null] => null
        )
)
```

**Comment by philwareham** [comment]
So indentation fixes the reserved work issue?

**Comment by philwareham** [comment]
Try this new file... 
[en.zip](https://github.com/textpattern/textpattern/files/1484984/en.zip)

**Comment by philwareham** [comment]
OK, so the Crowdin export (testing French) gives this file. It's not prefect but still a lot better than the old export (to XML) - although we'd still need to do some minor alterations to it when put into the GitHub repo. e.g. lines not indented, any untranslated strings are removed from the export.
[fr.zip](https://github.com/textpattern/textpattern/files/1484996/fr.zip)

**Comment by Bloke** [comment]
Looks ok to me after a cursory inspection. Wouldn't worry too much about leaving empties in there. The installer will skip them and replace them with fallback strings. The only downside is file size.

**Comment by philwareham** [comment]
Ok just need to hear from Makss and Oleg, then I can split out setup strings and upload both files to Crowdin. When we do have empty strings in the base file (I.e. strings have been added but nobody has written text yet) do you want to show as `newstring=` or `newstring=""`?

**Comment by bloatware** [comment]
I know a leading space works, but don't think we should do it this way. How to explain to plugin authors that they can use `null` in `.txt`, but must prefix it with a space (or `txp-`) in `.ini`? Leave me few minutes, I will try to fix it.

Re ` newstring=` vs `newstring=""` - the second one, otherwise those filling these strings by hand could forget to quote them.

**Comment by philwareham** [comment]
Agreed, using forced indentation seems hacks to me, would prefer a proper fix.

**Comment by bloatware** [comment]
A [branch](https://github.com/textpattern/textpattern/tree/textapcks-ini) created (sorry for `textapcks` :-), with unhacked `en.ini`, please test.

**Comment by Bloke** [comment]
Nice workaround, Oleg!

**Comment by philwareham** [comment]
@bloatware I'd rather keep them separated files as I have just done. There is no additional work to keep them in sync on Crowdin as they are simply grouped together within a language. See: https://crowdin.com/project/textpattern-cms-textpacks/sv-SE# (note that the old 'Textpack.xml' will be replaced with a 'Textpack.ini' once I know the format is correct).

**Comment by Bloke** [comment]
> would these separate setup files also need a [meta] section?

Yes. Please include `[@common]` section at the top, as we need it to render the initial dropdown list of available languages.

**Comment by bloatware** [comment]
> would these separate setup files also need a [meta] section?

That's what's worrying me, since it must be in sync with the main `lang` files. But if one does not have to do it manually, it's ok.

**Comment by philwareham** [comment]
It’s fine, I’ll amend with `[@common]` and keep them as 2 files as I planned.

**Comment by philwareham** [comment]
Issue ready to close?

**Comment by Bloke** [comment]
I think so. I'd rather put the debug language strings in the `lang` directory than in the main `textpattern` directory, but we'd have to give it a different file extension or modify our regex to only `glob` for files that fit a tighter pattern.

**Comment by philwareham** [comment]
@bloke I think @bloatware mentioned that this file might one day contain more than debug messages - hence why I have renamed it to a non-specific name of `mode.ini` and left it in `textpattern` directory. Feel free to amend if you feel a better alternative can be used.
