### ISSUE TITLE
"Deal w/ nested <txp:article[_custom]> tags" in `txplib_publish.php`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1009]
**Background**
This issue is part of a project (https://github.com/textpattern/textpattern/issues/1004) to migrate inline TODOs to GitHub issues. If this issue is still relevant, please assign milestone(s) and team member(s) accordingly.

On acceptance as a valid issue, the code should be annotated with a comment pointing back to this issue.

On completion of the issue, the code should be updated to remove the comment and the pointer to the issue.

**TODO and surrounding code**
https://github.com/textpattern/textpattern/blob/dev/textpattern/lib/txplib_publish.php#L855

```php
/**
 * Save and retrieve the individual article's attributes plus article list
 * attributes for next/prev tags.
 *
 * @param   array $atts
 * @return  array
 * @since   4.5.0
 * @package TagParser
 */

function filterAtts($atts = null)
{
    global $prefs, $trace;
    static $out = array();

    if (is_array($atts)) {
        if (empty($out)) {
            $out = lAtts(array(
                'sort'     => 'Posted desc',
                'keywords' => '',
                'expired'  => $prefs['publish_expired_articles'],
                'id'       => '',
                'time'     => 'past',
            ), $atts, 0);
            $trace->log('[filterAtts accepted]');
        } else {
            // TODO: deal w/ nested txp:article[_custom] tags.
            $trace->log('[filterAtts ignored]');
        }
    }

    if (empty($out)) {
        $trace->log('[filterAtts not set]');
    }

    return $out;
}
```

**Comment by bloatware** [comment]
I don't think this is still an issue: `<txp:article />` can not be nested, and `<txp:article_custom />` does not use this function. Leave it as is, just in case?

**Comment by Bloke** [comment]
Yeah, let's leave this alone. Nesting article tags is messy at best. If it is ever necessary we should design around it.

**Comment by petecooper** [comment]
Thank you - closing.
