### ISSUE TITLE
[inline TODO] Optimise language loader in `textpattern/index.php` to reduce expense of loading twice

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1010]
**Background**
This issue is part of a project (https://github.com/textpattern/textpattern/issues/1004) to migrate inline TODOs to GitHub issues. If this issue is still relevant, please assign milestone(s) and team member(s) accordingly.

On acceptance as a valid issue, the code should be annotated with a comment pointing back to this issue.

On completion of the issue, the code should be updated to remove the comment and the pointer to the issue.

**TODO and surrounding code**
https://github.com/textpattern/textpattern/blob/dev/textpattern/index.php#L168

```php
    // Initialise global theme.
    $theme = \Textpattern\Admin\Theme::init();

    include txpath.'/include/txp_auth.php';
    doAuth();

    // Add private preferences.
    $prefs = array_merge(get_prefs($txp_user), $prefs);
    extract($prefs);

    $dbversion = $version;

    // Reload string pack using per-user language.
    $lang_ui = (empty($language_ui)) ? $language : $language_ui;

    // Loading langs twice is expensive, so only do it when necessary.
    // @todo Optimisations to language loader will help here.
    if ($lang_ui !== $language) {
        $textarray = load_lang($lang_ui);
    }

    /**
     * @ignore
     */

    define('SITE_HOST', (string) @parse_url(hu, PHP_URL_HOST));

    /**
     * @ignore
     */
```

**Comment by philwareham** [comment]
Is this done now? I know there was further work on lang optimisation recently?

**Comment by Bloke** [comment]
Nope, but if there's any life to be had here, it'll require some extensive refactorisation of our bootstrap process which I'd like to leave for a future release.

**Comment by petecooper** [comment]
Closing for now - see https://github.com/textpattern/textpattern/issues/1004#issuecomment-353670101
