### ISSUE TITLE
[dev] parse error while trying to install a plugin

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1020]
PHP version: 5.5.38

STR
1. Plugin panel, paste the code for a plugin
2. Press Upload (preview OK), press Install

AR: a blank page wit a friendly  PHP message 

```
Parse error: parse error, expecting `')'' in /Users/username/Sites/_txp472/textpattern/vendors/Textpattern/Textpack/Parser.php on line 101
```

**Comment by bloatware** [comment]
Thanks @phiw13, I've forgotten to fix it on dev, done now.

**Comment by phiw13** [comment]
Works fine now :-). Closing.
