### ISSUE TITLE
Include database vendor in Diagnostics panel

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1028]
There are some minor (and not so minor) differences between the implementations of MySQL, and it's useful when troubleshooting to know the vendor of the MySQL (or equivalent) installed. I'm thinking about MariaDB, Percona and other drop in replacements.

In Percona, there's a variable `version_comment`:

```
version_comment	Percona Server (GPL), Release 71.0, Revision 726
```

Proposal: include the output of the `version_comment` if it exists.

If this is worthy of inclusion, I see a couple of options:

* append the MySQL version with the vendor info (for example: `5.6.22-71.0 (Percona Server (GPL), Release 71.0, Revision 726)`
* add another line under or near the MySQL version number currently in Diagnostics

**Comment by makss** [comment]
Check, please.

**Comment by petecooper** [comment]
Thank you, @makss - I'll test this in about 5 minutes and report.

**Comment by petecooper** [comment]
Perfect. Thanks @makss!
