### ISSUE TITLE
List options: disabled state accessibility improvement for the menu items.

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1029]
Is it possible to add the class `ui-state-disabled` to the `<li />` when the contained checkbox is `disabled` ?

See the example: https://jqueryui.com/menu/#default – they add the `ui-state-disabled` class to the HTML source and the script takes it from there.

This has a couple of benefits: JQ-ui script then adds the `aria-disabled` attribute (for screen readers), the item is skipped when using the arrow keys to move up/down (and the item is styled as disabled - greyed out).

If that is hard to do, would it possible to add the class `disabled` to either the parent `<label />` or its parent `<div />` (when the checkbox is disabled)? That is less ideal for AT, but at least it would be possible to style the item (text) to “look” disabled. AT will still know that the checkbox is disabled.

**Comment by bloatware** [comment]
[Done](https://github.com/textpattern/textpattern/commit/6e0a795a0552a2c992803a0d48bbc86ab1281f27), please test.

**Comment by phiw13** [comment]
Works quite well, thank you!

(I am a little puzzled that the disabled item is not skipped when using the up/down arrows, but on double checking the JQUI sample on their site, it does the same. So, OK… clicking / key press are killed which is the important thing here. Maybe a little tweak in the stylesheet might improve things visually for that case, gone think about it).

Closing.
