### ISSUE TITLE
Empty txp_lang items cause load_lang_event to fail

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#103]
_From [r.wetzlmayr](https://code.google.com/u/r.wetzlmayr/) on January 17, 2011 08:32:11_

== Symptom ==

jsoo reports at http://forum.textpattern.com/viewtopic.php?id=35305 :

The problem is that an empty (no name) item in txp_lang causes load_lang_event() to think that the language is not installed, so it defaults to en-gb.

== Reason ==

Languages on rpc.textpattern.com erroneously contain rows with empty 'name' columns. These are mirrored to individual RPC client sites via the language update mechanism.

== Solution ==

Defend against invalid langueage entries at all steps involved: 

* At the RPC server: Perform cleanup and reject future invalid data
* At the RPC client: Reject invalid data
* At the app core: Defensive use of language data

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=99_

**Comment by Bloke** [comment]
Closed by 33ac470979dd9fd854e7a1eef72160aa1dbfbcaf
