### ISSUE TITLE
Image upload thumbnail and mime type shown, Classic theme on 4.7.0-dev

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1030]
Background: using current 4.7.0-dev, tagged with `a435c4f6eec34c6f85fc2f5d083e9825` if that helps. I can't see where the Classic theme lives (does it have its own repo?), so I'll put this here and move if needed.

Classic theme, Image panel. Starting with zero images and adding the first. Use the `Choose Files` button, I select a single .png file from my computer, a thumbnail appears instantly with a faint overlay with the mime type and number of bytes. On hover, the mime type and byte count disappear.

On uploading, the progress bar clashes with the thumbnail, overlapping or underlapping it. After the upload is complete, the thumbnail remains as the image filename is persistent in the `Choose Files` area.

This only happens with Classic theme, though the filename is persistent across Hive & Classic.

*Arm the uploader*

![screen shot 2017-11-26 at 15 46 01](https://user-images.githubusercontent.com/226578/33241715-85d37d92-d2c1-11e7-8e64-c9b5727a2e43.png)

*Start the upload*

![screen shot 2017-11-26 at 15 46 45](https://user-images.githubusercontent.com/226578/33241716-8c643174-d2c1-11e7-970a-6710de281337.png)

*Upload completes*

![screen shot 2017-11-26 at 15 46 46](https://user-images.githubusercontent.com/226578/33241719-95c7d50e-d2c1-11e7-83d4-cbeec7d0c13c.png)

*Image is managed, filename and thumbnail remain*

![screen shot 2017-11-26 at 15 47 50](https://user-images.githubusercontent.com/226578/33241723-a3b1dcb4-d2c1-11e7-8068-76c66ccee079.png)

**Comment by philwareham** [comment]
I've not tested the multi-file upload feature yet (it's on my TODO list) for any styling amends. But, I thought we were not going to show any thumbnails at upload for now - just the progress bar? @bloatware can you confirm? Cheers.

**Comment by petecooper** [comment]
![re](https://user-images.githubusercontent.com/226578/33265103-3d710360-d368-11e7-813c-40d5a9d1081d.png)


@philwareham - here's the code from the inspector, if that helps hide with CSS:

```
<div class="preview"><input name="title[be3ee0c9e01c742f6b99a4d44e5337be]" value="20275e"><div class="info ">image/jpeg (69041 B)</div><img src="blob:http://dev-demo.textpattern.co/4780af7c-51cf-41fb-8329-a1b9cfdbab12"></div>
```

**Comment by philwareham** [comment]
Thanks. I'd prefer the HTML isn't generated in the first place rather than hide with CSS though. Will investigate once other tasks I have are complete.

**Comment by phiw13** [comment]
I thought thumbnail preview would be optional (for now?) - Oleg put some sample template in the Classic theme as an example.
@philwareham - Just remove the prefs.json file from the theme

**Comment by philwareham** [comment]
Ah OK, thanks Philippe. As I say I've not tested the uploader whatsoever since it's current iteration. Good to know.

Thumbnails I *may* activate in 4.8 if they work well enough (and tie in with our image grid work). Just not enough time left in 4.7 dev cycle to test this thoroughly.

**Comment by bloatware** [comment]
That's right, `prefs.json` is optional, mainly intended for tweaking by theme authors. But it includes a handy feature for multiuploads: files title field and invalid size alert. Dunno what to do with it in 4.7, ready to amend it if necessary.

**Comment by phiw13** [comment]
> But it includes a handy feature for multiuploads: files title field and invalid size alert.

Yes, that is the thing that interest me most, It gives a quick way to tell you which files are too big. I just did a test with my dummy site on Dreamhost, uploading 3 files, one of which is (just) over the server limit the two others just under it. Without preview box, you get successive messages for each upload, but they (quickly) overwrite each other. If you don’t pay enough attention, you’ll miss the message for the failed upload(s). 

@philwareham 

It looks like [this Sandspace mockup](https://dev.l-c-n.com/txp/txp-content-file_uploadpreview.html), still a bit WIP.

**Comment by bloatware** [comment]
> ... uploading 3 files, one of which is (just) over the server limit the two others just under it.

BTW, one can go beyond the server limits now, just increase the max file size pref.

> Without preview box, you get successive messages for each upload, but they (quickly) overwrite each other.

The expected behavior is *two* messages: the first one for all oversized files before upload start, the second one for all uploaded files on upload end.

**Comment by phiw13** [comment]
> BTW, one can go beyond the server limits now, just increase the max file size pref.

Yes, I know… but for the purpose of illustration of the issue, the default on that dummy install is fine

> The expected behavior is two messages: the first one for all oversized files before upload start, the second one for all uploaded files on upload end.

See, you show why that preview box is useful! It went all too fast… I barely had time to see the first message (I have a 1GB pipe, uploading a 2MB file goes just poof).

**Comment by philwareham** [comment]
OK, I've removed the `pref.json` file for now, which fixes the specific issue. I will try to find time before the 4.7 beta to test and style the preview box so we can get it back into 4.7 in good condition.
