### ISSUE TITLE
Admin themes at setup: should be defaulting to Hive

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1034]
### Expected behaviour

When doing initial setup, the default selected admin theme should be 'Hive'.

### Actual behaviour

Currently it's using 'Classic' erroneously. Also Classic should be labelled as a core admin theme.

### Steps to reproduce

Run setup.

**Comment by makss** [comment]
[Done](https://github.com/textpattern/textpattern/commit/8ee8a012708afa8225c7c870e002a283f0d0301b), please test.

**Comment by philwareham** [comment]
Great! Working as expected now thanks. Closing.
