### ISSUE TITLE
Styling of uploader widget

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1044]
Note to self that I need to check the styling of the current (and proposed) file uploader and adjust admin theme CSS accordingly, before 4.7 beta.

See here for some further history: https://github.com/textpattern/textpattern/commit/b319df3680ecbf482f58f7ef91aff544b06b90bf#commitcomment-25527805

**Comment by philwareham** [comment]
Styled now. There is some content jumping when the scrollbar appears but I think that's OK. Closing.

**Comment by bloatware** [comment]
Nice! If jumping is annoying, we can toggle `disabled` class on upload progress instead of hiding it.

**Comment by philwareham** [comment]
I think in this case content jumping is OK. I'd rather, when navigating through panels and not uploading files, that the lists al render in the same consistent position. So no further work needed. Cheers!
