### ISSUE TITLE
Textpack repo structure changed - build script needs amending

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1047]
Hi @makss - I have now updated the Textpack repo to house the new INI files. The two directories of note are...

`lang`
`setup-lang`

...which replace the old `textpacks` directory. Can you please amend the `get-textpacks.sh` script according so that it pulls both directories and puts the files in the correct places on the textpattern repo? Cheers!

**Comment by makss** [comment]
[Done](https://github.com/textpattern/textpattern/commit/4151ea36f6a1a6d013669c6fda18df4d99144b76), please check.

**Comment by philwareham** [comment]
Works! Thanks makss. Closing.
