### ISSUE TITLE
[UX] Fat fingers on Image/File upload, multiple copies uploaded

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1048]
### Expected behaviour

File and Image uploading should send file(s) once.

### Actual behaviour

File and Image uploading sends file(s) more than once with double & multiple clicks/taps.

### Steps to reproduce

Background: I was watching two clients trial Textpattern today and noticed them double clicking on all the links in the admin on 4.6.2. I watched them do the same thing on their existing (Drupal) site.

If I arm the File or Image uploader with a file, then double click the Upload button, it spawns two upload processes, ending up with a duplicate file (different IDs, as expected).

Attached file is a double-clicked Upload button with a single image recorded as a realtime (safe for work) video. The upload speed is slow because…well, my internet is slow.

Solutions:
* Clear the file name from the Choose Files area when the upload starts.
* Disable the upload button while files are uploading.

[FinderScreenSnapz001.mov.zip](https://github.com/textpattern/textpattern/files/1518991/FinderScreenSnapz001.mov.zip)

**Comment by bloatware** [comment]
Thanks @petecooper, patched in 4.7, will commit soon.

**Comment by bloatware** [comment]
Done in 4.7, don't think there will be a 4.6.3... closed?

**Comment by petecooper** [comment]
Perfect - thanks very much, @bloatware!
