### ISSUE TITLE
[inline TODO] serving non-utf8 content as utf8 in `/rpc/TXP_RPCServer.php`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1052]
**Background**
This issue is part of a project (https://github.com/textpattern/textpattern/issues/1004) to migrate inline TODOs to GitHub issues. If this issue is still relevant, please assign milestone(s) and team member(s) accordingly.

On acceptance as a valid issue, the code should be annotated with a comment pointing back to this issue.

On completion of the issue, the code should be updated to remove the comment and the pointer to the issue.

**TODO and surrounding code**
https://github.com/textpattern/textpattern/blob/dev/rpc/TXP_RPCServer.php#L307

```php
    // Override default UTF-8 output, if needed.
    function output($xml, $enc = 'utf-8')
    {
        // Be kind with non-UTF-8 capable clients.
        if ($enc != 'utf-8') {
            if ($enc == 'iso-8859-1' && function_exists('utf8_decode') && is_callable('utf8_decode')) {
                $xml = utf8_decode($xml);
            } elseif (function_exists('mb_convert_encoding') && is_callable('mb_convert_encoding')) {
                $xml = mb_convert_encoding($xml, $enc, 'utf-8');
            } else {
                // TODO: shouldn't this throw an error instead of serving non-UTF-8 content as UTF-8?
                // If no decoding possible, serve contents as UTF-8.
                $enc = 'utf-8';
            }
        }
        $xml = '<?xml version="1.0" encoding="'.$enc.'" ?>'.n.$xml;
        $length = strlen($xml);
        header('Connection: close');
        header('Content-Length: '.$length);
        header('Content-Type: text/xml charset='.$enc);
        header('Date: '.date('r'));
        echo $xml;
        exit;
    }
//------------------------------------------
```

**Comment by philwareham** [comment]
To be honest the RPCserver is obsolete. In a future release we should scrap it and use a modern API like the great [GraphQL](http://graphql.org). I think any TODO issues related to RPCserver should be closed and no further work done on that code (unless it's a super-quick east fix). @bloke @makss @bloatware thoughts?

**Comment by Bloke** [comment]
I concur.

**Comment by petecooper** [comment]
Alright. For what it's worth, I completely agree.

Proposal: officially deprecate/end-of-life XML-RPC in 4.7.0, let's start the ball rolling.

**Comment by petecooper** [comment]
Closing, pending merge of https://github.com/textpattern/textpattern/pull/1056
