### ISSUE TITLE
BlueIMP file uploader as NPM dependency

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1054]
The BlueIMP file uploader should be brought in as NPM dependency, like we already do for jQuery. Also means we can version track it.

**Comment by bloatware** [comment]
Sorry, I don't know what NPM dependency is  and why should we use it.

**Comment by philwareham** [comment]
@bloatware basically, I’m going to need to know where the original script for md5 lives and if you minified the NlueIMP script yourself or that lives somewhere.

**Comment by makss** [comment]
Done, please check.

**Comment by philwareham** [comment]
Cheers @makss - and you've concatenated md5 into the minified script, perfect! Will test it now,

**Comment by philwareham** [comment]
Works in my testing, thanks! Closing.
