### ISSUE TITLE
Expose `enable_short_tags` pref?

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1061]
Since 4.6 the parser processes short `<abc::tag />` as `<txp:abc_tag />`, though nobody seems have ever noticed it. In 4.7 this facility is extended to any length prefixes (e.g. `<article::id />` for `<txp:article_id />`) but disabled by default to avoid a (small) performance penalty. I think we should expose `enable_short_tags` preference to site admins but am not sure which parts of code must be modified. A new language string should be added too. @Bloke @makss @philwareham?

Note that `<txp::shortcode />` (interpreted as `<txp:output_form form="shortcode" />`) works by its own and does not depend on short tags pref.

**Comment by Bloke** [comment]
I'm for this.

Presumably introducing the pref itself will have a (tiny) performance penalty insofar as the parser would need to check if the pref was set before permitting the tag to be parsed, right? And that's a constant-time penalty because it needs to perform the check, even to determine if the setting is off!

But if the benefit of having a toggle outweighs the performance penalty of enabling it by default, then a pref is the right way to go. I can add the pref if you like, for you to hook up to the parser.

**Comment by bloatware** [comment]
Oh, it's just one extra `isset()` check (already done anyway) of a static variable, must account for 0.01% parse time perhaps. The main penalty comes from switching from `strpos()` to `preg_match()` when detecting tags presence, but it's marginal too.

Yes, please add the pref where you deem it to fit, the parser is ready. Thanks!

**Comment by Bloke** [comment]
Awesome. Will do.

**Comment by Bloke** [comment]
Just out of curiosity, does this only work for tags that contain underscores? Or do single-word tags like `<txp:body>` 'shorten' to `<body::>`?!

**Comment by bloatware** [comment]
Hehe, no, `<body:: />` is not a tag atm, but it's yet time. Yes, `::` is merely replaced with `_`, so we get a bunch of `<if::something />`.

**Comment by Bloke** [comment]
How's this for the help text? Any improvements or better examples?

----

<h2>Enable short tags</h2>
<p>Textpattern tags take the form <code>&lt;txp:tag_name attribute1="value" ... /&gt;</code>. It is possible to reduce the amount of typing involved by enabling a shorthand notation whereby the 'txp:' may be omitted by following a few simple guidelines. Here are some examples to demonstrate the concept:</p>
<ul>
    <li><code>&lt;txp:article_id /&gt;</code> becomes <code>&lt;article::id /&gt;</code></li>
    <li><code>&lt;txp:recent_articles/&gt;</code> becomes <code>&lt;recent::articles /&gt;</code></li>
    <li><code>&lt;txp:file_download_list /&gt;</code> becomes <code>&lt;file::download_list /&gt;</code></li>
    <li><code>&lt;txp:smd_if /&gt;</code> becomes <code>&lt;smd::if /&gt;</code></li>
</ul>
<p>If a tag contains an underscore and you enable short codes, the basic concept is:</p>
<ol>
    <li>Remove the <code>txp:</code> prefix.</li>
    <li>Swap the first occurrence of the underscore for <code>::</code>.</li>
    <li>Profit</li>
</ol>
<p>Note that setting this preference in no way affects the ability to use <code>&lt;txp:output_form /&gt;</code> short codes to render form snippets. You must still always use <code>&lt;txp::shortcode /&gt;</code>, which will be interpreted as <code>&lt;txp:output_form form="shortcode" /&gt;</code>.</p>

**Comment by Bloke** [comment]
I think all that's required is [this](941bec36). Log out and back in to resync prefs. We can add the lang string and pophelp later.

**Comment by bloatware** [comment]
Fine by me! Just replace `You must still always use...` with `You can still use...` (shortcode) perhaps? And add a `<short::else />` example:
```
<smd::if> ... <smd::else /> ... </smd::if>
```

**Comment by Bloke** [comment]
Updated, thanks.

**Comment by bloatware** [comment]
Magic! Log out, log in, and it's there, working. Many thanks @Bloke, now we miss just the string. Or could it be a combination of `use` and `<short::tags />`? Problematic in RTL probably...

**Comment by Bloke** [comment]
@philwareham Would you like me to add the pref text above to the `en_pophelp.xml` in the textpack repo? Or shall I hold off until you get Crowdin reconfigured?

**Comment by philwareham** [comment]
For the moment is should go in the pophelp repo not the Textpack repo. Thanks.

**Comment by Bloke** [comment]
Ugh, that's what I meant sorry. In git as opposed to waiting for Crowdin, is what I was kinda implying. I'll add it to the pophelp repo.

**Comment by Bloke** [comment]
This is interesting. Kind of expected when you think about it, but at first it made me go "what?"

On a page/form:
``` html
<txp:variable name="testing" value="yes" />
<smd::if field="txpvar:testing" value="yes">
Oh yeah!
<smd::else />
Oh no!
</smd::if>
````
With short tags on, I see `Oh yeah!`
With short tags off, I see `Oh yeah! Oh no!`

In the second case when it's not parsing the short codes, it silently skips them, thus rendering both true and false containers.

Guess there's nothing can be done about this. It just means that if theme authors use short tags in their template code, they'll need to make it clear in the README that the pref needs to be switched on, or the person installing their theme is gonna get a surprise!

When we build in support for bundling optional prefs (uhhh, somehow, no idea how yet), this issue might be lessened to a degree.

Anyway, it seems to work really well, thanks. I've added the string and pophelp in the `lang-on-demand` branch ready for merge so if you're happy with that, we can close this issue. Let me know if I've missed anything.

**Comment by bloatware** [comment]
Short tags are @vanmelick idea and implementation, I take no merit here. I concur switching the pref may break the site, but it's true for "alllow php/plugins/etc" too. Theme authors shouldn't use short tags, that's all. Or programmatically change the pref. Or we enable them once for all and basta, nobody seems to be affected by their silent presence in 4.6. Forum poll?

**Comment by Bloke** [comment]
Yes, true about the PHP prefs. Hand't thought of that.

I don't mind, it's just something to be aware of. If nobody's noticed so far and the parser is blazingly quick anyway, then... well maybe no pref is better after all. "Always on" means no fuss, and no support questions about "my site is broken" in relation to tag short codes.

Sure, ask on the forum/G+. Give some numbers to back it up if you can. Point out that nobody's noticed so far and the feature's been available for over a year! See what the consensus is.

**Comment by bloatware** [comment]
I have not measured the performance impact, just saying to myself that searching for `<txp:` must be faster than `<\w+:` if the thing contains many HTML `<long_tags />`. Ruud spoke about 10% slowdown AFAIR, but it should be less in the real life. Let's leave a pref, at least it reminds that the feature is there. :-)

**Comment by bloatware** [comment]
Thanks to all, closing.
