### ISSUE TITLE
Existing files `select` tag - non-multi select if single item

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1062]
The `select` tag used to select existing files and bring them into the files panel has recently been changed to a `select` `multiple` type UI. This kind of makes sense now that multiple files can be uploaded at once to the system. However the `select` `multiple` renders even if only a single file is detected.

IMHO a `select` `multiple` doesn't provide better UX if single, or even up to about 3, files are detected. In that situation I feel a standard `select` is better (in fact, there's been many articles written about the bad user experience of multi select form elements). If a way can be found of detecting how many files are to be listed, and providing either `select` or `select` `multiple` based on that - that would be my preferred UX solution here.

**Comment by bloatware** [comment]
I can revert it back to single, no worries. Switching between single and multiple depending on the files number is easy too, but less consistent. Go?

**Comment by philwareham** [comment]
I can see why having a multi select field would be handy if say, 5 or more files are detected (because you can click in the field and do a 'select all') so if it can go to multi select on 5 or more files that would be good I think.

**Comment by bloatware** [comment]
[Done](https://github.com/textpattern/textpattern/commit/413d4284dcb84686ab70fb573cd39f0ff5514027)

**Comment by philwareham** [comment]
Great, thanks Oleg! Closing.
