### ISSUE TITLE
Regression: search widget displayed on images/files panels even when no items

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1063]
### Expected behaviour

If you have not uploaded any items to a panel, the search widget should not display.

### Actual behaviour

On the images and files panels (all other panels seem to work as intended) even if there are no items in the database, the search widget shows. It shoudn't.

### Steps to reproduce

Either clean install, then check either of those panels. Or delete all images/files from the panel.

**Comment by Bloke** [comment]
[Hello search block always rendered](https://github.com/textpattern/textpattern/commit/da7a301aa2e5de7e22a5b9210b93382a6ddb8848#diff-87be22c53ff38784048b49cd4eea7edeR255).
@bloatware ??

**Comment by bloatware** [comment]
It's a consequence of async lists update. If we don't output the search block on empty lists and upload some images/files, it will not appear until a page refresh. Your choice, but the easiest solution is to CSS hide it, imo.

**Comment by philwareham** [comment]
OK, we can hide it with CSS - I'd just need to know what class name to hook a rule into (or if you can inline `style="display:none;"`if you wish - probably easier).

**Comment by Bloke** [comment]
Hiding's fine when there are no assets. Whichever way makes it work best all round.

**Comment by bloatware** [comment]
Hmm, not that easy, there is no mean to distinguish between "no records" and "no search results" cases in pure CSS (and even). They both produce
```
<p class="alert-block information"> ... </p>
```
I can try to inject some JS in the table block, but don't like the idea from the start. Is this issue really annoying?

**Comment by philwareham** [comment]
It's not annoying, just inconsistent with the behaviour of other panels. Is there no way to check whether the database table is empty asynchronously?

**Comment by bloatware** [comment]
I can try, but this alone would not avoid inconsistency: only articles/images/files lists are currently async. I wanted to do it for all list panels, but was stopped by the code redundancy. There should be a more structured way for this, dunno.

**Comment by Bloke** [comment]
If something needs to change to make it consistent, do it. The panels will all be overhauled and separated into data/display in some future version when the widget library is rock solid, so anything we need to do to make the panels more consistent will help us build a system based on templates.

**Comment by bloatware** [comment]
> If something needs to change to make it consistent, do it.

Wish I knew how :-) The admin side is sometimes so not MVC that you can only rewrite the code from the scratch. Too late for 4.7 and we'll need to rethink it in 4.8 custom fields anyway.

**Comment by Bloke** [comment]
Yeah, the lack of MVC has held us back for a while, but I can see a way out now (finally) in future versions. The Modules that makss proposes will help. And we can build a framework for different types of pages (tabular, individual edit page, etc) and extend a base panel to benefit from OO / Interfaces.

For now, dunno. If there's a quick win to make the search consistent or hide the search on "empty" panels, take it. If not, we'll live with it this release and revisit it when we refactor the admin panels in future.

**Comment by bloatware** [comment]
Yes, will patch.

**Comment by bloatware** [comment]
Should be [fixed](https://github.com/textpattern/textpattern/commit/427203a1114787f9eee3dc6c01f38ee310718a0e) now.

**Comment by philwareham** [comment]
Yep, working for me now in tests. Cheers Oleg! Closing.
