### ISSUE TITLE
RTL languages, diagnostics panel: markup visible around LTR strings

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1066]
For those languages some strings are wrapped in a tag e.g. `<bdi dir=LTR>Textpattern</bdi>`. This is outputted as plain text (not rendered) inside the  textarea. Because it is a `textarea`.

Screenshot below, I have highlighted some samples:

![diagnostics](https://user-images.githubusercontent.com/8944809/33873905-267009b4-df60-11e7-8015-7f621d8c4024.png)

**Comment by philwareham** [comment]
Thanks Philippe, think  have caught all these now.
