### ISSUE TITLE
[themes, UX] Themes list options has no mandatory items

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1074]
### Expected behaviour

At `/textpattern/index.php?event=skin`, select list options, toggle all unselected, `name` should be mandatory/greyed out.

### Actual behaviour

`name` is not mandatory, and so an empty row is possible.

The other list options dialogs I checked have at least one mandatory item, the most straightforward being `name`.

![screen shot 2017-12-23 at 16 23 59](https://user-images.githubusercontent.com/226578/34321051-d72ebfe8-e7fd-11e7-94cd-bc5d4dc19bc1.png)

![screen shot 2017-12-23 at 16 24 06](https://user-images.githubusercontent.com/226578/34321052-da5e1268-e7fd-11e7-8e5c-823e23a31e81.png)

**Comment by bloatware** [comment]
Should be [fixed](https://github.com/textpattern/textpattern/commit/742a08d8c73304072fed54683739f9b0ac0227b0), but we must really tighten these tables construction.

**Comment by petecooper** [comment]
Thanks @bloatware -- demo site is set to rebuild in 13 minutes, assuming all is fixed I will self-close shortly.

**Comment by petecooper** [comment]
Perfect - fixed, thanks again @bloatware.

![screen shot 2017-12-23 at 17 01 15](https://user-images.githubusercontent.com/226578/34321277-f42c9e8a-e802-11e7-8e0e-421fc2619d9f.png)
