### ISSUE TITLE
Fatal PHP error on Admin > Preferences

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1075]
STR (the steps that brought me to this at least)

1. set up a site with txp47dev up to date. On the first screen, choose French as language. On the last screen I selected my own admin theme.
2. login
3. (at this point I went to the themes panel and imported a theme, and duplicated it)
4. Go to admin > preferences panel.

Note: my `config.php` has this line: `define('TEXTPATTERN_DEFAULT_LANG', 'fr');`

result:

```
Fatal error: Call to a member function xpath() on a non-object in /Users/username/Sites/_txp472/textpattern/vendors/Textpattern/Module/Help/HelpAdmin.php on line 89
```

**Comment by Bloke** [comment]
Coding assumption should be fixed now.

**Comment by phiw13** [comment]
Indeed, this [commit](https://github.com/textpattern/textpattern/commit/fd2ca639f682252e6bfb241fbf6bfce33322ca34) resolved this. Closing.
