### ISSUE TITLE
Numeric theme/skin name throws 3x `User_Error "[name] is not a string.".` dialogs

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1077]
(Using current 4.7.0-dev version as of issue timestamp.)

### Expected behaviour

A theme/skin name should be able to begin with a number (for example, `2018`) without raising an error, _OR_ be prevented from being created in the first place.

### Actual behaviour

A theme/skin name is not currently able to begin with a number without scary errors being thrown. Subsequent navigation within the theme details page, and attempts to delete are met with `User_Error "[name] is not a string.".` errors, and confusing admin-side notifications. Additionally, some text formatting goes wonky (size increases), but this is resolved by a page refresh.

Duplicating a numerically-named theme throws additional dialogs, including `Warning "Invalid argument supplied for foreach()".`.

### Steps to reproduce

* visit `/textpattern/index.php?event=skin&step=edit` to create a new theme/skin
* enter a theme/skin name comprising numbers, e.g. `123`
* fill in the remaining fields
* select Save button
* note 3x `User_Error "[name] is not a string.".` dialogs, UI error notifications, and increased size of text
* select the newly-created numerical-name, select Duplicate from the dropdown, confirm duplication
* note 3x `User_Error "[name] is not a string.".` dialogs, 3x `Warning "Invalid argument supplied for foreach()".` dialogs, 1x `User_Error "[name] is not a string.".` dialog, 3x `Warning "Invalid argument supplied for foreach()".` dialogs, 1x `User_Error "[name] is not a string.".` dialog and 2x `Warning "Invalid argument supplied for foreach()".` dialogs.
* return to Themes list, note zero inherited Pages, Forms and Styles.

Safe for work video (with scintillating late-night commentary by yours truly) attached as a .zip file.

[textpattern 1077.mp4.zip](https://github.com/textpattern/textpattern/files/1592254/textpattern.1077.mp4.zip)

**Comment by Bloke** [comment]
Should be fixed now. Please check.

**Comment by petecooper** [comment]
Fixed - perfect! Thanks @Bloke!
