### ISSUE TITLE
`Uncaught error` on Pages, Forms and Styles

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1078]
(Using current 4.7.0-dev version as of issue timestamp.)

### Expected behaviour

Pages, Forms and Styles should be viewable.

### Actual behaviour

Visiting Pages, Forms and/or Styles throws an error.

#### Pages error
`Fatal error: Uncaught Error: Call to undefined function mb_substr() in /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/lib/txplib_misc.php:2272 Stack trace: #0 /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/include/txp_page.php(130): sanitizeForTheme('') #1 /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/include/txp_page.php(50): page_edit() #2 /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/index.php(230): include('/var/www/vhosts...') #3 {main} thrown in /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/lib/txplib_misc.php on line 2272`.

#### Forms error
`Fatal error: Uncaught Error: Call to undefined function mb_substr() in /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/lib/txplib_misc.php:2272 Stack trace: #0 /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/include/txp_form.php(315): sanitizeForTheme('') #1 /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/include/txp_form.php(83): form_edit() #2 /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/index.php(230): include('/var/www/vhosts...') #3 {main} thrown in /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/lib/txplib_misc.php on line 2272`

#### Styles error
`Fatal error: Uncaught Error: Call to undefined function mb_substr() in /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/lib/txplib_misc.php:2272 Stack trace: #0 /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/include/txp_css.php(168): sanitizeForTheme('') #1 /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/include/txp_css.php(50): css_edit() #2 /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/index.php(230): include('/var/www/vhosts...') #3 {main} thrown in /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/lib/txplib_misc.php on line 2272`

### Steps to reproduce

* visit Presentation -> Pages, Presentation -> Forms or Presentation -> Styles and note the error.

Safe for work video and commentary attached in .zip file.

[textpattern 1078.mp4.zip](https://github.com/textpattern/textpattern/files/1592278/textpattern.1078.mp4.zip)

**Comment by Bloke** [comment]
Fixed. Sort of.

For completeness we should probably use our built-in `Type/StringType.php` handler for this. Watch this space.

**Comment by petecooper** [comment]
Confirmed fixed (at least on demo site). Many thanks @Bloke!

**Comment by Bloke** [comment]
OK, we're now using the built-in string handler. Should be the same result, just a bit more robust.

**Comment by petecooper** [comment]
Yep, still fixed!
