### ISSUE TITLE
Theme name `0` creates a phantom theme that cannot be edited or removed

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1079]
(Using current 4.7.0-dev version as of issue timestamp.)

### Expected behaviour

Theme name `0` should be valid, or forbidden to be created in the first place with appropriate dialog. Theme properties set to `0` should be valid, or forbidden with appropriate dialog.

### Actual behaviour

Theme name `0` is permitted, but subsequent edit/delete actions are not possible and the theme properties acquires some non-`0` characteristics.

### Steps to reproduce

{Please write here}

* visit `/textpattern/index.php?event=skin&step=edit` to make a new theme
* call it `0`, and enter `0` in all other fields (apart from website)
* save it, return to themes list
* note theme version (`0.0.1` and author (current Textpattern user)
* select the theme name to edit it, note the empty fields

Safe for work video with commentary attached in .zip file.

[textpattern 1079.mp4.zip](https://github.com/textpattern/textpattern/files/1592292/textpattern.1079.mp4.zip)

### Possible routes

* forbid `0`-named themes, or numerical themes (see https://github.com/textpattern/textpattern/issues/1077) altogether (too draconian
* sanitise `0`- and numerically-named themes with appended/prepended text (e.g. `skin_0` or `0_skin`)

**Comment by Bloke** [comment]
Thanks for the report. This is an obscure bug/feature in PHP that we should trap. See https://stackoverflow.com/questions/13846769/php-in-array-0-value for details.

Bottom line, we need to do strict type checking when comparing skin names. Will fix.

**Comment by petecooper** [comment]
Thanks @Bloke – I was not aware of the bug, I literally had my finger over 0 in the number pad and it was the nearest key to use.

**Comment by Bloke** [comment]
Good that you did, it's highlighted a whole bunch of weird errors to do with what PHP considers "empty". Things are snowballing by the minute and I'm tracking them down one by one...

**Comment by petecooper** [comment]
I'll take a look, too - got some time today.

**Comment by Bloke** [comment]
Thanks. In other areas of the admin interface we forbid '0' as a page/form/style (though it's okay as an article!) so I think we should continue the tradition at forbid '0' as a theme name. But if you set other things (such as its title or author or version) to 0, they should be respected.

**Comment by Bloke** [comment]
Should be fixed now, please check.

**Comment by petecooper** [comment]
Yep - I see a red `skin_name_invalid` notification on the themes list. From a UX point of view, is there scope to sanity check the theme name on the theme details page itself, rather than dump back to the theme list?

Not a deal breaker, more a nice-to-have, easily deferred for future point release etc.

**Comment by Bloke** [comment]
Yeah, I did spot that it dumps you back out to the list panel. It's on my list of things to investigate when Nicolas drops his next iteration of the class library.

Fwiw, it does this on the Sections panel too and it's annoying. Never found a satisfactory solution for that either without some kludgy code so I've kind of put it on the back burner until we have a) a better widget library, b) a page building library. That should allow us to have better separation between API calls and UI calls, which has the knock-on effect of making this kind of thing easier.
