### ISSUE TITLE
Custom field(s) named `0` do not appear on Write

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1080]
(Using 4.7.0-dev version as of issue timestamp.)

### Expected behaviour

Custom field(s) can be named `0` OR be forbidden.

### Actual behaviour

Custom field(s) can be named `0`, but do not appear on the Write tab or Diagnostics as named `0`.

### Steps to reproduce

* visit `/textpattern/index.php?event=prefs#prefs_group_custom`
* name one or more custom fields `0`, select Save to confirm
* visit `/textpattern/index.php?event=article`, scroll to custom fields
* note missing `0`-named custom fields

Safe for work video and commentary attached in .zip file.

[textpattern 1080.mp4.zip](https://github.com/textpattern/textpattern/files/1593174/textpattern.1080.mp4.zip)

**Comment by Bloke** [comment]
I'm tempted to forbid 0 here too if we can. Shouldn't introduce backwards compatibility issues since anyone who made one called '0' wouldn't be able to use it!

**Comment by petecooper** [comment]
Agreed. 4.6.2 displays the same behaviour, I haven't tried 4.5.7 (if it's even supported).

**Comment by Bloke** [comment]
Cheeky fix to permit '0' here. As the commit message infers, it's way simpler to do that than to write code to forbid users from using such a value in a section of the Prefs panel whose days are numbered anyway.

We'll have to maintain this decision in future, but I'm happy to do so.

**Comment by petecooper** [comment]
Tested and resolved on dev site - thanks @Bloke!
