### ISSUE TITLE
[ui] `Theme base path` is missing a pophelp link

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1081]
(Using current 4.7.0-dev version as of issue timestamp.)

### Expected behaviour

`Theme base path` in `/textpattern/index.php#prefs_group_admin` should have a `?` pophelp.

### Actual behaviour

`Theme base path` in `/textpattern/index.php#prefs_group_admin` is missing its `?` pophelp.

### Steps to reproduce

* visit `/textpattern/index.php#prefs_group_admin` and note missing pophelp link.

![re](https://user-images.githubusercontent.com/226578/34438370-3a2b2e7a-ec9e-11e7-90bb-3f350074832e.png)

**Comment by Bloke** [comment]
Anything with a missing pophelp is now fetched automatically _if_ there's an entry in the `lang/en_pophelp.xml` file. So the way to make this go away is to write an entry in that file under the appropriate group heading.

**Comment by petecooper** [comment]
Aha, clever. OK - I'll close this and migrate to https://github.com/textpattern/pophelp

**Comment by petecooper** [comment]
Migrated to https://github.com/textpattern/pophelp/issues/39
