### ISSUE TITLE
Content > Discuss - notice: undefined variable

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1085]
TXP 4.7-dev up to date

Access the Content > Discuss panel

```
Notice "Undefined variable: createBlock"
in /Users/userame/sites/txptest/textpattern/include/txp_discuss.php at line 484.

textpattern/include/txp_discuss.php:484 adminErrorHandler()
textpattern/include/txp_discuss.php:57 discuss_list()
textpattern/index.php:230 include()
```

cc @bloatware

**Comment by petecooper** [comment]
New install of 4.7.0-dev (1103a204bc8d93fe3a10187de73d2486) here, all clear - no error.

**Comment by phiw13** [comment]
Testing or debug mode ? (default on a new install is testing - that won’t flag that `notice`)

**Comment by petecooper** [comment]
Aha - yes, debug mode shows that message. Mea culpa.

**Comment by bloatware** [comment]
Forgotten to re-enable debug mode when testing, sorry.
