### ISSUE TITLE
Functionality removed in PHP, check for and remove Textpattern references

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1086]
According to [1], `register_globals` was deprecated in PHP 5.3 and removed in PHP 5.4. There are currently some Textpattern code references to `register_globals` [2] that could be removed since the minimum version of PHP for 4.7.0 is being bumped to PHP 5.4.

[1] http://php.net/manual/en/ini.core.php#ini.register-globals
[2] https://github.com/textpattern/textpattern/search?utf8=✓&q=register_globals&type=

**Comment by Bloke** [comment]
Good call. 35 lines less crap code in `index.php` (x3), one less `gTxt()` string for Diagnostics panel and possibly a few classes to remove from `vendors`.

In light of [get_magic_quotes_runtime](http://php.net/manual/en/function.get-magic-quotes-runtime.php) and [get_magic_quotes_gpc](http://php.net/manual/en/function.get-magic-quotes-gpc.php) being removed at PHP 5.4.0 (at least, the notices on those page say that the function always returns false on PHP 5.4.0+, but the compatibility info still mentions PHP 7), we should probably consider removing `Server/Config.php` and `Security/Filter.php` in our `vendors` directory. Or, at the very least, deprecating them.

**Comment by petecooper** [comment]
Additional stuff to check:

* [safe mode](http://www.php.net/manual/features.safe-mode.php) was also removed
* [break](http://php.net/manual/control-structures.break.php) / [continue](http://php.net/manual/control-structures.continue.php) $var syntax was removed

Release notes for 5.4.0: http://php.net/releases/5_4_0.php

**Comment by Bloke** [comment]
Good call. I thinnk  we can probably remove our [one use of safe_mode](https://github.com/textpattern/textpattern/blob/dev/textpattern/vendors/Textpattern/Mail/Adapter/Mail.php#L109) by just doing a plain `else` there. And I hope to goodness we're not using the variable break/continue syntax anywhere!

@bloatware / @makss In light of moving to PHP 5.4, what do you think about removing `Server/Config.php` and `Security/Filter.php` from our `vendors` directory as well as removing all the crufty `register_globals` stuff mentioned in the above comments?

**Comment by bloatware** [comment]
Oops... in few places I have also used `array_column()` function available since PHP 5.5. Is it too early?

**Comment by Bloke** [comment]
Ah, possibly. We can either take another step up to 5.5 if we think that doesn't shut out too many users or [implement our own](https://github.com/ramsey/array_column/blob/master/src/array_column.php).

**Comment by petecooper** [comment]
Considering anything pre-5.6 has long since been EOL'd, I am +1 for bumping minimum requirements to PHP 5.5

**Comment by philwareham** [comment]
> do we trust these stats from late last year?

No, those stats are skewed by the results only coming from Composer installs. We can assume people using Composer would generally be favouring modern code.

Although I'd love to go to PHP5.5 at Textpattern 4.7, there is still a sizeable install base of PHP 5.4 (and indeed our own Joyent server is EOLed at PHP5.4 with no path to upgrade - although I'm tempted to move everything away from Joyent later this year now we have all the Textpattern domains and DNS records).

We can comfortably target PHP5.5 at Textpattern 4.8 I feel.

**Comment by bloatware** [comment]
No worries, we don't need anything worth a polyfill atm, fixed.

**Comment by Bloke** [comment]
Cool. A few parts of 9113dd8b have been undone in the process in `taghandlers.php` but it's only cosmetic.

What do you think to the stuff in the first few comments to this issue, btw? Think we can safely hack out all the crud regarding `magic_quotes` and `register_globals` and stuff? Looks like most of the code will be bypassed anyway on 5.4+ so if we can ditch any of it, now would be a good time to do so.

**Comment by bloatware** [comment]
Oops, sorry, git did not warn me enough. Will try to revert and commit again.

No idea re `magic_quotes`. The files are already in 4.6, anyway. If it's safe to keep them, let's think about it later?

**Comment by Bloke** [comment]
I'm okay to defer it. Nothing seems to have broken so far and I've been running dev on PHP 5.6/7.1 for some time.

**Comment by petecooper** [comment]
For completeness, if we're moving to PHP 5.5 minimum (advertised) on 4.8.0, do we need a similar issue to track functionality changes in from pre-5.5, or would you prefer to do this over 4.8.x patch releases instead to reduce the friction?

**Comment by petecooper** [comment]
_[Backward incompatible changes](http://php.net/manual/en/migration54.incompatible.php)_ in PHP 5.5 that should be investigated and addressed:

* there's a `safe_mode` reference at https://github.com/textpattern/textpattern/blob/d7f1bc08526e908ec36608abc1835ac2f7f45981/textpattern/vendors/Textpattern/Mail/Adapter/Mail.php#L109
* handful of references to `register_globals` [here](https://github.com/textpattern/textpattern/search?q=register_globals&unscoped_q=register_globals)

I'll update if anything else crops up.

**Comment by petecooper** [comment]
Bumping this for 4.8.0 release. At this time, there are some `register_globals` references that need to be zapped:

https://github.com/textpattern/textpattern/search?utf8=✓&q=register_globals&type=

…and a single `safe_mode` reference in `Mail.php`:

https://github.com/textpattern/textpattern/search?utf8=✓&q=safe_mode&type=

**Comment by Bloke** [comment]
Dealt with in e1b18716 and 6d1e82dc.
