### ISSUE TITLE
RFC: break -> separator in search_result_excerpt tag

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1087]
Proposal:

* Deprecate `break` attribute in [search_result_excerpt](https://docs.textpattern.io/tags/search_result_excerpt) because it's not really 'breaking' content like we do in other tags. It doesn't use `doWrap()` or anything like that and handles the attribute in a special way.
* Replace `break` with `separator` in this tag because it's more in-tune with how the attribute behaves.

Fallout: `breakby` wouldn't work, but I don't think it works in this context anyway... at least, I couldn't get it to do anything in my tests. Maybe I missed something.

If `break` is deprecated, remove `breakby` from the documentation for this tag too.

Thoughts?

**Comment by bloatware** [comment]
Yes, the opposite consistent way (enable `breakby` via `doWrap()`) seems of little use here.

**Comment by Bloke** [comment]
Thanks. Done and dusted.
