### ISSUE TITLE
Remove uncompressed assets from admin themes?

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1094]
AFAIK, txp uses only the minified `.js` and `.css` files of the standard admin themes. Removing their uncompressed versions (if possible) would spare ~3x200Kb disk space.

**Comment by philwareham** [comment]
Correct. I'd initially included uncompressed fees for people to use as learning resources if they wanted to develop their own themes or tweak CSS - but I guess they can just go to my theme repos on GitHub and do the same. Will remove.
