### ISSUE TITLE
Textpattern warnings cause XML errors if site is set to Doctype: XHTML and served with XHTML header.

### ISSUE THREAD

**Issue by johnstephens** [textpattern/textpattern#1095]
### Expected behaviour

**Setup:** "Doctype" in "Preferences" pannel is set to "XHTML", and I have a page that must be served as "application/xhtml+xml", using aks_header to set the header.

Opening the page using Textpattern 4.7 development snapshot throws a bunch of Textpattern warnings that didn't exist on Txp 4.6.2, formatted like this:

    Tag error: <txp:output_form form="foo"/> ->  Textpattern Warning: Tag opening/closing mismatch: <txp:if_variable name="bar" value="bat">…</txp:if_article_category>. while parsing form foo on page default

I would expect the error message to appear in the window when I access the page in a browser.

### Actual behaviour

Instead, the tag error is formatted like so:

    <pre dir="auto">Tag error: <b>&lt;txp:output_form form=&quot;foo&quot;/&gt;</b> -> <b> Textpattern Warning: Tag opening/closing mismatch: &lt;txp:if_variable name=&quot;bar&quot; value=&quot;bat&quot;&gt;&hellip;&lt;/txp:if_article_category&gt;. while parsing form <strong>foo</strong> on page <strong>default</strong></b></pre>

When that markup is served as XHTML, the browser displays the following XML error, as follows:

> This page contains the following errors:
> error on line 1 at column 221: Entity 'hellip' not defined

**Comment by Bloke** [comment]
Thanks for the report. Try opening `textpattern/mode.ini` and replacing the `&hellip;` in the `mismatch_open_close_tag` string with either:

`&#8230;`

or paste in a real-life horizontal ellipses character in its place. Then run your site again and see what happens. Whichever one fixes it (if any) let us know here and we'll patch it.

**Comment by johnstephens** [comment]
Thanks! That does get rid of the undefined entity error. But now it has the old "Extra content at the end of the document" error. I think that's due to the Textpattern errors printing "outside" the document—that is, before the !dotcype, html, and body tags.

I don't imagine there's such a simple fix for that. What would be great is to have a txp:debug tag that displays the debug info where the author designates (if present), instead of prepending it to the document.

**Comment by Bloke** [comment]
Okay, so the fix fixes it, but doesn't fix it really! We can patch the `mode.ini` file easily (which one fixed it, btw? The entity name or the real ellipses character?) but as for the other issue, I'm not entirely sure.

You're right that it's bad form to just chuck error message outside the DOM, whatever the doctype. We do have a JavaScript 'Console' implementation available to us that could receive errors (though they wouldn't necessarily be visible).

I like the idea of a tag that can output errors wherever you want instead of just dumping them unceremoniously to the page. Not sure what would happen if you didn't put the tag on the page though: how would we notify you? It might be possible to check if you've used the tag and only output stuff to the top of the page as a last resort if you haven't employed the debug tag anywhere, but I'm not sure.

If you don't mind I'll defer this to people who are more in the know about PHP error handling: @bloatware / @makss ? Any ideas on whether this is fixable or something we have to live with?

**Comment by johnstephens** [comment]
> which one fixed it, btw? The entity name or the real ellipses character?

I tried the entity name first, and that worked. I did not try the `…` ellipsis character.

My suggestion would be to check if the debug tag exists, and preserve the current behavior when it is not used. That way, people who don't know about it can continue getting debug info at the top of the page like old times. ;)

**Comment by johnstephens** [comment]
> We do have a JavaScript 'Console' implementation available to us that could receive errors (though they wouldn't necessarily be visible).

@Bloke, can you elaborate on this when you get a chance?

**Comment by Bloke** [comment]
In our `textpattern.js` we introduced (in Txp 4.6.0) a "Console" which is a message queue/display mechanism. I think Gocom added it. It's being used in the new multi-file-upload feature and handles our 'success' flash messages at the bottom of the screen when AJAX calls complete, but I don't think we're using the 'ConsoleLog' part of it yet.

That part of it would be ideal for capturing error messages and making them available... uhh, somewhere. Whether that was by looking in the JavaScript console in the browser or we could make its contents available to a tag, I'm not sure. I suspect the former but I've never used the system so I'm not sure what its capabilities are.

**Comment by johnstephens** [comment]
Web developers who create sites with Textpattern ought to be able to use a JavaScript console, and I wouldn't object to seeing debug messages there. In that case, it might be sufficient to have a preference like "Send debug information to [Document | Console]".

Then, if you have "Document" as the default, the current behavior of prepending the warnings would continue.

**Comment by bloatware** [comment]
We could redirect debug messages to console/tag/whatever, but we'd then loose their "local" nature, i.e. them appearing exactly where the error happens. This often helped me in debugging.

**Comment by Bloke** [comment]
I've never noticed messages appearing in-situ. All things like tag-is-unregistered etc are just dumped at the top of the public page above the doctype. Maybe it's because of my Page structure? They appear in-situ on the admin side, that's great and really helpful.

**Comment by bloatware** [comment]
I must confound with the debug output of some plugins, my bad.

**Comment by johnstephens** [comment]
@Bloke, do you know if debug message output was altered in any way for Txp 4.7?
