### ISSUE TITLE
Comments counting

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1099]
I commented the (incredible) latest blog article by Stef which hadn't been approved yet (https://textpattern.com/weblog/403/textpattern-cms-gains-themes-support). On the main page, comments count displays 3 (total counting, even hidden comments included) but the full article shows 2 comments (only visible ones). It seems that hidden comments waiting for approuvals  are included within some specificated tags.

Please Devs, check and confirm.

**Comment by Bloke** [comment]
No, it has been approved. That's why the counter is showing it. But the cache engine has cached the previous view of the page. Force refresh and you'll see it :-)

**Comment by cara-tm** [comment]
Ah. Ok. All is fine (sorry Stef)
Please delete this issue ;)
