### ISSUE TITLE
xml-rpc is failing with  multi-sites

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#110]
_From [tecumseh...@gmail.com](https://code.google.com/u/103128831540387028144/) on March 19, 2011 05:06:18_

What steps will reproduce the problem? 1. ScribeFire setup with a regular install = success
2. ScribeFire with multi-site install returns 404 error during setup. 3. What is the expected output? What do you see instead? Expected outcome was to successfully be able to access and post to the website using ScribeFire

Instead, the setup wizard reports 404 errors. What version of the product are you using? On what operating system? Txp svn

Firefox 4.0rc

ScribeFire 3.5.3.3 Please provide any additional information below.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=106_

**Comment by petecooper** [comment]
This is going to fail because there's no symlink in the relevant `/sites` directory to the `rpc` endpoint.

I'll test it and see what happens when there is a symlink.

**Comment by petecooper** [comment]
This can be closed, addressed by https://github.com/petecooper/textpattern/commit/a367b7a70d58e94b05a62e33b8f3ae22e0648305

**Comment by philwareham** [comment]
Thanks again!
