### ISSUE TITLE
`setup_autoinstall_text`?

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1100]
Just done a clean install of current 4.7-dev. At the send of the setup process I can see an (missing) text string called `setup_autoinstall_text` - along with a missing pophelp for it.

Should this be here? And if so, I'll need some guidance on the text string and pophelp item needed for it.

![setup-grab](https://user-images.githubusercontent.com/413665/34774455-494f4d1a-f607-11e7-91d5-17d7730f5bc0.png)

**Comment by petecooper** [comment]
It looks like @makss introduced it in https://github.com/textpattern/textpattern/pull/1019

**Comment by Bloke** [comment]
I _think_ it's just a place to show you a config file that you can use in future if you wish to automate the installation. If you click the pophelp, I seem to recall it displays the config file contents in the popup.

Not the most intuitive way of working. I think a twisty panel here or a link that serves the content as a .txt download would be nicer with some preamble as part of the `setup_autoinstall_text` string. e.g. If you would like to automatically install Textpattern in future, here's a config file that'll enable you to do so with the settings you just used. Drop it in blah blah and do thing thing...

**Comment by philwareham** [comment]
Can you add this to the things to do before beta - basically I will attempt to house this info in a better manner.

**Comment by petecooper** [comment]
+1 to @Bloke above. From a UX point of view, it's counter-intuitive to get most of the way through the installer and then see…another method of installing.

As revolutionary (and massively appreciated) as the automatic installer is, I'd vote for having an air gap between it and the GUI installer.

**Comment by Bloke** [comment]
I'm down with removing the mention for now, even if it's just commented out in the code so we can think about it later.

**Comment by petecooper** [comment]
Proposal: bump to `4.7.1` milestone.

**Comment by Bloke** [comment]
Cool, yeah. Let's deal with it temporarily for now and consider it in 4.7.1+.

**Comment by petecooper** [comment]
^^ This will make more sense if I explain I proposed a 'put a 4.7.1 milestone on it', then deleted the comment.

For the purposes of 4.7.0 beta, commenting out sounds great, this can be closed, and a subsequent issue can be opened for investigating doing something more useful in future (patch release, whatever).

**Comment by petecooper** [comment]
Done, can be closed.
