### ISSUE TITLE
Multiple valid gTxt entries not parsing correctly

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1103]
On the login screen, `password_forgotten` doesn't appear correctly. It _does_ exist in the respective .ini files, and doesn't appear to be language-specific (i.e. it isn't parsing on English or French): 

![screen shot 2018-01-10 at 20 28 59](https://user-images.githubusercontent.com/226578/34794276-0800b7ec-f646-11e7-84ff-86c41fad40ca.png)

Ditto for `no_articles_recorded`. Again, doesn't appear to be language-specific:

![screen shot 2018-01-10 at 20 29 05](https://user-images.githubusercontent.com/226578/34794287-148a9000-f646-11e7-8cb2-6e228f7fb2a5.png)

**Comment by petecooper** [comment]
And another – `preferences_saved` when activating a new language:

![screen shot 2018-01-10 at 20 43 20](https://user-images.githubusercontent.com/226578/34794564-f8ea452e-f646-11e7-8d9b-da7c24ced155.png)

**Comment by Bloke** [comment]
Just a few we've probably missed in the lang-on-demand revamp that need moving to their respective groups. Will fix, thanks for finding them.

**Comment by petecooper** [comment]
No worries and thank you, I'll keep looking. I'll update this issue with any stragglers.

**Comment by phiw13** [comment]
Is this related?

Themes panel, edit a theme, Save. The message box says `Themes updated: {$list}.`
Similarly, on Diagnostics panel: `/Users/user/Sites/_txp472/textpattern/setup/ {path} still exists`.

**Comment by Bloke** [comment]
The `{$list}` thing I know about. There shouldn't be a dollar sign in there. As for {path} we'll have to check out why it's not replacing that. Thanks for the report.

**Comment by philwareham** [comment]
Fixed all these issues apart from the `{path}` one which will need someone else to investigate.

**Comment by Bloke** [comment]
Nice, thanks. I'll take the `{path}` thing. Probably just an incorrect replacement being done on Diagnostics panel.

**Comment by petecooper** [comment]
This can be closed - OP issues are resolved, and current dev build resolves @phiw13's snags reported in https://github.com/textpattern/textpattern/issues/1103#issuecomment-356794343
