### ISSUE TITLE
Toggle language install/update notifications

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1104]
(Current 4.7.0-dev version used.)

### Expected behaviour

When a language is installed, notification should indicate it has been installed.

### Actual behaviour

When a language is installed, notification indicates it has been _updated_.

### Steps to reproduce

* visit `/textpattern/index.php?event=lang`
* install a non-installed language
* note notification dialog

Screencast attached (no audio).

[1104.mp4.zip](https://github.com/textpattern/textpattern/files/1620409/1104.mp4.zip)

**Comment by Bloke** [comment]
This came down to two things:

1. Not being arsed to add a new string just for the installation step.
2. We don't actually check if the language is already installed, just "update" all strings that aren't present... which for installation amounts to all of them.

I suppose we could check first and alter the string. If I get a chance I'll do that, but it's low priority.

**Comment by petecooper** [comment]
>Not being arsed to add a new string just for the installation step.

Somebody was arsed already! See `[language_installed](https://github.com/textpattern/textpacks/blob/master/lang/en.ini#L628)`:

`language_installed="Language <strong>{name}</strong> installed."`

**Comment by Bloke** [comment]
That's fine. Doesn't it show the same message when you subsequently alter the language and update it though?

STR:
1. Re-upload / touch an already installed language file.
2. Visit Languages panel.
3. Click 'Update'.
4. Message 'language_installed' triggered... I think?

Semantics. I suppose you are 'installing' it, as it's overwriting the strings and adding new ones.

And does `language_updated` ever get displayed now? I don't think so.

**Comment by phiw13** [comment]
> Doesn't it show the same message when you subsequently alter the language and update it though?

Yes it does. I `git pull`ed  a moment ago, which updated all lang files. Updated the installed languages and it says “installed”. That is slightly confusing, but no more than the previous situation (always telling me “updated” even when adding/installing a language).

**Comment by philwareham** [comment]
So do you want to remove the `language_updated` string from Textpacks, or keep it and make the system aware of if something is either installed or updated?

**Comment by Bloke** [comment]
We should probably differentiate then. Leave it with me and I'll figure out a way to toggle.
