### ISSUE TITLE
Pop-help looks odd with RTL languages as user language

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1106]
STR

1. activate an RTL language
2. on any panel click a pop-help link

actual results: the english help is displayed (there is no other in the system…) but text is right aligned. That makes it harder to read than could be.

expected results: text is left aligned.

Possible workaround: the content is loaded in `div id=pophelp-event`. Add a `dir=auto` attribute to that element (if a RTL pop-help file would materialise, the text would still display correctly).

![pophelp](https://user-images.githubusercontent.com/8944809/34803710-1e077220-f6b8-11e7-9ad2-dad5535a5081.png)

**Comment by Bloke** [comment]
`dir="auto"` on the pophelp div seems like a great workaround. Will add.

**Comment by philwareham** [comment]
Done and tested, seems to work as intended. Cheers!
