### ISSUE TITLE
Themes folder .htaccess blocks everything?

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1107]
Currently it [specifies](https://github.com/textpattern/textpattern/blob/dev/themes/.htaccess#L4): `RedirectMatch 403 .txp` 

While playing with `<txp:page_url type="theme_path"`, I noticed it blocked my `.css` file. Maybe because I have `txp` in my folder / theme name ?

Input: `<link rel="stylesheet" href="<txp:page_url type="theme_path" />/_r/test.css">`
Output: `<link rel="stylesheet" href="http://txp472.dev/themes/txp_default/_r/test.css">`

This regex however, appears to work  (via the Apache docs):

```RedirectMatch 403 (.*)\.txp```

or even: `RedirectMatch 403 \.txp`

**Comment by Bloke** [comment]
Good catch. A regex match is probably the way forward then. I'm not sure which pattern is best. Should the pattern anchor to the end of the string so we only catch suffixes that end in `.txp`? Otherwise: `article.txpattern.list` might trip it up.

**Comment by petecooper** [comment]
My 2c (untested):

```
RewriteRule .*\.txp - [R=403,L]
```

There are no hidden/dot files, so that _should_ be OK.

**Comment by Bloke** [comment]
Seems like a reasonable approach. Anyone care to test it?

**Comment by petecooper** [comment]
Give me 10 mins and I'll report back.

**Comment by petecooper** [comment]
Results (with `RewriteRule .*\.txp - [R=403,L]`):

* `/themes/` = 403
* `/themes/txp` = 403
* `/themes/txp/txp.css` = 200
* `/themes/txp/txp.txp` = 403
* `/themes/txp_default/_r/` = 403
* `/themes/txp_default/_r/test.css` = 200
* `/themes/txp_default/_r/test.txp.css` = 403 (FAIL)

Needs at least one regex tweak - file _ending_ `.txp` should be 403'd, not valid files _containing_ `.txp`.

I'll be back in 30 mins, I'll take a crack at refining.

**Comment by petecooper** [comment]
Take 2, with test results (trailing `$` on regex):

```
RewriteRule .*\.txp$ - [R=403,L]
```

* `/themes/` = 403 (PASS)
* `/themes/txp` = 403 (PASS)
* `/themes/txp/txp.css` = 200 (PASS)
* `/themes/txp/txp.txp` = 403 (PASS)
* `/themes/txp_default/_r/` = 403 (PASS)
* `/themes/txp_default/_r/test.css` = 200 (PASS)
* `/themes/txp_default/_r/test.txp.css` = 200 (PASS)
* `/themes/txp_default/_r/txp.txp.txp.txp.txp.txp` = 403 (PASS)
* `/themes/txp_default/_r/txp.txp.txp.txp.txp.txp.css` = 200 (PASS)
* `/themes/txp_default/_r/.txp.txp.txp.txp.txp.txp.css` = 200 (PASS)

BOOM.

**Comment by petecooper** [comment]
If you're happy with https://github.com/textpattern/textpattern/pull/1109, that should resolve @phiw13's OP.

**Comment by philwareham** [comment]
Thanks. Closing.

**Comment by phiw13** [comment]
Nice one @petecooper :-) Works great on the test install I used above.

While preparing dinner I had gone as far as the trailing `$` (in my head!), but not the rest.
