### ISSUE TITLE
txp_auth.php needs to be able to access `[admin]` Textpack group

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1110]
The login screens (specifically the password request/reset panel) needs to be able to access strings within the `[admin]` Textpack group (I'd rather that than try to move a load of strings from that group to `[common]` and bugger up Crowdin again).

**Comment by Bloke** [comment]
Should be fixed, please test.

**Comment by philwareham** [comment]
Yep - strings displayed correctly. Thanks!
