### ISSUE TITLE
Zero byte file - `textpattern/textpattern/setup/data/theme.prefs`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1111]
It looks like there's a zero byte file at `textpattern/textpattern/setup/data/theme.prefs`, looking at the history I think @makss was using it while working on the automated installer.

Safe to delete? Rename to a `-dist` with example content?

**Comment by Bloke** [comment]
If it has any content in it at all and a `.prefs` suffix, the installer will pick it up. So renaming it `-dist` won't stop it being read, and adding sample content will get it loaded. I think we should probably delete it and document what you can do in some "Themes" area of the Docs site.

An overall guide to themes (cribbed amnd embellished from the latest blog post on .com?) really needs writing...
