### ISSUE TITLE
Rename `empty` theme to `zero`, or prepend name, or apply weighting

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1113]
I understand there's work going on with resolving some themes issues (including [1101](https://github.com/textpattern/textpattern/issues/1101), for example), but @bloatware @jools-r have raised a valid point about theme ordering on the browser (non-automated) install.

Currently, the themes included are `empty` and `four-point-seven`. I'm surmising that the themes list is automatically populated from included themes, and `empty` is going to be first in that list until `eight-point-zero` (a few years away, I'd wager).

From a UX point of view, the Textpattern default them (currently `four-point-seven`) should really be default (first) when only two are available. That way the blank front page without articles is avoided, which is a dead-end to the uninitiated.

Solutions:

* rename `empty` to `zero`;
* prepend `empty` with something to shift it down the list;
* assign a theme weighting or sort order to each theme;
* something else more clever-er.

A rename is easy enough and probably simplest. Prepending might involved tacking `zzz -` at the start and looks pretty rough. Theme weighting is a bunch of extra work. There are probably smarter solutions available, also.

**Comment by Bloke** [comment]
8bba469b should also address this. The theme selector during the final step of setup uses `four-point-seven` as the default. `empty` is available as an option, as are any custom themes you've dropped into the `themes` directory.

I've yet to test if custom themes install fine. That's next on the list.

But if we want to rename `empty` to `zero` anyway, I'm fine with that.

**Comment by philwareham** [comment]
While I like the name zero - I think empty is more obvious to let users know they are getting a non-theme (since you don’t get to read the description until after the theme is installed). I’d worry that new users who select zero unwittingly are going to get a bad first experience with Textpattern.

**Comment by Bloke** [comment]
I'm good either way.

**Comment by petecooper** [comment]
How about (and I will stop now) combining the two for a more verbose title: `Zero (empty theme)`? Fulfils the last-in-the-list condition, explains what it is, and…honestly, I have no strong feelings either way and I'm just trying to make things a bit easier for you guys.

**Comment by philwareham** [comment]
OK, that works for me. I'll amend.
