### ISSUE TITLE
Unlimitted custom fields

### ISSUE THREAD

**Issue by colak** [textpattern/textpattern#1115]
### Expected behaviour
More custom fields please across the board. ie. articles, images and files.

### Actual behaviour

Only 10 exist in current versions and fewer in the image and files tabs

### Steps to reproduce

{Please write here}

**Comment by Bloke** [comment]
How does this differ from https://github.com/textpattern/textpattern/issues/279?

**Comment by philwareham** [comment]
Closing, as this is a duplicated issue.
