### ISSUE TITLE
Admin > Languages: Order of languages

### ISSUE THREAD

**Issue by uli-on** [textpattern/textpattern#1119]
Looks like languages in the Languages panel are sorted by their _English_ names, not by their proper names: Bahasa Indonesia at the alphabetic position of Malay, Suomi at the position of Finnish, Latviešu after Lietuvių. Might be confusing for first-time installers who don't discover their own language, then, while scanning the page quickly.

**Comment by petecooper** [comment]
Associated forum thread: https://forum.textpattern.io/viewtopic.php?id=48296

**Comment by philwareham** [comment]
Solution is in the forum thread - will put into core in due course.

**Comment by Bloke** [comment]
Yay! Much easier to reorient yourself if you do this and your Arabic isn't up to scratch:

![langswithbuttons](https://user-images.githubusercontent.com/21252/35335383-59e29892-010d-11e8-95e2-04f8f6bda783.png)

**Comment by petecooper** [comment]
@philwareham - love it, great work!
