### ISSUE TITLE
History.txt file: cmd/ctrl-s keyboard shortcut not mentioned

### ISSUE THREAD

**Issue by uli-on** [textpattern/textpattern#1122]
I think the headline tells all the necessary info.

**Comment by petecooper** [comment]
I've been out of the loop - what does that key combination do?

**Comment by petecooper** [comment]
@uli-on This kind of thing is perfect for an on-Github pull request. How about I record a screencast and show you how to do it, then you can raise the request if you're able to - sound OK?

**Comment by uli-on** [comment]
@petecooper Not only available on the Write panel, just anywhere there is something to save to the DB. 

Thanks for offering a screencast, I don't mind, of course, never! But I can't judge my English, you still remember my "wheather", don't you?

**Comment by petecooper** [comment]
OK, I'll walk you through the process with explanations and we'll see how you go.

**Comment by petecooper** [comment]
Recorded, now exporting - will upload shortly!

**Comment by jools-r** [comment]
Nice one Pete!

Uli, if you get an error trying to unzip, try with Unarchiver (can handle multi-part zip files and is free) or you can sew them together with the Terminal as follows:

```
cd {drop the folder with the downloaded files onto the Terminal window to auto-fill the location}
cat pr.mp4.zip.001 > s.zip 
cat pr.mp4.zip.002 >> s.zip
cat pr.mp4.zip.003 >> s.zip

unzip s.zip
```

… and you'll have a file called pr.mp4.

`cat` = concatenate. You can also do `cat cat pr.mp4.zip.001 + cat pr.mp4.zip.002 + cat pr.mp4.zip.003 > s.zip` on one line if you prefer.

**Comment by petecooper** [comment]
Note: please leave this issue open for now, I understand @uli-on will attend to it.

**Comment by uli-on** [comment]
OK, finally found some time to mess about with the pull request (https://github.com/textpattern/textpattern/pull/1132)

**Comment by bloatware** [comment]
To be pedantic: it works on any tab with `submit` button (forms, pages, ...), not only for posting articles.

Welcome on gitboard @uli-on!

**Comment by philwareham** [comment]
You can close this issue or amend text further than I already have if you wish. Cheers all.

**Comment by uli-on** [comment]
@bloatware I tried to but wasn't able any longer to raise a new pull request to reflect your justified objection: Buttons disabled, my branch not available from the comparison menu, etc. Please change my sentence, Oleg, I've been too busy with all these unknown steps and buttons in order to to focus appropriately on my wording.

**Comment by philwareham** [comment]
For minor amends like this, I think (with your contributor role) you can simply use the GitHub in-browser editor like so:

1. Go to the file you want to add, i.e. [HISTORY.TXT](https://github.com/textpattern/textpattern/blob/dev/HISTORY.txt)
2. Click on the pencil icon to go to edit mode
3. Make your edit
4. Commit the change with a commit message
5. Create a new branch/pull request

Maybe.

**Comment by petecooper** [comment]
You can edit inline, @uli-on.

**Comment by bloatware** [comment]
@uli-on just to warn you: if you start asking txp devs to push your commits, you'll end up txp dev and asked to push others commits ;-)
