### ISSUE TITLE
Dropdown checkbox lists - clickable area not full width

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1130]
### Expected behaviour

The dropdown checkbox lists (such as the search options menu) - the whole width of each row should be clickable to check/uncheck the option.

### Actual behaviour

Currently the `<label>` tag (the clickable item) does not stretch to fullwidth. Can be fixed with some better CSS (probably `flexbox` - need to try some options out).

**Comment by Bloke** [comment]
Yeah, I noticed this the other day. Thought I'd rediscovered the "first click doesn't do anything" bug we had before, but it turned out my cursor was just a pixel or two below the text so it wasn't triggering the click, even though I was still inside the option box.

Not a deal-breaker, but a nice usability boon if you can find a fix.

**Comment by phiw13** [comment]
While you’re looking at this: some languages have longer strings that currently wrap under the checkbox in Hive - makes if more difficult to scan (mostly the list options box). Spanish, Farsi, Greek and probably some more, didn’t check them all…

`label { display: block }` will do the job for the clickability.

**Comment by philwareham** [comment]
Done.

**Comment by cara-tm** [comment]
@philwareham

That's what I suggested you a couple of days ago but you didn't give it a try: https://github.com/philwareham/textpattern-hive-admin-theme/issues/164

;)

**Comment by philwareham** [comment]
@cara-tm oh yeah, thanks. Turns out it was more than a simple `display: block;` to fix it, but all good now I think. Might even improve display of your checkboxes in Firefox (seems to be improved in my Mac version) by using absolute display.

**Comment by cara-tm** [comment]
Cool.
