### ISSUE TITLE
Subset of Hive CSS for (pre-)installer screens

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1131]
The pre-installer for multi-site installations employs some minimal styling using the same classes as used in the setup screens – e.g. for basic layout, warnings/notices and pre/code output – and doesn't require the entire set of CSS statements from the textpattern.css file. A subset of the Hive 'textpattern.css' would suffice.

See [/admin/setup/index.php](https://github.com/textpattern/textpattern/blob/dev/sites/site1/admin/setup/index.php) and the [setup directory](https://github.com/textpattern/textpattern/tree/dev/sites/site1/admin/setup).

**Comment by philwareham** [comment]
I'll be onto this within next day or so. Cheers!

**Comment by jools-r** [comment]
No problem. It's not desperately important, but also not difficult for you … maybe you just need a different main sass file with fewer imports.

**Comment by philwareham** [comment]
For my reference: original PR https://github.com/textpattern/textpattern/pull/1129

**Comment by philwareham** [comment]
Done, subject to testing.
