### ISSUE TITLE
Consider using PHPMailer or similar library to handle outgoing email

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1133]
Feature/function request: ability to connect to known-good external or nominated SMTP server for sending of notification emails.

Possible considerations to…consider: envelope address, SSL/TLS, ability to change email template, send rich or plain email.

Forum thread: https://forum.textpattern.io/viewtopic.php?pid=308926#p308926

**Comment by Bloke** [comment]
And [this topic](https://forum.textpattern.io/viewtopic.php?id=48031) too, for reference.

**Comment by petecooper** [comment]
It appears [PHPMailer](https://github.com/PHPMailer/PHPMailer) might be an appropriate library to investigate. It's LGPL 2.1 licensed (IANAL, but I that's GPL-friendly as I interpret it), actively supported and as of the current version requires PHP 5.5…so a good fit with Textpattern minimum system requirements.

**Comment by Bloke** [comment]
I'm fine with rolling this in if everyone else is.  It's not _too_ massive, adding about 300KB to the project (minus LICENCE stuff, which I guess we'd need to include too).

I wonder if we can just dump their `/src` in our `/vendors` directory and be done with it? That does mean i18n won't be taken care of though. Composer has an annoying habit of including tonnes of crap that their project depends on, pulling in 300MB of Symfony code or something.

Bringing this in does save us doing it ourselves and it's tried and tested. We'd only need to map a bunch of email prefs, including options for SMTP credentials, from our Prefs panel into the `txpMail()` function and then call PHPMailer from there accordingly. Potentially deprecating our own `/vendors/Textpattern/Mail` classes in the process.

Is this a quick win to kill off email delivery issues? What does everyone think? Any better approaches?

**Comment by gocom** [comment]
> Bringing this in does save us doing it ourselves and it's tried and tested. We'd only need to map a bunch of email prefs, including options for SMTP credentials, from our Prefs panel into the txpMail() function and then call PHPMailer from there accordingly. Potentially deprecating our own /vendors/Textpattern/Mail classes in the process.

The OOP part of the code base uses [adapter design](https://en.wikipedia.org/wiki/Adapter_pattern), meaning you can provide PHPMailer as a separate adapter and then change it using `setAdapater()` in the appropriate "adaptable", I believe `Compose` in this case or what ever it was named to. Something along to this from top of my head:

```
namespace Textpattern\Mail\Adapter;

class PhpMailer implements \Textpattern\Mail\AdapterInterface
{
    // New implementation for PHPMailer.
}
````

And then:

````
Txp::get('\Textpattern\Mail\Compose')->setAdapter('\Foobar\Some\PhpMailer');
````

After that you can send using PHPmailer:

````
Txp::get('\Textpattern\Mail\Compose')->setBody('Hello World!')->send();
````

Unless of course if one has accidentally initialized the adapter itself directly in `txpMail()` etc without going through the adaptable interfaces, but that is also part of the design of drivers and adapters.

**Comment by petecooper** [comment]
Possibly useful in the dev process: https://github.com/maildev/maildev

**Comment by petecooper** [comment]
Given that we're implementing PHPMailer in 4.9, I'm going to close this since OP is now complete.

**Comment by Bloke** [comment]
Just an addendum: timely release of Txp 4.9.0 very soon is now imperative given the enforced restrictions at hosting providers for receiving signed SPF/DKIM/DMARC email headers, and the removal of some freebie email provides as gateway endpoints.

**Comment by bloatware** [comment]
Wish 4.9 were the last txp 4 version, to finish with dev->cf dance and move to txp 5, scarifying bwc when necessary.

**Comment by philwareham** [comment]
@bloatware I would be totally fine with moving to TXP v5. It's kind of ridiculous that there has never been a version apart from 4 (and probably harmed perception of the software to some extent).

**Comment by petecooper** [comment]
I've opened a separate issue so we can keep this subject on track.
