### ISSUE TITLE
1x pophelp icon addition: Write -> Status

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1134]
I had a client look around the 4.7 dev interface and took some feedback. A lot of it is already in hand, but one thing was something I had overlooked: article statuses from the Write panel. There's no pophelp icon.

The docs work has already been done, if we steal the content from `default_publish_status` pophelp and change the heading/intro text, so it's an easy win from that side of things.

How reasonable is it to have a pophelp inline'd on `Status`, please. I can take dibs on the glue from the  https://github.com/textpattern/pophelp end.

**Comment by philwareham** [comment]
Sure - sounds fine and feasible to me. Let me know when pophelp written and I'll hook it in.

**Comment by petecooper** [comment]
Thanks @philwareham - provisionally using `article_status` as the ID, I'll crunch the words now.

**Comment by petecooper** [comment]
@philwareham - done via https://github.com/textpattern/pophelp/commit/029ee615c593609d3cca5208937e44e0ee146867

Please shout if `status` is too general (there's no namespacing on pophelp as far as I can tell).

**Comment by philwareham** [comment]
Super 👏
