### ISSUE TITLE
[UX] Theme duplication logic - "themes created" and "themes duplicated"

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1137]
STR:

* visit `index.php?event=skin`
* select one theme by checking the checkbox
* from the `With selected…` dropdown, choose `Duplicate`, confirm
* note the success alert (`Themes created` etc)

The success alert states themes have been _created_ (emphasis mine) and lists the _source_ theme names, not the destination theme names. This is confusing and/or misleading.

When duplicating a theme component (style/form/page) the _destination_ names are listed.

Screencast attached (no audio, safe for work).

[1137.mp4.zip](https://github.com/textpattern/textpattern/files/1669225/1137.mp4.zip)

Some possible solutions:

* reword the textpack translation to say `Themes duplicated: {list}`
* add a `skin_duplicated` gTxt
* change the internal reporting and list the destination theme names instead

**Comment by Bloke** [comment]
Let me test out the new version of Themes from @NicolasGraph and see if this issue remains. If so, we'll patch it then.

**Comment by Bloke** [comment]
I think your third option is best: list the duplicates as 'created', which is more in line with the remaining UX. Also saves a couple of strings: hurrah! See 297d3cc7. Thanks, sir.

**Comment by petecooper** [comment]
Thanks again @Bloke – I'll take a look tomorrow with fresh eyes.

**Comment by NicolasGraph** [comment]
Works for me, thanks guys. Should another issue be open to list strings to delete from textpacks?

**Comment by Bloke** [comment]
I don't think the `_duplication` strings even made it into the Textpack in the first place. At least, that's why I spotted them because I got a raw untranslated string when I duplicated a theme last night. But if they are in there, once we've removed the strings from core code, file a ticket on the Textpack repo to get them removed from Crowdin too.

**Comment by NicolasGraph** [comment]
> I don't think the _duplication strings even made it into the Textpack in the first place. At least, that's why I spotted them because I got a raw untranslated string when I duplicated a theme last night.

Ok, thus it still needs to be removed in to places [here](https://github.com/textpattern/textpattern/blob/297d3cc7fcc88fd311a83448119c31307555a379/textpattern/vendors/Textpattern/Skin/Skin.php#L646) and [there](https://github.com/textpattern/textpattern/blob/297d3cc7fcc88fd311a83448119c31307555a379/textpattern/vendors/Textpattern/Skin/Skin.php#L675). I'll do it as it is confusing in these lines.

**Comment by Bloke** [comment]
Yes, thank you. And remove `$notImported`... I can't see it initalised anywhere, unless I've missed something.

**Comment by NicolasGraph** [comment]
> And remove $notImported…

Yes, that's part of the confusing things. I'll do it.
