### ISSUE TITLE
Textpattern\Admin\Table->render always hides the search form

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#1140]
Hi,
I tried to use the `Textpattern\Admin\Table` class for the themes related admin tab and I may have miss something because the documentation is not complete but as far as I tried, the search form is always hidden because of [this](https://github.com/textpattern/textpattern/blob/dev/textpattern/vendors/Textpattern/Admin/Table.php#L71), which set the `$total` and `$criteria` related values to `0` and `1`. Thus, [this](https://github.com/textpattern/textpattern/blob/dev/textpattern/vendors/Textpattern/Admin/Table.php#L86), hides the search form.
Shouldn't these variables be set if not already provided via the `$data` argument only?

**Comment by bloatware** [comment]
Hi @NicolasGraph,

`$total` stores the number of (found) records, your script should calculate it and pass to `render()` as `$data['total']` field. There is no point in showing the search form if the table is empty.

**Comment by NicolasGraph** [comment]
Hi,
I understand but the parameter value is overridden and reset to 0.

**Comment by bloatware** [comment]
It shouldn't be, otherwise the search form would be hidden on all tabs.

**Comment by NicolasGraph** [comment]
Is this class in use for all tabs? I can’t see it anywhere…
Is it a recent change?

**Comment by Bloke** [comment]
Although the manual implies that array operands on the right 'overwrite' their counterparts on the left, in practice - at least in my tests - this isn't true. At least not for string-indexed values. Perhaps numerically-indexed values might get overwritten.

I always get muddled up because with `array_merge()` if the input arrays have the same string keys, then the later value for that key will overwrite the previous one. If the arrays contain numeric keys, the later value will not overwrite the original value, but will be appended.

I'm not convinced array concatenation works quite the same (hence my confusion) but, in this case, any value you supply in the `$data['total']` parameter _should_ be respected, and only use 0 if you don't supply a value.

**Comment by bloatware** [comment]
Atm it's used for all Content tabs, the easiest to see must be the Links tab.

**Comment by Bloke** [comment]
> Is this class in use for all tabs?

[Most, yes](https://github.com/textpattern/textpattern/blob/dev/textpattern/include/txp_list.php#L465).

**Comment by NicolasGraph** [comment]
Ok, I’ll give it one more try, I can now see the `Table` class in use in some tabs, sorry for my inattention.

**Comment by Bloke** [comment]
If you notice any oddness behaviour, please let us know as it may be to do with the PHP version you're using. Who knows, they might have changed the way arrays concatenate in various versions or "fixed bugs" that actually break this feature!

**Comment by bloatware** [comment]
The array union should work as [expected](http://php.net/manual/en/language.operators.array.php).

**Comment by NicolasGraph** [comment]
Yes, it should, sorry.

**Comment by NicolasGraph** [comment]
I definitely made something wrong, it does now work. Thank you both @bloatware and @Bloke.
Just a small thing; the search form could maybe be hidden when there is only one item in the table?

**Comment by bloatware** [comment]
Glad you've solved it and no worries. Re only one item (say, article), the search form might still be useful to check, say, if its body contains some word.

**Comment by NicolasGraph** [comment]
> Glad you've solved it and no worries. Re only one item (say, article), the search form might still be useful to check, say, if its body contains some word.
> 
Oh yes, you’re right.
Thanks again.

**Comment by phiw13** [comment]
> the search form could maybe be hidden when there is only one item in the table?

The search form can also search for strings inside fields that are not available on the list opal itself, e.g.  on the Section tab, you can search the description field.
