### ISSUE TITLE
Skin related textpack changes

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#1144]
From https://github.com/textpattern/textpattern/pull/1143, with some enhancements.
Should currently be applied to the _themes_ branch.

### To delete
- [x] `skin_locking_failed`;
- [x] `skin_unlocking_failed`;
- [x] `remove_extra_templates`.

### To change

- [x] `tab_skins` to `tab_skin` to work with the [`Table` class](https://github.com/textpattern/textpattern/blob/dev/textpattern/vendors/Textpattern/Admin/Table.php#L72);

### To add
- [x] `override="Override"` or `"Re-import"`[Edit: or "Update"]? This would replace the _import_ multi-edit option.
- [x] `skin_synchronize="Synchronize template/file lists."` or `"Delete unused templates/files"`.
This string replaces `remove_extra_templates`. However, the `remove_extra_templates` value shouldn't be used because it is wrong. The pophelp contents should also be corrected and renamed.

- [x] I suggest something like so for the pophelp: 

> If checked, this option allows to synchronize template related database rows and files.
>
> In practice, on override/re-import, each template which is not part of the processed import will be deleted from the database, while on export, template files will be deleted if they are not part of the processed export.
>
> If, for any reason, import or export fails for a defined template it would not be considered as part of the current process and will be deleted from the database or the theme directory.
>
> Finally, on deletion _all_ themes related files will be deleted, including files which would not be part of the theme core structure and would not appears in the database.

**Comment by petecooper** [comment]
Tagging https://github.com/textpattern/textpacks/issues/256 for now, I'll update later when I have some time.

**Comment by philwareham** [comment]
Hi @NicolasGraph. Can you explain why `tab_skins` needs to change - is there a name clash?

**Comment by NicolasGraph** [comment]
Hi @philwareham,
I introduced the use of the `Table` class in the _Skin_ package and if you look at the [link to the `Table` class](https://github.com/textpattern/textpattern/blob/dev/textpattern/vendors/Textpattern/Admin/Table.php#L72) in my previous message you will see that the tab heading is build in there from the current `$event` like so `'tab_'.$event`. The _Themes_ tab related event is _skin_, not _skins_ so, for now, it displays `tab_skin`. Other tabs using the `Table` class already use singular such as [tab_file](https://github.com/textpattern/textpacks/blob/master/lang/en-gb.ini#L141) or [tab_image](https://github.com/textpattern/textpacks/blob/master/lang/en-gb.ini#L144).

**Comment by philwareham** [comment]
OK, thanks for the info. I'lll amend the string name in Textpacks.

**Comment by NicolasGraph** [comment]
Thanks @philwareham for applying these changes!

**Comment by philwareham** [comment]
I've made all the changes to the base language `en` Textpack but I'll still need to sync this back onto Crowdin and do some work there. It'll be tomorrow as I have deadlines to meet today. So I'll keep the issue open until then.

**Comment by NicolasGraph** [comment]
Ok, no worry.

**Comment by philwareham** [comment]
Done. Please test.

**Comment by NicolasGraph** [comment]
euh… sorry @philwareham, I'm not really familiar with this, how can I install the last strings? The _Languages_ tab update button is not active and pasting the [this](https://raw.githubusercontent.com/textpattern/textpacks/master/lang/en-gb.ini) does not work.

**Comment by philwareham** [comment]
If you merge my commit into your repo, you should be able to update the languages (note that `en.ini` is the default (fallback) language as of 4.7).

If the update button isn't working, then delete your database tables and reinstall.

**Comment by Bloke** [comment]
> The Languages tab Update button is not active

They should be. That is odd. Both my English and French languages make the update button available after uploading the latest changes in the `themes` branch.

As Phil says, if a language needs a  complete refresh:

1. Switch your public and admin-side language to something else.
2. Remove the language (from the UI or, delete all strings matching the language identifier from the `txp_lang` table by hand).
3. Reinstall the language from the Languages panel.

Pasting the Textpack in by hand should also work. Something odd going on, methinx.

**Comment by NicolasGraph** [comment]
Thanks @philwareham.

**Comment by NicolasGraph** [comment]
Thnaks @Bloke, I just didn't think to merge the _themes_ branch into mine.
