### ISSUE TITLE
Skin multi-edit form related pop-helps hide the theme list

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#1145]
From https://github.com/textpattern/textpattern/pull/1143.
Should currently be applied to the _themes_ branch.

Clicking on a pophelp link (_skin_synchronize_) in the multi-edit form displays the pophelp but hides the skin list… Any idea?

**Comment by Bloke** [comment]
Bizarre. No idea. Tried to find it, failed. Any ideas, @bloatware ?

**Comment by NicolasGraph** [comment]
> Bizarre.

Yes, moreover the import form related pophelp link does work correctly.

**Comment by Bloke** [comment]
Yes, it's probably something to do with the delegated nature of the pophelp handler. It might be looking back up ther DOM tree for something, not finding it, locating the closest thing that does match (perhaps in this case the previous pophelp, or the container ot something) and assuming it's the previous dialog box and closing it.

Putting judicial `console.log()` calls into `textpattern.js` and comparing the output of a regular pophelp call vs the delegated call on the Themes panel didn't reveal much to my untrained eye, so maybe there's something else going on.

**Comment by NicolasGraph** [comment]
Not sure how this could help but…
If you remove the pophelp related function from `textpattern.js`, the import form related pop help link gives a blank page with just the Txp footer infos using this kind of URL: `http://localhost:8888/GitHub/textpattern/textpattern/index.php?event=help&step=pophelp&item=skin_import`.
However the multi-edit related pophelp links still hide the theme list without changing the URL.

**Comment by bloatware** [comment]
The [fix](https://github.com/textpattern/textpattern/commit/320d518d5e2fc09af6745326618360c1ba7e9622) is easy, but dirty. We'll need to structure async updates better at some point.

**Comment by NicolasGraph** [comment]
I can also just get the multi-edit form out of the `.txp-navigation` and the `$foot` block of the Table class. Adding it to `$content` the way we did it for the import form seems to work…

**Comment by bloatware** [comment]
You can, at the price of loosing async navigation/pagination, but it's not a big deal.

**Comment by NicolasGraph** [comment]
> […] at the price of loosing async navigation/pagination […].

Thus your _dirty_ fix is probably better, isn't it?

**Comment by Bloke** [comment]
For now, yes. Let's go with the dirty fix and figure out something better later.

**Comment by bloatware** [comment]
Just for the record: it has all started with multiple files/images upload in 4.7. Imagine that you upload 20 files and want to do something (say, change the author) with the freshly uploaded files. We can check their boxes in the files list on upload end, but if the list is paginated by 12 files, they will not all appear. The new async mode solves this problem by allowing for lists navigation without loosing the checked states. But I didn't mean to apply it to other tabs, so the code is somewhat upload-specific atm.

**Comment by Bloke** [comment]
Absolutely fine. The key thing is that it works, and works well - optimization can improvements can come later.
