### ISSUE TITLE
Themes branch: Page and Stylesheet saves broken

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1147]
@NicolasGraph 

```
Uncaught Error: Call to undefined function sanitizeForTheme()
```

Happens in both Page and Styles panels.

**Comment by NicolasGraph** [comment]
I can't reproduce. Do you use all the _themes_ branch files?

**Comment by Bloke** [comment]
Thought I did. Will check.

**Comment by Bloke** [comment]
Yep. Definitely in there: https://github.com/textpattern/textpattern/blob/themes/textpattern/include/txp_page.php#L355 (in `txp_css.php` too)

**Comment by Bloke** [comment]
Thanks!

**Comment by NicolasGraph** [comment]
Sorry, thank you @Bloke.
