### ISSUE TITLE
Make skin_synchronize option consistent between methods

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#1154]
See: https://github.com/textpattern/pophelp/commit/0c890cc556fab810d8c1ce5b1fd36f9a82687cd2

I'll do it.

**Comment by NicolasGraph** [comment]
@Bloke,
I started to work on that but there is something I'd like to discuss.
For now, it is not allowed to create a theme if its directory exists to avoid to override something you wouldn't want to on export.

The thing is that if we only delete valid templates on deletion (as for import/export), the skin directory could be not removed because of the presence of any file which wouldn't be a valid template, a `.DS_store` file for example. Should I just let the user know that the some files/directories still exist? It mays often happen.

**Comment by Bloke** [comment]
Hmmm, yes, that's an issue. Rats. Not sure what to do for best here. Umm....

**Comment by NicolasGraph** [comment]
`skin_synchronize` should work the same way on deletion and import/export in my branch now.
I'll perform more tests before to send a PR because I also fixed a bug into _RecFilterIterator_.
I guess I should also display a warning if the theme directory still exists after deletion+synchronization; I can't think about something cleverer for now.
