### ISSUE TITLE
Automated installer defaults to `zero` theme

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1158]
I'm rebuilding the demo server from scratch in anticipation of the upcoming beta, and it looks like the automated installer is defaulting to the `zero` theme when no theme is explicitly requested in the JSON file.

Tagging in https://github.com/textpattern/textpattern/issues/1101 for completeness.

**JSON with no theme**

```
{
    "site": {
        "lang": "en",
        "siteurl": "",
        "theme": "",
        "public_theme": "",
        "datadir": ""
    },
    "mysql": {
        "user": "dev-demo",
        "pass": "<snipped>",
        "host": "127.0.0.1",
        "db": "dev-demo",
        "table_prefix": ""
    },
    "user": {
        "realname": "Textpattern Demo Robot",
        "email": "domo-arigato-mr-roboto@example.com",
        "name": "textpattern-robot",
        "pass": "<smipped>"
    }
}
```

This connects fine, and recognises English, and then installs `zero` (ignore the `beta.sh` name, I'm still working on it):

```
$ sudo bash ./beta.sh 
Cloning into '/var/www/vhosts/textpattern.co/dev-demo/staging/github-dev'...
remote: Counting objects: 467, done.
remote: Compressing objects: 100% (419/419), done.
remote: Total 467 (delta 99), reused 120 (delta 21), pack-reused 0
Receiving objects: 100% (467/467), 1.35 MiB | 0 bytes/s, done.
Resolving deltas: 100% (99/99), done.
Checking connectivity... done.
Cloning into '/var/www/vhosts/textpattern.co/eu/dev-demo/staging/github-dev'...
remote: Counting objects: 467, done.
remote: Compressing objects: 100% (419/419), done.
remote: Total 467 (delta 99), reused 120 (delta 21), pack-reused 0
Receiving objects: 100% (467/467), 1.35 MiB | 0 bytes/s, done.
Resolving deltas: 100% (99/99), done.
Checking connectivity... done.
[OK]	Connected
[OK]	Using dev-demo. (utf8mb4)
[OK]	Creating database tables
[OK]	Lang: 'en'
[OK]	Front-side theme: 'zero'
[OK]	That went well!
```

**JSON with theme title**

Note: I've changed the language to `fr` as a visual cue to the installer reading the correct JSON file.

```
{
    "site": {
        "lang": "fr",
        "siteurl": "",
        "theme": "",
        "public_theme": "Four Point Seven",
        "datadir": ""
    },
    "mysql": {
        "user": "dev-demo",
        "pass": "<snipped>",
        "host": "127.0.0.1",
        "db": "dev-demo",
        "table_prefix": ""
    },
    "user": {
        "realname": "Textpattern Demo Robot",
        "email": "domo-arigato-mr-roboto@example.com",
        "name": "textpattern-robot",
        "pass": "<snipped>"
    }
}
```

Again, it connects fine, and this time installs the right theme as expected:

```
$ sudo bash ./beta.sh 
Cloning into '/var/www/vhosts/textpattern.co/dev-demo/staging/github-dev'...
remote: Counting objects: 467, done.
remote: Compressing objects: 100% (419/419), done.
remote: Total 467 (delta 99), reused 120 (delta 21), pack-reused 0
Receiving objects: 100% (467/467), 1.35 MiB | 0 bytes/s, done.
Resolving deltas: 100% (99/99), done.
Checking connectivity... done.
Cloning into '/var/www/vhosts/textpattern.co/eu/dev-demo/staging/github-dev'...
remote: Counting objects: 467, done.
remote: Compressing objects: 100% (419/419), done.
remote: Total 467 (delta 99), reused 120 (delta 21), pack-reused 0
Receiving objects: 100% (467/467), 1.35 MiB | 0 bytes/s, done.
Resolving deltas: 100% (99/99), done.
Checking connectivity... done.
[OK]	Connectée
[OK]	dev-demo en cours d’utilisation. (utf8mb4)
[OK]	Création des tables de la base de données
[OK]	Lang: 'fr'
[OK]	Prefs: 'data/core'
[OK]	Import: 'data/txp_category'
[OK]	Import: 'data/txp_link'
[OK]	Import: 'data/txp_section'
[OK]	Import: 'articles/articles.welcome'
[OK]	Thème du site public: 'Four Point Seven'
[OK]	Tout s’est déroulé parfaitement. Les tables SQL ont été créées et remplies.
```

**JSON with theme title**

Using the theme name (`four-point-seven`) instead of title (`Four Point Seven`) in the JSON makes it failover to the `zero` theme. My memory is a bit hazy – is it mandatory to use the theme title or is this a bug that's (re)surfaced?

**Comment by Bloke** [comment]
Probably a bug that's resurfaced as part of the Themes changes. Both the manual and automated installers should respect your choice of theme - bearing in mind that the [sort-of-relative-path needs to be specified too](https://github.com/textpattern/textpattern/issues/1101#issuecomment-357912665) - or if you've not specified a theme (or used a bogus path), the default `four-point-seven` should be used.

Any clues @NicolasGraph or @bloatware ? We should probably figure out this path thing before we go live with the beta.

And I just remembered that we also need to remove the path from the dropdpown selector in the final step of the setup process, as it makes the dropdown too wide. I'm tempted to just remove it, wholesale. If anyone has two identically-named themes in their `themes` and `setup` directories, well, tough for now. They should have chosen better names :-)

**Comment by petecooper** [comment]
Thanks @Bloke - confirming that using the automated installer with Textpattern relative paths works fine, that slipped my mind. Great remindin', there!

While we have the chance to fix this, is it viable to tweak the theme namespace a bit? There are admin-side themes and front-side themes, clearly `"public_theme"` refers to the front-side, but `"theme"` isn't _obviously_ admin-side and appears before the front-side theme in the provided JSON, which could be misleading to dabblers and first-timers.

How badly will things go south if `"theme"` becomes `"admin-theme"`?

**Comment by Bloke** [comment]
Re: Changing the name of the JSON pref, that's a wholly-reasonable request. Can't see any reason it wouldn't work, beyond the fact that we (short-sightedly) employed the term 'theme' as a prefs key to mean 'admin theme'.

Depending on how stuff's wired behind the scenes, we might need to do a little translation between the JSON key and the database. But as a rule of thumb we shouldn't expose internal names like this to the public-facing side of things anyway (cf. skin vs public theme).

Anyone fancy taking a quick stab at changing the JSON structure to uses `admin_theme` instead of `theme` as a key? I can maybe do it (late) tonight or tomorrow if nobody jumps on it.

**Comment by petecooper** [comment]
Fantastic -thank you. Shall I jettison to a new issue?

**Comment by Bloke** [comment]
Yes please.

**Comment by NicolasGraph** [comment]
> I'm tempted to just remove it, wholesale. If anyone has two identically-named themes in their themes and setup directories, well, tough for now. They should have chosen better names :-)

…In fact, I did it. Let me know if that is ok… 😶

**Comment by Bloke** [comment]
@NicolasGraph I did wonder. I went to go and do it last night and couldn't find the code. That would explain it. Saves me a job, thanks!

**Comment by NicolasGraph** [comment]
@Bloke You're welcome; glad it was not a mistake to do it!

**Comment by NicolasGraph** [comment]
> Using the theme name (four-point-seven) instead of title (Four Point Seven) in the JSON makes it failover to the zero theme.

While I'm not familiar with this kind of install, I'm guessing that it could be a normal behaviour related to the way I modified the public theme select list. While the posted value is the theme name, the one displayed in the form is the theme title (like in the _Themes_ tab import form). In the JSON file, which value is needed? I would tempt to think that it is the posted one but…

**Comment by NicolasGraph** [comment]
As https://github.com/textpattern/textpattern/issues/1160 was closed, Is there still something to fix in this issue?

**Comment by petecooper** [comment]
@NicolasGraph - possibly, yes. The scope of this issue, to me, is that if no theme is specified in the JSON then the `zero` theme is installed. Is this expected behaviour?

**Comment by NicolasGraph** [comment]
Shouldn't it be `four-point-seven`, as suggested [here](https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/index.php#L404)?
How does the auto install work? I guess the JSON file is used to set `$cfg`, right?

**Comment by petecooper** [comment]
If the code logic at https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/index.php#L404 is saying: "if the `"public_theme"` setting in `"site"` is empty (not specified), then install `four-point-seven`", that does not happen with the latest build.

The results at https://github.com/textpattern/textpattern/issues/1160#issuecomment-367681328 show that an unset/unspecified `"public_theme"` falls back to `zero` theme.

The auto-install works from a command line, like this:

```
php /textpattern/setup/setup.php --config="settings.json"
```

…where `/textpattern/setup/setup.php` is the file system path and `settings.json` is built from @Bloke's schema here: https://github.com/textpattern/textpattern/issues/1159#issuecomment-367176884

**Comment by NicolasGraph** [comment]
Thanks @petecooper, I'm going to try the auto-install.

**Comment by NicolasGraph** [comment]
There is something I'm doing wrong with the auto-install…
Using this:

```
{
    "site": {
        "language_code": "en",
        "public_url": "",
        "admin_url": "",
        "admin_theme": "",
        "public_theme": "",
        "content_directory": "",
        "cookie_domain": ""
    },
    "database": {
        "user": "root",
        "password": "root",
        "host": "localhost",
        "db_name": "textpattern",
        "charset": "",
        "table_prefix": "",
        "client_flags": ""
    },
    "user": {
        "full_name": "Nicolas Morand",
        "email": "testing@txp.com",
        "login_name": "NicolasGraph",
        "password": "xxxx"
    }
}
```

I get the following errors…

```
Warning: Invalid argument supplied for foreach() in …textpattern/textpattern/vendors/Textpattern/L10n/Lang.php on line 374

Notice: Undefined index: mysql in …textpattern/textpattern/setup/setup_lib.php on line 306

Notice: Undefined index: mysql in …textpattern/textpattern/setup/setup_lib.php on line 307
[ERROR]	Cannot connect to database
```

**Comment by petecooper** [comment]
Check your database permissions - also, try setting your host to `127.0.0.1`.

**Comment by Bloke** [comment]
> The scope of this issue, to me, is that if no theme is specified in the JSON then the zero theme is installed. Is this expected behaviour?

Expected behaviour: if no `public_theme` is specified OR (perhaps) if the `public_theme` is in some way mangled/does not point to a valid theme manifest, then `four-point-seven` (a.k.a. 'default') theme is installed.

This is a concern in manual installs too - if someone drops a theme that is fubar into the `themes` directory, what should we do?

a) Not show it as an option in the list? (I think we do this anyway if the manifest is missing, but I've not tried it, nor have I tried mangling the contents)?
b) Refuse to install it?
c) Error / die?
d) Drop back to `four-point-seven`?
e) Something else...?

@NicolasGraph Are you using the latest dev / merge?

**Comment by NicolasGraph** [comment]
> @NicolasGraph Are you using the latest dev / merge?

Of course not… You're starting to know me well. 😕

**Comment by NicolasGraph** [comment]
Well, I'm still not able to connect…

> This is a concern in manual installs too - if someone drops a theme that is fubar into the themes 
directory, what should we do?
>
> a) Not show it as an option in the list? (I think we do this anyway if the manifest is missing, but I've not tried it, nor have I tried mangling the contents)?
b) Refuse to install it?
c) Error / die?
d) Drop back to four-point-seven?
e) Something else...?

a) is used for now. To be displayed in the select list, a theme must contains a _manifest_ file containing at least the following field+value : `txp-type="textpattern-theme"`.

**Comment by Bloke** [comment]
a) is fine. It's what I expect, and, yes, I like the fallback that if anything's mashed inside the tempalte (e.g. forms missing) then the essential stuff is created.

As for not being able to connect... hmmm. One thing I'm not sure about is what happens if you specify a field and leave it empty. e.g. `charset`. Does that set the charset to `''` (nothing) or use the default if empty? Depends on how it's coded - I can't recall.

Erring on the safe side, I'd omit anything from the JSON file that you're not explicitly using. And if that works, then we'll need to change the code so we check for empty and use default if the parameter is a required one.

Can you connect to the DB locally via the `mysql -u root -proot textpattern` command?

**Comment by NicolasGraph** [comment]
> Erring on the safe side, I'd omit anything from the JSON file that you're not explicitly using. And if that works, then we'll need to change the code so we check for empty and use default if the parameter is a required one.

Unfortunatly, it does not work…

> Can you connect to the DB locally via the mysql -u root -proot textpattern command?

```
-bash: mysql: command not found
```

but this does work:

```
/Applications/MAMP/Library/bin/mysql --host=localhost -uroot -proot textpattern
```

**Comment by Bloke** [comment]
Maybe it's a path issue then? Weird. PHP should know where to find MySQL, and clearly it's installed. `php.ini`? `my.cnf`? PATH variable? Not sure.

**Comment by petecooper** [comment]
For what it's worth, I usually use VirtualBox or Raspberry Pi environments for macOS web dev as MAMP has all kinds of quirks to work around.

**Comment by Bloke** [comment]
> Warning: Invalid argument supplied for foreach() in …textpattern/textpattern/vendors/Textpattern/L10n/Lang.php on line 374

P.S. This is a bug. We shouldn't assume that `$textpack` exists on line 374 if, for some reason, the wrong lang code is specified or the dir is not readable or something. Need a defensive code wrapper around the `foreach` to check `if ($textpack) { ...}` methinx. Or does that just mask the real issue?

**Comment by NicolasGraph** [comment]
I don't have this message anymore with the last _dev_ version. But that could maybe be an issue in other cases…

**Comment by NicolasGraph** [comment]
@petecooper, could you try to apply https://github.com/NicolasGraph/textpattern/commit/4f03445d8f08ff25b3e64b1e39649d42ee4cd660 to your _dev_ version? Not sure it will fix this issue but it should at least avoid to have an empty _default_ theme installed when the provided public theme is not valid.

**Comment by philwareham** [comment]
I've just tested auto install on MAMP here and it's working as expected. If that helps anyone.

**Comment by NicolasGraph** [comment]
> I've just tested auto install on MAMP here and it's working as expected. If that helps anyone.

Nothing special about your config?

**Comment by philwareham** [comment]
No, not that I know of. I did specify a `public_url` as I assume that it a minimum requirement needed to install. And I'm using MAMP Pro because I need a GUI for everything ;).

**Comment by NicolasGraph** [comment]
Ok, thanks @philwareham, I'm also using Mamp Pro. I guess I'll be able to make it work with fresher eyes tomorrow…

**Comment by petecooper** [comment]
OK, results from https://github.com/textpattern/textpattern/issues/1158#issuecomment-367734352 coming up…

Current `dev` version with https://github.com/NicolasGraph/textpattern/commit/4f03445d8f08ff25b3e64b1e39649d42ee4cd660 applied (listing lines 400 to 410):

```
$ awk 'NR>=400&&NR<=410' /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/setup/index.php 

    $public_themes_class->setDirPath(txpath.DS.'setup'.DS.'themes');
    $vals = array_merge($public_themes_class->getUploaded(), $vals);

    if (empty($cfg['site']['public_theme']) || !array_key_exists($cfg['site']['public_theme'], $vals)) {
        $public_theme_name = 'four-point-seven';
    } else {
        $public_theme_name = $cfg['site']['public_theme'];
    }

    $public_theme_chooser = selectInput('public_theme', $vals, $public_theme_name, '', '', 'setup_public_theme');
```
Running the auto-installer manually:

```
$ php /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/setup/setup.php --config="/var/www/vhosts/textpattern.co/dev-demo/staging/dev-demo.json"
[OK]	Connected
[OK]	Using dev-demo. (utf8mb4)
[OK]	Creating database tables
[OK]	Lang: 'en'
[OK]	Public theme: 'zero'
[OK]	That went well!
```

…shows the `zero` theme installed, and logging in to the admin-side confirms this:

<img width="691" alt="safariscreensnapz001" src="https://user-images.githubusercontent.com/226578/36552385-a59dfe34-17f1-11e8-9f4e-3c464982380c.png">

Conclusion: that does not appear to have worked as intended/expected.

**Comment by NicolasGraph** [comment]
@petecooper, I was able to test multiple auto-installs and everything went well.
The right default theme was install when `public_theme` was empty (or unknown, with my commit merged).

I thought @philwareham was confirming the auto-install worked with Mamp, but I'm seing he was telling us that it worked as expected…

> I've just tested auto install on MAMP here and it's working as expected. If that helps anyone.

While it should not fix your issue, my last commit could have not been up to date (not sure why), I'm going to send a PR to be sure we are both using the right version.

The only thing I can see that could maybe mysteriously cause a bug is where the _dev_ branch currently use `current(array_keys($public_themes));` in _setup_lib.php_. It was `'four-point-seven'` previously and I'm not sure why it was changed but maybe in your case something set `current()` to the `zero` key? @Bloke?

**Comment by petecooper** [comment]
@NicolasGraph - I believe you, I must be on a different commit here. I will investigate some more today. Thanks for your continued assistance with this.

For reference, the Textpattern version suffix in `-dev` diagnostics appears to be a hash of some sort - where is that listed? I looked through https://github.com/textpattern/textpattern/blob/dev/textpattern/include/txp_diag.php and it's not clear to me where that info is located.

It would be helpful to know where I can get this, so then I can add it to the installer shell script and confirm which _actual_ version is being used.

**Comment by Bloke** [comment]
Interestingly enough, I spotted that hash the other day and wondered where it came from. At first I thought it was a holdover from SVN, then I looked at it seems to be a 'total' md5 hash of all the files and their hashes in `checksums.txt`. Might be wrong, but that seems to be the case. Should be a fixed value for any given release, so that would give us a "fingerprint" for that release.

No idea how useful that is, beyond an additional verification that the core files we've listed in the checksums file haven't been tampered with... we detect each individually anyway and display separately if anything's amiss. *shrug*.

Can't hurt, but perhaps could be made more obvious what it is. Suggestions welcome... and if it can be done without a new gtxt string being required, all the better :-)

**Comment by petecooper** [comment]
>No idea how useful that is, beyond an additional verification that the core files we've listed in the checksums file haven't been tampered with

It's useful insofar as it's less hand-wavey than "I'm using the latest version", but is perhaps an edge case that doesn't need attention. If you're able to point me to the line(s) where the calculation takes place I'll try and recreate it in bash so I can state "using version a1b2cb3etc", but this is so low on the priority list that it should probably be ignored.

**Comment by Bloke** [comment]
Look in `txplib_msic.php` at the `check_file_integrity()` function. If you include that file and call the function with `INTEGRITY_DIGEST` as its parameter, then you should get returned the value that matches the one in the diagnostics panel.

**Comment by petecooper** [comment]
I'm still not getting 100% success in the automated installer with themes, but @NicolasGraph and @philwareham _are_, so it's probably a snag at my end. Closing for now pending further poking and prodding.

Thanks, everyone!
