### ISSUE TITLE
Automated installer front-side theme - `default`, with no content

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1160]
(Current 4.7.0-dev)

### Expected behaviour

Automated setup with config for `Four Point Seven` theme should install and use `Four Point Seven` theme.

### Actual behaviour

Automated setup with config for `Four Point Seven` theme installs a theme called `default` with no content, despite console output saying `Four Point Seven` was installed.

Possible regression since themes branch was merged in?

### Steps to reproduce

Using this JSON:

```
{
    "site": {
        "lang": "en",
        "siteurl": "",
        "theme": "",
        "public_theme": "/setup/themes/four-point-seven",
        "datadir": ""
    },
    "mysql": {
        "user": "dev-demo",
        "pass": "",
        "host": "127.0.0.1",
        "db": "dev-demo",
        "table_prefix": ""
    },
    "user": {
        "realname": "Textpattern Demo Robot",
        "email": "domo-arigato-mr-roboto@example.com",
        "name": "textpattern-robot",
        "pass": ""
    }
}
```

…gives this console output:

```
Checking connectivity... done.
[OK]	Connected
[OK]	Using dev-demo. (utf8mb4)
[OK]	Creating database tables
[OK]	Lang: 'en'
[OK]	Prefs: 'data/core'
[OK]	Import: 'data/txp_category'
[OK]	Import: 'data/txp_link'
[OK]	Import: 'data/txp_section'
[OK]	Import: 'articles/articles.welcome'
[OK]	Front-side theme: '/setup/themes/four-point-seven'
[OK]	That went well!
```

…and this in the admin-side:

![safariscreensnapz001](https://user-images.githubusercontent.com/226578/36442034-5b1e3666-166c-11e8-9381-97b079d5db2c.png)

Tagging https://github.com/textpattern/textpattern/issues/1158 and https://github.com/textpattern/textpattern/issues/1101 for completeness.

**Comment by Bloke** [comment]
@NicolasGraph - eeek! Any ideas?

**Comment by phiw13** [comment]
Hmm, I’m not sure this is a regression from the most recent _themes_ refactoring. I noticed the same thing recently on a 2~2½ week old install (manual, using _setup_).

I had installed that for testing something completely unrelated, did my tests but never checked anything under Presentation at the time. I only noticed it more than a few days later, and wasn’t sure anymore what actions  I had taken previously (and then I forgot about the whole thing… flue and high fever terrorizing my body…).

**Comment by NicolasGraph** [comment]
Sorry for the delay, I will take a look tomorrow morning. -------- Message original --------Objet : Re: [textpattern/textpattern] Automated installer front-side theme - `default`, with no content (#1160)De : Stef Dawson À : textpattern/textpattern Cc : Nicolas Morand ,Mention @NicolasGraph - eeek! Any ideas?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/textpattern/textpattern","title":"textpattern/textpattern","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/textpattern/textpattern"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Bloke in #1160: @NicolasGraph - eeek! Any ideas?"}],"action":{"name":"View Issue","url":"https://github.com/textpattern/textpattern/issues/1160#issuecomment-367155685"}}}

**Comment by NicolasGraph** [comment]
@petecooper, could you let me know if changing `/setup/themes/four-point-seven` to `four-point-seven` work?

**Comment by petecooper** [comment]
@NicolasGraph - thank you for your attention on this issue. I need to update the JSON schema to fit @Bloke's changes in https://github.com/textpattern/textpattern/commit/832281e704458cde850d658ca00d09734ac57e81 - I will report back today (Thursday) with my findings.

**Comment by NicolasGraph** [comment]
Ok @petecooper, see you.

**Comment by petecooper** [comment]
Here are my findings from latest dev version tests:

***

**`"public_theme": "",`**
```
Checking connectivity... done.
[OK]	Connected
[OK]	Using dev-demo. (utf8mb4)
[OK]	Creating database tables
[OK]	Lang: 'en'
[OK]	Public theme: 'zero'
[OK]	That went well!
```
**Result**: installs `zero` theme, with 1 Sections, 2 Pages, 6 Forms, 1 Style. `four-point-seven` is not installed.

<img width="509" alt="safariscreensnapz001" src="https://user-images.githubusercontent.com/226578/36540731-5ff9282c-17d3-11e8-86c3-943cfb44775c.png">

***

**`"public_theme": "zero",`**
```
Checking connectivity... done.
[OK]	Connected
[OK]	Using dev-demo. (utf8mb4)
[OK]	Creating database tables
[OK]	Lang: 'en'
[OK]	Public theme: 'zero'
[OK]	That went well!
```
**Result**: installs `zero` theme, with 1 Sections, 2 Pages, 6 Forms, 1 Style. `four-point-seven` is not installed.

<img width="509" alt="safariscreensnapz001" src="https://user-images.githubusercontent.com/226578/36540731-5ff9282c-17d3-11e8-86c3-943cfb44775c.png">

***

**`"public_theme": "four-point-seven",`**
```
Checking connectivity... done.
[OK]	Connected
[OK]	Using dev-demo. (utf8mb4)
[OK]	Creating database tables
[OK]	Lang: 'en'
[OK]	Prefs: 'data/core'
[OK]	Import: 'data/txp_category'
[OK]	Import: 'data/txp_link'
[OK]	Import: 'data/txp_section'
[OK]	Import: 'articles/articles.welcome'
[OK]	Public theme: 'four-point-seven'
[OK]	That went well!
```
**Result**: installs `four-point-seven` theme, with 2 Sections, 3 Pages, 11 Forms, 1 Style. `zero` is not installed.

<img width="509" alt="safariscreensnapz002" src="https://user-images.githubusercontent.com/226578/36540834-bf75c99a-17d3-11e8-9ef4-9d7e9d9cb8f7.png">

***

**`"public_theme": "/setup/themes/four-point-seven",`**
```
[OK]	Connected
[OK]	Using dev-demo. (utf8mb4)
[OK]	Creating database tables
[OK]	Lang: 'en'
[OK]	Prefs: 'data/core'
[OK]	Import: 'data/txp_category'
[OK]	Import: 'data/txp_link'
[OK]	Import: 'data/txp_section'
[OK]	Import: 'articles/articles.welcome'
[OK]	Public theme: '/setup/themes/four-point-seven'
[OK]	That went well!
```

**Result**: installs `default` theme, with 0 Sections, 0 Pages, 0 Forms, 0 Styles. `zero` is not installed. `four-point-seven` is not installed.

<img width="509" alt="safariscreensnapz003" src="https://user-images.githubusercontent.com/226578/36540914-120c62ea-17d4-11e8-85df-aa1b72724265.png">

***

**`"public_theme": "Four Point Seven",`**
```
[OK]	Connected
[OK]	Using dev-demo. (utf8mb4)
[OK]	Creating database tables
[OK]	Lang: 'en'
[OK]	Prefs: 'data/core'
[OK]	Import: 'data/txp_category'
[OK]	Import: 'data/txp_link'
[OK]	Import: 'data/txp_section'
[OK]	Import: 'articles/articles.welcome'
[OK]	Public theme: 'Four Point Seven'
[OK]	That went well!
```

**Result**: installs `default` theme, with 0 Sections, 0 Pages, 0 Forms, 0 Styles. `zero` is not installed. `four-point-seven` is not installed.

<img width="509" alt="safariscreensnapz003" src="https://user-images.githubusercontent.com/226578/36540976-463d3b7a-17d4-11e8-94c6-976d74fc4701.png">

***

**Conclusion**: `"public_theme": "four-point-seven",` syntax works correctly – theme is installed and activated. Additional themes (e.g. `zero`) are not installed or activated.

I hope this is helpful @NicolasGraph and @Bloke - please tell me if you want more testing.

**Comment by petecooper** [comment]
Also, if `"public_theme": "four-point-seven",` is the expected behaviour, this issue can be closed.

**Comment by petecooper** [comment]
Actually, yes - re-reading this thread, the issue is resolved. I will close. Thanks @NicolasGraph
