### ISSUE TITLE
PHP parsing rights in articles is possibly broken

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1169]
Using latest dev version, PHP allowed in articles, and PHP examples from here: https://docs.textpattern.io/tags/php

### Expected behaviour

According to the docs, this should display `phpinfo()` output:

```
<txp:php>
    phpinfo();
</txp:php>
```

### Actual behaviour

I get: `Parse error: syntax error, unexpected '<', expecting end of file in /var/www/<snipped>/textpattern/publish/taghandlers.php(4207) : eval()'d code on line 2`

(Testing mode)

### Steps to reproduce

* create new article, enter code, publish, view

Related, if I try the second docs example:

```
<txp:php>
    echo "The current Textpattern category is: "
        .category(array(
            'title'   => '1',
            'link'    => '1',
            'wraptag' => 'div'
        ));
</txp:php>
```

…on an article with or without a category, I get: `Parse error: syntax error, unexpected 'current' (T_STRING), expecting ',' or ';' in /var/www/<snipped>/textpattern/publish/taghandlers.php(4207) : eval()'d code on line 2`

Low, anonymous diagnostics:

```
Textpattern version: 4.7.0-dev (450b7e76c02e9c6369eaac21f90ad533)
Last update: 2018-02-27 13:31:46/2018-02-27 12:00:09
Textpattern path: __TXP-ROOT/textpattern
Article URL pattern: messy
Temporary directory path: __TXP-ROOT/textpattern/tmp
PHP version: 7.0.25-0ubuntu0.16.04.1
GD Graphics Library: Unavailable
Server timezone: UTC
Server local time: 2018-02-27 13:43:05
Daylight Saving Time enabled?: 0
Automatically adjust Daylight Saving Time setting?: 0
Time zone (GMT offset in seconds): Africa/Abidjan (+0)
MySQL: 5.6.22-71.0 (Percona Server (GPL), Release 71.0, Revision 726) 
Database server time: 2018-02-27 13:43:05
Database server time offset: 0 s
Database server timezone: SYSTEM
Database session timezone: SYSTEM
Locale: en_US.UTF-8
Web server: nginx/1.10.3
PHP server API: fpm-fcgi
RFC 2616 headers: 0
Server OS: Linux 4.4.0-116-generic
Admin-side theme: hive 4.7.0-dev
```

Standing by if you need anything else.

**Comment by Bloke** [comment]
*cough* turn off textile *cough* :-)

**Comment by petecooper** [comment]
Ah! Yes! Thanks! Mea culpa, schoolboy error. Whoops.

However…different error now thrown.

I confirm `allow_article_php_scripting` is set to yes/allow, and that I have Publisher rights, in Debug mode, with Textile turned off, I get this:

```
Tag error: <txp:php>
    phpinfo();
</txp:php> ->  Textpattern Notice: Author is not permitted to use PHP code. while parsing form default on page default
```

Anything else I need to check?

**Comment by Bloke** [comment]
Try this in your article:
```
<txp:php>
global $thisarticle;
dmp(has_privs('article.php', $thisarticle['authorid']));
</txp:php>
```

If it reports anything other than '1' you need to check:
* The `article.php` entry in your `lib/admin_config.php` file reports that 1, 2 or permitted.
* The article is authored by your login.
* Your publisher privs are actually 1!
After that... not sure what else to check.

**Comment by petecooper** [comment]
Solved – article was owned by a now-deleted author, and since the article was updated the logged-in user didn't inherit the ownership, hence the wig out.

Thanks @Bloke - I appreciate the second pair of eyes and brainz!

**Comment by Bloke** [comment]
No worries. FWIW, it is annoying that Textile can mangle things to such an extent that we get PHP errors thrown but I'm not sure what else we can do about it to detect this.
