### ISSUE TITLE
Add an `All` pagination option

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1173]
Feature/functionality request: extend the pagination options to include an All button.

I'm working on a site at the moment that has (or appears to have) 160,000+ articles and thousands of users, many of which need housekeeping and/or culling based on category/section/ownership.

This site is running on monstrous hardware with plenty of headroom (former Drupal server) and I'm limited to batches of 100 for housekeeping stuffs, which is a bit of a grind.

How practical is it to add an All button alongside the respective pagination blocks in the admin area `list-navigation`?

Thanks in advance.

**Comment by philwareham** [comment]
Well, the text translation for 'all' exists - so from that side it's doable. But wouldn't trying to show 160,000 articles totally blow up your browser!?

Maybe a safer solution would be to have a '192' items option instead?

**Comment by petecooper** [comment]
>Well, the text translation for 'all' exists - so from that side it's doable. But wouldn't trying to show 160,000 articles totally blow up your browser!?

160k is an edge case, for sure…but it's a case where there are lots of attributes that mean I won't be viewing all 160k in one shot – various authors, various categories, etc. Top count so far is in the high 20,000s but I forget the actual number.

(for info, I reckon ~160k article`<tr>` blocks comes to about 275MB before any compression…so yes, the browser would struggle for a bit but the database would do most of the work – and it has 128GB of RAM and 4 Xeons to help it. Nginx wouldn't struggle with the compression at that scale.)

>Maybe a safer solution would be to have a '192' items option instead?

Almost certainly. Maybe I just need a URL hack rather than a button…

**Comment by Bloke** [comment]
No need. A tiny admin-only plugin is your friend:

```
register_callback('smd_paginate_plus', 'list_ui', 'pageby_values');

function smd_paginate_plus($evt, $stp, &$sizes)
{
   $sizes[] = 256;
   $sizes[] = 512;
   $sizes[] = 1024;
}
```
Season values to taste.

**Comment by petecooper** [comment]
Solid – thanks @Bloke!

**Comment by jpdupont** [comment]
I am very interested in the smd_paginate_plus plugin :-)
Just copy / paste this code into ied_plugin_composer?

**Comment by Bloke** [comment]
Yep:

1. Create new plugin in Plugin Composer.
2. Set its type to 'admin only' and enable it.
3. Paste the code into the code area, tweak the values to taste and Save.

**Comment by jpdupont** [comment]
Thanks !!!
And ... to upgrade this plugin to images list ???

**Comment by Bloke** [comment]
Either add a single extra regsiter callback hook, if you want to use the same pagination values:

``` php
register_callback('smd_paginate_plus', 'image_ui', 'pageby_values');
```

or go mad:

``` php
register_callback('smd_paginate_plus', 'list_ui', 'pageby_values');
register_callback('smd_paginate_plus', 'file_ui', 'pageby_values');
register_callback('smd_paginate_plus', 'image_ui', 'pageby_values');

function smd_paginate_plus($evt, $stp, &$sizes)
{
    switch ($evt) {
        case 'list_ui':
            $sizes[] = 256;
            $sizes[] = 512;
            $sizes[] = 1024;
           break;
       case 'image_ui':
       case 'file_ui':
            $sizes[] = 128;
            $sizes[] = 256;
           break;
    }
}
```

**Comment by jpdupont** [comment]
Fine Stef !
