### ISSUE TITLE
Default article admin-side hyperlinks get mangled with auto installer

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1174]
Using the current dev version with automated installer, nothing weird in the accompanying JSON file, I'm getting mangled internal hyperlinks in the default article. This is what I get in the article body – note the triple forward slashes and references to admin-side removed:

```
h3. What do you want to do next?

* Modify or delete this article? The "article list":///index.php?event=list is the place to start.
* Change this site's name, or modify the style of the URLs? It's all up to your "preferences":///index.php?event=prefs.
* Get yourself acquainted with Textile, the humane markup generator which comes with Textpattern? The basics are "simple":https://textpattern.com/textile-sandbox. If you want to learn more, you can dig into an "extensive manual":https://textpattern.com/textile-reference-manual later.
* Be guided through your "Textpattern first steps":https://textpattern.com/textpattern-first-steps by completing some basic tasks?
* Study the "Textpattern Semantic Model?":https://textpattern.com/textpattern-semantic-model
* Add "another user":///index.php?event=admin, or extend the capabilities with "third party plugins":///index.php?event=plugin you discovered from the "Textpattern plugin directory?":https://textpattern.com/plugins
* Dive in and learn by trial and error? Then please note:
** When you "write":///index.php?event=article an article you assign it to a section of your site.
** Sections use a "page template":///index.php?event=page and a "style":///index.php?event=css as an output scaffold.
** Page templates use HTML(HyperText Markup Language) and Textpattern tags (like this: @<txp:article />@) to build the markup.
** Some Textpattern tags use "forms":///index.php?event=form, which are building blocks for reusable snippets of code and markup you may build and use at your discretion.

"Textpattern tags":https://docs.textpattern.io/tags/, their attributes and values are explained and sampled within the "Textpattern User Documentation":https://docs.textpattern.io/, where you will also find valuable tips and tutorials.

There's also a crowd of friendly, helpful people over at the "Textpattern support forum":https://forum.textpattern.io/. Come and pay a visit!
```

I don't recall seeing this before, so it may have changed recently or it could be pre-beta snowblind-ness.

Can anyone else using the auto installer corroborate or deny, please?

**Comment by Bloke** [comment]
Looks like it's not picking up the admin-side URLs properly when doing the replacements in the article. @jools-r any ideas?

**Comment by jools-r** [comment]
From the output, it looks like it's not picking up the constant `ahu` or the global `$adminurl`, so you're getting the `//` from the protocol-less link and `/` before index.php together. I just tried a completely fresh installation with a multisite (`admin.sitename.com`) and regular installation(`sitename.com/textpattern`) and both produce the correct output. So is the auto installer doing something different? I'm afraid I have no experience of that.

For info: [this was the patch](https://github.com/textpattern/textpattern/commit/85f10b504bf282b57b31b098f64d129f8cfc6543#diff-f7309db96748be1cef1e8a22597532f3) that extended the existing `$siteurl` replacement to also cover `$adminurl`.

@Bloke: I know you changed some string formats recently, but this was not affected by your replacement. Should it also have been changed. It works right now just fine as is.

**Comment by jools-r** [comment]
And this was [relevant part of your commit](https://github.com/textpattern/textpattern/commit/832281e704458cde850d658ca00d09734ac57e81#diff-e8c311eb53d8dc5eabef8acbb52fb15b) (setup_lib.php) of the changed string names in the JSON file.

**Comment by Bloke** [comment]
Hmmm, I expected that if admin_url was missing then it would default to our regular `example.org/textpattern`. Maybe there's a missing/wrong test somewhere that checks if it's `''` instead of `empty()` and lets it through if defined as the empty string?

**Comment by jools-r** [comment]
Yes, that's the idea. It happens [here](https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/setup_lib.php#L37). I guess if `$cfg['site']['admin_url']` were to be set but be empty, you’d get just `http://` and the `http`would be stripped out in the xml [replaceUrl()](https://github.com/textpattern/textpattern/commit/85f10b504bf282b57b31b098f64d129f8cfc6543#diff-f7309db96748be1cef1e8a22597532f3) function to give you `//`plus (blank) plus `/`.

@petecooper: Does it work if you change [this line](https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/setup_lib.php#L37) from

```
if (!isset($cfg['site']['admin_url'])) {
```
to
```
if ( !isset($cfg['site']['admin_url']) || empty($cfg['site']['admin_url']) ) {
```

If I've got that right, that should use `$siteurl.'/textpattern'`if the config variable doesn't exist or is empty.

@Bloke: any other reasons why that might not be a good idea?

**Comment by Bloke** [comment]
That should work. In fact you can get away with just the empty as it incorporates an isset.
```
if (empty($cfg['site']['admin_url']) { ... }
```

**Comment by jools-r** [comment]
Thanks, didn't know that. That’s even simpler and works on my test installation.

@petecooper: does it work for you with the automatic installer?

**Comment by petecooper** [comment]
Just back at my desk now - I'll digest the thread and see what I can find out, and report back.

Thanks @jools-r and @Bloke for your time and attention on this.

**Comment by petecooper** [comment]
OK, some progress:

* using the updated code outlined [here](https://github.com/textpattern/textpattern/issues/1174#issuecomment-369373948)

![re](https://user-images.githubusercontent.com/226578/36840763-10286c70-1d3e-11e8-9ca5-ef559f6beae2.png)

* using this JSON:

```
{
    "site": {
        "language_code": "en",
        "public_url": "",
        "admin_url": "",
        "admin_theme": "",
        "public_theme": "four-point-seven",
        "content_directory": "",
        "cookie_domain": ""
    },
    "database": {
        "user": "dev-demo",
        "password": "snipped",
        "host": "127.0.0.1",
        "db_name": "dev-demo",
        "charset": "",
        "table_prefix": "",
        "client_flags": ""
    },
    "user": {
        "full_name": "Textpattern Demo Robot",
        "email": "domo-arigato-mr-roboto@example.com",
        "login_name": "textpattern-robot",
        "password": "snipped"
    }
}
```

…the default article now defaults to:

```
h3. What do you want to do next?

* Modify or delete this article? The "article list":///textpattern/index.php?event=list is the place to start.
* Change this site's name, or modify the style of the URLs? It's all up to your "preferences":///textpattern/index.php?event=prefs.
* Get yourself acquainted with Textile, the humane markup generator which comes with Textpattern? The basics are "simple":https://textpattern.com/textile-sandbox. If you want to learn more, you can dig into an "extensive manual":https://textpattern.com/textile-reference-manual later.
* Be guided through your "Textpattern first steps":https://textpattern.com/textpattern-first-steps by completing some basic tasks?
* Study the "Textpattern Semantic Model?":https://textpattern.com/textpattern-semantic-model
* Add "another user":///textpattern/index.php?event=admin, or extend the capabilities with "third party plugins":///textpattern/index.php?event=plugin you discovered from the "Textpattern plugin directory?":https://textpattern.com/plugins
* Dive in and learn by trial and error? Then please note:
** When you "write":///textpattern/index.php?event=article an article you assign it to a section of your site.
** Sections use a "page template":///textpattern/index.php?event=page and a "style":///textpattern/index.php?event=css as an output scaffold.
** Page templates use HTML(HyperText Markup Language) and Textpattern tags (like this: @<txp:article />@) to build the markup.
** Some Textpattern tags use "forms":///textpattern/index.php?event=form, which are building blocks for reusable snippets of code and markup you may build and use at your discretion.

"Textpattern tags":https://docs.textpattern.io/tags/, their attributes and values are explained and sampled within the "Textpattern User Documentation":https://docs.textpattern.io/, where you will also find valuable tips and tutorials.

There's also a crowd of friendly, helpful people over at the "Textpattern support forum":https://forum.textpattern.io/. Come and pay a visit!
```

…so the `textpattern` URL component is now being found but there's still a triple forward slash.

**Comment by petecooper** [comment]
If the action of leaving `admin_url` blank is a show-stopper, then I can obviously add that in and – presto – problem solved, but it would be great to iron these snags out before wider release.

**Comment by Bloke** [comment]
Please take out the `!isset()` test and just use the single `empty()` test, as defined in [this comment](https://github.com/textpattern/textpattern/issues/1174#issuecomment-369525741). Then try again and see if anything changes.

**Comment by petecooper** [comment]
@Bloke – thanks, got the same result:

* using https://github.com/textpattern/textpattern/issues/1174#issuecomment-369525741 code changes…

![re](https://user-images.githubusercontent.com/226578/36841704-0b3f1b5c-1d41-11e8-9833-7edb24fb6027.png)


* and same JSON as https://github.com/textpattern/textpattern/issues/1174#issuecomment-369554023

…default article is:

```
h3. What do you want to do next?

* Modify or delete this article? The "article list":///textpattern/index.php?event=list is the place to start.
* Change this site's name, or modify the style of the URLs? It's all up to your "preferences":///textpattern/index.php?event=prefs.
* Get yourself acquainted with Textile, the humane markup generator which comes with Textpattern? The basics are "simple":https://textpattern.com/textile-sandbox. If you want to learn more, you can dig into an "extensive manual":https://textpattern.com/textile-reference-manual later.
* Be guided through your "Textpattern first steps":https://textpattern.com/textpattern-first-steps by completing some basic tasks?
* Study the "Textpattern Semantic Model?":https://textpattern.com/textpattern-semantic-model
* Add "another user":///textpattern/index.php?event=admin, or extend the capabilities with "third party plugins":///textpattern/index.php?event=plugin you discovered from the "Textpattern plugin directory?":https://textpattern.com/plugins
* Dive in and learn by trial and error? Then please note:
** When you "write":///textpattern/index.php?event=article an article you assign it to a section of your site.
** Sections use a "page template":///textpattern/index.php?event=page and a "style":///textpattern/index.php?event=css as an output scaffold.
** Page templates use HTML(HyperText Markup Language) and Textpattern tags (like this: @<txp:article />@) to build the markup.
** Some Textpattern tags use "forms":///textpattern/index.php?event=form, which are building blocks for reusable snippets of code and markup you may build and use at your discretion.

"Textpattern tags":https://docs.textpattern.io/tags/, their attributes and values are explained and sampled within the "Textpattern User Documentation":https://docs.textpattern.io/, where you will also find valuable tips and tutorials.

There's also a crowd of friendly, helpful people over at the "Textpattern support forum":https://forum.textpattern.io/. Come and pay a visit!
```

**Comment by petecooper** [comment]
More findings to consider.

Using current dev with no code changes.

**Specify `public_url` in JSON:**

```
    "site": {
        "language_code": "en",
        "public_url": "dev-demo.textpattern.co",
        "admin_url": "",
        "admin_theme": "",
        "public_theme": "four-point-seven",
        "content_directory": "",
        "cookie_domain": ""
    },
```

Result (excerpt): `The "article list":///index.php?event=list is the place to start.`

**Specify `public_url` and `admin_url` in JSON:**

```
    "site": {
        "language_code": "en",
        "public_url": "dev-demo.textpattern.co",
        "admin_url": "dev-demo.textpattern.co/textpattern",
        "admin_theme": "",
        "public_theme": "four-point-seven",
        "content_directory": "",
        "cookie_domain": ""
    },
```

Result (excerpt): `The "article list"://dev-demo.textpattern.co/textpattern/index.php?event=list is the place to start.`

**Specify `admin_url` in JSON:**

```
    "site": {
        "language_code": "en",
        "public_url": "",
        "admin_url": "dev-demo.textpattern.co/textpattern",
        "admin_theme": "",
        "public_theme": "four-point-seven",
        "content_directory": "",
        "cookie_domain": ""
    },
```

Result (excerpt): `The "article list"://dev-demo.textpattern.co/textpattern/index.php?event=list is the place to start.`

**Comment by Bloke** [comment]
Weird. I totally expected that `empty()` test to set the default value if the `admin_url` is missing or set to nothing.

Something else is it play then. So, in your current version can you please dump out some debug info just before line 31 https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/setup_lib.php#L31

```
dmp("CONFIG FILE CONTENT", $cfg);
```

And then after it's done the supposed assignment on line 46: https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/setup_lib.php#L46:

```
dmp("SITE/ADMIN URL", $siteurl, $adminurl);
```

What's baffling me is it's not even using the domain. If it's setting the adminurl properly here then maybe the replacement is failing for some reason in TxpXML.

Maybe we could also extend the debugging to here https://github.com/textpattern/textpattern/blob/dev/textpattern/vendors/Textpattern/Import/TxpXML.php#L219:

```
dmp("REPLACED TEXT", $txt);
```

Gotta track this down somewhere...

**Comment by petecooper** [comment]
Thanks @Bloke – here goes:

* using code changes outlined [here](https://github.com/textpattern/textpattern/issues/1174#issuecomment-369568654)

![terminalscreensnapz004](https://user-images.githubusercontent.com/226578/36844193-a00a9dee-1d49-11e8-8790-d8a6dad2bd3c.png)


```
$ sudo php /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/setup/setup.php --config="/var/www/vhosts/textpattern.co/dev-demo/staging/dev-demo.json"
[OK]	Connected
[OK]	Using dev-demo. (utf8mb4)
<pre dir="auto">
CONFIG FILE CONTENT
array (
  &#039;site&#039; =&gt; 
  array (
    &#039;language_code&#039; =&gt; &#039;en&#039;,
    &#039;public_url&#039; =&gt; &#039;&#039;,
    &#039;admin_url&#039; =&gt; &#039;&#039;,
    &#039;admin_theme&#039; =&gt; &#039;&#039;,
    &#039;public_theme&#039; =&gt; &#039;four-point-seven&#039;,
    &#039;content_directory&#039; =&gt; &#039;&#039;,
    &#039;cookie_domain&#039; =&gt; &#039;&#039;,
  ),
  &#039;database&#039; =&gt; 
  array (
    &#039;user&#039; =&gt; &#039;dev-demo&#039;,
    &#039;password&#039; =&gt; &#039;[SNIPPED]&#039;,
    &#039;host&#039; =&gt; &#039;127.0.0.1&#039;,
    &#039;db_name&#039; =&gt; &#039;dev-demo&#039;,
    &#039;charset&#039; =&gt; &#039;utf8mb4&#039;,
    &#039;table_prefix&#039; =&gt; &#039;&#039;,
    &#039;client_flags&#039; =&gt; 0,
  ),
  &#039;user&#039; =&gt; 
  array (
    &#039;full_name&#039; =&gt; &#039;Textpattern Demo Robot&#039;,
    &#039;email&#039; =&gt; &#039;domo-arigato-mr-roboto@example.com&#039;,
    &#039;login_name&#039; =&gt; &#039;textpattern-robot&#039;,
    &#039;password&#039; =&gt; &#039;[SNIPPED]&#039;,
  ),
)
</pre>
<pre dir="auto">
SITE/ADMIN URL
http://
http://
</pre>
[OK]	Creating database tables
[OK]	Lang: 'en'
[OK]	Prefs: 'data/core'
[OK]	Import: 'data/txp_category'
[OK]	Import: 'data/txp_link'
[OK]	Import: 'data/txp_section'
[OK]	Import: 'articles/articles.welcome'
[OK]	Public theme: 'four-point-seven'
[OK]	That went well!

```

**Comment by Bloke** [comment]
Well first of all it seems like it's not picking up your public site url in the config file. That's a mandatory component of the installation process, so if it's missing we need to figure out why. If it's definitely in your config file (as indicated by earlier posts) then it could be getting overwritten by something earlier in the process. We'll have to dig deeper if that's the case.

Does the result of the admin URL alter if you also employ the code change that uses the `empty()` instead of the `!isset()`? I think that's definitely a bug we'll need to fix, so assume it's going to appear in core today.

**Comment by petecooper** [comment]
Ah – OK, it wasn't clear to me that the public site was mandatory. Stand by, I'll re-test.

**Comment by petecooper** [comment]
OK, now I've updated the JSON to include the `public_url`, and here's the output from the auto install:

```
$ sudo php /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/setup/setup.php --config="/var/www/vhosts/textpattern.co/dev-demo/staging/dev-demo.json"
[OK]	Connected
[OK]	Using dev-demo. (utf8mb4)
<pre dir="auto">
CONFIG FILE CONTENT
array (
  &#039;site&#039; =&gt; 
  array (
    &#039;language_code&#039; =&gt; &#039;en&#039;,
    &#039;public_url&#039; =&gt; &#039;dev-demo.textpattern.co&#039;,
    &#039;admin_url&#039; =&gt; &#039;&#039;,
    &#039;admin_theme&#039; =&gt; &#039;&#039;,
    &#039;public_theme&#039; =&gt; &#039;four-point-seven&#039;,
    &#039;content_directory&#039; =&gt; &#039;&#039;,
    &#039;cookie_domain&#039; =&gt; &#039;&#039;,
  ),
  &#039;database&#039; =&gt; 
  array (
    &#039;user&#039; =&gt; &#039;dev-demo&#039;,
    &#039;password&#039; =&gt; &#039;[SNIPPED]&#039;,
    &#039;host&#039; =&gt; &#039;127.0.0.1&#039;,
    &#039;db_name&#039; =&gt; &#039;dev-demo&#039;,
    &#039;charset&#039; =&gt; &#039;utf8mb4&#039;,
    &#039;table_prefix&#039; =&gt; &#039;&#039;,
    &#039;client_flags&#039; =&gt; 0,
  ),
  &#039;user&#039; =&gt; 
  array (
    &#039;full_name&#039; =&gt; &#039;Textpattern Demo Robot&#039;,
    &#039;email&#039; =&gt; &#039;domo-arigato-mr-roboto@example.com&#039;,
    &#039;login_name&#039; =&gt; &#039;textpattern-robot&#039;,
    &#039;password&#039; =&gt; &#039;[SNIPPED]&#039;,
  ),
)
</pre>
<pre dir="auto">
SITE/ADMIN URL
http://dev-demo.textpattern.co
http://
</pre>
[OK]	Creating database tables
[OK]	Lang: 'en'
[OK]	Prefs: 'data/core'
[OK]	Import: 'data/txp_category'
[OK]	Import: 'data/txp_link'
[OK]	Import: 'data/txp_section'
[OK]	Import: 'articles/articles.welcome'
[OK]	Public theme: 'four-point-seven'
[OK]	That went well!
```

Correctly picks up the site (public) URL, doesn't figure out the admin URL.

**Comment by jools-r** [comment]
Forgive me if I'm muddling things, but your screenshot [in the thread above](https://github.com/textpattern/textpattern/issues/1174#issuecomment-369572918) with the added `dmp(…)` insertions shows the `if(!isset(…` and not the `if(empty(…` code.

**Comment by Bloke** [comment]
Is it reasonable to expect public_url as mandatory? Without that, the site can't function, right? And we can't populate the site URL pref, which is pretty vital.

So if it's not set in the config file, should we abort? Or can it soldier on and guess the URL based on some other values we can obtain?

**Comment by petecooper** [comment]
>Forgive me if I'm muddling things, but your screenshot in the thread above with the added dmp(…) insertions shows the if(!isset(… and not the if(empty(… code.

Good spot – my apologies. I'll reconnect and re-run the tests.

**Comment by petecooper** [comment]
>Is it reasonable to expect public_url as mandatory? Without that, the site can't function, right? And we can't populate the site URL pref, which is pretty vital.

Yes, very reasonable. The GUI sniffs it out, so the CLI needs some way of doing the same.

>So if it's not set in the config file, should we abort? Or can it soldier on and guess the URL based on some other values we can obtain?

The installer does work but leaves the URL blank internally, which is totally OK because it's only the default stuff that has the missing URL components, which makes perfect sense.

Most straightforward thing would be to have the URL set to mandatory, I'm Captain Guinea Pig for this stuff at the moment and I wasn't aware it was mandatory…but then how else would the URL be found from a CLI? It won't.

So yeah, I'll make it more obvious that it's mandatory.

**Comment by petecooper** [comment]
Checking in –

* three changes made to `setup_lib.php` (2x `dmp` entries from https://github.com/textpattern/textpattern/issues/1174#issuecomment-369568654 and 1x from https://github.com/textpattern/textpattern/issues/1174#issuecomment-369525741 )

![re](https://user-images.githubusercontent.com/226578/36851502-4325ebf2-1d61-11e8-95f3-34c8e5604ab6.png)

…which, gives me this:

```
$ sudo php /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/setup/setup.php --config="/var/www/vhosts/textpattern.co/dev-demo/staging/dev-demo.json"
[OK]	Connected
[OK]	Using dev-demo. (utf8mb4)
<pre dir="auto">
CONFIG FILE CONTENT
array (
  &#039;site&#039; =&gt; 
  array (
    &#039;language_code&#039; =&gt; &#039;en&#039;,
    &#039;public_url&#039; =&gt; &#039;dev-demo.textpattern.co&#039;,
    &#039;admin_url&#039; =&gt; &#039;&#039;,
    &#039;admin_theme&#039; =&gt; &#039;&#039;,
    &#039;public_theme&#039; =&gt; &#039;four-point-seven&#039;,
    &#039;content_directory&#039; =&gt; &#039;&#039;,
    &#039;cookie_domain&#039; =&gt; &#039;&#039;,
  ),
  &#039;database&#039; =&gt; 
  array (
    &#039;user&#039; =&gt; &#039;dev-demo&#039;,
    &#039;password&#039; =&gt; &#039;[SNIPPED]&#039;,
    &#039;host&#039; =&gt; &#039;127.0.0.1&#039;,
    &#039;db_name&#039; =&gt; &#039;dev-demo&#039;,
    &#039;charset&#039; =&gt; &#039;utf8mb4&#039;,
    &#039;table_prefix&#039; =&gt; &#039;&#039;,
    &#039;client_flags&#039; =&gt; 0,
  ),
  &#039;user&#039; =&gt; 
  array (
    &#039;full_name&#039; =&gt; &#039;Textpattern Demo Robot&#039;,
    &#039;email&#039; =&gt; &#039;domo-arigato-mr-roboto@example.com&#039;,
    &#039;login_name&#039; =&gt; &#039;textpattern-robot&#039;,
    &#039;password&#039; =&gt; &#039;[SNIPPED]&#039;,
  ),
)
</pre>
<pre dir="auto">
SITE/ADMIN URL
http://dev-demo.textpattern.co
http://dev-demo.textpattern.co/textpattern
</pre>
[OK]	Creating database tables
[OK]	Lang: 'en'
[OK]	Prefs: 'data/core'
[OK]	Import: 'data/txp_category'
[OK]	Import: 'data/txp_link'
[OK]	Import: 'data/txp_section'
[OK]	Import: 'articles/articles.welcome'
[OK]	Public theme: 'four-point-seven'
[OK]	That went well!
```

Default article:

```
h3. What do you want to do next?

* Modify or delete this article? The "article list"://dev-demo.textpattern.co/textpattern/index.php?event=list is the place to start.
* Change this site's name, or modify the style of the URLs? It's all up to your "preferences"://dev-demo.textpattern.co/textpattern/index.php?event=prefs.
* Get yourself acquainted with Textile, the humane markup generator which comes with Textpattern? The basics are "simple":https://textpattern.com/textile-sandbox. If you want to learn more, you can dig into an "extensive manual":https://textpattern.com/textile-reference-manual later.
* Be guided through your "Textpattern first steps":https://textpattern.com/textpattern-first-steps by completing some basic tasks?
* Study the "Textpattern Semantic Model?":https://textpattern.com/textpattern-semantic-model
* Add "another user"://dev-demo.textpattern.co/textpattern/index.php?event=admin, or extend the capabilities with "third party plugins"://dev-demo.textpattern.co/textpattern/index.php?event=plugin you discovered from the "Textpattern plugin directory?":https://textpattern.com/plugins
* Dive in and learn by trial and error? Then please note:
** When you "write"://dev-demo.textpattern.co/textpattern/index.php?event=article an article you assign it to a section of your site.
** Sections use a "page template"://dev-demo.textpattern.co/textpattern/index.php?event=page and a "style"://dev-demo.textpattern.co/textpattern/index.php?event=css as an output scaffold.
** Page templates use HTML(HyperText Markup Language) and Textpattern tags (like this: @<txp:article />@) to build the markup.
** Some Textpattern tags use "forms"://dev-demo.textpattern.co/textpattern/index.php?event=form, which are building blocks for reusable snippets of code and markup you may build and use at your discretion.

"Textpattern tags":https://docs.textpattern.io/tags/, their attributes and values are explained and sampled within the "Textpattern User Documentation":https://docs.textpattern.io/, where you will also find valuable tips and tutorials.

There's also a crowd of friendly, helpful people over at the "Textpattern support forum":https://forum.textpattern.io/. Come and pay a visit!
```

URLs are being found, protocol-less URLs (`//example.com/textpattern/index.php`) are being used – which is actually really smart because that sidesteps the http/https sniffing.

In that respect, it's working with the changes outlined. Hurrah! Thank you @jools-r @Bloke for your time and expertise, very much appreciated.

Do any core code changes need making? I'll close the issue since it's resolved.

**Comment by Bloke** [comment]
See 2b516024.

**Comment by jools-r** [comment]
Nice! Glad it worked.
