### ISSUE TITLE
plugin-help should use `.txp-layout-4col-3span` class for the content column

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1176]
Currently it uses `.txp-layout-4col-2span`.

Issues with this:
* it breaks the expectation for a theme that the layout is always based on a 4 column grid
* the content column can end up quite narrow, depending on window width…
* …resulting in very short line-lengths (and hard to read text), depending on the font-size.

Ok, I get it, you use that class because otherwise Hive will have very long lines on larger windows. I consider that a bug in Hive. The `.txp-prefs-group` should set a `max-width` (for the Preferences panel, Hive worked around the issue by constraining the length of the label block).

(and aside - maybe for TXP 4.8 we can revise slightly that `.txp-prefs-group` class naming… and make the JQUI vertical tabs more generic)

fix the line-length issue:
* option 1: Hive add a `max-width` to the `.txp-prefs-group` class 
* option 2: Add the class `.txp-layout-textbox` to each `.txp-prefs-group`

The second option _may_ cause issues (auto left/right margins). On the flip side, my Sandspace theme has some text optimizations on that particular class to make Help text more enjoyable. I would get it automatically for the new help layout (but I don’t mind making some adjustments to my stylesheet.

**Comment by Bloke** [comment]
Nicolas mentioned something in the [pull request](https://github.com/textpattern/textpattern/pull/1171) about using different class names here. Is it related to this issue?

**Comment by phiw13** [comment]
> Nicolas mentioned something in the pull request description about using different class names here. Is it related to this issue?

That would mostly deal with my *aside* in the OP

**Comment by phiw13** [comment]
A few screenshots to illustrate the issue: https://dev.l-c-n.com/_b/txp-plh

the “iPad“ screenshots are taken in Safari’s responsive view widget. The iMac one is my default-sized browser window; I hacked a bit to illustrate the text size my personal copy of Sandspace would use.

**Comment by philwareham** [comment]
Thanks for the details guys, I’ll try to fix later today.

**Comment by NicolasGraph** [comment]
I'm available to help now if needed.
I used `.txp-layout-4col-2span` to increase readability on large screens but if it causes issues with smaller sizes, @phiw13 suggestions seem appropriate.
Let me know if and how I can help.

**Comment by philwareham** [comment]
Can you let me know a plugin that uses this new feature, so I can check it out?

**Comment by Bloke** [comment]
com_connect should demonstrate it well.

**Comment by philwareham** [comment]
Aside: `.txp-prefs-group` in Hive (and Classic) already had a max-width rule. The simple fix for the original issue is to use `.txp-layout-4col-3span` which is the correct span for a 4 column layout. I'll sort it out.

**Comment by phiw13** [comment]
Thanks. Plugin-help is now much more usable.

(hmm + 112b to the weight of my stylesheet…)

**Comment by philwareham** [comment]
Yes, I've kept the old `.txp-prefs-group` in the stylesheet for legacy reasons. I'll remove it at Textpattern 4.8 to save a few bytes.
