### ISSUE TITLE
Pophelp doesn't render on new PHP 7 installs

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1177]
### Expected behaviour

Pophelp renders when clicking help topic.

### Actual behaviour

Popup window contains:
```
Fatal error: Uncaught Error: Function name must be a string in /path/to/textpattern/vendors/Textpattern/Module/Help/HelpAdmin.php:55
Stack trace: #0 /path/to/textpattern/lib/txplib_misc.php(1945):
Textpattern\Module\Help\HelpAdmin::init('help', 'pophelp')
#1 /path/to/textpattern/index.php(255):
callback_event('help', 'pophelp', 0)
#2 {main} thrown in /path/to/textpattern/vendors/Textpattern/Module/Help/HelpAdmin.php on line 55
```

### Steps to reproduce

1. Install brand new 4.7.0-dev on a PHP 7.0.0 host environment.
2. Log in, visit any admin-side tab with a '?' pophelp topic and click it.

I'm unsure if this is because the `HelpAdmin` methods are static and the `register_callback()` in `index.php` can't handle that for some reason under PHP 7. Or if our callback system needs tweaking to cater to the stricter runtime environment in PHP 7. Or if it's a bug in PHP 7.0.x.

Works fine on PHP 5.6.10. Haven't tried later PHP versions. I've been hacking away for a while and can't figure out a fix. Anyone else any ideas on a fix, or test case results on different versions of PHP? @bloatware ? @makss ? @petecooper ? Anyone?!

**Comment by Bloke** [comment]
Further thought: when setting up the callback, should we use something like:

```
$string = new \Textpattern\Type\StringType($func_name);
$func_name = $string->toCallback();
```

Or is that merely a convenience function to allow us to specify callbacks with `->` and `::` in them?

**Comment by bloatware** [comment]
Can not reproduce (PHP 5.4 neither 7.1). It seems to complain about `$step` in
```
            self::$step();
```
of  `/textpattern/vendors/Textpattern/Module/Help/HelpAdmin.php:55`. What if you replace `$step` with `pophelp`, to test?

And `toCallback()` is merely for convenience, imo.

**Comment by Bloke** [comment]
Yeah that works fine. I was just hoping to find a more scientific solution or cause, as it might be indicative of something that'll bite us in core. But if it's not reproducible in later PHP versions, perhaps it's a bug in 7.0.0 that got squashed in one of the many updates since then. I combed the changelog but couldn't find anything of significance (though it was late).

**Comment by bloatware** [comment]
Have you tried to dump the faulty `$step` somehow?

**Comment by Bloke** [comment]
Yes, and it shows up as a string, right before the call to `self::$step()`! Baffling.

However, if I dump the contents of the `$c` in the `callback_event()` function, the admin help entries have no 'step' defined in the passed array, whereas every other callback registered by core does. Further, the object passed as the function is an actual object in all cases _except_ the admin helper. That's presented as the string `\Textpattern\Module\Help\HelpAdmin` as defined in `index.php`.

Something's afoot and I can't put my finger on it.

**Comment by bloatware** [comment]
Then we should probably
```
register_callback('\Textpattern\Module\Help\HelpAdmin::init', 'help');
```

**Comment by Bloke** [comment]
That'll do! Thank you.
