### ISSUE TITLE
Manage plugin help tables of contents

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#1180]
I was wondering…
Should I provide a way for plugin authors to hide a section on plugin help rendering?
It would be mainly used for tables of contents which are now useless — tabs doing the job. It would allow plugin authors to keep their tables of contents for Txp < 4.7 (or as a fallback?) but hide it for the last release by adding an id or a class to the table header.

Related issue: https://github.com/textpattern/com_connect/issues/60
_arc_vimeo_ and _yab_review_rating_ also have this kind of "useless" tables.

**Comment by NicolasGraph** [comment]
> How would you detect a table of contents that is built into the plugin and hide it?

it should be formated like so:

```
<h1>Unique first-level header</h1>

Any kind of optional presentation.

<h2 id="table-of-contents">First tab/section</h2>

…

<h2>First tab/section</h2>

…

<h2>Second tab/section</h2>

 … 
```

**Comment by philwareham** [comment]
I'd rather plugin authors just eventually update their READMEs for 4.7 instead of hiding content via CSS or whatever. If they, in the short term, show a TOC section that it's not the end of the world (and conversely if they remove it and 4.6 or earlier lose a TOC again it's not that bad). IMHO.

**Comment by NicolasGraph** [comment]
Ok, thanks @philwareham, I let @Bloke deciding to close or feed this issue. If closed, I'll let @trenc and @drmonkeyninja know that their plugin help file would need a minor enhancement.

**Comment by Bloke** [comment]
I agree. Not a huge issue if a bit of content is duplicated. Plugins will need updating anyway.

Can we divert the effort into updating the "Writing a plugin" documentation on docs.textpattern.io? That could do with some love. [See here](https://docs.textpattern.io/development/plugin-user-help-guidelines).

**Comment by NicolasGraph** [comment]
> Can we divert the effort into updating the "Writing a plugin" documentation on docs.textpattern.io? That could do with some love.

Yes, we should remove the TOC suggestion at least.

**Comment by philwareham** [comment]
There's a lot of documentation that needs writing for 4.7 release: themes features (writing themes, installing and updating themes, etc), plugins authoring and recommended layout. Not to mention the many current documentation pages that haven't fully been fixed from the old Wiki for the new docs site. Phew :/

It's an ongoing process though - I thin the themes documentation is the most urgent.

**Comment by Bloke** [comment]
> I think the themes documentation is the most urgent.

Hey @NicolasGraph if you're at a loose end.... :-)

**Comment by NicolasGraph** [comment]
> I think the themes documentation is the most urgent.

Soory, I often do easier things first… 😉

**Comment by philwareham** [comment]
I'll help where I can to whoever claims that task.

**Comment by NicolasGraph** [comment]
> […] but obviously you are both very suited to that since you created the feature.

I knew it was a trap.

> Seriously […]

Ok, I'll try my best to help with my frenglish.

**Comment by philwareham** [comment]
Great! As long as the bare bones and structure are there I can flesh it out over time. I'll proof read any doc writing anyway. Anything is better then what's currently there! https://docs.textpattern.io/themes/

**Comment by bloatware** [comment]
Don't wanna open a new issue, so posting here. Clicking inline anchor links to sections in plugin help do not seem to open the corresponding section, even with corrected anchors.

**Comment by Bloke** [comment]
Weird, it did for me the other night on the batch of plugins I tried. I wonder if something's changed in the meantime?

**Comment by NicolasGraph** [comment]
I think that it comes from the way jQuery tabs work. If you try to add an anchor link which is linked to any id but a section, it should work.

**Comment by NicolasGraph** [comment]
Sorry, I need to test once more but in fact I guess it works only if the anchor is linked to an id in the same tab.

**Comment by bloatware** [comment]
I'm testing it on `Restore points` tab of `ied_plugin_composer` help. Clicking on `...?event=plugin&step=plugin_help&name=ied_plugin_composer#ied_plugin_list` does not seem to open `List panel` tab. I have tried to change the anchor to `...?event=plugin&step=plugin_help&name=ied_plugin_composer#plugin_help_section_list_panel`, but still no luck.

**Comment by NicolasGraph** [comment]
Which plugin are you testing please? I fail to edit the _com_connect_ help with _ied_plugin_composer_.

**Comment by bloatware** [comment]
`ied_plugin_composer` itself :-)

**Comment by NicolasGraph** [comment]
> ied_plugin_composer itself :-)

oh, ok… I'm gonna try, thanks.

**Comment by philwareham** [comment]
These might help:

https://www.sitepoint.com/community/t/jquery-tabs-linking-to-anchors-within-a-closed-tab/11876

https://blog.edwardawebb.com/site-news/link-element-ids-jquery-tabs-read-stateless

**Comment by bloatware** [comment]
Quick'n'dirty fix landed, please feel free to improve.

**Comment by NicolasGraph** [comment]
Nothing better for now, Thanks @bloatware (https://github.com/textpattern/textpattern/commit/62929df599997d4d0a60277edf5b0d363c83b365).

**Comment by NicolasGraph** [comment]
@bloatware, it seems that there is [no need to create an extra anchor](https://github.com/textpattern/textpattern/commit/e7903c890599f19e800aaeb4a220330f90aa42e0). Could you just tell me if there was a reason I missed to do that, otherwise I'll send a PR with another commit related to this feature. Thanks!

**Comment by bloatware** [comment]
Thanks @NicolasGraph, works great in my W7 FF58.
