### ISSUE TITLE
Parsing HTML entities – inconsistencies between article elements

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1184]
_Not a beta showstopper._

Current `dev` build.

### Overview

Some HTML entities aren't handled very cleanly in public-side category titles across article elements, e.g. `title` and `category2`, and there's some inconsistency.

### Steps to reproduce

* vanilla `dev` install
* modify an existing category or create a new one to include an encoded HTML entity
* modify an existing article or create a new one to include a title with an encoded HTML entity
* replace or add the following (example) test markup:

```
<txp:title escape="" /> (escape empty)
<txp:title escape="html" /> (escape html)

<txp:category2 escape="" title="1" /> (escape empty)
<txp:category2 escape="html" title="1" /> (escape html)
```

### Example

Prepend `&#10003;` (check mark/tick) to `Meaningful labor`:

![screen shot 2018-03-06 at 11 15 06](https://user-images.githubusercontent.com/226578/37029914-eefaffc6-2130-11e8-8ed5-e6d343e5adad.png)

Note parsed entity on admin-side category list:

![screen shot 2018-03-06 at 11 15 18](https://user-images.githubusercontent.com/226578/37029938-064968b6-2131-11e8-8a54-231ba52ac62d.png)

Prepend default article title with `&#10003;` and replace body text:

<img width="433" alt="screen shot 2018-03-06 at 11 27 54" src="https://user-images.githubusercontent.com/226578/37030113-a10fb12a-2131-11e8-9c7f-c0644d4ccbeb.png">

Note parsed entity on admin-side article list title and category:

<img width="882" alt="screen shot 2018-03-06 at 11 46 27" src="https://user-images.githubusercontent.com/226578/37030778-1eb6aab4-2134-11e8-8ac7-3457535d0a55.png">

Note rendering differences in parsed entities on public side:

![screen shot 2018-03-06 at 11 18 09](https://user-images.githubusercontent.com/226578/37030148-c1a047ce-2131-11e8-8ce1-d1a5d51ede02.png)

Site is in debug mode, no errors thrown.

**Comment by petecooper** [comment]
Note to self: this potentially extends beyond `category1` and `category2` – investigate other article elements.

**Comment by Bloke** [comment]
Yep, this needs attention, thank for highlighting it. Probably a rogue `txpspecialchars` or other encoding in the tag. If you do manage to sniff any more of this stuff out, that'd be appreciated.

**Comment by bloatware** [comment]
That was already the case in [4.6](https://github.com/textpattern/textpattern/blob/ff45a15e4052eabc3b58b8f23d189455d7f5bdf1/textpattern/publish/taghandlers.php#L2910). My only concern re dropping `txpspecialchars()` here is bw compatibility. Shall we?

**Comment by Bloke** [comment]
If dropping `txpsepcialchars()` is just for visuals and introduces no security considerations, then I say the greater good is to make it look better and consistent.

Alternatively, can we harness `escape` in such a way that outputting it raw becomes an option? Backwards compat is retained but someone has the option to change that. I'm thinking of something along the lines of the same way that `escape=""` in custom fields works: default to `escape="html"`.

Pros? Cons?

**Comment by bloatware** [comment]
Glad we think alike :-) There should be no more security hazard than with custom fields. Will do.

**Comment by bloatware** [comment]
Before I commit: is `category tag` a valid `rel` attribute value, or should we replace it with `tag`?

**Comment by bloatware** [comment]
I thought it was for [microformats](http://microformats.org/wiki/rel-category)?

**Comment by bloatware** [comment]
Actually, many other tags that had no `escape` attribute in 4.6 will act inconsistently in 4.7, but this can only be fixed on a tag-by-tag basis.

**Comment by philwareham** [comment]
Most of the older `rel` attributes were never ratified for HTML5. A load of them have been 'proposed' for years now and never ratified so I'd take that as they'll never be. Probably rightly so, there were way too many values previously IMO.

**Comment by Bloke** [comment]
My editor counts 80+ uses of `txpspecialchars()` in `taghandlers.php`. Granted, some of them are mandatory (anchor `title` attributes, for example) and some are used more than once in the same tag, but that's still a whole heap of tags that need to be checked.

Is it worth ploughing through them now and checking they work as expected when using `escape` or shall we mop this stuff up between beta and final? Not quite sure about the level of work involved here.

**Comment by petecooper** [comment]
>Is it worth ploughing through them now and checking they work as expected when using escape or shall we mop this stuff up between beta and final? Not quite sure about the level of work involved here.

It's very much a post-beta task, in my opinion. The scope is potentially big, no need to wait for beta.

**Comment by bloatware** [comment]
They can't be both bw compatible and 100% consistent with the "standard" global atts behavior anyway, because they add some markup to data. If we have few days before beta, I can patch article related tags, but it's not critical.

**Comment by Bloke** [comment]
Nah, let's do it post-beta. People might find other tag-related stuff anyway so we can pick it all up together. Thanks for fixing the category tags, does it work for you now, Pete?

Let's leave this open to remind us to look at it over the next few weeks.

**Comment by petecooper** [comment]
>Thanks for fixing the category tags, does it work for you now, Pete?

Just now, same test markup:

![screen shot 2018-03-07 at 13 06 58](https://user-images.githubusercontent.com/226578/37093801-8735e60c-2208-11e8-9325-07006fc370e6.png)

Fixed! Thanks very much @bloatware!

I think I've found another minor snag with the trailing `;`, but it's definitely a post-beta issue so I'll hold onto it for a few days to investigate and provide evidence.

**Comment by philwareham** [comment]
Is this issue now fixed? If so, please close the issue. Thanks all!

**Comment by bloatware** [comment]
It's 100% consistency vs 100% backwards compatibility now, I would close.

**Comment by petecooper** [comment]
I'd held back on closing because of @Bloke's request here: https://github.com/textpattern/textpattern/issues/1184#issuecomment-371102891

…but as far as I'm concerned, it's closable.

**Comment by bloatware** [comment]
I've done my best for all _article_ fields, so formally it's closed.
