### ISSUE TITLE
Textpack strings for multisite setup gone astray

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1186]
The couple of extra language strings on the first stage of a multisite setup no longer show:

```
multisite_config="Multi-site installation details"
please_enter_multisite_details="Please enter domain info for this site's admin area."
admin_domain_multisite="Admin subdomain"
cookie_domain_multisite="Cookie domain (usually main domain)"
```

They should be in the language files in [/textpattern/setup/lang](https://github.com/textpattern/textpattern/tree/dev/textpattern/setup/lang). We had them previously ([here](https://github.com/textpattern/textpattern/commit/7fe89540ba5396e90d6155952a1c9b7cdeb40872#diff-506bc512cd899837311aac2312206156) and [here](https://github.com/textpattern/textpattern/commit/f210166b19a95e1a5971c35d4d59cf8f4b9a9bb5#diff-506bc512cd899837311aac2312206156)) but they seem to have gone astray with more recent Crowdin syncs. 

Otherwise the multisite installation works fine in testing with the current state both in the regular location and when moved.

**Comment by Bloke** [comment]
Ack, could you raise on issue on the Textpacks repo please, with the missing ones and their translations listed. I found out the other day that changes made in the core get overwritten, but if they're lodged as issues in the Textpacks repo, Phil folds them into CrowdIn. Ta.

**Comment by philwareham** [comment]
If they were committed to core instead of to the correct destination (Textpacks repo) then they would have been overwrote by subsequent repo syncs.

**Comment by jools-r** [comment]
Ah, thanks for the info. I hadn't noticed they were missing before and wasn't aware of the proper issue-posting protocol. I've raised the issue over there. Sorry about that!
