### ISSUE TITLE
Protection against button spamming?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1187]
*Not a beta showstopper.*

Using current `dev` build. Possible edge case. I'm pushing at stuff that I perhaps shouldn't be pushing at.

As a result of the language packs now being stored in the filesystem, and database changes being made with the click or tap of a browser button, it's a lot easier to peg the CPU(s) on a server at 100%.

STR:

* open a server resources monitor of choice
* visit `/textpattern/index.php?event=lang` as a Managing Editor or Publisher
* find a language pack toward the bottom of the screen
* repeatedly click/tap Install as fast as you can

The language pack is installed, and the Install button moves to another language pack that's not installed, and that gets installed, and the process repeats. Clicking/tapping frequently and fast enough triggers a backlog and CPU use goes up until it's 100%.

This is normal CPU load on the demo server:

![screen shot 2018-03-07 at 12 45 12](https://user-images.githubusercontent.com/226578/37093287-c039369a-2206-11e8-9421-9d4ad7930006.png)

…and this is the output from mashing Install for a minute:

![screen shot 2018-03-07 at 12 46 45](https://user-images.githubusercontent.com/226578/37093336-e842eb4a-2206-11e8-97c0-7b592aac6f84.png)

It's not a beefy server, in fairness, but I was able to peg it pretty easily.

@philwareham - is there scope to perhaps disable the Install button after the first click/tap, like the article Save button? I know Install is gone after the Textpack is installed proper, but the second or so of activity (more on slower servers) is a window for tomfoolery.

The article Save button drops to grey as the work is happening, and holding Cmd+S on that panel doesn't create anywhere near as much load as installing a language pack, since the Textpack makes a bunch of database changes with a single click/tap.

**Comment by philwareham** [comment]
That would be something for @bloke or @bloatware - it's not my area of knowledge, sorry. Probably some AJAXy thing would prevent the above?

**Comment by petecooper** [comment]
Add another asshole condition to the list, perhaps less mitigate-able:

* visit `/textpattern/index.php?event=lang as a Managing Editor or Publisher`
* click Install on any language pack, wait for the install to complete
* refresh browser constantly (Cmd-R)

Similar result (redline), but much less clicking/tapping involved, and the drop-off back to normal load was a bit quicker.

**Comment by petecooper** [comment]
PS: please delete if this is not for public consumption.

**Comment by Bloke** [comment]
Actually, redirecting after install/update to clear the URL bar (or use `ps` instead of `gps`) was on my mental todo list one day.

**Comment by bloatware** [comment]
Both issues would be easier to fix if they were true submit buttons and not links, but I'm not sure how much work this change would take to restyle UX-wise. @philwareham?

**Comment by Bloke** [comment]
Yes. I think traditionally they were links simply because it uses GET. If we could use POST it would be better, but that would required a separate `<form>` for each language. I have no problem with doing that and converting things to being read via `ps()`.

Looking at the DOM  structure:
```html
<li class="txp-grid-cell warning">
   <p><span class="ui-icon ui-icon-alert"></span>
      <strong dir="auto">Español</strong><br><code dir="ltr">es</code>
      <span class="txp-lang-user-count"><a href="?event=admin&amp;step=author_list&amp;search_method=login&amp;crit=someone">(1)</a></span>
   </p>
   <p>
      <a class="txp-button" href="?event=lang&amp;step=get_language&amp;lang_code=es"><span class="ui-icon ui-icon-refresh"></span>&nbsp;Update</a>
      <a class="txp-button" href="?event=lang&amp;step=remove_language&amp;lang_code=es"><span class="ui-icon ui-icon-minus"></span>&nbsp;Remove</a>
   </p>
</li>
```

It should be reasonably simple to:

* Replace the surrounding `<ul>` with a div and retain the `txp-grid` class.
* Replace each `<li>` with a `<form>` (after all, `<li>` kinda acts like a block element in most respects).
* Swap out the buttons for submit buttons.
* Add `eInput()` and `tInput()` to each form where required.

The tricky thing is the fact that there are up to two submit buttons so we need to uses JavaScript to toggle some form field to know which `step` to pass. After that it's plain sailing: disable the button on click, wait for form submission, and the browser does the rest because you can't refresh the page without it whingeing about resubmitting the contents, which buys us time.

Whether it works depends on if the CSS is geared up to work via class name only.

**Comment by philwareham** [comment]
Can we get the beta out first please? I can certainly rework this UX for beta.2 - this is not a priority issue that should block a beta in my opinion.

**Comment by bloatware** [comment]
> The tricky thing is the fact that there are up to two submit buttons so we need to uses JavaScript to toggle some form field to know which step to pass.

Couldn't we name the buttons, say, `step` and use their value to detect the step?

> Can we get the beta out first please? I can certainly rework this UX for beta.2 - this is not a priority issue that should block a beta in my opinion.

Sure, this can wait imo.

**Comment by Bloke** [comment]
Sure, if we have separate forms, then using the names as steps makes sense. Hadn't thought of that.

And yes, this is a post-beta task. Early, post beta so Pete's server isn't at risk :-)

**Comment by philwareham** [comment]
Yep, I can definitely look at the HTML/CSS structure of this by end of Friday. Just think beta is a priority right now. Thanks all.

**Comment by phiw13** [comment]
@Bloke  [comment](https://github.com/textpattern/textpattern/issues/1187#issuecomment-371233332)

> Replace the surrounding `<ul>` with a `<div>` and retain the txp-grid class.

Using a `<ul>` has an advantage as that semantically what you present is a list of languages. Assistive technologies (screenreader) will then present the whole as such to the user.

--
On a side note, would it possible to ask to add a class to the `.txp-grid` element to specifically target this grid. Thinking ahead, if there are more uses of similar grid structures (an image grid?), it will be easier to adjust the styling depending on the internal requirements. The languages grid needs larger cells than a future images grid; each cell contains very different elements,…

`<ul class="txp-grid txp-lang-grid">` or `<ul class="txp-grid txp-img-grid">` etc.

**Comment by phiw13** [comment]
> Can we still retain the list structure and put the forms inside the <li> tags?

Sure can do, nothing prevents that. (the side bar on the pages panel uses that for the delete button)

**Comment by Bloke** [comment]
I'm down with that plan. Hadn't thought about plugins using the old step, good catch.

**Comment by philwareham** [comment]
So, do you want the `<form>` tags to just wrap the buttons `<p>` tag on each cell, or to be first child of the `<li>` on each cell? Doesn't really matter either way (they are both valid) but let me know your preference.

**Comment by Bloke** [comment]
I'm not fussed. Whatever makes most sense and is the leanest we can get away with. We need to post:

* language code
* event
* step (action)
* token

for each button of the 50-odd forms on that page... argh!

**Comment by bloatware** [comment]
Each form could contain just the language code, the rest can be sent via form URL (`event, token`) or appended with JS (`step`).

**Comment by Bloke** [comment]
Cool. As long as the result is POSTed so it can't be resubmitted/browser refreshed quickly, do whatever needs to be done in the smallest amount of markup!

**Comment by bloatware** [comment]
Oh, if a Publisher decides to redline his server, there is always a way. Are you already working on the markup or I try?

**Comment by Bloke** [comment]
:-) I won't have tome today, sorrry. Go for it.

**Comment by philwareham** [comment]
I made a start of the markup - but I can't duo any more Textpattern stuff today. It'll have to wait until Monday.

**Comment by bloatware** [comment]
I'm fine with waiting until Monday, no worries.

**Comment by philwareham** [comment]
OK, I've created a ew HTML structure where each language cell has it's own `<form>`. Please see http://design-patterns.textpattern.io/mockups/admin-languages.html

The cell is made up like so:

```
<li class="txp-grid-cell txp-grid-cell-lang success">
    <form>
        <p>
            <span class="ui-icon ui-icon-check"></span> <strong>English (British)</strong><br>
            <code>en-gb</code>
        </p>
        <p>
            BUTTONS HERE
        </p>
    </form>
</li>
```

And the buttons can be a mixture of:

```
<button type="submit" name="lang_update" disabled><span class="ui-icon ui-icon-refresh"></span> Update</button>
<button type="submit" name="lang_install"><span class="ui-icon ui-icon-plus"></span> Install</button>
<button type="submit" name="lang_remove" ><span class="ui-icon ui-icon-minus"></span> Remove</button>
```

**Comment by bloatware** [comment]
Nice! I won't have much time today, so any taker please don't hesitate.

**Comment by phiw13** [comment]
oh… so you’ve set an additional class on the cell. I was thinking setting an additional class at the container level ( `.txp-grid`). Useful if you use CSS grid layout to layout the thing (I do).

**Comment by bloatware** [comment]
@Bloke it would be great if you showed us how to use our new form widgets here :-)

**Comment by Bloke** [comment]
@bloatware It would be great if they were finished. A few more to add yet. Be my guest :-)

See the [widgets issue](https://github.com/textpattern/textpattern/issues/968) for some inline examples. A few of the early ones may need a tweak as things have evolved, but the later examples should give you an idea of where it's kinda going.

**Comment by philwareham** [comment]
@phiw13 just added `.txp-grid-lang` as requested. Out of curiosity, how are you polyfilling CSS Grid for our supported browsers (Safari 10 and IE11 to name two)? The reason I'm not using CSS Grid right now is because I don't really want to polyfill those browser with Flexbox just to use CSS Grid.

**Comment by philwareham** [comment]
Aside: we can probably drop IE 11 at Textpattern 4.8 and Safari 10 usage will have shrunk below my minimum usage level (0.5%) by then too.

**Comment by phiw13** [comment]
> added `.txp-grid-lang` as requested. 

TY.

> Out of curiosity, how are you polyfilling CSS Grid for our supported browsers (Safari 10 and IE 11 to name two)? 

Flexbox as fallback path - Mostly for IE 11. It is not much code.

I don’t think you need to worry much about Safari 10. Safari 10.1 supports CSS grid and has the same support matrix as S10 (macOS 10.10+); that leaves Safari 9, but there shouldn’t many of those left, me thinks.

**Comment by Bloke** [comment]
Should be sorted now, please test and reopen if I've missed something. I think the jQuery is as succinct and efficient as I can make it, but improvements welcome if there's a better way.

**Comment by phiw13** [comment]
I don’t want to disappoint you but it _only_ seems to work with Firefox (59). 

With Safari and Chromium (Opera beta): 
* Click on either “install” or “Remove” buttons
* Button appears greyed out
* Nothing happens: Language not installed / not removed.

(I don’t see anything in the error console)

**Comment by Bloke** [comment]
Must admit I only tested it in Firefox. More research required... thanks for the notification.

**Comment by phiw13** [comment]
Yes, now works fine (tested Safari only) and very fast!
