### ISSUE TITLE
Rendering of HTML entities without trailing semicolons

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1190]
(4.7.0-beta)

### Expected behaviour

Consistent handling of HTML entities across the admin-side.

### Actual behaviour

Inconsistent handling of HTML entities across the admin-side. Category titles appear to be more liberal in the way they handle entities without the trailing semicolon.

### Steps to reproduce

* visit `/textpattern/index.php?event=category`
* create or modify an article category title to include one or more HTML entities (decimal or hexadecimal format) but without the trailing semicolon, e.g.: `&#10004 Hope for the future &#x2714`:

![safariscreensnapz004](https://user-images.githubusercontent.com/226578/37153105-9691977e-22d3-11e8-9e26-2c418ce07d27.png)

* save changes, visit `/textpattern/index.php?event=category`, note the rendered entity

![safariscreensnapz005](https://user-images.githubusercontent.com/226578/37153115-9e55d0d8-22d3-11e8-8c76-2fc3ee9ba70d.png)

* next, create or update and article to include a text string with 1 or more semicolon-less entities, plus some tags to render with and without escaping:

```
<txp:title escape="" /> (title escape blank)
<txp:title escape="html" /> (title escape html)
```

![safariscreensnapz010](https://user-images.githubusercontent.com/226578/37153180-c523898a-22d3-11e8-807f-d4bf54f6013f.png)

* save changes, note rendering on public side:

![safariscreensnapz014](https://user-images.githubusercontent.com/226578/37153314-2af2b9f2-22d4-11e8-9586-c867339bf0b9.png)

(this screenshot is in French, another user changed the language while I was grabbing)

Potential solutions:

* be more strict on what constitutes an entity, so e.g. category titles don't rendered malformed HTML entities
* something else

**Comment by bloatware** [comment]
Title is not encoded in the same fashion that other fields, because it's historically used in XML (RSS and Atom) feeds. HTML is permissive and accepts unterminated entities, but XML does not. So, `&#10004` will be saved as is in Category fields, but transformed into `&amp;#10004` in Title. We can not change it for Title (would break RSS), and changing it for other fields is not bw compatible. So it goes.

**Comment by petecooper** [comment]
Thanks @bloatware – excellent explanation.

**Comment by bloatware** [comment]
Could someone explain me why the replacements in [textileEncode()](https://github.com/textpattern/textpattern/blob/16d7358d30cd587a0c73ab92d8ad7bfd2e55c242/textpattern/vendors/Netcarver/Textile/Parser.php#L1521) function are so complicated? As a side effect, you are out of luck if your Title contains `x%x%` - it is transformed into `&amp;`.

**Comment by Bloke** [comment]
Nope. Does a git blame/history give any insight in any commit messages that reference those lines?

**Comment by bloatware** [comment]
No idea, probably a commit by myself. Anyway, why not just
```
        $text = preg_replace("/&(?![#a-z0-9]+;)/i", "&amp;", $text);
```
The purpose is to encode XML-invalid `&` occurrences, but keep the valid entities like `&gt;` intact. We can not use `htmlspecialchars` here since it would also encode `<,>` etc.

**Comment by Bloke** [comment]
Seems reasonable to me. Do you have write access to [Textile](https://github.com/textile/php-textile)? If not, maybe a PR will do the job if Steve's still watching.
