### ISSUE TITLE
When using child categories articles in parent and child categories aren't displayed on a section

### ISSUE THREAD

**Issue by giopad** [textpattern/textpattern#1192]
### Expected behaviour

When I create a new child category in a section I would list articles in that category in that section or just that category.

### Actual behaviour

Articles in categories in sections are not listed with tag <txp:article> in a new installation (or demo) "default" page just echoes category name not the list of articles.

### Steps to reproduce

Create new category and new child category also new section. Write articles and put them in section, parent-category and chile-category. Put a <txp:category_list parent="parent-category" /> and click on a category. Results on clicked category obtains just category title.

**Comment by bloatware** [comment]
If I understand the problem right, you should check first

- whether `frontpage` option of the corresponding section is enabled,
- or call `<txp:article frontpage="" />` to disable filtering.

Hope that helps.

**Comment by giopad** [comment]
Many thanks. Solved. I did not understand that option.
