### ISSUE TITLE
Escape field in File tag builder incorrect

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1193]
### Expected behaviour

On the files panel, tags column of the files list - elect to build a tag using the tag builder. The escape field should be a drop-down list where you can select 'HTML' (as you can on the Image tag builder).

### Actual behaviour

The current escape field is a text field not a drop-down.

Also (maybe applies to a few tag builder items) - don't we allow more escape options now as well as 'HTML'?

**Comment by Bloke** [comment]
I'm sure it used to have this option, dunno why it changed.

> don't we allow more escape options now as well as 'HTML'?

Yes, hence the reason the 'global' escape values aren't dropdowns but freeform text fields. You can escape anything you like now - HTML tags included - so we can't possibly cover all the options in a dropdown. We could (should?) remove the dedicated dropdown selectors for `escape` in all tags, bar the ones accessed from the Images and Files panels. That would allow the global escape attribute to prevail.

**Comment by bloatware** [comment]
I guess the file download tag had no its own `escape` attribute in 4.6, unlike the images, so now it accepts the global one. But I don't see how to make local and global `escape` values uniform across all tags atm. In some tags, `escape` is used only to encode a HTML attribute (like `title`) value, so anything other than `html` is irrelevant.

We hardly could replace the text field by a dropdown for global `escape`, since its value can be e.g. any HTML tag, like `p` or `img`. But I'm ready to change it the way you like.

**Comment by Bloke** [comment]
Best bet is probably just to leave the global escape as a freeform field for most cases. Don't think we can cater to all use cases, nor should we limit people's options.

For any tags where the only realistic option is `html`, we can add a specific `escape` attribute to that tag and provide options. All the rest automatically get the global 'freeform' escape parameter.

**Comment by bloatware** [comment]
AFAIR all global attributes have already been added save for tags that had them before and won't process the globals anyway.

We can add `list` attribute filled with "standard" global values to the global `escape` text input.

**Comment by Bloke** [comment]
> We can add list attribute filled with "standard" global values to the global escape text input.

That'd be cool, thanks. No hurry, whenever you get a moment.

**Comment by bloatware** [comment]
Heck, `datalist` is not supported by Safari. Do it anyway?

**Comment by philwareham** [comment]
Can we not use a `<select>` here?

**Comment by bloatware** [comment]
No, also because global `escape` accepts comma-separated lists of transforms (e.g. `tidy, textile, html`), so we can not envisage to output all possible combinations (same for datalists). Moreover, their order matters, so neither multiselect nor checkboxes would help. There is nothing we can do here, I'm afraid.

**Comment by philwareham** [comment]
I guess `datalist` would be OK. Or... do we even need to give escape options on the tag builder? It's a fairly advanced feature anyway so one would assume people who know the tags and how to use escape would be able to manually enter that attribute and values. Dunno.

**Comment by Bloke** [comment]
`datalist` would be great, but it doesn't support multiple values (afaik) so you can only autocomplete the first item in a list. Still a handy feature to show people the sort of things available, though, even if it's not exhaustive.

**Comment by bloatware** [comment]
Finally, I have removed them all: even `wraptag` has nothing to do with, say, Textile/HTML file download links.

**Comment by philwareham** [comment]
Fine by me. How about the non-global escape attribute used on some tags (see https://github.com/textpattern/textpattern/blob/b09fc42ba42e5f5be9201794c79492eb0fcbadae/textpattern/include/txp_tag.php#L858) - do we leave that as-is, add to it or remove escape attributes entirely in the Tag builder?

**Comment by bloatware** [comment]
It looks like all tags save `<txp:text />` (which is not in the tagbuilder anyway) have adopted the global `escape` behaviour. So we can switch to `datalist`, but in Safari this would be just a text input, without hints. A placeholder with possible values, perhaps?

**Comment by philwareham** [comment]
Can;t we just remove escape entirely from the tag builder? Get rid of `tbEscapePop` wherever it's used? Datalist isn't going to suffice, I feel, neither is a placeholder.

**Comment by bloatware** [comment]
Well, I'd leave local `escape` there, to keep the track. There still is a difference between local and global attributes: one can permute the former without altering the output, but not the latter, executed from left to right. Should we fix an order? I feel that the natural one is `escape`, `wraptag`, `label`, but a free order is more flexible.

**Comment by philwareham** [comment]
Fix an order if we can - consistency is always good in m opinion. Cheers!

**Comment by bloatware** [comment]
Between consistency and flexibility *mon coeur balance*. I often need to output HTML code examples like "this is what `<txp:variable name="sample" wraptag="b" />` does":
```
<b>The sample content</b>
```
Currently we can do it with `<txp:variable name="sample" wraptag="p" escape="html" />`, but if we fix the order above (resulting in `<txp:variable name="sample" escape="html" wraptag="p" />`), this will output **The sample content**.

**Comment by philwareham** [comment]
OK, whatever you think is best. I'm no expert on escaping.

**Comment by bloatware** [comment]
No clever idea, sorry. I have just changed the text of the empty option to `gTxt('custom')`, as a hint.

**Comment by bloatware** [comment]
Argh, `gTxt('custom')` translates as "Custom field", and I don't find anything like `other` string. Do we add one?

**Comment by philwareham** [comment]
I'd prefer that gTxt was removed form the escape down drop list entirely and left as a blank. It shouldn't be a selectable value IMO.

**Comment by bloatware** [comment]
Some tags have `escape="html"` by default, so one might need to set `escape=""`. And gTxt string is only a visual hint, the value behind it is empty. I don't find any better, sorry, please do what you prefer.

**Comment by Bloke** [comment]
For dropdowns, let's just leave a blank entry at the top like we did. That'll insert `escape=""` as a convenience (right?) and if someone wants to customize it in the textarea, that's fine.

**Comment by bloatware** [comment]
That's how it still works, but the blank entry is (wrongly) labelled "Custom field" (i.e. `gTxt('custom')`), which I suggest to replace with "Custom value" or other appropriate text. Just to remind that other `escape` values are available now.

**Comment by Bloke** [comment]
Hmmm, I see what you mean. But we also, legitimately, offer `escape=""` as a way to remove the forced `html` in some cases. Could we use `escape="none"`? That doesn't conflict with anything in the global attribute code does it? If it doesn't understand a value it'll just fall back to 'raw'... right? `none` exists as a core string in '[common]' so that label could be used here.

In other words:
```html
<select>
<option value=""></option> <!-- for custom values -->
<option value="none">gTxt('none')</option>
<option value="html">HTML</option>
</select>
```
Yes it's not explicitly stated that you can use custom values here, but adding 'none' as a dedicated third option does leave this mysterious 'empty' entry which might cause people to wonder. Dunno.

**Comment by philwareham** [comment]
I'm OK with it saying 'None' (for `value=""`). I'm not keen on also have a blank as well. It's not like you can do anything custom with that as it's a select field.

**Comment by Bloke** [comment]
True. But if you build the tag with the 'empty' entry, you at least get `escape=""` rendered in the tag, which would allow you to enter your own values into it by hand.

If you chose "None" and it rendered `escape=""` in the tag, it has the desired effect, but would you think to look any further?

This is a tricky one. But the tag builder's only a minor part of the overall CMS so if we have to leave it alone for now as we figure out how to represent global attributes, so be it. Maybe there's a better way to represent the tag builder entirely in 4.8, which would allow us to indicate the 'custom' nature of attributes. Or even just a link to the docs from the attribute itself.

**Comment by bloatware** [comment]
> Could we use `escape="none"`?

We'd better not, who knows what `none` could mean in the future. Let's leave it as is, and revise it the day some `other` string is available.

**Comment by philwareham** [comment]
> Let's leave it as is, and revise it the day...

Agreed. Closing.
