### ISSUE TITLE
Incorrect HTML structure / markup on the Themes panel

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1194]
The multi-edit widget (`div.multi-edit`) is part of the `div.txp-navigation` (inside). It should precede it as on any other list panel, and inside the `.multi_edit_form` form. The `div.txp-navigation` should follow the `form`.

Themes panel:

```
form.multi_edit_form
  > div.txp-navigation
    > div.multi-edit
```

Sections panel:

```
form.multi_edit_form
  > div.multi-edit
/form
div.txp-navigation
```

2 screenshots:
https://dev.l-c-n.com/_junk/Sections.png
https://dev.l-c-n.com/_junk/Themes.png

**Comment by NicolasGraph** [comment]
Thanks for the report @phiw13.

**Comment by philwareham** [comment]
This should fee fixed now - let us know. Cheers all.

**Comment by phiw13** [comment]
Yup, looks much better. Thanks @NicolasGraph .
