### ISSUE TITLE
Theme enhancement (native oui_flat like support)

### ISSUE THREAD

**Issue by HashandSalt** [textpattern/textpattern#1196]
I am requesting and putting up for discussion the idea that the new theme support could be greatly enhanced if it was possible to edit the flat files on the file system and have them updated on a browser reload rather than having to manually force a them update or a use a webhook to update the theme code. This approach is much faster during development.

**Comment by NicolasGraph** [comment]
I feel like it is a plug-in area but I don't really know. Anyway I don't think would be able to do it for this release. 4.8?

**Comment by bloatware** [comment]
It shouldn't be too difficult to fetch themes directly from flat files, but it will have some time to test. Not in beta-2 anyway.

**Comment by bloatware** [comment]
Something to [test](https://forum.textpattern.io/viewtopic.php?id=48528).

**Comment by HashandSalt** [comment]
Ok, Some preliminary notes:

* Works great if you are logged in and viewing the local domain directly and you manually refresh the browser
* Does not work with Browserync via proxy, because it does not trigger a full page refresh when the theme files are changed. Reading the browsersync docs, it suggests it should do a full refresh if the file change is not a CSS or Javascript file.
* Reloading the the proxied browsersynced site only picks up content changed, NOT theme changes (which is bizarre).

I'll keep testing to see if i can get browsersync to do a full reload. I think some of these issues are down the way i usually use browsersync. Maybe TXP cant tell im logged in because viewing via browsersyncs built in proxy.

**Comment by philwareham** [comment]
Is this OK to close? Further enhancements can be made during the 4.8 dev cycle now I think (things such as URL hooks and/or working directly on flat files when in testing mode in core instead of as a plugin). Let me know. We can then look at releasing 4.7.2 in coming days and concentrate on all the 4.8 goodness we've planned.

**Comment by Bloke** [comment]
I'm happy to close this for now.

**Comment by HashandSalt** [comment]
@philwareham  Fine by me :)

**Comment by bloatware** [comment]
I'm still unsure for the workflow and wouldn't like to do it in a rush. Progressively amending the plugin looks more reasonable atm.

**Comment by philwareham** [comment]
Yep, agreed!

**Comment by philwareham** [comment]
The original scope of this issue has been addresses now. Theme handling from here on is iterative and doesn't need a specific issue open for it. Closing - cheers everyone!
