### ISSUE TITLE
Files and Images panel - need some space between category select and buttons

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1197]
In the upload widget, the `reset` button is flush against the category select widget (see screenshot below).

There used to be a white-space node separating the two in the source code. That has apparently disappeared with this [commit](https://github.com/textpattern/textpattern/commit/a611868901746b638be9d6e00487ad69761fc1b0) (in `txplib_html.php`).

Options:
* add some margin in the stylesheet
* add back a white-space node

For option two: please do **not** add a non-breaking space as this would mess with the layout on small screens. if the select widget contains long options (long category names), the `select` widget becomes as wide as the available space and the non-breaking space drops below the `select`, creating an extra “line” or an extra space before the buttons - depending on the styling for the `.inline-file-uploader-actions` span. (both on iOS and Android). (see [this simulation](https://dev.l-c-n.com/txp/txp-content-file(2).html), view with Safari responsive mode its enough to show the issue).

<img width="315" alt="upload-widget" src="https://user-images.githubusercontent.com/8944809/37550508-e6082f2a-29d1-11e8-82dd-3832f59a5534.png">

**Comment by petecooper** [comment]
Minor addition to this issue, I don't think it's worth opening a new one: the spacing around the `Replace file` components is a bit snug on desktop, but A-OK on mobile.

**Mobile**
![safariscreensnapz016](https://user-images.githubusercontent.com/226578/37604219-6393566a-2b88-11e8-81d9-f82d40f8301f.png)

**Desktop**
![safariscreensnapz017](https://user-images.githubusercontent.com/226578/37604228-673da572-2b88-11e8-991e-a05f46e93cd8.png)

**Comment by phiw13** [comment]
@philwareham - your commit fixes the issue perfectly (and TY for removing the non-breaking space after the `input type="file"` !!)

> I didn't even know there was a file category dropdown with that widget and I'm unsure how and when it appears

Create a Images category or a Files category.
You can then assign that the category during the upload process.

**Comment by phiw13** [comment]
The images panel suffers form the same issue, that is not yet done (?).

**Comment by philwareham** [comment]
OK, done for images panel too now.
