### ISSUE TITLE
Theme 'override' - rethink wordage

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1199]
The following option 'Override' in the new themes panel is too obtuse and confusing to end users (me included):

![grab1](https://user-images.githubusercontent.com/413665/37647592-8580e872-2c24-11e8-88aa-4498ed17cf3a.png)

It would be clearer if the wording was as follows I think:

![grab2](https://user-images.githubusercontent.com/413665/37647613-93f145a0-2c24-11e8-822e-831c3c32091f.png)

Any objections @bloke and @NicolasGraph ?

**Comment by Bloke** [comment]
Fine by me.

**Comment by ziselive** [comment]
Why doesn't my theme management page import theme options?

**Comment by NicolasGraph** [comment]
@ziselive, I guess you don't have any new uploaded theme in your themes directory.

**Comment by NicolasGraph** [comment]
It's ok for me too @philwareham.

**Comment by Bloke** [comment]
> Why doesn't my theme management page import theme options?

@ziselive What theme options are you referring to? Prefs? Information stored in the manifest? Themes don't natively import prefs right now.

@NicolasGraph We could leave the string key as `override` for now, coudn't we? And just change the string representations in languages (plus pophelps)?

**Comment by philwareham** [comment]
@Bloke it's same amount of upheaval even if we keep `override` string. Personally I'd say keep `override` and move it to the `common` group and also add `synchronize` in `common` too. They seem fairly generic and useful words to have available.

**Comment by bloatware** [comment]
Even in English `resynchronize` sounds weird for me (the spell checker confirms), and in Russian it would be abracadabresque. It is also bidirectional: synchronize in which sense? Couldn't we find something better to say "reload from disk"?

**Comment by philwareham** [comment]
@bloatware I believe the sync **is** bidirectional - if unused items are in database and not flat files, remove those / if unused items are in flat files and not database, remove those.

**Comment by ziselive** [comment]
@NicolasGraph you're right.  @Bloke ，I don't have any new uploaded theme in  themes directory. Put in a new theme and display it.

**Comment by Bloke** [comment]
If you choose this option (what essentially amounts to a "reimport" or "update" of what's in the DB) then the deletion is one way. In other words:

* If you're importing from disk and the checkbox is on, the _database_ templates are deleted and loaded from disk.
* If you're exporting from the DB and the checkbox is on, the _disk_ templates are deleted and recreated from the database contents.

**Comment by NicolasGraph** [comment]
In fact, deletion is the last thing that is processed. On import for example, it inserts/updates valid template files and then delete templates in the DB that do not have a related valid files.

**Comment by Bloke** [comment]
@NicolasGraph Thanks for the clarification. That's actually a more efficient process (yay). The outcome is the same.

Partly, this issue stems from a desire to try to reuse a single checkbox for all eventualities: import, export and delete. Maybe the fact we're going round in circles is because there is no simple way to cover all bases and we need to consider a separate string for at least one of the options. A bind on translators, so if we can somehow find something less abracadbra-ish, that'd still be my preferred option.

Or do the best we can with the single checkbox string and multi-edit labels, then worry about it in next release. Chances are we'll need more options in future anyway, or some import/export wizard so this might just be a temporary thing specific to this release.

**Comment by NicolasGraph** [comment]
Sorry but… Are we talking about changing the 'override' option to something else (like 'Resynchronize' as proposed by @philwareham), or about changing the checkbox label? Both?

**Comment by Bloke** [comment]
One or both. There's probably a combination of words out there that succinctly describes what the multi-edit option + checkbox does.

But if there isn't, we may have to consider different strings.

**Comment by philwareham** [comment]
Both I think.

Well this discussion proves that 'Override' isn't the correct term. If this is effectively just an 'Import to database' function then why not have these two specific wordings?...

- Import to database
- Export to files

And then two different secondary actions maybe:

- Delete unused database templates on import
- Delete unused file templates on export

If the 'Delete' option shares the above messages, then also an additional secondary action for that:

- Delete theme from disk too

Dunno. I feel it all needs to be obvious, since this can be a destructive feature.

**Comment by Bloke** [comment]
Taking a step back, are we happy with the notion of import / export? Or can we sidestep the issue by being more verbose in the multi edit option? e.g.

* Load from disk
* Duplicate
* Store on disk
* Delete

Something like that? If so, it'd be nice to _not_ use the term 'disk' twice so the list is more quickly scannable and you know you're picking the right option without reading the verb. But I can't think of a way to use the word 'database' in there right now.

**Comment by Bloke** [comment]
Iterating on what Phil said, can we just get away with:

* Import to database: 'Delete unused templates?' option.
* Duplicate
* Export to files: 'Delete unused templates?' option.
* Delete: can we use 'Delete unused templates?' option here? Or does this need a dedicated string as Phil suggests?

Save a string, save the world.

**Comment by philwareham** [comment]
Another option:

- Import from disk
- Export to disk

And keep the suggested secondary wordings I gave. I think they need to be absolutely 100% clear as to what they are going to do if you check them. Same for 'Delete' bit maybe 'Delete theme templates from disk too' (since it won't actually delete the theme if other files are in it other than template files).

**Comment by NicolasGraph** [comment]
If we go with your strings @Phil, we could even restore the 'update' word @Bloke introduced previously. 'Update from disk' seems quite obvious isn't it?

**Comment by phiw13** [comment]
> Import

The action is not really “Import” - the theme already exists in the DB. “Update” sounds more appropriate.

**Comment by philwareham** [comment]
OK, we are getting close to agreement!...

- Update from disk
- Export to disk
- Delete

Secondary actions for each of the above...

- Delete unused database templates on import
- Delete unused disk templates on export
- Delete theme templates from disk too

How's that?

**Comment by Bloke** [comment]
That's all good too. My only (very very minor) beef with using the word 'disk' twice is that you have to read everything to find the option you want. The words 'import' and 'export' have an implied notion - almost geekiness - that people already understand what the hell themes are all about.

Sure, _we_ know that the database is the centre of the universe when it comes to delivering themes to the public site, and therefore importing means pulling content into the database, but without reading up, is that obvious to others?

It's like using arrows to indicate import/export in other UIs I've seen. Some use an "up" arrow to import (because disk is "lower" than database?) and a down arrow to export (download?). Others use it the other way round, becasue the down-arrow is pulling content down into the DB and the up-arrow is shooting stuff out into the sky away from the app. Both are open to interpretation and imply foreknowledge of which way is which.

Having two differerent nouns makes things more scannable. The word 'database' is sufficiently different from 'disk' (I'd hope in most languages) so seeing 'to database' and disregarding the verb is clear that whatever this action means, stuff's going to appear in the database. And 'to disk' is going to put something on disk.

That said, 'From disk' is fine, and probably the best we'll get, so I'm perfectly happy with that nomenclature if everyone else is. Using multiple secondary action strings does seem to dismabiguate things and will make for a cleaner interface experience, even if it does result in some disgruntled translators in the short term.

**Comment by philwareham** [comment]
OK, let's go with that. Can someone please code the following strings into the skins panel and I'll then reconfigure Crowdin for that same:

```
update_from_disk
export_to_disk

skin_delete_from_database
skin_delete_from_disk
skin_delete_entirely
```

I'll probably make `update_from_disk` and `export_to_disk` common strings, as they may be useful in future for other things. And I'll rename `import_skin` to `import_from_disk` and make that a common string too. That covers all bases.

**Comment by NicolasGraph** [comment]
@Phil, I'm going to do it.

**Comment by philwareham** [comment]
😀

**Comment by Bloke** [comment]
I'll add the pophelp topics for the three actions.

**Comment by NicolasGraph** [comment]
Do we keep `skin_synchronize` as pref. name?

**Comment by Bloke** [comment]
> Do we keep skin_synchronize as pref. name?

No harm in that. Depends if we're going to be remembering the settings independently or not, or treating them as three dedicated checkboxes now.

**Comment by NicolasGraph** [comment]
Yes, that what I was thinking. As there are three different labels now, users could be confused if it is stored in the same place.

**Comment by Bloke** [comment]
So we're going for three independent prefs? If you check the `export_to_disk` option and commit the action, it will have no effect on the `import_from_disk` checkbox?

Or do we assume that if you've indicated you're doing some disk action that you want to always perform disk actions regardless of the multi-edit option selected?

**Comment by NicolasGraph** [comment]
I would expected each option to store my last action (check/uncheck) separately.

**Comment by Bloke** [comment]
I think I would too. If you are changing `getMultiEditOption()` accordingly, I'll make a note in the pophelp that the checkbox states are independent.

**Comment by NicolasGraph** [comment]
Ok, I need to go now but I'll do that asap, this evening or tomorrow morning.

**Comment by bloatware** [comment]
I wouldn't separate them. Moreover, one string like "Synchronize database/disk copies" could cover three cases. Our `txp_lang` table will thank us!

**Comment by NicolasGraph** [comment]
Ok @bloatware,  I can't code for now but I'll take a look here before to do anything. See you.

**Comment by Bloke** [comment]
> Synchronize database/disk copies

Argh! I like this too. Now you got me wondering again... and just when it was getting easy.

I'm all for fewer strings. In fact, I'd love to prune people's lang tables down on upgrade to 4.7.0 but daren't do it for fear of trampling anyone who hasn't used an `owner` for a custom string. As we move towards full multi-lingualism throughout, I'm conscious that we're going to need to find a better way to store, extract and index language info.

Anyway, I'll hang fire on committing the pophelp changes then until the dust settles later. If we can do it as one string, that's by far the best option.

**Comment by philwareham** [comment]
To clarify, these checkboxes need to be absolutely 100% clear on what they do - as they delete things from people's themes with no chance of undo (well, apart from if you version control of course). So 'Synchronize database/disk copies' isn't clear enough in my opinion.

Plus, I've already reconfigured Crowdin for the 3 extra strings and I have no intention of changing it again, so please proceed with the 3 pophelps. 🙃

**Comment by ziselive** [comment]
In fact, what I want to ask is: What are the advantages and disadvantages of the theme template stored in the database?
Or, why save the theme template to the database?

**Comment by NicolasGraph** [comment]
@Bloke and @philwareham, the [PR](https://github.com/textpattern/textpattern/pull/1201/commits/7a9c19e64879107e2b81bf47eeec7b0c6f27a217) seems ok to me. I separated the three multi-edit related prefs for now.

@ziselive, I think a core team member will explain that better than me. I think one reason why themes are stored in the DB is that it is easier and faster to edit them from the admin interface. It is also faster to parse I guess…

**Comment by Bloke** [comment]
Thank, Nicolas. Pophelp done in 5cd73558.

Let's live with the extra strings and prefs for now. Next release, as I mentioned, may bring update/export wizards so this may only be a temporary situation and we can deflate the lang table/prefs in due course.

**Comment by bloatware** [comment]
@ziselive We not only *save* themes in db, we *serve* them from db. Stef has explained it [here](https://forum.textpattern.io/viewtopic.php?pid=310082#p310082), please read.

**Comment by Bloke** [comment]
@ziselive And I answered your [forum question directly here](https://forum.textpattern.io/viewtopic.php?pid=310176#p310176).

**Comment by philwareham** [comment]
I'm happy with this now. Closing issue. Thanks all!
