### ISSUE TITLE
Squiffy Admin->Account panel for low-priv users

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1202]
### Expected behaviour

_Change your password_ button is rendered correctly and not cut off.

### Actual behaviour

See screenshot for a user with Designer privs.

![lowprivuseredit](https://user-images.githubusercontent.com/21252/37689492-29eac45a-2c9d-11e8-9c9f-841174e5a846.png)

### Steps to reproduce

1. Create low-priv user (4, 5 or 6 will do).
2. Log in as that user.
3. Visit Admin->Account on small desktop, tablet, phone.

**Comment by petecooper** [comment]
Appears that the button does render correctly, but gets overlaid – see attached SFW video.

[1202 viewport.mp4.zip](https://github.com/textpattern/textpattern/files/1832961/1202.viewport.mp4.zip)

For info: https://dev-demo.textpattern.co and https://beta-demo.textpattern.co have non-Managing Editor accounts baked-in, too. Choose one of `copy-editor`, `designer`, `freelancer`, `no-access` or `staff-writer` followed by a 3-digit number (e.g. `copy-editor437`) as your login and password.

**Comment by philwareham** [comment]
This should be fixed now - let me know if problems persist. Ta!

**Comment by Bloke** [comment]
Sorted, thank you!
