### ISSUE TITLE
4.7 beta 2 release

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1204]
Please list below any blockers to release of beta 2 (note that it's not essential to fix *everything* in the issues list pertaining to 4.7 final release for this beta - so only crucial items need to be listed). We should release this beta soon as possible.

**Comment by bloatware** [comment]
What do we decide with [this](https://github.com/textpattern/textpattern/issues/1196)? If we plan it for 4.7 then beta 3 would be necessary, unless we take few days more before beta 2. Or delegate it to plugins atm?

**Comment by philwareham** [comment]
I'm happy to leave that to a beta 3. I'd like it to be in core if possible.

I'm conscious that the button spamming fix needs to be available - hence beta 2 now. If beta 3 is needed (fairly sure it will be needed) we can release that in due course.

**Comment by Bloke** [comment]
Themes file support can be delegated to beta.3 imo.

Would be nice (not essential) to fix the [Admin->Users thing](https://github.com/textpattern/textpattern/issues/1202) but otherwise, no blockers from me. If someone could update HISTORY with any changes (e.g. article copy) I could bundle a release today.

**Comment by philwareham** [comment]
> Would be nice (not essential) to fix the Admin->Users thing

It's on my list along with the plugin preview text pack thing you want me to look at. hey can both be beta 3 IMO.

**Comment by philwareham** [comment]
I've updated history apart from article copy - not sure what the changes are for that one. If someone wants to write that history entry I'm happy for us release beta 2 today.

**Comment by petecooper** [comment]
I'm sifting through commits for other HISTORY tidbits, I'll drop PRs in piecemeal so as not to delay anything.

Standing by to configure beta demo to use beta 2 when it drops.

**Comment by Bloke** [comment]
Regarding copy: look at the Article List panel in the ID column.

**Comment by Bloke** [comment]
@philwareham When you get a chance, please update the various theme manifest version numbers and push them to the -dev repo. I'll then prep a beta 2 release branch this afternoon/evening depending on day job workload.

**Comment by philwareham** [comment]
Sure, will do.

**Comment by philwareham** [comment]
Theme manifests updated

**Comment by Bloke** [comment]
Done, go go go everyone, and thanks in advance.

**Comment by philwareham** [comment]
@petecooper is you'd like to post something to Hacker News, that always gets a good uptick.

**Comment by petecooper** [comment]
https://beta-demo.textpattern.co/ updated to beta 2, will rebuild to existing schedule

**Comment by petecooper** [comment]
…and Hacker News is now aware: https://news.ycombinator.com/item?id=16647432
