### ISSUE TITLE
Staff Writer/Freelancer/Designer saving as Live/Sticky gives misleading feedback in notification

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1209]
### Expected behaviour

Staff Writer/Freelancer/Designer cannot make articles live. If a Staff Writer/Freelancer/Designer attempts this, a warning should be shown indicating the action was not completed.

### Actual behaviour

If a Staff Writer/Freelancer/Designer attempts to make an article live, a green (positive) confirmation notification is shown indicating the article has been set to Pending

### Steps to reproduce

* log in as Staff Writer/Freelancer/Designer
* write an article, save as Live/Sticky
* note green (positive) confirmation and status saved as Pending

SFW screencast (no audio) attached.

[SafariScreenSnapz003.mp4.zip](https://github.com/textpattern/textpattern/files/1838055/SafariScreenSnapz003.mp4.zip)

**Comment by bloatware** [comment]
Thanks @petecooper, will fix.

**Comment by bloatware** [comment]
I have accidentally closed it (should be #1208), but now Staff Writer/Freelancer/Designer has no live/sticky option available, does it fixes the issue?

**Comment by petecooper** [comment]
Live and Sticky are listed but not selectable - OP resolved. Thank you @bloatware!

**Comment by Bloke** [comment]
Not quite. A freelancer can still change status from the multi-edit tool. Live and Sticky are available but if they choose it, they get the same green success message, yet the status is only set to Pending.

**Comment by Bloke** [comment]
Incidentally, if we open up Files access as outlined in #1212 then editing a file results in the same experience: a Freelancer can select Live from the dropdown when they edit their own file, get a Green confirmation message on save but actually only set the status to Pending.

**Comment by Bloke** [comment]
More findings:

1. Create article as Freelancer.
2. Visit Articles panel.
3. Click Copy alongside article just created.
4. Edit title of copy.
5. Click Save.

Expected result: article saved.
Actual result: 'Internal error' thrown. 'Invalid status' returned in flash message area.

Looks like status=Live is selected in the dropdown during the Copy operation, even though it's disabled and not selectable by hand.

**Comment by petecooper** [comment]
@Bloke 
>Incidentally, if we open up Files access as outlined in #1212 then editing a file results in the same experience: a Freelancer can select Live from the dropdown when they edit their own file, get a Green confirmation message on save but actually only set the status to Pending.

I'm less inclined to open up write access to Files and Images for Freelancers, given that they can't write articles and make them Live without approval but _can_ make Files and Images Lives without approval.

Is a roles reexamination or overhaul in order, after all?

**Comment by bloatware** [comment]
I have re-adjusted Status selectors for articles. Not sure about opening Files access to freelancers atm.

**Comment by Bloke** [comment]
Reverted File access in 7989606c.

**Comment by Bloke** [comment]
This getting closer. Thanks for fixing the multi-edit status assignment, Oleg.

Couple more observations:

1. With a publisher account, set the default publish status to Pending.
2. Log in as Freelancer.
3. Visit Article list panel.
4. Note no 'Create Article' button in control panel. Should there be one? They can create articles by clicking the Write panel. Probably faulty priv checking in the control panel rendering block.
5. Edit any article. Note status is fine.
6. Click 'Create article' on Write panel.
7. Note status is Draft, not default publishing status. Performing the Create article action with privs 1-4 results in it using the pref value as default status. But 5 and 6 always get draft for new articles.

**Comment by bloatware** [comment]
In my `txp_prefs` table I see one `default_publish_status` **per user**, is it normal? If yes, what is your freelancers publish status, could it still stay Live?

**Comment by bloatware** [comment]
Done for Create article button.

**Comment by Bloke** [comment]
> Edit: actually, how a freelancer can change his publish status?

That's the million dollar question. Yes, I forgot that the pref was per user.

Now that the prefs panel is open to all, it should be easier to offer only per-user prefs to lower priv level users. That would also counteract one of Pete's other issues he raised about the prefs panel always being empty on vanilla installs. We'll have at least one pref in the Publish group for all users!

Is it possible to make the prefs panel's priv checking more granular than just taking the "prefs.<sub-group>" priv at face value? Maybe make the implication that if any of those groups contain per-user prefs, they are exposed regardless of the priv setting?

**Comment by bloatware** [comment]
I'm not yet at ease with the privs system, dunno if we can expose them individually.

**Comment by Bloke** [comment]
I'll look at it and see what can be done there.

Addendum: this would make it tricky to enforce when saving. Will have to think about it.

**Comment by bloatware** [comment]
Meanwhile, Draft for freelancers is consistent with what we have on duplicate. And they can not see their publish status anyway, so...

**Comment by Bloke** [comment]
Okay, now they can edit their own pref (see 1c284160). So all we need to do now is make sure it's taken into account when they create a new article. It's fine if they Copy to always set draft, but if they create new it should default to the value in their per-user pref.

Can you tweak that please?

**Comment by bloatware** [comment]
Oh, nice! Would `min(pref, pending)` do (i.e. article statuses are linear)?

Probably we also need to check what happens on author creation/modification. Should the publishing status be adapted to the role?

**Comment by Bloke** [comment]
Using `min()` would work but I'd like to (eventually) get away from the assumed hierarchical nature of roles. That's what the status-mods branch is all about, which is 90% complete but I hit a roadblock. Can't remember exactly what it was and [my post on the subject](https://forum.textpattern.io/viewtopic.php?pid=302952#p302952) stupidly didn't go into details, bah!

Regarding new authors, yes, that's going to be problematic unless we cheat and set the status to Draft by default :-)

You'll notice I copied your exact code in the prefs status callback. Is there mileage in altering the `status_list()` function directly to take privs into account just before processing the `$exclude` portion? Then we get it for free everywhere that function is used. But (crucially) plugins can override that with the callback if they want to enforce a different workflow.

I can't think of a situation where we'd want the list of statuses to _not_ be cognisant of the maximum permitted statuses based on privileges, but maybe I'm not thinking hard enough?

**Comment by bloatware** [comment]
> Is there mileage in altering the status_list() function directly to take privs into account just before processing the $exclude portion?

You mean unset unavailable statuses? Then a published article viewed by a freelancer will have a wrong status on the Write tab.

**Comment by Bloke** [comment]
Yah, nuts you're right. Maybe an option then to exclude unavailable statuses for those times we need to do it? Or a wrapper function that strips them off?

Just conscious of using the same 'hack' in two places to limit the dropdowns. Centralising it is my preferred option to help minimise bugs later when only one version might be altered by mistake. But if we're going to rethink or at least revisit privs in 4.8 then maybe this can wait and we'll do it in a more OO manner then.

**Comment by petecooper** [comment]
@Bloke 
>But if we're going to rethink or at least revisit privs in 4.8 then maybe this can wait and we'll do it in a more OO manner then.

A heavy +1 to this.

**Comment by bloatware** [comment]
Revisiting this, it look like the OP problem is fixed? Though Staff Writers can publish their articles, is this intended?

And what's the matter of disabling textfilters (textile/linebreak/as is) for staff writers/freelancers, since they can circumvent it via `notextile..` anyway?

Another quirk: since low level users can not modify others articles, why not to disable all fields to make it clearer?

**Comment by petecooper** [comment]
Thank you @bloatware 👌🏻

**Comment by phiw13** [comment]
>  Another quirk: since low level users can not modify others articles, why not to disable all fields to make it clearer?

The body field (and excerpt, but  that is not important in my use case) is  now marked as `disabled`. That is a little problematic in some case. Would it be difficult to mark it `readonly` instead?

### Use case:

A site has multiple authors; one author writes a (complex) article, complete with state-of-the-art Textile. Another author  in the group, freelance privs, sees article and disagrees with content or reasoning. Author 2 start writing a rebuttal, and want to quote something from the original article _complete with all (Textile) formatting._ Author 2 goes to Write edit panel for said article, but now, the field is `disabled` cannot copy anything out of the textarea. With `readonly` it would still be possible to copy the part(s) Author 2 wants to quote.

`readonly` is already used for similar purpose on the Images edit panel.

**Comment by bloatware** [comment]
Valid point, though `readonly` still allows for checkbox/select/etc modifications, but it's not an issue. Will do, thanks.

**Comment by phiw13** [comment]
I mean, `readonly` on the main textarea _only_ (body or article).

**Comment by bloatware** [comment]
That's possible too, but then they need some styling to look alike.

**Comment by phiw13** [comment]
The `readonly` works perfectly,  thank you.
