### ISSUE TITLE
Fatal error: Maximum function nesting level of '256' reached, aborting! 

### ISSUE THREAD

**Issue by ziselive** [textpattern/textpattern#1210]
### Expected behaviour

Open the article page

### Actual behaviour
Fatal error: Maximum function nesting level of '256' reached, aborting! in E:\www\text\textpattern\publish\taghandlers.php on line 2845

# | Time | Memory | Function | Location
-- | -- | -- | -- | --
1 | 0.0000 | 374712 | {main}(  ) | ...\index.php:0
2 | 0.0640 | 3167424 | textpattern(  ) | ...\index.php:116
3 | 0.0640 | 3167784 | parse_page(  ) | ...\publish.php:581
4 | 0.0640 | 3172904 | parse(  ) | ...\txplib_misc.php:4418
5 | 0.0730 | 3273032 | processTags(  ) | ...\txplib_publish.php:520
6 | 0.0730 | 3274864 | Textpattern\Tag\Registry->process(  ) | ...\txplib_publish.php:596
7 | 0.0730 | 3274864 | call_user_func:{E:\1-neard\neard\www\text\textpattern\vendors\Textpattern\Tag\Registry.php:116} (  ) | ...\Registry.php:116
8 | 0.0730 | 3274864 | if_article_list(  ) | ...\Registry.php:116
...

### Steps to reproduce
1.Upload a custom theme.
2.Switch the custom theme, open the article page, there was an error.

The custom theme code is copied from the default installation theme. This problem did not appear before Beta2.

**Comment by bloatware** [comment]
Putting something like
```
<txp:article_custom id="13"><txp:body /></txp:article_custom>
```
inside the article N° 13 would surely produce a loop. We could probably do something, like we did for recursive forms, but all lists (categories, sections) are affected.

**Comment by ziselive** [comment]
@Bloke  Maybe I accidentally modified the file.

**Comment by ziselive** [comment]
I compared a few files and it was indeed my mistake.

**Comment by Bloke** [comment]
No worries, just wanted to make sure we hadn't broken anything in the core theme! Thanks for the confirmation.
