### ISSUE TITLE
Inconsistencies in menu items for lower-ability users

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1213]
(Something for 4.8 or a 4.7 point release - maybe a candidate for https://github.com/textpattern/textpattern/projects)

**Background**
Most of my own Textpattern sites are single-user and I access things as a Publisher. Some of my clients do the same, eschewing the roles stuff and giving trusted people the same roles for an easy life.

A recent addition to my client roster is very keen to have a) a lot of authors involved and b) each of them in a their best-fit tier. There's a support load/burden with some authors asking why, when they access feature X, they get a restricted warning, or no access.

**Examples** (not exhaustive)
* a Freelancer has an Admin -> Preferences option, but no preferences are available (vanilla install, no plugins)
* a Freelancer has access to Admin -> Languages, and a lovely table of languages, but can't do anything beyond selecting their site language from a dropdown
* a Freelancer can write an article, save it, but using the View option throws a 401 error

**Solution**
Decide on UI/UX style rules for user tiers, and enhance the UI to provide *only* the accessible functions to each tier. Essentially, where the options aren't available to them, they can't try them, and therefore can't fail. Fewer UI options will keep things clean and tidy, and make for a neater workflow.

A reexamination of the roles/tiers and their respective rights would, I think, be beneficial. Perhaps creating some fictitious personas for people in an organisation might help, and then figure out what stuff they need to achieve a smooth CMS experience.

I'd really like to hear any feedback and advice on this, even if (*especially* if) it's contradictory to the above.

Thanks very much for reading.

**Comment by bloatware** [comment]
Hard to disagree :-) I have fixed the third point, and the second one should be easy to fix. But the first point is tough atm, because a plugin could add some preferences for freelancers etc. But currently we have no way to know whether such preferences exist until we are on the tab. So we can not remove Preferences tab if some admin plugins are registered.

Hope in 4.8 we'll find a more flexible way to manage user rights, all ideas are welcome.

**Comment by Bloke** [comment]
> Freelancer has an Admin -> Preferences option, but no preferences are available (vanilla install, no plugins)

As @bloatware says, difficult to defend against. We don't necessarily know when the menu is built whether there are any prefs that a plugin might have installed on the panel. But we do some jiggery pokery in `txplib_head.php` with the Admin->Users panel for low priv users so we might be able to use similar logic on prefs too.

In versions gone by, prefs were restricted to only user groups 1 and 2. It's only in 4.6 that we permitted anyone to see the core prefs panel, because we made the act of managing prefs much easier. If we clamped it back down, then we may force plugin authors to write their own prefs panels, which is a lot of extra code.

> a Freelancer has access to Admin -> Languages, and a lovely table of languages, but can't do anything beyond selecting their site language from a dropdown

This is by design. I remember having a conversation with phiw13 about it a while ago. The consensus was that an entire page with a single dropdown on it looked a bit crap. Plus, a person using the admin side as a Freelancer might well not use English as their native tongue, see that we support their language and can petition the site admin to install it for them. So it's more of an advert of what languages are available.

> a Freelancer can write an article, save it, but using the View option throws a 401 error

Bug. Fixed. Yay.

**Comment by Bloke** [comment]
Regarding previewing own content... I agree with [this change](https://github.com/textpattern/textpattern/commit/ff51aef34eda54f3c047b8677e47759c003284fd), but shouldn't we permit anyone who can write an article - even in Draft - to be able to preview it? How will a Freelancer know they're Textile copy renders okay if they can't see it in-situ with the stylesheet? The on-Write-page Preview is only half the story, sometimes less depending on the content.

Is there a legacy reason anyone knows for preventing some user levels from previewing their own work on the site? Is it a security concern? We could just extend `article.preview` to all levels in `admin_config.php`.

**Comment by phiw13** [comment]
ref Admin > languages

> This is by design. I remember having a conversation with phiw13 about it a while ago. 

Correct. And I think it should stay like it is.

--

Am I the only to be little uncomfortable with giving Freelancer write access to the File panel. Read access seems OK, though

**Comment by petecooper** [comment]
@phiw13 
>Am I the only to be little uncomfortable with giving Freelancer write access to the File panel. Read access seems OK, though

No, not just you. I was a little surprised a Freelancer had to go through hoops to publish to Live, but could upload a File without anyone checking it. And I absolutely understand the logic behind the languages panel, I wasn't aware of that before now.

…but then again, the persona of a typical Freelancer, are they trusted? This is where I struggle a bit, as Textpattern has these roles that aren't necessarily very clear cut in the _person_ they're attached to.

Read access to Images and Files fits with the persona I have in my mind, but it's a bit hazy.

**Comment by petecooper** [comment]
@Bloke 
>Note to self: run more tests on non-Publisher accounts.

I've got this as a todo for me, also. The temptation to run things as Publisher and forget about the org/collab aspect is too high and I would love to have some extra eyeballs & feedback from people who actually do this in real life…they tend to be a bit quiet, however.

**Comment by bloatware** [comment]
> Is there a legacy reason anyone knows for preventing some user levels from previewing their own work on the site? Is it a security concern?

Possibly tags. Core should be safe, but if some public powaplugin is installed, a freelancer could abuse it.

**Comment by Bloke** [comment]
Right, so as I mentioned in the other thread, let's review the roles and figure out who should do what. Maybe freelancers shouldn't be able to upload files/images at all, not sure. But then if theyr'e freelancing and writing articles that require images and attachments, we're then confining them to only being able to use ones that have already been uploaded.

Designers have write access to images, but I think we all agree that design images (as in, structural stuff for site operation) should _not_ go in the database - they're for content images only. But if we revoke that access, it means giving them SFTP access or something.

Is there an argument for a hidden classification of images? User vs design? We can then allow designers to upload images as usual - same mechanism, everything, but they can only see imaghes tagged with the "Design" moniker - everything else is hidden. And likewise, regular users can's see such 'design' pics in the Images panel. Only content images.

**Comment by bloatware** [comment]
Let's open Pandora boxes after 4.7, betas are betas.

**Comment by Bloke** [comment]
I concur. Nothing to stop someone making a feature branch at any time though :-)

**Comment by petecooper** [comment]
I'd be grateful if someone could tag this with 4.8 milestone, please and thank you

**Comment by petecooper** [comment]
OK, I've opened the worm can [here](https://forum.textpattern.io/viewtopic.php?id=48939).

**Comment by petecooper** [comment]
OP is mostly taken care of, aside from the ongoing discussion about user privs which will naturally happen as 4.8 and 4.9 come around, so closing this.
