### ISSUE TITLE
Syntax error if PHP version is less than 5.6

### ISSUE THREAD

**Issue by makss** [textpattern/textpattern#1216]
`Dev` branch, `Skin` Tab.

> Parse error: syntax error, unexpected '.', expecting ')' in /home/mhosts/repo_txp/txp47/textpattern/textpattern/vendors/Textpattern/Skin/Form.php on line 81

> Parse error: syntax error, unexpected '.', expecting ')' in /home/mhosts/repo_txp/txp47/textpattern/textpattern/vendors/Textpattern/Skin/Form.php on line 87

> Parse error: syntax error, unexpected '.', expecting ')' in /home/mhosts/repo_txp/txp47/textpattern/textpattern/vendors/Textpattern/Skin/Form.php on line 93

> Parse error: syntax error, unexpected '.', expecting ')' in /home/mhosts/repo_txp/txp47/textpattern/textpattern/vendors/Textpattern/Skin/Form.php on line 99

> Parse error: syntax error, unexpected '.', expecting ')' in /home/mhosts/repo_txp/txp47/textpattern/textpattern/vendors/Textpattern/Skin/Form.php on line 105

> Parse error: syntax error, unexpected '.', expecting ')' in /home/mhosts/repo_txp/txp47/textpattern/textpattern/vendors/Textpattern/Skin/Form.php on line 111

> Parse error: syntax error, unexpected '.', expecting ')' in /home/mhosts/repo_txp/txp47/textpattern/textpattern/vendors/Textpattern/Skin/Css.php on line 44

Surprisingly, PHP less than 5.6 does not understand [this code](http://sandbox.onlinephpfunctions.com/code/9e2cd1ca1f28da3428054c9b04e96f9e58cc6c91)
1. Change PHP version
2. Press "Execute code"

---
If write code in one line, then everything works fine in all versions of PHP.
```
'css' => '/* Contents of the css tag goes here. See https://docs.textpattern.io/tags/css */'
```

**Comment by Bloke** [comment]
Holy moly. Well spotted. We should make a note in the code when it's patched so nobody tries to split the line in future.
