### ISSUE TITLE
Cleanup of list head area

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1218]
I've rewritten some HTML structure that I'd like to use for the area above list tables on admin panels.

Basically, it's to fix the 'list options' floating away above the top of the tables if there's a few UI widgets on the left-hand side of the area (although it has other benefits too for smaller screen widths). To fix this I've used Flexbox - see the example here: http://design-patterns.textpattern.io/mockups/content-list.html - so I need the HTML of that area changes slightly.

I need the components `txp-control-panel` and `txp-list-options` to be in a div `txp-layout-cell-row txp-list-head`, HTML like so:

```
<div class="txp-layout-cell-row txp-list-head">
    <div class="txp-control-panel">
        ...content...
    </div>
    <div class="txp-list-options">
        ...content...
    </div>
</div>
<form ...
```

However, the `txp-list-options` is currently appended inside the table's `form` tag right now via some JavaScript so I can't do that structure. Can one of you amend the JavaScript so that it is outside of the `form` and within a `txp-layout-cell-row txp-list-head` div?

I'll commit the new CSS now in preparation. Thanks!

**Comment by bloatware** [comment]
This will take some time (a dozen of tables to revise). I can do it tomorrow afternoon if no one shots first.

**Comment by Bloke** [comment]
I'm tinkering with it now. If I get anywhere, I'll commit, but if you've not heard anything by the morning, assume I've failed!

**Comment by philwareham** [comment]
Ok thanks for trying. Leave it with me for the morning and I’ll see if there’s some different css that can achieve this without so much upheaval. When I created the css for this I didn’t realise list options was inside the form tag.

Might be another solution. Not sure yet.

**Comment by philwareham** [comment]
Not seeing another way to do this - tried a few options but no joy. Sorry, I will need the aforementioned div to contain the list options.

**Comment by phiw13** [comment]
Given current HTML structure, been there, tried all the tricks in the book (and out of it), there is very little you can do.
The proposed solution would be pretty good for smaller screen users.

**Comment by bloatware** [comment]
Leave it with me if you prefer, it won't hurt to put some order into this holy mess (of mine) anyway.

**Comment by philwareham** [comment]
The only tricky thing I can see is that the list options is automatically added to txp-lists. Which is good for plug-in authors as they inherit our widget.

The new HTML I’ve proposed assumes that structure is available above the list - but we can’t guarantee plugin authors will ever follow that. Hopefully there is a way forward.

**Comment by bloatware** [comment]
I have more or less done it for Ajax lists (mainly Content tab) generated via our `Table` class and did my best for plugins. I will try to fix other lists (Comments, Themes) later, just a question: would setting
```
div.txp-control-panel {float: left}
```
break something, both inside a flex parent or not?

**Comment by philwareham** [comment]
The previous CSS used floats left and right for the items above the list. This is not desirable as you can push content down towards the list with floats. And floats can't be used within flex containers (the rule is ignored/overrode.

I tried all manner of float, flex, absolute positioning but the HTML code above is really the only satisfactory way of going.

**Comment by bloatware** [comment]
Ok, I have committed the first part (shouldn't break anything too much). Content lists should work, please test. Will fix the rest this afternoon if nobody does it before.

**Comment by Bloke** [comment]
> since list options are outside of the form now, they are visible even when the list is empty.

Hmmm, I did fear this might be the case. If the table contains no data, doesn't that mean no column headers? And no headers means no list options... right? In theory...

**Comment by Bloke** [comment]
Rats.

**Comment by Bloke** [comment]
All seems to work swimmingly, thanks Oleg.

The only minor niggle, as you say, is that the non-Ajax save on the Themes panel means that the list-options disappear if your search returns nothing. On all Ajaxified pages, the list-options stay put if your search result returns nothing.

Let's worry about that when we refactor `textpattern.js` in the next version.

**Comment by philwareham** [comment]
Why doesn't themes panel follow the same consistency as the rest of the panels? e.g. Ajax-save?

**Comment by bloatware** [comment]
Currently only the lists are ajax updated, not the headers. But when we delete a theme from db (but not disk), it should appear in Import select list that is inside the header.

It shouldn't be difficult to remove list options on no result searches in core, but I'm not sure about plugins.

**Comment by Bloke** [comment]
With reference to d9e5a17, anyone think of a reason why we have no search/pagination on the Plugins panel? Can't think of any technical reason for it.

Is it because we expect the average user not to have many installed? On my dev site I have 160+ so it would be useful. Maybe that's a corner case...

**Comment by philwareham** [comment]
Hi. Is this issue completed? Looks good in my test install. 😀

**Comment by Bloke** [comment]
Yep, works for me too.

**Comment by philwareham** [comment]
Thanks guys!
