### ISSUE TITLE
Odd search behaviour with select none

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1221]
### Expected behaviour

Search select boxes revert to previous selection if none checked.

### Actual behaviour

Search select boxes stay all empty, but search is performed on previous selection.

### Steps to reproduce

1. Visit Articles panel, perform a search. Note results.
2. In search widget, toggle all checkboxes off.
3. Repeat same search as in 1. Note search results are the same.
4. Click search widget to show searched fields - all are still off.

#### Additional information

Not sure what can be done about this. Searching for something nowhere is obviously silly and we (rightly) revert to the previous search selection. But can we indicate this to the user by updating the search widget to check the boxes that were previously there? If you do a full page refresh, the previous selection is restored.

Txp 4.7.0-dev.

**Comment by bloatware** [comment]
Mmm, dunno. I wouldn't like to async update the search widget too (with events to reattach). I think we should either disable the widget if nothing is checked, or not restore the previous selection but output the whole list.

**Comment by Bloke** [comment]
I'm fine with either of those options. Probably the first one makes more sense so you can't perform a search if there's no selection.

**Comment by Bloke** [comment]
Like it, thanks for fixing this.
