### ISSUE TITLE
escape attribute and latence

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1224]
Devs.

Could you try this below which seems to be a heavy memory consumption with a rendering latence:

`<txp:excerpt escape="json,p" />`

`<txp:excerpt escape="tidy,textile,p" />`

Tests with only 2 paragraphs as an excerpt within 4.7-dev latest on a local MAMP server for PC added just before a `<txp:body />` tag for the same article.

**Comment by bloatware** [comment]
Nothing noticeable on WAMP. Any clues in your debug info?

**Comment by petecooper** [comment]
@cara-tm – what is the source text for the article(s) that causes the latency? Are you able to share it here?

I've just tried a 2-paragraph excerpt on an Nginx server and it loads instantly, with no noticeable overhead or anything extraordinary in the debug information.

**Comment by cara-tm** [comment]
Ok. Fine. Maybe it's due to my TXP installation. If you (Devs) consider all is fine, please close this issue.

**Comment by bloatware** [comment]
I can neither guarantee that the regex used in the `escape` attribute is always fast, nor reproduce the issue. An example string would be quite useful.

**Comment by bloatware** [comment]
I have reworked the regex, hope it helps.

**Comment by cara-tm** [comment]
Oh!

**Comment by philwareham** [comment]
If this issue is resolved, please close. Otherwise please give further details. Cheers!
