### ISSUE TITLE
4.7 beta 3 release

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1226]
Hey all! Yep, it's that time again to consider another beta to keep the release momentum up!

To that end, can you let me know any issue blockers to beta 3 release below:

- [x] Make the checkboxes less visually heavy (Phil)
- [x] Add 'sync' checkbox state to theme callbacks (Nicolas or Bloke) https://github.com/textpattern/textpattern/issues/1223
- [x] Hyphen and duplicate article URLs (TBC?) https://github.com/textpattern/textpattern/issues/1191
- [x] Merge lang-tweaks branch into dev (anyone)
- [x] Fix glitches in Hive Neutral admin theme (icon colourings, checkbox/radio borders, etc.)
- [x] Fix glitches in Classic admin theme (missing icons)
- [x] Improve `txp-grid` structure (use CSS Grid where available)

**Comment by petecooper** [comment]
Not strictly relating to OP, but switching demo site to beta 3 is a cinch, so no blockers there.

Also, @philwareham, if time permits could you please add issue hyperlinks/references to OP checkbox points so we can cross-refer in future -thanks!

**Comment by jools-r** [comment]
Maybe also add Stef's language fallback to English for plugins when translation strings are not available in another language from the language-tweaks branch. In my testing, it worked fine.

**Comment by Bloke** [comment]
`lang-tweaks` branch definitely needs folding in. I'm happy with it, just needs updating to dev and merging back in.

**Comment by philwareham** [comment]
I've merged `lang-tweaks` now.

**Comment by bloatware** [comment]
I just have to update the docs on shortcodes, but it's not blocking anything.

**Comment by Bloke** [comment]
Theme sync done.

**Comment by philwareham** [comment]
OK, I've spotted some fixes needed in two of the admin themes - added those to the list. When done, I'm happy to go for beta 3 release.

**Comment by Bloke** [comment]
Sweet, I'll keep an eye on this thread. If nothing else presents itself after you've done those fixes, I'll prep beta 3.

**Comment by philwareham** [comment]
OK, I'm done with my changes. Now ready for beta 3!

**Comment by Bloke** [comment]
Sweet, I'll get beta 3 ready. Blog post is written as Draft.

**Comment by Bloke** [comment]
Actually, @philwareham could you bump the various theme manifests to beta.3 first please? If I do it directly in core, they'll get reverted when you next push from the theme repos. Ta!

**Comment by petecooper** [comment]
Possibly related - `HISTORY.txt` refers to `Changes in 4.7.0`, which implies final release.

Should that be changed or am I overthinking?

**Comment by Bloke** [comment]
Can't get the staff... ;-)

**Comment by petecooper** [comment]
I'll hold off on my issue to move everything 4 and a half pixels anti-clockwise and make the yellow a bit less yellow…

**Comment by Bloke** [comment]
All done. Over to you guys to push whatever buttons need pushing... Thanks everyone!

**Comment by petecooper** [comment]
Beta site updated, successfully rolling on beta 3. Top marks, everyone!

**Comment by petecooper** [comment]
@Bloke - if you can bump this when the official announcement blog post is live, I'll get that shared, too.

**Comment by Bloke** [comment]
No worries, thanks. Since I have strange issues with uploading files to .com, @philwareham takes care of that, so he'll notify when that's done.

**Comment by philwareham** [comment]
Will be back in office in about 30 mins. Will upload then and let you know.

**Comment by philwareham** [comment]
OK, article is live https://textpattern.com/weblog/407/textpattern-cms-470-beta-3-released 🎉🎂
