### ISSUE TITLE
Multiple image/file upload notification stacking

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1232]
### Expected behaviour

When multiple images or files are uploaded, one or more are successful, and one or more fail, notifications should reflect success(es) and failure(s) in a stacked or similar fashion.

### Actual behaviour

When multiple images or files are uploaded, one or more are successful, and one or more fail, notifications do not accurately reflect the outcome.

In the tests I've done, the success notification succeeds the failure notification in quick order, with no way to see what the failure notification said.

### Steps to reproduce

* find an image/file smaller in bytes than the upload limit
* find an image/file larger in bytes than the upload limit
* visit Images or Files tab
* upload both files at once
* note outcome and notifications

#### Additional information

Textpattern version: 4.7.0-dev

Safe for work screencast attached.

[multiple upload notifications.mp4.zip](https://github.com/textpattern/textpattern/files/1884351/multiple.upload.notifications.mp4.zip)

**Comment by Bloke** [comment]
Good catch. Multiple successes seem to stack fine. Ummm, @bloatware, any ideas...?

**Comment by bloatware** [comment]
When you try to upload a file sized beyond the pref limit, txp does not even send it and issues an error notification client-side. And if you are simultaneously uploading a huge and few small files, the small ones are uploaded very quickly and announced so, dismissing the failure notification.

We should tweak the announce process to be able to append new notifications to announced ones, but I have not found an easy way (e.g. to recalculate the status). Morgen, morgen...

**Comment by bloatware** [comment]
No, actually the problem was that if you upload *only* huge files, the notification is not fired server-side, since nothing is uploaded. So I had to trigger it client side.

**Comment by Bloke** [comment]
The only way I could think of doing this would be to always store the flash messages server side (Ajax or otherwise) and always ask the server to fetch the latest message stack at the end of any action chain.

My rudimentary FlashMessage stack that I never finished is attached for perusal. Doubtless there are better methods.

[FlashMessage.txt](https://github.com/textpattern/textpattern/files/1884586/FlashMessage.txt)

**Comment by bloatware** [comment]
Kinda fixed, but needs to be revised later, when we grok jQuery fileupload library.

**Comment by petecooper** [comment]
OP is addressed, so closing – thanks @bloatware!
