### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by colak** [textpattern/textpattern#1234]
There is one string which uses the `skin` term which I guess that it should be replaced

### Actual behaviour

`Not exportable skin names for: <strong>{list}</strong>. Names must match the following regular expression: <code>^[a-z][a-z0-9_\-\.]{0,63}$</code>`.

### Steps to reproduce

https://crowdin.com/translate/textpattern-cms-textpacks/16/engb-el

#### Additional information

Textpattern version: 4.7beta(all)

**Comment by philwareham** [comment]
Fixed, thanks. Closing.
