### ISSUE TITLE
Investigate feasibility of changing article comment "Remember" checkbox from cookie to localStorage

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1236]
See https://forum.textpattern.io/viewtopic.php?pid=310756#p310756

**Comment by bloatware** [comment]
Textpattern is "giving an opportunity to act before cookies are set on a first visit to a site" required by GDPR. We just need to add some "uses cookies" notice near the checkbox perhaps.

Storage would need some external or inline JS that we don't use in core on the public side atm.

**Comment by petecooper** [comment]
Thanks @bloatware - will close.
