### ISSUE TITLE
Article Status: Sticky, the front desk does not display article content.

### ISSUE THREAD

**Issue by ziselive** [textpattern/textpattern#1245]
### Expected behaviour
Display article contents

### Actual behaviour
Article page does not display content.

### Steps to reproduce
http://text.local/articles/text1
This is the generated link. The live article status can display the article content, but the sticky article does not display the content.

**Comment by bloatware** [comment]
It's not a bug since typically you want to output the sticky articles before the live ones with
```
<txp:article status="sticky" />
<txp:article />
```
so the second tag outputs only live articles by default. If you don't mind mixing live and sticky articles, call `<txp:article status />` (latest 4.7-dev).

**Comment by ziselive** [comment]
ummm... What I mean is how to display the entire content of the sticky article in the default article details page.
This default article details page：/forms/article/default.txp
<article class="article" itemprop="blogPost" itemscope itemtype="https://schema.org/BlogPosting">
    <meta itemprop="mainEntityOfPage" content="<txp:permlink />">
    <txp:if_individual_article>
        <h1 itemprop="headline">
            <txp:title />
        </h1>
    <txp:else />
       ...
       ...
</article>
