### ISSUE TITLE
Textpattern 4.7 RC1

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1250]
Please list below any blocking issues to the release of Textpattern 4.7 RC1. We should aim to get this out ASAP I feel. Thanks.

- [x] Test with MySQL 8 (petecooper) #1246 
- [x] Update 4.5 -> 4.7 seems problematic (anyone) #1242
- [x] GDPR compliance #1252

**Comment by petecooper** [comment]
Please update OP to include https://github.com/textpattern/textpattern/issues/1252

**Comment by petecooper** [comment]
This can be closed, now.
