### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1252]
Please see [this forum thread](https://forum.textpattern.io/viewtopic.php?id=48603) for general discussion.

To summarise:

- [x] Remove recording of IP address when comments stored. We don't do anything with that address anyway.
- [x] Recursively remove `ip` column from `txp_discuss` table.
- [x] For `<txp:comment_remember />` tag, ensure it is opt-in (unchecked initial state) for 'remember me?' context.
- [x] Logging system behavioural changes (see below).
- [x] Remove `use_dns` visitor logging preference.

This should make Textpattern CMS 4.7 compliant with GDPR, as no other user data is collated by the CMS (apart from the author accounts). No user data is sent/shared to third-parties.

### Logging system

Following items for discussion.

- Off by default?
- Maybe turn off logging if currently on at Textpattern 4.7 upgrade? Users can then decide to turn on at their own discretion. Not sure about that but worth discussion?
- Remove `ip` and `host` recording (and remove subsequent columns from `txp_log` table.
- Most radical solution: remove logging entirely in core and leave it to plugin authors if this functionality is needed? Server logs collect data anyway which may be of use to power users, if they really need this info. That puts the onus on server owners to ensure GDPR compliance, and not us.

**Comment by philwareham** [comment]
FWIW regarding the comments feature - my vote would be to remove entirely.

**Comment by bloatware** [comment]
I think we should remove `ip/host` recording, but keep the corresponding columns and callbacks data for one more dev cycle, in case plugins use them. We could announce dropping logging in 4.8.

Same for the comments, if an "official" plugin/module is provided in between.

**Comment by philwareham** [comment]
OK, can we remove `ip` collection from comments, and on fresh 4.7 installs not generate that column in `txp_discuss` table. Deleting the `ip` column from that table recursively too at 4.7 upgrade would be my best recommendation since it's not easy for admins without database access to delete stored IP addresses in that table (something necessary for GDPR).

For logging - remove `ip` and `host` collection from `$_SERVER` and not generate those columns in `txp_log ` table. I think corresponding code is around line 72 of `log.php`. No real need to recursively delete the columns as logs are easy to delete in admin panel.

That should give us the necessary GDPR compliance for 4.7. We can dump logging entirely at 4.8 if popular vote is that it is redundant to core needs.

**Comment by Bloke** [comment]
Sounds like a plan.

**Comment by bloatware** [comment]
Shouldn't we remove `referer` too? This means also removing few prefs/strings.

**Comment by philwareham** [comment]
> Shouldn't we remove `referer` too? This means also removing few prefs/strings.

From my understanding, referrer records would still be fine to collect *as long as* user data is anonymous. i.e. as long as the individual user is not identifiable (so no host or IP collection whatsoever) then it's fine to collect referrer data.

**Comment by bloatware** [comment]
It's pity to work on #1253 if in 4.8 the log pane will be gone, but we should remove `ip/host` columns anyway, so...

**Comment by Bloke** [comment]
I still think logging has value, just without IP addresses. For instance, it enables counters to be employed such as the [smd_lately](https://stefdawson.com/smd_lately) plugin.

**Comment by philwareham** [comment]
> I still think logging has value, just without IP addresses.

And without hosts.

**Comment by philwareham** [comment]
I'll add to the first post in this thread, thanks Pete.

**Comment by bloatware** [comment]
There should be no trace of IP in comments now. It has removed also the IP check in "Duplicate comments are not accepted" functionality, but what can we do? I would simply dump it.

**Comment by bloatware** [comment]
It remains to remove `use_dns` strings from textpacks and pophelp, and we should be GDPR-clean.

**Comment by philwareham** [comment]
Great, I’ll do that. Thanks Oleg!

**Comment by philwareham** [comment]
Done. Thanks everybody, good work! Closing.
