### ISSUE TITLE
Consider not using eval() for plugins every time

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1255]
(background: https://github.com/textpattern/com_connect/issues/64#issuecomment-386887752)

Currently, plugin source code is fetched from the database and run through `eval()` for every plugin, every page load. Is there some avenue of optimisation available? For example, running it through `eval()` once on plugin installation/udpate and then stashing the result somewhere else (Another column in the DB? A file that can be brought in via `include_once()`? Both?)

Not only would this help prevent the problems in the linked issue above, it might even be faster. Further things to consider:

* "Recompile" when plugins are altered from the UI.
* Are Textpack changes affected?
* Server/PHP/SQL cacheability.
* Combining plugins.
* Avoiding stale plugin content.

Additional forum post for completeness: https://forum.textpattern.io/viewtopic.php?pid=316613#p316613

**Comment by bloatware** [comment]
Given that some plugins include several assets (js, css), I think we should switch to fs storage anyway, even for "traditional" one-file plugins.

**Comment by bloatware** [comment]
FWIW, there seems to be no performance difference between `eval()` and `include_once()` (tested with ~10 plugins).

**Comment by bloatware** [comment]
A first step is [done](https://github.com/textpattern/textpattern/commit/ee30d92774bda0cf3e38771f72388e05c82bf883), please test it extensively by installing/updating/deleting several plugins via txp interface (`ied_plugin_composer` needs to be updated if we decide to follow this way). Thanks!

**Comment by bloatware** [comment]
I've got zipped multi-assets plugins uploading mostly working now, but can not decide where to store them in a multi-site setup. As I get it, plugins are site-specific, so they shouldn't be shared by different sites using a common txp core. Hence storing them inside `textpattern` folder (common to all sites) is not ideal. Creating a `plugins` directory at sites root conflicts with eventual `plugins` section in almost all permlink modes (actually, the default `files`, `images` and `themes` folders yield the same problem). Any advice?

**Comment by jools-r** [comment]
In a multi-site setup, my guess is they go in the /admin/plugins directory. As that's not in the /public directory, that should not result in section conflicts, right?

**Comment by jools-r** [comment]
@bloatware Also intrigued to see how the zipped multi-asset plugins (and packaging) works as it would be much better for things like bot_wtc and some others to be able to provide everything in one installable package.

**Comment by bloatware** [comment]
@jools-r thanks for the feedback.

> In a multi-site setup, my guess is they go in the /admin/plugins directory.

As I (poorly) understand this setup, sites are sharing core PHP files, but have separate DB. Since currently the plugins are stored in DB, every site can have its own plugins collection, in particular use different plugin's versions. This could create conflicts if we store all plugins in a common directory, though the latter case is rather untypical.

> Also intrigued to see how the zipped multi-asset plugins (and packaging) works as it would be much better for things like bot_wtc and some others to be able to provide everything in one installable package.

That's quite straightforward: unzip the package, read manifests, textpacks and so on and insert them into DB. I will probably commit later this week-end for testing.

**Comment by jools-r** [comment]
> [In] this setup, sites are sharing core PHP files, but have separate DB. Since currently the plugins are stored in DB, every site can have its own plugins collection … [which] … could create conflicts if we store all plugins in a common directory.

Yes, exactly. In the multi-site setup, the `/sites/sitename/admin/` folder is specific to the respective individual site and in [that directory](https://github.com/textpattern/textpattern/tree/dev/sites/site1/admin) the `/admin-themes`and `/vendors` are symlinked back to the respective folder in the central textpattern installation. You can, however, replace the `/admin-themes` symlink with an actual folder to have your own site-specific admin-theme. There's a similar setup with the `/public/themes` folder. If we save the plugin files to the `/admin/plugins` folder, they can be site-specific _and_ wouldn't cause a conflict with a front-side section name.

**Comment by bloatware** [comment]
Thanks @jools-r, makes sense. Will `ahu.'/plugins/'` always point to the right (symlinked or not) directory then?

**Comment by bloatware** [comment]
A ProseMirror [plugin](http://www.iut-fbleau.fr/projet/etc/index.php?s=file_download&id=58) is available for testing multi-assets zipped plugins. Their structure currently is
```
abc_plugin.zip
|_ abc_plugin
   |_ manifest.json
   |_abc_plugin.php
   |_ help.textile
   |_ textpack.txp
   |_ extra assets
```
Please test and report any bugs/improvements/etc.
