### ISSUE TITLE
Option to omit 'Recent articles' in write panel

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1256]
It would be nice to have the option to not show the 'Recent articles' box on the Write page if a user doesn't need it. Less noise.

This might tie in with planned custom field work, but if not then a pref could toggle it on a per-user level.

**Comment by Bloke** [comment]
Yeah. One thing that might be worth considering is some kind of "tray" of blocks that are currently not on-screen. Be that custom fields, excerpt, category block, meta data block, etc. If you click a button that signifies you want to edit the panel, you see this tray/sidebar.

You could drag anything from it to any area on the screen (and other UI components shuffle around to accommodate it?) or you can drag blocks off-screen to the tray (or click some 'destroy' button on each, which will dump them in the tray for future use).

I'm thinking in terms of the way Android does management of icons on the app screens. You tap "Edit" and all the icons become draggable. You can drag them to the trash or reorder them, then just tap 'done' and your UI is how you set it. Fairly simple and intuitive (with the obvious exception being dragging one app on top of another to make a group: that's just bonkers UX).

Whether we can factor this kind of thing in, or if there's something better I don't know yet. But it beats having a tonne of prefs.

Things to concern ourselves with:

* Do only admins get to do this on behalf of users? Or do all users get to do it?
* Is it done per user or per group/role?
* Can a layout be set for each Section? Does that overcomplicate things and we should defer that to plugins? It does mean Ajax to switch things when a Section is changed... and what then happens to any content that's already set, but isn't deemed useful in this Section? Ditch it on Save?
* If per-Section layouts can be defined, what happens with other panels that don't rely on Sections? Inconsistent.
* How to store all this info. localStorage means per device and only for a user. As a (global or per-user / per-group) pref means it works across the board, which might not suit if you hop between mobile and desktop.

Lots to think about. Ideas more than welcome.

**Comment by philwareham** [comment]
This is probably best tackled as part of a rethink of how the write panel (and potentially other panels) are laid out and if/how users can amend those layouts to suit their own workflow. Also tied to how we want to handle custom fields in future - so I'm removing 4.8 milestone tag from this.

**Comment by Bloke** [comment]
The OP (as it is, before I got sidetracked in my above comment) is technically closed, albeit not in a particularly user-friendly manner. In config.php you can add:

```
define('WRITE_RECENT_ARTICLES_COUNT', 0);
```

And the block will disappear. Any other value to display that many recent articles. If you omit it, you get 10.

Soooo, do we close this? Or do we still think a pref is warranted over the constant? Or do we keep this here as a reminder about what to do with custom field blocks? Or start a new issue about the CF stuff using the above comments as a basis?

**Comment by philwareham** [comment]
Start a new issue. As long as we note this method somewhere for now. Pretty handy to know, until something better appears.

**Comment by Bloke** [comment]
Okay, see #1512 

Where's the best place to document the constant that can be set in config.php? In config-dist.php? On the docs site somewhere?

**Comment by philwareham** [comment]
Probably the docs site, although we may need to make a new page for it ;and other define things that can be put in config). I assume this will change when custom fields changes land do don’t really want to put it in config file (although that’s the must logical place).

**Comment by petecooper** [comment]
Def docs site. We have a growing need for some `config.php` kung fu, I think. Tagging https://github.com/textpattern/textpattern/issues/1444

**Comment by Bloke** [comment]
[in here](https://docs.textpattern.com/setup/installing-the-software#create-configuration-file)?

**Comment by petecooper** [comment]
>does it deserve its own section because it's more about tweaking config, possibly at a later time?

This, I would say. If someone is installing and needs the docs, they don't need bogging down with extra tweaks at the start.

I'm rusty on the docs, I'll gen up and see where might it be best placed. I like the idea of a post-install config doc.

**Comment by petecooper** [comment]
We've got this covered in https://github.com/textpattern/textpattern/issues/1512 and I've linked from https://github.com/textpattern/textpattern.github.io/issues/175 to include in the doc, so I'm gonna close this.
