### ISSUE TITLE
Add production status to Diagnostics

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1262]
### Expected behaviour

View production status in Diagnostics.

### Actual behaviour

No reference to production status in Diagnostics.

### Steps to reproduce

View Diagnostics, note missing production status.

#### Additional information

Not sure if I missed the memo on why it's not there, but it would be appropriate for High diagnostics, I think.

**Comment by Bloke** [comment]
Good call. Potentially useful info so added it to both levels.
