### ISSUE TITLE
Standardise on minimum PHP requirements version for 4.7.0

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1263]
[Beta 3 blog post](https://textpattern.com/weblog/407/textpattern-cms-470-beta-3-released) states PHP 5.4 is the minimum system requirements spec, current `dev` branch requires PHP 5.3.3 according to https://user-images.githubusercontent.com/226578/39838994-c1083f1e-53d2-11e8-84e0-bec561918f16.png

[Pophelp says PHP 5.3.3](https://github.com/textpattern/pophelp/blob/master/help/en_pophelp.xml#L326) is minimum, but that hasn't been updated in a while.

We should pick one and stick to it.

@Bloke - not having a dig if there's an error on your blog post, just mixed messaging is all.

**Comment by petecooper** [comment]
Actually, now I think on it I recall something similar. And https://github.com/textpattern/textpattern/issues/1086 seems to corroborate it, though I've omitted any background info why I opened it in the first place.

**Comment by philwareham** [comment]
I've amended the pophelp so it states PHP 5.4.0. @bloke will have to amend the error notice that you screen grabbed as I am not sure what generates that.

**Comment by petecooper** [comment]
I think PH minimum is set here: https://github.com/textpattern/textpattern/blob/dev/textpattern/lib/constants.php#L705

**Comment by Bloke** [comment]
Yep, good spot. Fixed in e2f88f56.

**Comment by vanmelick** [comment]
On 10/05/18 11:56, Phil Wareham wrote:
>
> I've amended the pophelp so it states PHP 5.4.0. @Bloke 
> <https://github.com/Bloke> will have to amend the error notice that 
> you screen grabbed as I am not sure what generates that.
>

5.4 no longer gets any security updates. I'd go for at least 5.6 and for 
the post-4.7 release bump that to 7.x. It should be clear to users that 
it's pointless to update TXP for security reasons if it runs on a PHP 
version with more holes than Swiss cheese.

--Ruud

**Comment by philwareham** [comment]
That’s the minimum it actually runs on, regardless of which version people *should* be using. For 4.8 I’m suggesting bumping to PHP 5.5 as a minimum. Unfortunately there are still a fair few hosts using PHP 5.4 as of today.

**Comment by petecooper** [comment]
Aside: I have a friend who works at a mid-sized shared hosting company, she says part of the reason they offer pre-5.6 PHPs is that there are, in her words, "so many out-of-date, shitty LAMP apps" that continue to function on these older versions…so they continue to offer them…and ~~shitty LAMP apps~~ CMS vendors note they're still available, and are reticent to remove support for them…and the cycle is complete. Whenever they pull an old version, there are sites that go offline and that creates a support burden, so they're reticent to remove support for them. Ugh.

The messaging has changed a bit recently – which is appreciated – although it runs on older PHP, you really should be running on new PHP.

(Aside to the aside: as I understand it, newer PHP has less of a memory overhead at scale, so hosts might see the benefits of that and start migrating more quickly. Or not.)

**Comment by philwareham** [comment]
The cloud hosting company I use (TSOhost) allow you set PHP versions on a per domain/sub-domain basis from PHP 5.2 through to 7.1 - so I'm quote lucky in that respect.

I'm going to suggest we move Textpattern's official sites to them later this year and give up the obsoleted Joyent server (which is locked at PHP 5.4 with no upgrade path). I may move all the textpattern.io sites back to textpattern.com subdomains too now we own that domain and it's DNS, and consolidate with that single domain name for all future endeavours. That'd give good domain weight/value rather than the various domains we have now.

Anyway, I digress...

**Comment by Bloke** [comment]
This is why I like our new approach, at least insofar as it's documented: although we support older stuff, we recommend PHP 7+. Do we need to improve the in-code warning too? e.g.:

It is recommended to run Textpattern on PHP {recommended_version} or higher; it requires at least version {version} to be installed on your server.

Or something like that. Thus, anyone trying to install it on a low-end environment is encouraged to use the highest version possible, and given the minimum specs for info.

I hope we're not included in the list of "out-of-date, shitty LAMP apps"(!) and we're not contributing to the problem by offering a low entry point. Now we can officially support pretty much any version from 5.4 up, any advice on where to place the minimum marker and how to advertise the availability of support for higher environments to help hosters get out of this rut would be appreciated.

**Comment by petecooper** [comment]
>It is recommended to run Textpattern on PHP {recommended_version} or higher; it requires at least version {version} to be installed on your server.

On setup? Admin-side modal that can be dismissed? Nice idea, curious about implementation.

>"out-of-date, shitty LAMP apps"(!)

Nope, not guilty. I won't name names, suffice to say there are _a lot_ of 2005 to 2010-era LAMP apps that have been abandoned, forked, etc and they have a sufficiently low market penetration/attack surface that they just continue to work, and so there's no reason to update them.

>Now we can officially support pretty much any version from 5.4 up, any advice on where to place the minimum marker and how to advertise the availability of support for higher environments to help hosters get out of this rut would be appreciated.

My 2c:

* internally, accept that 5.6 is going to be the final PHP 5 release and decide on a realistic migration schedule
  * 4.7.* = PHP 5.4 minimum, PHP 7.0+ recommended
  * 4.8.* (~2020 onwards) = PHP 5.5 minimum, PHP 7.?+ recommended
  * 4.9.* (~2022 onwards) = PHP 5.6 minimum,  PHP ?+ recommended

Security support for PHP 5.6 ends this year (http://php.net/supported-versions.php).

Textpattern today is streets ahead of two years ago, which is amazing and very much appreciated. Perhaps in a couple of years there will be enough PHP 7 penetration that it's less of an issue.

I absolutely share @vanmelick's view on this, but then I don't consider myself a typical Textpattern user. If the thing just keeps on truckin', which it does, there's less impetus to upgrade stuff.

I would love to see (and maybe I'll write) a blog article for .com that outlines some of the issues involved with older PHP versions. If we can get our own userbase house in order, that'll bring everyone along.

**Comment by Bloke** [comment]
> On setup? Admin-side modal that can be dismissed?

I was thinking about displaying that message if you try to install and don't meet the minimum. Then you have the chance to know to go for the latest and greatest instead of just going for the minimum. And the same or similar message in Diagnostics (perhaps in pre-flight... not sure) if it detects PHP < 7 installed.

+1 on the blog post.
