### ISSUE TITLE
Time zone quirk with UTC

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1265]
(Not a blocker for 4.7.0)

### Expected behaviour

Be able to set `Etc/UTC` from the `Time zone` drop down.

### Actual behaviour

Not able to set `Etc/UTC` from the `Time zone` drop down.

### Steps to reproduce

* set server time zone to UTC
* confirm valid locale set
* note Textpattern's (typically auto-detected) `Time zone` doesn't have `UTC` or `Etc/UTC` in the list, and it default's to the first entry in the list alphabetically (`Africa/Abidjan`).

#### Additional information

`Etc/UTC` (and offsets) appear to be valid tz values (https://en.wikipedia.org/wiki/Tz_database).

It's considered good form to set a server to UTC to avoid DST-related weirdness, and setting each web app's time zone is a logical move from there.

Coincidentally, `Africa/Abidjan` is the same as UTC, but it would be _super_ to actually have `Etc/UTC` available from the dropdown and even better if it could be detected.

```
$ timedatectl status | grep "Time zone"
       Time zone: Etc/UTC (UTC, +0000)
```

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Thank you for reading.

**Comment by Bloke** [comment]
From memory, the list of available timezones and cities is provided by PHP. We just call a function and populate the dropdown. Now, whether the list PHP gives us is "standard" or whether it depends on the installed locales of the host I don't know. Investigation required, thanks for raising this.

**Comment by petecooper** [comment]
Further reading: http://php.net/manual/en/timezones.others.php

```
Warning
Please do not use any of the timezones listed here (besides UTC), they only exist for backward compatible reasons, and may expose erroneous behavior.
```

**Comment by petecooper** [comment]
Tag with a `4.8` milestone for now?

**Comment by petecooper** [comment]
Included in https://github.com/textpattern/textpattern/issues/1128 for consideration, so closing for tidiness.
