### ISSUE TITLE
RPC references in `/textpattern/lib/constants.php`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1271]
https://github.com/textpattern/textpattern/blob/dev/textpattern/lib/constants.php#L74

Brain's a bit hazy on this one – have we removed the textpattern.com RPC functionality completely? If so, does this stuff need to be here at? If not, please instaClose© and accept my grovelling apologies for a needless issue.

**Comment by philwareham** [comment]
It’s on life support as far as I know. I really want it ripped out in favour of GraphQL API at Textpattern 4.8

**Comment by petecooper** [comment]
@philwareham - I don't mean RPC in a given (public) Textpattern instance, that code link defines the `rpc.textpattern.com` server used for language updates and version updates etc, both of which are handled outside of RPC these days.

**Comment by philwareham** [comment]
Oh I see, @bloke there shouldn’t be any RPC server stuff now should there?

**Comment by Bloke** [comment]
Good catch. Yeah, as far as I can make out, that definition can go as it's not used any more.

**Comment by Bloke** [comment]
Thanks, Pete. With regards your PR, we can't unfortunately remove HELP_URL until we fix the glaring oversight that is the comments help link in `publish/comment.php`. What should we do here? We don't have the luxury of the modal popup like we do on the admin side. Should we just serve the popup content as we do now in a separate window, but read it from the local filesystem instead of the RPC server?

**Comment by petecooper** [comment]
Ah, nuts - I forget about that. Hmm. Shall I just close the PR and we can address this post-4.7.0? I mean .com RPC isn't going anywhere for the foreseeable, so it'll continue to work.

**Comment by Bloke** [comment]
Well we can apply half the PR for now. I agree that we should probably figure out how to handle that comment link post 4.7.0. Or link to txstyle.org now if there's a suitable page for "cutdown Textile" on there.

BTW, is it just me or does everyone's site show `textile_help` in the comments help link instead of the `gTxt()` content?

**Comment by petecooper** [comment]
Alright, cool - I've half reverted, `HELP_URL` is back.

**Comment by Bloke** [comment]
Merged, thanks.

**Comment by phiw13** [comment]
> BTW, is it just me or does everyone's site show textile_help in the comments help link instead of the gTxt() content?

Not here - On my own sites, I use my own widget, on the default (4.7.0 them) there is no comment help, affect,

BTW Is it me, or does the comments preview with the default theme not work  at all?

**Comment by petecooper** [comment]
@Bloke 
>BTW, is it just me or does everyone's site show textile_help in the comments help link instead of the gTxt() content?

Works fine here. I appended `<txp:comments_help />` to `comment_form`, like this:
```
<p>
    <txp:text item="enter_comment_here" /> <txp:comments_help />
</p>
```

…and this is how it looks (inline and with popup):

![screen shot 2018-05-14 at 10 12 12](https://user-images.githubusercontent.com/226578/39988506-6b88ac14-575f-11e8-8f63-d488a0c81735.png)
![screen shot 2018-05-14 at 10 12 23](https://user-images.githubusercontent.com/226578/39988507-6b9f2728-575f-11e8-8486-8aae3b3389c6.png)

**Comment by petecooper** [comment]
@phiw13
>BTW Is it me, or does the comments preview with the default theme not work at all?

Works fine here:

![screen shot 2018-05-14 at 10 14 33](https://user-images.githubusercontent.com/226578/39988603-b4e368fe-575f-11e8-8211-0af1db144745.png)

**Comment by phiw13** [comment]
> Works for me too.

Ok, thanks for the feedback. Turns out, the issue I saw has nothing to do with TXP. It is all due to enabling the “block comments” filter in 1Blocker (content blocker) (->`ol.comments-list`)
