### ISSUE TITLE
Spam blocklist check is no longer relevant

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1278]
Assuming all IP/hostname gathering has been removed, spam blocklist checking is now redundant, right? If so, it should be removed from Admin -> Prefs -> Comments.

Blocker for 4.7.0?

**Comment by bloatware** [comment]
Nope, spam checking is still valid. If enabled, it checks IP on-the-fly, without storing it.

**Comment by petecooper** [comment]
Thanks @bloatware - I'll update the docs!

**Comment by bloatware** [comment]
Note that we send IPs to third parties (spam lists) for checking. Dunno how's that re GDRP.
