### ISSUE TITLE
gTxt/pophelp – setup pophelps show untranslated tooltip & title

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1282]
### Expected behaviour

Setup pophelp windows should have translated title.

### Actual behaviour

Setup pophelp windows have untranslated gTxt title.

### Steps to reproduce

* start setup of new 4.7.0 instance
* trigger a pophelp, note the tooltip & title (`help`)
* after install, trigger an admin-side pophelp, note the tooltip & title (`Help` for English)

#### Additional information

Screenshots attached. Please note cursor is not visible. This might actually be a https://github.com/textpattern/pophelp issue but I'm a bit rusty on that, so here it lives for now.

*Setup*
![1](https://user-images.githubusercontent.com/226578/40315452-57364b4a-5d13-11e8-89f5-3173632a5da1.png)
![2](https://user-images.githubusercontent.com/226578/40315453-57501bf6-5d13-11e8-82b3-5ab4b0fa4709.png)

*Admin-side*
![3](https://user-images.githubusercontent.com/226578/40315471-6522de4e-5d13-11e8-820f-34b6a7e1de3f.png)
![4](https://user-images.githubusercontent.com/226578/40315472-6539aa8e-5d13-11e8-8038-bcf9d710adf9.png)

Textpattern version: 4.7.0

**Comment by Bloke** [comment]
Ack, thanks Eagle Eyes. `help` string is missing from setup/lang files. Probably needs to be raised in the textpack repo for completeness.

**Comment by petecooper** [comment]
Alright, leave that with me - I'll open it.

**Comment by philwareham** [comment]
@bloke can you amend in setup code to use `setup_help` here please. That is the string I've added to Textpacks. Thanks!

**Comment by petecooper** [comment]
Fixed! Thanks @bloatware!
