### ISSUE TITLE
Do help link (pophelp) need `target=_blank`

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1293]
I can’t think of any good reason. For assistive technology users, it makes it more confusing. Safari + VO announce it as opening in a new tab, I think - for sighted users it certainly shows them as opening in a new tab in the status bar.

There doesn’t seem to be any Aria attributes specifically for this (or opening a dialog in general); the closest is possibly `aria-expanded - true | false`.

The one exception is the `use Textile` “help” link which goes to an external site

**Comment by philwareham** [comment]
It’s propabky left over from when the help opened in a new small window. Will fix.

**Comment by philwareham** [comment]
Done, thanks!

**Comment by phiw13** [comment]
Much better I think. Thanks.
