### ISSUE TITLE
Offer a config.php download during install

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1294]
### Is your feature request related to a problem?

Nope.

### What is the feature?

Offer a downloadable `config.php` as well as the copy & paste option. One fewer hurdles to entry, and it's a bit faster.

Current workflow:

* create config.php in IDE/SFTP
* copy & paste contents
* check current line endings format is used
* save
* return to browser

Alternative workflow:

* download pre-formatted `config.php`
* upload with IDE/SFTP
* return to browser

Idea blatantly ripped off from FluxBB:

![screen shot 2018-06-05 at 16 46 37](https://user-images.githubusercontent.com/226578/40987703-2a8e4992-68e1-11e8-820f-eca4db5efbdb.png)

Considerations:

* line ending format
* …and this could be a previously-considered idea

**Comment by Bloke** [comment]
Nice idea. Local installs without network access still get the option to copy, paste and create by hand, but the ability to download and pre-populate a template file if possible would be a boon.

Could we offer a double-whammy approach?

Step 1. Try and create the file automatically. If permissions exist and that succeeds, great. Skip straight to the next step.
Step 2. Otherwise, offer the choice of download file, populated, and upload it manually. Or the option to copy n paste as we do now.

Only thing I can see going wrong here is if we need to make changes to the `config.php` structure in future. What happens with people clicking the download button in older installs? We'd just need to be cognisant of keeping it version-dependent somehow.

**Comment by petecooper** [comment]
>Action 1. Try and create the file automatically. If permissions exist and that succeeds, great. Skip straight to the next step.

Yes. I've toyed with the idea of tweaking the install to have the very first screen post-language selection to be a system requirements, file permissions and file integrity check. Assuming file permissions permit the creation, make the file. Absolutely.

>Only thing I can see going wrong here is if we need to make changes to the config.php structure in future. What happens with people clicking the download button in older installs?

The setup (note: not upgrade) routine needs a config.php, so it'll only be the first run. If an upgrade needs extra stuff added to config.php then that'll need an associated upgrade routine with walkthrough.

…or modify the file manually if permissions allow, of course.

**Comment by Bloke** [comment]
> The setup (note: not upgrade) routine needs a config.php, so it'll only be the first run. If an upgrade needs extra stuff added to config.php then that'll need an associated upgrade routine with walkthrough.

Maybe yeah. I was thinking of this scenario though:

* We host `config.php` at some central, well-known location. It contains the usual DB access credentials and paths.
* People can click the Download button, get it pre-filled and upload the file to their server. All good.
* A new version of Txp comes out. Perhaps it supports PDO or something. This may require us to _change_ the content of `config.php`. Introduce a new key name (which isn't an issue) or rename an existing key (which is).
* Someone installing the latest version of Txp is good. Someone installing an older version gets the newer file with different key names and the install doesn't work.

That was my only real concern. That we have to somehow version the `config.php` so we can be sure to deliver the 'correct' template for the version being installed. Upgrades are fine, as you say. We never tinker with `config.php` there.

**Comment by bloatware** [comment]
> Try and create the file automatically

Wasn't there some security concern, like what if someone runs `setup` script before you?

**Comment by Bloke** [comment]
> Wasn't there some security concern, like what if someone runs setup script before you?

Probably. I mean, it's not like it's rocket science to auto-create it. Besides requiring permissions, it should be smooth sailing. So yeah maybe there's an argument to be had for not doing that. Dunno.

**Comment by bloatware** [comment]
Imagine that you have prepared a table, uploaded txp and got disturbed before running `setup`. Then anyone with sufficient db credentials can run it and get a working site without any ftp access.

**Comment by Bloke** [comment]
True. Okay, maybe let's forget automation, but see if we can find a way to permit download of a template into which the credentials can be injected to save a bit of time for those inclined.

**Comment by petecooper** [comment]
4.8 milestone?

**Comment by petecooper** [comment]
Re-reading, I fear I may have explained this proposal in a less-than-ideal fashion.

For clarity: the download button in the FluxBB install relates to a localised file download _after_ the db credentials have been supplied and validated. The download is triggered from the Textpattern instance itself, not from a central location with pre-filled fields. It's purely a "here's the text for the config file you just asked us build from the data you provided".

While I like the idea of forward planning for future versions, it's perhaps outside the scope of this request. Step at a time, and all that!

**Comment by petecooper** [comment]
This looks like it might do the trick: http://cssdeck.com/labs/7bx7mmcm

**Comment by Bloke** [comment]
Over to you @philwareham / @bloatware . What do you think? Where should the button (it's actually an anchor) go and what styling should be applied?

It's 100% added by JS which gives us the option to do some more checks if we wish to omit it from certain environments. Alternatively we could add the anchor itself to the HTML in `setup.php` and just use JS to handle the click action. I'm easy either way.

**Comment by philwareham** [comment]
@bloke I'm happy with the styling (`a` link with `txp-button` class). Wondering if it would be better situated just above the text area though after the "Before you proceed ..." text? What do you think?

**Comment by Bloke** [comment]
Sure, we can shift it wherever you think works best.

I might hard-code it in the HTML and see how it works as I don't see any immediate need to do any jiggery pokery based on the environment so adding it via JS is probably overkill.

**Comment by Bloke** [comment]
@philwareham @petecooper [Like this](https://github.com/textpattern/textpattern/commit/55cc2d735b5d387e9780cc06605e4927a43729e5)?

**Comment by philwareham** [comment]
Looks great to me. Happy to close this issue if you are.

**Comment by philwareham** [comment]
BTW I've changed the classname to `txp-config-download` to avoid any potential clashes.

**Comment by petecooper** [comment]
Thanks again, @Bloke - much appreciated.

OP is achieved. Flawless victory. Closing in 3, 2, 1…

**Comment by Bloke** [comment]
Cool. The only thing that needs adding is the 'download' entry to the setup lang strings so the button gets a proper label. I presume 'Download' is the right thing to put here?

**Comment by petecooper** [comment]
>I presume 'Download' is the right thing to put here?

Or perhaps 'Download config.php', would that be clunky UX, @philwareham?

**Comment by philwareham** [comment]
Just Download would be fine IMO - also then we can just copy and paste the existing string from the main INI files to the setup INI files as it already exists there.
