### ISSUE TITLE
new form type

### ISSUE THREAD

**Issue by colak** [textpattern/textpattern#1299]
### Is your feature request related to a problem?

Not quite a problem but it would be good if a new type of form could be added so as to collate all the short codes. 

### What is the feature?

New form type to help with the taxonomy of Short code.

**Comment by bloatware** [comment]
Not sure about this. Any (article, file, image, ...) form can be used both as short- and long-code, why would we stamp it some way?

**Comment by colak** [comment]
You are absolutely right Oleg, but short codes are mostly created for use within the articles whereas other types are mostly created for use within the pages (templates).

**Comment by Bloke** [comment]
The only reason to have a separate group for such things would be to avoid the currently enforced link between Article Forms and the Override Form on the Write panel. You might want an "article" short code but _not_ have it appear in the override form list.

It's pretty tentative though. I'd rather invest time into figuring out the best way to offer customisable Form types, with the current ones just as defaults.

**Comment by bloatware** [comment]
Short code is not a type, just a shortcut. As for their use, I agree with Yiannis, but then `misc` type forms are used in the same way, aren't they?

I don't quite taste this notion of "type", save for articles (override form), but yes, if we can easily manage custom types, then everyone will be free to organize his forms as he likes.

**Comment by bloatware** [comment]
To add a new form type, say `shortcode`:

- go to Preferences/advanced
- edit `custom_form_types` preference's `shortcode` section, adding a text string per desired language (in `ini` fomat):
```
[shortcode]
*="Short code"
ru="Короткий тег"
```
Star `*` string will be used as fallback.

Note that this makes some preferences theme-relevant, we should probably export/import them too.

**Comment by Bloke** [comment]
Love this feature! And the direct 'Export to disk' feature for Forms and Styles is mighty handy.

My only tiny gripe - and I apologise if this comes across as bike shedding - is the name of the prefs group for the mime and form types. I'm just not a fan of 'Advanced options' as it's a catch-all meaningless phrase, like 'miscellaneous'. One person's advanced options are another person's standard feature. I suspect you struggled to come up with a name too :)

I can't think of anything suitable and succinct as a replacement right now that accurately reflects what the options are so I'm fine with leaving it until we can brainstorm something more definitive.

We need to plan for a 4.7.2 release soon... it rocks!

**Comment by NicolasGraph** [comment]
> To add a new form type, say `shortcode` […]

I just gave it a try and I like the idea. The only thing that surprises me is that I thought that the mime type would be managed through the form name extension, not the form type.
If different "assets" are grouped in form types, couldn't we have only one pref declaring custom form types with their name, name translations, **and** mime type?

```
[es6]
*="ES6"
mimetype="application/javascript"
```

**Comment by philwareham** [comment]
Instead of 'Advanced options' maybe just 'Theme'? i.e. preferences related to themes. Seems to cover this and potential future theme options? Dunno, just throwing it out there.

**Comment by phiw13** [comment]
After just a cursory look, kinda neat feature -)

Side note: after updating my local install/playground, I ended up with two new pref (groups) on the Prefs panel. “advanced” and “Advanced Options”, The first one had just one entry: `txp_evaluate_functions`.

Not sure about the name. “Advanced Options” isn’t perfect, but sits better than “theme”. Hmm. “Component options”?

**Comment by philwareham** [comment]
All preferences are options. Otherwise we would have 'Site options', 'Admin options', etc. We need something short but obvious. Scratching head.

**Comment by bloatware** [comment]
Thanks for the feedback, nothing is definitive yet, as ever :-) I'm not sure for `Theme`, because some other preferences (say, custom fields names) can be theme-related too. Should we group all "custom" stuff under a common theme-exportable tab, perhaps?

@phiw13 sorry, forgot about this easter egg. It will migrate where we deem appropriate in 4.7.2 release.

@NicolasGraph yep, good idea. I was tempted to unify these two prefs too (though differently), we just have to ensure there will never be `mimetype` language. +1

@Bloke let's roll it out for Christmas and start working on 4.8?

**Comment by philwareham** [comment]
If we could export/import all theme-relatable prefs as part of the theme panel export/import that would be very nice! 😀

i.e. this new custom form/mime stuff, custom fields, anything else in prefs that makes/breaks a theme.

One thing I can think of though is that if someone imports a theme - adds load of additional custom fields and content  to their site - then re-imports the theme destructively, they would wipe all their custom field stuff.

**Comment by philwareham** [comment]
And yes, we need to finish the 4.7.x branch and start on 4.8 as soon as feasible. Christmas (just before Christmas) final 4.7.x release sounds like a good and achievable plan.

**Comment by bloatware** [comment]
I think we'll need such a general section in 4.8 anyway, so we'd better think of it twice. Meanwhile, we could move custom forms pref to custom fields section, but nobody would ever notice it there, I'm afraid.

**Comment by philwareham** [comment]
I think this is in a state we are all happy with now? Can issue be closed? Thanks.
