### ISSUE TITLE
Emoji-only article titles don't generate a valid URL-only title

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1300]
### Expected behaviour

Some sort of parsing for emoji -> entity translation (e.g. 💩 -> `U+1F4A9`) on 100% emoji article title to generate a URL-only title entry.

### Actual behaviour

No emoji -> entity translation, as far as I can tell.

### Steps to reproduce

* create a new article with an entirely emoji title (e.g. 💩💩💩 )
* save/publish the article, note the warning about the article being saved without a URL-only title

#### Additional information

Textpattern version: 4.7.0

This might have a whiff of edge case about it. Is there scope for escaping or parsing emoji into something appropriate on the URL-only title?

**Comment by bloatware** [comment]
Good point, and not only for emoji. Our `dumbDown()` function looks too restrictive in 2018, IRI are quite common nowadays. And it's not of much help security-wise, since the user can type anything he wants as `url_title`.

**Comment by petecooper** [comment]
@bloatware –
>IRI

[This IRI?](https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier)

**Comment by bloatware** [comment]
zactly, currently we convert `.../Гугл` (Google transliterated in Russian) into `.../Gugl`, not sure what's better.

**Comment by petecooper** [comment]
Would [Punycode](https://en.wikipedia.org/wiki/Punycode) be viable?

**Comment by bloatware** [comment]
For hostnames it certainly would, but looks overkill for article URL. I would just strip what is confusing (/, ?, &, %, ...) and leave the rest alone.

**Comment by petecooper** [comment]
FYI: setting the URL only title slug to 💩 produces a valid `permlink` and works perfectly fine in a modern browser.

**Comment by phiw13** [comment]
Fwiw - when I create an article with a Japanese title (kanji/kana), the url-only field is filled with those character; the `<txp:permlink />` is URL encoded. The browser URL bar shows the JPN characters.

e.g title: `夜` (yourou, night), permlink: `/articles/%E5%A4%9C`

accessing `/articles/%E5%A4%9C` or `/articles/夜` works correctly - that is expected.

For emoji specifically, I see the behavior as described in the OP (url-only is left blank) but the message pane  gives me a warning (`Article posted. URL-only title was left blank.`). If I do fill the field manually, pasting the emoji, then the permlink is generated, URL encoded.

**Comment by bloatware** [comment]
Yes, the "alphanumeric" (even Japanese) characters are preserved, though some of them are first transliterated (e.g. Cyrillic `ж` => `zh`). Not sure why we need this transliteration.

**Comment by petecooper** [comment]
Throw a 4.8 milestone on for now and toss on the back burner?

**Comment by bloatware** [comment]
Code-wise it seems to be straightforward, we just need a decision. Most of this transliteration stuff looks outdated for me, but I'm not a SEO guru.

**Comment by petecooper** [comment]
Thanks @bloatware !
