### ISSUE TITLE
[UX] Invalid `permlink` URL on articles without a URL-only title in some link modes

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1301]
### Expected behaviour

Articles with no URL-only title should have a valid `permlink` URL, or yield nothing, across all link modes (article link pattern).

### Actual behaviour

Articles with no URL-only title don't have a valid `permlink` URL and yield a URL to the section in some link modes. While the section URL is valid in itself, it's not a link to the article, which is what `permlink` focuses on, and some confusion ensues (with me, at least).

### Steps to reproduce

* publish an article with no URL-only title, and include `<txp:permlink />` in the body for diagnostics
* cycle through the link modes, note how the `<txp:permlink />` URL changes for each

1. **?=messy** (valid)
`https://example.com/index.php?id=2`

2. **/id/title** (valid)
`https://example.com/2/`

3. **/section/id/title** (valid)
`https://example.com/articles/2/`

4. **/year/month/day/title** (invalid, links to any articles from that period)
`https://example.com/2018/06/15/`

5. **/section/title** (invalid, links to article list for assigned section)
`https://example.com/articles/`

6. **title** (invalid, links to root / default)
`https://example.com/`

#### Additional information

Textpattern version: 4.7.0

### Possible solutions

I'm not sure, honestly. Where the link mode has a title slug and no numeric ID (see 4., 5., and 6. above), don't output a URL at all. This is preferable to outputting an invalid/incorrect URL, especially with the schema.org metadata integration in Four Point Seven.

That way, `yield` could be used to determine if there's a valid final URL in front end theme pages/forms, and construct if it's valid.

**Comment by bloatware** [comment]
I guess we can just generate a messy URL in this case, it is valid in any mode.

**Comment by petecooper** [comment]
Actually, yes - that's a smart solution. Thank you!
