### ISSUE TITLE
Blank URL-only title does not save on existing article, and more

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1302]
### Expected behaviour

Deleting/removing an existing URL-only title slug then saving the article should respect the empty article slug.

### Actual behaviour

Deleting/removing an existing URL-only title slug then saving the article does not respect the empty article slug.

### Steps to reproduce

* create a new article, save/publish, confirm URL-only title is set
* delete the URL-only title slug, save/publish
* note the deleted URL-only slug has returned
* change this URL-only title slug to something different, save publish
* delete the new slug, note the original slug has returned

#### Additional information

Textpattern version: tested with 4.7.0 and 4.7.1-dev.

Screencast attached (no audio, safe for work)

[1303.mp4.zip](https://github.com/textpattern/textpattern/files/2107525/1303.mp4.zip)

**Comment by bloatware** [comment]
For newly created articles it's a feature, since their `url_title` is usually empty. And I actually don't see why would you empty this field?

**Comment by petecooper** [comment]
Thanks @bloatware - I'll chalk this up to another edge case.
