### ISSUE TITLE
`dev` version reports a confusing version string

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1311]
### Expected behaviour

`dev` branch should report its version string as a development version.

### Actual behaviour

`dev` branch is reporting as 4.7.2 at the moment, which indicates production release.

### Steps to reproduce

* check out the `dev` branch, install it, note the version string in Diagnostics

#### Additional information

![screen shot 2018-07-06 at 11 52 26](https://user-images.githubusercontent.com/226578/42375326-1b0af64c-8113-11e8-9b8f-0b1207af3f65.png)

**Comment by Bloke** [comment]
Unfortunately this is just to make merges simpler between 4.7.2 branch and dev. If we set the version to 'dev' then every merge requires manual intervention to fix the version string "conflict", which is a royal pain.

When we make fewer 4.7.x commits and/or spend more time on 4.8-dev features compared with patching 4.7, we'll flick the version to 'dev' then.

Please bear with us in the meantime. Or if you know of any git tricks that'll help bypass this then let us know, as I'd love to find a way round this. Ta!

**Comment by petecooper** [comment]
Makes total sense - thanks @Bloke. Will close.
