### ISSUE TITLE
Article image

### ISSUE THREAD

**Issue by p0limorf** [textpattern/textpattern#1316]
Hi!
I inserted the default image link for an article in the "Article Image"
Then, when you view this article, this image also appears at the top of the page. This can be played in the demo on the site https://dev-demo.textpattern.со
After studying this problem, I found a piece of code that does not work correctly: Presentation -> page -> archive
```
            <txp:if_article_image>
                <txp:images limit="1">
                    <meta property="og:image" content="<txp:image_url />">
                    <meta property="og:image:width" content="<txp:image_info type="w" />">
                    <meta property="og:image:height" content="<txp:image_info type="h" />">
                    <meta property="og:image:alt" content="<txp:image_info type="alt" />">
                </txp:images>
            </txp:if_article_image>
```
Now, Open Graph does not work correctly...

**Comment by philwareham** [comment]
Hi, you need to insert the image ID number in the "Article image" field, not an absolute path. Otherwise the system doesn't hold the meta info needed to dill out this code snippet. See [article image field] documentation (https://docs.textpattern.io/administration/write-panel#article-image) for more info.

**Comment by p0limorf** [comment]
I understood. Thank you. But the tooltip shows other ambiguous ways. I hope my question, and your answer, will be useful to other users.

**Comment by philwareham** [comment]
Cheers. I’ll amend the documentation in due course to make this more obvious.
