### ISSUE TITLE
File/image uploads & warnings when directory not writable

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1317]
### Expected behaviour

If `files` and/or `images` are not writable, there should be a warning shown and ability to upload (or attempt upload) should be omitted for both new and existing (replacement) uploads.

### Actual behaviour

If `files` and/or `images` are not writable, there's a warning shown on the file/image list, and ability to upload (or attempt upload) is omitted. Where a file/image already exists and `files` and/or `images` are not writable, no warning is shown on the file/image details screen and an upload facility is provided, though it fails as expected.

### Steps to reproduce

* upload a file or image and ensure it's recognised by Textpattern
* set `files` or `images` to not writable by the web server user
* visit `/textpattern/index.php?event=image` or `/textpattern/index.php?event=file`
* note yellow warning about not being able to write
* select existing file or image filename to edit (e.g. `/textpattern/index.php?event=file&step=file_edit&id=1`
* note no yellow warning about not being able to write, note file/image upload facility

#### Additional information

Textpattern version: 4.7.1

Screenshots below.

*File list*

![screen shot 2018-08-04 at 16 05 12](https://user-images.githubusercontent.com/226578/43677891-7fa8cd54-9801-11e8-9c37-c51c05b270c7.png)

*File detail*

![screen shot 2018-08-04 at 16 05 18](https://user-images.githubusercontent.com/226578/43677894-87012146-9801-11e8-8a40-1c43ba7c6b40.png)

*Image list*

![screen shot 2018-08-04 at 16 04 23](https://user-images.githubusercontent.com/226578/43677895-8d521488-9801-11e8-8dd9-4b44f2eb47a0.png)

*Image detail*

![screen shot 2018-08-04 at 16 04 35](https://user-images.githubusercontent.com/226578/43677897-93d0da38-9801-11e8-95cd-b3ff2af2d3ed.png)

**Comment by petecooper** [comment]
Confirming https://github.com/textpattern/textpattern/commit/d098689cc00c23638193039387c0d5b5d01d97a1 has resolved this issue for Files - thank you very much @bloatware!

**Comment by bloatware** [comment]
@petecooper Weirdly, I succeed in replacing an image/thumbnail on your dev site, despite of restrictions.

**Comment by petecooper** [comment]
The files and directories have different permissions, it seems. Directory is 555, files are 775 (oops). I will rectify that now - thanks for the report.
