### ISSUE TITLE
Persistent Cross site Scripting in textpattern-4.7.1

### ISSUE THREAD

**Issue by security-provensec** [textpattern/textpattern#1327]
Affected software: Textpattern-4.7.1

Type of vulnerability: Persistent Cross-site Scripting

URL: https://textpattern.com/

Discovered by: Provensec LLC

Website: https://www.provensec.com

Author: Subodh Kumar

Vulnerability Description: Cross-Site Scripting (XSS) attacks are a type of injection, in which malicious scripts are injected into otherwise benign and trusted web sites. XSS attacks occur when an attacker uses a web application to send malicious code, generally in the form of a browser side script, to a different end user. Flaws that allow these attacks to succeed are quite widespread and occur anywhere a web application uses input from a user within the output it generates without validating or encoding it.

Steps to reproduce vulnerability: -

1) Login the admin account.
2) Locate URL: http://127.0.0.3/textpattern/index.php?event=article&step=edit&ID=2&_txp_token=e0e3b8f490266011e6ca6d9c3c4f62e0
3) Put XSS payload "><svg/onload=alert("XSS")> and save. (Image-1.png)
4) Now, save the post and click on View (XSS payload gets executed, check Image2.png).

Vulnerable URL:
http://127.0.0.3/textpattern/index.php?event=article&step=edit&ID=2&_txp_token=cfaa7d07bd4870d91bd5aca1ffe746c7

Vulnerable parameter:
Input field name: -     Body (textarea)

Snapshots attached:

![image-2](https://user-images.githubusercontent.com/41563984/44205681-d664ab00-a174-11e8-84d7-aa82fd86a02c.PNG)
![image-1](https://user-images.githubusercontent.com/41563984/44205683-d664ab00-a174-11e8-986e-a4235f393403.PNG)

**Comment by rwetzlmayr** [comment]
PEBKAC, see #1312 and #1313
