### ISSUE TITLE
Potential `load_lang(LANG);` bug

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1328]
Just leaving this here so it doesn't get missed, please [see forum post](https://forum.textpattern.io/viewtopic.php?pid=313443#p313443).

Not sure if it's a bug or not so please can someone confirm and fix of needed. Cheers!

**Comment by philwareham** [comment]
@bloke thoughts on this one? Cheers!

**Comment by Bloke** [comment]
Yeah, I'm not sure about this. We've essentially killed off `$textarray` but maybe MLP (being legacy code) still needs it in this place. We did reintroduce it elsewhere for backwards compatibility so perhaps we should do so here. I don't think it'd do any harm, I'll check.
