### ISSUE TITLE
Login panel and browsers with cookies disabled

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1331]
A kind of an issue, more an UI enhancement.

Currently (TXP 4.7-dev): when you disable cookies within your browser, the Textpattern login page do not display nothing (a blank screen). May be a place for a warning message?

    <script>
    if (true !== navigator.cookieEnabled) {
        alert('Currently, your browser is set to disable cookies (check preferences).');
    }
    </script>

**Comment by bloatware** [comment]
I like the idea of a warning, but am not sure it covers all possible scenarios in this form. For example, if some browser extension blocks txp cookies, `navigator.cookieEnabled` will not necessary detect it. Moreover, the login screen will function normally, but the user will be redirected to it on consequent requests. Shouldn't we rather issue some unconditional "we use cookies" message on the login page?

**Comment by bloatware** [comment]
Actually, we already do this check, but something clashes with `localStorage` when cookies are disabled and the script is seemingly dropped. Needs investigation.

**Comment by bloatware** [comment]
Should be fixed by [this commit](https://github.com/textpattern/textpattern/commit/2143c82e61e8fe62842a19ae7fa533c04cf8815a), though the presentation is open to discussion.

**Comment by bloatware** [comment]
Closing, please reopen if necessary.

**Comment by cara-tm** [comment]
Fine, Oleg.
But after cookies disabled/enabled I've got this modal message (even if I clear my cache):

`Please force-reload the page or clear your browser caches`

**Comment by bloatware** [comment]
@cara-tm do you remember the STR? It happened to me once, but I can not reproduce it anymore.

**Comment by cara-tm** [comment]
It's pretty frightening! 😃

Disable, then restoring "Cookies" support within my browser (FF latest), I get this popup message: "`Please force-reload the page or clear your browser caches.`" However, reloading the page or clearing my cache haven't any effects.
