### ISSUE TITLE
RFC: how to handle default comment?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1337]
Scenario:

* install new, vanilla Textpattern
* read and understand default article
* delete default article

Default article comes with a default comment, which since Textpattern has commenting off by default, is not directly accessible from the admin-side (though a URL will work), and if (when) the default article is deleted, Donald is then orphaned.

It's a minor or perhaps trivial observation, but is there something practical we can do to mitigate this? I've already put a general link to the comments list in the article, is that sufficient?

**Comment by bloatware** [comment]
Donald will not survive his father anymore, can be closed.

**Comment by petecooper** [comment]
Thanks @bloatware!
