### ISSUE TITLE
Delete associated comments when deleting an article

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1338]
### Is your feature request related to a problem?

For me, no. For new installs, see https://github.com/textpattern/textpattern/issues/1337

### What is the feature?

Comments are assigned to an article ID. When deleting one or more article(s), include the option to delete associated comments.

Pros:
* keep database clean of orphaned comments
* useful as part as of database maintenance regime

Cons:
* might not be viable, possible or practical

**Comment by bloatware** [comment]
I actually thought they *were* deleted... So, should we add a "Delete associated comments" checkbox?

**Comment by petecooper** [comment]
>I actually thought they were deleted...

So did I, but not the case with 4.7.1.

For completeness, screencast for 4.7.1 (but with comments enabled) attached.

[comment.mp4.zip](https://github.com/textpattern/textpattern/files/2357396/comment.mp4.zip)

**Comment by petecooper** [comment]
>So, should we add a "Delete associated comments" checkbox?

From a UX perspective, sounds great. Is the database cleanup straightforward to do procedurally?

**Comment by bloatware** [comment]
Looks straightforward, though we should also fire `discuss_deleted` callback. The rest depends on whether the checkbox state must be persistent (hence new user pref).

**Comment by Bloke** [comment]
I thought they were deleted too. Is it simply the case that if the comments pref is off, they're not deleted but if it's on, they are?

I'm of the opinion that if the article goes, the comments go. No option. Why have orphan comments? Is there any practical reason? Maybe you could write a new article and reattach them at some point, but does that have any practical merit given the comments may not pertain to the new content?

Am I missing a use case to keep them around after their parent article is deleted?

**Comment by petecooper** [comment]
If this is a logic change -- and I'm heavy +1 to @Bloke with "article goes, comments go", do we need to also need to factor in a db cleanup on upgrade for orphaned comments?

**Comment by Bloke** [comment]
I'd be tempted to leave legacy comments, despite the mess. Less chance of something going wrong on upgrade.

It's a nicety, but not much hardship to remove them if you stumble upon them, as you can sort by Parent column and Multi-edit->Delete when they appear at the top of the list.

But I don't mind either way. The same as I don't mind having a checkbox that behaves the same way as the one when deleting disk-based themes, if we deem that doing so makes sense. But if it doesn't, then convention trumps configuration and the comments go when their parent is deleted.

**Comment by petecooper** [comment]
>I thought they were deleted too. Is it simply the case that if the comments pref is off, they're not deleted but if it's on, they are?

In my test, no. See https://github.com/textpattern/textpattern/files/2357396/comment.mp4.zip

>Why have orphan comments? Is there any practical reason? Maybe you could write a new article and reattach them at some point, but does that have any practical merit given the comments may not pertain to the new content?

And you'd need to manually renumber the article in some way (presumably a database fiddle), which is edge case for most sites.

>Am I missing a use case to keep them around after their parent article is deleted?

I've thought about this for a couple of hours and can't think of anything. Would someone perhaps want to save evidence for legal proceedings? It's a stretch, I know.

**Comment by Bloke** [comment]
> Would someone perhaps want to save evidence for legal proceedings?

If this was the case, they should probably set the article status to Hidden and therefore preserve the comment history.

If the article is deleted, I'm with you: honestly can't think of a reason to keep associated comments.

**Comment by bloatware** [comment]
The origin seems to be [here](https://github.com/textpattern/textpattern/commit/18784f40c67d5ab1a234b6e44707e0788ae53018), but not an explanation.

**Comment by Bloke** [comment]
Hmm, good find. 2006, wow.

Do we "ask the audience" on the forum and see if anyone can come up with a good reason to keep comments on deleted articles, or do we just change that line of code to `safe_delete()@`?

**Comment by petecooper** [comment]
>Do we "ask the audience" on the forum and see if anyone can come up with a good reason to keep comments on deleted articles

Yes. I have a few names in mind that I'd appreciate their point of view.

**Comment by petecooper** [comment]
PS: @Bloke -I'll open a forum thread unless you have any objection.

**Comment by Bloke** [comment]
Spot on, Pete. Thanks.

**Comment by petecooper** [comment]
Forum consensus seems to be in favour of "delete article, delete comments".

**Comment by bloatware** [comment]
Yeah, all the five :-)

**Comment by petecooper** [comment]
@phiw13 was one person who I was hoping to hear from, his +100 counts for _at least_ another half a person, though…maybe even a whole one.
