### ISSUE TITLE
Reduced width for the “Title” input field

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1339]
Currently (TXP 4.7-dev), the “Title” input field within the “Write” page is smaller in width than other fields because the rule affected to it is set as this:

    .navlink, .navlink-active, .navlink-disabled, .txp-button, .txp-logout a, button, input, optgroup, select, textarea {
    	max-width: 100%;
    }

![write-tab](https://user-images.githubusercontent.com/61045/45222372-abbdcc00-b2b4-11e8-894a-bf4b048139ad.png)

May be that could change the global visual aspect:

    #main_content .text input, #main_content .text textarea {
    	width: 100%
    }

**Comment by philwareham** [comment]
There was a reason for this being shorter but I can't remember why. Maybe we had planned on having an action to the right of the field at some point. OK, will probably amend.
