### ISSUE TITLE
Sections name / title will not save with emojis

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1340]
### Expected behaviour

Ability to save a section name and/or title with emoji characters.

### Actual behaviour

Section will not save from admin-side if name and/or title contains emoji. Manual database (`utf8mb4`) edit _does_ seem to work, and is reflected in admin-side after saving.

### Steps to reproduce

* create or edit a section name to include emoji characters, save
* note the error on failing to save
* manually edit `txp_section` in a `utf8mb4` database to achieve the above
* note the emoji(s) are shown in the admin-side

#### Additional information

Textpattern version: current `-dev`

And although I hate myself for raising another emoji issue, a friend of mine has Asperger syndrome and she's waxing lyrical about how these infernal bloody emoji things have changed her life communications-wise, so from an a11y aspect emoji is potentially a big deal.

**Comment by bloatware** [comment]
Emoji in the title are working fine in my tests. Re emoji in the name, I'm unsure whether we should allow them. Unlike articles `url_title`, sections `name` is quite common in tags attributes, but emoji are rather hard to type and easy to confound. And I have already tried, it didn't work. :-)

**Comment by petecooper** [comment]
Thanks @bloatware - will close.
