### ISSUE TITLE
Pophelp `?` anchors flash once on first trigger

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1345]
### Expected behaviour

Pophelp `?` anchors should not flash when clicked/tapped.

### Actual behaviour

Pophelp `?` anchors flash when clicked/tapped for the first time. Subsequent triggers on the same pophelp anchor do not cause the flash. If the page is reloaded, the flash appears again on the first trigger.

Tested in Mac/Safari 12 and Mac/Firefox 62.

### Steps to reproduce

* view any admin-side page with `?` pophelp triggers;
* click or tap `?` pophelp anchor to trigger pophelp;
* note the flash on the first trigger, and no flash on subsequent triggers;

#### Additional information

Textpattern version: vanilla 4.7.1 and -dev 

SFW screencast attached. Note that mouse clicks trigger the ripple effect on video, so it's not super clear, but hopefully gives you the gist.

[pophelp.mp4.zip](https://github.com/textpattern/textpattern/files/2438617/pophelp.mp4.zip)

**Comment by petecooper** [comment]
Follow-up: triggering the `?` on the admin-side login page does not appear to cause the flash effect.

**Comment by philwareham** [comment]
Probably some JavaScript/jQuery firing thing. Maybe @bloatware can offer a solution - not my area of expertise (not a CSS issue as far as I can tell)?

**Comment by bloatware** [comment]
This possibly comes from `a.busy{visibility:hidden}` rule, please check. The class is appended (and then removed) on the first click.

But yes, our JS is a mess.

**Comment by philwareham** [comment]
OK, thanks. Let's defer this until we tackle https://github.com/textpattern/textpattern/issues/1178

**Comment by bloatware** [comment]
Formally, it works as expected: the help text is loaded on the first click, taking some time (whence `busy` class). On subsequent clicks the text is served instantly from some "cache". I don't see how/whether should we amend this.

**Comment by philwareham** [comment]
OK I can live with the quick flash, it's milliseconds on my machine after all. Pete?

**Comment by petecooper** [comment]
Yeah - close it, or I’ll close it when I’m back in office. Thanks for clarification!

-- 
Pete Cooper
pete@pragmatika.net
