### ISSUE TITLE
HISTORY.txt content

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1347]
### Is your feature request related to a problem?

No just some considerations.

### What is the feature?

`HISTORY.txt` file could have some better considerations: open it into your default system text editor, its content is displayed on a single line and becomes illegible!
Are there any disadvantages to not adding line breaks in it?

**Comment by philwareham** [comment]
It's fine in all my text editors - all the line breaks in place, and the raw file displays fine on GitHub too https://raw.githubusercontent.com/textpattern/textpattern/dev/HISTORY.txt

What system and editor?

**Comment by cara-tm** [comment]
No. Not on PC with Windows 10 and its defaut text editor.

**Comment by philwareham** [comment]
Please see here: https://www.theregister.co.uk/2018/05/08/windows_notepad_unix_linux_macos/

Closing.

**Comment by cara-tm** [comment]
You're right. I'm sorry.
(Here is the HISTORY file opened in NotePad, the default text editor with Win 10 up to date, latest upgrade done yesterday: no line breaks, no tabs)

«_La discussion est close_.»

![history-file-notepad](https://user-images.githubusercontent.com/61045/46661260-21210300-cbb9-11e8-97c5-8c46d501ffba.png)

**Comment by philwareham** [comment]
So it's not fixed?!

**Comment by Bloke** [comment]
It's a standard feature of crappy Notepad, time immemorial. It doesn't handle UNIX line endings at all well, which is our default. Short of making the HISTORY file DOS format, I can only suggest right-clicking and opening it in a different text editor that is useful.
