### ISSUE TITLE
Allow `aria-label` and `placeholder` attributes on form input txp tags

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1351]
### Is your feature request related to a problem?

No, just a minor enhancement to 4 tags.

### What is the feature?

We should allow users to specify an optional `placeholder` and `aria-label` attribute on form fields generated by:

    comment_email_input
    comment_message_input
    comment_name_input
    comment_web_input

This allows form fields without labels, that are still accessible. It's also a requirement if you want to support displaying HTML pages with form fields on Apple Watch.

**Comment by philwareham** [comment]
Also of interest ([source](https://marcus.io/blog/websites-on-apple-watch)):

Wenson Hsieh of WebKit explaining their intention regarding form labels on Apple Watch:

> "[Placeholders are] no substitute for labeling form controls. However, it is a valuable source of context for a focused element, in the absence of any other attributes/labels! It's preferable to have a real `<label>` associated with the form control, or at least specify an aria-label — currently, the order of precedence that determines what text goes in the status bar if there are multiple potential sources is **(1)** text of an associated `<label>`, **(2)** `arial-label` attribute, **(3)** `title` attribute, and finally **(4)** `placeholder` as a last resort."

**Comment by phiw13** [comment]
Yeah, I was going to comment on that. Strictly,  the `aria-label` is not needed as long as your field is associated with a `label`. Wenson Hsieh and some other Webkit engineer were very clear on that in another twitter thread of which I lost track.

There is no harm, though, to have support for `aria-label` on those fields - or better, have support for `aria-label` for all TXP internal fields (including texture, select, …). com_connect uses those to build the fields, afaik.

**Comment by philwareham** [comment]
> Strictly, the `aria-label` is not needed as long as your field is associated with a `label`.

Indeed, but since the label is generated by an additional tag, and not enforced, it'll be good to have the alternative option.

> ...or better, have support for `aria-label` for all TXP internal fields.

Yep, we can do that.

**Comment by philwareham** [comment]
So for completeness those extra attributes would mean:

`function selectInput()`
Add `required`, `autocomplete`, `autofocus`, `aria-label`

`function text_area()`
Add `disabled`, `required`, `autocomplete` (boolean), `autofocus`, `aria-label`

Don't know about `radio` and `checkbox` type inputs, I guess they would always have a label so would never need an `aria-label`.

@bloke @bloatware what are your feelings on the above? By doing so we can gain a slight UX improvement for parts of our UI. For example, the language selector on first setup page could then have `autocomplete="language"` and `autofocus`.

**Comment by philwareham** [comment]
OK, I'll probably need some help getting the above done. Not in my comfort zone really.

> we'll scrap it all anyway in favour of the widget library...

Anywhere I can see this widget library and see how we'll implement it?

**Comment by Bloke** [comment]
> OK, I'll probably need some help getting the above done. Not in my comfort zone really.

No probs. Just holler.

> Anywhere I can see this widget library and see how we'll implement it?

Yep, check out the `widgets` branch and play. Examples in the [thread, from here onwards]( https://github.com/textpattern/textpattern/issues/968#issuecomment-341085645).

**Comment by bloatware** [comment]
FWIW, `fInput()` third argument can be an array [now](https://github.com/textpattern/textpattern/commit/f2865e7116ed4f738dab2ead5b62e16df158e0c2) where you can add any attribute you need.

**Comment by philwareham** [comment]
@bloatware oh, ok that’s a better solution, thanks. I’ll remove the additions I made and put them there instead. Could you possibly do same for select and textarea functions?

**Comment by bloatware** [comment]
That looks easy for textarea, but less evident for select. Would it be ok if we allow their first `$name` argument be an array? A bit fuzzy, but if we are going to replace them anyway...

**Comment by philwareham** [comment]
I'm sure that will be fine - as you say, we will be deprecating them in 4.8 anyway.

**Comment by bloatware** [comment]
@philwareham [done](https://github.com/textpattern/textpattern/commit/90073ddf5b75880e3f19367f82b496569f7c8f25). Now the first (i.e. `$name`) attribute of `selectInput()` and `text_area()` can be an array of attributes.

For consistency, now the *second* (i.e. `$name`) and **not the third** attribute of `fInput()` can be an array, sorry if you have already started using it.

**Comment by philwareham** [comment]
Thanks @bloatware and @Bloke. Any chance one of you could add those `aria-label` and `placeholder` as optional attributes on the tags I listed in the original issue above? We can then close off this issue. Cheers!

**Comment by bloatware** [comment]
@philwareham should it be called `aria-label` or `aria_label` or `arialabel`? Historically, it would be `aria_label`, though all three are possible in 4.7.

**Comment by philwareham** [comment]
`aria_label` name is fine for consistency. It also distinguished it from the actual HTML attribute which can be helpful.

**Comment by bloatware** [comment]
ok, will do.

**Comment by bloatware** [comment]
@philwareham mostly done, just curious about the useless 13th argument (like `name`, `email`, `url`) passed by these functions to `fInput()` that only takes 12. Should I remove it?

**Comment by philwareham** [comment]
Oh, that might be the remnants of autocomplete attributes which I’ve removed from the function - I’ll need to move those to the 2nd argument array.

**Comment by bloatware** [comment]
@philwareham done, no worries. Please check if the default `gTxt('search')` value fits there.

**Comment by philwareham** [comment]
Thanks, amended sightly. Closing.

**Comment by philwareham** [comment]
@bloatware @Bloke not exactly related to this, but one thing I'm not sure about is info in this docs page: https://docs.textpattern.com/tags/search_input

Specifically, the use of `search_input` form. The docs state that by default the form named `search_input` is used by <txp:search_input />` tag if no other form is specified.

But in my tests that only happens if you have made a form called `search_input` *and* you haven't added any other attributes to the txp tag. If you don't have a form called `search_input` or you do, but have added attributes to the tag, then it actuality uses an in-built form in the PHP code.

That's correct yes? If so, I need to amend the docs to make this a bit clearer.

**Comment by bloatware** [comment]
Yes, `form` is ignored if other attributes are set, because there is no way to inject them into a custom markup. Before amending the docs, should we allow for container use of `search_input` too, for more flexibility? Something like
```
<txp:search_input>
    <input type="search" name="q" value='<txp:search_term />' />
    <!-- some custom markup -->
</txp:search_input>
```

**Comment by philwareham** [comment]
Yep, agreed. Although a container plus the attributes on the tag makes my head spin a little over all the different outcomes!

**Comment by bloatware** [comment]
No need to amend the docs re `form` attribute anymore, it will always be used if set.

New feature: `<txp:search_input />` can be used as container and also inside itself:
```
<txp:search_input>
    <!-- will output the search input field -->
    <txp:search_input placeholder="Title, Body" />
    <!-- add some custom markup -->
    <input type="submit" value="Go" />>
</txp:search_input>
```
