### ISSUE TITLE
Export to disk on the forms panels is misplaced

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1353]
Bug (4.7.2 / dev, since the additional custom forms grouping)

1. STR
* export a theme to disk
* Go to the forms panel (any form), an additional “Export to disk” checkbox + label appears _after_ the “Save” button.
* Press Save (or use the keyboard shortcut…). Notice that the above mentioned combo moves slightly (to allow space for the spinner) with Hive, or with Sandspace, the spinner overlaps the checkbox.

2. Issues:
* The spinner display when saving
* more important: the combo is out of the logical tab order.

3. Suggestions: 
* wrap the combo in a `<span />`, add a class to it (`.txp-forms-export` ? Whatever you feel fits).
* Move the combo _before_ the “Save” button. Leaving it inside the `.txp-save` `<p />` is fine as the action belongs to the Save step.
* Eventually, style the `<span />` as `display: block`, it visually appears on its own line.

**Comment by philwareham** [comment]
I’ll take this one - not seen this new UI yet so I’ll test and make necessary amends as suggested. Cheers.

**Comment by phiw13** [comment]
Thanks. Looks good.
