### ISSUE TITLE
Images Panel with the smd_thumbnail plugin - the list options button is inserted in plugins section element.

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1354]
TXP 4.7.1 + 4.7.2.dev

STR:

* Install and activate the smd_thumbnail plugin
* access the Images panel

Actual results:
* initially the list options button is not visible (the plugins sub panel is toggled closed).
* toggle open the thumbnails twisty sub panel, the button is now available at the bottom right of the panel.

It is not a style issue, the button is actually injected _inside_ the plugins `<section />` element.

Screenshot with the plugins panel open (the list options button should be _below_ the light grey box):

<img width="373" alt="txp-images" src="https://user-images.githubusercontent.com/8944809/47075064-adc16600-d236-11e8-9085-4157a25b96b2.png">

**Comment by Bloke** [comment]
Bug in the plugin's (re)use of the `txp-list-options` class. Will fix.
