### ISSUE TITLE
Category_list sort order by default is not name asc

### ISSUE THREAD

**Issue by dragondz** [textpattern/textpattern#1355]
### Expected behaviour

<category::list parent="cat1" exclude="cat1" break=""><txp:category /></category::list>

Result :

a_cat_id2
b_cat_id1

### Actual behaviour

I dont now how they are sorted by default!

b_cat_id1
a_cat_id2

### Steps to reproduce

create 2 categories b_cat_id1 and a_cat_id2 with same parent cat1 and test the code :
<category::list parent="cat1" exclude="cat1" break=""><txp:category /></category::list>

#### Additional information

Textpattern version: 4.7.1

**Comment by bloatware** [comment]
There is no order clause by default, which means some db-server dependent order. We could make it `name`, but this would not be fully bw-compatible. What's wrong with using `sort="name"` attribute?

**Comment by bloatware** [comment]
Yes, indeed, either the docs or the code should be corrected. I would say code in this case, sorting by name looks more common use than no sort at all. Will do if no objections are issued, thanks for the report.

**Comment by philwareham** [comment]
Fixed by https://github.com/textpattern/textpattern/commit/d93372a898315cb07eba84d77d26b3f9e02c32dc

**Comment by bloatware** [comment]
But still open, Github glitch?

**Comment by philwareham** [comment]
Yes, GitHub having major issues today. I'd hold back on committing much [until things are working 100% again](https://status.github.com/messages).
