### ISSUE TITLE
Inline txp:php in article body producing error when not at start of line.

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1357]
### Expected behaviour

Using `txp:php` inline in the article body should execute the contained php, providing php is allowed in articles and the correct user privileges exist.

### Actual behaviour

In the current 4.7.2 dev version, `txp:php` throws the following error when used inline, but _doesn't_ when used at the very beginning of the line.

The following error is produced:

```
 <pre dir="auto">Tag error: <b>&lt;txp:php&gt;echo date(‘Y’);&lt;/txp:php&gt;</b> -> <b> Warning: Use of undefined constant ‘Y’ - assumed '‘Y’' (this will throw an Error in a future version of PHP) while parsing form <strong>article_single</strong> on page <strong>default</strong></b></pre>
<pre class="backtrace" dir="ltr"><code>textpattern/publish/taghandlers.php:4388 eval()
php()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:543 Textpattern\Tag\Registry-&gt;process()
textpattern/lib/txplib_publish.php:467 processTags()
textpattern/publish/taghandlers.php:2951 parse()
body()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:543 Textpattern\Tag\Registry-&gt;process()
textpattern/lib/txplib_publish.php:467 processTags()</code></pre>‘2018’
```

### Steps to reproduce

Add the following to an article body:

```
<txp:php>echo date('Y');</txp:php> is the current year.

© 2013-<txp:php>echo date('Y');</txp:php> Joe Blogs
```

The first instance will show, the second throws an error.

#### Additional information

Textpattern version:4.7.2

The txp prefs `allow_article_php_scripting` and `allow_page_php_scripting` are both set to `1`.

Might this be related to commit 9f8054482e21098810cab3710fb5408f693f62be?

**Comment by bloatware** [comment]
Textile effect, perhaps?

**Comment by jools-r** [comment]
I guess so. I tried this:

```
© 2003- ==<txp:php>echo date('Y');</txp:php>== Joe Blogs
```

and it works but leaves a preceding space: `© 2003- 2018 Joe Blogs`. So your reasoning would seem to be correct. 

_However, I don't remember it being necessary before to surround `txp:php` tags with `==` notextile modifiers in the past._


With no space before: `© 2003-==<txp:php>echo date('Y');</txp:php>== Joe Blogs` it produces the tag error again. I guess that's to be expected as textile doesn't cut in. 

I also tried adding `[` and `]` chars as follows, which I thought was the way of isolating textile (… but maybe I've forgotten the correct syntax):

```
© 2003-[==<txp:php>echo date('Y');</txp:php>==] Joe Blogs
```

which gives me `© 2003-[2018] Joe Blogs`, i.e. it isolates textile but also includes the square brackets.

**Comment by bloatware** [comment]
> However, I don't remember it being necessary before to surround txp:php tags with == notextile modifiers in the past.

I remember it *very* well, be `<txp:php />` at the beginning of a line or inline. Some wtf hours spent on debugging as soon as your php block contains quotes. But never remember how you avoid extra spaces in Textile.

**Comment by jools-r** [comment]
So it's the quotes causing the error?

Thanks for jogging my memory and apologies for the false bug report.

**Comment by bloatware** [comment]
> So it's the quotes causing the error?

Looking at curly quotes in `undefined constant ‘Y’` warning, I'm pretty sure that yes. But I concur with you that escaping textile without prepending a (persistent) space to `==` should be easier. Something like this, perhaps:
```
© 2003-.==<txp:php>echo date('Y');</txp:php>== Joe Blogs
```
and then remove the dot in the result? I can't see any use for `.==` combination in a text.

**Comment by bloatware** [comment]
For the record, this works:
```
© 2003-<txp:php>==echo date('Y');==</txp:php> Joe Blogs
```

**Comment by jools-r** [comment]
So it does! I would never have guessed that. It just looks so wrong. Thanks for all the explanations.

I guess the reason it works when at the beginning of the line but not elsewhere is that lines beginning with a tag are now no longer textiled.

**Comment by bloatware** [comment]
Can be closed, I guess?
