### ISSUE TITLE
link_to_prev or link_to_next returned zero value

### ISSUE THREAD

**Issue by promantic** [textpattern/textpattern#1358]
### Expected behaviour
**link_to_prev or link_to_next returned zero value**
### Actual behaviour

**link_to_prev or link_to_next returned zero value**

### Steps to reproduce
Open old post in single page view (as artircle)
For example date of corrent (first) post is 2010-08-22 
The second post was published in 2010-08-29.

In paginator tab i see only inactive buttons "older" and "earlier"

I switched my blog to trace mode and I catch interesting (maybe bug):

```
<txp:variable name="prev" value='<txp:link_to_prev />' />
[attribute 'value']
[true]
<txp:link_to_prev />
[filterAtts ignored]

[SQL: SELECT *, UNIX_TIMESTAMP(Posted) AS uPosted, UNIX_TIMESTAMP(Expires) AS uExpires, 
UNIX_TIMESTAMP(LastMod) AS uLastMod FROM textpattern WHERE (Posted > 
FROM_UNIXTIME(1282451762) OR Posted = FROM_UNIXTIME(1282451762) AND ID > 283) 
AND 1 AND `Posted` <= from_unixtime(2147483647)

AND `Posted` LIKE '2010-08-22%'

AND (from_unixtime(2147483647) <= Expires OR Expires IS NULL) 
AND Section  IN ('articles') AND Status IN (4) 
ORDER BY Posted ASC , ID ASC LIMIT 1 ]

138.01 |          | 				[Rows: 0]
```

Its finds only posts of current posted date mask:  `AND Posted LIKE '2010-08-22%'`
If I use `AND Posted LIKE '%%'`  in PHPmyADMIN instead `AND Posted LIKE '2010-08-22%' ` it works properly.

But I don't know how to resolve it in textpattern code

Textpattern version: 4.7.1

**Comment by bloatware** [comment]
Would `<txp:article />` tag accessible on this page have its `month` attribute set to something like `<txp:posted />`?

**Comment by bloatware** [comment]
Well, it's rather bug than feature. It was not seen before 4.7 because `month` attribute was restricted to `past`, `future` or `any`, defaulting to `past`.

The fix needs some thinking/testing. Awaiting 4.7.2 you can try to add
```
 <txp:php>
    global $pretext;
    $pretext['month'] = '';
</txp:php> 
```
before `<txp:article />` tag in the **individual article** part of your page. Sorry for the inconvenience.

**Comment by promantic** [comment]
Dear Bloatware, thanks for your reply. I will test my blog with your recommendations. I hope all be fine. Looking forward the 4.7.2 TXP version.

**Comment by promantic** [comment]
> Well, it's rather bug than feature. It was not seen before 4.7 because `month` attribute was restricted to `past`, `future` or `any`, defaulting to `past`.
> 
> The fix needs some thinking/testing. Awaiting 4.7.2 you can try to add
> 
> ```
>  <txp:php>
>     global $pretext;
>     $pretext['month'] = '';
> </txp:php> 
> ```
> before `<txp:article />` tag in the **individual article** part of your page. Sorry for the inconvenience.

Dear Bloatware. It works fine. Thanks a lot!
