### ISSUE TITLE
RFC: consider inclusion of GNU Kind Communications Guidelines

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1359]
https://www.gnu.org/philosophy/kind-communication.html

I've read this a few times now, and I like it. The more I read it, the more I think on things and the more I like it.

There's crossover with the existing code of conduct, but the tone of the above is different overall.

Worthy of inclusions alongside the code of conduct, or as a successor to it?

**Comment by philwareham** [comment]
That's more a general _philosophy_ that a specific _code of conduct_ in my opinion. But I'm not against any of it - you are certainly welcome to make reference to it within the current code of conduct document if you wish to. It certainly follows what I hope are our principles.

**Comment by petecooper** [comment]
Good point, well made -- thanks @philwareham.
