### ISSUE TITLE
Textile out of sync with PHP-Textile

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1360]
Gocom has just released a new version of PHP-Textile ([v3.6.1](https://github.com/textile/php-textile/releases/tag/v3.6.1)) 😃 but we won't be able to update to this currently as there have been unique commits made to our copy of `Parser.php`. I suggest backing out our unique modifications and PR them to the official PHP-Textile repo instead for evaluation and inclusion?

**Comment by bloatware** [comment]
Jukka is not keen to include it in PHP-Textile for legacy reasons. Awaiting another solution...

**Comment by gocom** [comment]
As you are now up to date, you probably want to also update your use of PHP-Textile. Currently it calls and extends deprecated methods (and has as long as Textpattern started using 3.6.0). Realistically you probably want to extend Parser into two pre-configured classes; restricted and... unrestricted. Something along the lines of:

```php
namespace Textpattern\Textile;

class Parser extends \Netcarver\Textile\Parser
{
    public function __construct($doctype = null)
    {
        if ($doctype === null) {
            $doctype = get_pref('some', 'html5');
        }

        parent::__construct($doctype);
        $this->setImagePrefix(ihu)->setLinkPrefix(hu);
    }
}
```

And:

```php
namespace Textpattern\Textile;

class RestrictedParser extends Parser
{
    public function __construct($doctype = null)
    {
        parent::__construct($doctype);

        $this
            ->setRestricted(true)
            ->setLite(!get_pref('some', 1))
            ->setImages((bool) get_pref('some', 1));

        if (get_pref('some', 1)) {
            $this->setLinkRelationShip('nofollow');
        }
    }
}
```

Then:

```php
$parser = new \Textpattern\Textile\Parser();
$parser->parse('Hello World!');
```

And:

```php
$parser = new \Textpattern\Textile\RestrictedParser();
$parser->parse('Hello World!');
```

**Comment by bloatware** [comment]
@gocom many thanks, will do, unless you fancy submitting a patch.

**Comment by gocom** [comment]
Well, yeah; it would fail the matching since that is not valid HTML-syntax and it didn't actually even check for self-closing tags at all. I've updated the regular expression to be more liberal.

**Comment by philwareham** [comment]
Closing this issue as Textile is now in sync (albeit with a dev version, but will keep it updated as closely as possible until stable release). Thanks guys.
