### ISSUE TITLE
Infinite recursion with <txp:body /> within body

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1365]
### Expected behaviour

Warn and ignore.

### Actual behaviour

Fatal uncaught error: Maximum function nesting level of '256' reached, aborting!

### Steps to reproduce

Put `<txp:body />` tag inside an article's body.

#### Additional information

Textpattern version: all, presumably.

We limit recursive calls of `<txp:output_form />`, but not of other tags. Caveat utilitor?

**Comment by Bloke** [comment]
Caveat utilitor all round. If you put a body tag inside the body, surely you get what's coming to you! Same as if you put a custom_field tag to fetch contents of custom 1 inside custom1.

Imo, output_form is different because it's easy to tie yourself in knots without realising it, so the warning is justified.

**Comment by bloatware** [comment]
I thought of bodies like `<txp:article_custom />`, with `default` form containing `<txp:body />`, a trap I often get in. Yes, there seems to be 3 tags (body, excerpt and custom_field) to protect atm. A patch à la `$is_article_body` is easy, but

- it would break eventual fuzzy constructions with `<txp:body />` inside a custom field;
- if we add `parse` to `escape` values, other tags would need to be considered too.

I guess you are right, caveat utilitor.

**Comment by Bloke** [comment]
`article_custom` bodies inside Body text that uses the same Form is valid. Hadn't thought of that. I suppose defending against that is a nice-to-have.

I can't see a reason to include a body or excerpt tag inside a custom field. But using a custom field tag inside another custom field is valid to chain them together. Just pointing back to itself might cause issues but I'm not sure how to defend against that.

**Comment by bloatware** [comment]
Limit the total body/cf/excerpt recurrence depth per `ID`, perhaps, as we do for Forms? Something like 15 should suffice for average humans.

**Comment by bloatware** [comment]
Caveat utilitor re cf.
