### ISSUE TITLE
Caption field

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1366]
Current version 4.7.x-dev:

I seems that any ASCII or HTML symbols filled into the `Caption` field from the "Images" panel aren't interpreted and displayed as expected within the public front website.

**Comment by bloatware** [comment]
Hi Patrick,

I think that was always the case, you must set `escape=""` to disable special characters escaping.

**Comment by cara-tm** [comment]
Yes! Excellent Oleg. Please, close this issue.
