### ISSUE TITLE
wrong entry in table txp_lang for "salutation"

### ISSUE THREAD

**Issue by testdept** [textpattern/textpattern#1367]
### Expected behaviour

emails a new comment to the article's author...
body of mail should start with "Dear _author_"

### Actual behaviour

mail starts with "salutation: _author_"

#### Additional information

table txp_lang entry for name="salutation" has event "admin-side"
event should be "common"

#### note
Textpattern version: 4.7.1
en-gb, not tested for other langs

**Comment by Bloke** [comment]
Yep, should be in `[common]` oops.

**Comment by philwareham** [comment]
M’kay, will fix soon. Thanks!
