### ISSUE TITLE
Number of selected items in multi-edit

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1368]
With the advent of enhanced multi-upload and various other AJAxy features of our list panels in recent versions, the checkboxes sometimes persist to allow many multi-edit actions to be performed in sequence. This is a good thing. Sometimes, though, you don't notice the fact that stuff is or isn't already selected if it's scrolled out of view.

Is it possible / desirable to tweak the first entry in the multi-edit tool to indicate how many items the action will affect? Acts as a visual cue in case you don't expect that many.

It would require the following changes as far as I can tell:

* lang string `with_selected => With [num] selected` (note: it's in square brackets not curly braces because it's not a server-side injection - syntax to be defined).
* Tweak `textpattern.js` to inject the number of selected checkboxes into the placeholder in real time. Default is 0 on page load/if none are selected, of course.

It requires some way of storing the "unprocessed" gTxt()'d string in the `<select>` element (perhaps as a `data-` item?) so the number can always be replaced with the currently selected quantity of checkboxes and the string with the updated count can then immediately replace the first `<option>` value.

This should work in other languages, since the replacement placeholder is hard-coded in the string itself and is passed to the page as-is.

I must admit I'm not sure exactly _how_ to do it efficiently and cross-browser (given various browser intricacies surrounding select-option lists) but it seems doable to my not-very-JavasSripty brain and seems like a good addition on the surface.

Worth doing? Or not?

**Comment by gocom** [comment]
Well, you already have a full `gTxt()` implementation in JavaScript that you can use to build the string, rather than making up new syntaxes. As far as storing goes, that is also done by the existing implementation, and the counting can be done simply in the change event.

You probably could do it in one line, something along the lines of:

```javascript
form.editMethod.find('[value=""]').gTxt('with_selected_num', {
    count: boxes.filter(':checked').length
});
```

That would go into the change event that is attached to the form `lib.checked` whatever I named it back in the day.
