### ISSUE TITLE
Numerous dialogs when logging in, navigating and writing an article

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1369]
### Expected behaviour

Smooth sailing.

### Actual behaviour

Dialogs when logging in, navigating and writing a new article.

### Steps to reproduce

* install current `dev` build
* log in, note error dialogs
* navigate to Preferences, note error dialogs
* navigate to Write, note similar dialogs
* publish a new article, note error dialogs

#### Additional information

Textpattern version: current `dev` branch, auto installed via native auto installer.

**Logging in** (chronological order)

* `Notice "Undefined property: Textpattern\Textile\Parser::$rawContent".`
* `Warning "array_merge(): Argument #1 is not an array".`
* `Warning "implode(): Invalid arguments passed".`
* `Notice "Undefined property: Textpattern\Textile\RestrictedParser::$rawContent".`
* `Warning "array_merge(): Argument #1 is not an array".`
* `Warning "implode(): Invalid arguments passed".`
* `Notice "Undefined property: Textpattern\Textile\Parser::$rawContent".`
* `Warning "array_merge(): Argument #1 is not an array".`
* `Warning "implode(): Invalid arguments passed".`

**Publish article**
* `Notice "Undefined property: Textpattern\Textile\Parser::$rawContent".`
* `Warning "array_merge(): Argument #1 is not an array".`
* `Warning "implode(): Invalid arguments passed".`
* `Notice "Undefined property: Textpattern\Textile\RestrictedParser::$rawContent".`
* `Warning "array_merge(): Argument #1 is not an array".`
* `Warning "implode(): Invalid arguments passed".`
* `Notice "Undefined property: Textpattern\Textile\Parser::$rawContent".`
* `Warning "implode(): Invalid arguments passed".`
* `Notice "Undefined index: divider".`
* `Warning "preg_match(): Empty regular expression".`
* `Notice "Undefined index: contained".`
* `Warning "preg_match(): Empty regular expression".`
* `Notice "Undefined index: unwrappable".`
* `Warning "preg_match(): Empty regular expression".`
* `Notice "Undefined index: divider".`
* `Warning "preg_match(): Empty regular expression".`
* `Notice "Undefined index: wrapped".`
* `Warning "preg_match(): Empty regular expression".`
* `Notice "Undefined index: divider".`
* `Warning "preg_match(): Empty regular expression".`
* `Notice "Undefined index: contained".`
* `Warning "preg_match(): Empty regular expression".`
* `Notice "Undefined index: unwrappable".`
* `Warning "preg_match(): Empty regular expression".`
* `Notice "Undefined index: divider".`
* `Warning "preg_match(): Empty regular expression".`
* `Notice "Undefined index: wrapped".`
* `Warning "preg_match(): Empty regular expression".`

Screencast attached. Note: some mild flashing effects since I was spamming the mouse button to get through the messages.

[dialogs.zip](https://github.com/textpattern/textpattern/files/2631665/dialogs.zip)

**Comment by bloatware** [comment]
Thanks @petecooper, our Textile implementation was conflicting with the recent PHP-Textile changes.
