### ISSUE TITLE
MIME Type -> Media Type

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1370]
MIME Type is now be called Media Type.

https://en.wikipedia.org/wiki/Media_type

Not sure if we should amend our code accordingly where it is mentioned (specifically in the custom form types we expect `mimetype=""`) or just leave it as-is.

Opinions welcome, but we should be aware of this before 4.7.2 releases and locks us to the older naming convention.

**Comment by Bloke** [comment]
fwiw, I prefer `mediatype` as it's more descriptive. We can probably get away with keeping things like the `getMimeTypes()` function internally, but if we can change public facing stuff like you suggest in the pref settings then that'd probably be better.

**Comment by philwareham** [comment]
Agreed. Do you want to take this one?

**Comment by bloatware** [comment]
@philwareham please update pophelp files in their repo.

**Comment by philwareham** [comment]
Pophelps done - thanks!
