### ISSUE TITLE
Confirm compatibility with PHP 7.3

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1371]
PHP 7.3 is now available: http://news.php.net/php.announce/250

Confirm Textpattern plays nice with 7.3. I'll take this for now, I've almost figured out all the specifics for compiling from source for PHP-FPM, should have some feedback soon.

**Comment by petecooper** [comment]
Sanity check of deprecations probably a good idea, too: http://php.net/manual/en/migration73.deprecated.php

**Comment by petecooper** [comment]
I've worked out how to compile PHP 7.x from source, and I'm intending to switch the dev demo site to 7.3.0 tonight, then I'll put a call out for any testers to poke and prod for good measure.

**Comment by petecooper** [comment]
…and the dev demo is now running PHP 7.3.0:

```
Textpattern version: 4.7.2 (b436f2b6590bfa9dc5e2b2f4c8984e41)
Last update: 2018-12-11 18:46:32/2018-12-11 18:00:11
Site URL: dev-demo.textpattern.co
Admin URL: dev-demo.textpattern.co/textpattern
Document root: /var/www/vhosts/textpattern.co/dev-demo/live
$path_to_site: /var/www/vhosts/textpattern.co/dev-demo/live
Textpattern path: /var/www/vhosts/textpattern.co/dev-demo/live/textpattern
Article URL pattern: section_title
Production status: testing
Temporary directory path: /var/www/vhosts/textpattern.co/dev-demo/live/textpattern/tmp
PHP version: 7.3.0
GD Graphics Library: bundled (2.1.0 compatible); Supported formats: GIF, PNG.
Server timezone: Europe/Berlin
Server local time: 2018-12-11 20:06:20
Daylight Saving Time enabled?: 0
Automatically adjust Daylight Saving Time setting?: 0
Time zone (GMT offset in seconds):  (+0)
MySQL: 5.7.23-23 (Percona Server (GPL), Release '23', Revision '500fcf5') 
Database server time: 2018-12-11 19:06:20
Database server time offset: 1 s
Database server timezone: SYSTEM
Database session timezone: SYSTEM
Locale: C.UTF-8
Site / Admin language: en / en
Web server: nginx/1.15.6
PHP server API: fpm-fcgi
RFC 2616 headers: 0
Server OS: Linux 4.15.0-42-generic
Admin-side theme: hive 4.7.2
```

**Comment by Bloke** [comment]
> Sanity check of deprecations probably a good idea, too: http://php.net/manual/en/migration73.deprecated.php

Nothing in that list affects us. The only one I couldn't exhaustively check so far is the non-string needle search cases. But since PHP converts non-needle strings to ints anyway, I don't think it's something we'd have ever done in the codebase. At least, not consciously.

**Comment by bloatware** [comment]
The improvements in mbstring performance makes some tweaks useless, we will probably drop them in 4.8 (reminder for myself).

**Comment by petecooper** [comment]
Thanks @Bloke, thanks @bloatware – barring any snags found in the dev demo with 7.3.0, I'll close this in a few days. Do not consider this a blocker for 4.7.2 release.

**Comment by petecooper** [comment]
Gonna close this, can't break core Textpattern with PHP 7.3.0 - so provisionally OK.
