### ISSUE TITLE
CSS files deletion from the 'CSS' panel

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1372]
### Expected behaviour

Correct file deletion.

### Actual behaviour

I just noticed a strange behaviour (never noticed before) with the last dev version: I have three CSS files into the "CSS panel". Here is the file names (in this order):

`default`
`default_copy`
`default_uncompressed`

When I tick the red icon to remove the `default_copy` file, this is the `default_uncompressed` file (I just created) deletes. 

Is there an AJAX problem here with file names includ an undescore? 

Please: *to be comfirmed by devs*.

### Steps to reproduce

Create files with the same prefixes followed by an undescore: try to delete one (on a local MAMP server for PC).

#### Additional information

Textpattern version: latest 4.7-dev.

**Comment by bloatware** [comment]
Thanks Patrick, confirmed, the (weird) reason found. Will check it for Forms and Pages too before submitting a patch.

**Comment by cara-tm** [comment]
Thank you, Oleg ;)
