### ISSUE TITLE
Magnifying glass icon and probably link pointer error

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1375]
### Expected behaviour

Magnifying glass icons and right links pointer into the "Comments" panel.

### Actual behaviour

What is the purpose of the link into the magnifying glass on the right of each comments in the "Comments" panel? It points exactly on the event list not on the corresponding article (the supposed location)?

For the upcoming new 4.7.2 release, please Devs check it.

### Steps to reproduce

{Please write here}

#### Additional information

Textpattern version: 4.7-dev.

**Comment by Bloke** [comment]
The magnifying glass is a feature introduced in 4.7.0 to quickly filter all comments in the article. Instead of having to search/filter by hand, clicking that will _only_ show comments on the Comments panel associated with the article on which you clicked. If you want to then visit the article, click the parent link alongside it.

As far as I'm concerned this is expected behaviour. Granted the magnifying glass icon isn't ideal iconography...

**Comment by philwareham** [comment]
Please feel free to choose an different icon if there is one that is more semantic:

https://hive-framework.philwareham.co.uk/#ui-doc-jquery-ui--icons

**Comment by Bloke** [comment]
I couldn't find one at the time. And it does actually perform a 'search' function on the current panel so it's kinda valid. It's just perhaps not intuitive what it does, as @cara-tm found. No immediate suggestions for improvement from me though.

**Comment by cara-tm** [comment]
Sure @Bloke & @philwareham. My question is: are these links pointing on a proper event?

**Comment by Bloke** [comment]
For me:

* The magnifying glass links point to `event=discuss` and `step='discuss_list' (comments panel list) and therefore filter the comments to only those related to the article upon which the comment was made.
* The links to the right of the magnifying glass got to `event=article` and `step=edit` which take you to the Write panel to display the article itself upon which the comment was made.

Does your experience differ from this?

**Comment by cara-tm** [comment]
"*The magnifying glass links go to event=discuss and step=discuss_list (comments panel list) and therefore filter the comments to only those related to the article upon which the comment was made.*"

I'm sorry: tested only on comments attached to only one article...

Please: close this issue.
