### ISSUE TITLE
Date order into "Write" page

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#138]
_From [patrick....@gmail.com](https://code.google.com/u/111387824658555502103/) on February 10, 2012 20:29:38_

What steps will reproduce the problem? 1. That's not a real problem, just a feature request. What is the expected output? What do you see instead? Dates order into the fields shown in the "Write" page is currently set as YYY / MM / DD.

	I know it's an international format. But this is not natural for some final users and a subject of misunderstanding between days and months (simple clients without knowledges in UI software).

	TXP could offer a preference setting from the "Preferences" pane to choose an order display for dates. And the date fields into the "Write" page will be displaying accordingly.

	That could be a very great improvement for the next realize and a better friendly experience. What version of the product are you using? On what operating system? All versions since TXP exists ;) Please provide any additional information below. No needed additional infos.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=134_

**Comment by philwareham** [comment]
Use of placeholder text negates this issue somewhat. Closing.

If HTML5 date fields ever become stable, we can integrate.
