### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by colak** [textpattern/textpattern#1381]
### Expected behaviour

Non english languages should also be read:)

### Actual behaviour

https://forum.textpattern.io/viewtopic.php?id=49386

#### Additional information

A solution which eliminates the problem for the particular user was posted on https://forum.textpattern.io/viewtopic.php?pid=315881#p315881

Textpattern version: 4.7.2

**Comment by bloatware** [comment]
I don't think anyone still uses MySQL <4.1, so we could probably dump old versions check in `txplib_db.php` that do not work for some MariaDB setups?

**Comment by philwareham** [comment]
Yep agreed - get rid!

**Comment by bloatware** [comment]
Not sure that would help though - MariaDB 10.1.37 works fine for me, but 10.1.24 seems to go west. And nothing special in the [compatibility table](https://mariadb.com/kb/en/library/mariadb-vs-mysql-compatibility/)...

**Comment by petecooper** [comment]
Given that:

* MariaDB 10.1 is EOL as of October 2020
* MariaDB 10.2 is supported until May 2022
* MariaDB 10.2 was Stable as of May 2017 and GA as of 2018
* we don't currently _officially_ support MariaDB

We can provisionally update the sys reqs along the lines of:

> Textpattern is reported to work well with MariaDB 10.2 and newer, but is not officially supported.

…and invite keen forumites to report back with known-good (and even known-bad) MariaDB versions, perhaps to form the basis of a docs article for non-Oracle MySQL variants.

**Comment by Bloke** [comment]
That wording works for me.

**Comment by petecooper** [comment]
I've posted a thread about non-Oracle MySQL engines to scope stuff out: https://forum.textpattern.com/viewtopic.php?pid=323236#p323236

**Comment by philwareham** [comment]
Did we ever resolve this issue in a satisfactory way?

**Comment by Bloke** [comment]
Nope. We fixed a few bugs ages ago with version comparison which were affecting MariaDB but besides that, encoding issues tend to be utf8/utf8_mb issues or those with hosting setups where the collations don't match between DB/server/connection.

I doubt it's MariaDB specifically, more likely (mis)configuration. But I second the motion to dump the MySQL 4 @preg_match()@ stuff in txplib_db.php. We no longer support it, so let's axe it and close this.

**Comment by Bloke** [comment]
A tangential thought: what if we surround this block:

```
            if ($this->charset == 'utf8mb4') {
                $this->table_options['collate'] = "utf8mb4_unicode_ci";
            } elseif ($this->charset == 'utf8') {
                $this->table_options['collate'] = "utf8_general_ci";
            }
```
with a conditional check for something like `BYPASS_MYSQL_COLLATION` that people could set in their config.php to skip this setting? Since it worked for that forum guy, maybe making it possible to skip our enforced notion of `utf8mb4_unicode_ci` and `utf8_general_ci`.

Or, perhaps better, introduce an option in config.php to set the collation? Similar to `dbcharset` we could allow `dbcollation`. If it's in use, great, use it. If not, fall back on our defaults.

Thoughts?

**Comment by petecooper** [comment]
>Or, perhaps better, _introduce an option in config.php to set the collation?_ Similar to dbcharset we could allow dbcollation. If it's in use, great, use it. If not, fall back on our defaults as today.

Emphasis mine. This was done in 4.8.2 (see `HISTORY.txt`) – we can close this…so I will…please reopen if not addressed.
