### ISSUE TITLE
older newer

### ISSUE THREAD

**Issue by colak** [textpattern/textpattern#1382]
### Expected behaviour

When using the `older` and `newer` tags together with the `variable` or `evaluate` ones, there should be nothing parsed if there is no older or newer pages.

Sample codes can be found on
https://forum.textpattern.io/viewtopic.php?pid=315966#p315966 and the next post.

### Actual behaviour

The parsed code returns empty urls as reported by singaz found on 
https://forum.textpattern.io/viewtopic.php?pid=315965#p315965

### Steps to reproduce

In the head add

```
<txp:if_article_list>
<txp:variable name="prev" value='<txp:newer />' />
<txp:variable name="next" value='<txp:older />' />
<txp:if_variable name="prev" value="">
<txp:else />
<link rel="prev" href="<txp:variable name="next" />">
</txp:if_variable>
<txp:if_variable name="next" value="">
<txp:else />
<link rel="next" href="<txp:variable name="prev" />">
</txp:if_variable>
</txp:if_article_list>
```

or

```
<txp:if_article_list>
<txp:evaluate test="older, newer">
<link rel="prev" href="<txp:older />">
<link rel="next" href="<txp:newer />">
</txp:evaluate>
</txp:if_article_list>
```

#### Additional information

Textpattern version: 4.7.2

**Comment by philwareham** [comment]
Is this an issue that needs further attention, or can it be closed? Thanks.

**Comment by bloatware** [comment]
This is not specifically older/newer issue, just an effect of the linear nature of parsing. Can be closed in its present form, imo.
