### ISSUE TITLE
Delete 4.7.2 milestone

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1384]
4.7.2 is out - we can probably delete the milestone, right?

https://github.com/textpattern/textpattern/milestone/10

**Comment by Bloke** [comment]
Aye. Do we usually Close or Delete expired milestones? Does it matter? And if it matters, does it matter that it matters?

**Comment by philwareham** [comment]
Close not delete - thanks!

**Comment by petecooper** [comment]
Ah, didn't see Close - done!

**Comment by philwareham** [comment]
Just keeps a bit of historical reference around  - that's all.

**Comment by Bloke** [comment]
Noted, thanks.
