### ISSUE TITLE
TXP variables and post-dated articles

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1386]
Not really a bug. A behaviour notification for your interest.

### Expected behaviour

Correct parsing: It seems that Textpattern variables are not parsed when articles are set in the future.

### Actual behaviour

Variables are not correctly parsed.

### Steps to reproduce

Create a conditional variable (a simple switching state, in my case a mobile browser detection with the PHP Mobile_detect.php class) into an article form. Write an article and set it in the future, then preview it: the conditional variable is not checking and is displayed never mind the context.

#### Additional information

Textpattern version: 4.7.2

**Comment by bloatware** [comment]
@cara-tm I'm confused, what do you mean by "preview it": public-side view or admin preview? On the public side everything works fine for me. On the admin side, no form is used and no txp tag is parsed.

**Comment by cara-tm** [comment]
Yes: from the public-side view.
Here is a test with a post dated darticle (https://pat.re/blog/swimming-pool): when you click on the Share link, all icons are displayed; try another article from the Blog part, only 3 are shown.

**Comment by bloatware** [comment]
Yes, indeed. But I have just tried putting this into `default` article form on Pete's demo site:
```
<txp:variable name="test" value="" />
<txp:if_variable name="test" value>Something's wrong...<txp:else />Everything is fine!</txp:if_variable>
```
I get `Everything is fine!` for both past and future articles. Is your variables setup quite different?

**Comment by cara-tm** [comment]
From this page where all files in use are listed https://pat.re/package/ I invoque the Mobile_detect PHP Class (https://pat.re/themes/Simplr/Mobile_Detect.phps) to create a TXP variable, then I check `<txp:if_variable name="device" value="desktop"><txp:else />` into this file https://pat.re/themes/Simplr/forms/section/share.txp

**Comment by cara-tm** [comment]
Ok @bloatware. So if you are sure it works, you can close this report.
