### ISSUE TITLE
Export to disk cleared after save new

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1387]
### Expected behaviour

Export to disk remains checked after saving new asset.

### Actual behaviour

Export to disk checkbox is cleared on new Form creation, but remains checked any time after that (on Ajax saves) for the current item.

### Steps to reproduce

1. Create new Form - any type.
2. Give it a suitable name that can be exported.
3. Check the Export to disk box.
4. Save.

### Additional info

Not sure if it's necessarily a bug or by design. The export checkbox is cleared when switching Forms (which is correct) so I suppose this is an extension of that, since creating a new Form does a full page refresh. Do we leave it as it is?

Textpattern version: 4.7.3-dev

**Comment by cara-tm** [comment]
Exact.

**Comment by bloatware** [comment]
This should be patched (Pages and Styles too), for consistency. But dunno where, since 4.7.3 is conflicting with dev...

**Comment by philwareham** [comment]
Please do it in dev and then I'll `git cherry-pick` the commit into 4.7.3 branch.
