### ISSUE TITLE
Admin-theme specific preferences

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1389]
### What is the feature?

For the admin themes in 4.8, I have a Dark Mode version of Hive upcoming (see screenshots). However to implement this in a user-friendly way I'd like to give users the option of enforcing Dark Mode (regardless of their OS setting), enforcing Light Mode (regardless of their OS setting), or adhering to their OS setting. The 3rd option also allows the theme to switch at day and night if the user has that feature in the OS or via third party OS app (this is achieved via the `prefers-color-scheme:` CSS rule in supported browsers).

You can see a similar UI handling in latest GitHub Desktop app on macOS Mojave (in preferences -> appearance).

The best way to achieve this is with a Textpattern preference I think, but that preference is specifically for this one theme (I don't intend to do a Dark Mode version of Classic). Unless people have other ideas of how to achieve it.

That would also give us the option of turning on/off the autosizing text areas which some users find annoying (but other users like).

Any thoughts welcome.

![screenshot1](https://user-images.githubusercontent.com/413665/52861583-d39a4100-312a-11e9-852d-a4630fbb8d3e.png)
![screenshot2](https://user-images.githubusercontent.com/413665/52861586-d5fc9b00-312a-11e9-9098-73559d91c5f7.png)

**Comment by bloatware** [comment]
Nice work! Theme preferences are a great idea, but they should be registered by themes themselves, not frozen in core. We'd need to provide an easy way to do it for theme authors, though.

**Comment by philwareham** [comment]
Agreed - I basically need some way of an admin theme having preferences that are stored in the database alongside standard core preferences.

**Comment by Bloke** [comment]
We could introduce a new pref type to complement `PREF_CORE` and `PREF_GLOBAL` and `PREF_PLUGIN` etc. How about `PREF_THEME`? that would help us distinguish them and the `owner` could be the theme name.

**Comment by philwareham** [comment]
The manifest seems like the most logical place to store initial pref values.

**Comment by bloatware** [comment]
Yep, some simple prefs format with install/delete on theme import/delete looks fine.

**Comment by philwareham** [comment]
There is also translations of the pref text and pop help to consider. I could just roll those into core but it seems better to allow third-party admin theme authors to come up with their own prefs if they want. Hmmm.

**Comment by Bloke** [comment]
Yep, makes sense to me too. A nice JSON structure to help delineate things:

```
{
  "title": "Hive (Flat Neutral)",
  "txp-type": "textpattern-admin-theme",
  "version": "4.7.3",
  "description": "Textpattern CMS Hive admin theme (Flat Neutral).",
  "author": "Phil Wareham",
  "author_uri": "https://github.com/philwareham/textpattern-hive-admin-theme"
  "prefs": [{
       "name": "auto_dark_mode",
       "val": "0",
       "html": "yesnoradio",
       ...
   }]
}
```
The only thing about import/delete is that we don't actually have an official install mechanism for themes (outside of smd_admin_themes, which needs updating for 4.7. anyway I think). You just drop the theme in the `admin-themes`folder and it's immediately available if it confirms to the base class structure. So we need some auto-hook that is run every time the theme is accessed, but isn't intrusive - i.e. if it's already been done and the version hasn't changed, skip install. Should we write the version number in the DB on first access so we can compare in future?

And yes we need some well-known translation ini file, like we did with `mode.ini`, that can be included in the theme package and is also picked up during "install" (first use) or on version change.

Doing this "has the version changed" thing gives a nice-ish mechanism for forcing a reload of the theme install process by just winding back the installed theme version number in prefs, like we do to force regular Txp updates. Sure, it's not immediate and user friendly, but the ability is there if anyone needs it.

**Comment by bloatware** [comment]
> You just drop the theme in the `admin-themes`folder and it's immediately available if it confirms to the base class structure.

Don't you need to import it into db?

**Comment by Bloke** [comment]
> Don't you need to import it into db?

Nope, just drop a valid theme structure with manifest into the `admin-themes` directory and it pops up in the Prefs->Admin panel selector for you to choose from.

**Comment by bloatware** [comment]
Ah, right, I confound with the public side. Well, it seems to require some work. On the other hand, custom fields could yield some changes in this area too.

**Comment by Bloke** [comment]
> Well, it seems to require some work.

Yeah, maybe. Depends how far we want to go. A simple routine on the `init()` method could check if the version in the manifest matches/is less than the one in the DB. If not, or it's missing (i.e. first install or update by author) it checks the manifest for any prefs and installs them and checks the theme folder for any language ini file and installs those. Bonus marks if we build in a system to remove obsolete prefs/lang strings in the process. Then it writes the theme version to the DB in a pref. Job done.

> On the other hand, custom fields could yield some changes in this area too.

Tell me more... would love to factor this in somehow.

**Comment by philwareham** [comment]
I don't need this feature for dark/light mode in themes now as I have a JavaScript solution that works per device (which is better). I'm going to close the issue as it was specifically for dark/light mode - if anyone feels theme prefs would be useful for other uses then feel free to reopen.
