### ISSUE TITLE
Remove 'Prevent widowed words in article titles?' pref

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1390]
The 'Prevent widowed words in article titles?' is a relic from a bygone era. It is not pertinent in an age of responsive web design and the phrasing makes it sound like something that is good to enable - when it isn't.

You can use CSS level 2 `widows` rule is *most* browsers (all but Firefox it seems) to achieve this better if desired.

I'd prefer to remove it from visibility in 4.8, and leave it as a hidden pref for backwards compatibility if needs be.

**Comment by Bloke** [comment]
I've always disliked that preference, especially its name.

**Comment by philwareham** [comment]
Cool. Do you ant to remove? :)

**Comment by phiw13** [comment]
the CSS 2/4 “widows” (and orphans) property does **not** apply at the _inline_ level (which is what the TXP pref does - append a non-breaking space between the 2 last **words**.

ref: https://drafts.csswg.org/css-break-4/#propdef-widows

**Comment by Bloke** [comment]
I doubt many would cry if it disappeared. What's the worst that can happen: you get one word on a line instead of two. Having a non-breaking space on a responsive site could make both words fall off the edge of the page anyway at small device sizes, so it's a service to axe the pref, imo. But I'm not a typographer so I'll leave the decision on keeping it around to those that are.

**Comment by philwareham** [comment]
> the CSS 2/4 “widows” (and orphans) property does **not** apply at the _inline_ level (which is what the TXP pref does - append a non-breaking space between the 2 last **words**).

Isn't a title going to be (mostly) used in a block-level element though? Such as a heading tag or paragraph tag?

Regardless, it's still obsolete.

**Comment by phiw13** [comment]
I’ve no real objections to remove the pref. In some language is is non-sensical(CJK), in  other languages it could wreak havoc on narrower screens (two long German words…, it is a language that has many long words).

**Comment by phiw13** [comment]
> Isn't a title going to be (mostly) used in a block-level element though? Such as a heading tag or paragraph tag?

the CSS property will force 1,2,3 more **lines** in a paragraph to be kept together, before it breaks to the next page (or column). InDesign has something similar

**Comment by philwareham** [comment]
It seems there are inconsistencies in widows and orphans meaning. When I studied typography at university (UK) a widow was a single word on it's own at the end of a paragraph. Others call this an orphan but the essence is the same.

The initial point of removing the pref still stands though. You can achieve this in CSS if really needed and the problems of the pref outweigh the questionable benefit.

**Comment by bloatware** [comment]
Amazingly, this morning I got a request re applying txp `noWidow()` functionality to `<h* />` tags. I'm not a typographer, but it seems that it's still in use. And CSS rules concern not words but lines, as @phiw13 says.

We could add `nowidow` to global `escape` values, or allow for registering custom `escape`, dunno.

**Comment by bloatware** [comment]
The pref is actually used just as default value of `<txp:title />` `no_widow` attribute, so we can remove it without entirely disabling the feature itself.

**Comment by philwareham** [comment]
> The pref is actually used just as default value of `<txp:title />` `no_widow` attribute, so we can remove it without entirely disabling the feature itself.

Yes please!

**Comment by bloatware** [comment]
@philwareham Done, please remove text/help strings and merge where necessary.
