### ISSUE TITLE
timestamps into txp_prefs field

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1392]
Looking into the `txp_prefs` table in order to get the timestamp of the initial textpattern installation, I noticed this:

Three fields use a (far away) future date (Tuesday 19 January 2038 03:14:07):

`sql_now_posted     2147483647`
`sql_now_expires     2147483647`
`sql_now_created    2147483647`

On the other hand this entry is correct (Thursday 20 December 2018 17:06:07):

`dbupdatetime      1545325567`

Is there a kind of mismatch here?

(See: https://github.com/textpattern/textpattern/issues/775)

**Comment by Bloke** [comment]
That value is the max int that PHP can store, which results in the greatest timestamp that 32-bit *nix systems can handle. Not sure why those values are wrong. They should be the time that Txp was installed. Is your system time correct?

**Comment by cara-tm** [comment]
Yes it is.

**Comment by bloatware** [comment]
AFAIR, these values are used as upper bounds in sql queries instead of `NOW()` in e.g.
```
Posted < NOW()
```
They are normally equal to the nearest future article/file timestamp, but if you have no future articles, the maximal integer value is used. So all is good :-)

**Comment by cara-tm** [comment]
Ok. Thanks.

**Comment by bloatware** [comment]
See [here](https://github.com/textpattern/textpattern/pull/526) for the background/history of these prefs.
