### ISSUE TITLE
Possible upgrade bug: stale Textpack (.txt) files

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1393]
### Expected behaviour

New string files are used in favour of old string files.

### Actual behaviour

If an old `.txt` language file remains in the `textpattern/lang` directory, it is used when installing a language, which leads to untranslated strings.

### Steps to reproduce

1. Install an older version of Txp (e.g. 4.6.2) that has en-gb as its site language.
2. Upgrade to Txp 4.7.3 but leave the old `textpattern/lang/en-gb.txt` file in place.
3. Navigate around the admin side. Notice untranslated strings dotted about.

This appears to be due to one or all of the following:

a) The `vendors/Textpattern/L10n/Lang.php->findFilename()` that only checks the _filename_ of the files in the `lang` directory for a match, not its extension too.

b) The order of the default file extensions in the  `vendors/Textpattern/L10n/Lang.php->files()` method. Using `$extensions = array('ini', 'textpack', 'txt'))` might be better, but the old text file still seems to be checked first for the metadata, which renders the language name incorrectly (as just the filename) in the Languages panel.

To verify:

1. Rename the old `en-gb.txt` file as `en.txt`.
2. Install at least one additional language that is _not_ en.
3. Select the secondary language as both site default and admin-language.
4. Delete 'en' language from the Languages panel if it's installed.

Observe: the name of the language in the 'en' cell is just 'en', not 'English' meaning it has not picked up the metadata correctly from the top of the `en.ini` file.

EDIT: If the `.txt` file is the first extension in the `files()` parameter then stale strings are installed from it. If the `.ini` file extension appears first in the list, the later `.txt` entry in the `files()` array overwrites the metadata read from the earlier `.ini` file.

**Comment by Bloke** [comment]
Think that fixes things. Please test rigorously to check nothing breaks either during upgrade, installation or when installing/uninstalling languages. Thanks!

**Comment by petecooper** [comment]
Do we need a 4.7.3 beta for more eyeballs, @Bloke ?

**Comment by Bloke** [comment]
I don't think it's warranted given the small feature set and fix list. I'm happy enough it works, but if anyone else wants to give it a few upgrade/install cycles today, and also check that `<txp:output_form />` and `<txp:yield>` still behave as expected now they have slightly enhanced superpowers, that'd be awesome.

All things being equal, I can pull the trigger tonight.

**Comment by philwareham** [comment]
I'm happy to release - if you can put together a release tonight Stef that would be awesome! I'm around tomorrow if any ends need tying.

**Comment by petecooper** [comment]
+1 from me, I'll be around tonight as well.
