### ISSUE TITLE
Reduce footprint of date/time group panel

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1395]
We can save a good amount of vertical screen estate but allowing the date and time fields to inline-block when space allows. See screen grabs. All achievable with CSS - no core changes.

Before:
![Screenshot](https://user-images.githubusercontent.com/413665/54271750-0abd1000-457a-11e9-89ce-a344c3d6fb5a.png)

After:
![Screenshot 1](https://user-images.githubusercontent.com/413665/54271752-0abd1000-457a-11e9-8bd6-d6c5f27b411d.png)

**Comment by Bloke** [comment]
Me likeeee.

**Comment by bloatware** [comment]
+1

**Comment by cara-tm** [comment]
+2 :D
