### ISSUE TITLE
No JSON escape for the author tag

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1396]
### Expected behaviour

Allowing the use of `escape="json"` within the `<txp:author />` tag.

### Actual behaviour

It seems that the `<txp:author />` tag do not allow escape attribute with json value.

### Steps to reproduce

Try this sample:

`<txp:author format="url" escape="json" section="my-page" title="1" />`

#### Additional information

Textpattern version: 4.8-dev (latest).

**Comment by bloatware** [comment]
That's "normal", as for a dozen of other tags that already had `escape` attribute before. They treat it internally, the global one is not applied. We can fix it case-by-case for core tags, but not in plugins.

**Comment by cara-tm** [comment]
I'm using it to generate a JSON-Feed with only TXP tags, no plugin (see the result here: https://pat.re/rss-feed and the markup here: https://pat.re/themes/Simplr/pages/rss-feed.txp)

**Comment by cara-tm** [comment]
Oh! Yes, that's work. Thanks lot @bloatware ;)

**Comment by bloatware** [comment]
Fine. It looks like `"` quote is missing after `"url" : `.

**Comment by cara-tm** [comment]
Corrected. Tks.

Can be closed, now.
