### ISSUE TITLE
Theme files served as text/plain

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1397]
### Is your feature request related to a problem?

Not a problem: more than a suggestion.

### What is the feature?

All theme files are written as UTF-8 characters from the administration interface.

Displaying these files from a browser (i.e. as contents to download) from direct links to the `theme` directory are all encoded into `text/plain`. This situation can be annoying if the corresponding files contain some ASCII signs (or some HTML entities): they are not well displayed.

I tried to editing the `.htaccess` file from the `root\theme` folder but without any better results:

    # Serve theme files as UTF-8
    AddType 'text/plain; charset=UTF-8' txp

Devs: do you think if a solution can be found?

**Comment by bloatware** [comment]
IIRC, our current rules simply forbid serving `txp` files directly, since they can contain sensible site information.

**Comment by Bloke** [comment]
I don't think we're going to expose template files to casual observers so I'm closing this.
