### ISSUE TITLE
Handling passwords in 4.8+

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1402]
I've been looking at some developments in SQL password handling, and it might be time to look at the way Textpattern handles its passwords.

This came about because of upgrades I was making to the demo sites. I've been using a MySQL 5.7 drop-in replacement for years, and it's worked fine. I upgraded to a MySQL 8.0 replacement and failed at the point where I import users to the freshly-created Textpattern instance.

To be clear: Textpattern appears to install as expected to MySQL 8.0, it's the ancillary stuff I bludgeon in with an additional SQL import that breaks it.

After some email and forum [to](https://forum.textpattern.io/viewtopic.php?pid=317524#p317524)-and-[fro](https://forum.textpattern.io/viewtopic.php?pid=317526#p317526) (thank you very much @Bloke), I have a few routes to investigate. One of these routes is to use the existing `phpass` library. According to the `phpass` [website](https://www.openwall.com/phpass/), there are some alternatives that might be more appropriate:

>(I)f your new project can afford to require PHP 5.5+, which it should, please use PHP's native password_hash() / password_verify() API instead of phpass.

Which brings PHP 5.5 into play. Textpattern 4.7 requires PHP 5.4, and as I understand it we're shooting for Textpattern 4.8 to require PHP 5.5, so is this an appropriate time to look at password handling going forward, with a caveat that very old version upgrades might need an extra step which covers the pre- and post-`phpass` marker (Textpattern 4.4, I think).

**Comment by Bloke** [comment]
If it's possible to migrate wholesale to native PHP password handling and stretching in a backward compatible manner (as far back as 4.3 at least) then I'm all for it. One less third party dependency.

**Comment by bloatware** [comment]
There seems to be no straightforward way to `password_verify` hashes generated by PHPass. So we'd need to keep (parts of) this library for few years to ensure bwc. Nuts.

**Comment by petecooper** [comment]
I'm inclined to close this, given its perhaps edge case-y nature and no straightforward way to resolve. Is there a way to reset a forgotten password directly in the database for MySQL 8.0? I know of a few routes with 5.x, but I've not used 8.0 sufficiently to understand its differences in real world use.

**Comment by bloatware** [comment]
It's fine to start migration as soon as we switch to PHP 5.5 imo, I'm just saying that we can not get rid of phpass immediately. We'd need to wait until all existing txp users switch to txp 4.8+ and log into txp to trigger the hash migration.

`PASSWORD()` function has been removed in MySQL 8, so PHP currently seems to be the only way.

**Comment by bloatware** [comment]
Fwiw, `CONCAT('*', SHA1(UNHEX(SHA1('my password'))))` can replace `PASSWORD('my password')` in MySQL 8.

**Comment by Bloke** [comment]
Don't mind if we do it that way or the way you've implemented in 78d00419. Whichever is more efficient, I guess.

**Comment by petecooper** [comment]
I'm not at a test bench right now, but would `CONCAT('*', SHA1(UNHEX(SHA1('my password'))))` be backwards compatible with MySQL 5? Bearing in mind minimum is waaaaaay back at 5.0.3 (2005-era).

**Comment by Bloke** [comment]
Good point. Dunno. I'm fine with the way it's handled now in dev but you're right we need to test it with some suitable minimum MySQL version after having set up an initial test environment on some _reeeal_ old MySQL with an ancient password stored in the DB, to simulate an upgrade from, say, 4.0.4 or something.

Anyone have any reliable stats on what MySQL versions are installed on the majority of hosts these days so we can pitch the next Textpattern version in the same ballpark?

**Comment by petecooper** [comment]
>Anyone have any reliable stats on what MySQL versions are installed on the majority of hosts these days so we can pitch the next Textpattern version in the same ballpark?

I have no reliable stats to hand, but on the grounds that 8.0 is newest, 5.7 and 5.6 are actively supported and 5.5 support ended last year, it's likely a safe bet that most hosts will be in the 5.6 and 5.7 bracket, with 5.5 at the left of the bell curve, and 8.0 at the right.

**Comment by bloatware** [comment]
I meant [this](https://github.com/textpattern/textpattern/issues/1402#issuecomment-538564238) as a solution to

> Is there a way to reset a forgotten password directly in the database for MySQL 8.0?

The way it is handled in dev now should be fine for MySQL 4.1+, I don't think `PASSWORD()` implementation has changed since.

**Comment by Bloke** [comment]
Ah right, yeah. You know what, we should update the documentation now for the FAQ 'how to reset a forgotten password'. I'll dig it out and update it. Good catch.

**Comment by Bloke** [comment]
[Okay, done](https://docs.textpattern.com/faqs/resetting_admin_password).

**Comment by bloatware** [comment]
Hmm, I'm not sure about `LOWER` in `set pass=PASSWORD(LOWER('my_pass'))`. Isn't it making uppercase characters unusable in passwords? We don't `strtolower('my_pass')` before hashing it, and PHP `strtolower` is not necessary equivalent to MySQL `LOWER` anyway.

**Comment by Bloke** [comment]
We've always stipulated that we use `lower()` but I presume that was just for ease. I guess it makes sense to remove that now. Good spot.

**Comment by petecooper** [comment]
>[…] would CONCAT('*', SHA1(UNHEX(SHA1('my password')))) be backwards compatible with MySQL 5?

Tested with 5.7, works perfectly. MySQL 8 on the demo sites is now a _lot_ more achievable on my pay grade.

**Comment by bloatware** [comment]
I hope it's not related, but currently the dev-demo throws a 504 time-out...

**Comment by petecooper** [comment]
>504 time-out

That was me overhauling the build scripts - I've tweaked a few things, should be fine now.

**Comment by Bloke** [comment]
Updated the FAQ to only use the sole SQL reset procedure irrespective of version. https://docs.textpattern.com/faqs/resetting-admin-password.

Closing.
