### ISSUE TITLE
Flat File call and local server

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1403]
I don't know if it is a bug, so I refer this here to Devs (please try, confirmation needed):

It seems that the new (excellent) feature with Flat Files calls do not work on local servers (js script or CSS).

Textpattern version: 4.7.3 with MAMP PC.

**Comment by bloatware** [comment]
I have no MAMP to test, but `<txp:css format="flat.link" />` works fine on XAMPP PC for me. Mind providing more details, Patrick?

**Comment by cara-tm** [comment]
All works fine with css (sorry): the problem occurs with js...

**Comment by bloatware** [comment]
No problem with js neither... Are you sure to have exported the form to disc (and also use the right theme)?

That's what works for me on XAMPP:

- Form `alert` of `application/javascript` mediatype: `alert("hello")`
- Form inclusion: `<txp::alert format="flat.script" />`

**Comment by cara-tm** [comment]
Thanks, Oleg.

So, I can't (and I don't know how) use the flat feature with js (and I think I'm not the only one)... The query into the generated link points to a domain.tdl/?file and a blank page (no reference to the current theme neither). May be the official documentation need some amendments and more examples to show us how to correctly implement such things.

**Comment by bloatware** [comment]
Sorry, my bad. The form name should have `.js` extension and called as
```
<txp:output_form form="alert.js" format="flat.script" />
```

**Comment by cara-tm** [comment]
Nope...

I've got this URL: https://domain.tdl/?f=test.js that points to a blank page.

I exported to the disk server the form `test.js` and my custom modules config into the "Advanced Settings" panel are:

    ;[js]
    ;mediatype="application/javascript"
    ;title="JavaScript"
    ;[css]
    ;mediatype="text/css"
    ;title="CSS" 


Other thing to notice to you:

I tried to create some `rel="next"` and `rel="prev"` mechanisms for my pages. The only model I found that works as expected is like below (a pretty complex one...):

    <txp:variable name="page" value='<txp:page_url type="pg" />' />
    <txp:variable name="prev" value='<txp:newer />' />
    <txp:variable name="next" value='<txp:older />' />
    
    <txp:if_variable name="page" value="1">
	<link rel="next" href="<txp:variable name="next" />">
    <txp:else />
	<txp:if_section name="default">
		<txp:if_variable name="next" value="">
		<txp:else />
			<link rel="next" href="<txp:variable name="next" />">
		</txp:if_variable>
		<txp:if_variable name="prev" value="">
		<txp:else />
			<link rel="prev" href="<txp:variable name="prev" />">
    	</txp:if_variable>
    <txp:else />
    	<txp:if_variable name="next" value="">
		<txp:else />
			<link rel="next" href="<txp:variable name="next" />">
		</txp:if_variable>
		<txp:if_variable name="prev" value="">
		<txp:else />
			<link rel="prev" href="<txp:variable name="prev" />">
    	</txp:if_variable>
	</txp:if_section>
    </txp:if_variable>

...But all occurencies (TXP variables or URL links) fail for the "`next`" pages (but not the "`prev`" ones; notice: the conditional variable fails on a `<txp:older />` tag despite it is empty)!

**Comment by bloatware** [comment]
Ah, but your mediatypes are commented out, I don't even see how you could assign a form `Javascript` type. Just remove `;`
```
[js]
mediatype="application/javascript"
title="JavaScript"
```
You don't need to do it for CSS if styles are served from `Styles` tab, as usual.

Sorry, the doc is missing, but `Custom form template types` pophelp contains a basic info for starters.

**Comment by bloatware** [comment]
You could try something like this
```
<txp:older wraptag='<link rel="next" href="<+>">' />
<txp:newer wraptag='<link rel="prev" href="<+>">' />
```

**Comment by cara-tm** [comment]
Oh! You're a master (for the second part, only)! Thank you lot ;)

So, I'm using this instead (simplier):

    <txp:if_variable name="page" value="1">
	<txp:older wraptag='<link rel="next" href="<+>">' />
    <txp:else />
	<txp:if_section name="default">
		<txp:older wraptag='<link rel="next" href="<+>">' />
		<txp:newer wraptag='<link rel="prev" href="<+>">' />
	<txp:else />
    		<txp:older wraptag='<link rel="next" href="<+>">' />
		<txp:newer wraptag='<link rel="prev" href="<+>">' />
	</txp:if_section>
    </txp:if_variable>

    <txp:if_individual_article>
	<txp:link_to_next wraptag='<link rel="next" href="<+>">' />
	<txp:link_to_prev wraptag='<link rel="prev" href="<+>">' />
    </txp:if_individual_article>

Unfortunatly, removing the comments for the media type (my bad, sorry) don't do the trick and I got a blank page for the ressource's link generated...

**Comment by bloatware** [comment]
> Unfortunatly, removing the comments for the media type (my bad, sorry) don't do the trick and I got a blank page for the ressource's link generated...

Try to resave the form now that `.js` mediatype is enabled.

**Comment by cara-tm** [comment]
Oh! My bad, Oleg !!!!

I don't see the new type of media into the dropdown list (I'm so strupid...)

Ok. You can close this (kind of) issue now (but consider to update the doc).

Many thanks again, Oleg.

**Comment by bloatware** [comment]
I actually can not see why you wouldn't put just
```
<txp:if_individual_article>
	<txp:link_to_next wraptag='<link rel="next" href="<+>">' />
	<txp:link_to_prev wraptag='<link rel="prev" href="<+>">' />
<txp:else />
	<txp:older wraptag='<link rel="next" href="<+>">' />
	<txp:newer wraptag='<link rel="prev" href="<+>">' />
</txp:if_individual_article>
```
Closing the issue here, will add few examples to the doc.
