### ISSUE TITLE
Replace our file uploader with Uppy

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1404]
### Is your feature request related to a problem?

Nope.

### What is the feature?

Investigate whether Uppy is appropriate to replace our current file uploader.

[1] https://uppy.io/blog/2019/04/1.0/
[2] https://github.com/transloadit/uppy
[3] https://github.com/transloadit/uppy/blob/master/LICENSE

**Comment by philwareham** [comment]
Yeah, I've been keeping my eye on that product for a while now. And doesn't require jQuery which is good for us going forward (I'd like to reduce jQuery reliance over time).

**Comment by Bloke** [comment]
I like the sound of that. Good ethos, good feature set without trying to cram too much in. I think it's a good fit.

**Comment by cara-tm** [comment]
Check out this one too (seems to be lighter): https://github.com/pqina/filepond

**Comment by bloatware** [comment]
The main reason for using a third-party file uploader was a demand to bypass the server max upload size limitations. This is usually done via chunked uploads, so any challenger should be able to manage it. From a quick look it seems that Uppy can do it, but Filepond can not atm (planned). Just my 2 kopecks.

**Comment by petecooper** [comment]
Ooh, Uppy has a (beta) image editor: https://uppy.io/docs/image-editor/

**Comment by philwareham** [comment]
> Ooh, Uppy has a (beta) image editor: https://uppy.io/docs/image-editor/

Nice, but I'd prefer to lean on server-side image manipulation rather than edit images at upload stage - it's just more flexible and (potentially) non-destructive. I still think Uppy can be a contender for initial file uploading though.

**Comment by bloatware** [comment]
> 

Uppy uses its own non-standard protocol for chunked files upload, which makes me think twice.

**Comment by petecooper** [comment]
Deferring to @bloatware's domain expertise; closing.

**Comment by bloatware** [comment]
It would also add 7Mb of php/js to txp, are we ready?
