### ISSUE TITLE
Advanced pref options for global variables (or another method)?

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1405]
### Is your feature request related to a problem?

Nope.

### What is the feature?

Sometimes I want to store site-wide variables (such as an API key). At the moment I'm creating a variables article and storing the items there (as I don't want to publicise the key or commit it to GitHub within source code). Could there be a field in the advanced pref options where we could house these or am I missing an easy place to store them already (maybe the config.php file)?

**Comment by philwareham** [comment]
Bump! @bloke @bloatware can txp:variables be store in config.php file already? If so, can you let me know how? Cheers!

**Comment by Bloke** [comment]
I've never tried storing them in `config.php` Might work if you do this:

```
global $variable;
$variable['api_key'] = "1234567890abcdef";
```

Failing that, I tend to just stash them all in a Form and include it in my 'head' with `<txp:output_form>`. Also means no Textile stuff to worry about.

**Comment by philwareham** [comment]
Thanks, I'll give that a try when I next work on the particular project.

Storing variables in a form is not going to cut it, as the files will be committed to a GitHub repo and the API key would then be publicly exposed (and subsequently revoked by issuer).

**Comment by Bloke** [comment]
Gotcha. I can't see a reason why the `config.php` approach won't work. It's included by core and `$variable` is used globally inside Txp, so as long as you expose it before you use it, everything should work out.

**Comment by philwareham** [comment]
OK, thanks Stef. Would I need to put the line `global $variable;` into the config.php file too?

**Comment by Bloke** [comment]
Yes, I would expect so. That exposes anything you put inside it to the global scope. Since we use it already in the global scope within core, it may not be necessary, but it won't hurt to include it.

**Comment by philwareham** [comment]
I've tested this theory on the Textpattern.com website and it works (now fetching the GitHub star count via latest API using a token key).

FYI `global $variable;` isn't essential in the `config.php` file.

Closing this issue since this method is fairly easy to do.

**Comment by bloatware** [comment]
You could also put these (and other) definitions in some `.php` file and add
```
$txpcfg['pre_publish_script'] = 'path/to/file';
```
to `config.php` to keep it cleaner.

**Comment by philwareham** [comment]
Thanks both - handy tips!

**Comment by cara-tm** [comment]
`$txpcfg['pre_publish_script'] = 'path/to/file';`

Pretty handy tips!

Could you please add it to the `config-dist.php` file as a commented example for any user who may need it?

**Comment by bloatware** [comment]
@cara-tm done, will commit soon, thanks.

**Comment by jools-r** [comment]
Came across this while trying to track down what the new `pre_publish_script` was (nice tip btw). I use oui_prefs for this at the moment which gives you an extra prefs menu item under Admin › Preferences and so keeps site specific keys out of the forms but provisions them as variables on page load. It also allows admins/user to edit the details à la adi_variables but without the form. The big disadvantage is you have to edit the plugin at the moment.

@Bloke did mention in that thread another way of storing them importing those (back in [this thread](https://forum.textpattern.io/viewtopic.php?pid=310542#p310542)), but it fell by the wayside. Stef, do you still have your other solution lurking on your hard disk somewhere?

I think this would be invaluable for themes: ideally variables that are site specific, e.g. google site verification, analytics, font kit ids, twitter apis etc. and those that are theme specific, e.g. colours, font stacks, theme-specific options. You also mentioned that these are theoretically importable with a theme, even with a default value (much like the setup themes) but I never got that working.
