### ISSUE TITLE
Preflight activities for 4.7.4 release

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1407]
Shall we shoot for a 4.7.4 release this week? If yes, and we can manage Wednesday it'll be a year to the day since 4.7.0 was released.

If there are any blockers for a 4.7.4 release, please make them known here as soon as possible and mark this opening post with a thumbs down so it's more visible.

If you're OK with a 4.7.4 release, please mark this opening post with a thumbs up so it's more visible.

If I've missed anything from the list below, please update this post.

Tasks to complete before the 4.7.4 release, with assigned person(s):

- [ ] latest translations, if appropriate (@philwareham)
- [ ] check `dev` branch for any easy wins that can be ported into `4.7.4` branch without breaking the semantic versioning intergalactic laws (all / anyone)
- [ ] sanity check `HISTORY.txt` (@petecooper or anyone)
- [ ] draft release blog post (@petecooper or anyone)

Mucho thanks, Textpattern familia.

**Comment by bloatware** [comment]
Hi Pete et al.

IIRC, we wanted to avoid the plugins `eval()` evil on some extra-zealous hosts, replacing it with `include`. This is minimally done in `dev` now, but it needs much more thinking and testing before getting official. So not this week for me, sorry, unless our PR department takes the risk. :-)

**Comment by petecooper** [comment]
@bloatware – thank you, I had forgotten about that! You're absolutely right.

**Comment by philwareham** [comment]
Just a refresher - we will release 4.8.0 as soon as we can, once the plugin stuff is written, agreed and tested. There (almost certainly) won't be another 4.7.x release now. 4.8.0 won't have a long list of new features so it should happen sooner than normal.

**Comment by petecooper** [comment]
Thanks @philwareham – clarification appreciated.
