### ISSUE TITLE
notextile

### ISSUE THREAD

**Issue by colak** [textpattern/textpattern#1408]
### Expected behaviour

The `<notextile />` tag should be expected to be recognised even when it is not preceded by a space. 

### Actual behaviour

The `<notextile />` tag is not recognised when not preceded by a space, as identified on [forum.textpattern.io/viewtopic.php?pid=317977#p317977](https://forum.textpattern.io/viewtopic.php?pid=317977#p317977)

### Steps to reproduce

`something<notextile><txp::short-tag /></notextile>`

#### Additional information

Textpattern version: 4.7.3

**Comment by bloatware** [comment]
Hi @colak, this request should be addressed to [textile](https://github.com/textile/php-textile) repo, imo.

**Comment by colak** [comment]
> Hi @colak, this request should be addressed to [textile](https://github.com/textile/php-textile) repo, imo.

Indeed. I reported the issue on [https://github.com/textile/php-textile/issues/191](https://github.com/textile/php-textile/issues/191)
