### ISSUE TITLE
Consider making sections hide-able from `<txp:section_list />`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1409]
### Is your feature request related to a problem?

No.

### What is the feature?

Section visibility. Whether a section is shown in `<txp:section_list />` output. Essentially: "visibility = on or off" (default = on). Syndication would still be handled in the current yes or no fashion.

An article can be hidden using the status dropdown. An article requires a section. To my knowledge, a section cannot currently be hidden or made invisible in a similar fashion. Syndication can be disabled, and searching can be disabled, but I'm not aware of any native way of hiding the section itself from a section list.

Considerations:

* `<txp:section_list />` assumes all sections are visible, so will need changing to account for:
  * sections with visibility set to `on` (default, per current behaviour, assumes a section is to be listed);
  * sections with visibility set to `off`;
  * sections with visibility set to `on` or `off`;
* if visibility of sections is considered, `sticky` could also be an option so those section(s) appear first in a section list;

**Comment by bloatware** [comment]
I like the idea, but wouldn't its typical use be a bit redundant with "include in site search" feature? In which case we could just introduce a new "exclude non-searchable sections" (or its opposite) attribute to `<txp:section_list />`.

**Comment by petecooper** [comment]
@bloatware - yeah, pretty much, now you put it that way. I like the granularity of an on/off for visibility and searching, but it's not a stretch to assume hidden sections are excluded from search results.

Thank you for your reply - your approach is far better than I initially imagined!

**Comment by bloatware** [comment]
@petecooper it's just easier to do this way - no extra pref/string to add. We could even abuse the valueless `exclude` or `sections` attributes (currently meaningless) to avoid introducing a new one. But if you see a situation where this would not do, please share. Forum poll?

**Comment by petecooper** [comment]
I'm happy with the "exclude (non-)searchable sections" route. A forum poll would provide additional points of view, of course, but it's your call. Would you prefer a broader overview from the coal face, as it were?

**Comment by bloatware** [comment]
The question is whether we should show (as presently) or hide these sections by default. In the first case valueless `exclude` is fine, in the second one (not bw compatible) I'd rather use `sections` to show all sections.

**Comment by petecooper** [comment]
Personally, I'm erring toward the first case, there's less of a behaviour / logic change.

**Comment by bloatware** [comment]
OK then, [here](https://github.com/textpattern/textpattern/commit/fe6dc199f917b573259c0ca140fdcbf9f082a16d) we are.

**Comment by petecooper** [comment]
Wonderful -thank you very much @bloatware!
