### ISSUE TITLE
`get_magic_quotes_gpc()` deprecation notice with PHP 7.4 beta

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1413]
### Expected behaviour

No PHP notices in Textpattern administration area.

### Actual behaviour

PHP deprecation notice appears throughout administration area when PHP 7.4 beta 1 is installed, and on public side when Testing or Debugging production status is enabled.

```
Deprecated
: Function get_magic_quotes_gpc() is deprecated in
/var/www/vhosts/textpattern.co/dev-demo/live/textpattern/lib/constants.php
on line
136
```

![Screen Shot 2019-07-23 at 11 53 33](https://user-images.githubusercontent.com/226578/61706758-cec46380-ad40-11e9-8c5d-b165d283c2a6.png)
![Screen Shot 2019-07-23 at 11 53 40](https://user-images.githubusercontent.com/226578/61706759-cec46380-ad40-11e9-8dcb-cd51ccc757c2.png)
![Screen Shot 2019-07-23 at 11 53 46](https://user-images.githubusercontent.com/226578/61706760-cf5cfa00-ad40-11e9-8a19-fe8955dba36f.png)
![Screen Shot 2019-07-23 at 11 53 52](https://user-images.githubusercontent.com/226578/61706761-cf5cfa00-ad40-11e9-8ce3-2d564fd5dd57.png)

### Steps to reproduce

* install Textpattern 4.8.0-dev to a web server running PHP 7.4.0 beta 1.
* view administration area, note error

#### Additional information

* currently occurring at: https://dev-demo.textpattern.co/textpattern/index.php?event=diag
* did not occur with PHP 7.4.0 alpha 1.
* `phpinfo()` attached.

[php-i.txt](https://github.com/textpattern/textpattern/files/3421655/php-i.txt)

* possibly related: clean URL reports as failing, notification includes escaped HTML characters (see screenshot above).

Affected code: https://github.com/textpattern/textpattern/blob/dev/textpattern/lib/constants.php#L136

**Comment by petecooper** [comment]
Updated affected site to 7.4.0beta2, same outcome.

[php74beta2info.txt.zip](https://github.com/textpattern/textpattern/files/3474159/php74beta2info.txt.zip)

![Screen Shot 2019-08-06 at 22 00 29](https://user-images.githubusercontent.com/226578/62577091-1517d780-b896-11e9-9ccb-191a79fa7956.png)

**Comment by Bloke** [comment]
Since we only support 5.4.0+ and all such functions return `FALSE` from that point forward, I'm tempted to just comb core for any mention of `magic` and remove all references. Anyone see any danger in that rather Hulk Smash approach?

**Comment by petecooper** [comment]
@Bloke - since we're shooting for PHP 5.5+ in the next minor release, does that help or hinder the above?

**Comment by Bloke** [comment]
Don't think it makes a difference. The entire GPC quotes things was pretty much squashed in PHP 5.4 so I expect all our tests for "is gpc_magic_quotes on or off" (static and runtime) in the code are redundant and will always return false. I expect it can be axed with no ill effect.

**Comment by petecooper** [comment]
@Bloke - I'm keeping `dev-demo` on the latest pre-release PHP (currently 7.4 beta 2, expecting beta 3 then GA), and `release-demo` is on the latest stable (currently 7.3.8), so by all means use `dev-demo` for testing if you'd like.

**Comment by Bloke** [comment]
Axed.

If we find any plugins that break due to reliance on the `MAGIC_QUOTES_GPC` constant, we can reinstate it for the time being for backwards compatibility:

```
define('MAGIC_QUOTES_GPC', false);
```

**Comment by petecooper** [comment]
Nice one, @Bloke - thank you!
