### ISSUE TITLE
Password field in Hive Themes

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1416]
### Expected behaviour

Better vertical alignment into the password field.

### Actual behaviour

This field, with other, is affected by a global padding may be not adapted.

### Proposal for change

This seems to restore the vertical rhythm (need cross browsers test):

`[type="password"] {padding-top: inherit}`

Textpattern version: 4.7.4

**Comment by petecooper** [comment]
@philwareham - any thoughts?

**Comment by philwareham** [comment]
What browser is the mis-alignment happening in - and on which panel? Thanks.

**Comment by cara-tm** [comment]
Hi Phil.
With FF (latest) on the login panel.

**Comment by cara-tm** [comment]
For an attempt at harmonization with the dot characters into password fields (between Google Chromium and Firefox):

    #login_form input[type="password"] {
    letter-spacing: 2px;
    font: caption;
    font-weight: bold;
    -webkit-text-security: circle!important;
    -moz-box-sizing: content-box
    }

Tested with success into PC system; I didn't have time to try with Mac.

**Comment by philwareham** [comment]
Firefox (and Internet Explorer) use the character "Black Circle" (●), which uses the Unicode code point `25CF`, Chrome (and any Blink/WebKit browsers) uses the character "Bullet" (•), which uses the Unicode code point `2022`. In my opinion we don't need to try and design around this visual discrepancy with additional CSS though.

So I'm closing this issue. Thanks anyway.
