### ISSUE TITLE
`Notice "Trying to access array offset on value of type bool"` dialog and messages

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1417]
### Expected behaviour

No notices displayed when editing the title of the default article.

### Actual behaviour

Notice displayed: `Notice "Trying to access array offset on value of type bool".`

### Steps to reproduce

* confirm 4.8.0-dev
* set Debugging mode
* change default article title, save article, note notice

#### Additional information

Textpattern version: 4.8.0-dev at time of writing, PHP 7.4-beta4. Does not occur with Textpattern 4.7.3 and PHP 7.3.8.

#### Notes

It's not clear to me what triggers the notice, as creating a new article then updating the title works without issue. Perhaps something in the article body or except, I will investigate further.

![Screen Shot 2019-08-20 at 19 25 59](https://user-images.githubusercontent.com/226578/63374188-40fc8800-c381-11e9-8ce2-0a038f865b88.png)
![Screen Shot 2019-08-20 at 19 26 30](https://user-images.githubusercontent.com/226578/63374189-41951e80-c381-11e9-9449-c94619d55d4e.png)
![Screen Shot 2019-08-20 at 19 26 34](https://user-images.githubusercontent.com/226578/63374190-41951e80-c381-11e9-94c1-730f3dcf2b69.png)

**Comment by petecooper** [comment]
Possibly useful: https://github.com/concrete5/concrete5/commit/023ad8d288149357ea4eb0fca4db9765633b3d12

**Comment by petecooper** [comment]
Also appears on front-side:

```
Tag error: <txp:page_title /> ->  Notice: Trying to access array offset on value of type null while parsing form None on page default
page_title()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:506 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:429 processTags()
textpattern/lib/txplib_misc.php:4579 parse()
textpattern/publish.php:650 parse_page()
index.php:116 textpattern()
```

![Screen Shot 2019-08-20 at 20 23 38](https://user-images.githubusercontent.com/226578/63377729-8c666480-c388-11e9-8f07-fef87a74d8e8.png)

A trigger appears to be Textile'd bullets:

![Screen Shot 2019-08-20 at 20 27 57](https://user-images.githubusercontent.com/226578/63377998-2201f400-c389-11e9-9623-5cce94f0a60e.png)
![Screen Shot 2019-08-20 at 20 28 01](https://user-images.githubusercontent.com/226578/63377999-2201f400-c389-11e9-9060-572ca7553843.png)

**Comment by Bloke** [comment]
My guess for the page_title front side error is if you try and use the tag outside article context (e.g. a list page outside a `<txp:article>` tag) then `$thisarticle` won't be set.

Please see if hacking the `page_title()` function in `publish/taghandlers.php` works. Change:

```
} elseif ($thisarticle['title']) {
```

To:

```
} elseif (!empty($thisarticle) && $thisarticle['title']) {
```

As for the admin-side error, more research will be required. It may depend on content or certain fields being omitted which leave a variable in a default bool state that's not overridden by an array and is then tried to be accessed as such.

**Comment by petecooper** [comment]
Tried to reproduce again, not able to this time - closing.

Thanks for the input, @Bloke - apologies for the distraction!
