### ISSUE TITLE
`problem_connecting_update_server` message on multilingual systems

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1419]
### Expected behaviour

`problem_connecting_update_server` message should respect site language and return the appropriate translation where >1 language is installed.

### Actual behaviour

`problem_connecting_update_server` message does not appear to respect the site language where >1 language is installed.

![Screen Shot 2019-09-24 at 17 46 06](https://user-images.githubusercontent.com/226578/65534790-fcbc5480-def7-11e9-8ad4-5114a1734f45.png)

![Screen Shot 2019-09-24 at 17 46 52](https://user-images.githubusercontent.com/226578/65534795-004fdb80-def8-11e9-89fc-1e3544a8d504.png)

### Steps to reproduce

* install additional language pack
* trigger the `problem_connecting_update_server` warning (i.e. firewall rule or similar)
* check Diagnostics for `problem_connecting_update_server` translation.

#### Additional information

Textpattern version: 4.7.3

I think this might have something to do with a cached response, and it not being translated for subsequent users. I spotted this on the release demo site, where another user had set their language settings to Spanish (see above screenshot), perhaps they'd set the site to Spanish, then the error triggered, then they set it back to English, and since the message is cached for a given time, is the translated string being cached? It's not 100% clear to me how this happened, hence the 'verification required' tag.

**Comment by Bloke** [comment]
Yes, it's currently a cacheing issue. And I honestly can't remember why it was done this way, but the entire translated string is stashed in the prefs table so it's just retrieved as-is and redisplayed until the 24-hour period elapses. That's a bit stupid.

What it should do is store the string _key_ and the release info separately for each message in the prefs table, and only run them through `gTxt()` during display so they respect the current language. Leave it with me, I'll fix that.

**Comment by Bloke** [comment]
This should be fixed in  4eb6432. Please test and reopen if not.
