### ISSUE TITLE
Show diagnostic info when `problem_connecting_update_server` error occurs

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1423]
### Is your feature request related to a problem?

Partially, yes.

### What is the feature?

When a Textpattern instance cannot check for updates, a generic error message is shown (the relevant translation for `problem_connecting_update_server`). Since we're on the Diagnostics panel, it would be useful to know more information as to why an error occurred:

* HTTP 4xx/5xx error at the textpattern.com end;
* a `curl` issue;
* …or something else;

My instinct would be to have the same error message as it stands now, with a more verbose error or debug output in the panel below, rather than messing up the 'headline' area with potentially lots of code.

**Comment by Bloke** [comment]
If we know the reason, yeah great. We can probably find out somehow.

But due to the fact the results are cached for 24 hours between requests, you'll see the same _detailed reason_ until the next check. Is that potentially more misleading than helpful? e.g. textpattern.com site issuing a 404 "all day" when it's clearly working and just had a wobbly a the very moment someone's site attempted an upgrade check?

Not saying more info isn't valuable, we just need to be careful how this info is presented to avoid adding to the confusion. We could reduce the time between checks. 24 hours is perhaps rather conservative given the number of times in a typical day that an administrator is likely to visit
 the Diagnostics panel.

**Comment by petecooper** [comment]
Presumably the 24 hour thing is a throwback to the Joyent era…is it viable to have some mechanism to reset a clock and force a check through manually? Assuming we can rate limit on the textpattern.com server side of things, I can't think of any real world reason not to make it available.

It's not a huge deal when this error crops up, but it's mildly irritating when we can't explain why it happened…and then the wait-and-see approach is fine, but leaves a support request hanging. Having a definitive reason (if it exists) would be great, if not then no great shakes.

**Comment by Bloke** [comment]
Forcing a manual check is a little hairy as one could resubmit the form rapidly and swamp the server.

24 hours is indeed legacy. What's a more appropriate rate limit these days? Hour? Half hour? Five minutes?

**Comment by petecooper** [comment]
>What's a more appropriate rate limit these days? Hour? Half hour? Five minutes?

I'd start with an hour, that's much more sensible. I can grep the log files and see what sort of traffic the JSON file gets, but I know from memory it's not much.

**Comment by Bloke** [comment]
An hour it is. So all we have to do now is find a way to extract the reason for the failure and add it to the (high?) Diagnostics panel.

**Comment by petecooper** [comment]
I grep'd the current access log: since 9 September 2019 18:45, there have been 848 hits on `version.json`. That's `8 weeks (56 days), so we're averaging about 16 hits a day. On an 81 byte file, that's about 67KB of traffic.

**Comment by petecooper** [comment]
For completeness: https://forum.textpattern.com/viewtopic.php?pid=324292#p324292

**Comment by petecooper** [comment]
It's very possible this has been made a lot more straightforward with https://github.com/textpattern/textpattern/commit/cf2900924feb811fa294dfd6db74520fee6ba985 (thanks @Bloke)

**Comment by petecooper** [comment]
I'm going to close this since we have better visibility of why this started happening (TLS / SSL mismatch), and the commit referenced above should provide enough to go in initially. We can reopen as required.
