### ISSUE TITLE
Offer `phpinfo()` link in Diagnostics

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1425]
### Is your feature request related to a problem?

Nope.

### What is the feature?

Provide a link to `phpinfo()` when Diagnostics panel Detail is set to High. Link opens in a new window. Will aid troubleshooting by making it easier to access info.

After the Diagnostics dropdown, before the checkbox to Hide Private Information.

![re](https://user-images.githubusercontent.com/226578/68283614-bff58880-0073-11ea-9819-8fad49eacf40.png)

Considerations:

* new window/tab or scrollable modal? I'm erring toward new window/tab;
* access to user grades who can access Diagnostics panel at present, deny to anonymous phishers and underlings;
* check whether `phpinfo()` is enabled (or, not listed under `disable_functions`) before offering link;
* any additional security considerations?;
* …did I miss anything?

**Comment by Bloke** [comment]
Can't see any reason not to include this. It's back-end and limited to Publishers and Managing Editors and is a useful diagnostic tool. Also saves us from telling people to write `phpinfo()` in an article.

Checking  if it's enabled or not is slightly cumbersome as it may rely on reading and parsing the output of `ini_get()` which in itself might be disabled. Not sure if this is a good avenue or if there are other ways to determine if it's enabled - it may be 'available' but just returns _this feature is disabled_ in its response.

Assuming we can reliably test the existence of the function, how about we introduce a new `step` to the Diagnostics panel, the link to which will simply be a new tab. The only consideration then is whether we render it with Txp furniture - navbar, primarily - or just output it raw. Thoughts?

**Comment by petecooper** [comment]
>[…] it may be 'available' but just returns this feature is disabled in its response.

This. We can try, at least.

**Comment by Bloke** [comment]
@petecooper See if this is close to what you envisioned. No idea what happens if the function is disabled. Should we render it as a link rather than a button? Put it somewhere else? It does seem to take up quite a bit of vertical space. Maybe float it right above the textarea? @philwareham any thoughts?

**Comment by petecooper** [comment]
Thanks @Bloke - I'll wait for the midday rebuild of dev-demo and take a look. I'm indifferent about whether it's a button or link, I think either will suffice. Deferring to @philwareham for the final say.

**Comment by petecooper** [comment]
Functionally sound, works seamlessly - thanks very much @Bloke, nice one.

**Comment by petecooper** [comment]
Gonna close this for now - OP is fulfilled. Phil can take a look as and when, I'm sure.
