### ISSUE TITLE
txplib_misc.php is txplib_mess.php

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1426]
This must be the largest php file (~200Kb) loaded on the public side, but about 1/3 of its functions are very unlikely to be used there. I suggest we transfer them to txplib_admin.php and globally include the latter on the admin side. The only risk are plugins that do some admin tasks on the public side, but they (if any) can be easily patched.

**Comment by philwareham** [comment]
Sounds like a good plan to me

**Comment by Bloke** [comment]
Makes sense and if, during the course of combing this file you find any deprecated functions from a few major versions ago, by all means cull them.

Ultimately, a heap of the functionality in this file just comprises backwards-compatible stubs for new Classes we have, and I'd like to continue this trend away from functions as we build new Objects that do stuff better.

Things like `gps()` and `ps()` and `doSlash()` are so ingrained that they'll have to live on for quite a while, but even these should be introduced into Objects of their own if they haven't already. There's a nice inheritance chain here, perhaps from cs->ps->gps. And, incidentally, `doSlash()` should become pretty much irrelevant once we fashion a PDO library and use parametrized queries.

I've never liked 'misc' as it just ends up a dumping ground for stuff that doesn't fit elsewhere. We could always move all the admin stuff out, as you suggest, and introduce a `txplib_public.php` (or `txplib_common.php`) that contains solely the public-aware/common functionality, then just leave `txplib_misc.php` in there for backwards compatibility, containing a single line:

```require_once txplib_public.php;```

**Comment by bloatware** [comment]
I'm all for switching to Objects, especially on the admin-side. But few vital functions (like parse(), splat() etc) should remain plain functions imo, since they are called thousands times on an average page. I fear a slowdown every time we touch them, thought static methods are becoming faster and faster.

**Comment by Bloke** [comment]
Yeah, only switch to Objects if it makes sense. If it's going to impact performance too much, stick with functions. I'm no purist!

**Comment by bloatware** [comment]
There is no much difference on PHP7, so we can start switching to objects:
```
Current PHP version: 7.4.0RC5
Total execution time is for static method is: 0.058917045593262
Total execution time for instance method is: 0.045562028884888
Total execution time for function is: 0.040056943893433
```

**Comment by Bloke** [comment]
Wow, that's waaay better results than I expected. They've been putting some work into PHP 7 it seems. Was that for a complex nested parsed page? If so, instance methods seem the way to go.

**Comment by bloatware** [comment]
Figures (tested on Pete's demo site) are rather unstable, once I even got
```
Total execution time is for static method is: 0.063441038131714
Total execution time for instance method is: 0.059608221054077
Total execution time for function is: 0.086368083953857
```
But under normal load functions are just marginally faster, that's great. But our min 4.8 requirements are PHP 5.5, dunno how it goes there.
