### ISSUE TITLE
Allow HTML to be stored on File System

### ISSUE THREAD

**Issue by waypointdelta** [textpattern/textpattern#1427]
I would like to make various changes to textpattern in a local fork.    It's difficult to do this when the code for rendering pages (HTML/CSS) is stored in a database.    It would be great to be able to change a pointer for reading source from either DB or OS storage.

**Comment by Bloke** [comment]
From Txp v4.7 we have Themes which are Pages, Forms and Stylesheets stored in the DB but updateable from disk in a single action. See the [Themes](https://docs.textpattern.com/themes/index.html) area of the docs site for some overview information or search/ask on the forum for more detailed help on this feature.

**Comment by bloatware** [comment]
There is a [plugin](https://forum.textpattern.com/viewtopic.php?id=48528) that seems to do what you request. We get users feedback before eventually implementing it in core.

**Comment by petecooper** [comment]
Closing this for now based on workaround / solution with `etc_flat`.
