### ISSUE TITLE
Confirm compatibility with PHP 7.4

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1429]
PHP 7.4.0 is out, `dev-demo` has been running seemingly OK on all the release candidates, and the GA release arrived this evening.

Is there anything in https://www.php.net/manual/en/migration74.deprecated.php that we should be aware of?

**Comment by Bloke** [comment]
Can't see anything in there that causes us concern. Most of the stuff doesn't apply or we don't employ. The only one that we might use is the ternary thing, though I don't think we're using complicated ternary chains. I tend to use parentheses anyway even in simple expressions, out of habit (and Oleg reminds me I don't have to!)

**Comment by bloatware** [comment]
I think we are ready, up to the final semi-colon. Thanks to @petecooper for beta-testing!
