### ISSUE TITLE
PHP system requirements for Textpattern 4.8 - increase to PHP 5.5

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1432]
This may simply be a formality, as we've discussed this before, but it's an important one.

Textpattern 4.7 says PHP 5.4 is minimum version. Textpattern 4.8 should be PHP 5.5 at minimum.

Support for PHP 5.5 is long since done, same goes for PHP 5.6 (the last release in the PHP 5 series). I'm seeing more and more web hosting organisations only offering PHP 5.6, so I don't think it's controversial to make PHP 5.5 the minimum for this release.

Please throw a thumbs up or thumbs down on this comment, leave a comment if further clarification is needed, and I'll make the changes. Thank you.

**Comment by bloatware** [comment]
> 
> 
> Textpattern 4.8 should be PHP 5.5 at minimum.

Its code actually *requires* PHP 5.5+

**Comment by petecooper** [comment]
>requires PHP 5.5

Perfect. Thank you.
