### ISSUE TITLE
Capitals on "Change Category", articles list

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1434]
![Screen Shot 2019-12-01 at 19 14 16](https://user-images.githubusercontent.com/226578/69918889-f3f37c00-146e-11ea-9a31-4a17fb2c316d.png)

For uniformity, "Change Category" entries in the Articles dropdown list should be lower case, as all other similar items (section, status, comments, author) are lower case, as are the dropdown options on other list pages.

**Comment by Bloke** [comment]
I believe this is a Textpack issue.

**Comment by petecooper** [comment]
Closing, is now https://github.com/textpattern/textpacks/issues/286
