### ISSUE TITLE
Minor tweak to Theme import UI

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1435]
Above the themes table on the Themes panel, why does the dropdown have a blank entry? Can anyone think of a reason why we can't just dive straight in to the list?

Also, is 'Upload' the right terminology? Looking around other panels we have:

* Files panel: file options such as category assignment and file chooser and an 'Upload' button. Makes sense we're uploading a file to the /files directory.
* Images panel: image options such as category assignment and file chooser and an 'Upload' button. Makes sense we're uploading a file to the /images directory.
* Plugins panel: uploading a plugin from a .php file. File browsers and an 'Upload' button. Makes sense, we're unpacking the zip/uploading the file and installing it on disk in the/plugins directory and into the database.
* Plugins panel: importing a plugin from disk that already resides there. Select list (note: no blank first) and an 'Import' button. Makes sense, we're importing what's already there and adding it to the database.
* Files panel: select list of files on disk (note: no blank first) and a 'Create' button. Makes sense(ish), as we're creating a file entry in the DB from what's on disk. Perhaps this should be 'Import'?

Proposal: change the button on the Themes panel to 'Import' to match the above uses. That also paves the way in future if we decide to permit 'Upload' of a theme package (a.k.a. file browser to upload a zipped bundle and unpack it on people's behalf into the /themes directory and install it in the database).

Thoughts?

**Comment by petecooper** [comment]
>Above the themes table on the Themes panel, why does the dropdown have a blank entry?

Pardon my ignorance, @Bloke - where are you seeing the blank entry, please?

![Screen Shot 2019-12-03 at 16 23 08](https://user-images.githubusercontent.com/226578/70069226-57091e00-15e9-11ea-88f0-e77554929bec.png)

**Comment by Bloke** [comment]
You'll only see it if you have themes on disk that are not in the database:

![Screen Shot 2019-12-03 at 16 27 04](https://user-images.githubusercontent.com/21252/70069636-0219d780-15ea-11ea-973a-16f651d97dd1.png)

**Comment by cara-tm** [comment]
> That also paves the way in future if we decide to permit 'Upload' of a theme package [...]

I like this Punk music that sound good into my hears.

**Comment by Bloke** [comment]
If there are no objections, I'll do it then.
