### ISSUE TITLE
Plugin import list not updated on plugin deletion

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1436]
### Expected behaviour

Deleting a plugin from the database and leaving it on disk should update the list of plugins available to import above.

### Actual behaviour

The list of plugins available to import remains as it was when the page was loaded.

### Steps to reproduce

* Install a plugin
* Delete it using the With selected... tool but leave it on disk.
* Observe that the list of available files in the Import from disk dropdown does not change (if already present) nor does it appear (if it was previously missing) until page refresh occurs.

#### Additional information

Textpattern version: 4.8.0-dev

**Comment by bloatware** [comment]
Yep, this list is outside the async-updated area. I thought it's not very much a problem (why would one want to install a just-deleted plugin), but will check, thanks.

**Comment by Bloke** [comment]
Yeah, it's not a major issue and we can live with it if it's too much hassle to fix. Just inconsistent with (for example) the Themes panel that _does_ do a refresh when you delete a theme. The Themes panel does a full refresh on delete, whereas the Plugins doesn't. Do we trigger one? Keeping the pagination the same as it was before the operation?

**Comment by Bloke** [comment]
Oh, and a possible use case is during plugin development. To test triggering lifecycle events:

1. Make changes to code on disk/VCS.
2. Delete plugin from database, leaving disk copy alone.
3. Reinstall it from disk via the import control.

Will that trigger a lifecycle install event, btw?

**Comment by bloatware** [comment]
We should simplify partial async page update API anyway, it's just a matter of time.

Dunno re Themes, I never had more than 5 installed at once.

Lifecycles should be triggered in all plugin install modes, but I will check.

**Comment by Bloke** [comment]
Oooh, actually, I've never checked if the list of available themes to import is updated if there are more than a screenful of themes. I should test that. Thanks for the nudge :)

**Comment by Bloke** [comment]
For reference, the Themes panel seems to update the import list immediately when you delete one. It's still Ajax so it must do something different on partial refresh.
