### ISSUE TITLE
Plugin import list shows plugins not on current page

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1437]
### Expected behaviour

The plugins available to import only represent those that are not in the _entire list_ of installed plugins.

### Actual behaviour

The plugins to import show plugins that are on subsequent pages of results because only the first page of results are removed from the Import list.

### Steps to reproduce

1. Visit the Plugins panel and ensure that the pagination control is set to 12.
2. Install more than 12 plugins.
3. Note the Import list dropdown shows plugin 13 onwards as being 'available' to import.

#### Additional information

Textpattern version: 4.8.0-dev

**Comment by bloatware** [comment]
Heh, thanks, what a mess! Will fix.
