### ISSUE TITLE
Minor display glitch on plugins pane

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1445]
#### Display anomaly on plugins pane

Not really a bug, just a display anomaly at wider viewports in the mid-stage of plugin installation resulting in there being apparently two "upload" buttons side by side. One is the upload file button and the other is upload pasted content button.

Narrower width ![Narrow width](http://jools.link/yc/up)

Wider viewport ![Narrow width](http://jools.link/wj78-)

#### Additional information

Textpattern version: 4.8.0dev

**Comment by Bloke** [comment]
Ah, so _that's_ what the `<br>` was for :)

**Comment by philwareham** [comment]
Yep, so it seems! I've just added it before the optional 'import...' row and it seems to be fine now.
