### ISSUE TITLE
Admin-side UI dialog not draggable/resizeable on touch screen

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1446]
Is it only me?

**Comment by Bloke** [comment]
Not just you.

**Comment by bloatware** [comment]
Plus tagbuilder.

**Comment by Bloke** [comment]
Weird, yeah. Sure they used to be movable but I must admit I've not tried much on mobile.

**Comment by Bloke** [comment]
Nope, just tried on the demo server. The help popups and tagbuilder weren't draggable on 4.7.3 either.

**Comment by philwareham** [comment]
jQuery UI doesn’t currently have touch enabled features. It’s a planned addition (if jQuery UI continues development).

**Comment by bloatware** [comment]
Click seems to work, fortunately, so the dialog is closable. I leave the issue open for reminder.

**Comment by phiw13** [comment]
Yes `click` will work because the close button (and the mini-tabs on the Preview diag) are interactive elements (`a[href]` or `button`). Scrolling in the dialog should also work as there is nothing JS / Jquery driven there.

**Comment by philwareham** [comment]
Closing this as it's a direct relation of https://github.com/textpattern/textpattern/issues/1398
