### ISSUE TITLE
Multi-site doc link is wrong

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1451]
### Expected behaviour

Proper link URL.

### Actual behaviour

Current link: https://docs.textpattern.com/installation/multi-site-textpattern

This link into the `/sites/site1/README.txt` file is incorrect and must be updated to this one:

https://docs.textpattern.com/setup/multi-site-installation

### Steps to reproduce

Try the incorrect link.

#### Additional information

Textpattern version: 4.8-beta

**Comment by petecooper** [comment]
Done -thanks @cara-tm!
