### ISSUE TITLE
`default` section URL format could be safely omitted

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1452]
Section `default` does not have articles assigned to it, but offers a URL format for articles:

![Screenshot 2020-01-01 at 18 57 09](https://user-images.githubusercontent.com/226578/71644962-e7aa4b00-2cc8-11ea-93d7-c656912d2005.png)

Is there a straightforward way of not showing that option, given that the name or ID won't change?

**Comment by bloatware** [comment]
@petecooper it's the default URL format used to access 'sectionless' pages like @?c=happy-new-year@.

**Comment by petecooper** [comment]
Got it - thank you!
