### ISSUE TITLE
Deleting dev theme leads to unknown section

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1453]
### Expected behaviour

When deleting an in-development theme, either prevent it from doing so or revert to live on affected sections.

### Actual behaviour

(untranslated) unknown_section error shown to logged-in users.

### Prerequisites

1. Duplicate an in-use theme and modify it slightly so it is easy to spot which theme is which.
2. Create at least two Sections with content assigned to each.
3. Assign all Live sections to a single theme, and ensure no Development themes are in use.
4. View a front-end article in each section to verify which theme is in use.

### Steps to reproduce

1. Assign the duplicated theme to a section as a development theme.
2. View the associated front-end article to verify that the development theme has been applied.
3. Note that the section is highlighted with the 'development' pill on the Sections panel.
4. Visit the Themes panel. Note that the only theme "in use" is the original Live theme.
5. Delete the duplicate theme (the one that is used in-development only). Clear the 'remove' checkbox to leave the theme on disk.
6. Visit the Sections panel.
7. Note that the deleted theme is still shown against the section, with a 'development' pill, even though the theme's been deleted.
8. Visit the front-end article in this section. Note that Txp returns unknown_section.
9. Further note this string is untranslated.

#### Additional information

Textpattern version: 4.8.0-dev.

**Comment by bloatware** [comment]
Yep, makes sense.

**Comment by Bloke** [comment]
Which would be your preference? Prevent or revert? Subtext question: which is easier to implement? :)

**Comment by bloatware** [comment]
Looks equally easy. Heads or tails?

**Comment by Bloke** [comment]
Hehe, anyone else have a preference here? What's most logical/useful for most users do you think? Prevention or rollback? Opinions please @philwareham @jools-r @petecooper @wion @phiw13

Thank you!

**Comment by wion** [comment]
/ flips coin /

**Tails!**

**Comment by bloatware** [comment]
Prevention [wins](https://github.com/textpattern/textpattern/commit/741b649c27f4ae8de32203e08ac21b930cac3bbd), it's safer in multi-admin cases. And we had to treat theme rename anyway.

**Comment by Bloke** [comment]
Works for me! Nice one, thank you. I'll give it a blast in a little while then close this.

**Comment by petecooper** [comment]
I'm fashionably late to this issue party, but thanks for the invitation. I'll be in the kitchen cleaning the dishes.

**Comment by Bloke** [comment]
Sorted, thanks Oleg. Works like a charm.
