### ISSUE TITLE
HTTPS support into the config-dist file

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1454]
### Is your feature request related to a problem?

No. Just an advice.

### What is the feature?

Currently, the `config-dist.php` file doesn't contain an advice for https protocol support:

Please, add this as a comment:

`// define('PROTOCOL', 'https://');`

**Comment by petecooper** [comment]
+1. I can see this being helpful now, and gradually less useful as time passes and more sites switch to https by default. I'll take this, anyone on a higher pay grade is welcome to undo it.
