### ISSUE TITLE
Let Textpattern installer try to delete /setup/ folder and its contents

### ISSUE THREAD

**Issue by kuopassa** [textpattern/textpattern#1457]
### What is the feature?

Installing Textpattern could be enhanced a bit by trying to automatically remove the /setup/ folder with its contents, if it looks like user has successfully installed Textpattern. That way user wouldn't need to do it manually. Maybe deleting the /setup/ could be attempted after a confirmation checkbox has been ticked.

**Comment by bloatware** [comment]
We do try to delete it, AFAIR. But the script does not always have sufficient rights on `setup` directory.

**Comment by Bloke** [comment]
Yes, we do this if possible. See '/textpattern/update/update.php'.
