### ISSUE TITLE
Minor admin-side css class additions

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1458]
@philwareham: As per the [forum topic](https://forum.textpattern.com/viewtopic.php?pid=321289#p321289), it would be great to have:

* a [helper class](https://forum.textpattern.com/viewtopic.php?pid=321004#p321004) for bumping (indenting) admin-side form items without a label into the right-hand column (for wider viewports). The class would also need adding to the class-list for posted_now field on edit panels (e.g. the new one under links).
* a `.txp-layout-3col` class (and related classes) to the grid as mentioned [here](https://forum.textpattern.com/viewtopic.php?pid=320845#p320845), e.g for use in own panels or dashboards.

Thanks!

**Comment by philwareham** [comment]
@jools-r these additions are now done. Closing.
