### ISSUE TITLE
Search dropdown disappears behind section_container

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1459]
### Expected behaviour

Dropdown displays when clicking search arrow to filter results by column.

### Actual behaviour

Dropdown disappears behind the table container, only showing the 'all' checkbox and first option.

### Steps to reproduce

* Visit any 'list' panel.
* Click the down-arrow on the Search box.

#### Additional information

4.8.0-dev. Related to css grid/3-column support, perhaps?

**Comment by philwareham** [comment]
@Bloke can you revert my commit with css grid in it please. I think I’ll leave that until 4.9 as it had unforeseen consequences. I’ll add a 3 column flexbox version in Monday when I’m next near my computer. Ta!

**Comment by Bloke** [comment]
I would but it won't let me revert it, because of the changes to the CSS in later files. It whinges of conflicts in all three files and I'm buggered if I can locate the differences in that one looooooooong line of CSS :(

Hmmm, how can we do this cleanly...? I wonder if we can extract the commits since eeee01f9, revert everything after eeee01f9, then play back the extracted commits? Might require some wrangling.

And even if we do that, won't your SASS files then be out of sync, 'cos the changes will need to be done there too, right?

**Comment by philwareham** [comment]
This will have to wait until Monday then, sorry!

**Comment by Bloke** [comment]
No worries. I'll leave those issues open for now so people don't duplicate them over the weekend.

**Comment by phiw13** [comment]
Why did you put this: ` overflow: hidden;` in ?

```css
.txp-layout>* {
box-sizing: border-box;
min-width: 0;
padding: 0 1em;
 overflow: hidden;
}
```

Remove that ` overflow: hidden;` and you are all set.

**Comment by philwareham** [comment]
Doh! I can’t remember why that rule was there (it was commented out along with the css grid stuff so I left it in). Thanks for investigating.

Stef, in the short term you can probably find/delete that rule in the theme css files to fix this now. I’ll then also fix in the repos on Monday.

**Comment by petecooper** [comment]
I'll have a look later this morning - I'll have some time after 10am.
