### ISSUE TITLE
With-selected no longer fixed at bottom of window

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1460]
### Expected behaviour

Multi-edit dropdown in its 'fixed' position, regardless of vertical scroll position.

### Actual behaviour

Multi-edit dropdown only appears after scrolling to bottom of table.

### Steps to reproduce

* Visit any 'list' panel, with quite a few rows of content in it.
* Select one or more items via checkbox.
* Note that multi-edit dropdown isn't available, as it was in previous beta.

#### Additional information

4.8.0-dev. Related to css-grid/3-column support?

**Comment by phiw13** [comment]
Same issue as #1459
