### ISSUE TITLE
Save box on Write panel no longer sticky

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1461]
### Expected behaviour

Save box on Write panel remains in view as viewport is scrolled.

### Actual behaviour

Save box on Write panel disappears from view as viewport is scrolled. Also, top line of Save box border is missing.

### Steps to reproduce

* Visit Write panel
* Scroll down :)

#### Additional information

4.8.0-dev. Related to css-grid/3-column support, perhaps?

**Comment by phiw13** [comment]
Same issue (and solution) as #1459
