### ISSUE TITLE
Potential issue with `link_to_*`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1463]
https://forum.textpattern.com/viewtopic.php?pid=321353#p321353

Potential blocker for `beta.2`, raising issue for completeness and tracking.

Pinging https://github.com/textpattern/textpattern/issues/1449 for monitoring.

**Comment by bloatware** [comment]
[Apparently](https://forum.textpattern.com/viewtopic.php?pid=321367#p321367) not an issue, awaiting confirmation.
