### ISSUE TITLE
`/textpattern/plugins/` has gone

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1466]
![Screenshot 2020-02-05 at 09 01 01](https://user-images.githubusercontent.com/226578/73826653-15b60a00-47f6-11ea-8afa-e71bc7714d05.png)

It looks like [this commit](https://github.com/textpattern/textpattern/commit/71e4d1c9fa0b876b607a151c0c6b884a2cb8c7b8) removes `/textpattern/plugins/.htaccess-dist` and an empty directory remained, which `git` ignores.

Is it safe to restore the `/textpattern/plugins/` directory?

**Comment by Bloke** [comment]
The .htaccess-dist should be there to avoid this.

**Comment by bloatware** [comment]
@petecooper yes please. It was me testing unwritable `plugins` directory, and something went wrong.
