### ISSUE TITLE
[meta] RFC: Consider point release milestones

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1469]
Currently, we target milestones at 'big' releases: 4.8, 4.9, 4.10 and so on. There are some issues that can be addressed for point release(s) on a given big releases: 4.8.1, 4.8.2 and perhaps 4.8.3.

I propose we have intermediate milestones for the interim times between releases, using one of the following:

* numbered point release milestone (e.g. `4.8.1`, `4.8.2`)
* relative point release milestone (e.g. `current.point`, `upcoming.point`), but this looks clunky
* something else I haven't considered

The main benefit would be better tracking between big releases, especially during development switches from current version maintenance to next version planning.

**Comment by Bloke** [comment]
Yep, we should do this. 4.8.1, 4.8.2, etc.

**Comment by petecooper** [comment]
Thanks @Bloke - will make 4.8.1 for starters and close.
