### ISSUE TITLE
Admin-side navigation keyboard shortcuts.

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1471]
### Is your feature request related to a problem?

No.

### What is the feature?

Admin-side navigation keyboard shortcuts.

Existing keyboard shortcuts are a very useful and welcome utility. Discogs have a neat feature for one or two sequential (not modifier + key) keys to navigate to certain areas of the site.

Info: https://blog.discogs.com/en/new-keyboard-shortcuts/

Current keys:

![Screenshot 2020-02-14 at 20 03 21](https://user-images.githubusercontent.com/226578/74563629-1de41700-4f65-11ea-8311-ebbcf9af31b6.png)

Clearly multilingual sites will be a consideration, especially given character sets and the like.

I'm erring toward off by default, perhaps the sequences are configurable in some fashion by the user…or maybe that's too complex.

**Comment by philwareham** [comment]
We’ve investigated `accesskey` attributes in the past but I can’t remember what the outcome was. It’s been years (maybe decades) since I used those on a site so I’d have to refresh my learning on them.

**Comment by philwareham** [comment]
Regarding `accesskey` specifically, note on MDN:

> ... Because of these issues, it is generally advised not to use accesskeys for most general-purpose websites and web apps.

Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey#Accessibility_concerns

**Comment by petecooper** [comment]
Makes a lot of sense - will close!
