### ISSUE TITLE
Incorrect pophelp anchor when update check fails

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1473]
### Expected behaviour

If new version update check fails, pophelp should reflect that.

### Actual behaviour

If new version update check fails, pophelp refers to a new version being available

### Steps to reproduce

Visit Diagnostics when an update check is unsuccessful (e.g. firewall, network down etc).
Note pophelp anchor and content.

![Screenshot 2020-02-24 at 17 53 19](https://user-images.githubusercontent.com/226578/75225855-478e1100-57a3-11ea-8b4b-802d92782402.png)

#### Additional information

Textpattern version: 4.8.0

**Comment by Bloke** [comment]
Good spot. We should add an error topic and flip flop between the pophelps depending on success/failure. I'll take this one.
