### ISSUE TITLE
Loging-in form indiscretion

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1475]
### Is your feature request related to a problem?

No. Just a consideration.

### What is the feature?

Currently, the `autocomplete="username"` attribute set within the User Name input of the login page do not give suffisant security principles due to the autofocus which display the list of previous loging-in credentials (a kind of indiscretion in a share working environnement and/or on a sharing computer).

Maybe we could consider changed this attibute property by this one, instead:

`autocomplete="off"` ¹

Note: ¹ this is the way most of social networks serve their connexion forms.

**Comment by cara-tm** [comment]
Sample:

![Login page](https://i.ibb.co/Bjjsjgq/login.png")

**Comment by Bloke** [comment]
I can appreciate this is not ideal on shared computers, but is handy on individual browsers. I'm fine with changing it, though.

Side note: would this affect people who choose to 'remember' their settings in the browser's password manager? When you start to type in your username and the browsers offers to autocomplete the user name and password from its internal database, I mean? Is that a separate system from 'HTML autocomplete'?

**Comment by phiw13** [comment]
> Note: In most modern browsers, setting autocomplete to "off" will not prevent a password manager from asking the user if they would like to save username and password information, or from automatically filling in those values in a site's login form. 

from MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

In theory, this means Keychain, Firefox password manager, Last-pass, 1password and friends should be able to fill in the username & password no matter what. I am not sure how Patrick is getting into this situation. Does his copy of Firefox remembers all those user/pass combos? That seems odd, I thought for those specific fields Firefox only remembers/suggests/fills the values if the password manager stores them.

**Comment by phiw13** [comment]
BTW - as viewed with Firefox 74.latest
* `twitter.com/login` -> `auto-complete="on"`
* `github.com/login` -> `autocomplete="username"`

**Comment by philwareham** [comment]
Assign this to me - although I won't be able to do much in the short-term, I'm doing emergency e-commerce work for a client over next few days.

**Comment by cara-tm** [comment]
Other situation from Google Chromium for Devs no credentials reminder on first login; second access with the first letter set into the Name field:

![Google Chrome for Devs](https://i.ibb.co/JnMXpNF/login.png)

**Comment by phiw13** [comment]
Oddly in my mind, I can reproduce that with Firefox :-(. But, as far as I can tell, if I quit the browser the value is forgotten (unless I did configure something…).

Safari 12 and 13 do *not* fill the field in that scenario. I really thought and expected that was what Firefox would do too.

@cara-tm 
can you reproduce that across sessions (e.g. 1/ closing browser window and opening new window 2/ quitting the browser and starting a new session)?

**Comment by cara-tm** [comment]
First test: Google Chromium for Devs (full cache clearing), open first window then close it; open a new window (pic 1).

Second test: Google Chromium for Devs new session (full cache clearing) (pic 2) 

![First Test](https://i.ibb.co/JQpyfKp/login.png)

![Second Test](https://i.ibb.co/bRdgtRj/login2.png)

**Comment by philwareham** [comment]
The login form is working as it should, accessibility guidelines state you should never explicitly state `autocomplete="off"` anyway and I did extensive research on this very topic when I introduced this attribute throughout the core forms a few months ago.

See https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields for some reference.

Therefore I see no reason to change this behaviour. Closing.
