### ISSUE TITLE
Renaming dev theme assets goes wonky

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1477]
**Steps to reproduce**

* Install vanilla 4.8.0
* Themes panel: duplicate 4.8.0 theme. Name+label it "next-site".
* Sections panel: Select 'articles' Section.
* Multi-edit: Change theme/page/style.
* Choose next-site theme. Leave Page and Style dropdowns empty. Confirm.

Result: split live/dev lanes on the articles Section. Shared asset names because both live and dev are using the same (live) asset.

At this point, there's no way to jump to the dev asset for editing, because it doesn't exist. This can be confirmed via MySQL: the dev_page column is still empty.

* Edit the 'articles' Section again
* Multi-edit: Change theme/page/style.
* Choose next-site theme. Select 'archive' and Style dropdowns empty. Confirm.
 
Result: split live/dev lanes on the articles Section. Shared asset names because the names are identical even though live and dev are using different assets.  This can be confirmed via MySQL: the dev_page column contains 'archive'.

At this point, there's still no way to jump to the dev asset for editing, because there's only one entry in the Pages column.

* Click to edit the 'archive' Page. Note this is the Four-Point-Eight theme.
* Switch the Theme selector to 'next-site'.
* Select 'archive' Page to edit if not already selected.
* Rename 'archive' to 'all-articles' and Save changes.
* Visit Sections panel.

Result: split live/dev lanes on the articles Section. Live asset is 'all-articles' (!) Dev asset is 'archive' (!) This can be confirmed via MySQL: the page column contains 'all-articles' and dev_page column contains 'archive'.

It appears that renaming any dev asset from an in-dev theme renames the live asset if the names are the same and renames _both_ live and dev assets if the 'dev_page' asset is unset. This can be confirmed:

* Visit the Pages panel.
* Select the 'next-site' theme from the dropdown.
* Rename the 'default' Page to 'front-page'. Save.
* Visit the Sections panel.

Result: The Default section has two lanes but:

1) A single, shared Theme name (Four Point Eight).
2) Two Pages, _both_ called 'front-page' and the lower one indicated as 'Missing'.

**Expected result**

Renaming dev assets affects dev themes. Special consideration should be made when a dev theme is yet to be assigned: the dev_skin should be updated in the txp_section table too, imo.

**Comment by Bloke** [comment]
@bloatware Can you replicate this, btw? Or is this expected behaviour? If not, I can look into fixing it if you don't have time.

**Comment by bloatware** [comment]
@Bloke sorry, switching to remote work is taking all my time. Please do whatever you deem fit.

**Comment by Bloke** [comment]
I _think_ the three commits 943a9c4, 73d692b and 02982d29 address this issue. What happens now is:

a) If you rename a Page or Stylesheet from their respective panels, any dev assets also update.
b) When you change theme/page/style to include a dev asset, the lane opens up and shows you all the dev assets so you can jump directly to them, if they differ from the live situation (or are missing).

Please everyone give this a whirl and see how it behaves.
