### ISSUE TITLE
Regression? yyyy/mm URLs return 404

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1478]
### Expected behaviour

URLs of the format example.org/2020/03 and example.org/2020/03/11 should trigger an article list of all articles in the given month or day, respectively. They did this in versions prior to 4.8.0.

### Actual behaviour

URLs of either format trigger a 404.

### Steps to reproduce

* On a default installation, create some articles in a section with URL scheme year/month/day/title and use a spread of dates in various months.
* Visit the front-end of one of the articles to verify it can be seen.
* Remove the /title or the /day/title portion of the URL and submit.

#### Additional information

Textpattern version: 4.8.0

Is this expected behaviour due to the changes in the URL handler? Previously, these URLs returned article lists so it feels like a regression, but maybe it's not possible now to handle these. I think it was perhaps a hack or undocumented feature anyway, not sure if it was ever official, but we used this feature in TXP Mag extensively, and it's really useful.

It begs the question: what _should_ we do? Things to consider:

* What if there are multiple sections with the year/month/day/title URL scheme? Does it mix the articles from those sections only? From all sections, irrespective of url scheme?
* Should example.org/section/year/month/ only return articles in the given month from the selected section? And example.org/year/month/ from all sections? Or only from sections with the matching URL scheme? Or neither?
* Pagination of /yyyym/m and /yyyy/mm/dd article lists.

**Comment by bloatware** [comment]
Formally, it's not a regression because `/yyyy/mm/` links continue to work if `year_month_day` is the *only* URL scheme used on the site. But since one can define *multiple* (i.e. per section) schemes in 4.8, txp has to guess which section is being accessed in this case, and it has no mean to distinguish between `2020` section and `2020` year. We could consider numeric values as date filters, but it would be not fully bwc.

**Comment by Bloke** [comment]
Okay, yeah, I see how that can be a problem. Must admit I didn't try it with an all y/m/d site.

Can we handle it this way:

* If section exists, use that. It trumps all. And use its per-section URL scheme, if set, to guide decisions on the rest of the URL.
* If section doesn't exist and it's all numeric, presume it's y/m.

Any issue with that approach?

**Comment by bloatware** [comment]
No serious issue imo, just inconsistency.

**Comment by Bloke** [comment]
Cool. We can add it to the other "problems" and inconsistencies:

* If you make a section name of the same name as a physical file/directory in site root, it overrides any section of the same name, and renders your articles in those sections useless.
* If you make a section called 'author' or 'category' or any other reserved top-level hook, your articles won't show up. You'll get a 404. But your /{hook} URLs will continue to work as normal.

All we're saying here is that if you make a numeric section name of exactly 4 digits in length, it overrides the built-in year/month handler. Otherwise, any URL of the format /yyyy or /yyyy/mm or /yyyy/mm/dd or /yyyy/mm/dd/title will trigger ymd permlink mode. I don't really see much of an issue with that.

The only question I have in addition to this is whether we allow /section/yyyy/mm et al to _only_ return articles in the given year, month, day from the given section. Haven't quite got it straight in my head yet what should happen if you visit:

example.org/yyyy/
or
example.org/yyyy/mm

In 4.7.3 it returned all articles from all sections that had posted dates in the given year/month. Under 4.8.0 with our per-section permlink schemes, do we still return all articles? Or only articles from sections with the year/month/day permlink scheme?

Do you have any thoughts on what we could/should do?

**Comment by bloatware** [comment]
Add here `id_title` scheme and people who remove trailing slashes... txp needs some discipline.

**Comment by Bloke** [comment]
Is this addressed or do we still need to tinker? Are the changes in f541eef1 sensible and reliable?

**Comment by bloatware** [comment]
@Bloke I will try to find some time this weekend. Can not do thorough testing right now, sorry.

**Comment by Bloke** [comment]
I've reverted part of f541eef to get rid of the partial title matching. Doesn't seem to have had any adverse effect on the operation of y/m/d URLs so I'm happy this is resolved. If nobody else finds any bugs I'll close it.

**Comment by Bloke** [comment]
This is still misbehaving for me. Scenario:

1) Fresh install of 4.8.1-dev.
2) Populate some articles in various months/days as test data.
3) Set default permlink scheme to /section/title.
4) Ensure all sections are using default scheme.
5) Visit front end, browse articles fine.
6) Construct a URL of the form example.org/2020/05/ (or whatever month your articles are in).

Expected result: list of articles in that year/month.
Actual result: 404.

Doesn't matter if the URL ends with a slash or not - although administrators should ensure all 'list' URLs end with one for disambiguation purposes.

Now:

7) Alter one section - any section - to use a different URL scheme. Any scheme other than the same one as default.
8) Visit front end, browse articles fine.
9) Construct a URL of the form example.org/2020/05/ (or whatever month your articles are in).

Actual result: article list, as expected.

**Comment by Bloke** [comment]
Niiiice! Thank you.

**Comment by bloatware** [comment]
I guess we also need to fix pagelinks in this case, because @/2020/@ becomes @?month=2020&pg=2@, though @/2020/?pg=2@ would work too.

**Comment by Bloke** [comment]
Maybe. I also like how this still retains the /section/y/m/d support IF the section you're in is set to y/m/d permlink mode. That makes sense. So on any section, you can use

* example.org/yyyy/
* example.org/yyyy/mm or example.org/yyyy/m/
* example.org/yyyy/mm/dd/ or example.org/yyyy/m/d/
* example.org/yyyy/mm/dd/title or example.org/yyyy/m/d/title

to get a list of articles or the actual article that matches.

On a section that utilises y/m/d permlink scheme you can do all the above to get _all_ articles that match across sections but also filter by just articles in that section:

* example.org/section/yyyy/
* example.org/section/yyyy/mm or example.org/section/yyyy/m/
* example.org/section/yyyy/mm/dd/ or example.org/section/yyyy/m/d/
* example.org/section/yyyy/mm/dd/title or example.org/section/yyyy/m/d/title

Neat.
