### ISSUE TITLE
Non logical URL title pattern

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1479]
### Is your feature request related to a problem?

Not really but a kind of.

### What is the feature?

After a fresh installation of TXP 4.8, we can observe a non logical URL title scheme between the default format within the preferences panel and the default article: preferences are set on "Intercapped" format and the first default article renders an hyphenated individual URL.

**Comment by Bloke** [comment]
Good spot, thank you. I honestly thought that hyphenated was default on new installs and was surprised to see interCapped as default recently. But maybe it's always been that way and I'm just so used to seeing hyphenated I never noticed.

The code seems to imply it _should_ be hyphenated (see vendors/Textpattern/Core/DB/core.prefs and look for permlink_format: the val is '1') but for some reason it seems to be set to interCapped. I think the check in Core.php is wrong to set the default top 'null' and that's the source of the inconsistency. I'll investigate this.

**Comment by cara-tm** [comment]
Thank you.
