### ISSUE TITLE
js console error reporting

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1481]
### Is your feature request related to a problem?

Not really, just a report.

### What is the feature?

On the login-in page, due to the absence of the `lightswitch` element into the DOM, the browser console notify this message:

`TypeError: document.getElementById(...) is null`

A verification on this element is required before calling its function:

    if(null!==document.getElementById("lightswitch")){document.getElementById("lightswitch").addEventListener("click"function(t){  ...  }}

**Comment by philwareham** [comment]
This should be fixed now, thanks. Let me know if there are still problems.

**Comment by cara-tm** [comment]
Perfect!

**Comment by philwareham** [comment]
👍 - hope you are keeping well and safe.
