### ISSUE TITLE
`Uncaught TypeError: mysqli_num_rows()` in `/textpattern/lib/txplib_db.php`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1484]
On the PHP 8.0.0-dev + Percona 8.0 + Textpattern dev demo site, there's a reproducible PHP error that happens each time the auto-installer runs:

```
2020/04/15 09:00:03 [error] 5674#5674: *1698 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: mysqli_num_rows(): Argument #1 ($mysqli_result) must be of type mysqli_result, bool given in /var/www/sites/textpattern.co/php-src-dev-demo/live/textpattern/lib/txplib_db.php:871
Stack trace:
#0 /var/www/sites/textpattern.co/php-src-dev-demo/live/textpattern/lib/txplib_db.php(871): mysqli_num_rows()
#1 /var/www/sites/textpattern.co/php-src-dev-demo/live/textpattern/lib/txplib_misc.php(3246): safe_field()
#2 /var/www/sites/textpattern.co/php-src-dev-demo/live/textpattern/lib/txplib_misc.php(4195): fetch_page()
#3 /var/www/sites/textpattern.co/php-src-dev-demo/live/textpattern/publish.php(728): txp_die()
#4 /var/www/sites/textpattern.co/php-src-dev-demo/live/index.php(74): textpattern()
#5 {main}
  thrown in /var/www/sites/textpattern.co/php-src-dev-demo/live/textpattern/lib/txplib_db.php on line 871" while reading response header from upstream, client: 2a03:b0c0:3:e0::65:d001, server: php-src-dev-demo.textpattern.co, request: "GET /6386c23445637a9916781881ec804abc/?txpcleantest=1 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php-src-fpm.sock:", host: "php-src-dev-demo.textpattern.co"
```

I was in two minds to report this considering the work-in-progress-ness of PHP 8, but here we are.

Diagnostics:

```
Textpattern version: 4.8.1-dev (1179f273855a35778612d4db4f3eef93)
Last update: 2020-04-15 09:39:32/2020-04-15 09:00:02
Site URL: php-src-dev-demo.textpattern.co
Admin URL: php-src-dev-demo.textpattern.co/textpattern
Document root: /var/www/sites/textpattern.co/php-src-dev-demo/live
$path_to_site: /var/www/sites/textpattern.co/php-src-dev-demo/live
Textpattern path: /var/www/sites/textpattern.co/php-src-dev-demo/live/textpattern
Article URL pattern: messy
Production status: testing
Temporary directory path: /var/www/sites/textpattern.co/php-src-dev-demo/live/textpattern/tmp
PHP version: 8.0.0-dev
GD Graphics Library: bundled (2.1.0 compatible); Supported formats: GIF, JPEG, PNG, WebP.
Server timezone: Europe/Berlin
Server local time: 2020-04-15 11:41:00
Daylight Saving Time enabled?: 0
Automatically adjust Daylight Saving Time setting?: 0
Time zone (GMT offset in seconds):  (+7200)
MySQL: 8.0.19-10 (Percona Server (GPL), Release '10', Revision 'f446c04') 
Database server time: 2020-04-15 09:41:00
Database server time offset: 0 s
Database server timezone: SYSTEM
Database session timezone: SYSTEM
Locale: C.UTF-8
Site / Admin language: en / en
Web server: nginx/1.17.10
PHP server API: fpm-fcgi
RFC 2616 headers: 0
Server OS: Linux 4.15.0-96-generic
Admin-side theme: hive 4.8.0

Pre-flight check: 
------------------------

Image directory is not writable: /var/www/sites/textpattern.co/php-src-dev-demo/live/images
File directory path is not writable: /var/www/sites/textpattern.co/php-src-dev-demo/live/files
Theme directory is not writable: /var/www/sites/textpattern.co/php-src-dev-demo/live/themes Help
------------------------
```

**Comment by Bloke** [comment]
Thanks for the report. This is probably gonna take some sleuthing to find out why it's return `false` (or, potentially, `true`) from safe_query() instead of finding the rows it expects. With that in mind ,I wonder if it's possible to hack txplib_db.php to dump some stuff out - either to the display or, more usefully I expect given this is a headless environment, to a file.

So, in your config.php please add to the end:

```define('txpdmpfile', 'some-file.txt');```

That should dump any debug info to that file the tempdir defined in the Txp installation's prefs.

Next, hack txplib_db.php by tweaking the safe_field() function around line 866 as follows:

```
    $r = safe_query($q, 1);
dmp($thing, $table, $where, $r);
    if (@mysqli_num_rows($r) > 0) {
...
```

Let it rip and see what appears in the .txt file. With luck, it'll capture a whole bunch of things, andt one of them will show the query we want to investigate. You're looking for the data being selected from txp_page I think, so squizz through the file looking for the query and then this output:

````
user_html
txp_page
name = '{some-page}' AND skin = '{some-theme}'
false
````

(that last line might be true, but I doubt it).

That should give us a clue what it's trying to query and maybe lead us to finding why that page and theme are unavailable. It could be a configuration issue, it could be that we need to be more defensive in some situations to trap error conditions.

**Comment by petecooper** [comment]
Thanks @Bloke - nice one. Given the error appears on the automated installer, I'm scratching my head on how to modify the config as the installer runs and spits it out. I'll investigate how it finds the values and see if I can shoehorn some changes in.

Post-install, I have updated the config.php and txplib_dp.php per your advice, and I'm seeing different errors outside the scope of this issue. I was sure I had raised them under separate cover, but I'm getting nowhere with my searching.

Second brain sanity check: is this worth debugging at this time seeing as PHP 8 dev is still pre-alpha release?

**Comment by Bloke** [comment]
Ah yes, you'll have to hack setup_makeConfig() in setup_lib.php to add the define() line:

```
    $config_details .=
   "define('txpdmpfile, 'your-file.txt')".nl.
    "?".">";
```

Regarding the other errors, they're probably legit as the PHP team improve/clamp down their type juggling, and it exposes our sometimes lax approach to overwriting variables of one type with another. But I'm fine if you'd rather wait for a more stable release before committing neuron cycles to it.

**Comment by petecooper** [comment]
Thanks @Bloke – much appreciated. I'm going to close this for now, given the nature of PHP development it seems premature to go digging around this soon.
