### ISSUE TITLE
Textpattern 4.8.1 release - flight plan

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1485]
We are targeting Textpattern 4.8.1 for release in May 2020.

Please update this post and subsequent replies with tasks etc as needed, assigning yourself or others where appropriate.

## Preflight

**Repo Issues**

* [`textpattern/textpattern`](https://github.com/textpattern/textpattern/milestone/13)
* [`textpattern/textpacks`](https://github.com/textpattern/textpacks/milestone/6)
* [`textpattern/textpattern.github.io`](https://github.com/textpattern/textpattern.github.io/milestone/2)

**Misc**

- [x] Outstanding tasks from https://github.com/textpattern/textpattern/issues/1449#issue-541358263

## Take Off

- [x] package up for GitHub and .com (@Bloke)
- [x] .com blog post (@petecooper and @Bloke)
- [x] update demo site (@petecooper)
- [x] forum announcement (@petecooper)
- [x] forum feedback (@petecooper)
- [x] socials (@petecooper)
- [x] tag public/admin themes with release tag (@philwareham)
- [x] tag Textpacks and Pophelps with release tag (@philwareham)

## After Landing

- [x] decide on whether to branch for `4.9` release (see https://github.com/textpattern/textpattern/issues/1486)

**Comment by Bloke** [comment]
I think we still need to nail down the issue that causes smd_tags and tru_tags (and probably gbp_permanent_links if it even still works) from falling apart under some circumstances. Having people resort to adding .htaccess rules to circumvent a URL interpreting issue is unacceptable, imo.

**Comment by petecooper** [comment]
@Bloke - can you update the OP with an appropriate task and a link to the issue, please?

**Comment by bloatware** [comment]
@Bloke did the direct (not via callback) function call on early (order<5) plugin load not help?

The idea was to avoid unnecessary includes/strings/plugin load when the site is not modified and finally just sends a 304. Jointly with some server side shared cache this would turn txp into a nearly SSG.

The cost is that plugins that need to intervene before `handle_lastmod()` call have not all txp functions/strings at their disposal, but I hoped they could be easily patched.

**Comment by Bloke** [comment]
@bloatware Sort of. It works as long as all your sections use the default permlink scheme. Say, you make three sections:

* 'tags' (default permlink scheme, and assigned to smd_tags as its handler section)
* 'articles' (regular stuff, default permlink scheme)
* 'events' (set to yyy/mm/dd permlink scheme)

'default' of course uses the prefs permlink scheme (which in this case is /article/title).

Under that situation, the plugin won't return any /tags/article/tag-name results. Just 404s on tag pages. If you set the 'events' section back to the default scheme, it works fine.

It seems it's something to do with `$permlink_modes`or `$custom_modes` in publish.php. Dumping the permlink_modes to screen shows that 'default' is `section_title`, the others are empty strings. Thus custom_modes is empty, and it doesn't try to guess the article.

But if you set a custom mode for the events section, it triggers the check for the article guessing routine, which fails and thus triggers a 404 before the plugin has a chance to do anything further.

It seems that if you alter the default (prefs-set) permlink scheme to match one of your custom-assigned section schemes, the  plugin behaves. But if you set one or more sections to a _different_ scheme than the one in prefs, the plugin breaks.

Does that help at all tracking this down?

**Comment by philwareham** [comment]
Note I'll need to bring across all the latest translations on Crowdin before we do the 4.8.1 release. Not been on there for a few weeks due to work commitments so there will probably be some admin and cleanup to do which takes me a few hours. Will get back to you by end of week to let you know how/if I've got on.

**Comment by bloatware** [comment]
@Bloke ah, ok, it's scheme detection related. Will check, thanks.

**Comment by Bloke** [comment]
@philwareham Nice, thanks.

@bloatware Thank you.

Can anyone please write a one/two liner in HISTORY.txt to cover the changes in 7d74c5c5 and a78cd708. Not quite sure what these changes fix as the commit messages are a little sparse! :)

**Comment by petecooper** [comment]
>Can anyone please write a one/two liner in HISTORY.txt to cover

```
* Some magical and mysterious @bloatware shiz. You don't need to know. It's better if you don't. Just enjoy the ride.
```

(but obviously formatted for 80 chars)

**Comment by petecooper** [comment]
@Bloke - I've had a few caffeinated passes through `HISTORY.txt` to tidy and format, would appreciate a second pair of eyes if I've misunderstood anything. No urgency.

**Comment by Bloke** [comment]
@petecooper That's perfect, thanks.

> Some magical and mysterious @bloatware shiz. You don't need to know. It's better if you don't. Just enjoy the ride.

:)

**Comment by Bloke** [comment]
Further research has indicated that `smd_tags_url_handler()` is trampling on the REQUEST_URI when it tries to detect the url scheme. This results in it blanking out a couple of url components (and there's a comment in the code that says '// Drop back to section list mode' so I must have done it for a reason at the time).

The behaviour after that point is still the same, so maybe this has nothing to do with it but I wonder if the plugin needs to be taught about the new URL schemes too? It blindly assumes that anything with 3 component is section/id/title, which is not the case.

**Comment by Bloke** [comment]
Debating opening a separate issue for the smd_tags/tru_tags thing. It's unclear whether the URL handler functions in the plugins themselves could trick core into NOT triggering its 'guess article' routine. If so, the problem goes away.

That would of course require modifying both plugins. Easy for smd_tags, which is still supported until core gets tagging capability, but I'm not sure the status of Nathan's involvement with tru_tags any more.

**Comment by philwareham** [comment]
Latest translations are now in the repo.

**Comment by Bloke** [comment]
Nice one @philwareham, thanks.

**Comment by petecooper** [comment]
@Bloke - high level, what's your take on current 4.8.1 release progress, please? Do issues mentioned in https://github.com/textpattern/textpattern/issues/1485#issuecomment-627370441 and https://github.com/textpattern/textpattern/issues/1485#issuecomment-627022650 register as blockers for release?

**Comment by Bloke** [comment]
I think so. I'm struggling to find a neat way to bypass/fix it. Hoping @bloatware has some inspiration.

**Comment by philwareham** [comment]
Any update on 4.8.1 release? I may have some quieter days in about a week and a half time while clients plan out the rest of year so I'd be keen to work on a few 4.9 bits during that time (e.g. CSS improvements by dropping IE11 and hopefully starting to use Stef's new widget builder code).

**Comment by philwareham** [comment]
Maybe I'll even work on the plugins site again. Really need to finish that now.

**Comment by Bloke** [comment]
Just investigating a weird thing with y/md/ URLs. Otherwise, I'm good to go.

**Comment by bloatware** [comment]
A week should suffice for what I'm testing (`<txp:else />` in shortcodes). Maybe also few tweaks to accommodate early loaded plugins like `smd_tags`.

**Comment by philwareham** [comment]
Perfect! Thanks guys.

**Comment by Bloke** [comment]
Note to selves: Chase [RPC functionality report](https://forum.textpattern.com/viewtopic.php?id=50753) and fix or remove mention in history.txt.

**Comment by philwareham** [comment]
It's a go from me, whenever you are ready. Latest translations just added.

**Comment by petecooper** [comment]
@philwareham - are we bundling up pophelps and/or textpacks for 4.8? See https://github.com/textpattern/textpattern/issues/1449#issue-541358263 for links

**Comment by philwareham** [comment]
Oh, ok I have overlooked that last two times. Can do this later this afternoon - just going out now.

**Comment by philwareham** [comment]
To be honest I’m not sure I need to do that any more. Latest Crowdin allows me to map downloads direct from there with correct file names. Will probably update .com site with this info. Doesn’t affect release though.

**Comment by Bloke** [comment]
Good for me. I'll make a local bundle and test a few upgrades. Anyone else who fancies doing likewise on the current codebase, feel free. Fresh installs are tested every three hours from the demo server, though I might do a local test just to check manual setup.

I think history.txt is up to date. Anyone want dibs on the .com blog post or shall I do it?

**Comment by bloatware** [comment]
@Bloke is `smd_tags` working now? I'd like to test just few tweaks to make its life easier.

**Comment by Bloke** [comment]
Seems to be working with the [latest code on GitHub](https://github.com/Bloke/smd_tags), but if you have anything to make it simpler then by all means add it and I'll test.

**Comment by philwareham** [comment]
Themes have all been tagged with a 4.8.1 release, as have language files. Over to you!

**Comment by petecooper** [comment]
>Anyone want dibs on the .com blog post or shall I do it?

@Bloke - I'm just in from a very early start work day, have you started on this? If not, dibs.

**Comment by Bloke** [comment]
Haven't done it yet. Just waiting to see what @bloatware does before I start bundling and testing. All yours if you want it.

**Comment by petecooper** [comment]
@Bloke - cool, I'll start at 5pm local time, need to unpack my brain from the day. Will update OP.

**Comment by petecooper** [comment]
OK, first pass of .com post done (see 427), will need second pair of eyes for the main pull quote, so please have at. I will get some food (not eaten in 24 hours) and check over again with fresh eyes.

**Comment by Bloke** [comment]
@petecooper Given it a once over. Lovely work, thank you.

**Comment by petecooper** [comment]
@Bloke - lovely, appreciate your eyes and brain meats on that. Standing by to bump demo to 4.8.1 on your command. I'm watching commits and release Atom feeds so should get it pretty quickly, will update OP when done.

**Comment by bloatware** [comment]
Just an hour, please.

**Comment by Bloke** [comment]
No probs.

**Comment by bloatware** [comment]
Ok, now `smd_tags` should be able to bypass section detection by setting global `$pretext['s']`. It can be done as before on `pretext` callback and you don't have to alter `REQUEST_URI | QUERY_STRING`.

**Comment by petecooper** [comment]
@bloatware @Bloke - what's the consensus, sirs? Are we ready?

**Comment by Bloke** [comment]
Sorry, got waylaid. I'm going to pull Oleg's changes into the release and see what they do. Depending how far I get, I might bundle the lot up as a final release tonight, or it might be the morning.

**Comment by Bloke** [comment]
Txp 4.8.1 all built and released. The blog post on .com is live. Social and forum can wait until whoever wakes up first. It won't be me... **yawns** :)

Congratulations everyone. Thank you for all your hard work on this mot excellent release.

**Comment by petecooper** [comment]
Amazing! I think we can wrap this issue up, only outstanding task relates to a decision on whether and when we branch for 4.9, and that deserves its own thread for clarity.

**Comment by philwareham** [comment]
Thanks guys, looks like Stef had a late night! Regarding 4.9 I'd like to branch now so that we can start on the planned changes ASAP. I can't foresee any major need for a 4.8.2 (unless some bugs appear of course, but we can do those in the branch).

**Comment by petecooper** [comment]
I'm +1 with @philwareham on this - branch now and make a dent in the to-do list.

**Comment by Bloke** [comment]
dev is now for 4.9.0. I've created a 4.8.2 branch just in case we need to backport any bug fixes there. Tally forth towards 4.9.0...!

**Comment by petecooper** [comment]
4.9 branched, OP fulfilled, _now_ I'm closing. Thanks for flying Air Textpattern.
