### ISSUE TITLE
Drop IE11 during Textpattern 4.9 dev cycle

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1486]
Since Textpattern 4.9 is a few months off release, we should consider dropping support for IE11 during this phase (after 4.8.1 release and possible branch).

This gives us some modernisation options, including:

1. Update our JavaScript to full ES6 features where appropriate.
2. CSS improvements (variables, filters, maths, etc.)
3. HTML5.1 elements, such as disclosure boxes, see https://github.com/textpattern/textpattern/issues/1247

**Comment by petecooper** [comment]
I've gone back and forth on this, knowing that a sizeable chunk of corporate computers are still running Win7+IE11, and likely will be for some time, but given their admins are averse to upgrading, any intranet instances could simply be pegged at 4.8.

So, +1 from me, too.

**Comment by petecooper** [comment]
Addendum: if this is broadly agreed, we should do the decent thing and inform people officially sooner rather than later. There appears to be an increase in interest around release time, especially 'big' releases, and the more notice we can give folks, the better.

**Comment by petecooper** [comment]
Do we need to take this to the forum / socials, or is that asking for trouble?

For completeness - @bloatware: are you Y or N on dropping support for Internet Explorer 11?

**Comment by Bloke** [comment]
I nearly added a line item to README.md in the section about future system requirements, but that's more about what we plan to support, not what we plan to *not* support, so it didn't seem to fit there. Didn't want to get into the "list of browsers we support" thing.

**Comment by petecooper** [comment]
@Bloke - I'm inclined to agree with you on the support stance, and I've seen similar numbers for usage.

A short blog post about intended 4.9 sys reqs changes would be sensible, especially since we're going for PHP 5.6 as a minimum (notable since it's the only pre-PHP 7 version supported), and we can work it into that easily enough.

**Comment by bloatware** [comment]
@petecooper personally I don't care about IE11 as long as txp works in FF. If the stats are 5% I don't think someone will complain if we drop it.

**Comment by petecooper** [comment]
Alright, cool. I'll start putting some words together for a future .com blog post, will send details over for your edits as and when. Closing for now, given agreement to drop IE11 support – _not_ an indication that the work is done.
