### ISSUE TITLE
RFC: omit or change article syndication `generator` entry

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1488]
### Is your feature request related to a problem?

Nope.

### What is the feature?

A config option (`config.php` probably preferable to UI) to set the `generator` field in syndication feeds to something that's not the CMS, or omit it entirely.

Atom and RSS feeds provide the CMS name, and the version. They're not the _only_ way of determining what a site runs, but it's an easy way considering many (or perhaps most) admins won't disable syndication.

Some options:

* omit `generator` entirely
* set `generator` to `site_name`, `site_slogan` or arbitrary plain text

I took the default 4.8.0 RSS and Atom output, and the above options are all valid according to the W3C validator: `generator` is optional, and as long as `site_name` / `site_slogan` avoid exotic characters, it looks fine.

**Comment by Bloke** [comment]
Awww, *sulks* that's my favourite way of telling which version someone's running!

If people think this is worthy and it aids in some semblance of security-through-obscurity then we can do it. That leaves just opening textpattern.js or checksums.txt or the source code of the login screen as the only reasonably accurate methods of version discovery.

**Comment by petecooper** [comment]
>Awww... sulks ... that's my favourite way of telling which version someone's running!

Yep! Same. Mixed emotions. Though `checksums.txt` is often more available, since barely anyone blocks access from outside. I know we've both gone back and forth on this over the years, especially with security through obscurity as you say. I intended this issue to be an RFC, I will update the title to clarify.

**Comment by petecooper** [comment]
Edge case. Self-closing. Can resurrect if and when need arises.
