### ISSUE TITLE
Version number in `package.json` in `master`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1491]
I'm investigating ways to further automate the demo sites (yay for front loading work in the cause of laziness). Please look at this file, note the branch is `master`:

https://github.com/textpattern/textpattern/blob/master/package.json

Given that `master` is essentially the production release, should the version in the above file be `4.8.1`? I'm not completely _au fait_ with the release procedure and branching, so I don't know if I'm missing something, nor am I being pernickety. Would appreciate clarification. Thank you.

**Comment by philwareham** [comment]
Yes it should be 4.9.0-dev

**Comment by petecooper** [comment]
>Yes it should be 4.9.0-dev

I must have wires crossed - I thought `dev` was `4.9.0-dev`…`master` should be the same?

**Comment by philwareham** [comment]
Oh sorry I misread the issue. The 4.8.1 branch can have 4.8.2-dev now I guess (even though there may never be an actual release)

**Comment by Bloke** [comment]
I honestly don't know what that file is for. My understanding is that the version number in there should match the branch.

**Comment by Bloke** [comment]
But we shouldn't tinker with it post-release or it makes merges tricky later. Best leave it for now if it's wrong.

**Comment by petecooper** [comment]
Thanks @Bloke - I was wary of mucking with it given the importance of `master`. `dev` and `4.8.2` are fine, and if the toolbelt has a note then I can safely close this.

**Comment by philwareham** [comment]
It's not wrong. The package.json file is mainly for my front end dev work on Textpattern via NPM - it only has a version number in it because NPM expects a version number in such files. The wrong number has no affect on Textpattern releases (we don't bundle Textpattern as an NPM package obviously).
