### ISSUE TITLE
Allow plugins dir to be moved

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1494]
With the advent of loading plugins from disk, should we allow the endpoint to be moved via a pref that defines the plugins file path? This would permit people to stash plugins outside of docroot.

Upside: more security.

Downside: any plugins that need public-side resources such as JS/CSS can't just "include" them using the path, they'd have to read the contents and inject (I think). Possibly an "include file" routine in the Plugin class could help, although it might need messy syntax under the hood.

If we do decide it's a good idea, some concerns:

* On changing the value, do we just set it in prefs and then start building a new cache at the given location? Or try and move (rename) the current cache?
* Leaving the old cache behind could be confusing. But moving it means changing the way prefs are handled as it needs to do some 'additional logic' for that particular value on save. Needs its own prefs callback, I guess.
* What if the new location isn't writable when the value is set? Do we forbid prefs to be saved until it's fixed? Allow it anyway, but the admin will find out when navigating to another tab that the plugins cache is unwritable, potentially causing admin and public-side breakage?
* What about the current plugin_cache_dir? Does it still have a purpose? Is it confusing to have two? What if someone sets the plugins and plugin_cache endpoints the same?

Or do we just leave it alone, hard-coded? Convention over configuration.

EDIT: One thing at the moment, btw, is that it is used in multiple places as a 'magic value' so even if we decide not to expose the path to admins, we could still do with setting a central constant and using that.

**Comment by petecooper** [comment]
Would a symlink do the job?

**Comment by Bloke** [comment]
In *nix, yes. Windows, not so.

**Comment by philwareham** [comment]
Hi. I seem to have a vague memory of @bloatware talking about moving the plugins directory to public root (and possibly allowing it to be moved wherever). I'm not sure where I read that though.

**Comment by Bloke** [comment]
You know what, I'm going to close this. I've done the 'get rid of magic value' thing so let's leave it. I don't think it's a big enough security hole to have this directory exposed under docroot given the untrusted nature of plugin code.

Since we only include code that's specifically enabled in the Plugins panel by administrators, the only thing to worry about is if people link directly to other assets bundled with the plugin. And that's down to them, not us.

**Comment by bloatware** [comment]
We should strongly suggest that they consult and use `.htaccess-dist` supplied within `plugins` dir.
