### ISSUE TITLE
Possible bug when replacing an image

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1500]
### Expected behaviour

No bug.

### Actual behaviour

Try to replace a png file format image by a jpg one into the "Image" panel served by smd-thumbnail: you'll got a white page with javascript code into it.

To be confirmed by Devs.

### Steps to reproduce

See above.

#### Additional information

Textpattern version: 4.8.1

Web server vendor and version: Linux 4.18.0-147.3.1.el7h.lve.1.x86_64, Apache, litespeed.

Database server vendor and version: MySQL: 5.5.5-10.3.23-MariaDB.

PHP version: PHP 7.2.31.

**Comment by Bloke** [comment]
I can't confirm this on 4.8.1, with or without smd_thumbnail installed.

But do you happen to have com_article_image installed? Until [this commit](https://github.com/textpattern/com_article_image/commit/7040182d8a135037a410be6fe2dcd9403ac2d89a) the other day, the plugin triggered erroneously on the image edit step, which caused a white screen + JavaScript splurge to be dumped to the screen.

**Comment by cara-tm** [comment]
Good point, Stef!

com_article_image installed, too.
