### ISSUE TITLE
Custom styles files for admin themes

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1502]
### Is your feature request related to a problem?

No. Just a suggestion.

### What is the feature?

It's a fact: the entire content of the `custom-example.css` file is commented out. Why not include it by default in the `config.php`: no more need to configure it, keeping the user the ability to overwrite it with a new one if necessary. Rename this file to `custom.css` could be a proposal.

**Comment by Bloke** [comment]
Because if we rename it to `custom.css` then, on upgrade in future, that file will overwrite the one on someone's site, obliterating any custom rules applied to the site.

**Comment by philwareham** [comment]
Yes, this was designed as Stef's says so that there was less risk of accidentally overwriting your own `custom.css` (and `custom.js`) on upgrades. Don't really see a reason to change that behaviour.

**Comment by cara-tm** [comment]
Ok. Fine: I understand.
