### ISSUE TITLE
Section specific search

### ISSUE THREAD

**Issue by colak** [textpattern/textpattern#1503]
### Expected behaviour

Section specific search should return articles from the specific section
 
### Actual behaviour

Section specific search returns articles from all sections. 

### Steps to reproduce

In the demo site:

1. Create a section called Test
2. Create a new article and in the body write tutorials and allocate that article in the test section.
3. The following should have returned just the one article in the test section but it returns both existing articles: https://release-demo.textpattern.co/?m=any&q=tutorials&s=test

#### Additional information

Textpattern version: 4.8.1

Web server vendor and version: tested on the demo site and on neme

Database server vendor and version: tested on the demo site and on neme

PHP version: tested on the demo site and on neme

**Comment by petecooper** [comment]
Tagging https://forum.textpattern.com/viewtopic.php?id=50802 for discussion reference.

**Comment by bloatware** [comment]
Please test if `<txp:article searchall="0" />` solves the problem.

**Comment by Bloke** [comment]
@colak Is this "fixed" by using Oleg's suggestion? If so, please close.

**Comment by colak** [comment]
I'm still testing it. I'm yet to get section specific results but I'm sure that I am doing something wrong!

**Comment by cara-tm** [comment]
@colak: Oleg's solution works fine, I'm using it without any troubles.

**Comment by bloatware** [comment]
There seems to be one quirk though: `searchall="0"` on home page does not respect `Searchable` section setting.

**Comment by petecooper** [comment]
@bloatware @Bloke - given https://github.com/textpattern/textpattern/issues/1503#issuecomment-661026362 is it viable to resolve for 4.8.2 or defer?

**Comment by colak** [comment]
We can defer it if it is difficult. No pressure from here. @cara-tm can you post a url demonstrating that search? Id does not need to be a real one. I'm interested in its structure.

**Comment by cara-tm** [comment]
@colak: see my latest project (shown in the forum), the `ebooks` page retrieves the searchs for only this page.

**Comment by colak** [comment]
Hi Patrick, It does indeed appear to be working in your site, but looking for "Définitions" in the default section does not produce any results. I'm still struggling with this but admittedly, i do not lose sleep over it.

**Comment by cara-tm** [comment]
Hi Yiannis.

"Définitions" don't occur in any articles. So you've got no results.

If you're looking for these terms: "jalousie" or "naturalisme", you'll got the expected results

https://editions-du-26-octobre.com/catalogue-general/

**Comment by petecooper** [comment]
Bumping this as part of issue housekeeping.

@colak @cara-tm - what's the current status from your side, please? Thank you.

**Comment by colak** [comment]
Not working for me:(

**Comment by cara-tm** [comment]
For your interest and feedback:

Thanks a lot Devs 👍, search into individual pages is much better now (I don't know exactly what's your changes): I'm currently test the current dev branch (4.8.5-dev) on an in production website (see link above) and noticed better results.

**Comment by cara-tm** [comment]
...But sure, it's currently pretty difficult to use sections specific search and global search within an entire website.

**Comment by Bloke** [comment]
> it's currently pretty difficult to use sections specific search and global search within an entire website.

Care to elaborate and perhaps suggest some improvements or ideas we could explore? Do the tag attributes need to change for the search_input? Do we need to tweak or introduce some settings in the admin side?

**Comment by bloatware** [comment]
Revisiting this issue, I'd suggest that we switch the default `searchall` value from `1` to `0`, so `?s=test&q=tutorials` would restrict the search to `test` section by default. This would be consistent with how it currently works for, say, categories: `?c=test&q=tutorials`.

Though it's not bwc, I don't really see a use case for redirecting *all* search results output to some particular section page via `<txp:search_input />` tag.
