### ISSUE TITLE
Theme importation and post creation of custom type forms

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1504]
### Expected behaviour

No warning message.

### Actual behaviour

See below "Steps to reproduce".

### Steps to reproduce

Install a fresh new Textpattern version; upload a theme (with different form types: i.e. javascript, stylesheets, svg etc.); create all needed form types within the "Advanced config" preferences panel; visit the "Form" panel a popup warning message appears:

`Warning "syntax error, unexpected end of file, expecting TC_DOLLAR_CURLY or TC_QUOTED_STRING or '"' in Unknown on line 15
".`

EDIT: <del>But I found a new behavior: try to delete the theme (after all custom type forms creation), a warning TXP message says some sections can't be deleted; visit le form panel: all is restaured! 😜</del>

#### Additional information

Textpattern version: latest 4.8.1.

Web server vendor and version: Local server (XAMPP latest) on PC, Apache/2.4.43 (Win64) OpenSSL/1.1.1g, Server OS: Windows NT 10.0.

Database server vendor and version: 5.5.5-10.4.13-MariaDB (mariadb.org binary distribution)

PHP version: 7.4.7

Browser: Firefox PC (latest).

**Comment by bloatware** [comment]
Can not reproduce.

**Comment by Bloke** [comment]
Me neither. Could you please share the theme you're uploading that's causing this behaviour?

**Comment by cara-tm** [comment]
Ok. The good process consists to create first all needed form types required by a theme. Don't know if it is possible : due to the fact we can change themes, a new config file could be exported on the server with the theme in order to reflect all these custom types.

**Comment by Bloke** [comment]
Yes you need form types to be in place first. I'm thinking about ways to allow import of types on theme installation.

**Comment by petecooper** [comment]
This sounds like it relates (mostly or entirely) to https://github.com/textpattern/textpattern/issues/1487

**Comment by Bloke** [comment]
Yeah, I think that covers it. If you agree @cara-tm please close this issue. But if this differs and you still think it's a bug, please provide some additional test content so we can repeat it.

**Comment by cara-tm** [comment]
Yep, It's the same but I can't close this issue (I don't have sufficient privileges).
