### ISSUE TITLE
Untranslated strings in menu from plugins loaded from cache

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1508]
### Actual behaviour

When loading a plugin from the cache_dir that uses `register_tab()`, language strings in the `[admin-side]` group are not available so the tab is rendered with an untranslated string. If the plugin is installed to the DB as a regular plugin, the string is rendered properly. All other strings that appear later on its own tab or in prefs etc are translated perfectly. It's just the menu.

Presumably, the plugin is loaded _after_ the menu is rendered? Or the [admin-side] group is not pulled in properly.

### Expected behaviour

The tab label is rendered correctly in the menu.

### Steps to reproduce

1. Download [smd_bio.php](https://github.com/Bloke/smd_bio)
2. Upload it to your nominated plugin cache directory.
3. Visit any admin tab.
4. Look at the Extensions menu bar. `smd_bio_admin_tab` is displayed. `Bio config` should be displayed instead.
5. Visit the plugin's admin panel. Note all other strings are translated correctly and read from the plugin's `$plugin['textpack']`.

#### Additional information

Textpattern version: 4.8.0+

**Comment by bloatware** [comment]
To import strings from `$plugin['textpack']`, plugins must be loaded. But on load the strings are not yet available. Chicken/egg case...

**Comment by bloatware** [comment]
I wonder whether this ever worked. An easy solution is to replace `register_tab('extensions', 'smd_bio', gTxt('smd_bio_admin_tab'))` with
``` php
register_callback(function() {
    register_tab('extensions', 'smd_bio', gTxt('smd_bio_admin_tab'));
}, 'admin_side', 'head_end');
```
but it requires plugins modification.

**Comment by Bloke** [comment]
Figured as much, thanks for checking it out. That's probably why I was scratching my head over it. No matter what I did, it didn't render.

I'm inclined to agree it never worked. I'm fine with the workaround (very inventive!). We can publicise it as "the way" if people want to ensure their admin-side plugins work from cache.

So that just leaves those little hacks to load strings in txp_auth.php. Any ideas on those?

**Comment by bloatware** [comment]
Yep, it can be fixed (kind of) in core for `register_tab()`, but I don't see how to generally enable 'onload' cached plugin strings.

Need to take a closer look at `txp_auth.php`.

**Comment by Bloke** [comment]
Loading the strings on demand each time the plugin is loaded from cache is fine. If it needs a workaround in plugins, that's cool. If it can be fixed in core without too much overhead when registering tabs, then that's fine too.

As for txp_auth, I _think_ it's to do with the JIT string loading in gTxt(), which means the static txpLang isn't available until _after_ an attempt at using `gTxt()` is made. So if you use your own L10n/Lang object prior to calling `gTxt()` for the first time, as soon as `gTxt()` is called, it sets its own Lang object up and then ignores the one you've set up already, thus (effectively) replacing any strings you've already set up because it uses its own object from that point forward.

The only way round it I could find was to fake a call to `gTxt()` first so I could then safely add strings to _its own_ L10n/Lang object afterwards (due to the reusable nature of that object via `Txp::get`).

**Comment by bloatware** [comment]
I don't like this `global $plugin` hack, but that's how plugin template is done. We should rethink it in 4.9.
