### ISSUE TITLE
Remove array_column polyfill

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1511]
Since our minimum spec now includes PHP 5.5's built-in `array_column()` function, get rid of lib/array_column.php in our repo.

Do we attempt to delete it via an update/_to_x.y.z.php? Or just remove it from the repo and let it rot on people's servers?

**Comment by philwareham** [comment]
I always replace the lib folder anyway at upgrade, so my opinion is just remove from repo.

**Comment by bloatware** [comment]
I would leave it for 4.9 to avoid bad surprises on update, since 4.8 actually works on php 5.4.

**Comment by petecooper** [comment]
>Do we attempt to delete it via an update/_to_x.y.z.php? Or just remove it from the repo and let it rot on people's servers?

Upgrade instructions currently state (emphasis mine):

> Replace the top-level index.php, css.php and .htaccess files (if Textpattern is running on an Apache or derivative web server), everything in the /rpc/ directory and *everything in the /textpattern/ directory* (except /textpattern/config.php and the /textpattern/setup/ directory) with the corresponding files in this distribution. In addition, ensure the /themes/ directory exists if it is not already there, and is writable. When uploading the /textpattern/ directory, ensure you preserve any custom files in your existing installation. Also ensure the /textpattern/plugins directory is writable.

Given that `/textpattern/lib/array_column.php` is under `/textpattern/`, the admin person should be getting rid of the old file. Do any plugins rely on it? Is that a thing? Excuse my ignorance, please.

**Comment by petecooper** [comment]
Ah, yes - delete and replace vs merge. Good point, well made.

**Comment by petecooper** [comment]
>Nobody should be reliant on that file, though, so if it stays around, no harm done.

I'm inclined to do this. Assuming there's nothing shady in there, and since it was invented here then I'm confident that's the case, I think we can remove it from here and be done. We can always revisit in a future upgrade should there be a reason to completely remove it from a server.

**Comment by petecooper** [comment]
>Nobody should be reliant on that file, though, so if it stays around, no harm done.

If we're happy to leave it, I think we can safely close this.
