### ISSUE TITLE
Add release dates to `HISTORY.txt`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1514]
I propose we (OK, I) add release dates for upcoming and historical releases to `HISTORY.txt`. It'll be a useful guide for how old a version branch is, and helpful for quick reference – currently I use the .com blog post timestamp to determine a release date, which is a bit long-winded.

Format proposed:

```
Changes in 4.8.1 (31 May 2020)

* Changed: Improved pophelp for update check status on Diagnostics panel.
* Changed: Tag builder includes new 4.8.x attributes where possible.
* Changed: Lazy load images within Images list on supported browsers.
[…]
```

Two-part issue: first, is there any historical reason why we don't do this? If not, what branch(es) shall I update if we're in favour of this, please?

Thank you.

**Comment by Bloke** [comment]
That's a great idea actually. Having release dates in there is handy if you don't mind doing it.

Just do it in the 4.8.2 branch version please and it'll get propagated when we merge it to the other branches, including master ultimately. Thank you.

**Comment by philwareham** [comment]
The release dates are correct in the GitHub releases section aren’t they? Can’t remember but I think so, if you need some data.

**Comment by philwareham** [comment]
Ah, they aren’t correct past a certain time - ignite that.

**Comment by petecooper** [comment]
Good enough. Closing.

**Comment by philwareham** [comment]
Cheers Pete, I cherry-picked this into dev branch too now.
