### ISSUE TITLE
GitHub community scoring - enable content reporting

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1517]
The repo community report has an amber light next to "Repository admins accept content reports".

https://github.com/textpattern/textpattern/community

![Screenshot 2020-07-12 at 16 48 50](https://user-images.githubusercontent.com/226578/87250840-95a86600-c45f-11ea-9817-925b7f302725.png)

It looks like this can be upgraded to a checkmark if "Accept content reports from collaborators and prior contributors" is enabled in settings:

https://docs.github.com/en/github/building-a-strong-community/managing-how-contributors-report-abuse-in-your-organizations-repository

**Comment by Bloke** [comment]
Done.

**Comment by philwareham** [comment]
Oohh, that's new. Closing now, thanks.
