### ISSUE TITLE
With selected feature lost on form save

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1518]
### Steps to reproduce

Save a Form and check few form boxes. With n selected option stays unchanged. Range selection seems affected too.

#### Additional information

Textpattern version: 4.8.2-dev

NOT READY FOR RELEASE YET

**Comment by Bloke** [comment]
Good catch!

**Comment by phiw13** [comment]
fwiw, 
1. The same problem happens on @4.9 dev@
2. The @.selected@ class is _not_ added to the selected rows
3. Variant: select some forms in the left-hand column (check-mark), then edit something however minor in the textarea and save. result: the selected items are deselected (as expected), but the multi-select widget still says “n selected”.

**Comment by bloatware** [comment]
Point 3 happens on 4.8.1 too, and probably before. We don't seem to rearm the widget on async refresh.

**Comment by Bloke** [comment]
Huh, didn't notice it failed on 4.8.1 either. Great sleuthing. So it's not those commits I highlighted earlier then. Interesting.

**Comment by bloatware** [comment]
It was partly https://github.com/textpattern/textpattern/commit/dbfd1740023542450b81ace9e81df4b9297778b4, partly some ancient bug.

**Comment by petecooper** [comment]
Works fine in my (limited) testing - good spot and fix, @bloatware!

Suggest we (i.e. someone who's not me) put an appropriate 'Fixed:' entry into `HISTORY.txt`.

**Comment by bloatware** [comment]
@petecooper thanks for testing, and agree on 'we' :-)

**Comment by Bloke** [comment]
I'll add the history entry in a bit.

**Comment by petecooper** [comment]
Have we had enough eyes on this for it be to deemed fixed, sirs?

**Comment by phiw13** [comment]
That seems to hold one well so far on the local copy of a real world site, including my point 3 above (thank you for that, I never noticed it before, but once you see it, …).

**Comment by bloatware** [comment]
The patch is not perfect, but seems to work, and I wouldn't like it to be a blocker for 4.8.2 release and 4.9 dev.
