### ISSUE TITLE
load_lang for draft previews seems broken

### ISSUE THREAD

**Issue by trenc** [textpattern/textpattern#1519]
### Expected behaviour

A preview of a draft article showing the preview showing no errors in debug mode.

### Actual behaviour

Get an error in debug an testing mode:

```
Warning "array_filter() expects parameter 1 to be array, null given"
in /textpattern/lib/txplib_misc.php at line 4796.
```
```
adminErrorHandler()
textpattern/lib/txplib_misc.php:4796 array_filter()
textpattern/vendors/Textpattern/L10n/Lang.php:599 do_list_unique()
textpattern/lib/txplib_misc.php:417 Textpattern\L10n\Lang->load()
textpattern/index.php:184 load_lang()
```

### Steps to reproduce

Create an article in draft mode, click preview.

#### Additional information

Textpattern version: 4.8.1

Web server vendor and version: Apache

Database server vendor and version: MySQL: 5.7.28-nmm1-log

PHP version: 7.4.5

**Comment by Bloke** [comment]
This should be fixed in 4.8.2, due for release in a few days all being well. Please would you be able to test it for us? Thank you.

**Comment by petecooper** [comment]
@trenc - .zip link for convenience: https://github.com/textpattern/textpattern/archive/482-recovery-bloke.zip

**Comment by trenc** [comment]
@petecooper thanks. Yes this build is working without that issue. Considering the issue as closed.
