### ISSUE TITLE
Removing all languages is possible

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1520]
### Expected behaviour

The site language should not be removable.

### Actual behaviour

It is.

### Steps to reproduce

Add some language. Select it as site language. Note that it is still removable. Remove it. Note that English becomes removable. Remove it. Enjoy the weirdness.

#### Additional information

Textpattern version: 4.8.2-dev

Web server vendor and version: all tested

Database server vendor and version: all tested

PHP version: 7

**Comment by Bloke** [comment]
Good catch. This must have been possible for a while now. Please test.

**Comment by bloatware** [comment]
@Bloke nice fix, thanks!
