### ISSUE TITLE
Suggested edit to `README.txt` - showing/hiding dot files

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1521]
I'm steering well away from PRs and direct edits given my recent transgressions and our relative closeness to release. Respectfully, if someone could review this and make the right edits, merges etc that would be greatly appreciated.

Currently, we say:

>* If you are running Textpattern on an Apache web server, ensure the top-level .htaccess file is transferred to your site. The file is hidden by default on some operating systems, including macOS. FTP clients and IDEs typically have an option to show these hidden files. Otherwise, you can temporarily show hidden files in macOS using Terminal.app - follow these instructions: https://textpattern.com/hidden-files-osx

We can tighten this up and reduce the friction a bit (final sentence):

>* If you are running Textpattern on an Apache web server, ensure the top-level .htaccess file is transferred to your site. The file is hidden by default on some operating systems, including macOS. FTP clients and IDEs typically have an option to show these hidden files. You can show or hide hidden files in macOS Finder with the Cmd + Shift + . keyboard shortcut.

Not convinced on the a11y aspects of this since it implies a keyboard combo, but I'll look into whether there's a menu option for the same thing.

Hiding dot files (Mojave dark mode):

![Screenshot 2020-07-21 at 14 20 02](https://user-images.githubusercontent.com/226578/88060732-8495de00-cb5e-11ea-899c-02720930891a.png)

Showing dot files (Mojave dark mode):

![Screenshot 2020-07-21 at 14 20 11](https://user-images.githubusercontent.com/226578/88060745-8790ce80-cb5e-11ea-9dd8-4479443cdabc.png)

**Comment by philwareham** [comment]
Amend made. Ta!

**Comment by phiw13** [comment]
@petecooper 

Just fwiw: 

1. there is no menu item to show hidden dot-files
2. the  keyboard shortcut has one benefit: there is no need for (force-)reloading to Finder.
3. there are some utilities that offer an UI to make those files visible, Marcel Bressink’s Tinkertool comes to mind.
4. in case of the command-line solution and/or Tinkertool, the need to force-reload the Finder may have unwanted side effects (loss of window view, …)
