### ISSUE TITLE
Release notes -> forum, as they are updated

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1528]
Firstly, congratulations on Textpattern 4.8.2 - I am privileged to work alongside you, and I repeatedly marvel at some of the things you cook up for this CMS. I learn so much, and also scratch my head quite a bit, which is the main reason for this issue.

I would like for us to have a bridge between changes made here and our own properties, specifically for stuff that is worthy of inclusion in `HISTORY.txt`, so there's a better understanding of what it does. My idea is essentially for an ongoing thread in Core Development where additions to the upcoming release's changes can be posted. There are numerous people who are of a non-developer persuasion who might not think to check here often. Many of these people also have access to active sites that could perhaps be wheeled out for testing (with appropriate backups etc) of features that would benefit from more testing. Think site admin rather than dev person, they know their site well and might have ways to battle test new things that haven't been thought of. These changes don't need announcements as such, so we're not going to be shouting to all and sundry too often. Perhaps a sticky thread would get the right people to be involved.

Something as succinct as the release notes entry being posted in the thread, with a succinct explanation where appropriate, would be enormously helpful. I appreciate it will involve an extra step in the workflow, but if some forumites are able to grok the details, they can write examples, explain to other people, or write docs, or whatever else…so in a fashion it might delegate some of the work down the tree to trusted people.

That's my proposal. What do you think?

**Comment by Bloke** [comment]
Great idea. Oleg started [dev news](https://forum.textpattern.com/viewtopic.php?id=50446) to be something along these lines. Maybe we could take that concept and split it into a thread per release instead? That way, feature notes are confined to the release to which they pertain.

So in the Core development forum:

* Features in 4.8.2
* Features in 4.9.0
* Features in 4.9.1
* ...

So the process would be that when a feature lands in the main branch of one of the releases, just throw a note in the relevant thread Core dev about the change to that release. Maybe an example or two to demonstrate it. Anything that deserves a bigger write-up compared with a note (e.g. the UI library, custom fields, etc), we can do as a proper .com post or three to explore things in more detail.

Is that the sort of thing you had in mind?

**Comment by petecooper** [comment]
>Is that the sort of thing you had in mind?

Actually, yeah - that's bang on what I what I was thinking. I like the granular nature of it, so rather than one monolithic thread with aaaaaaaaaaall the things in, the split approach would be better, I agree.

Nice one.

**Comment by petecooper** [comment]
Would it be appropriate for me to spin up a new thread on the forum for 4.9 notes, and tack a diversion reply on the end of @bloatware's dev news thread? If so, I'm inclined to make it clear that it's dev news and refers to an upcoming release…so perhaps calling it "Upcoming notes on 4.9" or similar. I'm open to advice on all this, obv.

**Comment by Bloke** [comment]
Absolutely. Your thread title sounds like a winner.

**Comment by philwareham** [comment]
OK, seems fine. It's just a thread, not a new forum, yes?

**Comment by petecooper** [comment]
>It's just a thread, not a new forum, yes?

Yep.

**Comment by petecooper** [comment]
Done: https://forum.textpattern.com/viewtopic.php?id=50967

Will add in diversion from Dev News and then close.
