### ISSUE TITLE
Add JSON Feed to syndication formats

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1536]
### Is your feature request related to a problem?

Nope

### What is the feature?

Consider adding JSON Feed to our article syndication functionality, since its first minor update (v1.1) has been made available.

https://jsonfeed.org/version/1.1
https://github.com/manton/JSONFeed
https://github.com/manton/JSONFeed/blob/master/pages/version/1.1.markdown (closest thing to a spec/schema)

Considerations (incomplete):

* could be achieved by a page template easily enough, should it not be deemed appropriate for core
* could also be achieved by a plugin, presumably

**Comment by petecooper** [comment]
Will refactor.

**Comment by petecooper** [comment]
Reopening.

**Comment by bloatware** [comment]
We could also go the opposite way and transform the hardcoded atom/rss feeds into external forms. This concerns files download too. Dunno if that's easy or feasible at all.

**Comment by petecooper** [comment]
Actually, that's a smart idea. I really like  that.

**Comment by petecooper** [comment]
>We could also go the opposite way and transform the hardcoded atom/rss feeds into external forms. This concerns files download too. Dunno if that's easy or feasible at all.

@Bloke - what's your overall take on this, please?

**Comment by petecooper** [comment]
FFS, what is it with me and not getting this?!

(PS: thanks @Bloke – I won't forget this now…)

**Comment by petecooper** [comment]
Covered by https://github.com/textpattern/textpattern/issues/1761, closing
