### ISSUE TITLE
Add a new 'loading' attribute on image tag(s)

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1545]
This was mentioned somewhere previously although I can't find an issue that tracks it, so opening one now.

We could add a new attribute on appropriate image tags for `loading`, whereby its would be `lazy` or `eager` (and possibly accept `auto` too, although that is the same as not specifying the attribute).

[MDN doc for reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading).

**Comment by bloatware** [comment]
@philwareham which tags are concerned, and should we check `doctype` pref (HTML5 or XHTML)?

**Comment by Bloke** [comment]
For reference:
https://forum.textpattern.com/viewtopic.php?id=50998

**Comment by Bloke** [comment]
I think adding a `loading` attribute with defaultl value 'auto' to:

* txp:images
* txp:image / txp:thumbnail (same function)
* txp:article_image

is sufficient?

**Comment by philwareham** [comment]
Ha, beat me to it! 😀

**Comment by Bloke** [comment]
True but I wouldn't worry about doctype checking. If it's omitted by default, we're covered for either doctype eventuality. And if someone adds it, they're doing it for a reason. If they're adding an attribute that isn't supported in their chosen doctype, surely that's on their head?

But if you think it's important to ignore their attribute request if the doctype doesn't support it, then I'm fine with that.

**Comment by philwareham** [comment]
It would need to be default of `null` (we don't display it). It displays when you explicitly set it with Ione of the 3 allowed options. We might as well allow someone to state `auto` as I can't see the hair in it (possibly they could override a previously set global `lazy`/`eager` I guess).

**Comment by bloatware** [comment]
So `<txp:[article_]image />` tags must inherit `loading` from their `<txp:images />` container or a globally set value by default? Should it be a pref?

**Comment by philwareham** [comment]
> Should it be a pref?

No, it needs to be granular (you can mix and match as you so wish). For example, I'd lazy load images I know are going to be roughly below the fold in a design/layout, but not others.

I think (if it's possible) `<txp:[article_]image />` should inherit from `<txp:images />` but can also individually have that attribute set too.

**Comment by Bloke** [comment]
Hmmm, ideally yes they should inherit. But does that go against a lot of our other attribute usage? I'm not sure offhand. I do that kind of thing in com-connect so if you set an attribute in the wrapper, it applies to any tags inside unless you override them on a tag-by-tag basis. Messy though, as it uses globals to pass things around

Maybe using the `loading` attribute adds it to the 'default' (self-closing) output of `<txp:images>` but if you use a form/container, you need to add it explicitly to your txp:image/thumbnail/article_image? That seems like a reasonable compromise.

**Comment by bloatware** [comment]
We do it where appropriate in core, but not so often. For example `<txp:pages />` can pass some overridable attributes (like `link`) to its children tags, via a static variable though. That's handy when a tag contains many children, which is not the case of `<txp:image />`. But the possibility to say 'from this point all images are lazy-loading unless explicitly stated otherwise' could be useful. Though potentially confusing.

**Comment by Bloke** [comment]
Ah, true. If there's precedent for it then I'm fine with passing things along as it's not too confusing.

**Comment by bloatware** [comment]
[Added](https://github.com/textpattern/textpattern/commit/313cdd1c32d832e2771115b2d8bed244753041d0) `loading` to single image tags. Not for `<txp:images />` atm, since it would be of little use anyway in this basic form.

**Comment by philwareham** [comment]
@bloatware great! Is this for all 3 of?:

* txp:image / txp:thumbnail (same function)
* txp:article_image

**Comment by bloatware** [comment]
@philwareham yep

**Comment by philwareham** [comment]
Tested and all seems to work exactly as intended - great stuff, thanks. Closing.
