### ISSUE TITLE
NTS: GitHub sponsors

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1547]
Update `README.md` to thank our GitHub sponsors. Can be deferred to after 4.8.3 or snuck in if someone fancies it.

**Comment by Bloke** [comment]
Might as well add it as part of the release process, since README.md is being checked anyway for version numbers.

**Comment by petecooper** [comment]
I'll update the readme now with a broad mention, rather than naming users - that way it's more evergreen.

(OK for me to leave branch merging to you after the 4.8.3 Merge-A-Geddon mess I made?)

**Comment by petecooper** [comment]
Done in https://github.com/textpattern/textpattern/commit/e65010e592326621ced51705a2c53975983faed2, can be improved later.
