### ISSUE TITLE
Merge conflict on HISTORY.txt

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1549]
We'll need to remerge the changes to `dev` HISTORY.txt from this commit: https://github.com/textpattern/textpattern/commit/7c42aa437b35f76fb278e407586e8d54ce1973d2 (my fault, sorry).

**Comment by Bloke** [comment]
No worries. Easy to add back in to the dev branch.

**Comment by petecooper** [comment]
more a NTS than an admission of a(nother) cock up!

**Comment by petecooper** [comment]
Done.
