### ISSUE TITLE
`.htaccess` or `.htaccess-dist` for `/files` & `/sites/site1/public/files`?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1550]
As I understand and expect it, the `/files` & `/sites/site1/public/files` directory contents _should_ be identical, comprising a single `.htaccess` or `.htaccess-dist` depending on current thinking.

The `/files` & `/sites/site1/public/files` directories currently differ. `/files` uses `.htaccess`, `/sites/site1/public/files` uses `.htaccess-dist`. In real terms, this means single-site instances on Apache and derivatives will automatically apply the conditions/rules, but on multi-site instances they are optional (as an exercise for the admin).

I think we should pick one, stick to it (perhaps from 4.9.0) _or_ if there's a reason why we're using two files, explain why, and if we have the inactive flavour, explain how to activate it, along with the ramifications.

**Comment by philwareham** [comment]
If this is the case and the rules are essential to the running of Textpattern on Apache (I've not checked), then probably `.htaccess` is the way to go - since I the install would by default be broken unless you manually renamed the `.htaccess-dist` file.

**Comment by philwareham** [comment]
It's not an essential rule (just some security for the files directory) but I've renamed it now for consistency. Thanks.
