### ISSUE TITLE
Multi-site themes directory is empty

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1551]
Given that front-side themes are now well-established, should `/sites/site1/public/themes` have content or a symlink? As it stands currently, there are empty `files` and `images` dirs, which is fine, but a front-side theme is essentially required for the display of content…and unless there's a very clever way of linking them together behind the scenes that I've missed, the admin is required to copy theme assets or symlink to an existing theme in `/files`.

From a usability point of view, we could set up two symlinks to the parent themes, and perhaps an accompanying README in `/sites/site1/public/themes` so there's at least _something_ to show styled content on the front page.

**Comment by philwareham** [comment]
Doesn't the theme get installed during setup? As it also does for non multi-site themes directory (which is also empty).

Although I'm thinking of suggesting we actually have a physical theme in the directory as off 4.9 - which gives us much more scope to have a more complicated default theme in future (i.e. one with JavaScript and fonts and other assets).

**Comment by petecooper** [comment]
>Doesn't the theme get installed during setup?

Oh, yeah - of course. Duh. Sorry.

**Comment by petecooper** [comment]
>Although I'm thinking of suggesting we actually have a physical theme in the directory as off 4.9 - which gives us much more scope to have a more complicated default theme in future (i.e. one with JavaScript and fonts and other assets).

Big +1.
