### ISSUE TITLE
Branch removal for 4.8.3 release

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1552]
As the 4.8.3 release process was the first with me at the buttons (with @Bloke on hand), I've renamed the branch that was known as `4.8.3` to `4.8.3-to-check-then-delete-if-ok`. I am pretty sure it can be deleted, but I wasn't confident enough to do it yesterday since I wasn't sure if there needed to be a do-over release for any reason. Now that successful install & upgrade reports are coming in, I think it can be safely deleted.

**Comment by philwareham** [comment]
All fine and deleted - thanks for doing the release Pete!

If we need to do a `4.8.4` release at some point we will simply branch that off of `main`.
