### ISSUE TITLE
Make override forms more useful

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1553]
Override forms are currently tied to the Article form types. That's a nice convention, but could be a little limiting if a designer wants to offer a dedicated set of overridable blocks. It potentially makes the Article group rather bloated.

With the advent of pageless sections, a "page" could be designed such that it always renders one article at a time via a single `<txp:article>` tag as normal. But that article could bring in a whole heap of other articles and stack them to 'build' the page layout. Each sub-article could have one of a number of override forms set that governs its layout.

Say, the designer made override forms called:

* no background
* colour background
* image background

When creating the article, you could pick an override form such as 'colour background' and it could be designed such that custom_1 was the colour value (or values, plural, to create a gradient. Or when we introduce unlimited custom fields, it could be a colour picker or a select list of pre-defined colour options set by the designer).

If you chose the 'image background' override form then custom_1 (or Article image) could be the image ID to display. And maybe custom_2 defined the background-size (cover, auto, contain, etc).

In this way, you could use override forms as individual building blocks to style/theme either entire articles or parts of articles (as a pageless chain) to build nice layouts that retain the power of customisability but also the power of forms to have their markup changed once and affect things site-wide.

### The Feature

Open up override forms so they are not confined to the Article type (that is simply the default).

Change the 'Allow override form' radio in Prefs to a multi-select that allows you to nominate one or more form types (possibly custom ones) to be represented in the override form dropdown?

If more than one type is defined, we then turn the 'Override form' select list on the Write panel into an optgroup dropdown, with options grouped by type. This gives designers a lot of flexibility to define and name custom override form types that give some degree of customisation to content authors, allowing them to pick and choose from stylable 'blocks' to apply to each article.

The list of available override forms still changes if the section is altered, based on the theme in use by the selected section.

EDIT: A stretch goal might be to rename 'override form' as something less scary in the UI.

**Comment by petecooper** [comment]
>A stretch goal might be to rename 'override form' as something less scary in the UI.

"Use form:"

**Comment by philwareham** [comment]
As a side-note to this. I am actually [building a theme at the moment](https://github.com/philwareham/textpattern-hive-framework) that has the concept of modules - i.e. you can choose from different article layouts/page modules/etc to build out websites quickly. i.e. a framework to build a site of your choice using pre-built components - like a basic version of Squarespace templates within Textpattern.

Still very much work in progress but the OT above would help realise that dream.

**Comment by Bloke** [comment]
I'll do this then. Seems like a winner to me.

**Comment by Bloke** [comment]
Okay, first stab at this has landed. Override forms can now be any type, selectable from Prefs>Admin area.

Note that I haven't used an `<optgroup>` to segregate them on the Write panel yet. That's hard graft and involves changing the way the forms are stored to include their type as well as skin. So let's not go there unless we see an overarching need to display them by type in the dropdown.

Should be backwards-compatible with the old radio settings. Please test.

**Comment by Bloke** [comment]
Note that this will require an update to:

* `[Prefs]` string `allow_form_override`. Ideas welcome.
* `[Article]` string `override_default_form` => 'Use form'
* 'allow_form_override' Pophelp, which is horribly outdated anyway as it mentions the 'Advanced options' on the Write panel; that hasn't been there for a while now.

Possible names for the prefs panel option now:

1) Override form types:
2) Article override form types:
3) ...

**Comment by philwareham** [comment]
I think we need to make the blank entry in the multiple `select` pref form field more obvious as to what it does, in that selecting it effectively means 'Turn off form override'.

**Comment by philwareham** [comment]
I wonder if instead you could look at the UI/UX used for the 'Automatically adjust Daylight Saving Time?' for inspiration? In that when it's turned off the subsequent pref below it is disabled.

i.e. have the original 'Allow form override' back how it was (an on/off input). And then a separate multi select pref below it for 
'Use these form types in form overrides' or similar wording.

Just my 2 pence.

**Comment by Bloke** [comment]
Hmm. Okay. That's extra JS code and two prefs for one feature. But if y'all think it's clearer than making the first entry read `-- None--` or `--Off--` or something then we can do it.

**Comment by philwareham** [comment]
Maybe put 'None' in the current version and let's see first. I was just thinking out loud. 😁

**Comment by Bloke** [comment]
I don't mind changing it to use an additional pref. I'll go with whatever is the best experience, and you're way ahead of me on UX!

**Comment by philwareham** [comment]
Seriously though, maybe just the 'None' in the current widget is enough. I just don't know until I actually see it in situ.

**Comment by Bloke** [comment]
Well [here it is](aa49ab73) but it's not great UX. Becuase you can multi-select 'None' along with other things and the none gets ignored. Which is right, because you've selected other stuff. But wrong becasue it looks like it's a regular selection. The only way you can make none sleected is if you select it on its own.

I think you're right, we need to go with a toggle and associated dropdown.

**Comment by philwareham** [comment]
Yeah, sorry Stef. I am right 😉

**Comment by Bloke** [comment]
:) Incidentally, do we have a design pattern for 'reveal secondary control(s) when something else is selected'?

We could do with that for the SMTP mail settings. I want to introduce a toggle: Use SMTP yes/no (with default no) and when you switch it to yes, you get these further options:

* Host
* Port
* Username
* Password

So we could do with some neat(er) way to handle this in JS by using one handler to handle any dependent UI controls.

**Comment by Bloke** [comment]
The DST togge isn't so bad that it takes up space when the radio above it is off, because it's only one control (although I wouldn't be averse to hiding it, and if we have a general way to handle such things in JS, then for consistency it should disappear).

Whatever options are unavailable have to stay in the UI and merely be hidden so that if you have  filled out previous settings, they are still passed on when you save. Otherwise, you'd lose stuff that you might have previously set, merely by toggling the feature off, which is a bind when you might have entered passwords or host info and just be testing the internal mail feature.

**Comment by philwareham** [comment]
@bloke we have the following CSS class available in the stylesheet:

    .ui-helper-hidden {
        display: none;
    }

So you could use JavaScript to add/remove that class as appropriate. As you say, we don't want to remove it from the DOM since you'd lose pref data, so I think this is the best solution.

**Comment by Bloke** [comment]
Okay, that's a start definitely, thanks @philwareham . So what we need then is:

* Some well-known class to assign to a 'parent' UI control (for want of a better word). JS handlers can then use that as a hook.
* If that parent control contains a `data-dependent="some_ID"` attribute, that designates the target block that contains dependent controls.
* If the parent is 'off' then toggle the class `.ui-helper-hidden` of the designated block ID to off as well, thus hiding the elements in that set.

Make sense?

**Comment by philwareham** [comment]
Yep!

**Comment by Bloke** [comment]
Slightly annoying, `yesnoradio` doesn't have a class parameter. *sigh*. This'll be a cinch with the UI class in 4.9, but not so with the current state of things.

So what I'll probably do now is add a dedicated handler to this control, locally, like we do with the DST control. And the same for the SMTP settings. Then, in 4.9.0 we can refactor things (which we'll do as part of the textpattern.js overhaul I expect) and use a single handler for all three.

**Comment by Bloke** [comment]
Okay, ea9c20ab adds a yucky JS handler to simply toggle the second pref bock on/off.

Toggling the class Phil mentioned on the container `prefs-override_form_types` did nothing, seemingly because there are other CSS rules for `txp-form-field` that are more specific, and thus override the generic rule on the container. It worked if the individual label and input control divs were assigned that class, BUT that left a little extra whitespace between the override form radio and the next pref, because the `prefs-override_form_types` container still took up space and has some top+bottom margin.

If you're going to test this btw, after trying the previous commits that I axed, you'll need to go into your database and set `html='yesnoradio'` in txp_prefs for the `allow_form_override` entry, to reset it back to a regular radio pair.

**Comment by philwareham** [comment]
I can set an `!important` on the `.ui-helper-hidden` which will deal with the specificity issue. I tend to avoid `!important` statements because they are generally regarded as bad - but here is what they are actual designed to be used for.

**Comment by Bloke** [comment]
Yeah, I'm not a fan of `!important` either. Kind of feels hacky, but you're right that if you're doing this kind of thing with a simple class toggle then it's necessary.

We could defer this to 4.9.0 anyway and maybe do it all in one go with a better handler, so don't bust a gut over changing it now. The hide/show works, but if you do change it we can toggle that container class instead.

**Comment by bloatware** [comment]
> You have any thoughts on this?

We have some pluggable prefs mechanism on the admin side (PHP), but not JS afaik. Anyway, if `display:none` inputs are not sent and we handle missing inputs case, hiding looks ok.

**Comment by bloatware** [comment]
ATM I've got two override form selectors and no radio.

**Comment by Bloke** [comment]
> ATM I've got two override form selectors and no radio.

Yeah, you'll need to reset you prefs html=yesnoradio for allow_form_override, as I noted in my addendum above. Sorry about that.

**Comment by petecooper** [comment]
If it helps, the `dev` branch running on PHP 8.0.0 RC1 (https://php-next-dev-demo.textpattern.co/dev/) rebuilds at the top of every hour. I can change this to be more frequent - just say how often and I'll make it happen.

**Comment by philwareham** [comment]
> Yeah, I'm not a fan of `!important` either. Kind of feels hacky, but you're right that if we're doing this kind of thing with a simple class toggle then it's necessary.
> 
> We could defer this to 4.9.0 anyway and maybe do it all in one go with a better handler, so don't bust a gut over changing it now. The hide/show works, but if you do change it we can toggle that container class instead.

I've just put the `!important` rule on `.ui-helper-hidden` in both dev and 4.8.4 branches for you.

**Comment by petecooper** [comment]
@Bloke - is your OP covered by the changes made in 4.8.4 re: article forms, or is there still work to do?

**Comment by Bloke** [comment]
Is it just my installation, or does override_form_types (and its associated pophelp) not exist? We should probably add those if not.

Otherwise, yep this issue is done besides thinking up a better name for 'Override form' on the Write panel, and to fix up its associated pophelp text, which is, ummm less than useful!

**Comment by petecooper** [comment]
>Is it just my installation, or does override_form_types (and its associated pophelp) not exist?

Can you attach a screenshot here?

**Comment by Bloke** [comment]
![Screenshot 2020-12-02 at 00 06 20](https://user-images.githubusercontent.com/21252/100811325-4aa0e680-3432-11eb-97f9-3c905a495936.png)

**Comment by petecooper** [comment]
Not just you, I get that here as well. Nuts. I completely missed that in the preflight checks.

**Comment by Bloke** [comment]
No biggie. I thought I raised it in the textpack/pophelp repos with a link to this issue, but might have forgotten, oops.

I can't see `override_form_types` in 'lang/en.ini' nor a corresponding entry in 'en_pophelp.xml'. But it's only language strings so easy to patch and it's not like it's mission critical.

**Comment by petecooper** [comment]
I've reopened https://github.com/textpattern/pophelp/issues/49 with a note at https://github.com/textpattern/pophelp/issues/49#issuecomment-736902722 to track it. As you say, could be rolled into the 4.9 changes given it's not a blocker.

**Comment by petecooper** [comment]
>Otherwise, yep this issue is done besides thinking up a better name for 'Override form' on the Write panel, and to fix up its associated pophelp text, which is, ummm less than useful!

Closing since OP is done, will open a fresh issue for the pophelp anchor.
