### ISSUE TITLE
Add SameSite attribute to cookies

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1554]
### Is your feature request related to a problem?

Not really, just an advice.

### What is the feature?

`txp_test_cookie` creation into the `textpattern.js` file lacks the use of `SameSite=Lax` and maybe `Secure` attributes in order to support an upcoming feature in recent browsers.

**Comment by bloatware** [comment]
Hi Patrick, thanks for the advice. I'm not sure `textpattern.js` is the right place to add these attributes, since it does not create `txp_test_cookie` but deletes it (via `Max-Age=0`), at least in theory. But setting cookies via PHP might need some attention.

**Comment by bloatware** [comment]
Please test 4.8.4 branch in various browsers, if you can. Thanks!

**Comment by cara-tm** [comment]
Thanks. It's perfect!

**Comment by bloatware** [comment]
Thanks for testing. We still have about 20 PHP `setcookie()` calls to patch (mainly in comments), and it's cumbersome in PHP <7. Would you mind changing the issue title to 'Add SameSite attribute to cookies'?

**Comment by bloatware** [comment]
It looks like this is fixed in https://github.com/textpattern/textpattern/commit/fcbb5c9a15f241164ec55e4d39e63427bb2536be.
