### ISSUE TITLE
Do we still have 'Article form preview' feature?

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1555]
There are traces of it in the code, but seemingly no user interface... or I have not found?

**Comment by philwareham** [comment]
IIRC that was removed a few years back because it was so problematic/erratic. Mostly article forms rely own other forms/pages to display content correctly so the preview almost always gave a false preview.

**Comment by Bloke** [comment]
Yeah, I don't remember getting rid of it (HISTORY.txt claims it was in 4.6.0) but we can jettison anything to do with this now.

**Comment by bloatware** [comment]
ok, thanks, will do.
