### ISSUE TITLE
SVG favicon

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1557]
### Is your feature request related to a problem?

No. Just an advice

### What is the feature?

Maybe it's time to add a SVG favicon for our back-office that support the "Dark Mode" and keeping the current one as a fallback?

See here for infos: https://codyhouse.co/nuggets/svg-favicon-dark-mode

**Comment by philwareham** [comment]
This is not supported in Safari though, and our current favicon is fine in Dark Mode. I'll keep an eye on compatibility in future in case anything changes, but I kind of feel this solves a problem we don't really have.

**Comment by petecooper** [comment]
https://caniuse.com/link-icon-svg
