### ISSUE TITLE
"Cannot use positional argument after named argument", `4.8.4` on PHP 8.0.0RC1

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1559]
https://php-next-dev-demo.textpattern.co/4.8.4/textpattern/index.php

Fresh install of current `4.8.4` branch (`dev` similarly is affected), navigate to `/textpattern/` and get this error:

```
Fatal error: Uncaught Error: Cannot use positional argument after named argument in /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/lib/txplib_admin.php:815 Stack trace: #0 /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/vendors/Textpattern/Admin/Theme.php(160): pluggable_ui() #1 /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/index.php(147): Textpattern\Admin\Theme::init() #2 {main} thrown in /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/lib/txplib_admin.php on line 815
```

Not a great deal extra in the Nginx error log:

```
2020/09/30 09:21:56 [error] 21368#21368: *155 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot use positional argument after named argument in /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/lib/txplib_admin.php:815
Stack trace:
#0 /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/vendors/Textpattern/Admin/Theme.php(160): pluggable_ui()
#1 /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/index.php(147): Textpattern\Admin\Theme::init()
#2 {main}
  thrown in /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/lib/txplib_admin.php on line 815" while reading response header from upstream, client: [REDACTED], server: php-next-dev-demo.textpattern.co, request: "GET /4.8.4/textpattern/index.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php-fpm80.sock:", host: "php-next-dev-demo.textpattern.co"
```

Possible useful background info: https://chat.stackoverflow.com/transcript/11/2020/8/21/1 (search for "Cannot use positional argument after named argument")

Tagging https://github.com/textpattern/textpattern/issues/1546

**Comment by Bloke** [comment]
Nice catch. Leave it with me.

**Comment by bloatware** [comment]
We must revise all `call_user_func_array()` calls and can not use `...` operator in 4.8.4 (requires php 5.6). A number of plugins could be broken too.

**Comment by Bloke** [comment]
We're using `...` in dev though, right? So, as long as we don't backport that change to 4.8.4, we should be good there I think.

And it seems the fix for `call_user_func_array()` is to just wrap the second argument with `array_values()`. Does that sound about right?

**Comment by bloatware** [comment]
Or replace it (in 4.8.4) with
```
array_merge(array(
        $event,
        $element,
       (string) $default === '' ? 0 : array(0, 0)
    ), $argv)
```
Yep, seems to work in php 7.

**Comment by bloatware** [comment]
From a quick test, `array_merge($a, $b)` is slightly faster than `array_values($a+$b)`.

**Comment by Bloke** [comment]
A question then, regarding the call in txplib_admin:

Current:
``` php
$ui = call_user_func_array('callback_event', array(
        'event' => $event,
        'step'  => $element,
        'pre'   => (string) $default === '' ? 0 : array(0, 0),
    ) + $argv);
```

Possibly could become:
``` php
$ui = call_user_func_array('callback_event', array_values(array(
        'event' => $event,
        'step'  => $element,
        'pre'   => (string) $default === '' ? 0 : array(0, 0),
    ) + $argv));
```

Or:
``` php
$ui = call_user_func_array('callback_event', array($event, $element, (string) $default === '' ? 0 : array(0, 0),
    ) + $argv);
```

Or Oleg's suggestion:
``` php
$ui = call_user_func_array('callback_event', array_merge(array(
        $event,
        $element,
       (string) $default === '' ? 0 : array(0, 0)
    ), $argv));
```

Or, if [this comment](https://www.php.net/manual/en/function.call-user-func-array.php#117655) is to be believed, we could take the (risky?) move of bumping the PHP version to 5.6 for a patch release and do this:

``` php
$args = array(
        'event' => $event,
        'step'  => $element,
        'pre'   => (string) $default === '' ? 0 : array(0, 0),
    ) + $argv;
$ui = callback_event(...$args);
```

Cast your votes please :)

**Comment by bloatware** [comment]
3 will not work (lost $argv). For the rest, see [this](https://github.com/textpattern/textpattern/issues/1559#issuecomment-701326343) :-)

**Comment by bloatware** [comment]
`...` should be the fastest, but is for dev only.

**Comment by Bloke** [comment]
I feel I'm not qualified to fix this! Plus I need to go out right now. I've unpinned myself so if anyone wants to take a shot, by all means go for it.

If we feel bumping PHP now to 5.6 is worth it for the speed improvement and so we don't need to patch this _again_ in 4.9.0 to use `...` then that's fine by me. I know it's not really the done thing to bump PHP requirements for a patch release though, so if y'all think that's foolish then let's take the path of least resistance now so we continue to get clean merges into 4.9.0-dev.

I'm just concerned if we muck about here with changes to such fundamental calls, that we'll end up making it harder to merge 4.8.4 changes into 4.9.0 as we'll get conflicts.

**Comment by petecooper** [comment]
>If we feel bumping minimum PHP now to 5.6 is worth it for the speed improvement and so we don't need to patch this again in 4.9.0 to use ... then that's fine by me.

I'd be inclined to break with tradition and +1 the sys reqs bump for 4.8.4, with a caveat that we decide either way soon and announce it as soon as we know (I can write something). We've already mentioned multiple times that we're intending to bump the minimum PHP spec, and alluded to our intentions in blog post announcements.

Finite development team, finite resources, finite time in everyone's day. We can preface the release notes with a note about the minimum spec bump, and go into the _why_ angle in a .com post, and on the socials, and forum, and so on.

We've got about 8 weeks from today before PHP 8 lands, I think there's a lot of sense in sorting this _once_ and not unpicking all the work for `dev`.

My 2c.

**Comment by philwareham** [comment]
Agree with Pete. Let's assume people that are upgrading to the latest Textpattern versions will _mostly_ tend to also be active users and have relatively up-to-date hosting, as opposed to someone who installed v4.4.1 many years ago and hasn't touched it since. Luckily we don't have the install-base of something like WordPress so we can dictate more the specs needed to run our software.

**Comment by petecooper** [comment]
The Textpattern Marketing Department is on the case: https://twitter.com/textpattern/status/1311271235729448960

**Comment by bloatware** [comment]
I would agree if 4.8.4 contained *only* php 8 patches, but it's not the case. So -1 for 5.6 switch for me, sorry. And actually any 4.8.4 fix above can be merged into dev and upgraded later if necessary.

**Comment by petecooper** [comment]
@bloatware - as a non-coder, it's tricky to know how much work this will create for you from the code coalface, is it vaguely quantifiable from your point of view? Factor in that other things might also come to light after this is resolved.

**Comment by bloatware** [comment]
@petecooper there are only 5 `call_user_func_array()` entries in core, we can handle it.

**Comment by bloatware** [comment]
@petecooper would it be possible to (temporarily) rebuild 4.8.4 demo every hour, please?

**Comment by petecooper** [comment]
@bloatware - you read my mind, I was just going to suggest that!

Done.

FYI  – preflight (obtain latest code from `dev` and `4.8.3`) happens at *:58, rebuild happens at *:00, please shout if any issues. I will force a rebuild now to get latest commits done.

**Comment by bloatware** [comment]
Getting better. The warning must come from unmuted `@` in php 8, I guess we had them already without noticing.

**Comment by petecooper** [comment]
OP appears to be resolved by https://github.com/textpattern/textpattern/commit/ae056d02850e3493bfb9e2afccf6fbf1be6e1b48 - so closing. Thank you very much @bloatware!
