### ISSUE TITLE
Author tag - can't escape as JSON encoding

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1561]
When I use the author tag in this format...

    <txp:author format="url" this_section escape="json" />

...the URL doesn't seem to be encoded. I just get this:

    http://www.textpattern.local/articles/?author=Phil+Wareham

Whereas other tags such as...

    <txp:permlink escape="json" />

...encode the forward slashes like so:

    http:\/\/www.textpattern.local\/articles\/welcome-to-your-site

#### Additional information

Textpattern version: all (including dev and 4.8.4)

PHP version: tested on PHP 7.4

**Comment by bloatware** [comment]
It's not really a bug but a heritage. Some tags already had `escape` attribute before it has become global. For `<txp:author />` only the name was escaped and not the link, and we have left it so for bwc sake. I can change it if you ensure the after-sales service :-)

Meanwhile, you can encapsulate it inside `<txp:hide />`:
```
<txp:hide process="1" escape="json"><txp:author link /></txp:hide>
```

**Comment by philwareham** [comment]
Ah, OK that `<txp:hide process="1" escape="json">...</txp:hide>` works so I'm happy enough with that solution. Will close, thanks.
