### ISSUE TITLE
Theme names, when multiple versions of a theme exist

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1567]
### Expected behaviour

When updating a theme that is installed on your site, our agreed best method is to name the theme directories with their version number, like so:

    example_theme-1.0.0
    example_theme-1.1.0

That way, when the user uploads the new theme it'll keep the old theme (in case the user made their own customisations to it) rather than overwrite. The user can then systematically change/assign their sections to the new theme and copy over any custom items if necessary.

### Actual behaviour

Although a theme manifest has a version number and theme name - when you've uploaded a new theme as outlined above, with the same theme name but different number - the UI can't differentiate between the two when you come to assign sections, because it just displays themes by name. Example:

<img width="626" alt="Screenshot 2020-10-19 at 11 17 46" src="https://user-images.githubusercontent.com/413665/96432400-c0dbe780-11fc-11eb-8aba-357a642957c2.png">

We could suggest that theme authors also put the version number into their theme name, but this is open to neglect. I'd suggest that when two themes share the same name, the system also shows the version number too, for example:

<img width="656" alt="Screenshot 2020-10-19 at 11 20 58" src="https://user-images.githubusercontent.com/413665/96433930-39db3f00-11fd-11eb-98c3-9959eabb0fc8.png">

#### Additional information

Textpattern version: 4.7+

**Comment by Bloke** [comment]
Good plan. I'll take this.

**Comment by petecooper** [comment]
@Bloke - How viable is this looking for 4.8.4, please? Thanks!

**Comment by Bloke** [comment]
Oooh crap, forgot about this. I'll try and fix it today.

**Comment by Bloke** [comment]
This is trickier to achieve on a per-theme basis due to the way the Skin code is set up. Would everyone be okay with the version number _always_ displayed after the theme name, or do I need to do some additional processing to determine which ones are duplicate and require the version number?

Bear in mind, if we go with a blanket theme version number, it appears _everywhere_ - in the Skin switchers at the top of the Pages/Forms/Styles. Whaddya think?

**Comment by philwareham** [comment]
Yes, I'm sure that would be fine. Thanks Stef.

**Comment by petecooper** [comment]
Works for me.

**Comment by Bloke** [comment]
Quick hack: https://github.com/textpattern/textpattern/commit/df2480030489ca3a01e085a01fabb1255d42a60a

Doesn'twork well in RTL languages because the version is force-appended to the string. Is that a problem? If not, we'll need a language string that has `{theme}` and '{version}` in them. (unless we have one of those already - not checked).

**Comment by philwareham** [comment]
> Doesn't work well in RTL languages because the version is force-appended to the string.

Not sure what you mean by this? Seems fine to me, even with a theme that has a RTL name (since our select fields have `dir=auto` on them)...

<img width="585" alt="Theme selector in RTL" src="https://user-images.githubusercontent.com/413665/99990547-d8822f00-2dab-11eb-9af9-e30ea3ca560b.png">

It is appended at the end, as expected, based on the language.

**Comment by philwareham** [comment]
I think when paired with a LTR language (e.g. latin-based) theme name you'd expect the version at the end (right).

When paired with a RTL language theme name, you'd expect the version at the logical end too (left).

So TLDR, it's fine! 😀

**Comment by petecooper** [comment]
Nice one @Bloke - love your work!

Closing as part of issue housekeeping - @philwareham please re-open if further stuff is necessary.

Thanks, both. Happy days.

**Comment by Bloke** [comment]
Cool, glad it works okay. Please test thoroughly. It should also show up on the Import theme dropdown if you have some stashed to disk.

**Comment by petecooper** [comment]
Aside: we need a workflow to get "please test this" requests out of here and into the forum, possibly even the socials.
