### ISSUE TITLE
Long theme titles and selection field (into Hive admin theme)

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1568]
### Is your feature request related to a problem?

A kind of; more a visual observation.

### What is the feature?

I noticed within the "Sections" panel a width difference (larger) with the "Use theme" selection field when the theme title counts a lot of words (tested from Google Chromium and Firefox for PC, both browsers in their latest version).

![Screenshot](https://i.ibb.co/6N2fxZB/screenshot.png "Current layout") 

In order to get a better layout, consider these corrections (I always use the excellent Hive admin theme).

Change this rule:

    .txp-form-field-label, .txp-form-field-value {
        max-width: 31em;
    }

To:

    .txp-form-field-label, .txp-form-field-value {
        max-width: 30em;
    }

Then assign to the select element this new rule:

    #section_skin {
        text-overflow: clip ellipsis
    }

**Comment by petecooper** [comment]
@philwareham - How viable is this for 4.8.4, please? Thanks!

**Comment by philwareham** [comment]
Just looking at it now. If it's a good solution, I'll provide a fix.

**Comment by philwareham** [comment]
Fixed, but please test.
