### ISSUE TITLE
'Expand/collapse' links don't work (v. 4-9-dev)

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1569]
### Expected behaviour

Access to "Expand All" tabs.

### Actual behaviour

Tested from the official demo with Google Chrome and Firefox (latest's browsers version) on PC, the "Expand All" links no longer work within TXP 4-9-dev but all work well within TXP 4.8.3 stable (javascript suspected but without any browser's console errors).

### Steps to reproduce

Try the demo sites.
To be confirmed by Devs.

### Edit ###

After some little investigations, I just found where is located the problem: a change into the style rules.

Simply by removed this all works fine as expected:

    .ui-helper-hidden {
        display: none !important;
    }

#### Additional information

Textpattern version: 4.9-dev

Web server vendor and version: {Please write here}

Database server vendor and version: {Please write here}

PHP version: {Please write here}

**Comment by phiw13** [comment]
Interesting…
from those “hidden” blocks: `class="toggle ui-helper-hidden"`

The intend seems to be that the `toggle` script adds/removes the  ui-helper-hidden class, but it only sets `style=display:none` or removes that.

And `.ui-helper-hidden` has `!important`. and thus the blocks are always hidden.

**Comment by philwareham** [comment]
I’m off on vacation from today until next Monday. Will look at this bug then if nobody does it beforehand. Cheers.

**Comment by cara-tm** [comment]
Have a nice holiday, Phil ;)

Philippe: I did some searchs and it seems more complicated...

Maybe an alternative could be to deal with arias:

    section [aria-expanded="false"] {
        display:none
    }
    section [aria-expanded="true"] {
        display:block
    }

But the default state seems to be set to `aria-expanded="false"`

**Comment by philwareham** [comment]
I have reverted the offending code temporarily, to fix the issue short-term. However I will need the help of @bloatware to fix this properly.

Background:

To allow for tighter CSP we (me) had removed inline JS from the admin side. The code at https://github.com/textpattern/textpattern/blob/dev/textpattern/lib/txplib_html.php#L549 for this particular item was changed from (4.8.x behaviour):

        $display_state = array(
            'class' => 'toggle',
            'id'    => $anchor_id,
            'role'  => 'group',
            'style' => $visible ? '' : 'display:none',
        );

To (4.9.0):

        $display_state = array(
            'class' => $visible ? 'toggle' : 'toggle ui-helper-hidden',
            'id'    => $anchor_id,
            'role'  => 'group',
        );

However, I had failed to take into consideration the JS functions `function toggleDisplay(id)` and `function toggleDisplayHref()` starting at https://github.com/textpattern/textpattern/blob/dev/textpattern/textpattern.js#L495 which don't work with the changes I'd made above.

Since my JS expertise is rudimentary, I don't know how the JS works entirely. So I need a JS expert to take a look.

**Comment by bloatware** [comment]
Did removing `!important` from `.ui-helper-hidden` display rule not help?

**Comment by philwareham** [comment]
That isn’t the issue here I think. It’s the php and js combination as far as I can see.

**Comment by bloatware** [comment]
Yep, you are right. Toggling `ui-helper-hidden` class instead of `display` produces weird results, things must be more imbricated.

**Comment by bloatware** [comment]
I don't like the class name `ui-helper-hidden` to hide/show elements, a plain `hidden` looks more robust.

**Comment by philwareham** [comment]
Ok, put the class in place for now and I’ll make sure the admin themes have a `.hidden` class when I next get to my computer.

**Comment by bloatware** [comment]
On a second thought, we must insure it works with every admin theme, not only the default ones. It looks like `ui-helper-hidden` is already adopted, so I leave it in place atm.

**Comment by phiw13** [comment]
I don’t really like that `ui-helper-hidden` class name either. `.hidden` would be fine be me (that is for 4.9-dev only, right ?).

**Comment by philwareham** [comment]
Yes this is only 4.9 onwards. 4.8.4 had the previous (working) inline JavaScript in place.

**Comment by bloatware** [comment]
Then I have [submitted](https://github.com/textpattern/textpattern/commit/ac0499c65a299af341398fa49e5e7e32d4e6fd5e) to the wrong branch.

It's too early to patch 4.9 UI, imo. If custom fields land there, more changes could be necessary.

**Comment by bloatware** [comment]
Breaks plugin composer, reverted.

**Comment by Bloke** [comment]
Plugin composer is broken anyway so don't use that as a blocker for progress.

**Comment by philwareham** [comment]
I've added the `.hidden` class as requested to admin themes.

**Comment by bloatware** [comment]
This class shouldn't be `!important`, otherwise jQuery `hide()/show()` that we (core, plugins) use in many places will break.

**Comment by Bloke** [comment]
Then we'll need to find another way to fix the issue that caused us to use `!important` in the first plalce. It was something fairly recent, if memory serves, but I forget exactly what it was. Something to do with me and a recent commit, oops. Sorry.

**Comment by bloatware** [comment]
The less class names we use for interactions the better for plugins/themes authors. They would certainly find `hide()` more intuitive to use than `addClass('hidden')`. As I get the OP problem, we just need to find a (preferably classless) way to hide elements on load without recurring to inline style.

**Comment by Bloke** [comment]
Yeah. I agree the fewer classes we have the better. If you want to alter the stuff in the prefs panel to use hide() instead, that's fine. I was probably taking the shortest path to completion rather than the best option.

**Comment by philwareham** [comment]
I've removed a few `!important` enforcements from the admin themes' CSS now. I assume the prefs panel might need a couple of tweaks as Stef mentioned above.

This then fixes the OP. Although if you want to think about a different way of to show/hide going forward then that's fine. Maybe wedded with Stef's UI widgets. Note that a few JS items use toggled CSS classes though, not just this one. So that has to be taken into consideration (just not the use of inline JS).

**Comment by bloatware** [comment]
I'm not against using classes here, but they should be part of a core `css`, not themes' one.

**Comment by philwareham** [comment]
@bloatware are you proposing we create a separate `core.css` file that is loaded in regardless of admin theme used? This is certainly doable although I would need a consensus on it. @phiw13 what are your thoughts?

**Comment by bloatware** [comment]
@philwareham @phiw13 yes, I think this would be logical, since we expect these classes to act as supposed in the central `textpattern.js`. I would call it `textpattern.css`, for consistency, and put there all 'technical' selectors like `.busy` etc. This would decrease themes `css` size too.

**Comment by philwareham** [comment]
OK sure, I think that needs a separate issue raised where we can work out what is deemed core and what isn't.

**Comment by phiw13** [comment]
`core.css`, I am a bit dubious about this. Maybe a very narrow subset of classes could be part of it but that would not make a huge difference on the size of theme.css.
Please open a new issue and expand a little on your idea, which classes you might want to include and what styling you would eventually want to apply.

**Comment by Bloke** [comment]
Some sort of core style rules might be a good move, actually. But only for things that core assumes **must** exist. As Phil and Oleg say, `busy` and `hidden` are contenders. It cuts down (a smidge) on theme rules that need to be represented and, if they're missing, could break the admin side operation.

If someone wants any specific styling at the theme level, there's nothing to stop them overriding the core rules: as long as we don't use `!important` on them, that's fine, right?

**Comment by bloatware** [comment]
+1 @Bloke It would at least include all selectors txp uses in `textpattern.js` (to hide/show things and other interactions). Themes CSS would be loaded after the core's one and override what deemed necessary.

**Comment by philwareham** [comment]
A major drawback of that approach is CSS specificity. By keeping the CSS within the theme you can control specificity (mostly). By loading it first you'll make the theme CSS further down the cascade and therefore it can potentially override the core CSS (unless we introduce more `!important` rules which we don't want to do). Therefore loading `core.css` after `theme.css` would be preferrable - if we go down this route.

**Comment by bloatware** [comment]
@philwareham overriding core rules is fine for me if done intentionally, unless I misunderstand your point.

**Comment by Bloke** [comment]
Oh, okay. For some reason I thought rules loaded earlier could be overridden by later rules of the same specificity. Isn't that what we want?

e.g. Core says: `.hidden` is display none.
Theme says: No, `.hidden` is display none with a transition.

**Comment by phiw13** [comment]
> For some reason I thought rules loaded earlier could be overridden by later rules of the same specificity. Isn't that what we want?

Yes, that is what should happen (and I would expect the selectors in an eventual `core.css` to have a very very low specificity. I would expect `core.css` to be loaded first, and to be _very_ minimal in what it actually does (only apply a very few rules).

**Comment by philwareham** [comment]
> For some reason I thought rules loaded earlier could be overridden by later rules of the same specificity. Isn't that what we want?

No, we want those rules to be respected. i.e. if a `.hidden` or `.busy` selector with a `display:none;` is being used then we don't want a theme rule with same specificity and `display:block;` to change the above rule. Hence why core.css should be loaded second IMO.

**Comment by bloatware** [comment]
Themes *should* be able to override core. We just need to insure (via `txp-` prefix or whatever) they do it intentionally.

I would put into core css a very basic overridable fallback theme à la Classic.

**Comment by Bloke** [comment]
> if a core rule `.hidden` or `.busy` selector with a `display:none;` is being used then we don't want a theme rule with same specificity and `display:block;` to change the above rule.

Why not? Genuine question. Regardless of load order, if people desperately want to override something, they can either use more specificity or add `!important` anyway. Why make them jump through those hoops?

If core rules load first, themers are blissfully unaware of the need to include those rules, we get 'safe' behaviour because we know the classes exist, but if someone knows what they're doing, they can easily alter them if they wish, without hackery.

Granted, if they swap it out for something daft like display:flex or display:block then it'll break our toggling ability. But why would they do that to make their theme incompatible with core?

Far more likely is they want the toggling to be styled additionally, so they can use the base behaviour we supply and build upon it.

Do you have specific use cases in mind where it's vital that core rules prevail at all costs? And if so, how do we ensure that? Maybe I'm not thinking far enough outside the box.

**Comment by philwareham** [comment]
> Do you have specific use cases in mind where it's vital that core rules prevail at all costs?

Sure, take the following, for instance, which could happen:

In `core.css` (first load):

```
.hidden {
    display: none:
}
```

In `theme.css` (second load):

```
.txp-search-clear {
    display: inline-block;
}
```

When the panel has class state of `class="txp-search-clear hidden"` the hidden state isn't honoured.

**Comment by Bloke** [comment]
Right, okay, so this is _other_ classes interfering with our ability to do what we intend. Gotcha. Hadn't thought of that. Hmmm, that is tricky.
