### ISSUE TITLE
Rework the default article

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1574]
Our default article is a wall of text.

We should investigate making it much simpler, clearer and easier for a newbie to understand. From a maintainability point of view, it will make [localisation](https://github.com/textpattern/textpattern/issues/1179) much more straightforward and sustainable.

Considerations:

* remove idioms or other ambiguous wording
* sufficient links to the stuff to get going with, and pointers for further reading
* perhaps work in docs site or .com subdomain mini site for "next steps"
* …lots more I haven't considered

@philwareham - what's on your shopping list?

**Comment by philwareham** [comment]
> What's on your shopping list?

The absolute bare minimum, in my opinion. To borrow from a lesser-known CMS, as an example...

> Welcome to ~~WordPress~~ Textpattern. This is your first post. Edit or delete it, then start writing!

😁

**Comment by petecooper** [comment]
Funny you say that, I'm inclined to do a blank sheet rebuild rather than edit the current text. The extra stuff could be the barebones of a .com/docs "next steps" landing page that opens in a new browser tab.

**Comment by bloatware** [comment]
Don't ask me to translate it again, unless it fits into 10 words!

**Comment by philwareham** [comment]
> Don't ask me to translate it again, unless it fits into 10 words!

Yes, exactly! The large welcome article is a pain to get translated. And if anything changes (which things do, in the current welcome article) then it means a re-translation. Shorter the better in my opinion.

**Comment by Bloke** [comment]
Shorter the better with a link to an online 'next steps' doc gets my vote. Don't we have one of those already that we can repurpose? I thought zero wrote one, which we eventually distilled to the one that's now in the default article? Might have been on the old docs wiki and got lost/recycled in the transition.

**Comment by philwareham** [comment]
Can you possible suggest some text Stef? As our master wordsmith!

**Comment by Bloke** [comment]
Sure, I'll get onto it and fashion an article on the docs site over the next day or so.

**Comment by petecooper** [comment]
OK, so we're largely agreed that it's a bit unwieldy right now and the pointer to a docs landing page seems like a straightforward thing to do.

This is not massively urgent. Given we have 4.8.4 coming out in three-ish weeks, I think we can definitely wait until after that. We'll need to:

- [ ] spec out the landing page contents & links
- [ ] write the new default article
- [ ] get it out for comment on the forum and perhaps socials
- [ ] decide if can it be part of the main repo or does it need to live under Textpacks in some way so we can weaponise CrowdIn with least resistance
- [ ] note somehow to translators that the docs landing page will initially only be in `en_US` or similar

What else?

@Bloke - I can help with this if you want additional eyes and brainz.

**Comment by philwareham** [comment]
I'd suggest that changes to the 'welcome' article are made in the `localised-setup-content` branch (which I've just synced to latest dev branch). Once we have something we're happy with I can move the translation file over to Crowdin and get translators onto updating their versions. Cheers!

**Comment by Bloke** [comment]
At the risk of regressing on what we currently have (which is, as @bloatware says, unsustainable as features are added) I don't think we should translate the docs landing page. Docs are English. We don't have the people power to keep multi-lingual docs up-to-date.

The new default article content can just be a few simple lines, as Phil suggests. A placeholder with nothing specific so we're not making work for ourselves / translators. We can use the linked English doc page as a springboard / dashboard - with orientation info on terminology, and links to a few other docs such as managing themes, plugins, general admin techniques, and so forth.

I see Pete has started a thread about [docs curation](https://forum.textpattern.com/viewtopic.php?pid=326680#p326680) so we should definitely use this to polish up the docs are and maybe get the docs/textpattern.com/index2 made live.

We also need to revamp all the tag pages to use the inlcudes for global attributes (see the [section_list tag](https://docs.textpattern.com/tags/section_list) for an example). I was holding back on doing that until we'd further investigated self-hosting docs. But maybe we should start now, since it'll be a bit of a chore.

**Comment by petecooper** [comment]
>Docs are English.

Yep. I've updated https://github.com/textpattern/textpattern/issues/1574#issuecomment-722563002

**Comment by philwareham** [comment]
> I don't think we should translate the docs landing page.

Agreed, it is not my intention to translate any of the docs site, not even a landing page directed from the welcome doc.

**Comment by petecooper** [comment]
>I'd suggest that changes to the 'welcome' article are made in the localised-setup-content branch (which I've just synced to latest dev branch snapshot).

https://github.com/textpattern/textpattern/blob/localised-setup-content/textpattern/setup/default-content/en/articles/articles.welcome.xml

**Comment by Bloke** [comment]
How about this as starter content. Refine at will:

**Body**

Welcome to Textpattern! This is your first post, which you can edit or delete and then start writing your own content.

If you're new here and would like a quick tour then please see [Textpattern in Two Minutes](https://textpattern.com/about/425/textpattern-in-two-minutes) or [head over to the docs](https://docs.textpattern.com/#) for more detailed information.

Have fun!

**Excerpt**

This is a an excerpt for the welcome article.

Article excerpts are optional and can be used to summarize an article's content for display on article list pages or as opening teaser paragraphs.

**Comment by petecooper** [comment]
@Bloke - can you work that into https://github.com/textpattern/textpattern/blob/localised-setup-content/textpattern/setup/default-content/en/articles/articles.welcome.xml so we can tweak, please? Thanks!

**Comment by Bloke** [comment]
Done in c165b79dc.

**Comment by philwareham** [comment]
I'm happy with this. Feel free to make any minor amends though as you see fit. The length is good now though, so no extra text needed IMO.

**Comment by petecooper** [comment]
+1 from me, much better. Thanks, @Bloke and @philwareham! A few too many words for @bloatware to translate, so he's escaped this time…

Can we merge into `4.9` if @Bloke is OK with wording? This can be closed when that's done.

**Comment by philwareham** [comment]
The branch can't be merged into 4.9 as yet, because the whole code around localised default content isn't written yet I think?

You can certainly cut/paste the text from the file above into 4.9 branch's equivalent file though, manually.

**Comment by philwareham** [comment]
@bloke Shall I update Crowdin with this new translation? It doesn't affect 4.8.4 development since that file is not used at all in 4.8.x.

**Comment by petecooper** [comment]
>You can certainly cut/paste the text from the file above into 4.9 branch's equivalent file though, manually.

Good enough!

**Comment by petecooper** [comment]
(OK, now I'm done fiddling.)

**Comment by philwareham** [comment]
Great! I have now moved the translation over to Crowdin for out translation gurus to action. Happy for you to close this issue when you are ready.

**Comment by petecooper** [comment]
>You can certainly cut/paste the text from the file above into 4.9 branch's equivalent file though, manually.

With the risk of looking a bit dense…what branch is that? `dev`?

**Comment by philwareham** [comment]
Yes!

**Comment by petecooper** [comment]
Done.
