### ISSUE TITLE
improve keyboard accessibility of list tables (scrolling with keyboard)

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1577]
Consider adding `tabindex=0` to the list-tables wrapper : `.txp-listtables`

suggestion / advice by Mr Roselli, to satisfy WCAG SC 2.1.1 Keyboard

source: https://adrianroselli.com/2020/11/under-engineered-responsive-tables.html

**Comment by philwareham** [comment]
Done. Thanks Philippe.
