### ISSUE TITLE
`dev` branch parse error on `vendors/Textpattern/Skin/Skin.php`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1578]
### Expected behaviour

`dev` auto installer completes without error.

### Actual behaviour

`dev` auto installer throws error: `Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /path-to-docroot/textpattern/vendors/Textpattern/Skin/Skin.php on line 1322`

### Steps to reproduce

* clone `dev` branch, run setup.php with valid JSON config
* note error:

#### Additional information

Textpattern version: 4.9-dev (aka `dev` branch)

Web server vendor and version: Nginx 1.19.4

Database server vendor and version: Percona 8.0

PHP version: 7.3.24

Possibly relates to https://github.com/textpattern/textpattern/commit/8747aec4112231ed6496ec2cd106e2b36be6f6ff

Should https://github.com/textpattern/textpattern/blob/8747aec4112231ed6496ec2cd106e2b36be6f6ff/textpattern/vendors/Textpattern/Skin/Skin.php#L1321 be `arrayarray` or is that a typo?

**Comment by phiw13** [comment]
See this comment: https://github.com/textpattern/textpattern/commit/8747aec4112231ed6496ec2cd106e2b36be6f6ff#r44322924
