### ISSUE TITLE
Some changes for the login-in form

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1580]
### Is your feature request related to a problem?

No. Only a consideration.

### What is the feature?

With the help of a custom.css file, I changed the layout of the login-in form.

After studying the design system in use by GitHub here: https://primer.style/design/ui-patterns/button-usage, it seems we could consider these little changes:

Center the connexion button in order to reconsiliate left hand and right hand users;
Put the "Remenber me" secondary link on the right in order to extract it from the logical flow of the main elements;
Center the front-end website link;
Materialize the bloc by a tiny border and/or a subtil shadow.

![Login-in proposal](https://i.ibb.co/BCs4qd9/login-in.png)

**Comment by philwareham** [comment]
I'll consider these proposals during our 4.9 dev cycle. Cheers.

**Comment by philwareham** [comment]
I've incorporated some of your suggestions into the 4.9 Hive theme login panel. Cheers!

**Comment by petecooper** [comment]
Pretty!

![Screenshot 2020-12-02 at 19 21 22](https://user-images.githubusercontent.com/226578/100920911-b5eec500-34d3-11eb-8c8e-4c438107abec.png)
