### ISSUE TITLE
Back-office message: an administrator is connected

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1583]
### Is your feature request related to a problem?

No.

### What is the feature?

Could it be useful to display a simple message when an administrator is connected within the back-office to all other users?
Sure! In order to inform some important changes currently in process will affect a website.

**Comment by Bloke** [comment]
I've thought about this before. I think smd_user_manager even has a 'who's online now' (or at least, did. It might not work any more or maybe I took it out).

Anyway, the tough thing with this feature request is that we don't necessarily know when people are visiting the back-end. The login cookie is the problem as it has an expiry of 30 days (I think) so we don't know any further than that granularity. That's the reason we only have the month shown in "last login" on the Users panel.

Can't remember how I got round it in smd_user_manager. I think I had a configurable timeout value in the plugin prefs and then tracked every page refresh so it updated a "last clicked" indicator per user. Then compared those values with the timeout to give an indication of who's around. Not ideal (as it "tracks" people) and not foolproof.

**Comment by petecooper** [comment]
For me, changes to a site where multiple users are involved (like the scenario @cara-tm outlined in the OP) should be communicated with details, not simply "Alice is connected", and that should happen outside Textpattern, so a) there is notice to anyone who has not logged in, and b) there is an audit trail for who has been informed, when they were informed, and what details they have been given.

**Comment by petecooper** [comment]
…plus there's also a good chance the administrator is perhaps checking Diagnostics, adding users, or other day-to-day tasks outside the look-and-feel of the site.

**Comment by petecooper** [comment]
Bumping this for housekeeping - it's plugin territory from my viewpoint, open to input from @Bloke and @bloatware.

**Comment by Bloke** [comment]
I agree - this is more plugin than core. smd_user_manager shows who's online.
