### ISSUE TITLE
Overhaul `README.txt`, split into more useful files, maintenance tasks

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1587]
`README.txt` has had all sorts of stuff added and changed over 15 years, it's time for a makeover.

To do [wip]:

- [x] Remove the FAQ link, it doesn't exist and ends up on the docs landing page.
- [x] Rewrite with a focus on legal preflight + links to…
  - [x] `INSTALLING`
    - [x] make the file
    - [x] copy from source
    - [x] rework
      - [x] preflight
      - [x] install
      - [x] upgrade
  - [x] `UPGRADING`
    - [x] make the file
    - [x] copy from source
    - [x] rework

**Comment by petecooper** [comment]
This shouldn't be a blocker for 4.8.5, so if it's the only outstanding item then it can be bumped to 4.9.0.

**Comment by petecooper** [comment]
I can hopefully finish this tomorrow, can be merged when done.

**Comment by petecooper** [comment]
OK, I think this is done-ish. I've spun out `README.txt` into three files on `4.8.5`:

* https://github.com/textpattern/textpattern/blob/4.8.5/README.txt – much leaner
* https://github.com/textpattern/textpattern/blob/4.8.5/INSTALL.txt – install stuff
* https://github.com/textpattern/textpattern/blob/4.8.5/UPGRADE.txt – upgrade stuff

@Bloke - if you're happy (broadly), it can be merged at an appropriate time.

**Comment by Bloke** [comment]
Nice! Much neater. Do we need to mention during upgrade that you should omit /textpattern/plugins from the repo? Depending on your FTP client it may blat the contents otherwise.

No major harm if they do: from what I recall, it'll auto-repopulate the plugins dir as you navigate the admin side, but that will put unnecessary strain on the server immediately after upgrade.

**Comment by petecooper** [comment]
>Do we need to mention during upgrade that you should omit /textpattern/plugins from the repo? 

We should. I'll do that now.

**Comment by petecooper** [comment]
Done. Merged. Good enough for now.
