### ISSUE TITLE
Missing pophelp `override_form_types` in Prefs -> Publish

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1588]
https://github.com/textpattern/textpattern/issues/1553#issuecomment-736899723

The missing pophelp string is tracked at https://github.com/textpattern/pophelp/issues/49#issuecomment-736902722

**Comment by philwareham** [comment]
If you or @bloke and provide help text for this and for the text string - I'll add those into the respective repos and upload to Crowdin for translation. Ta!

**Comment by petecooper** [comment]
@philwareham – "Allow override on form types" is the best I can manage right now, feel free to mangle to follow current terminology.

**Comment by Bloke** [comment]
We could just go with _Override form types_. Uhhh, maybe.

As for pophelp, how about:

Choose which form types will have their templates made available in the Write panel as override forms.

Is that good enough? Or do we need more?

**Comment by petecooper** [comment]
>Override form types

That's fine. Perhaps something in the pophelp about selecting multiple options (Cmd + select on macOS, Windows and Linux escape me) given it's the only multi-select pref we have. How we do this on mobile, not a clue.

**Comment by petecooper** [comment]
I'm trying to figure out how to add the anchor for it in `txp_prefs`, haven't got the foggiest with that JS block around `override_form_types`.

**Comment by Bloke** [comment]
Yeah, good call about multi-select. We need to add that. I don't know what the UX is on mobiles for that either. Might have to log in and try it.

As to your second question, what anchor? As soon as we make a pophelp entry for it, the '?' should appear automatically.

**Comment by petecooper** [comment]
Today I learned!

**Comment by petecooper** [comment]
Done via https://github.com/textpattern/pophelp/commit/09a5a4dd5a0723eeab8c13fdf30cf0df3cb0552b and https://github.com/textpattern/pophelp/commit/11ee5440e74e05bed08ebf0628614e0852851799
