### ISSUE TITLE
Comments off by default

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1589]
### Is your feature request related to a problem?

No.

### What is the feature?

In the age of GDPR, and of social media, third-party comment platforms, [webmentions](https://www.w3.org/TR/webmention/), etc. I think we should turn off the comments system by default in new installations.

Note that I'm not advocating removing comments features from the CMS, just make it an manual opt-in via the prefs panel.

Thoughts?

**Comment by Bloke** [comment]
Seeing as this only affects new installs and not upgraders, and it's only a one-line change, could we do it in 4.8.5?

**Comment by philwareham** [comment]
Sounds good to me.

**Comment by Bloke** [comment]
Okay, slightly more than one line but I thought it made sense to set the default off in all `get_pref()` calls too, for consistency.

**Comment by petecooper** [comment]
Done, closing.
