### ISSUE TITLE
Write page declutter

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1590]
### Is your feature request related to a problem?

No.

### What is the feature?

Let's declutter the write page a bit in the 4.9 dev cycle, ready for the custom fields changes and suchlike.

Non-essential things I think we can easily get rid of:

1. The expand/collapse all links. I know this was my addition in the first place but after living with it for a couple of versions I don't think it is overly useful.
2. The recent articles box. Again not overly useful and arguably it doesn't actually list the most recent articles you've worked on (just the latest by ID in the database).
3. Prev/next links (as suggested by @phiw13).

Feel free to add your arguments/additions too.

Note that I know we are hoping to make the panel more customisable - but the above I think can be removed regardless.

**Comment by petecooper** [comment]
Possible overlap with https://github.com/textpattern/textpattern/issues/1512

**Comment by philwareham** [comment]
Indeed, but this is about permanently removing those two items, not making them user managed. I want to be a bit opinionated on what we allow in the write page, and don't see these items as important.

**Comment by phiw13** [comment]
No objections to remove the recent articles box as it is not-so-useful (and remove the `next/prev` link as well?). However I would be _very_ sad to see the expand/collapse all widget disappear, and I am sure some of my clients will too. I use the collapse all widget frequently, not so much the expand all one.

**Comment by philwareham** [comment]
I've commented out the previous/next and recent articles UI on the write tab in dev branch for now. Let me know your thoughts. Can reinstate if the arguments for are strong enough.

**Comment by cara-tm** [comment]
As @phiw13 said, IMHO I think the widget system is useful (with its position memorization). But sure: the other things can be removed.

**Comment by rwetzlmayr** [comment]
I was wondering if you were considering whether to keep or remove the pluggable UI callback event `article_ui > recent_articles' when removing the recent articles list. 

This event is currently called by the now-defunct `article_partial_recent_articles' function (https://github.com/textpattern/textpattern/blob/73c29f498fd1b74a5228f81be377577fb90b603b/textpattern/include/txp_article.php#L1670). This event may provide an opportunity to revive the recent articles UI via a plugin for people who are unhappy with the loss of the built-in recent articles list.

**Comment by Bloke** [comment]
I'm fine with leaving it in so plugins can put stuff down there.

**Comment by bloatware** [comment]
Looks like some consensus has been found, closing.
