### ISSUE TITLE
Manual installation issue with PHP 8.0.0 - `mysqli_get_client_version()`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1592]
https://forum.textpattern.com/viewtopic.php?pid=327235#p327235

```
Fatal error: Uncaught ArgumentCountError: 
mysqli_get_client_version() expects exactly 0 arguments, 1 given in /var/www/otg/textpattern/setup/setup_lib.php:368
Stack trace: #0 /var/www/otg/textpattern/setup/setup_lib.php(368): 
mysqli_get_client_version() #1 /var/www/otg/textpattern/setup/index.php(365): 
setup_connect() #2 /var/www/otg/textpattern/setup/index.php(145): 
step_printConfig() #3 {main} thrown in /var/www/otg/textpattern/setup/setup_lib.php on line 368
```

**Comment by petecooper** [comment]
Related?: https://core.trac.wordpress.org/ticket/31644

**Comment by petecooper** [comment]
Confirmed with manual install of 4.8.4 on a fresh PHP 8.0.0 server with Percona (MySQL) 8.0. Looks like new installations fail on that combo. Ugh.

@Bloke – any ideas?

**Comment by Bloke** [comment]
If the argument is optional, let's just remove the `$DB->link` from the function call. It should then work back as far as, well, whenever they made it optional. As long as it works on PHP 5.5 and above, we should be good with that patch.

**Comment by petecooper** [comment]
I can spin up an older PHP server later on, see how it flies. Any chance you could either drop a patch here or make a new branch so I know what's changed?

**Comment by petecooper** [comment]
Confirmed fixed here with https://github.com/textpattern/textpattern/commit/f63609f392923f62a91c442a75e897f85a3515fb patch - thanks @Bloke !
