### ISSUE TITLE
`Warning "Undefined array key "skin_delete_from_database""` on admin-side login, PHP 8.0.0

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1596]
### Expected behaviour

Admin-side log in procedure is error-free.

### Actual behaviour

![Screenshot 2020-12-04 at 16 29 24](https://user-images.githubusercontent.com/226578/101188742-02f6a680-364e-11eb-96d1-c35b75a3d13e.png)

`Warning "Undefined array key "skin_delete_from_database"".`

### Steps to reproduce

* Install Textpattern 4.8.4 plus current patches in `4.8.5` branch, choose 'Zero' theme (not sure if this is relevant, I will retest shortly)
* Log in with provided username & password, note error.

#### Additional information

Textpattern version: Textpattern 4.8.4 + current patches in `4.8.5`.

Web server vendor and version: Nginx 1.19

Database server vendor and version: Percona 8.0

PHP version: PHP 8.0.0

**Comment by petecooper** [comment]
I will bump up PHP logging level to see what else can be gleaned.

**Comment by petecooper** [comment]
I will bump up PHP logging level to see what else can be gleaned.

**Comment by Bloke** [comment]
This doesn't rear its head on earlier PHP, so I'm stabbing in the dark, but by reading the code there are a few places I'm guessing this could be coming from:

1) Skin->getMultiEditCheckbox();
2) Lang->gTxt();

I won't know which until I see more detailed diagnostics. Would you please be able to install a fresh copy with Zero, but before logging in, alter your production_status pref to `debugging`. Then try logging in. That _should_ give way more detail about which line(s) exactly are complaining: a boon for tracking this down. Should also help with #1597 

Thank you.

**Comment by petecooper** [comment]
On the case. Hold tight.

**Comment by petecooper** [comment]
```
Notice "tempnam(): file created in the system's temporary directory"
in /var/www/sites/example.com/www/live/textpattern/lib/txplib_admin.php at line 1024.
```

```
adminErrorHandler()
textpattern/lib/txplib_admin.php:1024 tempnam()
textpattern/vendors/Textpattern/DB/Core.php:174 find_temp_dir()
textpattern/vendors/Textpattern/DB/Core.php:238 Textpattern\DB\Core->getPrefsDefault()
textpattern/include/txp_auth.php:342 Textpattern\DB\Core->checkPrefsIntegrity()
textpattern/include/txp_auth.php:50 doTxpValidate()
textpattern/index.php:150 doAuth()
```

```
Warning "Undefined array key "skin_delete_from_database""
in /var/www/sites/example.com/www/live/textpattern/vendors/Textpattern/DB/Core.php at line 245.
```

```
textpattern/vendors/Textpattern/DB/Core.php:245 adminErrorHandler()
textpattern/include/txp_auth.php:342 Textpattern\DB\Core->checkPrefsIntegrity()
textpattern/include/txp_auth.php:50 doTxpValidate()
textpattern/index.php:150 doAuth()
```

![re](https://user-images.githubusercontent.com/226578/101195951-0abb4880-3658-11eb-8eee-6af7643e63df.png)

**Comment by Bloke** [comment]
Looks like I was way off. That's gonna be super useful to help track this down. Thank you.

**Comment by petecooper** [comment]
I'll test https://github.com/textpattern/textpattern/commit/318f58af08b0a9821015177b3046048f851bd6ec and see how she go. Thanks @Bloke!

**Comment by Bloke** [comment]
I'm working on the second half of this now. The above patch only fixes (I hope) the first `tempnam()` warning.

**Comment by petecooper** [comment]
Ah, OK - I'll hold off for now.

**Comment by Bloke** [comment]
Okay, try that now please :)

**Comment by petecooper** [comment]
That appears to work. Excellent stuff, thank you.

I'll splat and reinstall a few more times to be 100%, but good call.

**Comment by petecooper** [comment]
Boom. Fixed. Thank you.

Cheque in the post, @Bloke.

**Comment by Bloke** [comment]
Ace, thank you. We may find a few more of these lurking. It's all the lazy programming where, instead of checking if something (such as an array index) exists, we try to access it anyway and mask it with the '@' sign to hide any errors. That worked in versions prior to PHP 8.0, but they're now (it seems) throwing warnings if you attempt that trickery. Quite rightly, because we shouldn't be using error suppression at all.

So if you see anywhere in the code with a '@' in front of the line of code or some variable, that's a potential pinch point where error messages might crop up.
