### ISSUE TITLE
`Warning "Trying to access array offset on value of type null".` when accessing Diagnostics, PHP 8.0.0

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1597]
### Expected behaviour

Diagnostics with no dialogs.

### Actual behaviour

`Warning "Trying to access array offset on value of type null".` notification.

![Screenshot 2020-12-04 at 16 30 35](https://user-images.githubusercontent.com/226578/101189224-aa73d900-364e-11eb-8f26-9528bf852e68.png)

### Steps to reproduce

* Install Textpattern 4.8.4 plus current patches in 4.8.5 branch, choose 'Zero' theme (not sure if this is relevant, I will retest shortly)
* Log in with provided username & password, access Diagnostics, observe notification.

#### Additional information

Textpattern version: Textpattern 4.8.4 + current patches in 4.8.5.

Web server vendor and version: Nginx 1.19

Database server vendor and version: Percona 8.0

PHP version: PHP 8.0.0

**Comment by Bloke** [comment]
A hunch, but this and #1596 are probably to do with the missing (empty) assets in the Zero theme. I'll try and chase it down.

**Comment by petecooper** [comment]
```
Warning "Trying to access array offset on value of type null"
in /var/www/sites/hellomynameispete.com/www/live/textpattern/include/txp_diag.php at line 200.
```

```
textpattern/include/txp_diag.php:200 adminErrorHandler()
textpattern/include/txp_diag.php:81 doDiagnostics()
textpattern/index.php:228 include()
```

```
Warning "Trying to access array offset on value of type null"
in /var/www/sites/hellomynameispete.com/www/live/textpattern/include/txp_diag.php at line 783.
```

```
textpattern/include/txp_diag.php:783 adminErrorHandler()
textpattern/include/txp_diag.php:201 checkUpdates()
textpattern/include/txp_diag.php:81 doDiagnostics()
textpattern/index.php:228 include()
```

```
Warning "Trying to access array offset on value of type null"
in /var/www/sites/hellomynameispete.com/www/live/textpattern/include/txp_diag.php at line 783.
```

```
textpattern/include/txp_diag.php:783 adminErrorHandler()
textpattern/include/txp_diag.php:201 checkUpdates()
textpattern/include/txp_diag.php:81 doDiagnostics()
textpattern/index.php:228 include()
```

```
Warning "Trying to access array offset on value of type null"
in /var/www/sites/hellomynameispete.com/www/live/textpattern/include/txp_diag.php at line 784.
```

```
textpattern/include/txp_diag.php:784 adminErrorHandler()
textpattern/include/txp_diag.php:201 checkUpdates()
textpattern/include/txp_diag.php:81 doDiagnostics()
textpattern/index.php:228 include()
```

```
Warning "Trying to access array offset on value of type null"
in /var/www/sites/hellomynameispete.com/www/live/textpattern/include/txp_diag.php at line 784.
```

```
textpattern/include/txp_diag.php:784 adminErrorHandler()
textpattern/include/txp_diag.php:201 checkUpdates()
textpattern/include/txp_diag.php:81 doDiagnostics()
textpattern/index.php:228 include()
```

![re](https://user-images.githubusercontent.com/226578/101196415-9b922400-3658-11eb-9160-5821d457604a.png)

**Comment by Bloke** [comment]
Please try that and report on its efficacy (or not).

Might be worth testing a brand new install with internet access switched off too, since that'll trigger the 'unable to connect to server' message from the get-go, which may well yield other problems we need to fix in this corner.

**Comment by petecooper** [comment]
That fixed it - muchas gracias!

**Comment by Bloke** [comment]
Oooh, bear in mind that the update check is ONLY triggered if the release is not dev. So it might not be showing up for you in tests unless you temporarily:

a) Hack your local textpattern/index.php and set `$txp_is_dev = false;`

OR

b) Edit txp_diag.php and comment out the `if (!txp_is_dev) {` and its corresponding close brace. lines 196 and 218 as of this writing.

**Comment by petecooper** [comment]
Crap. Please hold.

**Comment by petecooper** [comment]
Well, the error's gone away, which is super, but the `There was a problem connecting to the Textpattern update server. Please try again later.` remains.

**Comment by Bloke** [comment]
Okay, well that's good the error has gone. With regards the 'problem connecting' that should remain until:

a) Internet connectivity returns, and;
b) An hour(?) elapses. I think that was what we set the timeout to.

That'll clear the previous message and retry. Until then, it'll just throw you the last message it received to prevent swampage/DDOS.

**Comment by petecooper** [comment]
Fresh install, fresh db, so presumably no memory effect on the checks?

If I `tail` the server logs for any version.json checks, there are no hits from my site. I'll investigate further.

**Comment by Bloke** [comment]
Aye. A fresh db won't contain the `last_update_check` field and a fresh install set as 'live' (non-dev) or with those lines commented out should trigger an update check. You can do a check if you like by adding:

``` php
dmp($contents);
```

at line 782 of txp_diag.php. And/or:

``` php
dmp($response);
```
At line 784, viz:

``` php
    if (function_exists('curl_version')) {
        $ch = curl_init($endpoint);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $contents = curl_exec($ch);
    } else {
        $contents = file_get_contents($endpoint);
    }
dmp($contents);
    $response = @json_decode($contents, true);
dmp($response);
```

That'll tell you two things:

1) Whether the check is being called (by virtue of you getting some code dumped to the page).
2) What the contents of the version file is and then whether it can be successfully json_decoded.

If you get anything else (or nothing at all) when you visit the Diagnostics panel, then the check hasn't been run.

**Comment by petecooper** [comment]
Aside: could we weaponise this modification to show in verbose diags if the check fails? Or include the check results in the verbose diags regardless?

Overlap with https://github.com/textpattern/textpattern/issues/1423 but might be an easy win.

**Comment by Bloke** [comment]
Sort of, but since the check is only run once and the contents discarded, it's not much value. We could display the _result_ of the decision (as that's stored in the prefs table) but that's not much more info than is already displayed in the preflight info: "cannot connect to update server" or "new version a.b.c available". Doesn't tell you whether the check was run or not when you refreshed the page, just what happened last time it was run.

We could stash the actual result: the contents of the version file (if fetched) but that's not much use either.

What is of value in high diagnostics, however, is the timestamp of the last update check that was attempted. That is available in the database and would at least give you a clue when it was last run to help you diagnose stuff if you're donkeying around with the system.

We already add that to high diagnostics, BUT it's only shown if the last check yielded some results (a new version, or a failure to communicate with the server). Since that check doesn't run in dev mode, it's of limited use in anything other than a released environment.

Now, we could change this so that dev setups run the update check. Not sure there's value in that, because the implication is that dev is always the bleeding edge so there will never be a newer version than right now, but we _could_, if for no other reason than to test whether the checks were working prior to bundling a release.

Whaddya think?

**Comment by petecooper** [comment]
>Now, we could change this so that dev setups run the update check. Not sure there's value in that, because the implication is that dev is always the bleeding edge so there will never be a newer version than right now, but we could, if for no other reason than to test whether the checks were working prior to bundling a release.

I think there's value in the `dev` builds running checks, certainly. Anyone running `dev` code knows it comes with some extra frills for those on the ragged edge. One person's `dev` isn't necessarily the _latest_ `dev`, whether or not we can mobilise some sort of epoch check or similar to at least say "a newer in-development build is available".

And yes, very valid reason for the testing - when we roll out unit testing and the like, it'll be an easy thing to automate.

```
Update check timestamp: [epoch translated to local time format] (time elapsed in local time format)
Update check status: Success / Failure (http error code)
```

Bluntly, the .com `version.json` is not even remotely taxed access-wise, and it would be a great position to be in that we have to install a load balancer due to traffic! I'm not saying we should be promiscuous about checks, but we can afford to be a bit more liberal.

How we incorporate an epoch timestamp on the `dev` build, no idea. Perhaps a CI / CD runner could add it automatically after each commit?

**Comment by Bloke** [comment]
Okay, that's interesting. Hadn't thought of checking that there's "new commits for you so download the latest dev".

Yeah, this has legs so let's figure out how we do that.

**Comment by petecooper** [comment]
Fab. Spun out to a different issue: https://github.com/textpattern/textpattern/issues/1605 - thanks for the consideration, @Bloke.

**Comment by petecooper** [comment]
I should have some time this afternoon & evening to have another look at his, OP issue _is_ resolved – see https://github.com/textpattern/textpattern/issues/1597#issuecomment-739996038 for specifics – but I need to look into the notification mentioned in that link re: update check failing.

**Comment by petecooper** [comment]
Appears to be fixed - thanks @Bloke!
