### ISSUE TITLE
Diagnostics preflight check appends 'Help' to new version notification

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1608]
### Expected behaviour

Low detail Diagnostics shows a new version is available like this:

```
Pre-flight check: 
------------------------

New Textpattern version 4.8.4 available for download.
------------------------
```

### Actual behaviour

Low detail Diagnostics shows a new version is available like this:

```
Pre-flight check: 
------------------------

New Textpattern version 4.8.4 available for download. Help
------------------------
```

![re](https://user-images.githubusercontent.com/226578/102266767-cf9afe00-3f10-11eb-8c05-00838b15a006.png)

### Steps to reproduce

* Install Textpattern 4.8.3, visit Diagnostics, note diagnostics text.

#### Additional information

Textpattern version: 4.8.3

Web server vendor and version: Nginx 1.19

Database server vendor and version: Percona 8.0

PHP version: 7.4.13

**Comment by petecooper** [comment]
For completeness, 4.8.4 is also affected. If anyone has a solution but doesn't have the time or oomph to fix, please let me know the gist and I'll get to it.

![re](https://user-images.githubusercontent.com/226578/103274622-0154a000-49ba-11eb-9cf0-f63e542f02ad.png)

**Comment by Bloke** [comment]
More involved than expected, but 319dcdf should fix it, along with a few other bug fixes. Please test.

**Comment by petecooper** [comment]
Thanks @Bloke - should have some time this PM, will report back.
