### ISSUE TITLE
Remove support for SWF entirely

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1609]
Support for uploading .swf files from the Images tab was deprecated in 4.7.0, with a note that it would be removed entirely in a future version. Given Flash is [EOL'd at the end of 2020](https://www.adobe.com/uk/products/flashplayer/end-of-life.html), I propose we remove .swf functionality entirely from 4.10 onwards (or earlier if that's the consensus).

**Comment by philwareham** [comment]
Do it in 4.9 is my vote. Firefox had removed Flash support entirely in latest Dev Edition (which evolves to standard edition in January 2021).

**Comment by philwareham** [comment]
> Could this be part of the Imagick rollup? (or whatever we use?)

Image Intervention? Yeah it could form part of that, since my hope is we refector the whole image handling to use that library in 4.9 onwards.

**Comment by Bloke** [comment]
That's the puppy! Couldn't remember the name there. Yeah, it makes sense to do it all as a job lot. And a good excuse for _sorry if you use SWF, but time's are a changin'_

**Comment by phiw13** [comment]
Safari removed support for Flash in Version 14 (September 2020),
see: https://developer.apple.com/documentation/safari-release-notes/safari-14-release-notes

so, yes please, `rm -rf (with the prejudice flag)` :-).

**Comment by petecooper** [comment]
Reviving this - how viable is it for 4.9 realistically?

**Comment by Bloke** [comment]
It won't take much to remove it. I'll have a look.

**Comment by petecooper** [comment]
Thanks @Bloke - much appreciated!

**Comment by Bloke** [comment]
I can't find any way to upload or process a Shockwave Flash file in our code now. The only residual references to the .swf format remain in the Images panel in case there are SWF files already uploaded on the site from years ago, so it knows to skip thumbnail generation.

If we remove these branches then any existing swf files will be treated like regular thumbs and could break the admin panel. So I'm inclined to leave them intact.

As far as I can tell, support is no more. You can't upload them as Images. You can't assign one, and even if you hack the database to add one, you can't do much with it. Support was removed ages ago in the `get_safe_image_types()` function so as far as I can see, it's dead format from Txp's perspective.

**Comment by petecooper** [comment]
+1, @Bloke – thank you for checking.

Flash era is done. Closing.
