### ISSUE TITLE
Verify checksums during install preflight

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1613]
### Is your feature request related to a problem?

Yes, but it's minor.

### What is the feature?

Install preflight routine checks files against `checksums.txt`; warns if anything differs, silent if all is well.

I've just burned about two hours figuring out a white screen of death as the first thing after logging in. It transpires something got garbled on the file transfer, and at least two files differed (I stopped counting at two). A fresh upload fixed it, of course, but the dead-end of a white screen was embarrassing.

(I get the installer is fairly sacred ground, hence RFC. Come at me, bros. And thanks for reading.)

**Comment by Bloke** [comment]
That's a brilliant idea.

As long as we have the file checksum routine available to the installer (I'll have to check) then there's nothing to stop us giving the files a once over.

If we can do this, at what step do we mention it? Presumably asap, so step 2, after language selection, at the top of the connection credentials screen? Any better ideas?

Might requite a duplicate langs string for "the following files have changed:" but at least it won't require translation, as we already have the translations for those and can copy them into setup_lang.

**Comment by philwareham** [comment]
Strings added.

**Comment by philwareham** [comment]
Is this completed now?

**Comment by Bloke** [comment]
As far as I'm concerned, yes.
