### ISSUE TITLE
Keyboard shortcut for Save on Pages and Files panels stopped working

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1617]
(4.9.0-dev)

Pressing `command-s` or `ctrl-s` has no effect. Pressing /tapping the button still works fine. I guess a side effect of the @philwareham  layout work.

PS - Style panel untested but presumed to suffer from the same.

**Comment by philwareham** [comment]
Will fix when I get a moment - unless someone else wants to deal with. Probably just a selector change needed in JS.

**Comment by philwareham** [comment]
Need to keep this open, as although I've put a band-aid on it the code needs to be redone to make this globally useful (at the moment my code relies on the submit button having a `form` attribute stated.

**Comment by phiw13** [comment]
Well, your fix “works” on the Pages and Forms panels. Nice. But now the KB shortcut stopped working on the Edit panels (Presentation > Sections , Themes, Content > Files, Images,…, Admin > Preferences, … )

[selfish] Having it work on the Pages & Forms panels is more important on these TXP 4.9 test installs, atm.

**Comment by philwareham** [comment]
I had an epiphany on how to fix this better during the night, will amend later today.

**Comment by phiw13** [comment]
Yes now works fine everywhere. Thanks.
