### ISSUE TITLE
Merge dev into custom-fields branch

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1618]
Just a note to ourselves - we need to merge dev into custom-fields branch and fix the merge conflicts within. Then the custom fields work can continue.

**Comment by bloatware** [comment]
Will do when I'm back home (and probably after 4.8.5 release?)

**Comment by bloatware** [comment]
Rather surprisingly, it seems to work somehow.

**Comment by Bloke** [comment]
Wow. It totally borked last time I tried it, but I guess with the recent changes that have refactored some of publish.php it's made it a simpler merge.

Thank you so much for doing that. I'm going to spend some time on this branch and get it to a usable state we can actually merge into dev.

**Comment by bloatware** [comment]
This would be ace! I will revisit it too as soon as 4.8.5 is out.

**Comment by philwareham** [comment]
This was done. Closing.
