### ISSUE TITLE
Custom field order differs on Write panel

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1621]
### Expected behaviour

Custom fields appear in the order they are set in Preferences -> Custom fields.

### Actual behaviour

Custom fields do not appear in the order they are set in Preferences -> Custom fields.

### Steps to reproduce

* Install vanilla Textpattern 4.8.3
* Note default custom fields names:

![Screenshot 2021-01-02 at 16 09 12](https://user-images.githubusercontent.com/226578/103461326-748d4780-4d15-11eb-8080-8124b824fda1.png)

* Note custom field order on Write tab:

![Screenshot 2021-01-02 at 16 09 26](https://user-images.githubusercontent.com/226578/103461327-77883800-4d15-11eb-8cd5-c1128029ddb8.png)

#### Additional information

Textpattern version: 4.8.3 and `dev` tested, presumably 4.8.4 and `4.8.5` also affected.

Web server vendor and version: Nginx 1.19

Database server vendor and version: Percona 8.0

PHP version: 7.4.13

I added some more CFs to ensure it was reversed and not just the default two being swapped:

![Screenshot 2021-01-02 at 16 14 46](https://user-images.githubusercontent.com/226578/103461360-bcac6a00-4d15-11eb-9b68-d0887bc52f69.png)
![Screenshot 2021-01-02 at 16 14 56](https://user-images.githubusercontent.com/226578/103461361-be762d80-4d15-11eb-92fe-9c4ab270d8e5.png)

Edit: actually, it's not reversed, there's something afoot `baz` should be last / first and it's not. Investigating, will update with reply.

**Comment by petecooper** [comment]
Strange. Order is mostly reversed, but CF 7 seems to appear first (if set):

![Screenshot 2021-01-02 at 16 26 53](https://user-images.githubusercontent.com/226578/103461595-7d7f1880-4d17-11eb-94bf-9baf51472b08.png)
![Screenshot 2021-01-02 at 16 27 04](https://user-images.githubusercontent.com/226578/103461598-807a0900-4d17-11eb-9dea-7265492b59cd.png)

**Comment by Bloke** [comment]
Waaaaaht?! I can't even discern the order there. It's not by name, as that would put z or one of the symbol fields first/last. It's not by custom_N because otherwise it'd go 1, 10, 2, 3, 4, 5 (or reverse).

That is freaky.

**Comment by petecooper** [comment]
>That is freaky.

To be fair, 2020 was a funny year. Can you reproduce your side on a 4.8 instance?

**Comment by jools-r** [comment]
Not sure if it's related but I found that when updating the jcr_{file/image/section/link}_custom plugins recently (also testing with php8/mysql8) that the fields in the UI were not always being output in the correct order. It seemed the `preg_grep` function that retrieves the `custom_x_set` rows from the `$prefs` array keys wasn't always extracting them in order. My guess was it was extracting them in the order they were created or last modified.

Seeing as I only have up to five custom fields for those plugins, I added an `asort` to order the results which resolved that (see [this line](https://github.com/jools-r/jcr_file_custom/blob/60e06f68d5b6ee09a41d78f492df8182d58f6e30/jcr_file_custom.php#L215) for example). The code in those plugins is pretty much the same as [this line in getCustomFields()](https://github.com/textpattern/textpattern/blob/bd9fc848c3155bca56aca1cb0a4e9824e8b11b81/textpattern/lib/txplib_misc.php#L4071) in txplib_misc.php.

**Comment by petecooper** [comment]
My gut feeling says this might be a MySQL 8.0 (or off brand remix) quirk, that's the common factor with the testing I've done. Will continue to investigate.

**Comment by Bloke** [comment]
Baffling but entirely probable that they're coming out of the database in last modified order (or something) and we're assuming iin code they are retrieved in key order. Using `ksort()` - a bit like Jools has done - will reorder them by key, but unless we choose numeric sorting, they'll be in 1, 10, 2, 3, 4, 5, ... order. Hmmm.

Would be nice to find out in which part of the stack the variable lies, but we can probably work around it regardless with a jot of code.

**Comment by bloatware** [comment]
I would suspect that `ORDER BY FIELD(user_name, ".$user.")"` used in `get_prefs()` does not care about cf names.

**Comment by petecooper** [comment]
>Baffling but entirely probable that they're coming out of the database in last modified order (or something)

Doesn't appear to be last modified.
