### ISSUE TITLE
Consider replacing file_exists() where appropriate

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1623]
PHP's `file_exists()` call checks whether a file exists. [is_readable()](https://www.php.net/manual/en/function.is-readable.php) checks whether a file exists and is readable, which seems more useful because knowing whether it exists and being able to actually read it are very different.

Should we go through core and, softly softly as we find them, swap out `file_exists()` calls for `is_readable()` for more robust file/resource handling? That way, if a file exists but is unreadable, we'll fail more gracefully than if we find it's there, assume it's readable, open it, find we can't, and all hell breaks loose... comparatively speaking.

Any downsides to swapping these calls out?

**Comment by Bloke** [comment]
Just an addendum to this. Does anybody know which is less error-prone:

``` php
if (file_exists($file['tmp_name'])) {
    unlink($file['tmp_name']);
}
```
``` php
if (is_readable($file['tmp_name'])) {
    unlink($file['tmp_name']);
}
```
``` php
if (is_writeable($file['tmp_name'])) {
    unlink($file['tmp_name']);
}
```

?

We use the first construct in a few places throughout core. But does the _existence_ of the file mean it can be successfully deleted? Does the OS need write permissions to delete a file? Or just read?

**Comment by bloatware** [comment]
IIRC, it's the containing directory that must be `is_writeable`, not the file itself. Then we should check for `if_file` to unlink it, or for `is_dir` to `rmdir` it (once emptied).

**Comment by Bloke** [comment]
That rings a bell, thanks. So how about:

``` php
if (file_exists($file['tmp_name']) && is_writeable(dirname($file['tmp_name']))) {
    unlink($file['tmp_name']);
}
```

Is that more complete?

**Comment by bloatware** [comment]
Hmm, not sure `file_exists()` makes a difference between file and dir, and not sure whether one can `unlink()` a dir, needs confirmation. But `is_file()` in place of `file_exists()` could work. Some people say also `unlink(realpath($file['tmp_name']))` is more reliable.

**Comment by Bloke** [comment]
We could do that, no problem.

I'm fine with leaving it as it is, but in the interests of minimising potential PHP errors (and also as part of "operation remove error suppression") it just struck me that file_exists() only tells part of the story so if there was a better way to do it, that's what this topic is about.

**Comment by Bloke** [comment]
Okay, I think I've done all I can here. I've left some of the `file_exists()` calls alone where they make sense to use them. I've also left some `unlink()` calls intact without wrapping them in `realpath()`. Sometimes this is because it's already applied, sometimes I'm not sure if it matters because the files are built from well-known components. We can revisit this if necessary and add wrappers in future if we feel it's safer.
