### ISSUE TITLE
RFC: Let <txp:images> tag process <txp:else />

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1625]
As it says on the tin, should we retrofit the `<txp:images />` tag so instead of it just returning nothing if it finds no matching images that it parses any `<txp:else />` in its container?

In theory that would allow things like:

``` html
<txp:images name="my-pic.png" size="landscape">
   <txp:image />
<txp:else />
   <txp:image name="placeholder.png" />
</txp:images>
```

Any drawbacks?

Or is it better to add a `default` attribute instead with the name of a fallback image?

``` html
<txp:images name="my-pic.png" size="landscape" default="placeholder.png" />
```

(though that won't have any notion of _which_ other attributes were attempted so the default will always be static).

**Comment by philwareham** [comment]
Well, we allow the `<txp:else />` tag within an `<txp:article_custom>` tag (which I only found out about a few weeks ago), so I'm open to using it here too. I'd prefer that to having a default attribute as it's much more flexible (you could have any code in there instead of just a simple image link). So it's a yes from me.

Caveat is that we need to have some thought on the whole responsive images handling in Textpattern at some point, if and when the images improvements come along. I can't see the above affecting that directly though.

**Comment by bloatware** [comment]
Then we should add it to `file_download_list` and `linklist`, for consistency.

**Comment by bloatware** [comment]
And you know that `default` is global, and that this should work too:
```
<txp:evaluate>
<txp:images name="my-pic.png" size="landscape">
   <txp:image />
</txp:images>
<txp:else />
   <txp:image name="placeholder.png" />
</txp:evaluate>
```

**Comment by Bloke** [comment]
Ah, thanks for the reminder about  `default` being global. I'd forgotten, and it didn't seem to work in my tests, but it was because I was actually using a more complex example where the filename was passed into a shortcode via `<txp:yield />` (which in turn was the result of a `<txp:section />` tag). This construct essentially uses a generic 'responsive_image' shortcode to render a banner image with the same name as the section. What I was trying to do was to detect when an image wasn't found so that the site didn't throw an error if a new section is added without a corresponding image.

I'll test it again, as there may be a logic error in my shortcode. But If the solution is simply to wrap the tag in `<txp:evaluate>` then I'll do that for now as it probably works better than `default` in this case.

Maybe we don't need this request then. It just seems like we've added '<txp:else />` support to many other tags (as Phil noticed) and the other content type *list tags seem to be an exception at the moment.

**Comment by bloatware** [comment]
Oh, this global `default` is rather dumb. It just checks if the trimmed tag output is empty, so if your shortcode contains something else, `default` will not apply. There is no problem adding `<txp:else />`, it should be just few lines of code, just wanted to remind other possibilities.

**Comment by jools-r** [comment]
👍, 👍, and 👍 to txp:else cases in the common loop tags. Always useful to have that option.

**Comment by bloatware** [comment]
Please test.

**Comment by philwareham** [comment]
Keeping this open until testing is undertaken.

**Comment by philwareham** [comment]
Works in my testing here, thanks Oleg.
