### ISSUE TITLE
New message panels superposed over save buttons

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1627]
### Expected behaviour

Full access to 'Save' button

### Actual behaviour

I noticed a weird experience with the new message pane components within Textpattern. Its full width outside container is superposed over the "Save" button (with no ability to click inside). It's a real fact: when we work on a website development, we often haven't the time to close these panels.

Maybe you could consider one of these solutions:

1.° change the display property (that's the only one I found to limit the width to each border):

    #messagepane {
        display: inline-table
    }

2.° reduce the default textarea's height:

    .presentation textarea.code {
        height: 61vh
    }

### Steps to reproduce

Save a form within the Textpattern interface then try to click again on the "Save" button.

#### Additional information

Textpattern version: 4.9-dev

Web server vendor and version: not relevant for the CSS context.

Database server vendor and version: not relevant for the CSS context.

PHP version: not relevant for the CSS context.

**Comment by philwareham** [comment]
This is a work-in-progress. See https://github.com/textpattern/textpattern/issues/1598. Closing, thanks.
