### ISSUE TITLE
Disable TAB in input fields for pages/forms/styles

### ISSUE THREAD

**Issue by blekknajt** [textpattern/textpattern#1628]
### Is your feature request related to a problem?

When editing pages/form/styles pressing tab key goes to next focusable element.

### What is the feature?

Radio button to disable it for input area.

**Comment by petecooper** [comment]
I will admit I do most of my page / form / style editing in an external editor and then copy / paste into the relevant places in the admin-side because of the current tab-to-next workflow…so I can add a light +1 to @blekknajt's OP, but it's not a deal breaker.

I'm not _au fait_ with how this would affect accessibility in real-world terms - paging @phiw13 for comment, if appropriate.

**Comment by bloatware** [comment]
There are also other textarea [enhancements](https://forum.textpattern.com/viewtopic.php?id=51322) we might consider good for 4.9, please discuss.

**Comment by phiw13** [comment]
> I'm not au fait with how this would affect accessibility in real-world terms - paging @phiw13 for comment, if appropriate.

Hmm… disbling `TAB` for input fields would ofcourse be a usability and accessibility issue. That said, **IF** it is a yes/no _per user_ (advanced) preference setting, then maybe it can be OK. It should, no make that MUST per W3C grammar, be per user, you would not want all registered authors/users be affected by the taste of one user.

**Comment by phiw13** [comment]
> There are also other textarea enhancements we might consider good for 4.9, please discuss.

That might be an other one of those things that warrant a _per user_ setting. Not yet opining on the pro/contra of having the Pages an Forms textareas “enhanced”, as I barely use them anymore

**Comment by philwareham** [comment]
I'm not usually keen on changing the default behaviour of browsers - however I can see some value to this suggestion (although I use spaces for tabs myself).

If a disable button was used, you could also follow the GitHub route of allowing tabbing in editor windows AND using `option`+`TAB` and its PC equivalent to still let keyboard users tab out of the textarea.

**Comment by petecooper** [comment]
>If a disable button was used, you could also follow the GitHub route of allowing tabbing in editor windows AND using option+TAB (and its PC equivalent) to still let keyboard users tab out of the textarea.

That sounds eminently reasonable to me. +1.

**Comment by Bloke** [comment]
Me too! I don't use tabs, but I know many do.

**Comment by phiw13** [comment]
> If a disable button was used […]

I would still prefer a per user preference setting (and if you would put that sort of button on the Pages and Forms panels, I surely hope it would be out of the tab  chain).

**Comment by philwareham** [comment]
> I surely hope it would be out of the tab chain

Of course (otherwise it gives keyboard-only users a method to break their UX).

**Comment by Bloke** [comment]
Yeah, I meant this sounds good (in general) to have a way to enable tabs in textareas. Whether this is done at the panel level and there's a setting (out of the tab chain as you say) which is remembered per panel, or if it's a per-user preference that operates on the entire back-end, I'll leave to the UX gurus.

Follow-up: if we went the prefs route, would it only apply to Presentation textareas, or do we include things like Article body+excerpt too? And plugins that have them? We need to be careful not to trample on WYSIWYG syntax highlighters editors (such as codemirror) that I know some people use on the Pages/Forms panel and also provide tab insertion in textareas (I think).

Hmmm, thinking about that, a local pref per textarea might make more sense if we can do it without too much clutter. A way for plugins to add their own would also be a bonus so anyone who wanted to enable tabbing in other fields can add a standard checkbox control and benefit from consistent UX without having to ensure they manually remove the widget from the tab chain, and so forth. That might be something we do in 4.9 with the UI class library.

**Comment by bloatware** [comment]
I'd suggest we just transform `Shift-Space` to `Tab` (indent), without complicating any further.

**Comment by bloatware** [comment]
Once `tab-size` css rule is adjusted in themes, this can be closed, I think. Use `Shift+Space` to indent.

**Comment by philwareham** [comment]
Hi - what adjustment do I need to make to the CSS `tab-size` rule? (currently it's `tab-size: 4` which is my usual preference, do you want it to be `2` instead?)

**Comment by philwareham** [comment]
I can expose the `tab-size` CSS in the user CSS file too, which gives users more control of it themselves.

**Comment by philwareham** [comment]
OK, my latest commit should provide the correct tab rules as requested.

**Comment by Bloke** [comment]
The only thing with using 4 is that the textareas aren't usually that wide so code quicky wraps. Would it present any advantage to using 2 or 3 by default?

**Comment by philwareham** [comment]
Sure, I can default it to `2` and leave `4` as the custom file one? (basically reverse of what it currently is)

**Comment by bloatware** [comment]
The default theme uses 4 spaces indents, fwiw. Two might be less readable. Poll?

**Comment by Bloke** [comment]
I don't mind, honestly. Was just throwing it out there based on my experience of using the panels.

3 as a compromise?

**Comment by philwareham** [comment]
Vote away - https://github.com/textpattern/textpattern/discussions/1901

Feel free to let people know in the forum to if you wish.
