### ISSUE TITLE
The header TXP tag doesn't work anymore...

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1629]
It seems with current 4.8.5-dev the header TXP tag doesn't work as previous TXP version.

To be confirmed by Devs.

### Actual behaviour

Page are always served into txt/html headers despite the use of <txp:header ... />

### Steps to reproduce

Create a page and try to set another content type header in the very top line.

#### Additional information

Textpattern version: 4.8.5-dev

Web server vendor and version: {Please write here}

Database server vendor and version: {Please write here}

PHP version: {Please write here}

**Comment by bloatware** [comment]
Oops. It works, but you have to set both name and value:
```
<txp:header name="content-type" value="text/plain" />
```
Will try to restore 4.8.4 defaults, sorry.

**Comment by bloatware** [comment]
Should be fixed, though I prefer the explicit
```
<txp:header name="content-type" value="text/plain" />
```
to
```
<txp:header value="text/plain" />
```

**Comment by cara-tm** [comment]
Yep. It works for current `4.8.5-dev` version:

    <txp:header name="content-type" value="text/plain" />

**Comment by bloatware** [comment]
If setting name/value pair is ok, I will rerevert it: I really don't like `<txp:header value="text/plain" />` as shortcut for `<txp:header name="content-type" value="text/plain" />`.

**Comment by Bloke** [comment]
Note to selves: we'll need to [change the tag doc](https://docs.textpattern.com/tags/header) to get rid of the default values for both attributes, if both attributes are required.

**Comment by petecooper** [comment]
>I really don't like `<txp:header value="text/plain" />` as shortcut for `<txp:header name="content-type" value="text/plain" />`.

+1.

>Note to selves: we'll need to change the tag doc to get rid of both default values, if both attributes are required.

I've opened an issue over there (see https://github.com/textpattern/textpattern.github.io/issues/188), I think we can close this.
