### ISSUE TITLE
Consider adding output of `php_uname()` to extended diagnostics

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1632]
### Is your feature request related to a problem?

Not directly, but it'd help to diagnose some problems I've had in the past.

### What is the feature?

Consider adding the output of `uname -a` to extended diagnostics so give some insight into the details of the operating system, if the system is POSIX-compliant / UNIX-like. Example output, single-liner, no whacky characters:

```
$ uname -a
Linux hostname 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

We already have good visibility into the workings of the web server + PHP + db stack, this would be useful complementary info in case of problems. Restricting to extended diagnostics means it's not cluttering the standard diagnostics.

**Comment by Bloke** [comment]
Good idea. Two things:

1. We need to make sure we don't try and run it on Windows servers :)
2. Do you think we need to add this to the set of 'obfuscateable' content when you click the privacy checkbox at the top of the panel?

**Comment by petecooper** [comment]
Thanks, @Bloke.

>We need to make sure we don't try and run it on Windows servers, which you've mentioned but is a note-to-self :) Are there any ways to reliably detect if we can run it? And do you know of any systems that might have it available but forbid it from being run from a web server for security reasons?

High level: if it's runnable by PHP, and has output (or error code 0, however you play it), then it's displayed…otherwise, just move to the next item.

>Do you think we need to add this to the set of 'obfuscateable' content when you click the privacy checkbox at the top of the panel?

Yes. There's a chance the hostname might leak an IP address or org name (e.g. `123-123-123-123.hosting.example.com`).

**Comment by Bloke** [comment]
Intriguing... PHP has a built-in function for it that must do the Windows stuff for us...

https://www.php.net/manual/en/function.php-uname.php

Note the caveat though:

> keep in mind this constant will contain the operating system PHP was **built on**.

Is that likely to be a problem do you think?

**Comment by petecooper** [comment]
>Using a PHP call seems safer than relying on a system call to uname.

I concur. And it's better than nothing, so gets my vote. We could give it a spin in `dev` to see how it plays before committing to it, perhaps?

**Comment by petecooper** [comment]
https://www.php.net/manual/en/function.php-uname.php

>keep in mind this constant will contain the operating system PHP was built on.

My interpretation of that note is that it refers to `PHP_OS`, _not_ `php_uname()`.

**Comment by petecooper** [comment]
I wonder if this might be best handled as a parenthetical suffix of 'Server OS' in extended diagnostics, i.e. in Low diags it shows barebones info, but High diags tacks on the `php_uname()` output. Is there enough granularity to do this in diags, or would it need its own line item?

**Comment by Bloke** [comment]
How about that? 37827529

Rather than output uname -a, which includes hostname, we simply do this:

1. In Low diagnostics mode, output OS + Release (as it does now).
2. In High diagnostics mode, tack on Version and Machine Type.

That bypasses any security info leakage which means the _Hide private information_ checkbox still works without extra hackery.

**Comment by petecooper** [comment]
Perfect!
