### ISSUE TITLE
PHP 8.0.x - changing language causes 500 Internal Server Error on MAMP Pro

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1633]
### Expected behaviour

If more than one language is installed - either change the site language or user language using the `<select>` element on languages panel.

### Actual behaviour

Causes a 500 Internal Server Error on my local MAMP setup if I'm running PHP 8.0.0 or 8.0.1 (works fine on PHP 7.4.14 and earlier.

#### Additional information

Textpattern version: produced the above error on Textpattern 4.9.0-dev and 4.8.5 (but I assume affects 4.8.4 too).

PHP version: 8.0.0, 8.0.1

**Comment by bloatware** [comment]
Seems to work fine on XAMPP PHP 8.0.0

**Comment by petecooper** [comment]
>Causes a 500 Internal Server Error on my local MAMP setup if I'm running PHP 8.0.0 or 8.0.1 (works fine on PHP 7.4.14 and earlier.

Anything sensible in the PHP error log, Phil?

**Comment by petecooper** [comment]
I've tried this with 8.0.0 and 8.0.1 native (Linux not MAMP) and cannot reproduce.

**Comment by philwareham** [comment]
Ok I’m sure it’s a glitch in my setup - don’t worry.

**Comment by petecooper** [comment]
Following up - this might be addressed with recent commits relating to the `en` locale.

Assigning to @philwareham as OP for feedback in due course.

**Comment by philwareham** [comment]
Fixed.
