### ISSUE TITLE
Tiny SVG TXP icon

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1636]
### Is your feature request related to a problem?

No. This demand concerns TXP reputation and marketing.

### What is the feature?

@philwareham:
All tools have an SVG icon (i.e.: https://simpleicons.org/)
In order to share the TXP branding, we need a simple and tiny icon (`viewBox="0 0 24 24"`) in SVG format included its official colors.

**Comment by philwareham** [comment]
This can be done, but stored where exactly?

**Comment by petecooper** [comment]
In the absence of anywhere else, would https://github.com/textpattern/textpattern.github.io/tree/master/brand be suitable?

**Comment by philwareham** [comment]
We already have a branding repo that houses our logos. It should go in there probably. There may already be one there to be honest - haven’t checked it for a while. The repo zip can be linked where we see fit.

**Comment by philwareham** [comment]
@cara-tm I've created a an icon and it's been merged into the simple-icons repo now, please see https://github.com/simple-icons/simple-icons/commit/6921681a6c011e1bae8072f17f62aec2939c7b52

I have attached a black and a white version below too, in case you want it for other uses.

Next time I do a tag release of [the Textpattern branding repo](https://github.com/textpattern/textpattern-branding), those icons will be included.

Cheers.
[simple-icons.zip](https://github.com/textpattern/textpattern/files/5960285/simple-icons.zip)

**Comment by cara-tm** [comment]
https://simple-icons.github.io/simple-icons-website/?q=Text

**Comment by philwareham** [comment]
Cool, it’s live.

**Comment by cara-tm** [comment]
Firefox PC and Dark Mode system enabled ;) 

![Firefox PC](https://i.ibb.co/vCN8Qqz/ff-prefered-pages.png)
