### ISSUE TITLE
Read-only theme directory presents different notification files / images

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1640]
Images:

![Screenshot 2021-02-21 at 13 47 56](https://user-images.githubusercontent.com/226578/108627080-abe1c000-744b-11eb-9412-f936fa31e0ea.png)

Files:

![Screenshot 2021-02-21 at 13 47 43](https://user-images.githubusercontent.com/226578/108627085-b13f0a80-744b-11eb-8b8a-f66e7245f5ba.png)

Themes:

![Screenshot 2021-02-21 at 13 48 06](https://user-images.githubusercontent.com/226578/108627108-c3b94400-744b-11eb-8d02-a7068a7f1588.png)

Note the `{}` wrapper on the themes warning.

Is this intentional, given there's >1 directory involved and >1 item may be presented?

**Comment by philwareham** [comment]
@bloke this is rendered by https://github.com/textpattern/textpattern/blob/eb4038580332abcdad6e2f9154acf44297fc2111/textpattern/vendors/Textpattern/Skin/Skin.php#L1232 but I don't know how to fix it myself.

**Comment by Bloke** [comment]
Balls. The physical strings are different because the Theme message is generic for any type of content, but those braces shouldn't be there. The line Phli highlighted in the code should read:

```
gTxt('path_not_writable', array('{list}' => $this->getDirPath())),
```

**Comment by petecooper** [comment]
It can wait, it's trivial.

**Comment by Bloke** [comment]
Only one line to change. Easy bug fix.
