### ISSUE TITLE
Locale issue on local server (MAMP) breaks setup in PHP 8.0

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1642]
### Expected behaviour

Installation goes smoothly on MAMP (and others?)

### Actual behaviour

Internal server error thrown, or 'connection has been reset' when the httpd process dies during installation.

### Steps to reproduce

* Install MAMP.
* Select PHP 8 from the interface.
* Run textpattern/setup.
* At the last stage during database creation, the server process dies.

#### Additional information

Textpattern version: 4.8.5-dev.

Web server vendor and version: MAMP 6.3 (Apache or Nginx).

Database server vendor and version: MySQL 5.7.32.

PHP version: 8.0.0

This issue stems from our `setLocale()` routine in vendors/Textpattern/DB/Core.php. Trying to call PHP's `setlocale(LC_TIME, null)` or `setlocale(LC_TIME, '')` breaks the process.

This also affects language switching of the _front end language only_ (not admin language!) from the Admin->Languages panel. See #1633.

A possible fix is to add an 'en' entry to the `$locales` array in the Locales.php class but that only masks the issue not fixes it per se: there may be other languages that aren't represented here that will trigger this (although since we don't support them officially it might be okay).

The situation is fine on MAMP running PHP 7.4 so either:

a) Something has changed in PHP 8 that needs configuring/setting to default in the environment (if we find the culprit, can we check what it is and set it to some sensible default in the code?).
b) Something is broken in MAMP 6.3 (which may be related to not setting something above).
c) Something is not set at the OS level (macOS in this case) or at least not being drawn into the PHP 8 environment from the OS.
d) We need to defensively code around this situation and just _not set the locale at all_ if we can't find it in our mapping table. This seems sensible since we don't support languages that aren't in that list.

**Comment by philwareham** [comment]
I’ve skimmed the internet and it’s suggested that US English is a pretty safe fallback locale (I’ve updated the line in latest commit). Maybe you can put some defensive code in that falls back to that if the locale isn't recognised/in our list?

**Comment by Bloke** [comment]
Thanks.

Sure, we could fall back on "en-us" instead of null/empty (which then looks up the system default and seems - in this case - to not be set at the system level). Most other calls to this function from other parts of our ecosystem seem to fall back on "C" but I _think_ that's only the case on *nix environments and, even then, is not guaranteed. I don't really know enough about locales to say either way.

**Comment by philwareham** [comment]
Fixed.
