### ISSUE TITLE
config.php file localization

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1647]
### Is your feature request related to a problem?

No.

### What is the feature?

With multisite feature, we can customize the access to the back-office. When we install a single Textpattern website on a server, we do not customize our URLs (front-end and back-end). I noticed the only one reference to the administration interface is set as this (`root/index.php`):

    if (!defined('txpath')) {
        define("txpath", dirname(__FILE__).'/textpattern');
    }

Is there a reason to locate the `config.php` file into the `/textpattern` folder? If this file will be into the `/root` the `txpath` global PHP variable could be adapted depending on our needs.  Is this request make sense?

**Comment by petecooper** [comment]
This could be considered alongside the discussion in https://github.com/textpattern/textpattern/issues/1440 - if I understand the issue correctly…I have little experience of multisite recently, paging @jools-r for any comment.

**Comment by jools-r** [comment]
On the current multisite setup you have:
```
/sites
    /admin     = admin root
    /private … config.php
    /public    = public root
```

and the `/admin/index.php` file in the admin.php links to `@include '../private/config.php';`. If you assign those to individual subdomains, you can use whatever naming scheme you want.

I guess there several issues here:
- Moving config.php out of a web-accessible root for better security
- Changing the admin URL to something other than `/textpattern`.
- Not accidentally deleting config.php (or other folders like plugins) when updating.

If we were to move config.php out of /textpattern, it could go into its own folder such as `/private` or `/cfg`.

> Although better security, it might be a barrier to adoption to ask users to move config.php outside docroot …

Another aspect here is if you use a backup service to keep copies of your installations. You don't want to accidentally omit the all-important config.php.

**Comment by Bloke** [comment]
Yes, all those points are valid and would be solved by shuffling things around. The backup angle is also vitally important. Good point!

I'm all up for migrating our main directory structure to mirror that of multi-site. That allows even tighter limits to be applied to /private (or /cfg, or whatever we call it), which is a boon. Does multi-site use /private for anything else? Plugin prefs or supplemental data? Shared content of a secure nature? Public keys perhaps?

**Comment by jools-r** [comment]
> Does multi-site use /private for anything else? Plugin prefs or supplemental data? Shared content of a secure nature?

Not that I know of. I've used it to place source files for assets, instructions or site notes. I suppose one could use it for things like storing digital files only downloadable via from the homepage, e.g. via some pw-protected or pay mechanism. In the same vein, one might one potentially place the /files folder in there so that downloads are truly only accessible via `/file_download/xxx/file-name.pdf` links.

What I can't remember is whether the /private folder is actually hidden if you use the subfolder approach rather than two subdomains for the /admin and /public folders. Must test that again.

**Comment by bloatware** [comment]
I don't think we should be eternally bound by bw compatibility. Look at PHP8...

**Comment by cara-tm** [comment]
> 
> 
> This could be considered alongside the discussion in #1440 - if I understand the issue correctly…I have little experience of multisite recently, paging @jools-r for any comment.

Exactly. Didn't see this request...

**Comment by petecooper** [comment]
Closing. See https://github.com/textpattern/textpattern/issues/1440 for related issue, with notes. Thanks @cara-tm for discussion.
