### ISSUE TITLE
Article syndication does not correctly output latest article(s)

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1649]
See https://forum.textpattern.com/viewtopic.php?id=51405 for background and https://forum.textpattern.com/viewtopic.php?pid=329133#p329133 for confirmation by @bloatware.

Barebones issue for tracking, please edit or update without prejudice.

**Comment by bloatware** [comment]
It's not solely RSS feed problem, which is easy to fix per se. It comes from  [unset($GLOBALS['thisarticle']);](https://github.com/textpattern/textpattern/blob/74229b33a13e9c56b59536bf73b6b2c254fa7571/textpattern/publish.php#L1163) in `doArticles()` function used in `article[_custom]`, and can potentially emerge somewhere else. Removing this line seems to work, but wish I understood what problem it was intended to solve.

**Comment by bloatware** [comment]
This should be fixed for feeds now, but please keep the issue open for 4.9.
