### ISSUE TITLE
Custom "Body" & "Excerpt" labels

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1652]
### Is your feature request related to a problem?

Not at all.

### What is the feature?

For the next release (4.9.x) and the project of unlimited custom fields, did you envisage allowing, via some preferences' configuration, changing the labels of "*Body*" and "*Excerpt*" for the "Write" page?

I know there is a plugin for this customization. But it seems that'll not be a big work to add such feature (via `get_pref()` and the default labels as fallback). My request come from my clients uses: each website is different from the other and "articles" writing can have a special signification based on websites purposes.

**Comment by philwareham** [comment]
Hi. Covered by issue https://github.com/textpattern/textpattern/issues/1512. Please direct any feedback there.

**Comment by cara-tm** [comment]
Oh. Didn't see it. Sorry...
