### ISSUE TITLE
Error 503 doesn't call forms

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1658]
### Expected behaviour

When issuing a site maintenance 503 message, the error_default or error_503 form can call other forms correctly.

### Actual behaviour

~~~
<txp:output_form form="body_header" /> ->  Textpattern Notice: Form not found. .body_header while parsing form None on page default
textpattern/lib/txplib_misc.php:3339 trigger_error()
textpattern/lib/txplib_misc.php:3369 fetch_form()
textpattern/publish/taghandlers.php:532 parse_form()
output_form()
textpattern/vendors/Textpattern/Tag/Registry.php:140 call_user_func()
textpattern/lib/txplib_publish.php:544 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:406 processTags()
textpattern/lib/txplib_misc.php:4414 parse()
textpattern/plugins/smd_at_work/smd_at_work.php:44 txp_die()
textpattern/lib/txplib_misc.php:1578 smd_at_work()
~~~

Notice the dot prefixing the form name in the error message... is that relevant?

### Steps to reproduce

* Ensure your error_default page has a call to a form in it via `<txp:output_form form="some_form" />` or shortcode `<txp::some_form />`.
* Set production status to debugging.
* Install [smd_at_work](https://github.com/Bloke/smd_at_work/releases/tag/v0.41).
* Switch maintenance mode on in the plugin prefs.
* Visit the site in a non-logged in browser.

#### Additional information

Textpattern version: 4.8.5-dev
Web server vendor and version: Apache/2.4.18 (Ubuntu)
Database server vendor and version: 5.6.47-87.0 (Percona Server (GPL), Release 87.0, Revision 9ad342b) 
PHP version: 7.3.18-1+ubuntu16.04.1+deb.sury.org+1

Paging @bloatware Is it just the plugin, or is this a core issue? 404s seem to work just fine. All the plugin does is issue a `pretext_end` callback to `txp_die()` with status 503.

**Comment by bloatware** [comment]
It looks like as if `$pretext['skin']` were empty, though it should be already populated on `pretext_end`. Will test.

**Comment by bloatware** [comment]
It's a core bug: `output_form()` uses `global $skin`, but `$pretext` is not yet extracted at this step. A fix is easy, but which one to choose?

**Comment by bloatware** [comment]
Given the number of `global $s` etc calls in core, I'm actually surprised this bug has not been discovered before. Should we extract `$pretext` before `pretext_end`? Then plugins altering `$pretext` at this step could stop working. Should we extract it twice, before and after callback?

**Comment by Bloke** [comment]
Sorted! And an elegant solution. Thank you so much.

**Comment by jools-r** [comment]
I'm seeing exactly this situation again on a current 4.9.2-dev installation. In this case it's rah_maintenance that triggers it, but it works the same way as smd_at_work by calling `txp_die()` with 503 as the error status. Again, the form in the error message starts with a dot, suggesting that the theme is missing in the call to output_form.

```
Textpattern Notice: No form data found for: .body_start. Issue detected while parsing form Keine on page fzw_home

textpattern/lib/txplib_misc.php:3719 fetch_form()
textpattern/publish/taghandlers.php:447 parse_form()
output_form()
textpattern/vendors/Textpattern/Tag/Registry.php:140 call_user_func()
textpattern/lib/txplib_publish.php:540 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:429 processTags()
textpattern/lib/txplib_misc.php:4794 parse()
textpattern/plugins/rah_maintenance/rah_maintenance.php:64 txp_die()
textpattern/lib/txplib_misc.php:1689 Rah_Maintenance->errorPage()
textpattern/publish.php:241 callback_event()
```

followed by

```
8192: Using null as an array offset is deprecated, use an empty string instead Issue detected while parsing form Keine on page fzw_home

textpattern/lib/txplib_misc.php:3685 trigger_error()
textpattern/lib/txplib_misc.php:3719 fetch_form()
textpattern/publish/taghandlers.php:447 parse_form()
output_form()
textpattern/vendors/Textpattern/Tag/Registry.php:140 call_user_func()
textpattern/lib/txplib_publish.php:540 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:429 processTags()
textpattern/lib/txplib_misc.php:4794 parse()
textpattern/plugins/rah_maintenance/rah_maintenance.php:64 txp_die()
textpattern/lib/txplib_misc.php:1689 Rah_Maintenance->errorPage()
```

EDIT: `<txp:php>global $pretext; dmp($pretext);</txp:php>` at the top of the page template does show that `$pretext['skin']` is set, but `global $skin, dmp($skin);` returns `NULL`. 

Adding the following to the top of `error_503` template restores output_form functionality…
```
<txp:php>global $skin; $skin = 'mytheme';</txp:php>
```

… though a lot of other errors then show related to other tags that expect article context.
