### ISSUE TITLE
Dot in file_download_downloads

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#166]
_From [cior...@gmail.com](https://code.google.com/u/105537742124208296940/) on April 08, 2012 22:34:09_

Hi. I would appreciate very much an improvement in the tag <txp:file_download_downloads />. It would be better if a comma is displayed in numbers greater than a thousand. Thanks anyway.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=162_

**Comment by philwareham** [comment]
Non-issue. Closing. If there is an appetite for number formatting it should be a tag attribute option across all tags that return number values.
