### ISSUE TITLE
Transition to per-theme form types

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1661]
In 4.9 we should consider moving the Advanced Prefs media type setting to the Forms panel itself, so the media type is a part of the Form definition (i.e. in the txp_forms DB table). This should allow form types to be created (those that don't already exist) on the fly during theme installation/update.

We'll have to think about how to handle what happens if a type already exists but I expect that can be handled quite neatly by adding a 'theme verify' step just like we do with plugins. So when you install a theme it reads all the metadata and (potentially) prefs and maybe even plugins bundled with the theme and whatnot, then presents you with an 'intent' panel: this is what is gonna be installed. Any clashes can be highlighted and you can be given the option via a series of checkboxes to decide what parts of the incoming theme you want to install/overwrite. Theme updates might be trickier as they affect Forms/Pages/Styles only so if a new Form is on disk and it's in a different group to before that doesn't exist in the database the type will need to be created. But if it already exists, well, not sure what's best. Making theme updates go through the verify step is a barrier to those people that want to use disk-based themes as a rapid flat file store so I'd be keen to reconcile that automatically if we can, and have the verify step only on theme installation/import, not subsequent update.

By moving the media type pref to be theme-based, each theme has its own set of types made up from the set of Forms assets it contains, which is better than a global set. Helps reduce/eliminate clashes.

In any case, I'm not sure language strings should be supplied. Do they hold intrinsic value to name groups in different languages in this manner? Would they be better served via a Textpack that's installed alongside? If so they should be handled by txp_lang. Otherwise, just name your custom form types in one language.

Not sure what the media type of the existing form types should be. HTML, I guess.

**Comment by bloatware** [comment]
I think per-theme form types could just become a particular case of per-theme prefs, which look handy anyway. For example, a theme might need to define some set of php functions for use in `<txp:evaluate />`, or require `<txp:php />` tag, or use its own date format etc. It's not immediately evident which prefs should remain side-wise, or become theme-specific.

**Comment by Bloke** [comment]
Duplicate of #1487.
