### ISSUE TITLE
Visual tweak

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1664]
### Is your feature request related to a problem?

Nope.

### What is the feature?

For a better buttons vertical alignment within some browsers (Firefox; don't affect Google Chrome), maybe you could consider adding this (into hive theme):

    [type="submit"].publish, a.publish, button.publish {
	    ...
	    line-height: 1
    }

**Comment by philwareham** [comment]
Can you please provide a screenshot of the issue and what Textpattern version (4.8 or 4.9)?. Looks fine in Firefox Mac version. Adding `line-height: 1` breaks the heights in my local testing.

**Comment by cara-tm** [comment]
Without `line-height`:

![without-line-height](https://user-images.githubusercontent.com/61045/112473102-392b7380-8d6e-11eb-863e-8c7e599c5b60.png)

With `line-height`:

![with-line-height](https://user-images.githubusercontent.com/61045/112473165-4ba5ad00-8d6e-11eb-9789-a5450f9c3f21.png)

Browser: Firefox latest PC.
Textpattern: latest 4.8-dev.

**Comment by philwareham** [comment]
Hi. Can you please test 4.9 (the dev branch) as buttons were refactored a but in that branch. Let me know if the minor glitch is still there?

**Comment by cara-tm** [comment]
I'm sorry @philwareham for my late: I didn't see your comment.
Unfortunately, I can access to the 4.9.0 back-office, I got a blank screen (tested within Google Chrome & Firefox PC latest versions):

![Current screen to TXP 4.9.0 back-office](https://i.ibb.co/d0hxZP2/blank.png)

**Comment by petecooper** [comment]
>I got a blank screen

@cara-tm - sorry about that, you managed to use the demo server as I was moving it to another location - should be OK now!

**Comment by cara-tm** [comment]
Perfect!

![Result](https://i.ibb.co/c8dNh92/result.png)
