### ISSUE TITLE
Overflowing text in some languages

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1666]
### Expected behaviour

Text wraps nicely or is gracefully truncated somehow.

### Actual behaviour

At some widths (width shown in screenshot) :

![OverflowTextArticlePanel](https://user-images.githubusercontent.com/21252/112757578-3cc73080-8fe2-11eb-9b37-db33364b7264.png)

![OverflowTextArticleSidebar](https://user-images.githubusercontent.com/21252/112757783-1fdf2d00-8fe3-11eb-9171-513949bf2c1b.png)

### Steps to reproduce

* Install Txp
* Install (say) French language
* Navigate to the Write panel and change viewport width. May occur in other places.

#### Additional information

Textpattern version: 4.8.5-dev+

**Comment by cara-tm** [comment]
I can reduce the length of the two strings:
`Affectation/Présentation d’article`
`Commentaires`

**Comment by Bloke** [comment]
Thank you, that helps. I wasn't picking on French specifically, btw, I just noticed it as I was testing 4.8.5!

It doesn't stop the issue happening in other languages of course, or in other UI locations, so if there's any way we can apply some magic in the code (shrink-to-fit / truncate with tap-or-hover-to-reveal-full-text / fade out / etc) to mitigate this, then that would be better, imo.

I targeted 4.9 for this, but thank you for shortening those strings. I'll see if Phil can cheekily push your translations to 4.8.5 so I can drag them into the release I'm building.

**Comment by philwareham** [comment]
I can do text update first thing tomorrow, not this evening. Hope that works for you? Unless you want to change it directly in 4.8.5 branch of Textpattern now and I’ll back port to other repo/Crowdin afterwards.

**Comment by Bloke** [comment]
No rush. Tomorrow is good. I've found a glitch in the pophelps that I've fixed and committed locally that we'll need to backport anyway after release. A rogue opening angle bracket at the end of the third 'li' in the new parser passes advanced pref.

**Comment by philwareham** [comment]
Done.

**Comment by Bloke** [comment]
Niiiice! Thank you. Merged into 4.8.5 release.
