### ISSUE TITLE
Low-priv article workflow: save not permitted after duplicate

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1667]
### Expected behaviour

Duplicating an article of another user permits immediate save.

### Actual behaviour

Save/publish button is missing after duplication. You need to flick to another panel first, or refresh the page to get the button to appear.

### Steps to reproduce

1. Create two users: 1 Publisher, 1 Staff Writer.
2. Log in to two sessions; once as each author.
3. Create an article by the Publisher and publish it.
4. From the Staff Writer account, open that article for editing. Save button is missing, as expected (it's not their article: they don't have permission to save it).
5. Click Duplicate.
6. Note: Save button still missing.

#### Additional information

Textpattern version: 4.8.5-dev

Presumably, the Save area needs to come under Partial control so it can be modified on save.

**Comment by petecooper** [comment]
@Bloke - is this a candidate for 4.8.6, do you think?

**Comment by Bloke** [comment]
Could be. Depends how invasive the change is. May be quite involved as it (probably) requires the save area to be added to the partials. @bloatware might have a view on whether this is doable easily or requires more refactorisation than comfortable for a patch release.

**Comment by bloatware** [comment]
Wouldn't it be easier to disable/enable `Save` button rather than remove/append it?

**Comment by Bloke** [comment]
Probably.

But does that give a signal that it _might_ be possible to save if the user takes some action? Like, they might think they've missed a required field or something that would 'unlock' the save feature? Whereas if it's missing it's a definite signal that they can't do it. Plus, less temptation to use the inspector to change the `disabled`status, even though it won't do any good since we check their permissions server side.

Not sure. What do the UX gurus think? @philwareham

**Comment by Bloke** [comment]
Rockin'! That's sorted it, thank you.
