### ISSUE TITLE
Optimise callback array

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1669]
Consider optimising the callback array for faster access. No need to loop through all registered callbacks when there aren't any for the current event/step/pre.

#### Original issue text (for prosperity)

Would it be handy (and not too much of a performance hog) if we could have a callback at the end of the core's `permlinkurl()` and `pagelinkurl()` functions? If those passed the currently created URL to interested plugins, they could alter the URL and return the modified link.

The 'custom_url_func' is a nice feature, but only of use if you completely want to replace our handler with your own. A callback at the end would give plugins the flexibility to choose to replace the handler entirely via custom_url_func, or just tweak the URL prior to it being used in the callback(s).

Think of a multi-lingual site plugin:

* Hook into pre-pretext callback to populate a [lang] entry in `$pretext` that could be used to handle URLs such as /fr/section/title, and strip off the language designator prior to letting Txp carry on handling the URL.
* Hook into `pagelinkurl()` callback right at the end to insert the current language into the link.
* Hook into `permlinkurl()` callback right at the end to do the same.

Currently, to handle all the various permlink schemes, plugins are forced to duplicate - and keep up-to-date - chunks of core to create their own permlinks.

Doable? Desirable? A performance nightmare?

**Comment by bloatware** [comment]
These functions can be used a hundred times per page (menus, permlinks), so we should be careful re performance. Our present `callback_event()` function loops through the whole `$plugin_callback` array, even if there is no callback associated with a given event/step. Probably, we should reindex `$plugin_callback` by some event/step/pre hash, for a faster access?

Anyway, a `custom_url_func` plugin can already cheat to get hand on core URLs:
```
global $prefs;
isset($prefs['custom_url_func']) and $old_cuf = $prefs['custom_url_func'];
unset($prefs['custom_url_func']);
$url = permlinkurl($article_array);
isset($old_cuf) and $prefs['custom_url_func'] = $old_cuf;
// tweak $url;
return $url;
```

**Comment by Bloke** [comment]
Ah, clever. In which case I'm fine with dropping this idea.

I'm all for optimising the callback array in 4.9, though. That can get heavy and, as you say, no need to check them all.

I'll rename this issue to keep it in scope.

**Comment by bloatware** [comment]
[This](https://github.com/textpattern/textpattern/commit/5650bf9c6448468fab724a7d1973bdf033fc4943) should do it, testers welcome.

**Comment by Bloke** [comment]
I'm happy that the above change (plus 3d5f7c22, 1081c64e and 9dd96d344) put us in great shape to move forward with overhauling the callbacks in 4.9.0. Work is underway.

I'll reopen this if I spot any snags or enhancements we can make but otherwise, this is solid. Thanks!
