### ISSUE TITLE
TXP variable and trim attribute

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1670]
### Expected behaviour

Depending on the servers (local or live), I notice some annoying behavior with the `trim` attribute for the `variable` tag:

    <txp:variable name="deal" trim>
        <txp:article_custom section="my-section" preorder time="future" limit="1"> 
            <txp:article_id />
        </txp: article_custom>
    </txp:variable>

(notice: `preorder` is a custom_field with "Yes" or "No"/empty value)

Follow-up of this test:

    <txp:if_variable name="deal" value="" not> Ok </txp:if_variable>

It does not return a result, but if the first construct is written into one line of code (inline) it is efficient (although the `trim` attribute protects from spaces and/or line break):

    <txp:variable name="deal" trim><txp:article_custom section="my-section" preorder time="future" limit="1"> <txp:article_id /></txp: article_custom></txp:variable>

### Actual behaviour

The `trim` attribute seems to fail.

**To be confirmed by Devs.**

### Steps to reproduce

See above.

#### Additional information

Textpattern version: latest 4.8.5 final

Web server vendor and version: MAMP PC and live server.

Database server vendor and version: {Please write here}

PHP version: 7.4.x

**Comment by Bloke** [comment]
Not sure why this is happening in this case. Swear I tested this, but `escape="trim"` works as advertised in any case.

**Comment by cara-tm** [comment]
Incomprehensible!...

**Comment by bloatware** [comment]
Could it be just the space after `txp:` in `</txp: article_custom>`?

**Comment by bloatware** [comment]
Actually, `trim` being global, it is applied to the tags *output*, not its *content*. The output of `<txp:variable name="deal" trim>...</txp:variable>` is empty, so `trim` changes nothing here.

`escape` is global too, but it has been tweaked for use in `<txp:variable />`, so Stef's proposal works as expected.

**Comment by bloatware** [comment]
This request makes sense, since `<txp:variable name="a" value="b" />` outputs nothing, so global `trim` and `replace` are useless in this case. But the implementation is not as straightforward as with `escape`. Will think of it.
