### ISSUE TITLE
Consider putting a blank `index.html` into `/textpattern/tmp/`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1671]
Some of my sites default to `/textpattern/tmp/` for a temp dir, which is not always ideal but it seems to work.

Could we consider protecting (loosely) the contents by putting a zero-byte or basic `index.html` in that directory to restrict opportunistic public snooping?

**Comment by Bloke** [comment]
Works for me. Add something at will.

**Comment by petecooper** [comment]
Good enough for now, can be prettied up as needed.
