### ISSUE TITLE
Do we need a 4.8.6 for snags?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1672]
https://github.com/textpattern/textpattern/commit/ef2a430c7127a6c6c5c800b93a37a74f56cff810
https://github.com/textpattern/textpattern/commit/3bef7bfd7a492700dc6db52987c3a9334b03e56c
https://github.com/textpattern/textpattern/commit/5ad20cb43bc3a631b58f40943bc1f4c19807a41f

While we're still in recent release mode, should we take the opportunity to plan another out and incorporate these (plus any others deemed a good fit)?

**Comment by Bloke** [comment]
Could do. I'll split off a branch.

**Comment by Bloke** [comment]
Could we consider #1669 too? Or is it not viable?

**Comment by petecooper** [comment]
I think we've got enough to warrant a low key release. It's plausible we might possibly need some tweaks for PHP 8.1 in the 4.8 series, too, but that's months away, so 4.8 might not quite be ready to leave home just yet.

**Comment by petecooper** [comment]
OK, flight plan tracking issue ready - please leave this open for now and I'll merge in specifics later this morning then close.

https://github.com/textpattern/textpattern/issues/1673

**Comment by petecooper** [comment]
I've name dropped the three commits mentioned in OP in the flight plan, so this can be closed now.

@Bloke - please spin off a `4.8.6` branch when you're able to, no great urgency - thank you very much.
