### ISSUE TITLE
What time is now?

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1676]
Something that occurred to me this morning while I was scheduling posts in _that other CMS_. I'd set the post to pop up at 8am. The post schedule time was 2021-04-12 08:00. Eight o'clock arrived and the post didn't appear on the site.

I prodded the Publish button in case something was wrong but no, it wasn't posted. So I figured there must be a mismatch between 8am 'now' (for me) and 8am on the server. I couldn't find that information so in the end I just altered the scheduled time and changed it to 'publish immediately' then hit the button and the post appeared on the site.

Which got me thinking about Txp and similar situations. Yes, we have 'reset timestamp to now' which is fab if you're there, but if you're scheduling posts you really do need to know what time _the server_ thinks it is so you can adjust your post time accordingly. I've never really noticed much because my server tends to be in the same - or very similar (+/- 1 hour) - timezone as me. But there are many people who host in far-off lands.

Is there mileage - somehow - in displaying a clock (maybe in the footer or something) that shows what the time is in server land? Maybe it doesn't even have to be realtime - although it would be less confusing if it could tick - even the time on the server when you performed the last action would be a start. Just some reference so you know that if you set the post to show at 8am in your timezone, you need to add 5 hours to that time because it's currently 3am where your server is located.

Yes, that info is in Diagnostics so you could always hop over there - if you have permissions to see it - but for lowly content editors and staff writers, that's not an option.

Failing a clock, how about a simple notification in the Date & Time area that states the timezone difference between server and 'you' right now (if it's non-zero)? Can we get that info? Do we even know what time it is for the person in the browser at page load time or is this only available client side?

Would something like that be handy, if we can figure out how to do it sanely?

**Comment by phiw13** [comment]
Isn’t the timestamp - as displayed in Textpattern admin and front end based on the Time Zone preferences ? And then, doesn’t Textpattern calculate based on those settings ?

**Comment by petecooper** [comment]
Doesn't the article auto-calculate this?

**Comment by Bloke** [comment]
Honestly, I don't know! The whole timestamp offset thing is such a mess. Maybe it does, in which case, no problem except with DST shifts where things are an hour or so out (which screws up date-based navigation).

I think, for instance, that if you schedule a post today (April, when DST is in effect) in YMD permlink scheme for, say, midnight this coming November 5th (when DST will not be in effect) the post will get a timestamp URL of example.org/event/2021/11/05/my-post-title. But when DST switches over on the server timezone, that permlink changes to example.org/event/2021/11/04/my-post-title (because the timestamp is then wrongly calculated as an hour before midnight, tipping it into the day before). That thus delivers a 404 when the clocks change, for six months, then returns the correct article permlink during the other six months of the year.

Or, err, something like that. It might move forward an hour in that case, but moves back an hour if it was scheduled for April during winter. Dunno. Does my head in!

Maybe except for that DST anomaly, we have it mostly covered in Txp. But since my server is in my timezone and I don't like messing with it when it's live, it's difficult for me to say objectively how it works in other timezone situations. Maybe this is a non-issue and I should think about it before posting.

We really really really should  be storing dates in UTC internally, *sigh*
