### ISSUE TITLE
`Missing files:  /lib/txplib_validator.php` on `dev`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1677]
From `dev` diagnostics, site built ~5 minutes ago:

![Screenshot 2021-04-13 at 10 04 45](https://user-images.githubusercontent.com/226578/114527400-dd069180-9c3f-11eb-9135-aac6429c067c.png)

File exists in `4.8.6` but not in `dev` currently.

Safe to duplicate it, or are there underlying issues?

**Comment by Bloke** [comment]
It's superfluous and deprecated in 4.6.0, so I axed it. We have the textpattern/vendors/Textpattern/Validator classes now.

The checksums file hasn't been updated to remove it from the list, which is why it's complaining. I'll update those.

**Comment by petecooper** [comment]
Thanks @Bloke – appreciated!
