### ISSUE TITLE
Back-office user language

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1678]
### Expected behaviour

The "User language" (from other ones) selected stored and retrieved by global preferences.

### Actual behaviour

I'm currently test the 4.8.6 version on a local server. It seems the chosen user language is no more stored correctly by the global environment preferences.

**This situation needs to be verified by Devs**. Keep in mind I'm using a local distribution, not a production one: XAMP PC with PHP 8.

### Steps to reproduce

Install more than one language into Textpattern. Select one as "User language". Close Textpattern. Return into it to see what is the current administration language displayed.

#### Additional information

Textpattern version: 4.8.6-dev

Web server vendor and version: XAMP PC (Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/8.0.0)

Database server vendor and version: MySQL 5.5.5-10.4.17-MariaDB (mariadb.org binary distribution)

PHP version: PHP 8.0.0

**Comment by Bloke** [comment]
I can't reproduce this on MAMP (Mac), sorry.

When you switch language, please check your txp_prefs table and look for `language_ui`. Does it reflect the language just selected? Is it a per-user pref (`user_name` column is set to your login name)? If not, does putting your site in debugging mode reveal anything when you switch language?

**Comment by bloatware** [comment]
I've noticed that when switching between two local branches with different admin languages using a common db.

**Comment by Bloke** [comment]
Interesting. The language in use on any particular installation regardless of branch will be the one stored in the shared database for your username. Note:

1) If your user cookie is already set, it will read the language_ui from the database and present it in that language.
2) If, however, when you switch branch you are _not_ logged in and dumped back to the login screen, you will get the language that you choose _on the login panel_ and it will be set as your language throughout.
3) If you then switch back to the first branch, rule (1) applies: you're logged in so you'll see the language that you just set in the other branch.

If that's not the process and somehow the cookie is interfering and resetting the language in the database then we need to investigate.

**Comment by cara-tm** [comment]
Oops, my fault. I'm sorry.
I didn't notice the language selector from the login page.

Never mind, here is an interesting behavior. I couldn't see the selector until I remove all cookies and local storage data from my browser.

**Comment by Bloke** [comment]
No worries. Glad you found it!

> I couldn't see the selector until I remove all cookies and local storage data from my browser.

Weird. As far as I can recall it shows up if there's more than one language installed but (I think) it does try to remember your last stored language via cookie so maybe it was a combination of it remembering your last language but not detecting the fact you had more languages installed. I don't think the control itself is cached so it _should_ show up, but maybe if your browser cache is showing the old login panel for some reason then you might see this behaviour.

Incidentally, when you create new users (or edit them) from Admin>Users, you can choose their default language there - assuming you've installed more than one language. This means welcome messages and first contact with the password setting process are sent out in that language too, which is a nicer experience.
