### ISSUE TITLE
Undefined $article when processing non-existent sticky

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1679]
At the end of `doArticle()` should we either:

a) test if `$article` isset/empty
b) initialise $article = false outside the conditional

STR:

1. Create a regular Live article in a section
2. In a page/form template, add `<txp:article status="sticky" limit="1"><txp:body /></txp:article>`
3. View the individual article that uses that template.

Notice:
```
Undefined variable: article while parsing form None on page default

textpattern/publish.php:1192 doArticle()
textpattern/publish.php:918 parseArticles()
article()
textpattern/vendors/Textpattern/Tag/Registry.php:140 call_user_func()
textpattern/lib/txplib_publish.php:544 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:406 processTags()
textpattern/publish/taghandlers.php:4329 parse()
if_section()
textpattern/vendors/Textpattern/Tag/Registry.php:140 call_user_func()
textpattern/lib/txplib_publish.php:544 Textpattern\Tag\Registry->process()
```

Textpattern 4.8.6-dev (and earlier).

**Comment by bloatware** [comment]
Yep. Adding $article = false (outside the conditional or to its 'else' part) should be safe.

**Comment by Bloke** [comment]
Oki doke, I'll do that now, thank you.
