### ISSUE TITLE
[RFC] Language panel: do we need to have disabled update buttons ?

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1685]
If an installed language is up-to-date, the tile shows a `disabled` button (it is actually a `<span />` that is, a non interactive element, at least). I think this provides more noise than anything, especially to screen readers.

* for (most) users, mouse users, sighted keyboard users, … the button looks disabled but says nothing relevant otherwise. It does **not** make clear that the language is actually up-to-date. Some people will probably understand, others might be confused. At least is hard(er) to read…
* for AT, the string is still readable without any hint of a disabled state, particularly for those users who check the page in a more verbose mode. Again, it says “update” but does nothing. On Windows High-Contrast (aka forced colors) themes, the ambiguity is equally present.

Proposal: only show the “update” button when there actually is an update available, otherwise don’t bother.

**Comment by Bloke** [comment]
I like this. Leave it with me and I'll see if I can convince the Languages panel to behave this way.

**Comment by philwareham** [comment]
Agreed, sounds good.

**Comment by Bloke** [comment]
Try that.

**Comment by philwareham** [comment]
Works for me. We still have an empty `<p>` tags though when the language is your active one. And of lesser importance a `<form>` tag wrapping it all even though this form can't be interacted with. For example...

``` html
<form method="post" action="index.php">
    <p>
        <span class="ui-icon ui-icon-check" role="status">Installed</span>
        <strong dir="auto">English</strong><br><code dir="ltr">en</code>
    </p>
    <p></p>
    <input name="lang_code" type="hidden" value="en">
    <input name="event" type="hidden" value="lang">
    <input name="step" type="hidden" value="">
    <input name="_txp_token" type="hidden" value="61b6abb8f6e420ec12ec885733ce20ad">
</form>
```

..should we sort that out too maybe?

**Comment by phiw13** [comment]
Quick quick check: Nice!

**Comment by Bloke** [comment]
> We still have an empty `<p>` tags though when the language is your active one

True, good catch. I took the path of least resistance.

The code is set up so that it _always_ displays a button and form (harks back to the days of old) so it needs a bit of refactorisation to remove all the surrounding markup if we determine there are no buttons. Doesn't seem to break the layout if I remove the form and empty para tag via the inspector, since the grid is applied to ul/li. So it's doable, just needs some thought.

**Comment by Bloke** [comment]
Actually, pretty easy. See bde2df81. Please test.

**Comment by philwareham** [comment]
Just tested and looks great to me. Happy to close when Philippe has confirmed too.

**Comment by phiw13** [comment]
I’ll test first thing in the AM tomorrow (local time). Dinner time and other real world activities for now.

In the mean time, I already checked the removed button and if Phil is happy with the underlying updated markup, that is good enough for me.

**Comment by phiw13** [comment]
@Bloke 

Thanks! All work fine and display as expected.
