### ISSUE TITLE
RFC: PHP 8.1 compatibility

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1688]
https://wiki.php.net/todo/php81

At the time of writing, GA is expected late November 2021, about 180 days from now.

Given our release schedule and development style, I'm inclined to recommend we plan a 4.8 point release with any changes baked in. I'm aware this has knock-on effects with the branching here, but if we assume a new minor PHP release lands once a year, it's not something we're really going to escape from in future. This is also a factor for another RFC that I'm mulling for after 4.8.6 lands, relating to release schedules and frequency.

There's a northern hemisphere summer season to factor in, and we're traditionally a little less active at that time of year, so perhaps if we get 4.8 feature complete, we can use 4.8.7 (or later) as a PHP 8.1 compatibility thing to bookend the series.

Would appreciate your advice and feedback on this, the floor is yours.

**Comment by Bloke** [comment]
I'm in.

**Comment by petecooper** [comment]
Thanks, @Bloke.

Closing since we have a `4.7` branch now.
