### ISSUE TITLE
Textpattern 4.8.6 throws User_Error on visiting Admin->Users

### ISSUE THREAD

**Issue by prbt2016** [textpattern/textpattern#1689]
Hello,

I was in the process of manual installation of Textpattern 4.8.6  downloaded from official site, on 
Centos 6.9 Final with PHP 5.5.38, MYSQL 5.5.62, Apache 2.2.34.

However after successful installation, when i visit the following link inside admin panel i.e Admin->Users, the following error is thrown i.e : 

`User_Error "Table '{{DBNAME}}.txp_users' doesn't exist"` instead of showing the admin user.

The {{DBPREFIX}} I have used is pretx_ for installation.

What could be causing the following issue? . Could you please replicate this issue at your end and fix this?.

**Comment by Bloke** [comment]
Drat, that's a definite issue. It's either to do with the db layer change yesterday which doesn't take the PFX into account or the changes to the search filter I made. Although if that's the case, it should break on all other pages too. So I'm not sure if it's that.

Leave it with me and I'll fix it later today. In the meantime, please accept my apologies and stick with 4.8.5.

**Comment by prbt2016** [comment]
Hello,

Thanks @Bloke for confirming the issue. Kindly notify when you post the fix.

**Comment by bloatware** [comment]
It must be `$sql_from = 'txp_users'` variable on l.321 that is injected without prefixing.

**Comment by Bloke** [comment]
Yeah. Totally my fault. Could we sneakily patch 4.8.6? Bust off a branch from main and just re-release?

**Comment by bloatware** [comment]
Releases are beyond my pay grade, sorry. Please do as you deem fit.

**Comment by bloatware** [comment]
4.8.7 looks patched. I've also reverted `context` tweaks for bwc sake.

**Comment by Bloke** [comment]
Could you patch it in the 4.8.7 branch then please and test? As soon as it's done, Pete or I can issue 4.8.7 today and just change the numbers in the blog post that's been written!

**Comment by Bloke** [comment]
Sorry for the hassle, btw. Totally avoidable on my part.

**Comment by bloatware** [comment]
No worries, nice to be in a good company :-)

**Comment by petecooper** [comment]
I think it's my turn to break something next, right? I've just about stopped having nightmares about merge-a-geddon from some releases back…

**Comment by Bloke** [comment]
Thanks so much, @bloatware . I think the users panel is the only one that's affected as it was the only one I altered. The Diagnostics panel doesn't have any such table interaction. But might be worth a check with a table prefix in force, both with and without the rss_admin_db_manager plugin installed. Also might be worth checking that the latest smd_user_manager works. I can maybe do it later but if anyone has time in the meantime it would be appreciated.

I'm such a tool.

**Comment by petecooper** [comment]
>I can maybe do it later but if anyone has time in the meantime it would be appreciated.

I'll get the demo server rebuilt and resolve that other db issue, then take a look if time / brainz permit.

**Comment by bloatware** [comment]
> I think the users panel is the only one that's affected

Yep, at least that was the only unprefixed `$sql_from` entry I've found. Fast checked other tabs, they look fine.

I've actually noticed 4.8.6/dev demos did not work few weeks ago, but thought it was a temporary quirk. Will bother Pete the next time.

**Comment by petecooper** [comment]
>Will bother Pete the next time.

Please. I had no idea they were down, granted I was busy elsewhere with domestic stuff, but definitely let me know.

**Comment by philwareham** [comment]
I’d release as 4.8.7 today. If you can bump version numbers in the main repo I’ll tag the other repos end of next week. Doesn’t really impact anything there.

**Comment by philwareham** [comment]
I may be to tag the other repos this evening before I leave for holiday tomorrow. I’ll keep an eye on what you decide to do.

**Comment by Bloke** [comment]
@prbt2016 The 4.8.7 branch has the fix applied. Will be released today/tomorrow by one of us.

Thank you for reporting this and, again, sorry for the hassle it's caused.

**Comment by petecooper** [comment]
4.8.7 landed, closing. Thanks @prbt2016 for the report!

**Comment by prbt2016** [comment]
Hello,

Thanks a lot @Bloke , @petecooper  for notifying and fixing the issue. Shall check 4.8.7.
