### ISSUE TITLE
FOUND_ROWS() deprecated as of MySQL 8.0.17

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1692]
We'll need to remove it from `txp_admin.php` soon.

**Comment by Bloke** [comment]
How annoying. Is there an alternative to do the same thing? Or do we have to do pagination in PHP now?

**Comment by bloatware** [comment]
They [say](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows) use `COUNT(*)` instead.

**Comment by Bloke** [comment]
Yeah, that makes sense. I was just amending my post as you replied.

**Comment by Bloke** [comment]
We do that in most cases, it just made things simpler to use `found_rows()` in this case. There's probably a way to fudge it with two queries.

**Comment by Bloke** [comment]
Well that was easy.
