### ISSUE TITLE
missing file (diagnostics report)

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1693]
TXP 4.9-dev
The diagnostics panel reports:

```
Missing files:  /lib/txplib_validator.php
```

The file is (again) included in the `checksums.txt` file. I suppose an (unintended) consequence of merging 4.8.6 or 4.8.7 branches.

**Comment by Bloke** [comment]
Oops, yeah. Checksums will probably need updating again.

**Comment by phiw13** [comment]
Thank you. Now with less noise :-)
