### ISSUE TITLE
Tagbuilder deprecation message

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1695]
The first time accessing (opening) the tagbuilder on either the Pages or Forms pages, at the top of the dialog, there is this notice:

```
Deprecated: Required parameter $value follows optional parameter $type in /Users/<username>/Sites/_txp-dev/textpattern/include/txp_tag.php on line 788
```

Both TXP 4.8.6 +, 4.8.8-dev and TXP-4.9-dev. Database: MySQL 8.0.22 on localhost, 4.0.23 Percona on the demo sites and MySQL 5.7.28 on a live server. 

PHP 8.0.x  localhost and live server.

**Comment by Bloke** [comment]
Fixed, thank you.

**Comment by phiw13** [comment]
Indeed. Thanks.

that was too fast :-)
