### ISSUE TITLE
UI consideration about the "Write" page

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1698]
### Is your feature request related to a problem?

No just a RFC.

### What is the feature?

"Write" page: The alert block where some messages are displayed about the  current process can be omitted due to the fixed position of the "Save" button because the eyes are solicited by the little loading animation. May be could you project to move this block from the  "Footer" to below the main navigation menu?

**Comment by bloatware** [comment]
This rather belongs to [default theme](https://github.com/textpattern/textpattern-default-theme) repository. Core itself does not impose a particular `#messagepane` position.

**Comment by philwareham** [comment]
FYI the whole save area is being revised in Textpattern 4.9 Hive admin theme anyway so I'll take this into consideration there. Closing in this repo specifically..

**Comment by cara-tm** [comment]
Here is a mockup with the message at the top center of the main content and a better horizontal alignment for the "Write" label:

![message-center](https://user-images.githubusercontent.com/61045/204432695-b76d6cbe-2c24-4195-9a64-881066057e4d.png)
