### ISSUE TITLE
PHP 8.1.0 alpha 1, various `explode()` and `preg_split` `Passing null to parameter` errors on viewing all panels

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1699]
### Expected behaviour

Panels are shown without errors in Debugging mode.

### Actual behaviour

Panels show 2x errors:

```
Deprecated
: explode(): Passing null to parameter #2 ($string) of type string is deprecated in
/var/www/servers/textpattern.co/dev-demo/live/4.8.8/textpattern/lib/txplib_misc.php
on line
4972
```

```
Deprecated
: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in
/var/www/servers/textpattern.co/dev-demo/live/4.8.8/textpattern/lib/txplib_misc.php
on line
5731
```

### Steps to reproduce

* Install Textpattern `4.8.8` on PHP 8.1.0 alpha 1
* Enable Debugging mode
* Visit Write tab
* Note errors.

![Screenshot 2021-06-09 at 19 28 00](https://user-images.githubusercontent.com/226578/121408934-d69f4800-c958-11eb-971b-cd2528c6cdf0.png)

#### Additional information

Textpattern version: `4.8.8-dev`

Web server vendor and version: Nginx 1.21.0

Database server vendor and version: Percona 8.0

PHP version: 8.1.0 alpha 1

```
2021/06/09 18:22:33 [error] 15709#15709: *2014 FastCGI sent in stderr: "PHP message: PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/servers/textpattern.co/dev-demo/live/4.8.8/textpattern/lib/txplib_misc.php on line 4972PHP message: PHP Deprecated:  preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in /var/www/servers/textpattern.co/dev-demo/live/4.8.8/textpattern/lib/txplib_misc.php on line 5731" while reading response header from upstream, client: x.x.x.x, server: dev-demo.textpattern.co, request: "GET /4.8.8/textpattern/index.php?event=article HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php-fpm81.sock:", host: "dev-demo.textpattern.co", referrer: "https://dev-demo.textpattern.co/"
```

**Comment by Bloke** [comment]
Okay, we definitely shouldn't be doing this so yeah, let's hunt these suckers down and zap 'em.

If this is the only major fallout, I'm impressed!

**Comment by petecooper** [comment]
### Themes

```
8192 "json_decode(): Passing null to parameter #1 ($json) of type string is deprecated".
```

### Sections

```
8192 "json_decode(): Passing null to parameter #1 ($json) of type string is deprecated".
```

### Pages

```
8192 "json_decode(): Passing null to parameter #1 ($json) of type string is deprecated".
```

### Forms

```
8192 "json_decode(): Passing null to parameter #1 ($json) of type string is deprecated".
```

### Styles

```
8192 "json_decode(): Passing null to parameter #1 ($json) of type string is deprecated".
```

**Comment by Bloke** [comment]
Yeah, all the same kind of stuff.

It probably means we need to `(string)` any nulls before passing them in, as we use `null` specifically in places (such as tag param attributes) to distinguish them from 'empty' user-supplied values vs internal defaults. 

Might need some thought.

**Comment by Bloke** [comment]
Keep 'em coming, btw if you find any more! Good to have a checklist to make sure we found them all when we zap them.

**Comment by petecooper** [comment]
### Diagnostics

```
8192 "explode(): Passing null to parameter #2 ($string) of type string is deprecated".
```

### Preferences

```
8192 "explode(): Passing null to parameter #2 ($string) of type string is deprecated".
```

### Languages

```
8192 "explode(): Passing null to parameter #2 ($string) of type string is deprecated".
```

### Users

```
8192 "explode(): Passing null to parameter #2 ($string) of type string is deprecated".
8192 "htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated".
```

### Plugins

```
8192 "json_decode(): Passing null to parameter #1 ($json) of type string is deprecated".
```

**Comment by petecooper** [comment]
Front-side stack trace for `8192: explode(): Passing null to parameter #2 ($string) of type string is deprecated on line 4972`:

```
general_error 8192: explode(): Passing null to parameter #2 ($string) of type string is deprecated on line 4972
textpattern/lib/txplib_misc.php:4972 explode()
textpattern/lib/txplib_misc.php:5010 do_list()
textpattern/vendors/Textpattern/L10n/Lang.php:650 do_list_unique()
textpattern/vendors/Textpattern/L10n/Lang.php:690 Textpattern\L10n\Lang->extract()
textpattern/lib/txplib_misc.php:423 Textpattern\L10n\Lang->load()
textpattern/lib/txplib_misc.php:324 load_lang()
textpattern/publish.php:1323 gTxt()
textpattern/publish.php:522 validContext()
textpattern/publish.php:239 preText()
index.php:69 include()
```

**Comment by Bloke** [comment]
Same issue: `passing null to parameter N`. Thanks for grilling!

**Comment by Bloke** [comment]
So, 90% of the explode() ones I expect can be fixed by changing [line 4969 of lib/txplib_misc.php](https://github.com/textpattern/textpattern/blob/v4.8.8/textpattern/lib/txplib_misc.php#L4969). I'm not entirely sure what that does, it's some intialisation voodoo, but it makes it likely that the second param contains a null.

I'd have to dump the contents out and try it under lots of varying situations (e.g. use ID ranges in tags) to see what was happening, then I might be able to figure it out. No doubt @bloatware could patch it in seconds! Will see what I can do tonight. It might be simpler than I expect.

As for the other ones, it might be more of the same, I haven't looked at those yet.

**Comment by bloatware** [comment]
> So, 90% of the explode() ones I expect can be fixed by changing line 4969 of lib/txplib_misc.php. I'm not entirely sure what that does, it's some intialisation voodoo, but it makes it likely that the second param contains a null.

Line 4969 looks ok, it's rather that we call `do_list_unique(null)` in `textpattern/vendors/Textpattern/L10n/Lang.php:650`. What is it expected to return: `array()`, `array(null)`?

**Comment by Bloke** [comment]
I've patched the `Lang()` ones - that was an oversight on my part. I've also just fixed `preg_split()` instances. One of the preg_split instances comes from upstream in Textile itself, so we'll need to raise an issue there and patch it. Line [3256 of Parser()](https://github.com/textile/php-textile/blob/master/src/Netcarver/Textile/Parser.php#L3256) needs -1 as its third param.

**Comment by bloatware** [comment]
Is `$events = ''` in `extract()` fully compatible with `$events = null`? We don't seem to extract without the 2nd parameter in core, but plugins?

**Comment by bloatware** [comment]
That's actually a bad move from PHP, `explode(null)` resulting in `array()` was handy.

**Comment by Bloke** [comment]
Good question about the Lang. Don't know. I'm just patching other instances of `$events=null` as we call it from `load()` that way. Testing a few changes, revised patch forthcoming.

**Comment by bloatware** [comment]
I've patched it on `do_list()` side, that could suffice.

**Comment by Bloke** [comment]
Untested but I think the above patches will cover most, if not all, of the issues. We'll be able to find out at 01:00UTC when the demo server rebuilds.

**Comment by Bloke** [comment]
I'm hoping that 2cedb5c catches the `json_decode()` and `htmlspecialchars()` instances of this bug. That'll just leave the `preg_split()` in Textile, plus any we find as we test things like making the absolute bare minimum content types. For example, by deliberately omitting as many optional fields as possible when making links, files, images, articles, users, and so forth and seeing if this bug is triggered.

**Comment by Bloke** [comment]
Okay, that's better. Now we just have 'internal error' which is a pain to debug. Do you have any snippets of this morning's PHP error logs that you could pease furnish me with, @petecooper after the admin side has been used a few times so I can get a stack trace?

Thank you!

**Comment by petecooper** [comment]
@Bloke – I will get onto that right now.

**Comment by petecooper** [comment]
@Bloke - annoyingly, the `8192 "preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated".` errors are not written to Nginx error logs. There must be a way to set PHP to log more verbosely, leave that with me.

**Comment by petecooper** [comment]
OK, turns out PHP 8.1.0 has changed the PHP-FPM configuration scaffold - what worked for PHP 8.0 in `www.conf` doesn't work in PHP 8.1. I'll set an action for me to investigate, but it'll have to be after work today or tomorrow.

@Bloke – OK to leave `4.8.8-dev` demo running with PHP 8.1 alpha 1 with errors thrown so we can fine-tune? Not ideal, but it's probably helpful overall.

**Comment by petecooper** [comment]
- [ ] NTS: @petecooper to reconfigure `www.conf` with previous tweaks (see build guide ref 531)

**Comment by Bloke** [comment]
Sure yeah leave it up, no probs. I might be able to find out why it's throwing that internal error by a process of elimination.

Given the fact it's only occurring once per panel and it does it so early before it's even rendered any of the UI, I'm thinking it's more likely to be something central like the admin theme code, Lang or one of the txplibs like misc/admin/head/form/html.

P.S. I notice the iconography is also missing on dev-demo/488 and the console shows CSP violations for inline-src.

**Comment by Bloke** [comment]
Ah, is it still showing the `preg_split()` somewhere then? If it's only article related then my guess is that's the Textile one rearing its head, which is probably independent of the 'internal error' that's issued.

Since we're only tracking the entire file, we could patch Textile locally for now until someone in the Textile project comes up with a patch and releases an update. I'll do that as a band-aid.

**Comment by petecooper** [comment]
I'll push a demo site rebuild through now.

**Comment by petecooper** [comment]
@Bloke - much cleaner. Still get `Internal error` in debugging mode, but we can hopefully find those issues with better logging.

**Comment by petecooper** [comment]
OK, a quick skim through admin pages shows a much happier situation. The errors mentioned in OP are resolved, we're left with a more generic `Internal error` modal which needs some more investigation. Should be able to reconfigure the PHP-FPM stuff to get it inline with 8.0 error logging, but that'll be later on.

Gonna close this on the grounds OP is solved, will open a fresh issue with `Internal error` as the focus.

Thanks @Bloke & @bloatware!
