### ISSUE TITLE
Access from older browsers

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1701]
### Is your feature request related to a problem?

No. Just a consideration.

### What is the feature?

I know old browsers are any more supported by choice. Maybe we could add such a warning message to prevent the use of unsupported browsers. Here is currently how the 4.8.7 back-office login page is shown within IE11:

![Internet Explorer 11](https://i.ibb.co/4tjkjqr/ie11.png)

**Comment by philwareham** [comment]
Really? I thought IE11 displayed ok in 4.8.x last time I checked (which was admittedly a few months ago). I’ll check tomorrow on my PC laptop and confirm.

Either way, IE11 definitely won’t work in Textpattern 4.9 because I’ve stripped support for it.

**Comment by cara-tm** [comment]
Certainly. I know that.
Maybe you could project to display a warning message for such older browsers.

**Comment by cara-tm** [comment]
Another consideration: is it relevant to allow the printing of the back-office pages? 

    @media print{body{width:100%;margin:0;padding:0}body:after{content:"♺ Sorry, this website part can't be printing.";text-align:center;font-size:18pt}@page{margin:2cm}body *{display:none}

**Comment by phiw13** [comment]
> Another consideration: is it relevant to allow the printing of the back-office pages?

Yes. It can be useful for backing-up some info or in meetings (think more bureaucratically oriented organisations). And some people in the forum asked for this – timeframe TXP 4.6+, iirc.

**Comment by phiw13** [comment]
Out of curiosity, is that the `.not-ready` class that is not removed ?

**Comment by philwareham** [comment]
FYI I've just split the print CSS off into a separate print.css file in the admin themes for 4.9 onwards, which can make it easier for you to customise into your own version.

I'll check the 4.8 branch IE11 report on my PC laptop when I go into the office later today.

**Comment by philwareham** [comment]
> Out of curiosity, is that the `.not-ready` class that is not removed ?

Just checked on IE11 and yes the issue seems to be that class not being removed - so it’s a JavaScript or jQuery issue that we need to investigate, not the theme itself.

**Comment by Bloke** [comment]
I don't have IE11 but if you can post any console errors it might give us a clue what's going on.

**Comment by philwareham** [comment]
I will post the error (or try to fix myself) when I get home in an hour or so.

**Comment by philwareham** [comment]
IE console error:

```
SCRIPT004: expected ';'
textpattern.js (1913,23)
```

For reference that line is:

```js
        for (let file of fileInput.prop('files')) {
```

I'm guessing it's to do with the `let` with a `for` "[as mentioned on MDN for IE11 compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#browser_compatibility):

"In Internet Explorer, let within a for loop initializer does not create a separate variable for each loop iteration as defined by ES2015. Instead, it behaves as though the loop were wrapped in a scoping block with the let immediately before the loop."

But I'm no JS expect - Sio if someone know a fix and wants to jump in - please go ahead.

**Comment by bloatware** [comment]
What if you replace `for (let file of ...` with `for (var file in ...` and try to upload few files?

**Comment by philwareham** [comment]
> What if you replace `for (let file of ...` with `for (var file in ...` and try to upload few files?

I've tried this and the issue still persists in IE11. I've also tried downgrading jQuery to v3.4.1 and still no luck.

**Comment by philwareham** [comment]
Just as a side note, IE11 usage 0.62% as of May 2021, so I'm not overly concerned about this.

**Comment by phiw13** [comment]
BTW , if you want a cheap hack to at least let the user view something: wrap the offending style-block in an `@supports` query, as that is *not* supported by IE 11. That won’t make the JS error(s) disappear and there are possibly lots more issues.

```
@supports (display:flex) { /* max:0 is shorter but not sure if that is supported by all other browsers*/
.not-ready main {
    opacity:0
}
}
```

**Comment by cara-tm** [comment]
Yep, the browser console is clean now within IE11 (https://dev-demo.textpattern.co/dev/textpattern/).

A warning message could encourage users to switch to a modern browser: "For a better experience, please use a most recent browser".

![IE11](https://i.ibb.co/brQ6779/ie11.png)

**Comment by philwareham** [comment]
I've the latest version of Windows 10 on my laptop and it pretty much reminds me every time I load up Internet Explorer that it's obsolete and to use Edge instead.

Whilst this issue is a mystery - I've been through the JS file with a fine-tooth comb now and I don't see anything obvious causing this issue. Do you have real-world reports from users about this, or just from testing the demo server? Maybe something in our CSP or security setup that prevents the JS from firing? @petecooper

**Comment by cara-tm** [comment]
IE11 is obsolete. Don't try to correct this. Just add a warning message instead to switch to a modern browser.

**Comment by petecooper** [comment]
> @petecooper did the X-XSS-Protection header removal I did get pushed to the live server?

I'll do that now, I don't get notifications of codebase updates so I only push configs when a) I do it or b) you prod me with a @ - give me 5 mins, will sort.

**Comment by philwareham** [comment]
That would mean adding JS to do some sort of browser sniffing, like this one...

https://www.npmjs.com/package/outdated-browser-rework

...however I'm loathe to use something like that here. I don't want to add ~28K of JS just to tell people their browser isn't supported, especially when these things are notoriously unreliable.

**Comment by cara-tm** [comment]
Sure! I noticed you use a little line of js code within the official TXP website to detect AVIF support. Maybe you could add a kind of message ("It seems you are using an old browser. Consider switching to another modern one") onto the logging page and hide it with CSS for new browsers.

**Comment by cara-tm** [comment]
...Or SVG support (https://caniuse.com/webp):

    "use strict";document.documentElement.className="js "+(!document.createElementNS||!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect?"nosvg":"svg");

**Comment by cara-tm** [comment]
Here is the result of some searches.

The main CSS file has a class governed by jQuery (as @phiw13 said above: https://github.com/textpattern/textpattern/issues/1701#issuecomment-865620190)

    @supports (display:flex) { /* max:0 is shorter but not sure if that is supported by all other browsers*/
        .not-ready main {
            opacity:0
        }
    }

And to display the warning message, see: https://github.com/textpattern/textpattern/issues/1701#issuecomment-866071286

![IE11](https://i.ibb.co/R35rM90/ie11.png)

Here is the WP logging page:

![WP](https://i.ibb.co/vx1K3w6/wp.png)

**Comment by cara-tm** [comment]
Perfect!
You are a master!

![txp-logging-page-internet-explorer-9-preview](https://user-images.githubusercontent.com/61045/142156407-753c8c8c-5dbb-4565-9d65-678620c6992f.png)
