### ISSUE TITLE
Sorting by non unique value is random and can break pagination

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1702]
### Expected behaviour

Install few dozens of plugins and sort them by `Active` state. Pagination should work ok.

### Actual behaviour

Some plugins appear on several pages, and some not at all. Other panels might be concerned too.

#### Additional information

Textpattern version: 4.8.8-dev

Web server vendor and version: Apache/2.2.23 (Unix)

Database server vendor and version: MySQL 5.5.14

PHP version: 5.4.8

**Comment by bloatware** [comment]
For example, go to [demo](https://dev-demo.textpattern.co/dev/textpattern/index.php?event=admin) site and sort users by `Role`. For me, `no-access1000` appears on both the 1rs and the 2nd page.

**Comment by Bloke** [comment]
Drat. I bet this is my fault with the search adjustments to cater for better numeric searches. I'm going to get in the bin.

**Comment by bloatware** [comment]
I've got no old version to test, but am inclined to think it has always been like this. Some panes take care of this, some not. For example, for comments we explicitly add
```
    if ($sort != 'date') {
        $sort_sql .= ", txp_discuss.posted ASC";
    }
```
(it should rather be `id` though).
