### ISSUE TITLE
Pick one of "time zone" or "timezone" for non-code text

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1708]
https://github.com/textpattern/textpattern/blob/4bb815f36dd5cf22b799eed2b4234a5d92387bbb/textpattern/mode.ini#L73

https://github.com/textpattern/textpattern/blob/4bb815f36dd5cf22b799eed2b4234a5d92387bbb/textpattern/mode.ini#L92

I'm inclined to favour "time zone" over if we're referring to it in the non-code sense. We should pick one, and then comb through pophelps. docs etc and make sure they're in line.

**Comment by philwareham** [comment]
`time zone` gets my vote. Should only affect English Textpacks hopefully.
