### ISSUE TITLE
PSR standards

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1710]
I'm installing [CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) to the demo server, and I remembered we're using PSR-2.

We currently [state](https://github.com/textpattern/textpattern/blob/dev/.github/CONTRIBUTING.md#coding-standard):

>The project follows the PSR-0 and PSR-2 standards with PHP 5.3 style namespacing.

PSR-0 was deprecated in 2014 and [PSR-4](https://www.php-fig.org/psr/psr-4/) is the recommended successor.
PSR-2 was deprecated in 2019 and [PSR-12](https://www.php-fig.org/psr/psr-12/) is the recommended successor.

Is it appropriate to revisit the standards we're using?

**Comment by Bloke** [comment]
Yes and yes. Good catch.

We are mostly following PSR-12 anyway I think. The main deviation I can think of is to do with multi-line declarations where we sometimes put the first argument or three on the same line as the opening parenthesis and then continue underneath. This is a no-no in PSR-12 for functions and control structures: if we intend to split them for clarity, each argument entity in the list must be on its own line, with the closing `) {` on their own line.

Closures too, possibly. There's a stipulation that there's a space after the `function` where regular functions have no space after the function name, but we may not be strict about that. I expect the linter will pick up most of this stuff and we can accept most of its suggestions without ill effect as we're quite close already, bar a few nitpicky things.
