### ISSUE TITLE
UI clarity for `?event=admin&step=author_list&search_method=login&crit=username`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1712]
![re](https://user-images.githubusercontent.com/226578/124441776-f1a48280-dd73-11eb-8c0b-5675ccd2f753.png)

I think there's a missing gTxt for the above. If not, then it probably needs one, since it's not very clear what the '(1)' means in this case.

Edit: the cursor is in the English box, middle of the top row. Also, Textpattern 4.8.7.

**Comment by phiw13** [comment]
The number of (registered) uses who uses that particular non-default lang. pack ? Same as number of articles or images in a particular category for example.

It **is** a bit confusing though.

**Comment by philwareham** [comment]
It's as Philippe says - number of users of that particular pack. I guess we would tooltip and ARIA it though, maybe?

**Comment by philwareham** [comment]
OK, I'm looking at adding a `title` and `aria-label` attribute to the aforementioned link anchor, as well as to the similar ones in the categories panel (FYI I've just added some `aria-label` attributes to other links in the control panel too, to improve accessibility).

I want to try and be as consistent as possible with the existing:

```
article_count="Articles in this section: {num}."
skin_count_css="Styles in this theme: {num}."
skin_count_form="Forms in this theme: {num}."
skin_count_page="Pages in this theme: {num}."
skin_count_section="Sections used by this theme: {num}."
```

So, for the language panel I'm thinking:

```
language_count_user="Users of this language: {num}."
```

For the category panel there's a couple of options, either verbose...

```
category_count_article="Articles in this category: {num}."
category_count_image="Images in this category: {num}."
category_count_file="Files in this category: {num}."
category_count_link="Links in this category: {num}."
```

...or succint...

```
category_count="Items in this category: {num}."
```

I'd prefer minimal extra text strings so I'm leaning towards the succinct option, but fo you all feel 'Items' is the right terminology?

**Comment by Bloke** [comment]
Awesome. The fewer strings the better so yeah, go succinct if you can. "Items" seems fine to me.

**Comment by Bloke** [comment]
P.S. Unlike other panels, the indicator on the Languages panel is only for information. It'll let you delete a language if it's in use by N other people, they'll just get the default UI language, and can (re)set it from the login panel or the Languages/Users panel (depending on their access rights).

**Comment by philwareham** [comment]
> Unlike other panels, the indicator on the Languages panel is only for information

It works the same as other panels as far as I can see, you click on the value and it takes you to a list of users associated with that language, yes?

**Comment by Bloke** [comment]
Yep, the link itself does the same type of thing. I meant in terms of it still allows you to delete, whereas in other panels the presence of the indicator won't. Sorry for not being clear.

Incidentally, the link breaks if smd_user_manager is installed. *sigh* I'll fix that.

**Comment by philwareham** [comment]
@Bloke I've come across a slight stumbling block - the aforementioned links in the languages panel are generated using `function eLink` (see https://github.com/textpattern/textpattern/blob/b1b67a367e9150e34ae807304aa0e14fbe6e1845/textpattern/include/txp_lang.php#L106).

As I want to add an 'aria-label` too that mirrors the `title` attribute (for accessibility reasons) I'd have to add yet another parameter to `function eLink` such as `$atts` to do this - which we are trying to avoid. Winder if this can use your newer UI code (can't remember if that was 4.9 only or available in 4.8.x?). If so, can you provide guidance?

**Comment by Bloke** [comment]
Hmmm, the UI class is only in 4.9+. Can we alter the `eLink()` function itself to copy the `title` attribute and add the corresponding Aria stuff?

**Comment by philwareham** [comment]
Doh, oh yeah! Done now, thanks. Closed.

**Comment by petecooper** [comment]
Thanks @Bloke @philwareham @phiw13 !

**Comment by phiw13** [comment]
A thought for better all-around accessibility:
`language name (users: <a href="…">4</a>)`

Everybody - touch devices users, users of keyboard and similar devices, … , benefits of a (short) clarification. The `title` attribute is invisible for those users.

Of course, on the Languages panel it is not-so problematic, there is lots of space. On the Categories panel, or List panels is would take up more (too much?) space.

**Comment by Bloke** [comment]
That is a good point about signposting. In other places (e.g. the Sections panel) the number is in the 'Articles' column so it's more obvious that clicking it will take you to the articles in use in that section.

The Categories panel is already a bit cluttered so I'm not sure how we could make that clearer without introducing too much extra page weight. While I'm not a fan of over-labelling, I agree in the case of the Languages panel it's not obvious what the number means so it could do with some kind of clarification.

It's also not so obvious on the Comments panel that the 'magnifying glass' filters comments by parent, so we could look at that in the same kind of light, perhaps?

**Comment by philwareham** [comment]
While I agree with the sentiment somewhat, it's a fine balance between over-clutter and UX. IMO having the title and ARIA labelling is enough for accessibility specifically. Once a user has navigated the admin panels a few times (and as long as we are fiercely consistent with our patterns) then there is no need to telegraph everything.

**Comment by philwareham** [comment]
> It's also not so obvious on the Comments panel that the 'magnifying glass' filters comments by parent, so we could look at that in the same kind of light, perhaps?

This I do agree with (I saw it yesterday and was going to bring it up a some point). Needs reworking.

**Comment by philwareham** [comment]
Also, can't remember why we don't filter by category on the articles list by making the category linkable? Maybe it was because of the category1/category2 semantics. Open to discuss as an issue if it's not already been discussed previously.

**Comment by Bloke** [comment]
[Comments issue opened](https://github.com/textpattern/textpattern/issues/1714)

> Also, can't remember why we don't filter by category on the articles list by making the category linkable?

That'd be great. As you imply, it's just a case of whether we make it filter by one or both. e.g. if you click a category1 link to "Iron man":

a) filter catgeory1=iron man
b) filter catgeory1=iron man OR catgeory2=iron man

Jury's out which is more useful.

**Comment by phiw13** [comment]
* I certainly don't disagree about that fine balance between being informative enough and overload. I alluded to that in my comment above. On the flip side, I am not convinced that title and ARIA labelling is strictly enough.
* on the other hand, like all moderately complex UI, there is a learning process and some patterns are not all that difficult to remember after a few times using. In some cases, Sections, Categories, it is even _relatively_ easy to grasp the meaning (of those numbers). This is certainly the case for often used panels (basically the “content” oriented panels first). 

But then a few panels – and the Languages panel is a prime example — that are rarely visited and eventually deserve some more love… Thus my suggestion.

PS - yes that magnifier widget on the Comments panel is even for me a puzzle. I was going to bring it up at one point. Thanks for filing it as an issue.
