### ISSUE TITLE
PHP 8.1: Function (gm)strftime() is deprecated

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1721]
Used in various places in core.

**Comment by bloatware** [comment]
Converting `strftime()` formats to `date()` promises to be fun.

**Comment by Bloke** [comment]
Rather you than me! There's rakes everywhere waiting to be stepped on.

Tagging #1128 for completeness.

**Comment by bloatware** [comment]
PHP makes you wish Earth were plate and monolingual...

**Comment by petecooper** [comment]
@bloatware @Bloke - should we be sending you gin, coffee, or other?

**Comment by bloatware** [comment]
@petecooper preferably the same beverage the authors of this deprecation proposal took.

**Comment by petecooper** [comment]
@bloatware Kool Aid it is!

**Comment by petecooper** [comment]
Given this is a deprecation, and if it's safe to say we want to avoid warnings in Testing mode, are we aiming for 4.8.8 or 4.9.0 to address this, please? Thank you.

**Comment by bloatware** [comment]
4.8.8 for the time being, since it is announced PHP 8.1-compatibe? Sure, that could wait, but I'm digging into `IntlDateFormatter` stuff, and it looks promising, namely for different calendars choice.

**Comment by petecooper** [comment]
Tentatively closing, issues appears resolved.

@bloatware - please re-open if there are stragglers.
