### ISSUE TITLE
html_id doesn't work in article_custom tag

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1723]
Since `wraptag`, `class` and `break` et al are now global, there's an interesting issue with `html_id`. Consider this, to create a list of testimonials with content drawn from a pageless section:

``` html
<txp:article_custom section="testimonials" wraptag="section" html_id="testimonials" class="testimonials" label="Testimonials" labeltag="h2" break="blockquote">
   <txp:body />
</txp:article_custom>
```

Expected:
``` html
<h2>Testimonials</h2>
<section class="testimonials" id="testimonials">
    <blockquote>...</blockquote>
    <blockquote>...</blockquote>
    <blockquote>...</blockquote>
    <blockquote>...</blockquote>
</section>
```

Actual: the above but with no `id` attribute.

Bug? Expected outcome given the tag's scope? Does this affect other such tags too?

Running latest 4.8.8-dev.

**Comment by bloatware** [comment]
Will fix, but `html_id` has [never been](https://github.com/textpattern/textpattern/blob/090fec4c06aaa80d54ade0900c2d7cc275785e6b/textpattern/publish.php#L700) supported by `<txp:article_custom />`.

**Comment by Bloke** [comment]
Thank you.

Yeah, it was never really needed beforehand, but recent tag advancements have made it possible. I only tried it because, well, I was curious if it would work now it's a global attribute and was surprised when it didn't. Guess there may be other tags that output 'lists' (and thus now support `wraptag` etc) which need tweaking too. We can do those on a case-by-case basis.

**Comment by bloatware** [comment]
No worries, please test. It should work in all 'list' tags now.

**Comment by Bloke** [comment]
Hmmm, not working in article_custom still for me. *scratches head*

**Comment by bloatware** [comment]
Yep, sorry, please test again.

**Comment by Bloke** [comment]
Bingo, thank you.
