### ISSUE TITLE
RFC: Indicate if selected (article / file / image / etc) search fields are non-standard

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1724]
I've just spent a mildly frustrating 20 minutes looking through the .com admin-side to find out where the donation page is set up. Long story short, it turns out that my search settings had been remembered from a previous search, and when I searched for 'patrons', it was only searching the ID field. Whoops.

Could we consider adding some form of visible indicator to the dropdown to show search field selections are non-standard? 

It's possible this RFC might be influenced by me feeling like a plank after such a simple oversight, but I'd appreciate your take on it either way.

**Comment by Bloke** [comment]
There is/should be an indicator already, albeit rather subtle. The drop down arrow alongside the search field is a lighter shade if there's a filter in place, and solid if all checkboxes are on. There might be something more sledgehammery we can do.

**Comment by petecooper** [comment]
Gosh, there is. I hadn't even noticed. Maybe it's less obvious with dark mode…

![1](https://user-images.githubusercontent.com/226578/128596698-29db031e-60e4-4920-b3d9-abecba60067d.png)
![2](https://user-images.githubusercontent.com/226578/128596700-c8abc1fc-e39c-4f3d-b305-228369f26148.png)

Anyhow. Now I know. Thanks @Bloke! Will close.
