### ISSUE TITLE
Tidy up `subpath` in clean URL test array?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1729]
From high diagnostics on 4.8.7, where Textpattern lives in a subdirectory of the web root (e.g. `/dev/`):

```
Pretext data: array (
  'request_uri' => '/dev/09ad7e17fd0145e0589d8d38dc81559b/?txpcleantest=1',
  'qs' => 'txpcleantest=1',
  'subpath' => '\\/dev\\/',
  'req' => '/09ad7e17fd0145e0589d8d38dc81559b/?txpcleantest=1',
  […]
```

…and the same where it lives in the web root:

```
Pretext data: array (
  'request_uri' => '/9010c28bfa605c01cf78cd6f45a0c2a0/?txpcleantest=1',
  'qs' => 'txpcleantest=1',
  'subpath' => '\\/',
  'req' => '/9010c28bfa605c01cf78cd6f45a0c2a0/?txpcleantest=1',
  […]
```

The `subpath` entry in the array looks a little clumsy compared to the rest…can we trim the `\\` without breaking anything?

**Comment by bloatware** [comment]
Hush! You will wake up some pre-historic plugins.

For the record, `subpath` is used only once in core, so we don't really need to store it in `$pretext` at all. But see above...
