### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [textpattern/textpattern#1734]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Bloke** [comment]
Thanks for getting in touch. Security information is [on our website](https://textpattern.com/contact#security) but please take the [user privilege considerations](https://textpattern.com/weblog/security-considerations-and-user-privileges-in-textpattern) before filing an issue.

**Comment by petecooper** [comment]
Hi @zidingz - we have had https://textpattern.com/security.txt in place since https://github.com/textpattern/server-config/commit/3bb130ef2e2042269b9f67adb64f4d8e251e55eb but I will make a note to add in a reference into `.well-known` also.

**Comment by petecooper** [comment]
- [ ] set up https://github.com/textpattern/textpattern/security/policy
- [ ] add `security.txt` to `.well-known` via https://github.com/textpattern/server-config/issues/69

**Comment by petecooper** [comment]
Set up https://github.com/textpattern/textpattern/security/policy – closing.

Thanks for the heads up @zidingz !
