### ISSUE TITLE
Enable support for AVIF images?

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1744]
### Is your feature request related to a problem?

Nope

### What is the feature?

Since txp 4.8.8 is flagged php 8.1 compatible, and the latter [supports](https://php.watch/versions/8.1/gd-avif) AVIF image format, should we consider adding it, or wait for a new txp 4.9 image [magic](https://github.com/textpattern/textpattern/issues/1472)?

**Comment by bloatware** [comment]
@petecooper afaik, you need to expressly [compile](https://php.watch/versions/8.1/gd-avif#compile) it. And currently txp does not check for avif support anyway.

No idea how much time it will take to release 4.9 (or 4.8.9?), whence the question of conditionally including it in 4.8.8.

**Comment by bloatware** [comment]
@petecooper I would certainly be unable to do what you do. Txp avif support is laying on your shoulders!

**Comment by petecooper** [comment]
>I would certainly be unable to do what you do.

@bloatware – likewise!

I'm investigating viable routes now. OK for me to pollute the issue with appropriate updates?

**Comment by petecooper** [comment]
Packages? We don't need no steenkin' packages:

```
pete@donald:~$ /usr/local/bin/avifenc --version
Version: 0.9.2 (aom [enc/dec]:3.1.1)
libyuv : unavailable
```

`libyuv` is next, then `libjxl` and `libheif`. Tomorrow onwards, eyes are tired.

**Comment by petecooper** [comment]
I agree with @philwareham – if it's rinse and repeat in the way we handle WEBP, and it's not too arduous a task, I say we do it in 4.8.8.

**Comment by petecooper** [comment]
>libjxl compilation underway with an open issue to resolve a build error, libyuv is gonna need some courage on my part, and libheif is tbc.

I'm finding this a bum ache to accomplish, for the record. It'll be _far_ easier when there's package support in the next LTS Ubuntu due in April 2022, so I'm going to defer until either a) I can figure it out or b) packages make it a lot easier.

**Comment by bloatware** [comment]
Yep, avif support is reserved for a happy few atm, but at least txp would be ready. And yes, the idea is to handle avif in the same way that webp, available only from php 7.1.something.

**Comment by petecooper** [comment]
@phiw13 

>PHP version: 8.0.11

.avif support is being introduced in PHP 8.1.0.

**Comment by petecooper** [comment]
> Whilst AVIF is OK, I'm waiting for [JPEG XL](https://caniuse.com/jpegxl) for the real magic to happen.

Game on.

https://mobile.twitter.com/jonsneyers/status/1471942556468584454

**Comment by philwareham** [comment]
Great news!

**Comment by petecooper** [comment]
Tentatively closing this as we approach 4.8.8 beta 1. There's support to a greater extent based on operating system and `libgd` flavour (see numerous _commits passim_ from @bloatware, with special; thanks to @phiw13 for field reports, and https://forum.textpattern.com/viewtopic.php?pid=332192#p332192 for ongoing considerations). Beta feedback may prove fruitful. we'll see how it goes!

**Comment by petecooper** [comment]
Reopening this; hashtag weekend project.

**Comment by petecooper** [comment]
Mea culpa - wrong issue. Back you go to closed.
