### ISSUE TITLE
Category changes aren't reflected in cat list

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1748]
STR:

1. Visit Content->Categories
2. Create a new category name = mistake / Title = Mistak
3. Save.

Note new category isn't in list.

Reload page to show all cats.

1. Click Mistak to edit it.
2. Correct the typo in the title to 'Mistake'.
3. Save.

Note changes aren't reflected in list.
Reload page to show changes.

Txp 4.8.8-dev

EDIT: wait, it works fine on the demo server but not on my test environment. Specs:

PHP version: 7.3.18-1+ubuntu16.04.1+deb.sury.org+1
GD Graphics Library: 2.3.0; Supported formats: GIF, JPEG, PNG, WebP.
Intl extension: Unavailable
Multibyte String extension: 7.3.18-1+ubuntu16.04.1+deb.sury.org+1
Server time zone: UTC
Server local time: 2021-11-04 20:42:25
Daylight Saving Time enabled?: 0
Automatically adjust Daylight Saving Time setting?: 1
Time zone (GMT offset in seconds): UTC (0)
MySQL: 5.6.47-87.0 (Percona Server (GPL), Release 87.0, Revision 9ad342b) 
Database server time: 2021-11-04 20:42:25
Database server time offset: 0 s
Database server time zone: SYSTEM
Database session time zone: SYSTEM
Locale: en_US.UTF-8
Site / Admin language: en / en
Web server: Apache/2.4.18 (Ubuntu)
Apache version: Apache/2.4.18 (Ubuntu)
PHP server API: apache2handler
PHP SSL version: OpenSSL 1.1.1g  21 Apr 2020

**Comment by petecooper** [comment]
>Visit Content->Categories
>Create a new category name = mistake / Title = Mistak

I must be missing something…Content -> Categories on my sites only permits creation of a category with a unified name & title, which can be edited after creation. How are you providing the name / title pair, Stef?

**Comment by petecooper** [comment]
Added 'feedback required / pending' tag per https://github.com/textpattern/textpattern/issues/1720#issuecomment-999550653 as part of beta 1 prep.

**Comment by petecooper** [comment]
Defer to after beta of 4.8.8 lands.

**Comment by Bloke** [comment]
Problem diagnosed: it's to do with the adi_matrix plugin. Disabling the plugin makes the categories panel behave itself and reflect changes to the categories immediately. But with the plugin enabled, you can create/delete categories just fine, but the category list does not update until you refresh the panel.

Baffled why - it throws no errors in debugging mode. Sorry for the hassle everyone. I'll report it to Adi.
