### ISSUE TITLE
A more intuitive value for the 'limit' attribute.

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1753]
### Is your feature request related to a problem?

Nope. Rather a suggestion.

### What is the feature?

Many users set the `limit` attribute to a high number (i.e. `999`). Maybe it will be more intuitive to allow a more significant value as `infinite` or what other you'll choose.

**Comment by bloatware** [comment]
Many listing tags (`category_list`, `section_list`, `images` etc) already interpret `limit="0"` as 'no limit'. Should we make all tags act the same way? Is there any other use for `limit="0"`?

**Comment by Bloke** [comment]
I'd prefer limit="0" to mean 'unlimited', if at all possible. I don't think it interferes with anything else. Do we use valueless `limit` for anything (e.g. pageby)? Even then it doesn't conflict because valueless means 'set it on'. Can't seen any downsides.

**Comment by cara-tm** [comment]
I'm confused: I tried a valueless limit attribute (`limit="0"`) without any results... (v 4.8.8-dev).
