### ISSUE TITLE
Ajax process within 4.8.8-dev version

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1754]
### Expected behaviour

Ajax "save/publish" process and very long latency...

### Actual behaviour

I'm currently testing the upcoming dev version 4.8.8 on a production server and I notice an annoying very long latency with the Ajax "save/publish" process. I don't know if I undergo a temporal network slowdown (on Sunday when everyone consults its Facebook account or a Netflix movie): Devs, could you verify?

### Steps to reproduce

Save a page template from a real server.

#### Additional information

Textpattern version: 4.8.8-dev (latest)

Web server vendor and version: o2switch

Database server vendor and version: 5.5.5-10.5.13-MariaDB (MariaDB Server)

PHP version: 7.4.25

**Comment by bloatware** [comment]
Can not reproduce, neither on demo nor any other server. No changes have been recently made in this area afaik. Any plugin interfering?

**Comment by cara-tm** [comment]
Yep, sorry.
A temporary overused network, I'm afraid...
