### ISSUE TITLE
Missing important info into the UPGRADE file

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1758]
### Is your feature request related to a problem?

Nope!

### What is the feature?

IMHO, the `UPGRADE.txt` file does not include a necessary post-upgrade check (writing in a better English):

_Configure your website Production status in "test" mode in order to detect the existence of Textpattern warning messages into the pages of your public site (Admin -> Preferences -> Site)._

**Comment by petecooper** [comment]
Done! Thanks @cara-tm
