### ISSUE TITLE
Make Dev Preview per user group

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1759]
Currently, the dev preview theme feature is on/off for everyone.

On sites where the txp_user table is employed for customer accounts (front-end login stuff) they are usually assigned to a low-level user role or a new group made via plugin. Unfortunately, when these people log in via the front end, they see the in-dev theme by virtue of being "logged in" to Textpattern.

Consider making the dev preview a multi-select dropdown of user groups- which may be augmented by plugins - that defaults to all selected (for backwards compatibility). That way, access to this feature can be shut off to any groups if they are designated for front-end usage.

**Comment by bloatware** [comment]
> Currently, the dev preview theme feature is on/off for everyone.

Really? In my tests it is per user, and freelancers have no dev preview ability. Don't remember though what happens when an admin user with dev preview enabled is lowered in privileges.

**Comment by Bloke** [comment]
Well, okay not _everyone_. Freelancers excepted. I guess if you're using a plugin to extend the capabilities, then you could just turn that priv off for your new group, or clone the freelancer priv level.

Maybe this isn't worth considering then. Just an idea.

**Comment by Bloke** [comment]
What I meant was, the groupings are hard-coded at present. Only a plugin can alter them. So if you wanted to shut it off to Copy Editors then you can't, short of hacking the core or writing/using a plugin. Maybe that's fine, actually.

**Comment by bloatware** [comment]
It is called `skin.preview`, fwiw.

**Comment by Bloke** [comment]
Yeah, found it. Ignore me.
