### ISSUE TITLE
Configure scrutinizer-ci.com for static analysis in CI pipeline

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1760]
No cost for open source projects, can be hooked into CI:

https://scrutinizer-ci.com/
https://scrutinizer-ci.com/pricing

@Bloke @bloatware @philwareham -sounds like a no-brainer to me, what do you think?

**Comment by philwareham** [comment]
Since losing Travis CI I'd be keen to get a new CI hooked in to various projects - so a yes please from me!

**Comment by petecooper** [comment]
I don't have admin access to https://github.com/textpattern/textpattern/ so I will have to defer this to @philwareham or @Bloke (unsure about @bloatware status).

**Comment by petecooper** [comment]
OK, I think we're rolling. First inspection has completed, and we have some bedtime reading on these dark evenings:

https://scrutinizer-ci.com/g/textpattern/textpattern/

I had to change the `jquery-ui-dist` version since 1.13.0 doesn't exist in npm at the moment (see https://github.com/textpattern/textpattern/commit/adc06fa6f61d03e15b7fa3310a191a9b56db72fb). It appears that the Scrutinizer CI runs after each commit, but could be optimised a bit (git clone depth is currently 200, for example) in time, so please consider it open season on any config changes.

I'll close this now since OP is addressed, and we can fine-tune stuff as we go.

**Comment by philwareham** [comment]
Thanks. I noticed yesterday that `jquery-ui-dist` was out of sync with the actual release, when I ran `npm install`. I'll see if I can raise an issue at that repo to rectify it.

Really need to ditch jQuery UI in a future Textpattern release.

**Comment by philwareham** [comment]
Can you add me to the Scrutinizer account/organisation when you get a spare moment - no hurry. Ta!

**Comment by petecooper** [comment]
@philwareham - done, I think. Please confirm and re-close if you're happy.

**Comment by philwareham** [comment]
Yep, I'm now linked to the Textpattern organisation, thanks! Will add some of our other repos to the CI in due course.
