### ISSUE TITLE
Tag error with txp:images and sort=extension

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1764]
Input: use `<txp:images` in the body of an article, either use `id` to select images or `article image` custom field. save and view article on the public side

```
Tag error: <txp:images id="31,37,38,33,34" sort="extension asc" /> ->  Textpattern Error: Unknown column 'extension' in 'order clause'
```

```
textpattern/lib/txplib_db.php:453 trigger_error()
textpattern/lib/txplib_db.php:1191 safe_query()
textpattern/lib/txplib_db.php:1039 startRows()
textpattern/publish/taghandlers.php:3666 safe_rows_start()
images()
textpattern/vendors/Textpattern/Tag/Registry.php:140 call_user_func()
textpattern/lib/txplib_publish.php:544 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:406 processTags()
textpattern/publish/taghandlers.php:2983 parse()
textpattern/publish/taghandlers.php:3012 txp_sandbox()
```

(accidental find… tested while testing other sorting stuff, and it’s “in the docs”. I never actively used this…)

PHP 8.0 and 8.1, TXP 4.8.7 and 4.8.8

**Comment by bloatware** [comment]
Dunno what the docs say, but the column name is `ext`.

**Comment by phiw13** [comment]
Then the docs need a correction or update

from the docs

> sort="sort value(s)"
[…]
`date`. 
`extension` (image extension). 
[…]

https://docs.textpattern.com/tags/images#attributes

**Comment by petecooper** [comment]
>Then the docs need a correction or update

![sVi31Po](https://user-images.githubusercontent.com/226578/147384270-cc41faf8-f5b6-4745-98df-f95a50187ee2.gif)

**Comment by petecooper** [comment]
>Then the docs need a correction or update

Done.
