### ISSUE TITLE
Include an optional subtitle, or thesis field under title

### ISSUE THREAD

**Issue by marek-lach** [textpattern/textpattern#1772]
### Is your feature request related to a problem?

Not directly.

### What is the feature?

When writing an article, it is often helpful to think of a thesis statement, a hypothesis that guides the premise of the article. So an optional field labelled 'Premise', 'Thesis', or perhaps 'Subtitle' under title would be appropriate to help remind the writer when composing an article in _Textpattern_. Its absolute absence feels a bit jarring and distracting to me.

Thank you for considering,

**Comment by philwareham** [comment]
Hi. This would be addressed by the custom fields branch that @Bloke has been working on, which allows (I believe) users to create their own specific fields in the write panel.

I don't have an ETA of when that will be merged into core, but in the meantime the functionality can be achieved using the [glz_custom_fields plugin](https://github.com/jools-r/glz_custom_fields).
