### ISSUE TITLE
Fields for meta description should be longer than 255 chars

### ISSUE THREAD

**Issue by kuopassa** [textpattern/textpattern#1779]
### Is your feature request related to a problem?

Text written for a meta description field isn't saved if it exceeds x characters. This happens with Textpattern 4.8.7 using Hive theme. Probably not related to the theme.

### What is the feature?

Allow more than 255 characters in any meta description field, or at least use maxlength="255" in the forms.

**Comment by Bloke** [comment]
See #1801. Fixed in various commits.
