### ISSUE TITLE
RFC: PHP version support for upcoming versions

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1781]
Proposal: We should reconsider how we're going to support PHP versions in future releases of Textpattern. The frequency of major & minor PHP branches is more frequent than it used to be (i.e. pre-PHP 7). A minor release of Textpattern should be able to remove >1 of the very oldest (and unsupported) PHP versions.

At the moment, each Textpattern minor release series chops off the oldest supported version of PHP (e.g. Textpattern 4.8 has a minimum of PHP 5.5, Textpattern 4.9 is targeted at a minimum of PHP 5.6 at the moment). A Textpattern release series tends to last more than a year:

* Textpattern 4.5: ~48 months
* Textpattern 4.6:  ~21 months
* Textpattern 4.7:  ~21 months
* Textpattern 4.8: ~22 months (at time of writing)

It's reasonable to say that we're currently adding a new supported version of PHP once a year or so, given the PHP folks are doing the same. If we average 18 to 24 months for a release series, and PHP continue to release at the rate they're going, the supported versions of PHP will rack up, which adds overhead and possibly needless complexity to the development process.

There's no accurate way for us to find out how many people are still using Textpattern with PHP 5 in production since, you know, no telemetry. Our friends at Automattic have some info for Wordpress, however:

https://wordpress.org/about/stats/

![Screenshot 2022-01-31 at 14 46 21](https://user-images.githubusercontent.com/226578/151814710-9330da0e-7066-4f90-ad05-215a2c1d64d9.png)

![Screenshot 2022-01-31 at 14 46 14](https://user-images.githubusercontent.com/226578/151814702-00896171-d111-4507-bb0e-9b1f2add1959.png)

Assuming those stats are mostly correct, ~11% of all Wordpress instances are running on PHP 5.6. ~40% of all Wordpress instances are older than current-minus-one, so there're plenty of unmaintained Wordpress sites out there. While there's no data to correlate it, it's not a stretch to say that older Wordpress instances are more likely to have older PHP versions, either by virtue of a server limitation, or the admin not being savvy enough to update, or shoddy hosting, or other factors.

I'd like us to consider being more direct with dropping older PHP support from Textpattern 4.10 onwards. Perhaps instead of following the drop-the-oldest-PHP-version script we could jump >1 at a time, at least until the spread of supported PHP versions is commensurate to the resources we have available, with a view to longer term sustainability (and less bum ache).

Thanks for your consideration.

**Comment by Bloke** [comment]
I'm happy to accelerate kicking out older PHP versions.

OT: my current MAMP build (granted, it's a few months out of date now) isn't built with Imageick so I'm relying on PHP 5.6 to test the new images functionality. Not sure why it came with PHP 5.6 and PHP 8 only. *shrug*. I might have just had PHP 5 lying around in a directory and enabled it. I should probably go see if PHP 7 is available and has Imagick compiled in. That said, if it isn't compiled, the entire branch fails spectacularly so I'm not sure how to get round that.

Anyway, yes to killing off older PHP versions.

**Comment by vanmelick** [comment]
Extra data points, using oldest versions of popular server distros:

- Debian 9 (support till June 2022): PHP 7.0.33
- Debian 10 (support till June 2024): PHP 7.3
- RHEL/CentOS 7 (support till June 30, 2024): PHP 5.4 (yes, really, but if you're running this, it's either too old for textpattern or you have additional repositories like https://rpms.remirepo.net/enterprise/7/ added and can install up to PHP 8.1)
- CentOS 7 + cPanel / WHM: PHP 5.4, 5.5, 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1 (so people can switch to newer PHP here)
- Ubuntu + cPanel / WHM: PHP 7.3, 7.4, 8.0, 8.1 (same here)
- Ubuntu 18.04 (support till April 2023): PHP 7.2
- Fedora 34 (support till May 17h 2022): PHP 7.4

So assuming TXP 4.9 is released in the second half of this year, by that time all Linux versions which still have standard / LTS security updates will offer at least PHP 7.2. And assuming TXP 4.10 (or TXP 5?) follows at least a year after that, you're looking at PHP 7.3 and above (or even 7.4 it it takes 20-22 months).

About the Wordpress pie chart posted by Pete. A large percentage of those still running on PHP 5.6 likely already have the option to switch to a more recent PHP version or can get this option simply by asking their hosting company. Just because they haven't doesn't mean they can't. And as Pete pointed out, those that frequently update TXP likely aren't the ones still on old PHP versions.

If you want PHP statistics for servers where people are still actively installing or upgrading web applications, also have a look at Packagist, which currently lists PHP 5.6 usage as only 0.7% (and all PHP versions below 7 combined just 1%):
https://packagist.org/php-statistics

**Comment by petecooper** [comment]
Updating with April 2022 stats.

![2](https://user-images.githubusercontent.com/226578/162484051-b3e45db7-f749-4392-bd23-e21b83534ec2.png)
![1](https://user-images.githubusercontent.com/226578/162484062-86c3e4db-e378-434e-8432-bf91829cb61b.png)

First pass observations / pull quotes (incomplete):

* PHP 8.0 and PHP 7.4 gaining market share.

**Comment by petecooper** [comment]
https://craftcms.com/blog/craft-4

> PHP 8. Craft now requires PHP 8, enabling developers to safely take advantage of several new language features.

Wow!

**Comment by philwareham** [comment]
Pretty bold move. I think Textpattern 4.9 could easily move to at least PHP 7.0, possibly higher if it makes coding and new features easier.

**Comment by petecooper** [comment]
It helps that it's a commercially-supported CMS, I guess.

**Comment by petecooper** [comment]
Updating with current Wordpress stats (May 5 2022).

![Screenshot 2022-05-05 at 13 19 57](https://user-images.githubusercontent.com/226578/166921800-1745b2c6-8a68-40d3-b787-b053435ebe11.png)
![Screenshot 2022-05-05 at 13 19 53](https://user-images.githubusercontent.com/226578/166921802-64d85df4-4f0c-4843-8fc4-00635336da73.png)

**Comment by petecooper** [comment]
Updating with current Wordpress stats (Jun 24 2022):
![Screenshot 2022-06-24 at 15 40 47](https://user-images.githubusercontent.com/226578/175559610-738cca41-8767-476c-ba65-5a4531cd5527.png)

![Screenshot 2022-06-24 at 15 40 52](https://user-images.githubusercontent.com/226578/175559623-e52d355c-b54c-47ef-b436-308990a23bf7.png)

**Comment by petecooper** [comment]
Well, hello. It's been a while, hasn't it?

![Screenshot 2022-07-31 at 13 53 48](https://user-images.githubusercontent.com/226578/182027506-506d0eef-5832-4cea-b52c-8bf1dc1a457e.png)

![Screenshot 2022-07-31 at 13 53 40](https://user-images.githubusercontent.com/226578/182027505-02337966-d96b-4fd1-a092-0310de9f9d6a.png)

Comments to follow in edit.

**Comment by petecooper** [comment]
Guess who's back…back again.

![Screenshot 2022-08-30 at 19 26 32](https://user-images.githubusercontent.com/226578/187514681-84e5ce98-857b-4283-89d2-53ff29df95e1.png)
![Screenshot 2022-08-30 at 19 26 48](https://user-images.githubusercontent.com/226578/187514693-1f63669a-ee10-4054-85ea-1bf2b1ebc92c.png)

**Comment by MioVisman** [comment]
https://packagist.org/php-statistics

![versions](https://user-images.githubusercontent.com/5917956/187602422-04807c47-a726-4b18-bc87-5a2b9c00f478.png)

**Comment by petecooper** [comment]
October 2022 update

![Screenshot 2022-10-09 at 13 25 52](https://user-images.githubusercontent.com/226578/194756795-ce845484-bfde-4649-bcef-3f6ef347447a.png)
![Screenshot 2022-10-09 at 13 25 46](https://user-images.githubusercontent.com/226578/194756802-801b5a94-40e3-49af-a732-531eb89b0c75.png)

10th percentile is PHP 7.0; 20th percentile is PHP 7.2.

**Comment by petecooper** [comment]
This isn't a hill I'll die on, but we need to decide on our PHP ride height should be for 4.9.*, and I propose it starts with a 7 not a 5…

If we assume that 4.9.0 lands in or around 2023Q1, the official vendor-supported versions of PHP are: 8.2, 8.1, and 8.0. Everything before that has been gracefully EOL'd by way of security support ending. PHP 7.4 was EOL'd at the end of November 2022.

Currently, we're working with PHP 5.6 being the ride height. Presumably there are some benefits to only supporting newer PHP, so if we split the difference and state PHP 7.2 as the minimum…would that be viable? As @vanmelick says in https://github.com/textpattern/textpattern/issues/1781#issuecomment-1026254105 :

>So assuming TXP 4.9 is released in the second half of [2022], by that time all Linux versions which still have standard / LTS security updates will offer at least PHP 7.2.

Anyone who's pegged at older-than PHP 7.2 can stay on Textpattern 4.8 _or_ move to a supported PHP version. Assuming the 4.9 series will be around two years total, we can expect another two minor PHP 8s to land, or perhaps a major PHP (9?) in that time.

@bloatware @Bloke From a dev perspective, are there tangible benefits to leaving very old PHP behind?

**Comment by petecooper** [comment]
Latest stats:

![2](https://user-images.githubusercontent.com/226578/206470090-d812537e-cccf-46dc-94dc-fb503293337e.png)

![1](https://user-images.githubusercontent.com/226578/206470083-b2eaafe8-4fd6-4abd-9e89-ab3a08074da8.png)

**Comment by philwareham** [comment]
PHP 7 seems fine baseline for me.

**Comment by Bloke** [comment]
We don't gain much by abandoning them. A few legacy calls can be updated as we have notes in the code to update them. Maybe some efficiencies in places. At least one thing Oleg patched in 4.9 to cater for PHP 5 could be reverted. Otherwise, the only thing we lose is approx 5% of users whose systems are still on PHP 5.x, if we believe those numbers.

**Comment by Bloke** [comment]
That said, I'm fine with PHP 7 as minimum

**Comment by philwareham** [comment]
Hmmm, true. Our code works in PHP 5 so not much gain from saying it doesn't. Maybe if/when we use some code or libraries that specifically _don't_ support <7 then we can bmp minimum requirements.

**Comment by philwareham** [comment]
I think the image manipulation stuff needed PHP7 but I may be mistaken. Anyway that is not going into the upcoming release.

**Comment by Bloke** [comment]
Correct. The image library needs it. Until then we can chug along on 5 as bare minimum but downplay it and make 7.2 our minimum recommended baseline?

**Comment by bloatware** [comment]
As long as a new txp release is fully compatible with the previous one (as for 4.9), I see no urge in upping PHP version, unless the code requires it. CF might be a different story, so we could label it txp 5.0 and switch to PHP7+.

**Comment by petecooper** [comment]
Tagging https://github.com/textpattern/textpattern/issues/1931#issuecomment-2206113408

Textpattern 5 should be at least PHP 7.1

**Comment by petecooper** [comment]
Bumping with current (Jan 1 2025) snapshot in case we need to revisit. PHP 8.2 is now in security support.

<img width="973" alt="Screenshot 2025-01-01 at 21 16 56" src="https://github.com/user-attachments/assets/3821b1c1-0d70-470d-ae9d-bc9b651699d0" />

![Screenshot 2025-01-01 at 21 15 44](https://github.com/user-attachments/assets/7ba43e81-b450-40e4-9b16-948af5419c3d)


![Screenshot 2025-01-01 at 21 15 36](https://github.com/user-attachments/assets/f1f601c1-bee1-4478-a26c-b182dcd77cee)
