### ISSUE TITLE
4.8.8 + PHP 8.1 + txp:variable PHP Deprecated: trim(): Passing null to parameter #1 of type string is deprecated

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1782]
### Actual behaviour

This is only a deprecated warning that seems to happen when initiating a non-pre-existing txp:variable with the `default` attribute:

### Steps to reproduce

Defining a variable and acting on it using the `default`attribute (e.g. for a counter):

```
<txp:variable name="counter" add="1" default="0" />
```

returns a deprecated warning: `8192: trim(): Passing null to parameter #1 ($string) of type string is deprecated while…`.

ADDED:

On the 4.8.8 demo site with PHP 8.1, set the Site Status to debugging and add this to the end of the Welcome article:

```
<txp:images>
<txp:variable name="counter" add="1" default="0" />
counter: <txp:variable name="counter" /> – img_id: <txp:image_info type="id" />
</txp:images>
```

The error trace points to `textpattern/publish/taghandlers.php:5025 trim() – variable()` which is here: [L5024-L5026](https://github.com/textpattern/textpattern/blob/6538ab2b064dadb0ad86a4b378dc3f93a1085052/textpattern/publish/taghandlers.php#L5024-L5026).

### Workaround

Checking if the variable exists and setting it first if absent gets around the warning, e.g.:

```
<txp:if_variable name="counter" not><txp:variable name="counter" value="0" /></txp:if_variable>
<txp:variable name="counter" add="1" />
```

#### Additional information

Textpattern version: 4.8.8

PHP version: 8.1

**Comment by bloatware** [comment]
@jools-r thank you, should be fixed in dev. But I'm sure it's not the last php 8.1 surprise.
