### ISSUE TITLE
Add Snyk Code for PHP security checking

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1783]
Snyk Code now has security coverage in PHP:

https://snyk.io/blog/php-security-support-snyk-code/

We should investigate how feasible it is to add this into CI.

**Comment by philwareham** [comment]
Can you invite me again - tried the link from yesterday and it has expired. Cheers.

**Comment by petecooper** [comment]
Added @philwareham as org admin, closing this for now since we're tracking our own repos in Snyk, but not via CI as such.
