### ISSUE TITLE
4.8.8 / PHP 8.1: Deprecated “passing null to version_compare()” notice on Diagnostics panel

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1786]
In **debug mode** on Textpattern **v4.8.8** and **PHP 8.1**, I get the following notice on the Diagnostics panel:

```
8192 "version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated"
in/…/textpattern/include/txp_diag.php at line 849.
```
and:
```
adminErrorHandler()
textpattern/include/txp_diag.php:849 version_compare()
textpattern/include/txp_diag.php:213 checkUpdates()
textpattern/include/txp_diag.php:93 doDiagnostics()
textpattern/index.php:230 include()
```

[Line 849](https://github.com/textpattern/textpattern/blob/b16653990e5fac4bbe0397671709d0836bf9af1a/textpattern/include/txp_diag.php#L849) of txp:diag.php is the check against the pre-release version number. And indeed [version.json](https://textpattern.com/version.json) currently returns the following as we don't have a new pre-release at the moment:

```
{
  "textpattern-version": {
    "release": "4.8.8",
    "prerelease": null
  }
}
```

Presumably the version_compare statement just needs wrapping in a defensive if $prerelease is not null wrapper...

**Comment by Bloke** [comment]
Yes, or we patch the json value to return 'false' or something instead, which means no changes to core required :)

**Comment by petecooper** [comment]
Should I be worried about `version.json` going from null to Boolean?

**Comment by bloatware** [comment]
I guess it would complain about anything else than a string.

**Comment by Bloke** [comment]
So can we return `''` then, to mean "not available"?

**Comment by bloatware** [comment]
Dunno, just saying php 8.1 seems to expect the exact function [signature](https://www.php.net/manual/en/function.version-compare.php). Which implies hundreds of potential warnings to patch.
