### ISSUE TITLE
CLS issue points at image element not having width and height

### ISSUE THREAD

**Issue by AmritasyaPutra** [textpattern/textpattern#1798]
I am referring to this location:
https://github.com/textpattern/textpattern/blob/d4f026d7f675d148ab1896da3e35190ca34be5f0/textpattern/setup/themes/four-point-nine/forms/misc/images.txp#L9

Existing code in the above location renders the following on my website:
```
 <p itemprop="image" itemscope="" itemtype="https://schema.org/ImageObject">
        <img loading="lazy" itemprop="url contentUrl" src="https://ekvastra.in/images/29.png" alt="Anger" >
        <meta itemprop="width" content="700">
        <meta itemprop="height" content="700">
 </p>
```
 
For whatever reason, pagespeed Insights, GTmetrix, and dareboost all were saying that "Image elements do not have explicit width and height " ... "Set an explicit width and height on image elements to reduce layout shifts and improve CLS". I checked in Firefox that the itemprop width and height were greyed out.

I specified the width and height in the img element instead of separate meta line and the problem was fixed! 

I also removed lazy loading because I was getting "Largest Contentful Paint image was lazily loaded" ... "Above-the-fold images that are lazily loaded render later in the page lifecycle, which can delay the largest contentful paint." This isn't important here though.

**Comment by cara-tm** [comment]
FYI,, to keep the "lazy-loading" for images below the fold but to remove this attribute above the fold, I did this model within a website:


    
    <txp:variable name="img_counting" add />
    
    <txp:variable name="caption" value='<txp:image_info />' />
    
    [...]
    
    <figure itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
    
    	<img itemprop="url contentUrl"<txp:evaluate query='number(<txp:variable name="img_counting" />) < 2'><txp:else /> decoding="async" loading="lazy"</txp:evaluate> src="<txp:image_url link='0' />" alt="<txp:image_info type='alt' />" width="<txp:image_info type="w" />" height="<txp:image_info type="h" />">
    
    [...]

</figure>

**Comment by jools-r** [comment]
> For whatever reason, pagespeed Insights, GTmetrix, and dareboost all were saying that "Image elements do not have explicit width and height " ... "Set an explicit width and height on image elements to reduce layout shifts and improve CLS". I checked in Firefox that the itemprop width and height were greyed out. I specified the width and height in the img element instead of separate meta line and the problem was fixed!

Yes, it's discussed in detail on [web.dev](https://web.dev/optimize-cls/#images-without-dimensions). Another solution is to specify aspect-ratio.

> I also removed lazy loading because I was getting "Largest Contentful Paint image was lazily loaded" ... "Above-the-fold images that are lazily loaded render later in the page lifecycle, which can delay the largest contentful paint."

> FYI,, to keep the "lazy-loading" for images below the fold but to remove this attribute above the fold, I did this model within a website:

Nice tip :-) I found myself doing almost the same thing after auditing with PageSpeed Insights, except using a variable in place of your "2", because I had a grid layout, so image 5 was the first below the fold.

You could use if_first_article / if_first_image to catch the first instance but by placing it in your image form as you have, it is independent of the looping structure it's located in.

(BTW: in your logic, you should be able to use `evaluate … not` in place of `<txp:else />`.)

Even then, this method does depend on layout. How many images lie below the fold can change between desktop and mobile viewports so it's an approximate method at best.

**Comment by petecooper** [comment]
From my read, the OP from @AmritasyaPutra is addressed by https://github.com/textpattern/textpattern/issues/1798#issuecomment-1106607057 and the comments on https://github.com/textpattern/textpattern/pull/1799 – please re-open if further action is needed.
