### ISSUE TITLE
Fine-graining control of expired articles

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#18]
_From [r.wetzlmayr](https://code.google.com/u/r.wetzlmayr/) on July 09, 2009 09:32:48_

Past their expiry date, expired articles are output according to the
'publish_expired_articles' prefs - a site-wide setting which affects the
range of electable articles for both XHTML output and RSS/Atom feeds. 

For feeds, this behaviour seems sufficient.

OTOH, XHTML pages should allow expired articles to get published in any
arbitrary fashion, at the designer's discretion. An additional attribute to
<txp:article[_custom] />, <txp:recent_articles /> and <txp:related_articles
/> would be reasonable.

Related discussion: http://forum.textpattern.com/viewtopic.php?id=30726

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=14_

**Comment by vanmelick** [comment]
Restoring missing content in issue start:

---

Project Member Reported by r.wetzlmayr, Jul 9, 2009

Past their expiry date, expired articles are output according to the
'publish_expired_articles' prefs - a site-wide setting which affects the
range of electable articles for both XHTML output and RSS/Atom feeds. 

For feeds, this behaviour seems sufficient.

OTOH, XHTML pages should allow expired articles to get published in any
arbitrary fashion, at the designer's discretion. An additional attribute to
`<txp:article[_custom] />`, `<txp:recent_articles />` and `<txp:related_articles
/>` would be reasonable.

Related discussion: http://forum.textpattern.com/viewtopic.php?id=30726

**Comment by philwareham** [comment]
@bloke what's your take on this? Been open for years and not sure it's still an issue? Close or keep open?

**Comment by Bloke** [comment]
It probably has value, I just haven't looked at the referenced thread and immersed myself in it. Will try and do that this week and see if there's anything that can be done about it.

**Comment by bloatware** [comment]
FWIW, `<txp:article_custom />` (thus `<txp:recent_articles />` and `<txp:related_articles />`) accepts `expired` attribute and outputs expired articles accordingly. Can be closed, I think.

**Comment by philwareham** [comment]
Great, thanks Oleg. Good enough for me - closing.

**Comment by bloatware** [comment]
While we are there, we could extend the binary `expired` to time values. So, `expired="-10 days"` would mean "not expired before 10 days ago". Just for fun :-)

**Comment by Bloke** [comment]
If it's easy to do, sure, why not. Might as well really make this attribute totally head-scratching! But as it would open up some interesting event-based possiblities, it has value I think.
