### ISSUE TITLE
Fatal error when pasting too much text into Section Description field

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1800]
### Expected behaviour

A warning of some kind, either before or after clicking _Save_.

### Actual behaviour

Fatal error (see below) when pasting too much text into the _Description_ field on the _Edit Section_ panel.

### Steps to reproduce

- Visit _Presentation › Section_ on the admin side
- Edit a section and paste a longer chunk of text into the _Description_ field.
- Click _Save_.

The error is reproducable on both online demo sites.

#### Additional information

Textpattern version: v4.8.8 and v4.9.0 dev (txp demo)

Web server vendor and version: nginx 1.21.6

Database server vendor and version: MySQL v8

PHP version: v8.1

Operating system: Darwin 21.4.0 / Linux 5.4.0-109-generic (txp demo)

---

This is the full error - which is informative as to why it occurs. Perhaps it is suffice to specify a `maxlength` attribute for the textarea? Alternatively, a length check before submission to the database?

```
Fatal error: Uncaught mysqli_sql_exception: Data too long for column 'description' at row 1 in /path/to/textpattern/lib/txplib_db.php:442
Stack trace: 
#0 /path/to/textpattern/lib/txplib_db.php(442): mysqli_query(Object(mysqli), 'UPDATE txp_sect...', 0) 
#1 /path/to/textpattern/lib/txplib_db.php(503): safe_query('UPDATE txp_sect...', false) 
#2 /path/to/textpattern/include/txp_section.php(657): safe_update('txp_section', 'skin = 'skin-na...', 'name = 'default...') 
#3 /path/to/textpattern/include/txp_section.php(59): section_save() 
#4 /path/to/textpattern/index.php(230): include('/path/to/S...') 
#5 /path/to/.composer/vendor/laravel/valet/server.php(234): require('/path/to/S...') 
#6 {main} thrown in /path/to/textpattern/lib/txplib_db.php on line 442
```

**Comment by phiw13** [comment]
The *Categories* description field has the same issue, but e.g. *Links* and  *Themes* do not.

I can see the logic of having a length limit for those 2 (Categories and Sections) — it is pure meta data in both cases.

**Comment by vanmelick** [comment]
On 2022-04-23 18:42, jools-r wrote:
> This is the full error - which is informative as to why it occurs.
> Perhaps it is suffice to specify a maxlength attribute for the
> textarea? Alternatively, a length check before submission to the
> database?

maxlength (defined as max characters) could work, if you divide the max 
length of the database column (in bytes) by the maximum number of bytes 
possible per character (4 when using UTF-8, IIRC). Downside is that in 
most cases each character is just one byte, so it's more restrictive 
than necessary. For the description field (varchar), this would limit 
the field to 64 (or 63) characters to be on the safe side, while it can 
potentially fit 255.

A better solution would be to use Javascript to check the actual byte 
length of the form input (perhaps even with a "x characters left/used" 
indicator).

--Ruud

**Comment by phiw13** [comment]
FWIW again, the same issue *might* exist on the Write panel, meta description field. I say might because 1/ the ajaxy Save routine may hide it and 2/ I currently run into a JS error when trying , see https://github.com/textpattern/textpattern/issues/1801

**Comment by jools-r** [comment]
Thanks Philippe @phiw13 for checking the other instances. 

And thanks Ruud @vanmelick (nice to see you here!) for the valid note about varying maxchar length depending on the charset used. Might that at least be predictable even that the charset should be known as it is specified in `$txpcfg['dbcharset']` in [config.php](https://github.com/textpattern/textpattern/blob/bc5184ea6548a3dec5aee6b066b6ae102a599aa3/textpattern/config-dist.php#L88)?

**Comment by Bloke** [comment]
Hmm, this is annoying. Good catch.

The trouble with looking up the current charset and using that is there's no guarantee that every character will occupy 4 bytes, if using utf8-mb4 for example. You might type 26 ASCII chars and a Japanese Kanji character, which occupies 4 bytes, for a total of 30 bytes of data stored.

The only reliable(ish) way I can think of is to add a class or `data-` attribute to certain input fields and use JavaScript to calculate (or estimate) the byte cost with a 'characters remaining' counter. Whether that can be defined once and then it automatically provides that facility on all inputs with that class/data attribute I'm not sure.

Can JavaScript even determine how many bytes each typed character takes up? And if so, what do we do about it if it goes over? Stop further entry? Throw a warning somehow? Provide visual feedback when they counter reaches 0?

Thoughts anyone?

**Comment by vanmelick** [comment]
Several suggestions on how to do it in Javascript with benchmarks:
https://stackoverflow.com/questions/5515869/string-length-in-bytes-in-javascript

**Comment by Bloke** [comment]
Nice find, Ruud. So perhaps the most performant one for UTF-8 is:

``` js
function byteLengthCharCode(str) {
  // returns the byte length of a utf-8 string
  var s = str.length;
  for (var i=str.length-1; i>=0; i--) {
    var code = str.charCodeAt(i);
    if (code > 0x7f && code <= 0x7ff) s++;
    else if (code > 0x7ff && code <= 0xffff) s+=2;
    if (code >= 0xDC00 && code <= 0xDFFF) i--;
  }
  return s;
}
```

**Comment by Bloke** [comment]
A counter has been introduced e2634557 using a variant of the above JavaScript counter. It doesn't work so well with non-UTF-8 characters (e.g. emoji) so if anyone has any ideas on how to handle those in the truncater, then please speak up.

Anything above the UTF-8 byte count will be chopped unceremoniously, with no respect to word boundary.

Bonus future feature: a live countdown number near the input field.

The limits are only implemented on the Section panel for now but can be rolled out elsewhere if this seems like a reasonable approach. Please test and feed back thoughts.

**Comment by phiw13** [comment]
Are you sure this is the correct way to solve the problem? For multibyte languages at least that would lead to _serious_ loss of capability. Before your patch, a Section description in Japanese could be 255 characters long without causing any issue anywhere (admin panel, DB, output on front end). With the current patch, that would now be limited to ~86 characters. A serious difference (loss).

From what I understand, the DB stores / counts characters when using `varchar()`, independently of language or encoding [1]. The main/only limit: the DB has to support the encoding. Using Japanese or Chinese characters with a Latin1 DB is obviously bound to cause problems & potential dataloss.

–^–
Reading MySQL documentation on string data types (covers `varchar()`) here: https://dev.mysql.com/doc/refman/5.7/en/string-type-syntax.html and https://dev.mysql.com/doc/refman/5.7/en/char.html (MySQL 5.7 docs).

> For definitions of character string columns (CHAR, VARCHAR, and the TEXT types), MySQL interprets length specifications in character units.

the keyword: “character units” 
–^–

What is needed I think (1) use of `maxlenght=255` (the UA will stop accepting input beyond that) (2) eventually a JS counter to help the user and (3) insert after the “description” label a note: “max. 255 characters”.

Try a test in Textpattern 4.8.8 (demo site  is OK) with the text below (exactly 256 characters long). This will fail. Delete the last character, try again. Success! Close the panel, reopen, check the content in the DB, and so on, everywhere you should see the same block of text.

Sample text extracted from this Wikipedia page (subject: apples)
https://ja.wikipedia.org/wiki/リンゴ
That article has a wide assortment of text (with/without roman text, numbers) that you can play with for testing.

> 栽培法リンゴに限らず商品価値の高い果実を収穫するためには、開花直前から開花時期に優位な花を残す「花摘み」、結実後30日程度を目安に実を間引く「摘果」作業が必要である。リンゴには果実に袋をかける有袋栽培とかけない無袋栽培がある。無袋の方が日光が多く当たり糖度も上がるが、ふじ等の一部の品種は果実の色を鮮やかにし商品価値を上げるため有袋栽培を行う。また、有袋栽培には貯蔵性が向上する効果もあり、さび防止のためには遮光度の弱い袋を使用し、着色向上のためには遮光度の強い新聞紙や二重袋などを使用する。名称の頭にＡＢＣＤＥ

(I have helpfully inserted full-width roman characters at the end, easier to recognise, perhaps)

**Comment by Bloke** [comment]
No I'm not sure at all, haha. If MySQL handles multibyte and emoji etc on our behalf in its size limit calculations then all we need is a simple string character counter in the JavaScript function. That's way simpler. The remaining code about adding the limits to the input controls would still stand.

**Comment by phiw13** [comment]
> That's way simpler. 

Indeed… 
But please consider adding the `maxlength` attribute to the affected fields. That way, screen readers etc will know what to expect.

**Comment by Bloke** [comment]
Okay, try that. We can add `maxlength` too, no problem.

**Comment by phiw13** [comment]
Quick test, this works rather well, first with Japanese text, then mixed Chinese + French,  then adding some emoji (treated as one character unit, even composite ones – cat and black cat). 255 character can go in, above that the text is clipped.

Noticed that (at least in Firefox) the count doesn’t seem to update unless the cursor is at the end of the input (or the clipping does not happen).

**Comment by Bloke** [comment]
Cool, thanks for testing. I noticed in Firefox Mac that if I copied a phrase and pasted it in multiple times, it doesn't register the key press (and hence truncate the string) until after I release the CMD key. So it gives the impression the max can be exceeded, but then chops it when I let go.

It will become more apparent what is going on when/if we introduce a live character decrementer alongside the input box. Haven't tried this in other browsers yet.

**Comment by bloatware** [comment]
You'd probably rather use `input` event than `keyup`?

**Comment by Bloke** [comment]
Ah yeah maybe. I always forget about that one. Thanks.

**Comment by Bloke** [comment]
Okay, please give https://github.com/textpattern/textpattern/commit/b03fca0c3cb1d00937c8d569d67f90368ff0e588 a whirl.

**Comment by Bloke** [comment]
Using the `input` event works much better. Thanks, @bloatware.

I used the web inspector to add `maxlength="200"` to the textarea and then pasted in the test block that phiw13 supplied. It permitted 200 of those characters, truncating the remainder, so the textarea element seems to be cognisant of multi-byte too. That's a bonus.

Setting it to 255 cuts it at the same place as the JavaScript so maybe we don't even need it at all? Just enforce `maxlength` wherever we feel it's necessary. That means we can probably do away with `data-max-length` attribute, and just hook the JS into `maxlength` if it's there. The JS itself won't be of much use right now because maxlength will take care of everything for us at the browser level, but when/if we decide to show a 'remaining characters' count, it can be modified to handle that, so I might just leave it there for now unless anybody objects and thinks we should strip it out.

Of course, neither client-side method will prevent form submissions that have been tampered with, because there's no validation on the server to check the data fits. My purist heart says we should find a way to truncate the incoming data on the server too. Thoughts?

**Comment by bloatware** [comment]
I'd leave it with the browser client-side if it works in all browsers. Less event handlers - faster UI.

**Comment by Bloke** [comment]
Oki doke, no 'Remaining characters' indicator then. Easy!

**Comment by Bloke** [comment]
Yes, I was pleasantly surprised that it understood multibyte character limits.

And yep, it is pretty unceremonious when the limit is reached. But beyond reinstating some JavaScript counter that compares the limit and notifies you, there's not much we can do about it.

**Comment by bloatware** [comment]
There is no real problem updating a counter on `input`, nobody tapes 1000 characters per second. But I'd say, if you often reach the limit, then the field is undersized.

**Comment by Bloke** [comment]
I think that: https://github.com/textpattern/textpattern/commit/01d1fd113c94d803984bc68d822d39651ef4dd44 https://github.com/textpattern/textpattern/commit/6ff0e66643eec549d138038b73676929cbfd49db https://github.com/textpattern/textpattern/commit/42c56a514a255568878519f5fa939b4cac98fa33 https://github.com/textpattern/textpattern/commit/199ededf9ec53fe25669fb812933cbb6753272a5 https://github.com/textpattern/textpattern/commit/3bc77a9793b4b474aa16fe8010850fef3bf8d9f4 and https://github.com/textpattern/textpattern/commit/c6dd206603339d681c906d3ce45585af3bf8d455 complete this issue.
