### ISSUE TITLE
Write panel, JS error when saving with a long meta description field

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1801]
### Expected behaviour

a message pane with an error message that the input in that field is too long.

### Actual behaviour

STR fill in the Description meta data field on any article with a text of **more** than 256 characters.
Save.

Actual result: no message pane is displayed, the fresh input is not saved

THE JS error:

``` js
SyntaxError: Unexpected token '<'
	appendChild (index.php:1:851)
	b (jquery.js:2:851)
	globalEval (jquery.js:2:2880)
	text script (jquery.js:2:82990)
	(anonymous function) (jquery.js:2:79371)
	l (jquery.js:2:79487)
	(anonymous function) (jquery.js:2:82256)
```

The Safari console helpfully links to this line: `"message": "<span class=\"ui-icon ui-icon-{status}\"></span> {message}"`

#### Additional information

Textpattern version: 4.8.8 / PHP 8.1 / MariaDB

**Comment by phiw13** [comment]
BTW - by a “long” text I mean 256 characters or more…

**Comment by Bloke** [comment]
See https://github.com/textpattern/textpattern/issues/1800
