### ISSUE TITLE
php 8.1 Warning : A non-numeric value encountered in textpattern/lib/constants.php on line 518

### ISSUE THREAD

**Issue by mkavici** [textpattern/textpattern#1811]
### Expected behaviour

No warning output

### Actual behaviour

A non-numeric value encountered in textpattern/lib/constants.php on line 518

### Possible Fix
Casting to int fixes
`define('AJAX_TIMEOUT', max(30000, 1000 * (int)@ini_get('max_execution_time')));`

#### Additional information

Textpattern version: 4.8.8

PHP version: 8.1

Operating system: Deb 10.11

**Comment by bloatware** [comment]
Thank you, should be fixed now.
