### ISSUE TITLE
Incorrect thumbnail orientation when uploading certain image orientations from phone cameras

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1816]
### Expected behaviour

The thumbnail will be created with the same orientation as the original.

### Actual behaviour

The thumbnails produced by Textpattern are created upside down or rotated / or a combination thereof.

### Steps to reproduce

Test images taken with an iPhone 11: 
- [IMG_4065.jpeg](http://jools.link/x4bw7) - iPhone 11 / landscape orientation, no contextual cues – EXIF['Orientation'] = 6
- [IMG_4067.jpeg](http://jools.link/w0uhb) - iPhone 11 / landscape orientation, contextual cues – EXIF['Orientation'] = 3

_Explanation of EXIF orientations [here](https://sirv.com/help/articles/rotate-photos-to-be-upright/)._

Results when uploading (screenshots):

- [IMG_4065.jpeg: Textpattern thumbnail orientation compared with original uploaded file](http://jools.link/zzoax) - upside-down and rotated
- [IMG_4067.jpeg: Textpattern thumbnail orientation compared with original uploaded file](http://jools.link/ofge6) – upside-down
- [Textpattern thumbnail orientation compared with finder (left) and Fotos.app (right)](http://jools.link/angim)

The thumbnails contain no EXIF metadata.

Problem identification:

class wet_thumb in [class.thumb.php](https://github.com/textpattern/textpattern/blob/dev/textpattern/lib/class.thumb.php) fails to check for EXIF orientation.

#### Additional information

Textpattern version: 4.8.8

Web server vendor and version: PHP 8.1 / nginx or apache

Database server vendor and version: 8.0.29

PHP version: PHP 8.1

Operating system: Linux

**Comment by jools-r** [comment]
Potential solution:

After studying this [Stackoverflow thread](https://stackoverflow.com/questions/7489742/php-read-exif-data-and-adjust-orientation) and various tests (particularly given the conflicting orientation suggestions in that thread), I added the following snippet to [class-thumb.php](https://github.com/textpattern/textpattern/blob/dev/textpattern/lib/class.thumb.php) ahead of [line 268](https://github.com/textpattern/textpattern/blob/fe2bcc98c12f50c5fb2aecf50da6f5e3e96405b6/textpattern/lib/class.thumb.php#L268), i.e. before the images portrait/landscape orientation is set.

```
        // Check exif orientation (if exists)
        $exif = exif_read_data($this->_SRC['file']);
        // Correct orientation / mirroring of thumb
        if (!empty($exif['Orientation'])) {
            switch ($exif['Orientation']) {
                case 3: // upside-down
                case 4: // upside-down (mirrored)
                    $this->_SRC['image'] = imagerotate($this->_SRC['image'], -180, 0);
                    break;
                case 5: // rotate-left (mirrored)
                case 6: // rotate-left
                    $this->_SRC['image'] = imagerotate($this->_SRC['image'], -90, 0);
                    break;
                case 7: // rotate-right (mirrored)
                case 8: // rotate-right
                    $this->_SRC['image'] = imagerotate($this->_SRC['image'], 90, 0);
                    break;
            }
            // Swap height and width if rotated by 90°
            if (in_array($exif['Orientation'], [5, 6, 7, 8])) {
                $this->_SRC['width']      = $temp[1];
                $this->_SRC['height']     = $temp[0];
            }
            // Flip if original is mirrored
            if (in_array($exif['Orientation'], [2, 5, 7, 4])) {
                imageflip($this->_SRC['image'], IMG_FLIP_HORIZONTAL);
            }
        }
```

Essentially it tests if EXIF Orientation metadata exists in the uploaded file. 
- If it does, it rotates the image data accordingly.
- If that rotation is by 90°, the incoming width and height values are swapped.
- If the original is in one of the mirrored orientations, it additionally flips the image.

In my own real-world testing, this seems to work successfully. Here are some further images taken with the same camera in [landscape turned left](http://jools.link/iwr52) and [landscape turned right](http://jools.link/37n9q), and in [portrait upright](http://jools.link/vxjp1) and [portrait upside-down](http://jools.link/zf4fy).

I also tested using the test images at [github.com/recursor/exif-orientation-examples](https://github.com/recurser/exif-orientation-examples) so as to test the image flipping. Here too all thumbnails from the examples in portrait and landscape with all EXIF Orientations (checked using exif_read_data) came out correctly.

Problems? If the height and width values are already set for a thumbnail and you try re-uploading the original image (i.e. in the image edit pane for an existing image), the thumbnail is incorrectly cropped and you get a black bar on part of it.

**Comment by Bloke** [comment]
Amazing work, thank you. I'd be happy to patch class.thumb as indicated and just roll with it, then see if there's any fallout with other cameras. We can then tweak or revert parts as we get more test data in.

**Comment by jools-r** [comment]
Ok, [PR 1817](https://github.com/textpattern/textpattern/pull/1817) submitted to the dev branch.

Those who need it now can either cherry-pick the commit or copy across class.thumb.php from the dev branch.

Feel free to make any improvements you may deem necessary.

**Comment by petecooper** [comment]
Merged https://github.com/textpattern/textpattern/pull/1817 – thank you very much @jools-r!

**Comment by phiw13** [comment]
@jools-r 

You have used this on a production site (Textpattern 4.8.8), did I understand correctly?

Afaict, the patch applies correctly on that branch, but given the way we handle images I have not much opportunity to test it. On the other hand one of the clients is breathing new life in her site and that person mostly uses her iPhone, it might come in handy there.

**Comment by jools-r** [comment]
Yes, a 4.8.8 with those lines and a few others patched.* Hence my discovery of the error message (now corrected) when a GIF/PNG is uploaded.

You can test it with the example images from the recursor GitHub repo linked above.

In theory, if/when we switch to another image-handling library this will be made obsolete, or the new library deals with that but for the moment it corrects a problem that can be quite annoying and otherwise requires that you open and resave the image in the correct orientation in something like photoshop.

_*On my fork, I currently use 4.8.8 with a few other patches/fixes but not the more major changes in the dev branch._
