### ISSUE TITLE
Comment Form shows Twice

### ISSUE THREAD

**Issue by rn-src** [textpattern/textpattern#1819]
### Expected behaviour

Go to comment, comment form shows once.

### Actual behaviour

I see the comment form twice.

### Steps to reproduce

Go to an article, click the link that allows you to comment.
[{like this one}](https://www.mightyheave.com/index.php?id=3#comments-head)

#### Additional information

Textpattern version: 4.8.8

Web server vendor and version: Apache 2.4.5.2

Database server vendor and version: MySql 8.0.29

PHP version: 8.1.2

Operating system: Ubuntu 23.04 LTS (from docker container on Alpine Linux 3.16)

**Comment by cara-tm** [comment]
Hi.
Are you sure you're using Textpattern CMS?
It seems that the link you provided point to a WordPress website.

**Comment by rn-src** [comment]
I was, but not anymore.  Thanks for looking though.
