### ISSUE TITLE
Missing translated entry into the login page

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1828]
### Actual behaviour

It is just a reminder: from the login page, the string into the title attribute for the front-end website link isn't populated (the `tab_view_site` entry into translated Textpacks).

https://dev-demo.textpattern.co/dev/textpattern/

**Comment by petecooper** [comment]
This may be due to `tab_view_site` is admin-only at the moment, so the public site cannot use the translated string.

@bloatware @Bloke - is it safe to relocate `tab_view_site` to public, or should we use another name for the public-side link as outlined in OP?

**Comment by cara-tm** [comment]
I tried many placements into the different part strings for the tab_view_site entry, but without any results.

**Comment by Bloke** [comment]
Ah yeah, in theory it should be in `[common]` so it can load on both public and admin sides. Does that work?

**Comment by philwareham** [comment]
To be honest this doesn't really need a `title` attribute so I'll remove the attribute instead of the upheaval of editing the Crowdin setup.
