### ISSUE TITLE
Considerations for CI pipeline / Github Actions

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1835]
We have two checksum generation scripts, they do the same job but they're slightly different. It would be helpful to sync them (as far as viable) with a view to introducing into dev CI pipeline in future.

https://github.com/textpattern/textpattern/blob/dev/.github/txp-checksums.php
https://github.com/textpattern/textpattern-toolbelt/blob/main/release/checksums.php

**Comment by Bloke** [comment]
I'm not sure what or who uses the one in the `.github` directory. The other one is just for releases. My guess is that the github one is for interim checks during development to see if there are any files that need adding. It's not as fully featured as the one in the toolbelt so I'd be inclined to ditch it, unless it's somehow hooked into our processes.

If CI pipelining can't execute scripts from other repos, then we might have to rethink.

**Comment by petecooper** [comment]
>If CI pipelining can't execute scripts from other repos, then we might have to rethink.

I'm pretty sure it can do that, now you mention it. I'm assuming fewer CPU cycles & fewer bytes through the pipes for a local / native checksums rebuilder, so perhaps a dupe of the release script would do the job.

**Comment by petecooper** [comment]
- [ ] `txp-checksums.php`
- [ ] `npm run phplint`

**Comment by philwareham** [comment]
Do any of us use phplint? Latest usage in this field is phpstan, via Composer, if you want some automated code linting. Can be set up as a GitHub Action too if required.

**Comment by petecooper** [comment]
I was just using `phplint` as it's mentioned in README, happy to look into other options if that's preferable.

**Comment by petecooper** [comment]
I'm going to close this for now, I'll fork and get it working first, and PR it back in if it's not an absolute horror show.
