### ISSUE TITLE
HTML5-conform self-closing (void) tags

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1836]
(Not really a bug report)

The W3C validator complains about `/>` endings of self-closing (void) tags when using an HTML5 doctype.

We have only a handful of situations where these tags are output and I tracked them down and made a [small commit](https://github.com/jools-r/textpattern/commit/0706e40b5c9fbcdb8a36ab5da4956cb7e655523e) in a branch of my own fork that switches these to plain `>`-tag endings when the doctype setting is set to HTML5.

Is this worth submitting as a PR?

BTW: What's not affected here is `<br />` tags produced by textile. That needs adapting [over there](https://github.com/textile/php-textile).

**Comment by philwareham** [comment]
Sure, I don't use `/>` myself (rather just `>` for that extra 1 byte of savings!) so a PR would be good - but note that any amends should only be made to code that affects the backend only, as we still allow frontend to have an XHTML doctype, where that code would be invalid.

Although I thought `/>` was still valid in HTML5, even though it's a holdover from XHTML to be honest. Surprised the validator is flagging this.

**Comment by phiw13** [comment]
Related forum thread: https://forum.textpattern.com/viewtopic.php?id=51908.

Thumbs up from me for a small 4.8.8+ patch.

**Comment by jools-r** [comment]
You guys are quick!

This does affect front-end output as well, for example the meta_description tag, all tags that output input or img tags such as txp:image and txp:article_image, etc.

FWIW, the W3C Validator produces the following *notice*:

> Trailing slash on void elements [has no effect](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) and [interacts badly with unquoted attribute values](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values).

I've done a [parallel fix for com_connect](https://github.com/textpattern/com_connect/issues/84) too :-)

**Comment by philwareham** [comment]
Unquoted attribute values are the worst, anyone who uses those should be given a stern talking to. 😀

**Comment by petecooper** [comment]
>Is this worth submitting as a PR?

Yes, please.

**Comment by jools-r** [comment]
Hmm, my [commit](https://github.com/jools-r/textpattern/commit/0706e40b5c9fbcdb8a36ab5da4956cb7e655523e) on my fork was against the main branch. I'm guessing I need to make this PR against the dev branch?

**Comment by Bloke** [comment]
> Hmm, my [commit](https://github.com/jools-r/textpattern/commit/0706e40b5c9fbcdb8a36ab5da4956cb7e655523e) on my fork was against the main branch. I'm guessing I need to make this PR against the dev branch?

Yes please :)

**Comment by jools-r** [comment]
Just a note that a corresponding mini fix has been made over at https://github.com/textile/php-textile/commit/b603dabd21a3a7a3ed26e4cc91f99285af825081 for textile output. Thanks to Stef for advice and pointers and to Jukka for guiding me gently through the submission and testing process. The next version of Textile should incorporate this. With luck this may be out in time for the v4.9 release.

**Comment by philwareham** [comment]
Textile updated to v4.0.0 in dev now - please test. Ta!
