### ISSUE TITLE
txp:variable: output default value if variable does not exist

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1837]
At present, when supplying a `default` attribute for `txp:variable`, it will be used only if the variable *already exists and is empty*. If the variable has not been defined, the tag returns an ‘variable does not exist’ error message.

However, a typical / common situation in which one might set the `default` attribute is to guard against situations in which a needed variable has not been set. This can be used, for example, to make a shortcode form portable between themes so that it can respond to a variable set elsewhere in the theme, but will still work with a default if it is missing.

As discussed in [this forum post](https://forum.textpattern.com/viewtopic.php?id=51919), Oleg noted that the current behaviour with the error message can be useful for finding mistyped variable names, but that the `output` attribute could be wired to output a value specified in the `default` attribute and bypass the error message.

This minute [commit](https://github.com/jools-r/textpattern/commit/b289e237ad167ea03b38f67504bd48dd33272d42) on my fork produces the following behaviour…

If `output` attribute is set:
- Bypass error message if the variable does not exist
- Output any specified default value
- but do not set the variable value

**Comment by bloatware** [comment]
This seems to work, thank you. Committed, feedback welcome.

**Comment by jools-r** [comment]
Thank you! Your help made all the difference.
