### ISSUE TITLE
"no language" available in Users panel

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1843]
### Expected behaviour

Users in the Admin->Users panel should only be permitted to select actual installed languages.

### Actual behaviour

An empty entry at the top of the list is present, meaning.... no back-end language assignment?! Even though it cannot be selected.

### Steps to reproduce

1. Install more than one language from Admin->Languages panel.
2. Visit Admin->Users panel.
3. Edit any user and click the Language dropdown.

#### Additional information

Textpattern version: 4.8.8+

**Comment by Bloke** [comment]
Hmmm, this is more nuanced. If a language is removed that has been assigned to a user, that user technically has 'no language'. Until one is assigned (either by themselves or an administrator) they will see untranslated strings in the UI after an in-use language is deleted.

Under those circumstances, an empty entry in the language dropdown is valid: they do indeed have no language and it's a visual cue to set one, rather than (erroneously) choosing the first item in the list, or the default site lang.

If an attempt is made to set the language to the empty entry, it is rejected and reverts to whatever was set before. So it won't cause harm being there it just looks... odd.

A potential fix is that, when a language is deleted, if any user account was using it, go through and update all affected accounts and set their language pref to the default system language. At least that way they don't get a sea of untranslated strings.

Opinions?

**Comment by bloatware** [comment]
Dunno, I'd prefer untranslated strings to a language I don't speak. Probably, a more user-friendly option would be forbidding to remove a used language?

**Comment by Bloke** [comment]
> I'd prefer untranslated strings to a language I don't speak.

True dat.

Not sure about forbidding removal of in-use langs. Guess we could do that. But if there are a lot of users, I think a tandem feature ought to be a multi-edit to reassign language on the Users panel. That way, it's easy(ier) to remove a language:

1. Visit Admin->Languages
2. Click the number in parentheses against the language you want to remove. That will jump to the Users panel with a filter in place.
3. Use Multi-edit->Change language.
4. Revisit Admin->Languages and delete the language.

The only snafu is if there are a lot of users - more than 96 using any particular language. Then the above would need to be done in batches. But, I guess, limited use cases there so probably an acceptable trade-off.

**Comment by petecooper** [comment]
Viable to display if a language pack is in use by a user? Visual clue before they are deleted, for example. Bonus prize: show # of users with that language pack, hyperlinked to the users panel showing just the users using that pack.

**Comment by petecooper** [comment]
>The only snafu is if there are a lot of users - more than 96 using any particular language. Then the above would need to be done in batches. But, I guess, limited use cases there so probably an acceptable trade-off.

Another reason to work in an 'All' option from dropdown menus. A site with hundreds of users will likely have enough CPU & RAM headroom to run that query.

**Comment by Bloke** [comment]
@philwareham This changeset requires a new `[admin]` language string:

`changelanguage="Change language"`

**Comment by philwareham** [comment]
Language string added. Thanks all.
