### ISSUE TITLE
Add Mastodon as a legitimate channel of contact

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1849]
Currently we have Twitter as one of our social media channel points of contact, across the software and websites. We need to now also promote our Mastodon account. I set one up about 5 years ago but left it dormant.

I need to migrate it to a new Mastodon server due to the one we chose shutting down in December. After that we should start adding it as a social media channel in our list.

**Comment by philwareham** [comment]
Done, just need the server redirects uploaded but closing the issue anyway.

**Comment by cara-tm** [comment]
Maybe you need to add it into the "Links" page for the "Default" theme?

**Comment by philwareham** [comment]
@cara-tm already done: https://github.com/textpattern/textpattern/commit/8b890dfc0602879e7a12645aee55f8aca29e5e6e#diff-bf3762f34989c25b76e63d1283c5829b67e29ecc7a1652065784264ae97cac39
