### ISSUE TITLE
PHP 8.2: dynamic property txp_thumb::$link

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1852]
Depreciation notice: “Creation of dynamic property txp_thumb::$link is deprecated“

Uploading an image, the thumbnail creation phase flags the above (in debug  mode). The thumbnail image is created though.

```
8192 "Creation of dynamic property txp_thumb::$link is deprecated"
in /Users/username/Sites/_txp-dev/textpattern/lib/class.thumb.php at line 200.
textpattern/lib/class.thumb.php:200 adminErrorHandler()
textpattern/lib/class.thumb.php:566 wet_thumb->__construct()
textpattern/include/txp_image.php:1104 txp_thumb->__construct()
textpattern/include/txp_image.php:64 thumbnail_create()
textpattern/index.php:231 include()
```

**Comment by jools-r** [comment]
Might [this](https://github.com/textpattern/textpattern/blob/fa008951a0b7597cc442161aea8f282942e3058e/textpattern/lib/class.thumb.php#L200) be the culprit. Unlike the other $this->properties, it is not defined further up in the class. Defining it would probably silence the warning, but I don't see where it is used elsewhere in the class (there's $this->linkurl but not $this->link).

**Comment by bloatware** [comment]
@jools-r I think you are right, core does not use it. If some plugins need it, `$link` should be declared, or removed otherwise.
