### ISSUE TITLE
RFC: permit searching of forms, pages, and styles

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1855]
### Is your feature request related to a problem?

A small one.

### What is the feature?

Admin-side search functionality for forms, pages, and styles. We can search content easily enough, but the pages + forms + styles trifecta is not (obviously) searchable. As the amount of each grows, it becomes less clear on where to find things.

Today I have to update a page on .com and have to pick through pages & forms to find out what needs updating and where, since it's not readily searchable. It would be _much_ more straightforward if we could search these presentational elements in a similar way to content.

**Comment by Bloke** [comment]
True. In the meantime *cough* [smd_where_used](https://github.com/Bloke/smd_where_used/releases).
