### ISSUE TITLE
`Uncaught mysqli_sql_exception: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set.` during installation to remote database

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1858]
### Expected behaviour

An error-free installation process using a (remote) [DigitalOcean Managed Database](https://www.digitalocean.com/products/managed-databases) using InnoDB engine.

### Actual behaviour

SQL error after user credentials are supplied (formatted for legibility):

```
Fatal error:
  Uncaught mysqli_sql_exception: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set.
  Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
in /var/www/servers/pragmatika.click/textpattern/live/innodb-test/textpattern/lib/txplib_db.php:442
Stack trace:
#0 /var/www/servers/pragmatika.click/textpattern/live/innodb-test/textpattern/lib/txplib_db.php(442): mysqli_query()
#1 /var/www/servers/pragmatika.click/textpattern/live/innodb-test/textpattern/lib/txplib_db.php(834): safe_query()
#2 /var/www/servers/pragmatika.click/textpattern/live/innodb-test/textpattern/vendors/Textpattern/DB/Core.php(82): safe_create()
#3 /var/www/servers/pragmatika.click/textpattern/live/innodb-test/textpattern/setup/setup_lib.php(119): Textpattern\DB\Core->createAllTables()
#4 /var/www/servers/pragmatika.click/textpattern/live/innodb-test/textpattern/setup/index.php(533): setup_db()
#5 /var/www/servers/pragmatika.click/textpattern/live/innodb-test/textpattern/setup/index.php(154): step_createTxp()
#6 {main} thrown in /var/www/servers/pragmatika.click/textpattern/live/innodb-test/textpattern/lib/txplib_db.php on line 442
```

### Steps to reproduce

* Set up DO Managed Database instance, create user and password, assign user privileges.
* Start Textpattern installation process, connect to database with above credentials, append provided `config.php` contents with `$txpcfg['dbengine'] = 'InnoDB';`, save `config.php`, proceed to admin-side user credentials.
* Provide admin-side user credentials, proceed to next step, note error above. Stop.

#### Additional information

Textpattern version: 4.8.8

Web server vendor and version: Nginx 1.23

Database server vendor and version: DigitalOcean Managed Database, 8.0.30

PHP version: 8.1

Operating system: Ubuntu 20.04 LTS

### Further reading

There is a [solution](https://stackoverflow.com/a/72438019) to this that involves fiddling with the DO side of things: create an API token, find the database cluster, make a `POST` request, done.

**Comment by vanmelick** [comment]
Why does textpattern create tables without a primary key?
Simply just create tables with primary keys and the problem is gone.
Having a primary key in each table doesn't have any downsides that I can 
think of.

**Comment by Bloke** [comment]
We certainly should be using primary keys! If not, it needs addressing.

**Comment by Bloke** [comment]
Does 5a0f1d8 fix this? We have a number of tables with UNIQUE indices only but I think those are good enough to bypass this error. The only table we had no primary or unique index was txp_section.

**Comment by petecooper** [comment]
@Bloke I should have some time after work today, I will spin up a server and check.

**Comment by petecooper** [comment]
Using current `dev`. We're still not quite there.

Connection to remote database is good, `config.php` is standard issue:

![Screenshot 2023-04-03 at 14 59 44](https://user-images.githubusercontent.com/226578/229534290-f31c6287-24d8-4fed-b4b7-a90b033462e4.png)

After creating `config.php`, we continue to user creation, which complains:

![Screenshot 2023-04-03 at 15 00 54](https://user-images.githubusercontent.com/226578/229534631-9d62c5c7-2225-4741-9ee7-2951ce24cb24.png)

```
Fatal error: Uncaught mysqli_sql_exception: Storage engine MyISAM is disabled (Table creation is disallowed). in /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php:442
Stack trace:
  #0 /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php(442): mysqli_query() #1 /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php(865): safe_query()
  #2 /var/www/servers/textpattern.co/managed-demo/live/textpattern/vendors/Textpattern/DB/Core.php(82): safe_create() 
  #3 /var/www/servers/textpattern.co/managed-demo/live/textpattern/setup/setup_lib.php(119): Textpattern\DB\Core->createAllTables()
  #4 /var/www/servers/textpattern.co/managed-demo/live/textpattern/setup/index.php(549): setup_db()
  #5 /var/www/servers/textpattern.co/managed-demo/live/textpattern/setup/index.php(154): step_createTxp()
  #6 {main} thrown in /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php on line 442
```

If I add `$txpcfg['dbengine'] = 'InnoDB';` from https://forum.textpattern.com/viewtopic.php?pid=323012#p323012 and retry the user creation step, there's a different error:

![Screenshot 2023-04-03 at 15 10 56](https://user-images.githubusercontent.com/226578/229535366-b4e56321-1acb-4da8-9ab4-a5c581274b3f.png)

```
Fatal error: Uncaught mysqli_sql_exception: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting. in /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php:442 
Stack trace:
  #0 /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php(442): mysqli_query()
  #1 /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php(865): safe_query()
  #2 /var/www/servers/textpattern.co/managed-demo/live/textpattern/vendors/Textpattern/DB/Core.php(82): safe_create() 
  #3 /var/www/servers/textpattern.co/managed-demo/live/textpattern/setup/setup_lib.php(119): Textpattern\DB\Core->createAllTables()
  #4 /var/www/servers/textpattern.co/managed-demo/live/textpattern/setup/index.php(549): setup_db()
  #5 /var/www/servers/textpattern.co/managed-demo/live/textpattern/setup/index.php(154): step_createTxp()
  #6 {main} thrown in /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php on line 442
```

**Comment by petecooper** [comment]
This is in the MySQL log:

```
2023-04-03T14:10:50.030285Z 456 [Warning] [MY-011071] [Server] Attempt to create or modify table without primary key: managed-demo.txp_css
```

**Comment by Bloke** [comment]
Okay, the styles, pages, forms and plugins tables are all pretty easy to add a primary key on name. But the txp_prefs table is more tricky. We currently have:

UNIQUE prefs_idx (name(185), user_name),
INDEX  user_name (user_name)

Which makes sense because the name can be duplicated per user. But can we keep that and add a simple primary key on name?

Does the compound unique index cover us for the duplication on name if we have a simple primary key on the name column? Or do we have to replace the prefs_idx index with a composite primary key? Or do we need an additional composite primary key identical to the prefs_idx index?

My index fu is adrift here. Guidance welcome please. @bloatware ? Anyone?

**Comment by bloatware** [comment]
I get it as one can not create two identical `(name, user)` pairs, but ignore whether this will suffice as primary key. Never met this error before.

**Comment by phiw13** [comment]
Is this related? With an up-to-date TXP-dev (says Git), setting up a site. I get as far as the “Populate Database” step, but after filling all fields on this pane (name, email address, login name,…) it blocks.

```
Fatal error: Uncaught mysqli_sql_exception: 
Specified key was too long; max key length is 1000 bytes in /Users/[username]/Sites/_txp-dev/textpattern/lib/txplib_db.php:442 
Stack trace: 
#0 /Users/[username]/Sites/_txp-dev/textpattern/lib/txplib_db.php(442): mysqli_query(Object(mysqli), 'CREATE TABLE IF...', 0) 
#1 /Users/[username]/Sites/_txp-dev/textpattern/lib/txplib_db.php(865): safe_query('CREATE TABLE IF...', false) 
#2 /Users/[username]/Sites/_txp-dev/textpattern/vendors/Textpattern/DB/Core.php(82): safe_create('txp_section', 'name V...') 
#3 /Users/[username]/Sites/_txp-dev/textpattern/setup/setup_lib.php(119): Textpattern\DB\Core->createAllTables() 
#4 /Users/[username]/Sites/_txp-dev/textpattern/setup/index.php(549): setup_db(Array) 
#5 /Users/[username]/Sites/_txp-dev/textpattern/setup/index.php(154): step_createTxp() 
#6 {main} thrown in /Users/[username]/Sites/_txp-dev/textpattern/lib/txplib_db.php on line 442
```

Some tables are created (see screenshot in Sequel Ace - total: 14).

Localhost, PHP 8.2.4, MySQL 8.0.28

<img width="241" alt="setup-db" src="https://user-images.githubusercontent.com/8944809/229678616-533ce990-843b-42e5-a7f5-244f24a4dfac.png">

**Comment by Bloke** [comment]
> Is this related?

Probably. Maybe we should constrain the key size. I'll fix that, sorry.

**Comment by Bloke** [comment]
@phiw13 Does https://github.com/textpattern/textpattern/commit/73ecda277648c34e226531bd80acdeafcdcd570b help at all? I'm not sure if specifying a partial primary key is valid SQL.

**Comment by phiw13** [comment]
@Bloke I’ll test tomorrow morning first thing, it is getting late this side of the sun.

**Comment by Bloke** [comment]
@phiw13 @petecooper Okay, I think as of fb28e98 that all the indices have now been converted successfully to PRIMARY KEYs. Fingers crossed.

**Comment by Bloke** [comment]
> Also related to these latest changes? ... I am followed everywhere by a memo/message “A new Textpattern version (4.9.0-dev) has been installed.”

Yes. That will be because the upgrade didn't finish and the last thing it does is set the version string. Your system never got that far so it thought it was still on 4.8.8.

**Comment by phiw13** [comment]
Ok… Installing from scratch (nice touch, going directly to the install panel), step 1, 2, 3, 4. Greeted with the message:

> That went well!

Logged in, and successfully accessed everything as needed & expected.

Good work.

–^–

I’ll check later for the 4.8.8 to 4.9(-dev) upgrade.

**Comment by Bloke** [comment]
Excellent, thank you for taking time to test this. Let's see how it fares in @petecooper's remote DB environment and go from there

**Comment by petecooper** [comment]
Scheduled for today - sorry for the delay - will report back.

**Comment by petecooper** [comment]
OK, using latest `dev`, here's the news…

Standard issue `config.php` as before, proceed to user creation, bails out with this error:

```
Fatal error: Uncaught mysqli_sql_exception: Storage engine MyISAM is disabled (Table creation is disallowed). in /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php:442
Stack trace:
  #0 /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php(442): mysqli_query()
  #1 /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php(865): safe_query()
  #2 /var/www/servers/textpattern.co/managed-demo/live/textpattern/vendors/Textpattern/DB/Core.php(82): safe_create() 
  #3 /var/www/servers/textpattern.co/managed-demo/live/textpattern/setup/setup_lib.php(119): Textpattern\DB\Core->createAllTables()
  #4 /var/www/servers/textpattern.co/managed-demo/live/textpattern/setup/index.php(551): setup_db()
  #5 /var/www/servers/textpattern.co/managed-demo/live/textpattern/setup/index.php(154): step_createTxp()
  #6 {main} thrown in /var/www/servers/textpattern.co/managed-demo/live/textpattern/lib/txplib_db.php on line 442
```

Appending `$txpcfg['dbengine'] = 'InnoDB';` and retrying the user creation part, we get…

![Screenshot 2023-04-06 at 16 15 12](https://user-images.githubusercontent.com/226578/230423196-98eaaf80-792a-421b-9b28-1980da559923.png)

…which is _excellent_ news!

**Comment by petecooper** [comment]
I don't know if https://github.com/textpattern/textpattern/issues/1859 should be reopened on the basis that the primary key issue (here) and the database engine (there) are two separate threads. According to https://dev.mysql.com/doc/refman/8.0/en/innodb-check-availability.html, there might be scope to figure out what engine(s) is/are present (or, alternatively, if the user knows the engine, perhaps offer a dropdown of sorts).

**Comment by Bloke** [comment]
Yay, well the reduced errors related to the primary keys is a step forward.

If there are environments where MyISAM is not available then it makes sense to expose the dbengine as a select list. The only thing is that there are a tonne, some of which may work, some of which probably won't. Some are MySQL specific and there may be others available for other engines when we move towards PDO. So I don't want to introduce something and then find we can't maintain it in future, or it paints us into a corner.

Asking MySQL what storage engines it supports is fine after you've established a connection, but we capture everything databasey in step 2 and then populate config.php before I Did It. So we'd need an intermediate step, or just add a pre-populated dropdown in step 2 to allow a choice between MyISAM and InnoDB, assuming that they're both available at all times, and if you pick one that doesn't exist, well, you'll get errors. Doesn't seem particularly satisfactory.

Ideas on how to approach this welcome.

**Comment by petecooper** [comment]
>So I don't want to introduce something and then find we can't maintain it in future, or it paints us into a corner.

Yep – good point, well made. Let's leave as-is for now. OP issue addressed, I will close. Many thanks, @Bloke!
