### ISSUE TITLE
Detect database engine during installation, adapt `config.php` accordingly

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1859]
### Is your feature request related to a problem?

Yes. ~~See https://github.com/textpattern/textpattern/issues/1858 for background.~~

### What is the feature?

Ascertain database server default (or supported) storage engine (e.g. InnoDB or MyISAM) during connection phase of installation and adapt `config.php` accordingly.

**Comment by vanmelick** [comment]
On 2023-01-19 17:35, Pete Cooper wrote:
> IS YOUR FEATURE REQUEST RELATED TO A PROBLEM?
> 
> Yes. See #1858 [1] for background.
> 
> WHAT IS THE FEATURE?
> 
> Ascertain database server default (or supported) storage engine (e.g.
> InnoDB or MyISAM) during connection phase of installation and adapt
> config.php accordingly.

The issue in #1858 is not about which storage engine is used, but rather 
a specific mysql setting/variable. Detecting the storage engine doesn't 
fix that. You'd have to add detection for that specific setting. 
Instead, just avoid the error and don't create tables without primary 
keys. Probably better for performance reasons anyway.

--Ruud
