### ISSUE TITLE
Tidying for the latest PHP

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1867]
I expect textpattern/lib/array_colump.php can be ditched, since our minimum requirements in dev exceed PHP 5.5.0 now? I can't see any reason to keep it.

Are there any other ToDo items in core we can revisit and tidy up now more stuff is available in PHP? I seem to recall spotting a few such items dotted around.

**Comment by Bloke** [comment]
@bloatware Any thoughts on tweaking core with respect [this little todo note](https://github.com/textpattern/textpattern/blob/dev/textpattern/include/txp_admin.php#L328)?

**Comment by bloatware** [comment]
@Bloke no memories of this one. And how `array_filter()` would help here?

**Comment by Bloke** [comment]
No idea, haha. Was hoping you could shed some light on it. If not, we can probably safely ditch the comment and leave it alone.

**Comment by petecooper** [comment]
OP file doesn't exist (presumably pruned), we can open separate issues to track inline `todo` comments, and Rector r&d is handled in https://github.com/textpattern/textpattern/issues/1868

Closing for now.
