### ISSUE TITLE
RFC Replace `<txp:search_result_count />` with `<txp:items_count />`

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1870]
The default templates (theme: four-point-nine) should be updated to use `<txp:items_count />` instead of `<txp:search_result_count />`

It is annoying to see a depreciation warning when experimenting  & testing with something on a vanilla install and debug mode is ON.

**Comment by Bloke** [comment]
Good catch. Will fix. Thank you.

**Comment by Bloke** [comment]
Ah, @bloatware has [already done it](https://github.com/textpattern/textpattern-default-theme/commit/813bea23e41d404a29c7dcb004c5c3b343852fdc) but it just needs merging into core.

*nips off to brush up on npm commands*

**Comment by Bloke** [comment]
Closed by https://github.com/textpattern/textpattern/commit/b366f0c6eb0680003a30198abece3f8b1c6230b5.
