### ISSUE TITLE
comments blocked by some ad blockers

### ISSUE THREAD

**Issue by colak** [textpattern/textpattern#1876]
### Expected behaviour

Show in the front end

### Actual behaviour

Comments are hidden in the frontend when ad blockers are active

### Steps to reproduce

Install ad blockers, visit a page with comments.

#### Additional information

Textpattern version: All

Web server vendor and version: NA

Database server vendor and version: NA

PHP version: NA

Operating system: NA

See [335441#p335441 forum post](https://forum.textpattern.com/viewtopic.php?pid=335441#p335441) from phiw13.

**Comment by petecooper** [comment]
This isn't uniform across _all_ ad blockers, so I've tweaked the issue title.

**Comment by petecooper** [comment]
We have a standard `class` / `id` namespace for comments on the default theme, and it's not _all_ ad blockers, so I'm inclined to say this is an ad blocker vendor issue, not Textpattern.

What theme authors decide to do with their `div`s and `span`s is outside our remit.

**Comment by petecooper** [comment]
Given that this isn't universal to _all_ ad blockers, and many (most?) ad blockers have filter updates that can work with reports of errors / exceptions, I'm going to close it for now. If it crops up again we can re-open and sort a plan to fix.
