### ISSUE TITLE
RFC: type=email for comment email input field

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1878]
Affected tag: <txp:comment_email_input />

current  output:
```
<input name="email" autocomplete="email" required="required" class="comment_email_input" id="email" type="text" size="32" value="">
```

note: `type=text`

Should that not be: `type=email` ?

That would provide much better input UI for small screen devices (dedicated keyboard type, form autofill) and basic input validation (and allow immediate feedback).

–^–

currently the user can input any odd string, there is absolutely no input validation – but the field automatically is set to `required`.

**Comment by philwareham** [comment]
That's a yes from me. I would do that myself but I just had a quick glance through the source code and the tag handlers code is baffling to me - can't see where it is rendered.

**Comment by Bloke** [comment]
Yeah, good catch. Leave it with me.
