### ISSUE TITLE
RFC: retarget 4.9.0 for winter 2023, factoring in PHP 8.3 support etc

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1879]
Since we're not being bowled over with requests for PHP 8.2 support (note that Textpattern 4.8.8 pre-dates PHP 8.2), I propose we target Textpattern 4.9.0 for winter 2023 or spring 2024, after the arrival of PHP 8.3 (due late November 2023).

We've currently got ~40 open issues in the 4.9 milestone. Clearly some will be bumped to minor or patch milestones, some will be added, some will be closed…but we've got a good chunk of stuff to get our teeth into as resources permit. From an optics perspective, PHP 8.3 support would be good to share, as well as the other significant changes / improvements we've already got baked in from previous commits.

I'd also suggest we have a remote video meeting at some point in summer / autumn 2023 where we can nail down what we're realistically going to be able to do with what we have available. I'm privileged to work with you amazing people, and I want to be sure we're all doing stuff within our means and we're all working towards the same goals. Summer is basically here, and we tend to have a natural lull during that time, with a refocus of energies in the autumn as the days get a little shorter.

As ever, I'd appreciate your take on stuff - either here or elsewhere. Best wishes to you all!

Textpattern 4.9 milestone: https://github.com/textpattern/textpattern/milestone/5

PHP 8.2 compatibility tracking: https://github.com/textpattern/textpattern/issues/1802
PHP 8.3 compatibility tracking: https://github.com/textpattern/textpattern/issues/1872

**Comment by Bloke** [comment]
Or. Y'know. Custom fields.

**Comment by petecooper** [comment]
PHP 8.3.0 was tagged today, will be GA in two days. PHP 8.1 enters security support in about 3 days.

We don't have official support for PHP 8.2 in Textpattern 4.8.8, so we're gonna be in a hinterland in a few days where production Textpattern is OK with a version of PHP in security support (8.1)…and not any versions in active support (8.2 & 8.3).

Paging @Bloke @bloatware @philwareham.

How viable is a winter release, realistically? We need a beta cycle or three, there's a whole raft of stuff that's changed that it's necessary for everyone's sanity. I can help where I can help (!?), but I'm mindful it's down to you dudes to do the dev work stuff.

Thank you.

**Comment by petecooper** [comment]
It feels like we're moving toward 4.9 organically, so I'll close this now in anticipation of a full flight plan.
