### ISSUE TITLE
plugin edit panel is blank

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1880]
Plugin is installed and NOT active, and plugin is not on the file system

Possibly an edge case… ?  Possible scenarios in which it might occur:

scenario 1. 
* a plugin has been installed a long while ago, maybe used, but is disabled (Active = No)
* the site has been upgraded from TXP 4.7.x to 4.8.x and then (later) to 4.9-dev [*]
* the plugin has NOT been installed on the file system (because it not active, I  think ?)

scenario  2 – TXP 4.9dev
* a plugin is installed (and dumped on the file system during install process), activated and then disabled (Active = No)
* by accident / user mistake / conscious user  decision, the plugin is removed from the file system (but not from the plugin panel)

Result, in both cases:

If the user then wants to check the plugin code on the plugin edit panel – the panel opens blank.

[*] If my memory is right, the plugin-from-file-system came with TXP 4.8.x

**Comment by Bloke** [comment]
Hmmm, a tricky one to trap. All our routines in the Plugin class (bar install) assume that the filesystem is intact, and tries to read the content from there when you click to Edit any plugin.

Possibly in the `read()` method, we could add an 'else' clause to see if the plugin's .php destination file solely `is_readable()`. If not, we have two options:

1. (nice) Read the contents from the database and repopulate the directory with that.
2. (not so nice) Fail with a 'please reinstall the plugin' message.

Not sure how easy (1) is. It would essentially sidestep any security we put in place during the installation process (hashes, verification, preview step) so it could be used as a method to surreptitiously install dubious content from a compromised database row. I'm not sure how likely that scenario is, but it's a possibility.

Option (2) is potentially easier by just bombing out if the endpoint is unreadable and squirting an appropriate message to the screen. Not very user friendly, but a little safer perhaps.

@bloatware Any thoughts on how we might handle this for the best?

**Comment by phiw13** [comment]
For option (2), a possibly slightly less messy path: a message that tells the user to enable the plugin and logout. Upon login again, the plugin will be dumped to the file system and editing will be possible.

Potentially saves  the user having to find the plugin for download.

**Comment by Bloke** [comment]
There are probably other ways to trigger a refresh of the content actually. It may even be possible to simply enable the plugin and navigate to another tab, then back to the Plugins panel. But that's only viable (presumably) if the plugin doesn't contain any errors - e.g. if it's broken due to a PHP or Txp upgrade.

If we figure out the best method - least intrusive, most likely to succeed in a variety of plugin state circumstances - then we can certainly see if we can present the user with this process to relink the plugin without having to download/reinstall.

**Comment by Bloke** [comment]
[Please try this](https://github.com/textpattern/textpattern/commit/454ffcb18a05b8d97a68b91fe7fac7e62baea13f). It should throw a `plugin_not_editable` string if the filesystem version is unavailable, and we can define the string as something like:

> Plugin is not available for editing. Please enable (activate) it, visit another admin-side panel, and return here to attempt relinking.

**Comment by Bloke** [comment]
Styled in https://github.com/textpattern/textpattern/commit/713c76adfdc85fd9d2104cf9fcf573d68c2aebbd.

I'll add the string to the repo and you can close the issues if you're happy. Thank you.

**Comment by phiw13** [comment]
Thanks, looks good.
