### ISSUE TITLE
detect-missing-adblocker

### ISSUE THREAD

**Issue by RealVegOs** [textpattern/textpattern#1883]
Could somebody please make a Textpattern plugin from this:
[detect-missing-adblocker](https://github.com/stefanbohacek/detect-missing-adblocker) 

Thanks for any consideration.

**Comment by petecooper** [comment]
Hey @RealVegOs - thanks for your interest in Textpattern.

You may have better visibility if you open a thread on the Textpattern forum, there's a group for plugin development there:

  https://forum.textpattern.com/viewforum.php?id=13

I'll close this issue as there's more of the core Textpattern family around there than here, so you're more likely going to get the correct people looking.
