### ISSUE TITLE
Invalid HTML in the `search_input.txp` form

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1885]
In https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/themes/four-point-nine/forms/misc/search_input.txp

The closing `</div>` should be `</search>`.

See also https://github.com/textpattern/textpattern/commit/fff26ce1e19e1aef569ac6b1373735ce738dd1bf

PS – consider adding `search { display: block; }` for older browsers in `default.css`.

**Comment by philwareham** [comment]
Will add CSS fallback as suggested.

**Comment by phiw13** [comment]
small issue? https://github.com/textpattern/textpattern/commit/2a4d5b92624bfa0f769ccc97b3ff60048427ea13#r128387607

**Comment by philwareham** [comment]
Gah, this is what happens when I try to work whilst having COVID. 😂

**Comment by philwareham** [comment]
Done properly this time.
