### ISSUE TITLE
admin js dropdown code for menu missing from recent commit

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#1886]
It looks like commit 5a9af91 accidentally dropped the dropdown code needed to open the main menu items from `/textpattern/admin/{admin-theme-name}/assets/js/main.js}`

### Expected behaviour

Clicking on a main menu (area) causes the corresponding drop-down menu to show.

### Actual behaviour

No menu shows.

### Solution

Reverting the change for main.js restores functionality.

**Comment by philwareham** [comment]
Bah, looks like Dependabot has pulled in Bootstrap 5 again without me noticing. Will fix.
