### ISSUE TITLE
wrong category 2 assigned to Welcome article

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1892]
This has annoyed me for a while, even if it is a bit of a  minor issue.

On a brand new install, article list panel, the “category 2” `<td />` for the 1st article (welcome to textpattern) has the `error` class applied (the cell is empty).

With the Hive theme it is not immediately visible, it is however with Sandspace theme.

Then you dig deeper and discover – by checking in the database directly - that the “Welcome…” article does have a category assigned, but that category does _not_ exist.

On initial install, with default lang (`en`):

category name used by the “Welcome…” article: `meaningful-labour`
category name as listed in the DB, txp_category table: `meaninful-labor`

Saving the “Welcome…” article makes it disappear.

TXP 4.9 and 4.8.8 if memory serves, PHP 8.2 and now 8.3.

screengrab (I created an additional article for more viewing pleasure)
<img width="345" alt="cat2_name" src="https://github.com/textpattern/textpattern/assets/8944809/f315c5a1-ee2a-4925-bc6f-db57b2f9b85a">

**Comment by petecooper** [comment]
[Mea culpa](https://github.com/textpattern/textpattern/commit/bd31f77ae7a4004828a09c2274845c522a1560ef) - now [fixed](https://github.com/textpattern/textpattern/commit/70809237a880404bafa66d1439d3eda8721736fa).
