### ISSUE TITLE
How to customize <title></title>

### ISSUE THREAD

**Issue by bluesky0341** [textpattern/textpattern#1897]
for example,
if my article title is ceramic cup,

then click view source code for this article

<title>ceramic cup</title>
above is not good for google seo

i need <title>ceramic cup, cermic mug</title>,this is good for google seo

how can i do?

**Comment by Bloke** [comment]
Please direct this sort of usability query to the [Textpattern forum](https://forum.textpattern.com/). GitHub issues are for discussing code changes and bugs.

By default, the template will render the article title between the `<title>` tags. Look in the Presentation>Pages and Presentation>Forms panels for the `<txp:page_title />` tag. If you wish to display something different, change the template to use, for example, `<txp:keywords />` and put what you wish to display inside the HTML tags in the article's Keywords field.
