### ISSUE TITLE
how to install EDITOR

### ISSUE THREAD

**Issue by bluesky0341** [textpattern/textpattern#1898]
how to install new EDITOR

**Comment by bluesky0341** [comment]
you can check this in the attachment
![1704104340513](https://github.com/textpattern/textpattern/assets/105836139/e0d134ff-e55c-48f2-b561-c69cbd22703f)

**Comment by Bloke** [comment]
The GitHub issue queue is for issues relating to the code, not for general queries. please direct your question to the [Textpattern forum](https://forum.textpattern.com/).

That said, if you mean a WYSIWYG editor, like you get in some CMS', then we don't have one per se out of the box. You can try some plugins such as [smd_textile_bar](https://github.com/Bloke/smd_textile_bar/releases). There are others that add functionality such as CodeMirror to the admin side. Alternatively, it's possible to click the Preview link above the text areas to see a mockup of what the content will look like. That feature has been significantly improved in the forthcoming version 4.9.0of Textpattern.
