### ISSUE TITLE
Safari 15.7 / iOS 15 preview text view not loading

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1899]
The panel opens *empty* save for the UI (title, close button, etc) – the article contents never loads. Interestingly, as soon as I switch to the HTML view, the Sanitize warning fires (messagepane shows the issues)

Console report:

```JS
[Error] Unhandled Promise Rejection: TypeError: Illegal constructor
	CSSStyleSheet (textpattern.js:2167)
	(anonymous function) (textpattern.js:2167)
	asyncFunctionResume
	dispatch (jquery.js:2:40041)
	trigger (jquery.js:2:70130)
	(anonymous function) (jquery.js:2:70734)
	each (jquery.js:2:3134)
	(anonymous function) (textpattern.js:885)
	each (jquery.js:2:3134)
	(anonymous function) (textpattern.js:874)
	each (jquery.js:2:3134)
	handle (textpattern.js:871)
	(anonymous function) (textpattern.js:897)
	c (jquery.js:2:25310)
	fireWith (jquery.js:2:26055)
	l (jquery.js:2:77794)
	(anonymous function) (jquery.js:2:80267)
```

(JS error is based on the 2024 jan 04 textpattern.js)

Safari 15.latest on macOS will probably also been affected. @Bloke – do you still that MBP running 10.15? I think  that is the version of Safari you have installed.

**Comment by bloatware** [comment]
Sorry, I have no mean to test it, the only iOS version at my disposal is 17.1.2 (works fine). It just looks like Safari is [late](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/CSSStyleSheet) to the party.

**Comment by phiw13** [comment]
Tested a potential solution in this [forum thread](https://forum.textpattern.com/viewtopic.php?pid=336314#p336314)  that works perfectly fine.
