### ISSUE TITLE
Show spam form action (or rather page URL) is not updated on clear search

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1900]
On a site with many comments, filter comments by parent (admin side), clicking its magnifying glass. Then clear the search and click on 'Show spam'. The parent filter is applied again.

I know why, but do we really need this 'show spam' feature?

**Comment by bici** [comment]
never use it

**Comment by phiw13** [comment]
> do we really need this 'show spam' feature?

You’d leave all (un-managed) “spam” comments always visible on the admin panel then ? That is fine as far as I am concerned. In those situation I had to deal with, those comments are either approved (marked as “not spam“ and approved for public viewing) or deleted as soon as possible.

**Comment by bici** [comment]
Perhaps I misunderstood the poll? But I no longer ever want to use comments on a website. Not worth it.

**Comment by bloatware** [comment]
Yep, I see no point in hiding spam: either delete or approve it. And there is no issue for those of us who do not use comments, of course.

Thanks for comments :-)

**Comment by bloatware** [comment]
I would rather make this checkbox act as 'show ONLY spam', to be able to quickly batch select/delete it.

**Comment by bloatware** [comment]
Thanks for thumb ups for transforming 'show spam' into a filter. I guess then the checkbox form is nod needed any more, otherwise people who (normally) have checked it, would see ONLY spam. Might it be just a shortcut link for `visible=-1` search criteria?
