### ISSUE TITLE
Function strftime() has been DEPRECATED as of PHP 8.1.0 but is still used in safe_strftime

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#1902]
### Expected behaviour

**Content > Write** panel rendering smoothly.

### Actual behaviour

Upon entering the **Content > Write** panel with an existing article, an error message is printed (sometimes twice, depending on whether the article's LastMod column is set) into the page saying ```Function strftime() is deprecated in .../textpattern/lib/txplib_misc.php at line 2837.```

The culprit is IMHO located here https://github.com/textpattern/textpattern/blob/4c62fcac51b9d08d78ffca29669dbedae56a014c/textpattern/include/txp_article.php#L1385 and here https://github.com/textpattern/textpattern/blob/4c62fcac51b9d08d78ffca29669dbedae56a014c/textpattern/include/txp_article.php#L1388

### Steps to reproduce

Use PHP 8.1.0 or above on your testbed. Open an existing article into the "Content > Write" tab. Enjoy.

### Additional information

Textpattern version: 4.9.0-dev

Web server vendor and version: Apache/2.4.58 (Win64)
Database server vendor and version: 10.4.32-MariaDB
PHP version: 8.3.18.3.1.
Operating system: Win11

**Comment by bloatware** [comment]
Are you the [lucky one](https://github.com/textpattern/textpattern/issues/1780#issuecomment-1026689987), just to be sure?

**Comment by rwetzlmayr** [comment]
I am not sure at all, sorry. Investigating. 

I am currently rebuilding my dev setup and suddenly out of the blue this error appeared. First, I blamed XDEBUG, then I found [this thread](https://forum.textpattern.com/viewtopic.php?id=51934) and now I'm a bit confused what really happens...

My php.ini contains the line `;extension=intl` with a prefix comment. I am running XAMPP like testdeputy [here](https://forum.textpattern.com/viewtopic.php?pid=335403#p335403).

My phpinfo() reports this no matter whether I enable or disable `;extension=intl` in the php.ini file :

#### intl
Internationalization support | enabled
-- | --
ICU version | 73.2
ICU Data version | 73.2
ICU TZData version | 2023c
ICU Unicode version | 15.0


Confusing... Any help very appreciated.

**Comment by bloatware** [comment]
Theoretically, txp calls `strftime()` only if it has no other choice:

- the date format includes a localized string (month name etc)
- `intl` extension is not enabled

Have you tried to uncomment `extension=intl` (and restart the server)?

**Comment by rwetzlmayr** [comment]
I now changed the Archive date format in Preferences to YYYY-MM-dd, and then back to the previous pattern `%b %d, %I:%M %p` which it had when the error popped up. The error vanished. Misterioso.

**Comment by bloatware** [comment]
If it's on a remote server, there is sometimes a lag after settings change. Or a cache issue. Otherwise no clue.

**Comment by rwetzlmayr** [comment]
I am working on my local machine

And now the error has reappeared without me doing anything. It looks like it depends on the $whatever. Time to close the lid it seems.

**Comment by bloatware** [comment]
Is `class_exists('IntlDateFormatter')` misbehaving somehow?

**Comment by rwetzlmayr** [comment]
`class_exists('IntlDateFormatter')` returns `false` correctly in situations when the error pops up.
After good night's sleep and uncommenting `extension=intl` in `php.ini` the error does not occur any more.
Looks like PEBKAC. Sorry for the confusion.
