### ISSUE TITLE
Incorrect layout on the plugins panel

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1904]
Following https://github.com/textpattern/textpattern/commit/453e6e7a1e5bf05984a2d0154596079c037dae38#commitcomment-137902824

The container that holds the “Install Plugin” box (`<section class=txp-details>`) used to also contain the “Column display options” widget (`div class="txp-list-options"`) This does not happen anymore, restulting in the widget bein out-of-alignment

Reason, as far as can tell, the widget is inserted with JS (line 1707++) and depends on the previous block being `<div class=txp-control-panel>`. This has been remove and replaced by `<section class=txp-details>` on the Plugins panel.

Easiest fix: wrap the `<section class=txp-details>` inside a `<div class=txp-control-panel>`. Expected HTML:

```
<div class="class="txp-layout-cell-row txp-list-head""
  <div class="txp-control-panel">
    <section class="txp-details">
    </section>
  </div>
</div>
```

(this has the benefit of not needing any stylesheet changes, see this mockup https://dev.l-c-n.com/txp-4.9/txp-admin-plugin.html - with theme Sandspace)

–^–

Also a suggestion: wrap a `<p>` the `<a class="txp-button">` link-button. Benefit for AT users: this marks a slight pause and separate the different actions better, for the visual layout: vertical spacing, no need for stylesheet changes.

-^-

Screen shots: before (Fuschia layout outline-edges) and current

<img width="873" alt="pluginspanel_old" src="https://github.com/textpattern/textpattern/assets/8944809/b942eae7-4bb6-4d27-bc36-a19bac407f4d">

<img width="884" alt="pluginspanel_new" src="https://github.com/textpattern/textpattern/assets/8944809/60ce0dcf-2ae3-4d4a-9689-00230370541b">

**Comment by bloatware** [comment]
Nice catch, thank you, patched. But in my Sandspace version, this sends `<input name="install_new">`button out of the area, probably caused by this rule:
```
.plugin-data [type="submit"] {
	float: inline-end;
	margin: 0 var(--margin);
}
```

**Comment by bloatware** [comment]
All good now, thanks.
