### ISSUE TITLE
RFC: Textpattern 4.9 is final 4.x release; Textpattern 5.0 next 'big' release

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1905]
Wish 4.9 were the last txp 4 version, to finish with dev->cf dance and move to txp 5, scarifying bwc when necessary.

_Originally posted by @bloatware in https://github.com/textpattern/textpattern/issues/1133#issuecomment-1914444345_

@bloatware I would be totally fine with moving to TXP v5. It's kind of ridiculous that there has never been a version apart from 4 (and probably harmed perception of the software to some extent).

_Originally posted by @philwareham in https://github.com/textpattern/textpattern/issues/1133#issuecomment-1914474653_

**Comment by petecooper** [comment]
I'm a +1 for Textpattern 5.0 as successor to 4.9.

It's a good opportunity to let some backwards compatibility go to pasture, and support a sensible (reduced) range of PHP versions, and there are a whole bunch of other advantages.

Comments welcome.

**Comment by Bloke** [comment]
No argument from me for 5.0.

**Comment by bloatware** [comment]
I'm especially annoyed when resolving dev->cf merge conflicts, which make me think the whole bwc would be problematic. So a major update looks natural, unleashing our hands as a bonus.

**Comment by Bloke** [comment]
Yeah, commit merges for CF and other branches is a pain to keep in sync. The same happened with crockery many moons ago.

Options:
* Get 4.9 out the door and keep them side by side for a wee smidge longer; OR
* Branch off now and just remember to cherry pick commits between now and 4.9.0 final to push to the 5.0.0 branch.

They both have pain points. Choose your poison.

**Comment by bloatware** [comment]
This can wait for 4.9 release, imo.

**Comment by petecooper** [comment]
Core team in favour, no other comments in 100 days - closing.
