### ISSUE TITLE
utf8_en/decode() are deprecated in PHP 8.2

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1909]
With the [deprecation of utf8_encode and utf8_decode](https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated) in PHP 8.2 - and removal in PHP 9.0 - we need to replace our core usage of the functions, primarily in our String type and Mail classes.

For `utf8_encode()` replacements might be:

```
mb_convert_encoding($string, "UTF-8", mb_detect_encoding($string));
```
OR
```
mb_convert_encoding($string, 'UTF-8', mb_list_encodings());
```

And for `utf8decode()`:

```
mb_convert_encoding($string, 'ISO-8859-1', 'UTF-8');
```

However, that assumes the mbstring extension is loaded. Defensively coding a check for the existence of the library around each call seems a waste of processing and lots of repetition.

I propose we introduce a class/function that handles this more elegantly so we can simply replace our utf8_en/decode calls with a single replacement wrapper method that checks the extension and offers the conversion as a return value. StringType.php already includes a check for the extension, but the utf8_decode() doesn't use it, so that is a potentially simple fix.

The big question I have is: what do we do if the extension is not loaded? Do we return the original unencoded string (which may lead to unexpected output if its UTF8ness is assumed), do we return false, or throw an exception? Or try an alternative extension like iconv or intl?

Anyone any ideas how best to approach this?

**Comment by bloatware** [comment]
Note that the only occurrence of `utf8_encode()` in core is `safe_encode()` function, that acts already as a wrapper.

**Comment by Bloke** [comment]
Yes but we still need to remove it from that function.

So do we introduce safe_decode() ?

**Comment by bloatware** [comment]
It looks like a check for `is_callable('utf8_encode')` is already done in `safe_encode()`, wouldn't this suffice? As for `safe_decode()`, it is just a shortcut for `safe_encode($str, 'ISO-8859-1', 'UTF-8')`, probably not worth a stand-alone function?

**Comment by Bloke** [comment]
Yeah, I'm fine with that. But we still have 11 calls to `utf8_decode()` in core that need swapping out for something.

Are you proposing we globally replace `utf8_decode($str)` with `safe_encode($str, 'ISO-8859-1', 'UTF-8')` and leave it at that?

**Comment by bloatware** [comment]
Dunno, maybe. Decoding to `ISO-8859-1` only seems to be used in mail functions. Once these few calls are swapped, we should be all done?

**Comment by Bloke** [comment]
I think so yeah. Plus the plugin panel tidy up if it's not been done already. Haven't checked the commits  today.

**Comment by philwareham** [comment]
I'll do the plugin panel cleanup before the end of this week.
