### ISSUE TITLE
Articles with status 'Hidden' do not return a `404 Not Found` response when requested but a `200 OK`

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#1911]
### Expected behaviour

If the status of an existing article is set to 'Hidden', I expect the public page of that article to return a `404` response when the URL of the article is requested. I expect the site to not disclose if an article exists at a known URL, regardless of the status of the article.

### Actual behaviour

The page is rendered with the default page layout lacking the article's content but with a [200 OK](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) response. `<txp:page_title />` renders the correct article title O_o.

### Steps to reproduce

1. Go to the admin area of the Textpattern demo site [and edit the sample article](https://dev-demo.textpattern.co/dev/textpattern/index.php?event=article&step=edit&ID=1).
2. Set the status of the article to __Hidden__.
2.1. You can now log out. It doesn't make any difference AFAICS.
3. Request the [hidden article](https://dev-demo.textpattern.co/dev/index.php?id=1).

#### Additional information
Textpattern version: v4.9.0-dev, running the demo site as of today

**Comment by bloatware** [comment]
Should be fixed, thanks @rwetzlmayr, though the code might be refactored yet. Since the article preview happens on the public side now, we had to open the access to hidden articles, but more carefully.
