### ISSUE TITLE
Form names may contain hyphens or other 'strange' characters. Such form names do not work as 'txp::' shortcuts.

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#1913]
I have created three forms with these properties:

| Form name   | Form code |
| ------------- | ------------- |
| fu  | FU  |
| fu-bar | FU-BAR  |
| fu²bar | FU²BAR  |

Then I used these forms in the body of an article, using both the long term ``txp:output_form`` and the shortcode ``txp::`` call methods:

```
* <txp:output_form form="fu" />
* <txp:output_form form="fu-bar" />
* <txp:output_form form="fu²bar" />
* <txp::fu />
* <txp::fu-bar />
* <txp::fu²bar />
```

### Expected behaviour

The article's output should read:

```
<ul>
	<li>FU</li>
	<li>FU-BAR</li>
	<li>FU²BAR</li>
	<li>FU</li>
	<li>FU-BAR</li>
	<li>FU²BAR</li>
</ul>
```

### Actual behaviour

The short-code invocations of the forms with a hyphen or a `²` character in their name are rendered literally and apparently not parsed.
```
<ul>
	<li>FU</li>
	<li>FU-BAR</li>
	<li>FU²BAR</li>
	<li>FU</li>
	<li><txp::fu-bar></txp::fu-bar></li>
	<li><txp::fu²bar></txp::fu²bar></li>
</ul>
```

### Steps to reproduce

...see above.

#### Additional information

Textpattern allows literally any character to be part of form names. The parse segment that detects the shortcode may make assumptions about the legit characters in form names.

While using a funny character like `²` in form names looks unusual, using hyphens in form names seems quite natural to me. Speakers of languages not written in latin characters may have more general assumptions about what's in a name.

Textpattern version: current state of https://dev-demo.textpattern.co

**Comment by phiw13** [comment]
all those name fields (forms, pages, sections, themes, …) are rather problematic with non-ASCII, or white-space characters, see also https://github.com/textpattern/textpattern/issues/1826

**Comment by Bloke** [comment]
Yeah I think it's our function that sanitizes for pages or URL or something. The lack of hyphens for short codes has caught me out a few times. It'd be nice if we could work around it somehow.

**Comment by bloatware** [comment]
The reason is that shortcode names are detected via txp parser pattern, which, historically, forbids not-alphadigital characters in tag names (because they were directly mapped to php function names before 4.6). We could either

- extend the allowed characters set in all tag names (probably easier)
- or do it specifically for `txp::` pattern used for shortcodes detection.

Or just leave it as is.

**Comment by rwetzlmayr** [comment]
Thanks for the background explanations.I note know what to adhere to when invoking short codes

**Comment by rwetzlmayr** [comment]
From my point of view, an extension of the pattern to include hyphens (and other similar syllable-separating glyphs contained in the usual ASCII range, whatever they may be) would be helpful, while respecting the technical limitations that inevitably exist. 

I happened to stumble into this situation when I was adapting a pre-built site theme to Textpattern, which was built from partials named using a `block-subelement` naming convention.

In addition to the code change, a short explanatory note in the corresponding [docs page (maybe here)](https://docs.textpattern.com/tags/shortcodes/custom-short-tags-and-shortcodes#when-short-tag-preference-is-disabled) would probably provide enough clues for people like me and [a certain developer](https://github.com/textpattern/textpattern/issues/1913#issuecomment-1982773767) who stumble across a silent `txp::` shortcode tag without any obvious clue as to why this thing just does nothing at all.
