### ISSUE TITLE
"Admin > Visitor logs" panel rendering gets caught in EasyPrivacy, a very popular ad blocking filter

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#1914]
The Textpattern visitor logs panel at **Admin > Visitor logs** uses a request to scroll through the log entries beyond the very first listing page, or to toggle the "entries per page" limit. This request contains the `?event=log&` URL parameter, e.g. `?event=log&step=log_change_pageby&qty=24`.

The `?event=log&` URL parameter [is a filter criterion](https://github.com/easylist/easylist/blob/95d6d5ff0ff09dc59fcb22360dac0b4f89b3e225/easyprivacy/easyprivacy_general.txt#L2692) included in the ['EasyPrivacy' EasyList filter list](https://easylist.to/), which is a very popular ad blocking filter list [bundled with uBlock Origin](https://github.com/gorhill/uBlock/wiki/Filter-list-licenses), AdBlock Plus and Opera Browser, among others. 

Any request containing this filter criterion will be blocked. As a result, the visitor log freezes whenever the user tries to go to page 2 or change the "entries per page" setting. 

I think there are three options to deal with this situation, in increasing order of clumsiness:

1.  Leave it as it is.
1. Modify Textpattern's visitor log display code to use a different URL parameter.
1. Apply to [EasyList to change their filter set](https://forums.lanik.us/viewforum.php?f=64-report-incorrectly-removed-content) and remove Textpattern's offending URL signature from it.
1. There is no option 4.

**Comment by Bloke** [comment]
I'm fine with option 2. I don't think any plugins rely on that event. Maybe smd_lately, but that's ancient anyway and easily patched if it does.

Are there any core links like eLink or sLink that jump to the log panel for filtering? I don't think there are, so it should be pretty safe to just change the event name now.

**Comment by rwetzlmayr** [comment]
+1.

`pageview` might be a proper event term, methinks. `visit` is not, despite what the menu title says.

I would prepare a pull request if you agree. Please let me know.

**Comment by rwetzlmayr** [comment]
+1 for option 2. 

If you like, I would be happy to look at this issue and make a pull request. I encounter it in a real-world situation, so the fix solves my own needs.

**Comment by rwetzlmayr** [comment]
[Done.](https://github.com/textpattern/textpattern/pull/1915)

As a by-product, I have added the word 'lore' to my working knowledge of the English language, hoping that it does not have a pejorative connotation in constellations of which I am unaware.

**Comment by rwetzlmayr** [comment]
Closed via #1915.
