### ISSUE TITLE
Setting permlink_mode to '/title' and trailing_slash to 'No' causes reproducible 404 on single article view

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#1916]
### Expected behaviour

Article lists and single articles will render properly with any `permlink_mode`  and `trailing_slash` setting.

### Actual behaviour

1. In prefs, set `permlink_mode` to '/title' and `trailing_slash` to 'List'.

2. Go to the public site and click on the 'Articles' navbar section link (http://example.com/articles/). The correct article list is rendered.

1. Go to the public site and click on the 'Welcome to Textpattern' article title link (http://example.com/welcome-to-textpattern). The proper article page is rendered.

1. Set `permlink_mode` to '/title' and `trailing_slash` to **'No'** .

2. Go to the public site and click on the 'Articles' navbar section link (http://example.com/articles). The correct article list is rendered.

1. Go to the public site and click on the 'Welcome to Textpattern' article title link (http://example.com/welcome-to-textpattern). A **404 Not Found** error page is rendered.

#### Additional information

Textpattern version: 4.9.0-dev

PHP version: 8.2.12, 8.2.16

Operating system: Win64, Linux 3.10.0

**Comment by bloatware** [comment]
The silly rabbit must have [fixed](https://github.com/textpattern/textpattern/commit/bf68838d065fe9c229b8eb067e40d71f78a6d7ef) it, please test.

**Comment by rwetzlmayr** [comment]
Works for me! Thanks!
