### ISSUE TITLE
Plugins panel elements on `dev` are wonky (potentially WIP?)

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1924]
4.8.8 plugins panel:
<img width="1442" alt="Screenshot 2024-05-09 at 21 13 32" src="https://github.com/textpattern/textpattern/assets/226578/c5a8dff5-1558-4733-bd83-f04de8f60d6a">

`dev` plugins panel:
<img width="1442" alt="Screenshot 2024-05-09 at 21 13 35" src="https://github.com/textpattern/textpattern/assets/226578/3c2c4578-6e25-408a-a2ea-ecf7e37015bb">

**Comment by Bloke** [comment]
Hopefully fixed now. Thank you, phiw13.
