### ISSUE TITLE
escape="tidy, textile" not behaving

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#1925]
Given an image caption:

`I am a caption with "source attribution":https://textpattern.com for an image`

And a tag that displays the image caption in some article page context:

```
<txp:variable name="caption" value='<txp:image_info escape="tidy, textile" />' />
...
...
<txp:variable name="caption" />
```

### Expected behaviour

A Textiled link, according to [the docs](https://docs.textpattern.com/tags/learning/#available-escape-values):

> escape="tidy, textile": Remove spaces/newlines, prepend a single space to remove the surrounding <p> tag, then Textile the content.

### Actual behaviour

The text is not passed through Textile and remains unprocessed, raw text.

#### Additional information

Removing the 'tidy' renders the proper Textiled link. Using `escape="textile, tidy"` also works. But using `escape="tidy, textile"` doesn't.

Textpattern version: 4.9.0-dev

Web server vendor and version: dev-demo server

**Comment by bloatware** [comment]
Damn, I thought `setBlockTags(false)` would be a cleaner way to prevent block wrapping, but it handles quotes too. So what, revert, tweak?

**Comment by Bloke** [comment]
Not sure what's best. Tweaking just adds more layers of complexity and exceptions but if it's doable then by all means go for it. Revert if necessary.

We need to put aside some time to set up the unit testing framework, for the parser at the overy least. That would save us some serious effort and manual testing, and let us be more confident in changes. It's on the list!

**Comment by bloatware** [comment]
Must be fixed now in the last php-textile, please test.

**Comment by Bloke** [comment]
This seems to be working now. Thanks, Oleg/Jukka. Closing.
