### ISSUE TITLE
`blueimp/jQuery-File-Upload` is now archived

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1927]
https://github.com/blueimp/jQuery-File-Upload

We currently use this for our file & image uploads. It's archived, which indicates it will no longer be developed.

We should consider finding a maintained / supported alternative for Textpattern 5, if we're still rolling with jQuery at that point.

**Comment by petecooper** [comment]
Tagging https://github.com/textpattern/textpattern/issues/1404

**Comment by bloatware** [comment]
Then I guess we can safely modify it as we need? We actually use only one 22Kb file from the package (plus our own adapters). I'm not really fond of custom protocols (and the size) of Uppy and alike. But alternatives welcome.

**Comment by petecooper** [comment]
+1 for not using Uppy. If it's viable to continue as-is, even better!

**Comment by bloatware** [comment]
We'll need to adapt it to jQuery 4, but this looks feasible.

**Comment by bloatware** [comment]
I think our version is compatible with jQuery 4 now, so we'd better remove the dependency, to avoid an accidental override.
