### ISSUE TITLE
Consider updating the suggested CSP directives in `config-dist.php`:

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1928]
1. consider adding `blob:` to the `img-src` directive
2. remove the `block-all-mixed-content;` directive, as it is obsolete – see [MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content)

**Comment by philwareham** [comment]
Done, thanks Philippe, hope all well with you.
