### ISSUE TITLE
MySQL 9.0 compatibility tracking

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1936]
MySQL 9.0 is now GA: https://dev.mysql.com/doc/relnotes/mysql/9.0/en/

It is likely that some hosting providers will deploy MySQL 9.0 in due course, so we need to make sure where we stand regarding Textpattern compatibility. More info on support here: https://www.mysql.com/support/supportedplatforms/database.html

MySQL 9.0 is a feature release, not an LTS release, so the uptake likely won't be as high compared to e.g. MySQL 8.4 (see https://github.com/textpattern/textpattern/issues/1923 for compatibility)

I'll make some time in the coming weeks for some outline testing.

**Comment by Bloke** [comment]
Nothing major I can see that will affect us in a cursory glance of the changes.
