### ISSUE TITLE
Sync multisite-specific files with their counterparts

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1943]
Was previously https://github.com/textpattern/textpattern-toolbelt/issues/22

We need a script to run periodically (manually / automatically) to sync the multisite files with their associated counterparts in the main file tree. We've missed a few of these on past releases, and a script would at least give us a fighting chance to get it right.

- [ ] Update this issue with file locations
- [ ] Write and test YAML workflow
- [ ] Activate workflow

**Comment by Bloke** [comment]
Yeah. I largely ignored that line in the build that said "check .ultimate counterparts". I think I checked .htaccess and config-dist and forgot that Textpattern.js and so forth need to be synced.

Are there ever going to be instances when there's custom code in the multisite installs? If not, there are two places we could sync this.

1. At build time in the gitdist script somehow.
2. Automatically after any commits if we build a CI hook or something to copy over any files we know are shared.

**Comment by petecooper** [comment]
I'm inclined towards 2 on the grounds someone may choose to checkout the source tree prior to a tagged release, and that way it'd be correct (even being dev code).

**Comment by Bloke** [comment]
Me too. Is it easy to set up? I've never done it on GitHub

**Comment by petecooper** [comment]
As I understand it, we should be able to build a GitHub Actions workflow in .yaml format and drop it into `.github/workflows`…and that should be it. Leave it with me for now, I'll take a look after the beta.1 post is ready and we have the word out there.

**Comment by petecooper** [comment]
Manually done as far as possible, closing for now until a GitHub Workflow can do the heavy lifting
