### ISSUE TITLE
RFC: would PHP profiling be useful for dev work?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1945]
I've had PHP-SPX in my to-do list for a while, and I'm getting around to it over winter. Is there any benefit to having a dev-only server with it?:

https://github.com/NoiseByNorthwest/php-spx

Access would be restricted to just dev team, and on the basis of us having a dev-only server, there could be other things bolted on in a similar vein, should they be of interest.

Tagging @Bloke and @bloatware, though anyone is welcome to comment.

**Comment by bloatware** [comment]
This surely looks more powerful than our own trace class. I'm not sure to be able to get much more from it, though, without trying. If you are ready to invest into a potential overkill...

**Comment by petecooper** [comment]
Thanks for the insight @bloatware – it appears to be relatively straightforward to set up (compared to some of the horror shows I've encountered) so I'll investigate further.
