### ISSUE TITLE
light-dark() and backwards compatibility

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1955]
Continuing a conversation from this [commit](https://github.com/textpattern/textpattern/commit/b8b04cba6b2036c917168b555c3ae25a89d4584c#commitcomment-148924154)  –  where I am unable to reply for some mysterious GH reason. The comments-block never finish loading when logged-in with both Safari & Firefox.

@bloatware 

> Thank you, I finally see what `color-scheme: light dark;` means.

BTW, the article at MDN is fairly good: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark

>For older browsers, do you mean adding an extra section with colour definitions? Then there is no point in using `light-dark()` function at all?

Well there is a point in using the `light-dark()` function: forward looking modern code – aka progressive enhancement. That said, I don’t think that textpattern.css should/must cary a fallback for older browsers. Coverage for the `light-dark()` function is pretty wide (last two versions of Safari, Firefox 128 ESR, Firefox, Chromium ).

An admin-theme could include a fallback if it chooses to support older UA and older OS.

**Comment by bloatware** [comment]
CSS is becoming more and more capable, and I'm all for modernising our code. 80% browsers support should be enough.

**Comment by phiw13** [comment]
That is Ok.

I’ll add support in theme Sandspace (it doesn’t cost much, ~< 0.3kb).

Thanks for adding `color-scheme: light dark;` in textpattern.css.
