### ISSUE TITLE
Add a preview bloc into discuss page

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#211]
_From [patrick....@gmail.com](https://code.google.com/u/111387824658555502103/) on June 09, 2012 09:42:53_

What steps will reproduce the problem? 1. Not a problem, just a feature idea.

What is this feature request? What is the expected output?
- From the TXP back-end, actual comments page allows to make changes into the comment message. That's very useful. But final users without HTML knowledge can be surprised to see all these strange tags. Adding a comment message preview, above or below the textarea as it will appear on the public side, could be much readable.

This feature request isn't a very complex transformation. It could improve the UI experience.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=207_

**Comment by vanmelick** [comment]
An alternative solution would be to store the comment both as textile and HTML, similar to what we do with articles.

**Comment by jools-r** [comment]
Came across this: drmonkeyninja has a plugin for this: [arc_admin_comment_preview](https://github.com/drmonkeyninja/arc_admin_comment_preview). It's not a full edit window (which would be better), just a jQuery preview of the output.

**Comment by petecooper** [comment]
This is included as a line item in 
https://github.com/textpattern/textpattern/issues/308 (see 
https://github.com/textpattern/textpattern/issues/308#issuecomment-361098916 for context), so closing.
