### ISSUE TITLE
The message pane (#messagepane) should be moved out of .txp-header

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#237]
_From [ph.witte...@gmail.com](https://code.google.com/u/100003077239308735091/) on July 25, 2012 09:01:48_

The #messagepane is in no way related to the semantics of 'header' (masthead) of the Textpattern CMS UI. Assuming we move, txp 4.6 ?, towards html5 markup, .txp-head would become a `<header>` instead of a `<div>` in the present markup. #messagepane would then be more out of place (according to the semantics of the `<header>` element).

#messagepane should become either
[1] a direct child of body
[2] a first- or last-child of .txp-body

(I prefer option the second option; after all that element is directly related to actions performed on elements contained inside .txp-body)

Having #messagepane as a child of .txp-head does impose some (serious) limits on what can be done with the 'header'. For example in my Sandspaces theme (*) I position the 'header' as a side-column using position: absolute. If I were to use .txp-header for this, #messagepane would forever be trapped inside that block. At present I work around this by adding a div (#masthead in my case), child of .txp-header and position that. I'd like to get rid of that additional div.

I think the Hive theme would face similar constrains.

An additional benefit: a theme author doesn't need to add #messagepane inside his or her themename.php file…

(*) http://forum.textpattern.com/viewtopic.php?id=38139 ---
(this is certainly not urgent for Txp 4.5, more like something for Textpattern.next

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=233_

**Comment by Bloke** [comment]
@philwareham Is this done in either master or admin-layout-update? If so, can it be closed?

**Comment by phiw13** [comment]
Nope, it is not yet done on either branch.
If I understand things correctly, it should go in either `txplib_head.php` or `txplib_html.php` (depending on where it is added to the `main.txp-body` element).

**Comment by philwareham** [comment]
Will be done soon - it's a 4.6 blocker for me.

**Comment by philwareham** [comment]
Done. Can be closed when we merge admin-layout-update branch into master.

**Comment by philwareham** [comment]
@phiw13 Also: maybe the HTML of these can probably be improved, since the `role` and alert state (`success`, `error`, etc.) classes could go on the `div` in core itself rather than a child `span` in my Hive theme?

**Comment by phiw13** [comment]
@philwareham
Oh sure. If it is not complicated to do, go for it. The less code a theme needs to maintain in the theme.php file, the better!
