### ISSUE TITLE
populateArticleData() custom field handling

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#24]
_From [netcarv...@gmail.com](https://code.google.com/u/106891488036972988949/) on July 23, 2009 15:06:12_
# Problem

Currently populateArticleData() adds the custom fields to the $thisarticle
array using the label the administrators setup in the advanced preferences
page. However, no checking seems to be done to determine if the user's
chosen field name is already used by textpattern. This can give rise to
some confusing scenarios.

If a user were to name one of their custom fields such that the name
matches an existing field of the $thisarticle array, then that value is
overwritten by the value of the custom field, potentially leading to
unpredictable behavior and potentially support issues.

For example, if you create a custom field named 'body' then all existing
data in any article's 'body' field becomes hidden -- overwritten by the
value of the corresponding custom field. 
# Proposed Solution

The populateArticleData() routine should add the custom field values to
$thisarticle array in a segregated namespace (perhaps as simple as one
created by prefixing 'cf_' to the start of every custom field's name.)

The custom field tags would also need adapting to fetch field values from
the namespace too.

I'd suggest adding a single routine to the txplib_misc.php file to provide
a standard implementation for this 'name' => 'custom name' mapping and that
this function be used internally by populateArticleData() and the custom
field tag handlers. 
# Impact on Plugins

Custom field accessing plugins will probably need to be modified.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=20_

**Comment by petecooper** [comment]
Should be covered by https://github.com/textpattern/textpattern/issues/456 in real terms, so closing for the moment.
