### ISSUE TITLE
add protocol "sms" to classTextile.php $this->unrestricted_url_schemes

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#244]
_From [janusz.s...@gmail.com](https://code.google.com/u/105455425832352332023/) on August 08, 2012 14:36:47_

Protocol "sms" could be added to a list of unrestricted_url_schemes in constructor of Textile in classTextille.php on line 425

For example like this:
$this->unrestricted_url_schemes = array('http','https','ftp','mailto','file','tel','callto','sms','sftp'); http://www.ietf.org/rfc/rfc5724.txt

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=240_

**Comment by petecooper** [comment]
This looks like a more appropriate issue/request for https://github.com/textile/php-textile than https://github.com/textpattern/textpattern.

**Comment by philwareham** [comment]
Closing, as this is not directly Textpattern related. Please open at the [Textile rep](https://github.com/textile/php-textile) if you want to explore further.
