### ISSUE TITLE
Consistent expiry date validation

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#245]
_From [r.wetzlmayr](https://code.google.com/u/r.wetzlmayr/) on August 09, 2012 07:45:29_

gomedia reports at http://forum.textpattern.com/viewtopic.php?pid=264191#p264191 :

1) If you try to create a new article with Expires timestamp filled in, the article is saved with a blank Expires timestamp.

2) If you edit an article which already has Expires set & attempt to set it before Posted, a green “Article posted” message is displayed & the Expires timestamp is ignored. Shouldn’t there be a warning?

3) If you edit an article which already has Expires set & attempt to set the Posted timestamp to be after Expires, a green “Article posted” message is displayed & the Posted timestamp is saved. The database now has an article saved with Posted > Expires timestamps. Shouldn’t it be an error?

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=241_

**Comment by Bloke** [comment]
Fixed already.
