### ISSUE TITLE
Double urlencode?

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#250]
_From [dev.nnnn@gmail.com](https://code.google.com/u/dev.nnnn@gmail.com/) on August 20, 2012 16:18:49_

What steps will reproduce the problem? 1.Make a category using multi-byte (eg."報告")
2.Publish an article using the category.
3.View the article from top page, and the url of the category looks wierd. What is the expected output? What do you see instead? The encoded url seems to be encoded double, which makes the url very messy even using clean url. Using the category example "報告", the expected/insted output is as follows.
EXPECTED: http://example.com/textpattern/&#37;E3&#37;82&#37;AB&#37;E3&#37;83&#37;86&#37;E3&#37;82&#37;B4&#37;E3&#37;83&#37;AA/&#37;e5&#37;a0&#37;b1&#37;e5&#37;91&#37;8a INSTEAD: http://example.com/textpattern/&#37;E3&#37;82&#37;AB&#37;E3&#37;83&#37;86&#37;E3&#37;82&#37;B4&#37;E3&#37;83&#37;AA/&#37;25e5&#37;25a0&#37;25b1&#37;25e5&#37;2591&#37;258a/ Please use labels and text to provide additional information. Using the language Japanese, the clean-url shall be " http://example.com/textpattern/カテゴリ/報告 ", but the url becomes " http://example.com/textpattern/カテゴリ/&#37;e5&#37;a0&#37;b1&#37;e5&#37;91&#37;8a ".
Using urlencode, encoding "&#37;e5&#37;a0&#37;b1&#37;e5&#37;91&#37;8a" becomes "&#37;25e5&#37;25a0&#37;25b1&#37;25e5&#37;2591&#37;258a", which can be seen in the example above.
Since the link itself is working properly, it seems more like an extra encoding error when addind a new category.
The encoded string also can be observed by looking through the admin panel to edit the category while the category name will show the encoded string in the text-field (expected to be decoded. Maybe a different issue?). The category title seems to be decoded as expected (see attached screenshot).

**Attachment:** [category_edit_Textpattern_CMS.png](http://code.google.com/p/textpattern/issues/detail?id=246)

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=246_

**Comment by vanmelick** [comment]
The problem lies in the sanitizeForUrl function, which in this case uses rawurlencode on the input. I think this is incorrect, because we normally do escaping/encoding as late as possible. In fact urlescaping happens in pagelinkurl() (as it should) which is always used to create links based on the category name. 

Also, as it is now, entering 報告 results first in an ugly category name %e5%a0%b1%e5%91%8a, but if you edit the category and save it again, that changes to e5a0b1e5918a. This should not occur.

Pull request sent.

**Comment by Bloke** [comment]
Closed by 4e5df263f9cd657bb57d2cb152ce5171fef4f75b
