### ISSUE TITLE
load_lang() - get all untranslated strings from 'en-gb'

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#261]
_From [zasl...@gmail.com](https://code.google.com/u/112308807792196922428/) on August 30, 2012 12:07:48_

Get all untranslated strings from 'en-gb' language for admin/public interface.

ps: function load_lang_event() also something loads from txp_lang, but the current code this function is not used anywhere.

Patch attached.

**Attachment:** [txplib_misc_load_lang_r4090.patch](http://code.google.com/p/textpattern/issues/detail?id=257)

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=257_

**Comment by Bloke** [comment]
Closed by 33ac470979dd9fd854e7a1eef72160aa1dbfbcaf
