### ISSUE TITLE
Suppressing errors if textpattern folder is corrupt

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#269]
_From [zasl...@gmail.com](https://code.google.com/u/112308807792196922428/) on September 06, 2012 08:57:35_

What steps will reproduce the problem? 1. Delete folder /textpattern
2. Open site via web

What do you see?
Many errors with real_full_path to textpattern: /var/www/txp_svn/
---
Warning: include(/var/www/txp_svn/textpattern/lib/constants.php) [function.include]: failed to open stream: No such file or directory in /var/www/txp_svn/index.php on line 68

Warning: include() [function.include]: Failed opening '/var/www/txp_svn/textpattern/lib/constants.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/txp_svn/index.php on line 68

Warning: include(/var/www/txp_svn/textpattern/lib/txplib_misc.php) [function.include]: failed to open stream: No such file or directory in /var/www/txp_svn/index.php on line 69

Warning: include() [function.include]: Failed opening '/var/www/txp_svn/textpattern/lib/txplib_misc.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/txp_svn/index.php on line 69

Fatal error: Call to undefined function txp_status_header() in /var/www/txp_svn/index.php on line 72
---

After patch will be displayed simple string:
---
config.php is missing or corrupt. To install Textpattern, visit textpattern/setup/
---

**Attachment:** [index_noerror_r4096.patch](http://code.google.com/p/textpattern/issues/detail?id=265)

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=265_

**Comment by rwetzlmayr** [comment]
Won't fix, see https://github.com/textpattern/textpattern/pull/521#issuecomment-132162081 for rationale.
