### ISSUE TITLE
Key/value store

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#281]
_From [r.wetzlmayr](https://code.google.com/u/r.wetzlmayr/) on October 11, 2012 15:47:47_

Implement a key/value store facility as a base component for unlimited custom fields, unlimited categories, and other custom schema extensions.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=277_

**Comment by Bloke** [comment]
I'm closing this in lieu of #279. Although we could use a single table for key/value storage across CFs/categories/tags/whatever I'm not altogether comfortable with how to implement it. The proposed custom field storage solution (different tables depending on data type) is very efficient in both space and performance.

When we look at unlimited taxonomy, we can revisit this and perhaps either use the CF idea there, or (more likely) come up with something else.
