### ISSUE TITLE
<txp:comment_x_tags/> don't allow closing without trailing space.

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#29]
_From [j...@beardedbaby.net](https://code.google.com/u/101554656051604297040/) on August 04, 2009 17:32:42_

What steps will reproduce the problem? 1. Use any txp:comment tag like so: <txp:comment_name_input />. it works in 4.0.8 and 4.2.0-
rc1.
2. Now, use the same tag without a trailing space: <txp:comment_name_input/>. Textpattern 
throws the following warning, and fails to render the specified comment-form output: "Textpattern 
Warning: tag does not exist  on line xxx".

As far as I can tell, you can use *any* other Textpattern or TXP plugin tag without the trailing 
space-- so far, I've only noticed the comment form tags being affected by this.

This behavior appears in 4.0.8 and 4.2.0-rc1.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=25_

**Comment by vanmelick** [comment]
Fixed by pull request #513

**Comment by bloatware** [comment]
Should it be closed, or we expect 4.5.8?
