### ISSUE TITLE
Prevent clients from caching old resources on updates

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#291]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on October 15, 2012 03:40:52_

Currently Textpattern doesn't inform browsers about resource (js, css) changes and refresh caches on updates. This causes issues to users when Textpattern is updated.

Options:

1. add a URL query to the resource links that changes based on version number
2. rename files on release to include the version number
3. combine 1 and 2, and try to do URL rewriting if supported

I'm leaning towards first one, even that it's nasty method according HTTP specs.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=287_

**Comment by Bloke** [comment]
This has been done insofar as `TEXTPATTERN_SCRIPT_URL` and `TEXTPATTERN_SCRIPT_ATTACH_VERSION` have been added as options to `script_js()`. Neither are currently used in core or our release mechanism to refer to cache-busted copies of resources, though.

Is the _ability_ to use them enough to close this issue? Or should we rename `textpattern.js` as `textpattern.v4.6.0.js` first and convert any core calls to use the new flags? Same with the CSS (and JS) in the core themes?

Note that doing this also impacts any plugins that include `textpattern.js` manually as they'd need to also use the version number or convert to using `script_js()` with the appropriate flags.

**Comment by philwareham** [comment]
I suggest that you harness the new functionality now. Let me know how I should do the CSS in themes too.

Regarding plugins that use textpattern.js - isn't that script always loaded in the admin side anyway? Or do you mean public plugins that reference it? Could a rerouter be put in as a bridge to the new cached version - where all our core directly point to textpattern.4.6.0.js and a redirect to that also put into a textpattern.js file? Not sure if that is possible?

**Comment by philwareham** [comment]
You could then also have a 'js' folder in that contains the scripts, to keep things ordered nicely.

**Comment by Bloke** [comment]
Right, here's the lowdown to do this. First the pre-requisites:

* Once the relevant `script_js()` calls are patched (see below), resources are _only_ mapped with their version numbers for non-dev environments. Thus we need two copies of each resource to live in the repo: one for dev and one for live. This has the benefit that any plugins linking directly to the file without using a patched `script_js(`) call will still get the dev version, which at release time will be identical to the versioned file. Force refresh to get new content is worst case scenario.
* As you stated, it makes sense to put such files in a subdirectory to stop them cluttering the main directory. This has the effect that if anyone manually links to the file in its old location, it'll fail, but there's nothing we can do about that short of supplying symlinks (which won't work under Windows, I guess).
* Decide which assets to version. Current choices are:
* --> `textpattern.js` (yes)
* --> /vendors/jquery/jquery/jquery.js (maybe)
* --> /vendors/jquery/jquery-ui/jquery-ui.js (maybe)
* --> /vendors/dropbox/zxcvbn/zxcvbn.js (maybe)
* Regarding CSS files, currently they're all linked or imported manually so no versioning is possible. We'd need to change `css.php` and/or introduce a new function similar to `script_js()` , e.g. `load_asset($css_file, $flags, $route)` and convert all PHP resource loading to use it. That doesn't help with any `@import` statements inside CSS files themselves, which would need to all be manually altered to pick up the versioned filenames. That has the knock-on effect that we don't get the luxury of a dev/live split during development, as the versioned resource filename would need to be used all the time. What's the impact of that with your SASS builder? Can it squirt out two versions of each file, one with version number, one without?
* On release, we need to make sure that the current non-versioned names of all js/css assets are duplicated with the new version number appended so the versioned assets are up-to-date.

Converting the js calls is easy. Just append the version flag to any calls that currently use `TEXTPATTERN_SCRIPT_URL`. For example:

    script_js('textpattern.js', TEXTPATTERN_SCRIPT_URL | TEXTPATTERN_SCRIPT_ATTACH_VERSION);

So, given the issues above regarding css file assets and the fact we're only potentially dealing with four js files, is this worth doing just for `.js` assets? And if so, do we move `textpattern.js` into a `js` subdirectory?

**Comment by philwareham** [comment]
For CSS, we are only talking about admin side yes? Public side should be left exactly as-is. My admin themes don't use `css.php` they just link directly to the CSS files (and the theme-specific JS also links direct). The themes also don't use any CSS `@import` rules anywhere within (and they never will either).

So all I need to do is amend my build script to append the version on a few links and files which is a breeze to do. Nice and simple.

For JavaScript I would limit the cache busting to just `textpattern.js` as that is the one most likely to break between releases (all the other vendor libraries are mature and won't cause major problems if older versions are cached for a limited time). Otherwise things get complicated and messy after a few releases with loads of versions of jQuery and suchlike in the vendors folder, which I wouldn't be keen on.

**Comment by philwareham** [comment]
I've created [a branch for this issue](https://github.com/textpattern/textpattern/tree/issue291). We can test this there.

I would also suggest that the release version of the scripts in `js` directory (the ones appended with version number) are also minified.

**Comment by philwareham** [comment]
I've been thinking about this, and all 3 of the aforementioned solutions aren't great really - I don't want to introduce multiple versioned files into people's installs and also create more complexity in the code.

WordPress uses URL queries to achieve this task but although this is the cleanest and simplest solution, as @rwetzlmayr says, it introduces a constant performance penalty. If that is undesirable then I'd say close this issue and just add a couple of sentences in the upgrade instructions that users may need to refresh their cache after an upgrade (it's not like we upgrade very often anyway!).

Thoughts?

**Comment by rwetzlmayr** [comment]
> Thoughts?

Leave it as it is.

**Comment by Bloke** [comment]
Close it and the branch it rode in on. Worry about it another day, if at all.

**Comment by philwareham** [comment]
Agreed. Closing.
