### ISSUE TITLE
<txp:article_custom /> in body or excerpt breaks feeds

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#31]
_From [r.wetzlmayr](https://code.google.com/u/r.wetzlmayr/) on August 10, 2009 13:35:24_

Reported by makss in http://forum.textpattern.com/viewtopic.php?id=29399 :

Steps to reproduce:

1. Create a few articles
2. Create another article with
2.1 body:
<txp:article_custom wraptag="ul" break="li"
<txp:permlink><txp:title /></txp:permlink>
</txp:article_custom>
2.2 excerpt:
<txp:article_custom wraptag="ul" break="li"
<txp:permlink><txp:title /></txp:permlink>
</txp:article_custom>
3. ATOM and RSS feeds contain body and excerpt of the last created article
in all feed items

Reason: $thisarticle global gets overwritten while parsing the embedded
article_custom tags.

**Attachment:** [feeds-with-embedded-article-tags-r3266.patch](http://code.google.com/p/textpattern/issues/detail?id=27)

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=27_

**Comment by vanmelick** [comment]
Restoring info that got lost:

---

 Project Member Reported by r.wetzlmayr, Aug 10, 2009

Reported by makss in http://forum.textpattern.com/viewtopic.php?id=29399:

Steps to reproduce:

A. Create a few articles
B. Create another article
```xml
with 2.1 body:
`<txp:article_custom wraptag="ul" break="li">`
`<txp:permlink><txp:title /></txp:permlink>`
`</txp:article_custom>`
2.2 excerpt:
`<txp:article_custom wraptag="ul" break="li">`
`<txp:permlink><txp:title /></txp:permlink>`
`</txp:article_custom>`
```
C. ATOM and RSS feeds contain body and excerpt of the last created article
in all feed items

Reason: $thisarticle global gets overwritten while parsing the embedded
article_custom tags.

---

Robert added this patch:
```diff
> Index: textpattern/publish/atom.php
> ===================================================================
--- textpattern/publish/atom.php	(revision 3266)
+++ textpattern/publish/atom.php	(working copy)
@@ -117,8 +117,8 @@
 					$e['category1'] = (trim($Category1) ? '<category term="'.htmlspecialchars($Category1).'" />' : '');
 					$e['category2'] = (trim($Category2) ? '<category term="'.htmlspecialchars($Category2).'" />' : '');
 
> -					$summary = trim(replace_relative_urls(parse($thisarticle['excerpt']), $permlink));
> -					$content = trim(replace_relative_urls(parse($thisarticle['body']), $permlink));
+					$summary = trim(replace_relative_urls(parse($Excerpt_html), $permlink));
+					$content = trim(replace_relative_urls(parse($Body_html), $permlink));
 
 					if ($syndicate_body_or_excerpt) {
 						# short feed: use body as summary if there's no excerpt
Index: textpattern/publish/rss.php
===================================================================
--- textpattern/publish/rss.php	(revision 3266)
+++ textpattern/publish/rss.php	(working copy)
@@ -69,8 +69,8 @@
 					$a['posted'] = $uPosted;
 
 					$permlink = permlinkurl($a);
-					$summary = trim(replace_relative_urls(parse($thisarticle['excerpt']), $permlink));
-					$content = trim(replace_relative_urls(parse($thisarticle['body']), $permlink));
+					$summary = trim(replace_relative_urls(parse($Excerpt_html), $permlink));
+					$content = trim(replace_relative_urls(parse($Body_html), $permlink));
 
 					if ($syndicate_body_or_excerpt) {
 						# short feed: use body as summary if there's no excerpt
```

**Comment by bloatware** [comment]
Presumably closed by two commits above, please confirm.
