### ISSUE TITLE
Optimizing admin-side queries

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#310]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on November 02, 2012 04:53:43_

Some of the admin-side SQL statements either eat too much resources or do not scale well enough when the site grows.

One example of this is the Article list panel (?event=list) which strangely fetches section, author and category names when looping over the results making;

A. maximum of 400 queries.
B. eating memory and runtime which increases rapidly when site grows
C. most importantly makes correct sorting impossible.

C. also one of the reasons why these details where never present in the table but just used for tooltips; table can not be sorted by these values.

For example the list panels maximum of 400 queries can be dropped to 1 with couple LEFT JOINS.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=306_

**Comment by Bloke** [comment]
This was done on the article List and File panels ages ago. Images and Links (possibly among others) still to go.
