### ISSUE TITLE
Multi-page articles

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#312]
_From [Alexande...@gmail.com](https://code.google.com/u/112778174728213832438/) on November 03, 2012 03:27:46_

Add the ability to create multi-page article.
This can be done as an "add new page" in the "Write" tab or add separator to textile markup(such as .page)

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=308_

**Comment by vanmelick** [comment]
Previous comment contained this link:
http://www.iut-fbleau.fr/projet/etc/index.php?id=14

**Comment by philwareham** [comment]
This is out of scope, and can be done with current plugins or via future plans for unlimited custom fields. So closing this.
