### ISSUE TITLE
Multi-plugin install capability

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#319]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on November 08, 2012 20:08:18_

As requested here: http://forum.textpattern.com/viewtopic.php?id=38647 Multi-plugin installing could be supported. This would include:
- way to join multiple plugin packages together somehow (note: current format allows whitespace). Maybe JSON?
- preview step showing all plugins as an list separated by headings.

Possible issues:
- if one of the plugins errors out, rest of the plugins will not be installed. But I suppose that is not that big of deal. It would happen too if it was a single install.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=315_

**Comment by bloatware** [comment]
This should probably be linked to themes support.

**Comment by philwareham** [comment]
This, and themes install support, could be covered by recreating functionality of Gocom's Textpattern-Installer and Textpattern-Lock in the core. Subject to plugin authors putting Composer support into their plugins.

The single plugin install method would still work too, via the standard Plugins admin panel.

**Comment by cara-tm** [comment]
👍

**Comment by philwareham** [comment]
Pushing this to v4.8 - I think it's best to get a functional themes support first and then build upon it in future releases. Otherwise we risk creating too much work for single release.

**Comment by philwareham** [comment]
This specific issue is negated in part by the plugin upload feature we have now, and the dedicated plugins directory. I will close the issue now. We are always looking at ways of improving plugin handling and the upcoming new plugins site may be of help long-term (we have loose plans for checking plugin versions, auto updates, etc. using that site as an pseudo API).
