### ISSUE TITLE
JavaScript routing

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#320]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on November 08, 2012 21:24:05_

As suggested by Julián: http://forum.textpattern.com/viewtopic.php?pid=248474#p248474 This would include removing embedded JavaScript blocks to an external file and introducing some super simple a routing functions.

Textpattern already has 'textpattern.event' and 'textpattern.step' which can be used for accurate routing.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=316_

**Comment by Bloke** [comment]
Mostly, if not completely done. Review later.
