### ISSUE TITLE
Prefs panel overhaul

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#325]
_From [stefdawson](https://code.google.com/u/stefdawson/) on November 12, 2012 14:34:34_

* Move 'Languages' to its own menu.
* Consolidate basic and advanced prefs into one screen.
* Open up prefs to all users so plugins can use the prefs panel.
* Improve pref panel security.
* Improve markup.
* Better UX for saving / traversing / collapsing pref groups as it could become unwieldy with many plugins and prefs.
* Improve API to allow (for example) pref removal.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=321_

**Comment by philwareham** [comment]
This work has been merged now in 4.6 master branch. Closing.
