### ISSUE TITLE
Displaying human-readable titles instead of names

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#331]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on November 15, 2012 19:55:23_

On the forums displaying Section titles instead of names has been requested numerous times. One of common reasons is localization, and well, can make things clearer to the regular folks as the section has an actual name instead of the URL path resource.

Since the dev branch now uses joined queries on the list panels, doing this task wouldn't be hard. It's literally about changing few variables around.

Proposed changes include showing and sorting by:

- section titles on Articles panel (the list).
- section titles on Write panel (the editor).
- author's real name instead of login id on Articles, Files, Links, Images panels (lists).
- category title on Images, Links and Files panels.

Like now the alternative (in this case name) would be shown as a tooltip when hovering over the value (cell).

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=327_

**Comment by Bloke** [comment]
Fixed already.
