### ISSUE TITLE
txp_die doesn't encode Location header

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#337]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on December 02, 2012 10:30:26_

Which leads to sending improper, broken headers, injections and redirects not working accordingly.

Location field's value should follow RFC2616 as far as I'm aware. http://www.ietf.org/rfc/rfc2616.txt This basically means that every special non-ASCII byte and not a control character should be URL encoded (percent encoded). This would take care about URL encoding, but also proper sanitation.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=333_

**Comment by vanmelick** [comment]
I don't think this is fixable in txp_die, because you have to encode the URL when you construct it, not when you're given a complete URL, so this would have to be done by the user when using <txp:die> in templates.

**Comment by philwareham** [comment]
Out of core scope. Closing.
