### ISSUE TITLE
Compatibility with jQuery 1.9

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#349]
_From [r.wetzlmayr](https://code.google.com/u/r.wetzlmayr/) on December 18, 2012 10:49:28_

jQuery 1.9 removes many of the items they deprecated during the last few versions of jQuery; see http://blog.jquery.com/2012/12/17/jquery-1-9-beta-1-released/ This issue tracks any compatibility issues within Textpattern.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=345_

**Comment by philwareham** [comment]
Is this issue fixed now, considering we are on jQuery 1.11 and I've not encountered any obvious issues?

**Comment by rwetzlmayr** [comment]
> obvious issues?

The only obvious issue would be the occurrence of a warning starting with ``JQMIGRATE`` in the browser console: We still [link to the jQuery Migrate plugin](https://github.com/textpattern/textpattern/blob/master/textpattern/lib/txplib_head.php#L102) which provides compatibility for pre-1.9 code.

Have you encountered such a message anywhere? If not, we can remove ``jquery-migrate`` while keeping an eye on 'real' jQuery errors popping up.

**Comment by philwareham** [comment]
I've not encountered any of those messages, and I've been using the admin area a lot recently. I will remove query-migrate soon. As I have now dropped support for IE8 in the admin-layout-update we could feasibly move to jQuery 2 at some stage. Maybe for v4.7 - gives any plugin authors time to update their JavaScript if necessary.
