### ISSUE TITLE
Modernize OOP-PSR-0 new developer APIs

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#351]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on December 20, 2012 02:42:41_

The plan would be to namespace and move the APIs to vendors. New design would include using shared blueprints and abstract base classes, setters and getters.

This would include the new 4.6 APIs such as:
- Pref
- User
- Template [Form, Page, Style]
- More as thing go on.

Planned methods would include the once already bundled in the current API base:

public function create();
public function update();
public function exists();
public function rename($name);
public function remove();

Getter methods would include:

public function item();
public function items();
public function __toString();

Setter and getter value methods depend on the API, used fields are obviously different. For instance Form would include:

public function __construct($name);
public function name($name);
public function type($type);
public function code($code);

Also some supporting functions (validation) would be included:

public function is_valid_name();
public function is_valid_type();
public function types();
public function essential();

The end-developer the usage would be straightforward. Small example with forms:

$form = Textpattern_Template_Form();
$form->name('formName');
$form->type('misc');
$form->code('Abc.');
$form->create();

Would set name to 'formName', type to 'misc' and code/markup to 'Abc.' after which it runs 'create' command to the created instance.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=347_

**Comment by Bloke** [comment]
Ongoing...

**Comment by Bloke** [comment]
I'm going to close this as it's just hanging around. We know we have to continue modernising the core and migrating stuff to more OO principles so we'll just keep chipping away at it.
