### ISSUE TITLE
Admin side search

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#352]
_From [stefdawson](https://code.google.com/u/stefdawson/) on December 21, 2012 16:11:52_

Current search facility is limited to one field at a time. A preferable approach is to make the default 'search everything' (within the context of the current panel) and then allow filtering if more specific results are required.

Aims of this may include:

* A single search box with popup filter, akin to like http://tympanus.net/Tutorials/UIElements/SearchBox/ but with all boxes selected by default.
* 'Memory' so the last-used checkboxes for each panel are remembered (per user).
* Option to automatically prepend 'all' to the passed list of search locations.
* Allow developers to utilise the core's search box on their own panels.
* Ability for plugins to chime in and add columns / search options.
* Fixes for the columns that are defined as Integer: alphanumeric searches always return 'true' if the database has a '0' in the column.
* Backwards compatibility with existing plugins that use the URL to filter as a link destination.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=348_

**Comment by philwareham** [comment]
This is done in admin-layout-branch and will be merged soon. Closing.
