### ISSUE TITLE
Page number with <txp:page type="url" /> tag.

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#353]
_From [patrick....@gmail.com](https://code.google.com/u/111387824658555502103/) on December 21, 2012 22:13:28_

What steps will reproduce the problem? - Devs, please trying to test using the <txp:page type="url" /> tag on a multiple pages template context. It seems that this tag doesn't render properly the first number.

- For my meta, I'm using this in order to display the correct first page number :

<meta name="description" content="<txp:php>

echo( (page_url(array('type'=>'pg')) == '' ? 'Page 1 - ' : 'Page '.page_url(array('type'=>'pg')).' - ' ) );

</txp:php> What is the expected output? What do you see instead? - Just display the "1" number for the first page context. What version of the product are you using? On what operating system? - Older one, so I'm not sure this affects the dev version. Please provide any additional information below. - Nothing more, see above.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=349_

**Comment by vanmelick** [comment]
Some stuff got lost. Let's try that again:

---

What steps will reproduce the problem?
 - Devs, please trying to test using the `<txp:page_url type="pg" />` tag on a multiple pages template context. It seems that this tag doesn't render properly the first number.
- For my meta, I'm using this in order to display the correct first page number :

> `<meta name="description" content="<txp:php>`
> `echo( (page_url(array('type'=>'pg')) == '' ? 'Page 1 - ' : 'Page '.page_url(array('type'=>'pg')).' - ' ) );`
> `</txp:php>`

What is the expected output? What do you see instead?
- Just display the "1" number for the first page context.

What version of the product are you using? On what operating system?
- Older one, so I'm not sure this affects the dev version.

Please provide any additional information below.
- Nothing more, see above.

**Comment by Bloke** [comment]
`<txp:page_url>` just dumps whatever is given in the `type` attribute to the screen if it exists in `$pretext`. That's pretty lame. Perhaps we intervene in this case and squirt out a '1' if the pg is not set. Would that potentially break backwards compatibility? Probably...

**Comment by vanmelick** [comment]
http://www.textpattern.net/wiki/index.php?title=page_url
If we'd make it behave as documented, then:
* check if type is one of those listed
* if type is 'pg' and it's not set, return 1 (which would be the 'current page number in article list mode' as documented)

Should I prepare a patch?

**Comment by Bloke** [comment]
Hmmm, I'm sure that, just like with `<txp:custom_field>` someone will be using this to output stuff that's not officially sanctioned by the documentation. Not checking the `type` explicitly also means it's a handy feature for any plugin authors who add stuff to `$pretext` as it can be extracted using this tag.

So maybe we'd best allow anything in `$pretext` to be returned (after all, all global and available to the page so nothing there is private or sensitive). But I'd prefer to remove the hacky error suppression by checking if the passed `$type` exists in `$pretext` first and then, as you say, return 1 for the first page if using `type="pg"`, as I believe that to be more correct behaviour.

Feel free to patch away, if you'd be so kind!

**Comment by rwetzlmayr** [comment]
Fixed via #520. 

Thanks, Ruud.
