### ISSUE TITLE
Certain characters in users' real names cause invalid SMTP headers 

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#357]
_From [r.wetzlmayr](https://code.google.com/u/r.wetzlmayr/) on January 07, 2013 08:59:12_

What steps will reproduce the problem? 1. Create a user with a real name containing one or more characters which are special to the SMTP protocol (single quote, double quote, left or right angle brackets), e.g. /Richard O'Brien/ or /<FOO><BAR>/
2. Login as this user and create a new user to send a sign-up email, or perform any other action which causes Textpattern to send an email with a "From:" header from this user. What is the expected output? What do you see instead? - Expected: "From:" headers intact
- Actual result: "From:" headers mangled by double backslashes, or invalidated by including unescaped angle brackets.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=353_

**Comment by vanmelick** [comment]
Can't reproduce this.
The name in the "From:" header is encoded as type 'phrase' whenever possible.
If it contains characters with the 8th bit set or one of the 32 first control characters then it's base64 encoded.
If not, but it contains characters ][()<>@,;:".\x5C, then the \ and " are backslash quoted and the entire string is contained in "".
If not, it doesn't need encoding.

**Comment by vanmelick** [comment]
Original issue text, more readable:

---

What steps will reproduce the problem?
1. Create a user with a real name containing one or more characters which are special to the SMTP protocol (single quote, double quote, left or right angle brackets), e.g. `Richard O'Brien` or `<FOO><BAR>`
2. Login as this user and create a new user to send a sign-up email, or perform any other action which causes Textpattern to send an email with a "From:" header from this user.

What is the expected output? What do you see instead?
- Expected: "From:" headers intact
- Actual result: "From:" headers mangled by double backslashes, or invalidated by including unescaped angle brackets.

**Comment by rwetzlmayr** [comment]
Cannot reproduce either now. Might have been unintentionally fixed w/ other changes to the mail code.
