### ISSUE TITLE
Integration for jQuery UI's sortable interaction

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#360]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on January 26, 2013 15:55:19_

The cool stuff in jQuery UI comes in form of interactions, like sortable, e.g. sorting. These interactions could be very beneficial for both core (sorting lists, load order) and 3rd party plugin developers.

All these widgets need server end point, or more specifically away to get that data to the server. Providing a simple wrapper for these interactions would:
1. Make implementation easy, making requirement only adding few attributes to the HTML markup.
2. Offer consistent event hooks and attribute names.
3. Since the events, the interactions would itself be extendable by plugins.

For $.ui.sortable() the todo would be;
- Expose public method $.txpSortable() with pre-configured options.
- Expose few attributes for easy interaction; item identifier (data-txp-sortable-id) and widget identifier (.txp-sortable).
- On drag updates send the updated order to the server (e.g. ?event=event&step=sortable_save&order[]=id1&order[]=id2) and receive/process a script response as offered.

Furthermore:
- Later on this can be extended to support connected lists, and various event bindings which deemed necessary. For simple-single lists only 'update' event is needed.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=356_

**Comment by philwareham** [comment]
I think this can be closed. I provide styles for jQuery UI interactions but they don't currently work on touch devices (it's a planned future rewrite for jQuery UI) and we don't actively use the in our UI.
