### ISSUE TITLE
Allow users to remove branding and add their own logos

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#364]
_From [p...@designhive.com](https://code.google.com/u/100991452291349786445/) on February 15, 2013 11:33:22_

Some users want to brand the admin-side of Textpattern for their clients, and so would like to easily replace the logo with their own designs.

Investigate ways to achieve this without breaking the layout.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=360_

**Comment by Bloke** [comment]
@philwareham How close is this to reality, if not achieved already?

**Comment by philwareham** [comment]
The CSS is now cleaner, and we provide an override file, so if someone knows a little CSS they can easily do this. Closing, thanks.
