### ISSUE TITLE
Merge save_pane_state functions into one

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#372]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on February 24, 2013 10:54:40_

Instead of having those separate functions for each panel, we could calculate and use tokens. The toggle links are generated in PHP, so they could contain fraud preventing token of their own.

By using a token, you will no longer need back-offices, but just that one. This same code could then be re-used for any other async event apart from the super-advanced editors. Like for instance pageby, visible columns etc. could be synched the same way, having no PHP paths of their own.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=368_

**Comment by bloatware** [comment]
More I look at this, more I think that UI states management should be delegated to client JS (via `localStorage`): no more AJAX requests on every click, nor weird security tokens. Yes, it would be per user+browser rather than per user, but few clicks when you change the browser is not a great annoyance, and there is nothing really secret in panes states. It could even be convenient to store different settings on a widescreen laptop and a phone. Any thoughts?

**Comment by philwareham** [comment]
Sounds logical - if it speeds of/simplifies the code then I'd say do it. localStorage is designed for this sort of stuff anyway.

**Comment by bloatware** [comment]
I have created the [local-storage](https://github.com/textpattern/textpattern/tree/local-storage) branch to test the `localStorage` approach. Seems to work, though I wasn't able to find a `localStorage`-incapable browser for tests.

It eliminates the need for db-storage of panes states in both core and complying plugins. We can test it and close this issue by merely deleting `txp_pane.php` if everything is ok. Meanwhile, I don't see a big risk in keeping it as is.

**Comment by philwareham** [comment]
OK, thanks Oleg. [All modern browsers support `localStorage`](http://caniuse.com/#search=localstorage) so that's great (Opera Mini we don't support anyway, so don't worry about that one).

**Comment by bloatware** [comment]
Thanks Phil, that means testing will be pertinent. It actually should work side by side with the current db storage, so I would merge it in 4.6beta and, following the feedback, drop one of two methods in 4.7.

**Comment by philwareham** [comment]
OK, sounds fine to me.

Please merge if you feel it is OK, but please also create an issue, targeting 4.7, to remind everyone that some of these methods can be removed in the future. Just for reference.

**Comment by bloatware** [comment]
OK, the local storage works so far so good for me. To keep traces of modifications, I defer this issue to 4.7, no particular security threat being involved.

**Comment by Bloke** [comment]
@bloatware Can `txp_pane.php` be removed from core (and from `checksums.txt`) and this issue closed now?

**Comment by bloatware** [comment]
@Bloke core-wise it should be ok, but I dunno what will happen if a plugin tries to save its panes. Let's try :-) It also should be safe to remove `_txp_token` from url when it's sent by POST, but this is probably another issue.

**Comment by Bloke** [comment]
Ah true, plugins. I have many of those that save pane state. Best leave it for one more version then, and make sure we advertise that it's going to be removed so authors have time to make the switch.

**Comment by bloatware** [comment]
The switch is fairly easy: just use the "official" txp-pane structure (available e.g. via `wrapRegion()` function):
```
<section class="txp-details" id="txp-some-group">
  <h3 class="txp-summary" id="txp-some-group-label">
    <a role="button" data-txp-pane="article_some" href="#txp-some-group-content">Some options</a>
  </h3>
  <div class="toggle" id="txp-some-group-content" role="group" style="display: none">
    <!-- pane content -->
  </div>
</section>
```
and there'll be no need to send async requests any more.

**Comment by Bloke** [comment]
I think this is done. Notwithstanding the issue about the CSRF token security (which could be made into a separate issue). Do you agree we can close this, @bloatware ?

**Comment by bloatware** [comment]
The only way to know is to remove `txp_pane.php` and see if any plugin complains...

**Comment by Bloke** [comment]
Let's leave `txp_pane.php` for now. Give plugins a chance to catch up.

I'll close this and we should add a note to `HISTORY` that `txp_pane.php` will be disappearing in future and that plugin authors should use `wrapRegion` style code instead to benefit from automatic pane state recall.
