### ISSUE TITLE
Add template tag registry and registering

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#375]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on February 26, 2013 06:44:32_

This was first asked to be included in Neal Poole's security findings. Registering has few benefits:
- Security, the tag language can not execute any and every function.
- Namespace support, callbacks, prevents collisions. The PHP name and tag name do not have to be same.
- Automation; building tag collection classes and magic binds becomes very much possible.

Todo;
- Add basic tag registering. Don't go too crazy with extending and stuff - goal is to make the code usable in some framework too if we decide to use one.
- Allow current function-to-tag mapping as a fallback. Issue unregistered tag notice if deemed necessary.
- Later on introduce classes for automation and update the new 4.6.0 tags to use PSR-0 class loader.

Those that are wondering, yes this will increase memory usage and runtime. But this being about this, I don't even consider it as a factor.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=371_

**Comment by Bloke** [comment]
Mostly, if not completely, done. Automation and class loader to be decided.

**Comment by Bloke** [comment]
The registry itself is done and core tags have been registered. The tags themselves can still be called as functions, since the code has not been fully migrated from `taghandlers.php` yet. Should we close this, @bloatware ? Or push it back a release as a 'todo' item?

**Comment by bloatware** [comment]
I'm fine with how it works and have no idea of @gocom automation plans, neither its benefice. That's all I know :-)

**Comment by Bloke** [comment]
Fine by me. Let's close it and consider what we'll do about making the tags more OO later.
