### ISSUE TITLE
Error handling causing errors

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#377]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on March 15, 2013 13:22:50_

There are few slight issues with the error handler functions:

* All handlers will cause error on their own if they catch an error number that is not in the $error list.
* Due to differences in error types between PHP version, the admin error handler kills script responses without reason.

The biggest problem we have is E_STRICT. Textpattern does invoke those on certain PHP version. For instance extract will invoke E_STRICTS on certain PHP releases due to the function, at one point, only accepting variables due to it 'defaulting' to referencing.

In which case the there will be E_STRICT, error code 2048. Which isn't in the table which in return invokes an E_NOTICE about undefined index.

Outside of that actual programming error, this wouldn't be a big issue because 'live' production status. But. There is adminErrorHandler which ignores production status. On script response pages it does stuff no matter what the status is. An if the page happens to be set as 'text' (like async links) the page is killed and returned as HTTP 500.

Currently on PHP 5.2.17 it will actually even kills almost all async responses. Almost every page generates E_STRICT on that PHP version.

Todo;

* Change the error handlers to work entirely based on the production status. Each status has list of explicit error codes it will show. This prevents the differences in visible errors between different version and prevents errors on error codes that are not supported.
* Make sure that the adminErrorHandler kills script response pages only when it needs to. Especially makes sure it does not do anything when live mode is active, or there is no message to print out.

As a sidenote; error reporting on PHP 5.4 works fine and doesn't cause unexpected issues.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=373_

**Comment by Bloke** [comment]
Looks like this is fixed, as far as is practical for now. Anyone see any reason not to close this?

**Comment by Bloke** [comment]
No takers, so closing for now.
