### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#389]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on July 20, 2013 20:43:21_

New OOP parts should throw Exceptions on error. Exceptions are an important part of any modern framework.

To be considered;
- Localization. Although, not all Exceptions would need localization. Most of the Exceptions are for the developer and the application only. Most code Exceptions (non-tag language basically), don't probably need any translating, especially if the localization itself can generate further errors.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=385_

**Comment by Bloke** [comment]
Partially done. The rest can wait as more parts are converted to OOP in due course.

**Comment by petecooper** [comment]
Background task as we convert to OOP.

Closing for now.
