### ISSUE TITLE
Enhance doLabel()

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#39]
_From [stefdawson](https://code.google.com/u/stefdawson/) on September 04, 2009 11:55:41_

Currently there is no way to prevent doLabel() from displaying a <br /> tag
if you don't want one, or if you want a 'simple' break between label and
item (e.g. a colon or a space). Whatever you specify is surrounded by '<'
and '>' brackets.

I propose doLabel() should behave similarly to doWrap() insofar as if you
specify something that _isn't_ a tag it should put it after the label
without brackets.

At the moment it is also not possible to specify an empty labeltag, because
if it's empty it adds a break tag by default. Whether an empty labeltag is
desirable is open to debate, but for tags and plugins that use
<code>doLabel($label, $labeltag).doWrap($out, $wraptag, $break,
$class)</code> it allows more flexibility in output.

If an empty labeltag is permitted, to preserve backwards compatibility we
would either have to:
1. allow something like a space or a known constant that indicated "no
   break please", or
2. permit labeltag="" to set no labeltag, thus all other tags that
   currently use labeltag=>'' in lAtts() would need modifying to make 'br'
   their default

Would modifying this have any other side effects? Is this something that
would be useful to people who use label/labeltag? Should there be an empty
labeltag option? Should the labeltag be allowed to be a simple character
like colon or space, or is this a gross violation of naming convention?

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=35_

**Comment by philwareham** [comment]
Covered by larger scope of issue #968 - closing this one.
