### ISSUE TITLE
Specify category title and name on creation

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#397]
_From [gaek...@gmail.com](https://code.google.com/u/107692553785564982606/) on August 26, 2013 10:45:25_

When a category is created, only the name is requested; the title is assumed to be the same as the name. This causes problems where there are nested categories with common entries, e.g.:

Colours
- Yellow
- Orange
- Red

Fruits
- Apple
- Banana
- Orange

A workaround for the user is to have a unique name and optionally different title; this satisfies the requirements for uniqueness in the name and gives options for appropriate front-end markup to mimic the lists above.

On category creation, I am asked for the name of the category. If this is a duplicate name (say, Orange), the category will, rightly, not be created. In the 4.5.4 classic theme, sections can be created with name _and_ title provided at the time of creation. If this option was available to categories at creation time, a unique name (say, colours-orange) could be applied, along with a pretty title (you guessed it: Orange) for the front-end.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=393_

**Comment by philwareham** [comment]
Is this still/was it an issue? Debatable really. I vote to close it since the categories work OK.

**Comment by Bloke** [comment]
I don't see a fabulous workflow either way with the screen in the current layout state. Maybe if we make alterations to it when we go towards unlimited cats/tags we can consider this? I'd close it for now.
