### ISSUE TITLE
Optimize getNextPrev() function

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#398]
_From [haut.b...@aliceadsl.fr](https://code.google.com/u/106452029543525188687/) on August 29, 2013 17:20:19_

If "section" field were included in the array output by getNextPrev() function, then link_to_prev/next() functions could use permlinkurl() instead of permlinkurl_id(), sparing a db query.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=394_

**Comment by vanmelick** [comment]
Pull request sent.

**Comment by rwetzlmayr** [comment]
Closed via #512.
