### ISSUE TITLE
Set default timezone if missing to avoid countless date errors

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#403]
_From [gaek...@gmail.com](https://code.google.com/u/107692553785564982606/) on November 13, 2013 13:05:53_

I have installed Textpattern 4.5.5 for the nth time to a MediaTemple DV server which, by default, does not have the PHP timezone set correctly for Textpattern. Forgive my lack of PHP knowledge, but I can resolve this by setting the date.timezone in textpattern/config.php, which I do.

Each time I install, I expect a lot of PHP warning errors relating to the initial SQL setup, specifically this over and over:

Warning: strftime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/vhosts/example.com/httpdocs/textpattern/setup/txpsql.php on line 466

Today, for the first time, I counted the number of errors output on the 'That went well' page: the message above appeared above 1157 times in a row. Is there a feasible way to check, during install, for a suitable timezone setting and then, perhaps, apply it to the copy + paste configuration file page if it needs to be applied, perhaps letting the user select from a drop down or PHP time zone list?

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=399_

**Comment by vanmelick** [comment]
Should this also be marked milestone 4.6, just as the other three timezone issues?

**Comment by philwareham** [comment]
Has this been implemented now?

**Comment by Bloke** [comment]
I don't think so. Someone more well-versed in timezone issues - maybe someone who has servers in various locations around the globe - might be able to suggest a fix.

**Comment by petecooper** [comment]
I'm the ghost OP on this issue.

This is now part of https://github.com/textpattern/textpattern/issues/1128 so can be closed.
