### ISSUE TITLE
Fixing timezones part 2: Selecting timezone identifiers

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#405]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on December 01, 2013 12:06:36_

Next step would be setting the identifier:
- Make sure timezone identifier is always selected.
- If not, default to the server default timezone.
- If server default timezone isn't set, try to pick one.
- Set server default timezone with the timezone pref.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=401_

**Comment by Bloke** [comment]
Defer for now.

**Comment by petecooper** [comment]
This has been merged into https://github.com/textpattern/textpattern/issues/1128 - can be safely closed.
