### ISSUE TITLE
Fixing timezones part 3: date caculations

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#406]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on December 01, 2013 12:08:11_

Todo;
- Drop is_dst and auto_dst options.
- And use the actual timezone data for date calculations.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=402_

**Comment by Bloke** [comment]
Defer for now.

**Comment by petecooper** [comment]
This has been merged into https://github.com/textpattern/textpattern/issues/1128 - can be safely closed.
