### ISSUE TITLE
Fixing timezones part 4: Saving and selecting dates

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#407]
_From [jukka.m.svahn](https://code.google.com/u/jukka.m.svahn/) on December 01, 2013 12:14:09_

Todo:
- Make sure all dates are generated by the PHP application, not MySQL.
- Save dates to database in specific timezone such as UTC.

Problems:
- Conversion. Somehow convert the current dates to UTC (if any).
- URLs: how to keep current URLs intact (if any).

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=403_

**Comment by Bloke** [comment]
Defer for now.

**Comment by petecooper** [comment]
This has been merged into https://github.com/textpattern/textpattern/issues/1128 - can be safely closed.
