### ISSUE TITLE
qmail MTA requires \r linebreaks in (subject) header of mails sent using PHP mail() function

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#42]
_From [r...@vanmelick.com](https://code.google.com/u/108652838195029914806/) on September 08, 2009 23:10:43_

see discussion in http://forum.textpattern.com/viewtopic.php?id=31697 TXP tries to use the right line endings when sending emails, but fails when
using qmail ( http://cr.yp.to/qmail.html ). Apparently qmail wants \r line
endings (instead of \n) in the subject parameter of the PHP mail() function
if you're using linebreaks in subjects, which happens automatically if your
subject line is too long (encode_mailheader limits the length of header
lines according to relevant RFCs).

This is the error you get when for example you're trying to add a new user
in such a situation (qmail MTA + long site name, causing a multi line
subject header):

Warning: mail(): Bad parameters to mail() function, mail not sent. in
/.../textpattern/lib/txplib_misc.php on line 989

Before even considering to think about attempting to fix this, please
reproduce the problem first, because while qmail is known for being really
strict when it comes to proper use of line endings, all documentation I can
find suggests using \n (as TXP already does on *nix systems). Using \r
makes no sense yet solved the problem for the user in the forum topic
mentioned above, unless it's two wrongs making a right.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=38_

**Comment by vanmelick** [comment]
Not reproducible with the latest version of (net)qmail, TXP and PHP. This issue can be closed. I've tested with "\r", "\n" and "\r\n". In all cases mail was sent.
