### ISSUE TITLE
Attribute values of 0 don't render attribute

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#420]
_From [stefdawson](https://code.google.com/u/stefdawson/) on July 01, 2014 12:51:31_

See http://forum.textpattern.com/viewtopic.php?id=41488 Presumably join_atts() is the culprit and:

  $flags & TEXTPATTERN_ATTS_STRIP_EMPTY && !$value

should be more vigorous in its use of 'not a value'. Also affects public tags trying to use attribute values of 0. Will investigate.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=416_

**Comment by Bloke** [comment]
Is the backwards-compatibility issue big enough to warrant sidelining this, or can we just go ahead and fix it and be damned with people who expect their hand-crafted attributes with a zero value to disappear?

**Comment by bloatware** [comment]
The function `join_atts()` being new, my plan would be to set the default `$flag = TEXTPATTERN_STRIP_EMPTY_STRING` and pass the explicit `TEXTPATTERN_STRIP_EMPTY` in core when necessary. This should suffice for bw compatibility and preserve `attr="0"` in newly created tags by default. The main concern is `tag()` function that is used just everywhere. It makes about 100 places to check :/

**Comment by bloatware** [comment]
A [pull request](https://github.com/textpattern/textpattern/pull/649) is ready. Test, anyone?

**Comment by Bloke** [comment]
Will test tonight. Thanks.

**Comment by bloatware** [comment]
So far so good in my tests. Should we close the issue? Speak now or forever hold your peace!

**Comment by bloatware** [comment]
Should be solved by [this](https://github.com/textpattern/textpattern/issues/649), closing.
