### ISSUE TITLE
Add option to expire 1 or more articles

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#421]
_From [p...@pragmatika.net](https://code.google.com/u/104499604015813158952/) on July 02, 2014 14:10:24_

Forum thread: http://forum.textpattern.com/viewtopic.php?id=41503 There's currently no immediate way to expire one or more articles, either from the Write or Articles tab, short of setting the expiry to a current or passed time. There is functionality to update an article timestamp to 'now', and I propose this same workflow is duplicated for article expiry.

I have no metrics to state how useful this would be for the user base, but my feeling is it's a feature that is appropriate for core rather than via a plugin.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=417_

**Comment by philwareham** [comment]
This could be achieved with a 'Set expiry date to now' checkbox in the Date and time panel fairly easily I think. @bloke thoughts?

**Comment by Bloke** [comment]
Sounds reasonable. Will see how feasible this is to slot in,
