### ISSUE TITLE
URL to download a file doesn't work

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#424]
_From [p...@pragmatika.net](https://code.google.com/u/104499604015813158952/) on July 17, 2014 18:27:31_

What steps will reproduce the problem? 1. Install Textpattern from current SVN version at time of writing
2. Upload a file in the admin-side
3. Download the file using the provided link What is the expected output? What do you see instead? I expect the download to start. Instead, I am shown a 404. The URL format is: http://example.com/index.php?s=file_download&amp;id=1 It should be: http://example.com/index.php?s=file_download&id=1 File is confirmed as existing and can be downloaded manually, outside of Textpattern. 4.5.5 uses the latter format and works. Using the latter format with the SVN release also works. What version of the product are you using? On what operating system? 4.6-dev (1306ac2a805ad7eb416aea68276362b5), Ubuntu 14.04LTS. Please provide any additional information below.

I'm still looking for where this happens in source - haven't located it yet.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=420_

**Comment by petecooper** [comment]
Regarding the options laid out in https://github.com/textpattern/textpattern/issues/424#issuecomment-57905031, I see the situation as follows:

* it works in 4.5.7
* it doesn't work in 4.6-dev currently
* something's changed to stop it working

The download URL format is correct, but there's some escaping weirdness with the `&amp;`. Easiest solution would be switch the escaping, so the `&amp;` becomes `&`.

I assume there were good reasons behind the changing of things (whatever they may be) that made this go from working to not working, but I'm not aware of the details.

Any chance this issue could be tagged for the 4.6 milestone?
