### ISSUE TITLE
txp_public_login cookie and multisite installations.

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#426]
_From [patrick....@gmail.com](https://code.google.com/u/111387824658555502103/) on July 28, 2014 13:29:29_

What steps will reproduce the problem? - Fail to read the 'txp_public_login' cookie on the public side in a multisite installation of TXP. What is the expected output? What do you see instead? - Better support of the multisite installation feature on public cookie. What version of the product are you using? On what operating system? - TXP v. 4.5.5 Please provide any additional information below. Is there a security reason why the 'txp_public_login' cookie isn't available through the entire domain even subdomains?

Since the new multisite feature in Textpattern, the creation of this cookie doesn't reflect this great capacity.
I didn't inspect the source of the future TXP version because it may change lot until its official release; but for the latest stable version, these changes could be useful for plugin creators who need check against 'txp_public_login'.

../textpattern/include/txp_auth.php add  '.'.$prefs['siteurl'] into the fifth parameter of setcookie('txp_login_public') function.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=422_

**Comment by philwareham** [comment]
I believe Jakob will soon provide a solution for this issue with his multi-site amends.

**Comment by philwareham** [comment]
See [multi-site update branch](https://github.com/textpattern/textpattern/tree/multi-site-fix) which should fix this. Please close on branch merge.

**Comment by philwareham** [comment]
I'm assuming this can be closed now? CC @jools-r @petecooper @Bloke

**Comment by petecooper** [comment]
I haven't fully tested yet (ran out of weekend) so can't comment accurately, personally.

**Comment by jools-r** [comment]
I just double-checked on the cookie aspect and using a fresh dev build, installed a multi-site, then tried out maintenance mode with [rah_maintenance](https://github.com/gocom/rah_maintenance/releases), [rvm_maintenance](https://vanmelick.com/txp/) and [smd_at_work](https://stefdawson.com/sw/plugins/smd_at_work) and all work with the public cookie. 
rah_maintenance and rvm_maintenance (ideally) require an `error_503` page template, and smd_at_work needs a revised/second [example code](https://stefdawson.com/sw/plugins/smd_at_work) for the front-side links to the admin page for multisite installations – just a matter of adding `http://admin.domain.com/index.php` to the link (which gives me [an idea](https://github.com/textpattern/textpattern/issues/1120)). In fact, the revised prefs panel means I think you can no longer link directly to maintenance panel on the prefs pane, or am I mistaken?

So, I'd say yes, … pending testing from others, of course.

**Comment by Bloke** [comment]
Great stuff. Just need to figure out the [private/public themes thing](https://github.com/textpattern/textpattern/commit/c95016cf2d680348d4dcea57764bd05966ecbd70#commitcomment-25940041) in multi-site. I was hoping @makss would be able to sneak this in prior to beta. It'll be a train wreck if I do it. Unless @bloatware has any ingenious code to offer?

> the revised prefs panel means I think you can no longer link directly to maintenance panel on the prefs pane

It is possible via hashes but depending on the browser you can't just type them into the location bar as it just stares blankly back at you until you force refresh. But from a link, `https://example.com/textpattern/index.php?event=prefs#prefs_group_smd_at_work` should work. Hover over the links in the left box on the prefs panel to see them.

**Comment by jools-r** [comment]
BTW: re: testing.

Testing all edge cases and bad user input, of course, takes a little longer, but doing a multi-site install is now officially no-big-deal™. When there are no hurdles or unusual situations, the only extra steps are:

* point your public domain to the `/sites/myname/public` folder (not an extra step, just a different location)
* set up an admin subdomain
* provide the admin URL and cookie domain during the setup and config routine – both of which are pre-filled with the expected values.

Everything else works just like a usual setup. And if you shift the sites folder, it does it's best to recreate symlinks. Dealing with command line stuff is only ever needed if the pre-installer is unable to create symlinks, and the respective commands are output to make it easier to cut and paste.

**Comment by jools-r** [comment]
> Great stuff. Just need to figure out the private/public themes thing in multi-site. 

In theory, this *could* be added later…

At present I've included a `themes` folder in the respective `sites/myname/public` folder. So the **standard setup is per-site themes**.

You can replace that folder with a symlink to the main `textpattern/themes` folder. The pre-installer is prepped to do this, but I've commented it out for the moment. That gives you centralised themes storage.

You could also do a hybrid variant by keeping the `themes` folder in your `sites/myname/public` folder and making own symlinks to individual named theme folders in the main `textpattern/themes` folder.

With both of the latter, you just need to be aware of the fact that changing a template in one site and exporting it, changes the base files for the other sites too. If you want that, you need to re-import on the other sites. It's not a 'problem' but you need to be aware of it. It gets a bit more complex when you get to the forms the pages refer to, though.

A bona-fide tiered arrangement would make it easier to do a proper parent-child theme(-like) arrangement where a local site's template overrides the main template … but it could, theoretically, come later.

**Comment by jools-r** [comment]
I'm guessing that's the case. I didn't 'do' anything special for themes except to add the themes directory in the public folder (analogue to the images or files folder), and to try out the variant with the symlink, so I don't think there's anything you would break by changing that later (except for some established working methods. All the same, I guess 'a proper method' would be better sooner than later, maybe in a point update.

**Comment by petecooper** [comment]
Basic testing complete here, looks good - haven't been able to break it yet. The themes issue outlined in https://github.com/textpattern/textpattern/issues/426#issuecomment-359396567 could be jettisoned to a separate issue, or left to bubble in the @Bloke ideas factory, perhaps.

+1 for closing the issue as OP resolved. Sterling work, @jools-r!

**Comment by philwareham** [comment]
Cheers all, lovely stuff! Closing.
