### ISSUE TITLE
Popup tag - make consistent (or deprecate)

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#434]
_From [p...@designhive.com](https://code.google.com/u/100991452291349786445/) on September 30, 2014 14:20:01_

As discussed in this thread: http://forum.textpattern.com/viewtopic.php?id=42836 Popup tag attributes are inconsistent with schema used in system for other tags.

But... maybe look at removing this tag or repurposing, since it has an obsolete function.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=430_

**Comment by petecooper** [comment]
+1 for deprecating.

**Comment by Bloke** [comment]
Undecided on this tag. It serves a purpose, it's just badly named and makes some dubious UX decisions, such as auto-submit. Would have to determine its usage in the wild to know if it's worth ultimately removing.
