### ISSUE TITLE
Avoid creating invalid custom_field names

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#456]
See:
http://forum.textpattern.com/viewtopic.php?id=43726
http://www.textpattern.net/wiki/index.php?title=Advanced_Preferences#Custom_Fields

Instead of having a list of "do not use" names for the custom_fields in the Wiki, it would be more userfriendly if TXP rejected those names when a user tries to create a custom_field with such a name. Not doing so results in problems that the average user cannot diagnose himself.

The way custom_field names are handled right now when parsing attribute values is really just an ugly hack. An alternative, which would break some of the current installs, is to no longer support the use of user-supplied custom_field names as attribute names.

**Comment by bloatware** [comment]
I would

- allow for `custom_n` attributes as alternative to `cfname`. These are unambiguous (unlike dumbed-down names) and users are already using them in `sort`.
- still allow for `cfname` attributes, but ignore them as cf values when they clash with tag's attributes like `sort` etc.
- internally store, say, `custom_11` as `$thisarticle[11]`. This avoid eventual variables pollution on `extract($thisarticle)`, which we should avoid but still have in few places.

I'm currently testing the first two points and it looks doable.

**Comment by bloatware** [comment]
Not sure we can do more in pre-CF branch. As long as it is not intended to be used as article filter, `sort` is a valid cf name. Close after warning strings addition/translation?

**Comment by Bloke** [comment]
I'll give this a whirl. Looks good from a cursory glance at the code. Nice work! I'll sort the strings out.

**Comment by Bloke** [comment]
Firefox doesn't give the most useful default experience if you try and make a custom field with a reserved word. "Please match the requested format" is a bit obtuse, haha. But there's not much we can do about it when using the `pattern` attribute.

![CF-FormatMatch](https://github.com/textpattern/textpattern/assets/21252/54cb7c10-3c55-4fca-b79b-a8c75ce0e206)

Better than letting it through and then it causing issues later.

**Comment by Bloke** [comment]
How do we feel about the string `Reserved word in custom field name(s): <strong>{list}</strong>`?

Can anyone come up with anything better? Bearing in mind this string can appear in the announcement box when saving Prefs, and the pre-flight check on Diagnostics, so it needs to supply context.

**Comment by bloatware** [comment]
> Firefox doesn't give the most useful default experience if you try and make a custom field with a reserved word. "Please match the requested format" is a bit obtuse, haha. But there's not much we can do about it when using the `pattern` attribute.

A bit of JS could probably fix it.
