### ISSUE TITLE
[UX] Add button to installer to see front-side of site

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#458]
http://forum.textpattern.com/viewtopic.php?pid=287684#p287684

Requesting an additional button on the final install page/screen with a link to the front-side. Same size (broadly), same shape, same colour. Could use existing language string `viewsite` rather than creating an additional one.

**Comment by Bloke** [comment]
Hmmmph, slight snag. At the point the setup completes, the database is in the "1.0" state, i.e. prior to any upgrade scripts being run. That means if you try and view the front-of-house site, it throws a bunch of errors. Only after you've logged in once and the upgrade scripts have all run is the site in a fit state to be viewed. Shame.

**Comment by petecooper** [comment]
Oh, yeah - actually that makes sense.

Never mind - thanks for trying, Stef.
