### ISSUE TITLE
Logs tab not visible or permitted

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#459]
I'm using the current/latest commit as of the time stamp of this issue -- https://github.com/textpattern/textpattern/commit/24fc394579d989d4a08f80cad15e7c02a22568c5 -- and it's a fresh install.

The logs tab is not visible. If I visit `textpattern/index.php?event=log` I am shown the `Restricted area` message, despite being a Publisher. Single-user instance, no actions performed after installation.

Full diagnostics: https://gist.github.com/petecooper/ebbf9a5294e346a181ce

**Comment by petecooper** [comment]
Closing. Logs tab is disabled if logs are disabled. Ugh. Lost 30 minutes to this.

**Comment by Bloke** [comment]
In theory, the Visitor Logs menu item is supposed to disappear so you can't even select the tab. Is that not happening? If so, that's a bug.

From memory, it doesn't disappear right away after saving the prefs. But that's a by-product of the prefs being read first, before being saved, so they're stale on first display after saving prefs. After that, the menu item is gone (though my dev copy is a little out-of-date so maybe something broke recently?)

Is there a better way you can think of to handle this situation? At minimum, the help text should probably state that the visitor logs panel disappears when logging is disabled!

**Comment by petecooper** [comment]
On a fresh 4.6-dev install, logging is disabled and therefore the tab isn't visible. Manually hitting the URL throws the generic error about it being off limits, and that's where it stopped. It will no doubt be straightforward to understand for newcomers, but it threw me because I was expecting to see. Objectively, the UX logic is as expected, but it's not particularly graceful about it. My suggestion throw a "To view logs, enable logging in Admin &rarr; Preferences", or thereabouts. New language string, I'm afraid.

**Comment by Bloke** [comment]
Yeah, unfortunately the way the panel throws the restricted area message is a little ungainly of itself.

Without making too many waves and adding defensive code that is unlikely to be seen by 99.995% of the population, the simplest solution is something like this one-liner + a suitable lang string as you mentioned:

    diff --git a/textpattern/include/txp_log.php b/textpattern/include/txp_log.php
    index 02f7395..b35866f 100644
    --- a/textpattern/include/txp_log.php
    +++ b/textpattern/include/txp_log.php
    @@ -34,6 +34,7 @@ if (!defined('txpinterface')) {
 
     if ($event == 'log') {
         if (get_pref('logging') === 'none' || !intval(get_pref('expire_logs_after'))) {
    +        echo '<p class="restricted-area">' . gTxt('enable_logging_to_view') . '</p>';
             require_privs();
         }

The class can be changed of course, but either way it's not exactly pretty output. Improvements?

**Comment by petecooper** [comment]
Leave as is; it's an education issue, I think. It was an abrupt stop because I have a habit, and it seems counter-intuitive to re-engineer solely for that reason. No big deal, really.
