### ISSUE TITLE
Bug in join_qs function

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#464]
On the first page of an article listing when accessed directly it'd just be URL:

    http://www.example.com/blog/

Then the next paginated page via `<txp:older />` is, as expected URL:

    http://www.example.com/blog/?pg=2

Now if you click the prev page via `<txp:newer />` you get a URL:

    http://www.example.com/blog/?pg=0

I'd expect that to be `/blog/?pg=1` or simply `/blog/`. Speaking to Oleg in the Textpattern forums he has confirmed this is a recent bug.

**Comment by petecooper** [comment]
@philwareham - your OP is missing the `<txp:older />` and `<txp:newer />` tags.

**Comment by philwareham** [comment]
For reference, the forum post that started this (and which may help solve it):
http://forum.textpattern.com/viewtopic.php?pid=288746#p288746
