### ISSUE TITLE
Add html_id for section and category lists

### ISSUE THREAD

**Issue by colak** [textpattern/textpattern#472]
Following the idea on http://forum.textpattern.com/viewtopic.php?id=45327, it wold be good if section and category lists had an html_id attribute so instead of 

`<ul id="menu"><txp:category_list break="li" wraptag="" /></ul>`

and

`<ul id="menu"><txp:section_list break="li" wraptag="" /></ul>`

we could have

`<txp:category_list break="li" wraptag="ul" html_id="menu" />`

and

`<txp:section_list break="li" wraptag="ul" html_id="menu" />`

**Comment by philwareham** [comment]
It might be wise to check all other tags and see if this attribute is missing/of benefit on any of those too. Might be OK already, but worth a look.

**Comment by Bloke** [comment]
Crossed my mind, but we should probably [hold off bloating the tag suite with attributes](http://forum.textpattern.com/viewtopic.php?pid=289980#p289980) for the time being in case a better solution arises.
