### ISSUE TITLE
README on GitHub

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#475]
The README really needs to be tailored for GitHub (and formatted), since it is the introduction to the project here. So maybe a separate INSTALL.txt with the current installation instructions would suffice?

**Comment by petecooper** [comment]
I was thinking exactly the same about two hours ago. Spooky.
The `README.txt` is part of the release build process (as I understand it), and could stay as-is; the `README.textile` should be created and excluded from the release build process.

**Comment by petecooper** [comment]
PS: I can take dibs on this later today, I have some time.

**Comment by philwareham** [comment]
OK, please do a first draft. I can always add to that. Cheers.

Also, agreed on leaving the .txt file in place.

**Comment by petecooper** [comment]
This, to me, still looks like a Textual Wall of Doom. It should be stripped back to point to external how-to guides re: install and update? The list presentation is unwieldy.

**Comment by petecooper** [comment]
OK, I tried it with less wordage - looks better.

https://github.com/petecooper/textpattern/commit/fbea7697414022b1da97dacd86251519e3eb2312

**Comment by philwareham** [comment]
OK, closing this issue as it has been resolved now. Feel free to amend the README if necessary.
