### ISSUE TITLE
Make txp:recent-articles more intelligent (context-aware) or deprecate it.

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#487]
Discussion thread: http://forum.textpattern.com/viewtopic.php?id=45808

Quoting Stef (Bloke):

EDIT: Just looked at the code for it. No attributes there that are anything special, as you say. It’s just a poor-man’s txp:article_custom. And like article_custom, you can’t paginate it (not that you’d probably need to). Perhaps that’s the real reason for keeping the tag around, since having two txp:article tags on the page would potentially break pagination. From that angle it’s kind of useful. Sort of.

EDIT 2: So the question comes down to whether having a non-paging, context-aware tag for displaying articles is useful. Like a halfway tag between the fully context-aware and fully pageable <txp:article />, and the wholly not pageable (without a plugin) and completely uncontext-aware txp:article_custom.

End Quote.

**Comment by philwareham** [comment]
Not exactly an issue, just a fairly limited tag. Closing.
