### ISSUE TITLE
Language file names may have a '.textpack' extension

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#496]
The **Admin > Languages** screen finds eligible files to install strings from by looking for files matching ``*.txt`` while on the other hand our [Textpacks](https://github.com/textpattern/textpacks) repository keeps all string in files with a ``.textpack`` extension. We should accepts these files without having to rename them first.

**Comment by makss** [comment]
Please check your patch.
```
$name = preg_replace('/(.txt)|(.textpack)/i', '', $file);
```
I think the more correct
```
$name = preg_replace('/(\.txt|\.textpack)$/i', '', $file);
```

**Comment by makss** [comment]
Update:
```
$name = preg_replace('/\.(txt|textpack)$/i', '', $file);
```

**Comment by philwareham** [comment]
Reopening issue until verified by @rwetzlmayr

**Comment by rwetzlmayr** [comment]
Good catch.
