### ISSUE TITLE
Use utf8mb4_unicode_ci on MySQL 5.5.3+

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#519]
utf8_unicode_ci (and utf8mb4_unicode_ci) is more accurate when sorting compared to utf8_general_ci (and utf8mb4_general_ci), but is around 10% slower.
utf8mb4_unicode_ci allows the full utf8 character set (with a small speed penalty), while utf8_unicode_ci only allows characters that take up to 3 bytes,

* http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
* https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html
* https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-upgrading.html
* https://www.drupal.org/node/2473301
* https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/

Should we use utf8mb4_unicode_ci collation for *new*  TXP installs on MySQL 5.5.3+... or even require MySQL 5.5.3+ as the minimum version for TXP 4.6?

**Comment by vanmelick** [comment]
I have a patch for this. 
One thing I did encounter is that changing from utf8 to utf8mb4 requires us to reduce the size of some columns. If there's a KEY (whether it be primary, unique or just a regular key) set on a table, the combined size of such a key may not exceed 1000 bytes. This means that if you use a varchar column as a key, that column can be at most 250 characters, because each character can take up to 4 bytes.

I'd recommend reducing varchar(255) columns to varchar(250). And even then there's one case where even that isn't enough... in the txp_prefs table, we have a key that consists of the username, the pref name and the pref id, which are respectively 255 chars, 64 chars and 4 bytes (int) long. Combined that's 1280 bytes. Can be fixed by reducing the pref name to 200 chars, the username to 40 chars.

**Comment by vanmelick** [comment]
Ideally the above only applies to new installs, but because we'd also have to change some of the update scripts, it could also hurt people that are not yet 100% up-to-date, causing a few older upgrade scripts to trigger (scripts that would have to be modified to reduce column sizes).

**Comment by makss** [comment]
If you do add utf8mb4 for a new installation, it is only optional.

Personally, for myself, I do not see any sense to go to this encoding. While I see only the negative side:
* Slowly
* Takes up more space
* Not all versions libmysqlclient support it
* While reverse migration may be difficult with the encoding. What will happen if restore MySQL 5.5.3+ backup with utf8mb4 to old version  MySQL?

**Comment by vanmelick** [comment]
* True, it is a bit slower.
* As I understand it, it only takes up more space if you actually use 4-byte UTF-8 chars, not if you stick to the limited 1-3 byte UTF-8 chars you're currently using.
* libmysqlclient 5.5.3 and higher should support it. We can check for that. I'd have to check if older versions support it as well, as long as the mysql server version is high enough.
* Shouldn't be a problem as long as you don't actually use a 4-byte UTF-8 char.

**Comment by makss** [comment]
Why do you want to force to impose `utf8mb4` even if it is not needed? You do not give the user the right to choose.

My assumption was right: sql dump with `utf8mb4` can not be restored on older versions of mysql. (It gives this error `#1115 - Unknown character set: 'utf8mb4' `.)
It can be very unpleasant when disaster recovery backup after a server/hosting crash or simply migrate to another hosting.

I often work with backups, so pay attention to this point.

**Comment by vanmelick** [comment]
* MySQL 5.1 is EOL and has been since the end of 2013.
* Users can still choose. When creating config.php, simply modify the charset. The same applies to the difference between latin1 and utf8 charsets.
* This doesn't affect current installs. They stay at utf-8 / latin, although you should upgrade, because...
* Technically, this is a bugfix, because data is truncated upon insert when a 4-byte UTF8 char is encountered while the table/column has charset utf8. This is also a potential security risk.

**Comment by drmonkeyninja** [comment]
:+1:

**Comment by rwetzlmayr** [comment]
Fixed. See #539.

**Comment by bloatware** [comment]
I was not able to setup `themes` branch with `utf8mb4` ("line too long" error). Worked with `utf8` though. Few plugins failed too when trying to create a 255 VARCHAR field.

**Comment by Bloke** [comment]
@bloatware Yeah, we need to find out where this error is coming from and fix it. I have a suspicion it's because the max key length is 1000, yet 255 * 4 is slightly more than that. Maybe if we reduce all our `varchar(255)` down to `varchar(250)` things would work better? At the expense of possibly losing a little data. What do you think?

**Comment by bloatware** [comment]
That was 65535 (2^16 - 1) on setup, sorry, so switching to 250 would not help here, but yes, we should do it for new installs. But what to do with old plugins, where 255 is quite common? Maybe, suggest a choice between `utf8` and `utf8mb4` on setup, with a warning re plugins?

**Comment by vanmelick** [comment]
On 23/09/17 10:40, Stef Dawson wrote:
>
> @bloatware <https://github.com/bloatware> Yeah, we need to find out 
> where this error is coming from and fix it. I have a suspicion it's 
> because the max key length is 1000, yet 255 * 4 is slightly more than 
> that. Maybe if we reduce all our |varchar(255)| down to |varchar(250)| 
> things would work better? At the expense of possibly losing a little 
> data. What do you think?
>

varchar(255) shouldn't be a problem as long as you keep the index key 
length at 1000 bytes or less by explicitly setting the key length when 
creating the index.

PS. In response to the arguments against utf8mb4:
* all currently supported MySQL versions (meaning those that receive 
security updates) support utf8mb4. If you're on an older version, you 
haven't had security updates for almost 4 years (or more).
* utf8mb4 doesn't take up more space. The 4th byte is only used or 
characters that the crippled mysql 3-byte utf8 charset didn't support.

Regards,
--Ruud

**Comment by bloatware** [comment]
> varchar(255) shouldn't be a problem as long as you keep the index key length at 1000 bytes or less by explicitly setting the key length when creating the index.

@vanmelick thanks for the clarification, this should be done in core. But old plugins are still a problem.

**Comment by vanmelick** [comment]
On 23/09/17 11:16, etc wrote:
>
> That was 65535 (2^16 - 1) on setup, sorry, so switching to 250 would 
> not help here, but yes, we should do it for new installs. But what to 
> do with old plugins, where 255 is quite common? Maybe, suggest a 
> choice between |utf8| and |utf8mb4| on setup, with a warning re plugins?
>

Old plugins => update them. Most of them needed an update anyway for 
registering tags.

--Ruud

**Comment by bloatware** [comment]
> Most of them needed an update anyway for registering tags.

That was only a warning.

**Comment by vanmelick** [comment]
On 23/09/17 11:24, etc wrote:
>
>     Most of them needed an update anyway for registering tags.
>
> That was only a warning.
>

With the intention to require it in later versions. Otherwise, why 
bother registering at all.
The situation with utf8 vs utf8mb4 really only affects new installs, not 
upgrades. For new installs it makes sense to have up-to-date plugins.
Besides we already have plenty users that installed the 4.6.x version, 
so plugin authors really do need to update their plugins to make it work 
there.

One could also argue that we should switch back to latin1: works on much 
older MySQL versions. Takes up less space for characters with bit 8 set. 
Faster too ;)

--Ruud

**Comment by bloatware** [comment]
> One could also argue that we should switch back to latin1: works on much older MySQL versions. Takes up less space for characters with bit 8 set. Faster too ;)

Good idea! :) No, I'm arguing for giving a choice, be it just a comment in `config.php`.

BTW, couldn't we write `config.php` directly (if the directory is writable), to avoid copy-paste step?

**Comment by Bloke** [comment]
Yes, thanks for the clarification, @vanmelick. Let's explicitly ensure to set the index sizes then. The only thing is... to what size? I've had a go at hard-coding them in plugins and they worked on my server, but others have reported they got the 'index too large' warning. So, presumably, it's down to some environmental / config settings? Any rules of thumb to employ here?

> couldn't we write config.php directly (if the directory is writable), to avoid copy-paste step?

It's been discussed before. Yes, possible. But I wouldn't want to do it fully automatically because some people customize `config.php` at that stage. However, if we determined that the directory was writable, we could offer a slightly different description text and an optional button alongside "I did it" that tried to create the contents of the textarea on the user's behalf.

If it fails, no problem, the next step would "fail" (as the file wouldn't exist) and the user would then be diverted back to the "I did it" step so they could install it manually. A suitable message that the auto-create failed would be sufficient information.

Wanna give it a go?

**Comment by bloatware** [comment]
Ok, I'll try. Should we add a choice between `utf8|utf8mb4` (and `latin1` :-) at this stage?

**Comment by Bloke** [comment]
A choice of character sets? Sure, don't see why not.

Another thing that's bugging me about all this (trying not to get too off-topic) is the collations, and specifically the issues when people suddenly get [illegal mix of colations](https://forum.textpattern.io/viewtopic.php?pid=307087#p307087), which has happened a few times on upgrade.

It mostly happens in the plugins table, but sometimes occurs in others. Is it a plugin issue? i.e plugins that specify collations and shouldn't? Or ones that should specify one and don't? Or those that specify the wrong one? Or is it something we do wrong in core when setting up tables?

Anyone any idea what we should do to minimise this issue? Even if it's publishing guidelines to plugin authors on the docs site.

**Comment by vanmelick** [comment]
On 23/09/17 12:18, Stef Dawson wrote:
>
> Yes, thanks for the clarification, @vanmelick 
> <https://github.com/vanmelick>. Let's explicitly ensure to set the 
> index sizes then. The only thing is... to what size? I've had a go at 
> hard-coding them in plugins and they worked on my server, but others 
> have reported they got the 'index too large' warning. So, presumably, 
> it's down to some environmental / config settings? Any rules of thumb 
> to employ here?
>

Unlikely, but they aren't by any chance using InnoDB tables instead of 
MyISAM? Those have a 767 byte limit for indexes (191 characters utf8mb4) 
depending on configuration. For MyISAM I haven't seen any documentation 
that says something about configurability or anything other than the 
1000 byte limit. It would be interesting to get a dump of such a 
database (structure, not data).

--Ruud

**Comment by bloatware** [comment]
> BTW, couldn't we write config.php directly (if the directory is writable), to avoid copy-paste step?

On second thought, I think this step is a security feature. So no go, unless we furnish a random secret key with every copy of txp.

**Comment by Bloke** [comment]
Fair enough. I suppose if people leave the `setup` folder around, it prevents actual corruption of existing config data.
