### ISSUE TITLE
file_download_list shows files with a future creation date

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#531]
When editing a file, you can set a timestamp, where it says "or publish at", which has a popup help that reads:

> The time an article or file is published or revised. It can either be (re)set to the moment the item is saved, or to any other time. [...]
Content with timestamps greater than the current time (i.e., in the future) will not appear on the site

But this doesn't work. Regardless of what you set as the timestamp, the file shows up on the site when you use file_download_list. Is this a bug (the 'created' column is not used in the where part of the select query) or is the popup help text incorrect?

**Comment by rwetzlmayr** [comment]
I think this feature was never actually implemented. IIRC, Alex (zem) began the UI work and then left to work for the other organisation.

**Comment by bloatware** [comment]
Looks fixed by some commits referenced above. Closing.
