### ISSUE TITLE
Setup:  Uncaught Error: Call to undefined function trace_add()

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#536]
When visiting the textpattern/setup page, I got this error:

```
Fatal error:  Uncaught Error: Call to undefined function trace_add() in /var/www/html/textpattern/textpattern/vendors/Textpattern/Loader.php:78
Stack trace:
#0 /var/www/html/textpattern/textpattern/setup/index.php(36): Textpattern_Loader->register()
#1 {main}
  thrown in /var/www/html/textpattern/textpattern/vendors/Textpattern/Loader.php on line 78
```

Appears to be caused by txplib_misc.php being loaded after the Loader.php file.
Should we move the include_once lines that load the various /lib files higher up in setup/index.php?

I got this using PHP7, but it also seems to occur in PHP5, though not in every setup (only on Ubuntu, not on Debian).

**Comment by makss** [comment]
This has been fixed https://github.com/textpattern/textpattern/commit/b722589aa7d4026ee792098e01fdc224373491ab

**Comment by vanmelick** [comment]
My mistake (forked master branch not up to date).
