### ISSUE TITLE
Admin/Preferences, Admin section, "Default admin tab" control

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern#538]
The label should read: "Default administration panel"

"Panel" being the key focus there, but for perspective on the other part and style guide rules (soon):

1. "admin" is short for administrator
2. "admin-side" is the exception (an old hat), but only when used as an adjective (e.g., "admin-side  panels", "admin-side callbacks", etc.)
3. Otherwise, in noun form, it should be written out (e.g., "Log in to site administration.")

This only applies in the UI, user docs, main website copy, etc. Community forum banter is exempt, of course. ;)

I haven't scoured the UI for other instances of "tab" or "admin", but the same rules would apply anywhere else they were used.

**Comment by philwareham** [comment]
Partially fixed as per Destry's recommendation. Will go through the GB and US languages in due course and swap out any references to 'tabs' with 'panel'.

**Comment by philwareham** [comment]
Fixed in GB and US languages. Other languages will have to be dealt with by translators (if indeed they use a localised phrase for tabs instead of panels). Closing.
