### ISSUE TITLE
Improvement to 'Permalink title-like-this' pref

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#553]
The pref is currently a bit clunky. Proposing that a better layout for this would be:

    Label: Permalink title pattern
    Select list containing 2 options:
        Hyphenated (title-like-this)
        Intercapped (TitleLikeThis)

This also gives the option of having more patterns in future if desired.

Based on this forum post (but not radio buttons as suggested) http://forum.textpattern.com/viewtopic.php?pid=295299#p295299

**Comment by Bloke** [comment]
So if not radio buttons, what widget? Dropdown list?

**Comment by philwareham** [comment]
Yes please, a `select` dropdown list.

**Comment by Bloke** [comment]
Over to the docs team for stringification.

**Comment by philwareham** [comment]
Issue resolved. Will close when admin-layout-update branch merges into master.
