### ISSUE TITLE
Remove broken Import functionality

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#557]
The import function doesn't actually work any more for WordPress, and the other CMSes we support importing from are effectively dead.

As discussed at our recent meetup, we should ~~deprecate~~ delete this in v4.6 and hide it from admin panels. Another thing that we don't need to support in future (not that is has been supported from some time).

~~Potentially remove all import code in a future release? Not sure how we handle deprecated code in this project - only at major release numbers (i.e. 5.0 - bearing in mind e've never had a major release number since initial release) or can it be done at point releases (i.e. 4.7).~~

If anyone feels an import/export feature would be beneficial in future then that can be written from scratch.

**Comment by vanmelick** [comment]
If it doesn't work, removing it completely won't affect anyone. And those that need it to convert from an ancient obscure CMS can download an older TXP version to do the import and then upgrade.

I'd skip the deprecating phase. This is something you'd only use directly after installing.

+1 on removing it completely in 4.6.

**Comment by Bloke** [comment]
I'd also be tempted to just bin it. It doesn't work and most of the supported systems don't even exist any more.

**Comment by philwareham** [comment]
Great! The less code the better in my opinion. Let's get rid. @vanmelick, would you be willing to do that for us? (I've already assigned plenty of tasks to Stef!)

**Comment by vanmelick** [comment]
Sure. I'll prepare a patch.

**Comment by philwareham** [comment]
Fone
