### ISSUE TITLE
Add a meta title

### ISSUE THREAD

**Issue by ClaireBrione** [textpattern/textpattern#561]
On the model of the new *description* fields, I'd suggest to add a field to hold an alternate (and optional) title for articles because sometimes you need to have different `<title>...</title>` and (let's say) `<h1>...</h1>`. This could be extended to categories and sections.

**Comment by Bloke** [comment]
In my experience (and this may be just me being old skool), the meta title has always been constructed manually via some combination of the article title, site name, category being viewed, and so forth, separated by some character(s). e.g. on category landing page:

Category name | Site name

On an individual article:

Article title | Site name

And so on. This is often made up by using the `<txp:page_url />` tag and various other tags. So I'm not sure how useful a dedicated title would be. I thought search engines liked it when the meta title matched the article title? Or maybe I'm out of touch with how things work these days...

**Comment by rwetzlmayr** [comment]
What Bloke says. Also: Why not use a custom field if you cannot build the title from regular tags?

**Comment by philwareham** [comment]
The meta description functionality was only added because of the convulted steps users had to use in the past to create it. I don't feel meta title suffers the same way, since it's easy to use existing tags for that task, as mentioned above. Closing issue, but thanks for the suggestion Claire.
