### ISSUE TITLE
SQL coding style and updates

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#567]
Proposals:

1. Write all reserved SQL keywords as uppercase (consistency).
2. Remove backticks around table/column names where not needed (consistency)
3. When inserting forms/pages/articles/css (in txpsql.php), use heredocs instead of unreadable long lines.
4. On new installs, don't trigger the various update scripts, but let txpsql.php handle it completely. Why?:
 * If the goal was to let txpsql.php be the same as in the most ancient TXP version, then that isn't true anyway at the moment. Some newer stuff is in there as well and has been for quite some time.
 * If you currently want to know what the up-to-date DB structure is, you either have to put together all the pieces from txpsql.php and the various update scripts or you have to query the database itself (and assume you didn't change anything yourself). Having the end result in txpsql.php would be self-documenting; it's immediately clear what the table structure should be.
 * No more creating tables that are removed in later update scripts or changes that were reverted in later updates.

(and yes, I'm volunteering to do this).

**Comment by Bloke** [comment]
Yes please!

The update scripts are a royal pain anyway and could do with some try... catch loveliness at some point so they can abort if something doesn't go to plan. That way, upgrades can continue where they left of after the sticking point has been corrected without the database or file system  being in an unknown state.

At the moment, the update scripts blunder through to the end. Unless something truly catastrophic happens, the version number is set to the latest version at the end. Once the version number is set, upgrades cannot be re-run without manually altering the version string in the database, touching a file and logging back in.

For reference: [Jukka's legendary post on the subject](http://forum.textpattern.com/viewtopic.php?pid=272537#p272537).

**Comment by vanmelick** [comment]
5. replace the use of PFX with safe_pfx() calls
6. replace ```key=value, key2=value2``` with ```key = value, key2 = value2``` (consistency)

Is proposal 6 okay as well... or should we remove those spaces everywhere?

**Comment by Bloke** [comment]
I don't mind either way, but personally I find spaces more readable. By all means go for it.

**Comment by vanmelick** [comment]
Okay, first batch of changes sent in pull request.

Next on my TODO list is:
* update the SQL queries in other parts of TXP, which should be just cosmetic changes (uppercase + spacing). A lot of work so that depends on whether the style people like the style in this request.
* removing update files that don't contain content.
* removing update files for versions older than 4.0.3... why? Because those versions are more than 10 years old and we can't really test the update scripts anymore because the older versions are either no longer available (4.0.2 and older) or no longer function when installed (the 1.0rc versions).
* check if RealName is filled out in the setup/index.php file. Surprisingly, only name, pass, email are checked but not realname, which instead relies on the browser enforcing that the field is required.
* investigate whether there's an easy way to avoid bumping the version during upgrades if the queries partially fail.

**Comment by Bloke** [comment]
This is fabulous work, and your next batch of proposals sound perfectly reasonable. Especially the `prefs_id` column. I was only looking at it today thinking "what the heck is this column for?"

**Comment by philwareham** [comment]
Please note that some of the changes committed so far have caused bug, [see my comment here](https://github.com/textpattern/textpattern/pull/570)

**Comment by vanmelick** [comment]
I'll fix that.

**Comment by philwareham** [comment]
Can this issue be closed now, or are there still substantial code style changes to come (any minor style changes don't really need an issue still open)?

**Comment by vanmelick** [comment]
Coding style issues are resolved. Closing.
