### ISSUE TITLE
Drop support for upgrading from ancient versions

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#574]
Currently, TXP aims to update from versions even older than the first stable release. I tried installing such an old release and it failed to create tables in the database. That means it is impossible to test if upgrades from those releases still work.

Previously we were forced to keep files like update/_to_1.0.0.php around, because they were used even during new installs. After the recent changes to the update scripts, that is no longer true.

What should be the oldest release we support for upgrading?
- 4.0.0, the first official release (assuming it still installs)?
- 4.0.3, because there's no dev around anymore from the time before that.
- 4.x?, because it is no more than x years old?
- 4.x?, because it is more than x major releases old?

And what do we do when someone still tries to update from such a version... die with an error message?

At the same time, we need to ensure that we have access to all the versions that we claim to support as far as updating is concerned, so it remains possible to test whether the update scripts actually work. There are currently several places to find old versions, but none that has them all (once 4.6 is released):
- https://github.com/textpattern-community/textpattern-releases/
- https://code.google.com/archive/p/textpattern/source/default/source
- https://code.google.com/p/textpattern/source/browse/#svn%2Freleases (until jan 2016)
- via the downloads of textpattern.com (if you know the download ID's and even then it's not a complete collection)
- https://github.com/textpattern/textpattern/releases (releases after 4.5.2 are missing here!)

Opinions?

**Comment by petecooper** [comment]
Which releases is https://github.com/textpattern-community/textpattern-releases/ missing, Ruud? I thought it was complete.

**Comment by vanmelick** [comment]
4.0, 4.0.1 and 4.0.2
You can find them here: https://github.com/textpattern/textpattern/releases?after=4.0.4

**Comment by petecooper** [comment]
Much obliged, sir. I will fix that now - and my apologies for the hijack.

**Comment by philwareham** [comment]
Done, thanks everyone!
