### ISSUE TITLE
Drop the prefs_id column in txp_prefs

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#575]
That column isn't used for anything. All prefs have a prefs_id with value 1.
Depends on #573

**Comment by Bloke** [comment]
Axing it gets my vote. Never seen the point of it.

**Comment by Bloke** [comment]
@vanmelick Do you have a patch for this lurking anywhere that you could apply?

**Comment by philwareham** [comment]
This has been done, yes? I don't see that column in my 4.7 installs. We can close then?

**Comment by makss** [comment]
Yes, can close it.

**Comment by philwareham** [comment]
Great, closing, thanks.
