### ISSUE TITLE
[Write panel] Consider changing the (target) id of the “Article Image” twisty pane to something less generic.

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#578]
The current `ID` is “image”, which is very generic, and result in conflicts with an extension.
 
For background, see [this forum post](http://forum.textpattern.com/viewtopic.php?pid=296348#p296348), where I debug a conflict in `ID`s that prevent the “Article Image” twisty pane to function correctly on the Admin Layout branch.

(by extension, it is probably a good idea, while going through the various panels for further layout work, to make sure the `ID`s in use are Textpattern-core specific. The `txp-` prefix as a (pseudo) namespace remains a useful idea)

**Comment by philwareham** [comment]
@Bloke - are there implications if I change the `id` attributes used on group twists and also on the child `div`, for example:

    <section class="txp-details" id="image_group" aria-labelledby="image_group-label">
        <h3 class="txp-summary expanded" id="image_group-label">
            <a role="button" data-txp-pane="article_image" href="#image">Article image</a>
        </h3>
        <div class="toggle" id="image" role="group">
            ...content...
        </div>
    </section>

If we changed the `section` `id` to `txp-image-group` and the child `div` to `txp-image-group-content` or something similar? Not sure how the system stores what panels a user has expanded/closed (maybe it uses `data-txp-pane` for that purpose and doesn't refer to `id`s at all?

**Comment by Bloke** [comment]
It does indeed use `data-txp-pane` to store panel states so the IDs should be fine to change. Just watch out for any odd jQuery snippets that might hook into them.

**Comment by philwareham** [comment]
Done.
