### ISSUE TITLE
Admin-layout-update: long delay after updating language

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#582]
After clicking a language name to update, I get a long delay -- a second or more -- once it completes. During this time I see the full admin panel (as if the 'Show details' checkbox was checked), then the page "wakes up" and jumps back to just showing the main two columns. Bit disconcerting.

On my test site I do have a bajillion plugins running so there's every possibility that it could be one or more of those interfering, but I don't think there are (m)any that target the new Languages panel. At least not specifically.

Before I invest energy in tracking down if there's a problem here, can anyone else corroborate this finding on a more vanilla installation?

**Comment by philwareham** [comment]
Worked ok on my local install earlier today - no noticeable delay.

**Comment by Bloke** [comment]
OK, this is on a server hosted in Scotland. But as I say it may well be plugins. I'll install wet_plugout, turn 'em all off and see what happens.

**Comment by Bloke** [comment]
Still doing it with all plugins off. Weird.

After clicking Update on any installed language, it goes away and does it, then shows the entire page -- all four columns -- for about two seconds, then drops back to two columns. Here's the inspector trace:

![languagespanel-inspector](https://cloud.githubusercontent.com/assets/21252/10896614/054ac786-81b3-11e5-8bea-116946a11da8.png)

Why so long loading the page and blocking Javascript from showing only the two columns that are indicated by the state of my Show Details checkbox? Maybe it's something local to my box or a misconfiguration somewhere along the line, but it'd be interesting to find out if anyone else has something like this.

**Comment by phiw13** [comment]
I don’t see any such problems here (Safari 9, with Hive and Sandspace themes). There is a slight delay while the language file is being fetched (where are those hosted? Europe data center?), but zero layout issues.

Localhost, with the truckload of processes that an average OS X machine always runs that don’t improve on local server perf.

**Comment by Bloke** [comment]
Thanks for the report. Must be local to my setup then. Bizarre.

**Comment by philwareham** [comment]
Closing for now. Beta testing will ascertain whether this is an ongoing problem.
