### ISSUE TITLE
Remove the little arrow glyphs on buttons and links.

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#589]
For longer discussion, refer to this thread:
[accessibility] prev/next links and their arrows
http://forum.textpattern.com/viewtopic.php?id=43321

A while ago, I raised an issue in the forums about the accessibility problems (mainly for screenreaders) caused by having little arrows hard coded in the text value for some buttons. My suggestion was (and still is) to remove those arrows from the strings and let the (admin) theme author decide  how to present those buttons.

The secondary consideration for removal is an aesthetic one, they are visually jarring and take up space in some instances

The `prev/next` strings/buttons where used as an example (and the situation has improved with the change in the navigation widget on list panels) - there are other instances in the strings used in the text packs: the buttons on the set-up pages, there is a `back_to_top` string present, may be more. The `prev/next` is used on the Write panel.

**Comment by philwareham** [comment]
This has been done, will gradually be phased into the RPC as part of my normal RPC sync work.

**Comment by phiw13** [comment]
Thank you
