### ISSUE TITLE
Plugin help, RTL UI, text direction.

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#590]
STR:
1. install any plugin with a help file (I used [cbe_rand_content](https://github.com/ClaireBrione/cbe_rand_content) while testing), but any plugin will do.
2. switch the Texpattern language to any of the RTL languages available (Hebrew works out of the box for a local install on an average OS X box).
3. go to the Plugin panel, click the help link for the plugin.

Actual result: the (Western, LTR) text is displayed right aligned.
Expected: the text is aligned from the left.

On the plugin-install and plugin-edit sub panels the actual content (plugin code / help) is wrapped inside a `div.code` with the `dir=ltr` attribute hard coded. This probably could be done for the plugin-help sub panel (applied to the `div.txp-layout-textbox`I think).

Of course, if the plugin author actually provides a help file in a RTL language, this will look a bit sad.

**Comment by philwareham** [comment]
Not quite sure of the solution to this. Do we assume all plugin help is LTR? Probably not. Are multi-language plugin help files even supported in core?

**Comment by phiw13** [comment]
With my suggestion above, I assumed that the great majority of the plugins are LTR — perhaps that is a stretch.

Not sure either if that is the better solution. An alternative: modify the plugin templates to recommend the developer wraps his/her help text inside a div and sets the `dir=rtl` or `dir=ltr` on it. And a gentle suggestion in the plugin documentation.

(I noticed for instance that for the afore mentioned plugin, the author has already don’t part of it: the text is wrapped inside a `div`, just need to add the `dir`).

**Comment by philwareham** [comment]
I think @rwetzlmayr looks after the plugin template stuff. This is not really part of my scope so I've removed my assignment from the issue. Cheers!

**Comment by philwareham** [comment]
@bloke can modify plugin template for guidance - we can then assume English unless told otherwise by plugin.
