### ISSUE TITLE
MySQL 5.7: default SQL mode conflicts with having 0000-00-00 00:00:00 as default datetime

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#591]
See:
* http://forum.textpattern.com/viewtopic.php?id=46577
* http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-setting
* http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date

If the MySQL configuration setting ```sql-mode``` contains ```STRICT_ALL_TABLES``` and/or ```NO_ZERO_DATE``` (possible also if it contains ```STRICT_TRANS_TABLES```), creating tables that have a ```datetime``` column with default value set to ```0000-00-00 00:00:00``` fails.

In MySQL 5.7, ```sql-mode``` contains  ```STRICT_TRANS_TABLES``` and ```NO_ZERO_DATE``` by default, causing errors while setting up the tables:
1. Invalid default value for ‘Posted’
3. Invalid default value for ‘posted’
5. Invalid default value for ‘date_banned’
6. Invalid default value for ‘issue_time’
7. Invalid default value for ‘date’
8. Invalid default value for ‘date’
15. Invalid default value for ‘time’
16. Invalid default value for ‘last_access’

IIRC, the value "0000-00-00 00:00:00" has special meaning for the expired column, so we'd have to find an alternative for that as well as setting a different default value or not setting a default at all for other affected datetime columns.

Another solution might be to override the SQL mode in TXP before issuing any table related queries:
```SET SESSION sql_mode = '';```

**Comment by Bloke** [comment]
I'm a bit dim when it comes to such relational stuff, so what does your gut instinct tell you is the best option for Textpattern? Specifically I suppose we need to weigh up:

* What is an acceptable default for datetime columns under MySQL 5.7 with these config settings. NULL?
* What is it set to if we choose no default?
* How do we best compare if there is "no date" (e.g. for Expires) vs "some date", if it's not set to a known value?
* What is the impact of using the proposed solution on MySQL < 5.7?

Seems like overriding the SQL mode would be simplest (== least work), but could there be situations when that is disallowed by the host?

**Comment by vanmelick** [comment]
Overriding sql_mode is compatible with older MySQL versions (possible since MySQL 4.1).
This is the simplest way to fix this for now, but if at some point we plan on supporting other database servers (like ProgreSQL, which doesn't allow 0000-00-00 dates), then we may have to take a different path.

This issue is related to #414. I think we don't want to have zero dates stored in the database except for Expires (magic number, meaning: don't expire), so I think it's better to remove the default value for datetime columns, forcing TXP to explicitly set them at all times. For the Expires column, allowing NULL (for non-expiring articles) is probably the correct way to solve it. It'll probably affect some plugins that have queries which use the Expires column.

Since MySQL 5.7 is already released, I think this should be fixed for TXP 4.6. I'm volunteering to do this once a decision has been made on how to solve this.

**Comment by vanmelick** [comment]
There are now two reports of this issue in the forum.
I can reproduce it using MariaDB 10.1 (MySQL 5.7 refuses to install on my ubuntu/debian servers).

Once #579 and #526 are merged (anything holding them up?) I'd like to fix this by moving away from using 0000-00-00 dates. 

WP solved it by filtering out undesired SQL modes, because they thought it would break too many plugins. I don't think that'll be a problem with TXP. For one, plugins need updates anyway because of the tag registry and the only place where we use the zero dates is in the expired column and for that we have a constant, so changing it there should change it everywhere.

**Comment by philwareham** [comment]
@bloke or @rwetzlmayr can you take a peak at https://github.com/textpattern/textpattern/pull/579 and merge if all looks well?

**Comment by philwareham** [comment]
Fixed. Closing.
