### ISSUE TITLE
RFE - wrap the ‘edit’ links next to the category/sections select widgets in a `span`

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#592]
Write panel —> Sort and Display
Depending on width of the column and the length of `<select>`  widget, the ‘edit’ links next to the Category / Sections dropdown can potentially wrap between the `[` or `]` and word `edit` (or even inside the word, depending on the language, e.g. CJK). There are at least 2 line-breaking opportunities there

Suggestion: wrap the whole thing inside a span that would allow CSS control over the wrapping. Like so:

```
<span class=someclassname><span aria-hidden="true">[</span><a title="Edit" href="">Edit</a><span aria-hidden="true">]</span></span>
```

CSS: `.someclassname { display: inline-block; white-space:nowrap }`

(and then remove the non-breaking space adjacent to the `<select>`)

Screenshot of issue:
![edit-link](https://cloud.githubusercontent.com/assets/8944809/11327282/57eae75c-91c4-11e5-8b16-d8e2873e87c6.png)

**Comment by phiw13** [comment]
Hmm, while checking the Hive mockups, I notice that this `<span>` actually exist there:
https://github.com/philwareham/txp-hive-admin-theme/blob/master/mockups/content-article.html#L245

**Comment by philwareham** [comment]
Done, thanks.
