### ISSUE TITLE
Files panel control area layout

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#595]
There's an odd inline layout going on when there are files in the `/files` directory that don't have an entry in the database. See screenshot:

![filespanelcontrolarea](https://cloud.githubusercontent.com/assets/21252/11603838/67a968e0-9add-11e5-881b-350f25b4655e.png)

The spacing of buttons and controls seems a bit unstructured.

As the screen collapses, it starts to looks a bit better, but at some resolutions the buttons still don't seem to be in proximity to the boxes they represent:

![filespanelcontrolarea-small](https://cloud.githubusercontent.com/assets/21252/11603934/3503706a-9ade-11e5-89ec-18ca68791eee.png)

Might just need a bit of whitespace to make it render better. Anything that can be done about this? Markup changes? CSS?

EDIT: If the file name of the file on the server is reaaaaaaaally long, the select list box expands likewise.

**Comment by philwareham** [comment]
That's an oversight on my part - I will fix it.
