### ISSUE TITLE
Plugin panel: options link

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#600]
Not really a bug just a visual annoyance:

* Install a plugin that raises the `PLUGIN_HAS_PREFS` flag (e.g. ied_plugin_composer, adi_matrix, adi_form_links, smd_access_keys, ...)
* When the plugin is disabled, observe the rogue pipe symbol after the `Help` link.

Toggling the enabled/disabled status merely toggles the 'active' class on the row, and CSS takes over displaying the options link. Possible ways to fix:

* Tag the pipe with a class and use CSS to target it, only showing it when `active` is set on the `tr`.
* Somehow wrap the pipe in with the current `plugin-prefs` class so the two are treated as one element and thus toggled together.
* Something else...?

I think option 1 is the simplest fix, but I'm open to alternatives. @philwareham is this a good approach, and if so, what class name should be assigned to the pipe (currently line 206 of `txp_plugin.php`) bearing in mind it carries no ARIA weight?

Feel free to take ownership of this issue and add a class/CSS kludge if you wish, or let me know what you'd prefer and I'm more than happy to do the HTML/PHP.

**Comment by philwareham** [comment]
I'll take this one.
