### ISSUE TITLE
Focussed state of menu items (navigation bar) is hard to see

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#601]
Particularly for the top level menu items ( Content, Presentation, etc) the focus ring tends to get lost into the background colors. The submenu items do better, but they could use some love as well.

Perhaps the :hover style could be reused for the :focus style - although the background colour could be a bit stronger, that is ‘more whitish’ ?

`.txp-nav>ul>li>a:hover{background: rgba(255, 255, 255, .2)}`,
and `rgba(255, 255, 255, .4)` for the :focus state

(cheapo windows laptops don’t handle those delicate colour changes that well, from what I’ve seen yesterday…)

**Comment by philwareham** [comment]
Agreed, I will look at this soon.

**Comment by phiw13** [comment]
Hmm, Ok, that is not really what I mean.

I was mainly talking about the `:focus` state of the top level menu items – that is the state that is triggered when the user navigates the page with the keyboard (to be exact: `.txp-nav>ul>li>a:focus`).

Atm, the only visual feedback that happens is the display of a focus ring. That is eventually OK, my problem in this case is that the focus ring is hard to see against the background in that tight context (with the border separating the menu items and so on). I the went to to suggest to use the same style as you apply to the `:hover` state for the `:focus` state.

In other words:
- .txp-nav > ul > li > a:hover
+ .txp-nav > ul > li > a:hover,
+ .txp-nav > ul > li > a:focus {
+  background: rgba(255, 255, 255, 0.3);
}

Or more verbose: the keyboard user receives two types of visual feedback when the menu item is focussed: a focus ring *and* a background colour change. You might consider doing the same for the submenu items. As an added bonus you might consider highlighting that top level menu item when the submenu is open (after the user has clicked / pressed enter on the item).

What I usually do for that kind of navigation bar is suppress the focus ring but use (moderately) strong / contrasting color and background changes to indicate the focus state – similar to e.g. the OS X menu bar.

**Comment by philwareham** [comment]
I've made the focus rings more visible. Just got to sort out a little style bug with linked images focus rings and I will close this.
