### ISSUE TITLE
[regression] Current sticky footer code cause problems for Safari 9 (and won’t work in older browsers anyway)

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#602]
1. This: `@supports ((display: -webkit-flex) or (display: -ms-flexbox) or (display: flex))` is non-sense: IE 10, 11 + Safari 7/8 do not understand `@supports ()`

2. This
```
.txp-body {
    -webkit-flex: 1 1 0%;
        -ms-flex: 1 1 0%;
            flex: 1 1 0%;
  }
```

Cause the sticky footer to display in the middle of the page (on very long pages) or otherwise overlap the bottom of the `.txp-body` element. It is a bug in Safari 9 (and older) and older Blink based browsers (Chromium < 43 I think) where it incorrectly handles percentage based `flex-basis` with `flex-direction: column`. Try the Admin > languages panel for an obvious example.

It should be `flex: 1 1 auto`.

**Comment by phiw13** [comment]
it is a regression from this commit: https://github.com/textpattern/textpattern/commit/8243be11849d36bb096f562895e753c3b747cc19

(and this: https://github.com/philwareham/txp-hive-admin-theme/commit/3537bf66b10ed9896c549172275aa75cfa3d097a

**Comment by philwareham** [comment]
Yeah the supports problem is that autoprefixer mangles the rule. I may have to drop autoprefixer from the build script unless I can find a way to stop it from changing that one rule, or just live with it,

Will amend the other flex rule, thanks.
