### ISSUE TITLE
Fatal error: Uncaught Exception: invalid_argument: locale

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#603]
I got this error after I installed the nl-nl language and then selected that language at the top in the languages tab.
```
Fatal error: Uncaught Exception: invalid_argument: locale
in /var/www/html/textpattern/textpattern/vendors/Textpattern/L10n/Locale.php:141
Stack trace: 
#0 /var/www/html/textpattern/textpattern/include/txp_lang.php(310): Textpattern\L10n\Locale->setLocale(6, 'nl-nl')
#1 /var/www/html/textpattern/textpattern/include/txp_lang.php(49): save_language()
#2 /var/www/html/textpattern/textpattern/index.php(210): include('/var/www/html/t...')
#3 {main} thrown in /var/www/html/textpattern/textpattern/vendors/Textpattern/L10n/Locale.php on line 141
```
This occurs on a server with the following locales:
```
# locale -a
C
C.UTF-8
POSIX
en_US.utf8
```
Changing the language in TXP to en-gb or en-us did not cause any errors. 

There's two issues here, I think:
1. The exception isn't caught.
2. Why was the exception thrown? Changing the language to one I just installed seems like a valid thing to do.

**Comment by phiw13** [comment]
See also this forum thread: http://forum.textpattern.com/viewtopic.php?id=40685

**Comment by philwareham** [comment]
Fixed. Closing.

**Comment by brachycera** [comment]
Heads up for anyone else who has Problems updating from TXP 4.5.7 to TXP 4.6.0. I had the following Error:

`Fatal error: Uncaught exception 'Exception' with message 'invalid_argument: locale' in PATH_TO/textpattern/vendors/Textpattern/L10n/Locale.php on line 141`

I had two `<txp:posted>` Tags with the Attribute value for `lang="de"`. After changing the value to `lang="de_DE"` the Error went away. This Error also occurred  with other languages.

**Comment by Bloke** [comment]
I'm looking into this, thanks. I think all we need to do is add judicial use of `try... catch` blocks around any `setLocale()` calls that might try to set the locale to anything other than your default. I just need to set up a test environment to simulate it and I'll see if my patch works.

For your specific issue (inside the `safe_strftime()` function) I've done this as an as-yet-untested kludge, replacing the block from line 3111 with this:

```
    if ($override_locale) {
        $oldLocale = Txp::get('\Textpattern\L10n\Locale')->getLocale(LC_TIME);

        try {
            Txp::get('\Textpattern\L10n\Locale')->setLocale(LC_TIME, $override_locale);
        } catch (\Exception $e) {
            // Revert to original locale on error and signal that the
            // later revert isn't necessary
            Txp::get('\Textpattern\L10n\Locale')->setLocale(LC_TIME, $oldLocale);
            $oldLocale = false;
        }
    }
```

In theory, that rolls back to the default locale if it can't do your specific bidding. I'd be interested to know if it works in your case, if you fancy patching your core.

**Comment by brachycera** [comment]
@bloke, after adding your code snippet to `txplib_misc.php:3111` I was not able to trigger the Error again! 👍
