### ISSUE TITLE
Error message on languages panel should have an icon

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#604]
(side benefit of a server downtime…)
A minor issue… but for the sake of consistency, etc:

current markup: `<p class="error lang-msg"> text of message`

expected markup, based on the pattern used elsewhere: `<p class="alert-block error lang-msg"><span class="ui-icon ui-icon-closethick"></span>  text of message`

Screenshot of issue:
![txp-error-message](https://cloud.githubusercontent.com/assets/8944809/11949416/0e5dc3d8-a8c2-11e5-872d-67dd5dbf3a64.png)

**Comment by philwareham** [comment]
Thanks, fixed now!
