### ISSUE TITLE
Integrate Tablesaw for better responsive tables

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#606]
Investigate using [Tablesaw](https://github.com/filamentgroup/tablesaw) to provide better table functionality and responsiveness. Also provides better column sorting and hiding than our very rudimentary 'show more detail' toggle.

Either as part of a admin theme, or as a vendor library (which is preferred route for me).

Tables would need additional `class` attributes and some `data-x` attributes depending on what we choose to harness.

**Comment by Bloke** [comment]
Funnily enough I was looking at this approach for a separate project a few weeks ago. The [one I saw](http://codepen.io/pixelchar/pen/rfuqK) required the HTML 5 `data` element to tag each cell with the column name, then at small breakpoints used CSS to prepend that element's content to the markup using the `:before` pseudo-element:

    content: attr(data-title);

Cunning, but it didn't do all the sorting, column selection, and cool swiping malarky that datasaw does.

So, yeah, a plugin for all that stuff takes away the headache of doing it by hand. All we'd have to do would be to add the classes and kick it off. The plugin does have a bunch of fairly major open issues at the moment, though.

**Comment by philwareham** [comment]
Great! Yeah hopefully some of these issues will be resolved by the time we release Textpattern 4.7 ;)

I'll do some local testing of this when I finish other tasks.

**Comment by philwareham** [comment]
Closing this, as we have our own solution to responsive tables in development (column hiding).
