### ISSUE TITLE
Sections panel: title attribute on links in the ‘articles’ column contains markup

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#608]
Expand the table (show more detail), view the last (‘Articles’) column.

Markup for the links:

```
<a title="Articles in this section: &lt;strong&gt;25&lt;/strong&gt;." href="foo">25</a>
```

![txp-art-markup](https://cloud.githubusercontent.com/assets/8944809/12161070/3308f822-b535-11e5-841f-1388b5f3a621.png)

**Comment by philwareham** [comment]
Thanks for the report. Fixed by this commit https://github.com/textpattern/textpacks/commit/d4d1b109e3e03690d98a372b140f242cc421279f
