### ISSUE TITLE
Widths in setup splash screen too narrow

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#617]
In the first page of `/textpattern/setup/`, the `form` width is too narrow for the default language text. The form field should be long enough for the longest language name, which is currently 'Bosanski (Bosna i Hercegovina)'. Screenshot attached.

@philwareham - I appreciate you could likely change this more quickly than I could, but I can pick through the CSS if time is short.

![setup textpattern cms 20160125](https://cloud.githubusercontent.com/assets/226578/12562169/9801706e-c39b-11e5-96e1-4d5612f3daae.png)

**Comment by philwareham** [comment]
@petecooper oh, I thought I'd already fixed that, but you're right. I will fix now. Cheers for spotting it.
