### ISSUE TITLE
User_Error "Field 'LastMod' doesn't have a default value" when duplicating an article

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#618]
Articles panel: select an article (checkbox), using the widget at the bottom of the table, choose duplicate.

```
User_Error "Field 'LastMod' doesn't have a default value"
in /Users/<username>/Sites/site/textpattern/lib/txplib_db.php at line 401.
adminErrorHandler()
textpattern/lib/txplib_db.php:401 trigger_error()
textpattern/lib/txplib_db.php:477 safe_query()
textpattern/include/txp_list.php:710 safe_insert()
textpattern/include/txp_list.php:58 list_multi_edit()
textpattern/index.php:210 include()
```

And afaict, the article is not duplicated.
Tested with an old site( upgrade to 4.6dev latest), a new site (created with 4.6dev), with old and newly created articles.

MySQL: 5.6.21, PHP: 5.5.30

**Comment by vanmelick** [comment]
I cannot reproduce this, but I'm on MySQL 5.5 and this may be something that happens only in 5.6+.
Probably it's because of line 702 in txp_list.php, where LastMod is unset in the array that is used to insert data for the duplicated article into the database.

**Comment by vanmelick** [comment]
The easiest fix is to not unset LastMod. The effect would be that the copied article has the same last modified timestamp as the original, which would match the behaviour of duplicating the article from the write tab. This is related to issue #614, so once a decision has been reached there on how to solve it, I'll tackle both issues with a single patch. I'd pick the "write tab" duplicating behaviour over the "article list tab" approach.

**Comment by phiw13** [comment]
> I'd pick the "write tab" duplicating behaviour over the "article list tab" approach.

Yeah, I would expect both “duplicate” functions to return the same results.

**Comment by philwareham** [comment]
Fix now, thanks Ruud.

**Comment by phiw13** [comment]
Hmm, I still get an error when duplicating an article from the Articles panel (and no article is duplicated, AFAICS):

```
User_Error "Incorrect datetime value: '' for column 'Expires' at row 1"
in /Users/username/Sites/_txp/textpattern/lib/txplib_db.php at line 401.
adminErrorHandler()
textpattern/lib/txplib_db.php:401 trigger_error()
textpattern/lib/txplib_db.php:477 safe_query()
textpattern/include/txp_list.php:712 safe_insert()
textpattern/include/txp_list.php:58 list_multi_edit()
textpattern/index.php:210 include()
```

None of the articles I tried have an “Expires” date set.
Everything works fine from the Write panel.

**Comment by vanmelick** [comment]
Which MySQL version do you use? I can't reproduce this on 5.5 and 5.6.
I think I know what's causing it. See pull request #628

**Comment by vanmelick** [comment]
Apologies. Pull request #629 instead (or my duplicate branch).

**Comment by phiw13** [comment]
> Which MySQL version do you use?

same as my original post above.

Pull request #629 does seem to fix the issue though. No more ugly errors displayed and article(s) is/are duplicated.
