### ISSUE TITLE
One column layout for default theme

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#619]
Just putting this here as a 4.6 release blocker. Full issue here: https://github.com/textpattern/textpattern-default-theme/issues/67

**Comment by Bloke** [comment]
Can members of the community submit their own take on the front-end theme and you just roll in the best design? Or the best elements of the designs submitted? Takes the pressure off you to do it all, and might create a bit of buzz about the release.

**Comment by philwareham** [comment]
They can at v4.7 when we have a theme system, in the meantime I'd rather keep what is already there. Changing it to one column layout is pretty simple and I can do it in one afternoon, when I get time. It would actually be more work than that to incorporate user contributed layouts right now.

**Comment by philwareham** [comment]
Working on this at the moment.
