### ISSUE TITLE
Tag for 4.5.7 release

### ISSUE THREAD

**Issue by scar45** [textpattern/textpattern#620]
Hello TXP Team,

I am integrating TextPattern's source into a new website project of mine, by using this repo as a submodule. However I noticed there is no branch or tag for the stable 4.5.7 release. Is it possible that one can be created?

I'd prefer to (eventually) launch this site on 4.5.7 rather than the latest batch of development commits. Thanks in advance, and also massive thanks for your efforts in maintaining this excellent project!.

**Comment by philwareham** [comment]
Hi!

Unfortunately due to the project being migrated from Google Code (SVN) to GitHub (Git), the 4.5.x branch was not carried over. I've tagged all the releases that I could - up until 4.5.2. That was were the 4.6dev and 4.5.x branches diverged.

Thinking out loud, I guess I could create a new branch and upload 4.5.7 to it. It won't have the commit history but it would allow a tag I think and it would allow that branch to be developed independently if there needs to be any major security/bug fixes for 4.5.x in the future.

@bloke and @rwetzlmayr - what do you think?

**Comment by rwetzlmayr** [comment]
I think that the 4.5.x branch relies on SVN revision numbers in some parts (e.g. diagnostics), and we already have a repo established for that. 

You can tag any existing git commit by its hash:

```
git tag -a v4.5.7 <commit_hash> -m "Tagging v4.5.7"
```

**Comment by scar45** [comment]
Thanks for the detailed explanation @philwareham -- I didn't want for this to change the repo policy or create more work in any way. Even if the 4.6.0 official release is tagged, that would be great.

Also, may I be so bold as to suggest a reworking of the Git branch/tags? I was kind of confused to discover that the `master` branch has the latest, bleeding edge code. I've always used a `dev` branch for that purpose, then updated `master` and created a final release `tag` from it once the code was ready. 

After reading the [roadmap blog post](http://textpattern.com/weblog/386/textpattern-portishead-meet-2015), it seems like there are other 4.x.0 branches on the cusp as well, and I'm not sure if they're being developed simultaneously, but if so, they could be denoted by branches like `dev-4.7.0` etc. Again, I hope I am not crossing boundaries, but it's just a humble suggestion for the post-migration from SVN.

BTW, would the core devs ever consider accepting Bitcoin as a form of donation? Looking forward to the release of 4.6.0 (and beyond) with TXP! Thanks again.

**Comment by philwareham** [comment]
The GitHub workflow is one of individual preference really. I personally like the workflow of:

1. Develop in `master` for minor commits.
2. For larger feature changes, develop in a branch and then when ready merge back into `master`.
3. For releases, tag the release, then branch off for any further patches in that release e.g., a branch called `4.6` with any further tags in that for 4.6.x changes.
4. `master` then effectively becomes 4.7 development.
5. Any changes that are appropriate to both `master` and `4.6` can be merged in both.

I'm hoping we can get 4.6 out within a few weeks, and follow this above method - other devs agreeing, of course.

**Comment by scar45** [comment]
After you've laid it out @philwareham, it definitely makes sense, and I apologize for suggesting otherwise (although I wasn't fully aware of the strategy). Excellent to hear that 4.6 is nearing a release, and I will keep an eye out for the tag so that I can base my new projects off of that as a submodule.

Thanks again, and I hope my donation came through to you, and the team, successfully via PayPal. Cheers!

**Comment by philwareham** [comment]
No apology needed. And I've just seen the PayPal donation - thank you very much! Will close this issue for now.

**Comment by philwareham** [comment]
Hi again,

I've created a 4.5.x branch and imported snapshots of the original SVN fork at various 4.5.x versions into it. All properly tagged as releases.

It doesn't have the complete commit history, but that is a small price to pay I think for having the releases readily available on GitHub.

**Comment by scar45** [comment]
This is great @philwareham - and definitely no worries about missing the commit history for this branch. I just basically needed a branch that I know matches the current production release for 4.5.7. I was prepared to wait for 4.6.0, but this was a nice surprise. Thanks much!
