### ISSUE TITLE
Supply default favicon

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern#626]
In .htaccess we have a rule to avoid TXP handling requests for a missing favicon.

Why don't we supply a default favicon instead? It's free advertising.

**Comment by philwareham** [comment]
Do you mean on the public side theme or admin side? On the public side we try to be as non-opinionated as possible.

**Comment by philwareham** [comment]
I've added a favicon when users are in the admin-side. I won't add a public side favicon for he reason stated above. Closing.
