### ISSUE TITLE
Permalink title format text string incorrect

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#632]
The text string used for the revised Permalink title format preference is wrong.

It should use the text string `permlink_format` not `permalink_title_format`.

**Comment by Bloke** [comment]
Wait, so we're using `permlink_format` but leaving `attach_titles_to_permalinks` (with an 'a')?

**Comment by philwareham** [comment]
Yes, it seems there are some strings that reference `permalink` and others that reference `permalink` - there is no consistency as far as I can see, although it could be argues that some directly reference our `txp:permalink` tag and others are more generally talking about permalinks.

**Comment by Bloke** [comment]
OK, well the label in prefs is easy to change, but note that it also means we need a new help entry in the RPC server for `permlink_format`. You gonna copy the old one over and tweak it to reflect the new strings names?

**Comment by philwareham** [comment]
Yes, I will duplicate - we had to make a new string because changing the legacy string was not viable in this instance.

**Comment by Bloke** [comment]
Addresses in 522a47425513e022c1fa99819db0a4dc15a9f66f. Up to you if you close this ticket now or leave it as a reminder to do the RPC pophelp entry.

**Comment by philwareham** [comment]
Thanks Stef. I will close this and open an issue at the pophelp repo.
