### ISSUE TITLE
Multisite symlinks incorrect

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#634]
due to relocation of jquery.js to vendors folder.

In the [/sites/site1/admin](https://github.com/textpattern/textpattern/tree/master/sites/site1/admin) folder:

* delete symlink to `jquery.js`.
* add symlink to `vendors` folder.

In the [/sites/site1/public](https://github.com/textpattern/textpattern/tree/master/sites/site1/public) folder:

* add symlink to `.htaccess`, (or a duplicate htaccess) OR
* Add the need to copy the htaccess to the public folder to the [How-to](https://github.com/textpattern/textpattern/blob/master/sites/README.txt) instructions.

In the [How-to](https://github.com/textpattern/textpattern/blob/master/sites/README.txt) instructions, add clarification about:

* Which files/folders to delete (e.g. `/files`, `/images`, `index.php`) + which to keep (e.g. `css.php`). What about phpstorm.meta.php, phpcs.xml and composer.json? Or are these not part of the distro version anyway?
* Expected error messages on the diagnosis panel. Some of these are mentioned elsewhere (e.g. [Jeff Soo's article](http://ipsedixit.net/txp/118/textpattern-multisite-setup)). Maverick pointed to several issues in [this thread](http://forum.textpattern.com/viewtopic.php?id=35521) too.

**Comment by philwareham** [comment]
Bit confused about the jQuery symlink - it seems to point to the `vendors` location for `jquery.js` already. Can you provide further info on that?

**Comment by jools-r** [comment]
I did a test install of the multisite configuration a few days ago and after installation, a lot of the query-dependent functions in the admin area would not respond: the web inspector showed that jQuery and jQuery UI were not loading. In v4.6, jquery.js is no longer in the base directory and is instead referenced via the vendors folder, so I surmised that the symlink needed setting to the vendors folder and deleted the first symlink and added a folder symlink to the vendors folder. Thereafter the admin functioned properly. I then set up a further multisite folder and noticed that the password strength meter was now also showing (but maybe I was just inattentive the first time around).

**Comment by philwareham** [comment]
I've created a branch `multi-piste-fix` for these multi-site fixes - please download a Textpattern install from that branch and test. If OK, I will then merge into master.

Since I have never used multi-site capabilities, maybe you would like to amend the README file with any additional info you feel is pertinent. Just create a pull request once you are happy with the content (for example, I don't know if the top-level `css.php` file is needed when using multi-site).

FYI `phpstorm.meta.php`, `phpcs.xml` and `composer.json` files (and some of the hidden files such as `.gitignore`) should not form part of the distro, as they are for development only.

**Comment by jools-r** [comment]
I'm sure you've seen this already, but I tested it and reported back [in the forum](http://forum.textpattern.com/viewtopic.php?pid=297939#p297939).

**Comment by philwareham** [comment]
@jools-r I think I've corrected the symlink now - let me know. As mentioned previously - you are probably better placed than I to amend the README instructions as I've never used multi-site. Please fork the branch and make amends, then do a pull request and I will merge. Thanks!

**Comment by philwareham** [comment]
Fixed now. Closing.

**Comment by jools-r** [comment]
Thanks!
