### ISSUE TITLE
Preferences page - save the menu position

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#637]
I think it would be better UX if, when pressing 'save' in preferences page, that it stays on the current pane you have open, instead of jumping back to the 'Site' pane at the top. I'd imagine this could be done with tokens in a similar fashion to how other page states in the admin side are stored?

**Comment by Bloke** [comment]
Thanks for reminding me. This was actually on my todo list but at the time I couldn't find a neat way to use/hack/extend the current mechanism we have for stashing a per-user pref when toggling UI elements.

**Comment by philwareham** [comment]
OK great, OT any ideas on issue #631 - I had a quick look and I can't understand the code :(
