### ISSUE TITLE
Accentuated characters and author tag

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#643]
Latest TXP 4.6 dev branch:

Changing the author's real name with accentuated characters.

Using the `<txp:author />` tag in a form.

It seems that `<txp:author link="1" this_section="1" />` tag do not returns accentuated characters in author's name.

**Comment by cara-tm** [comment]
Please delete this: all is fine. Results wasn't shown due to a strange server delay.
Sorry.

**Comment by philwareham** [comment]
Closing as requested.
