### ISSUE TITLE
Protect current article ID from duplication

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#653]
Current 4.6 dev branch.

Just to report; I imagine this is over the scope and a programming difficulty.

Writing a new article, publish it, clic on the "Preview" icon, see the current article on the front side, then go back with the browser arrow (the only one possibility).

Due to a temporary Internet access error, I can't return to the back admin side. I click into my address bar in order to reload the page: a warning message tell me I'm going to submit again my request (so, a "post event" request). I've got the same article twice.

**Comment by bloatware** [comment]
Thanks for the report, confirmed. New (only?) articles seem to be duplicated on reload.

**Comment by philwareham** [comment]
@bloke thoughts on this one?

**Comment by Bloke** [comment]
Short of redirecting after saving a new article (so the POST data is cleared) I can't think of a way round this.

**Comment by bloatware** [comment]
[This](https://forum.textpattern.io/viewtopic.php?pid=306172#p306172) would help too, if ever we are going to switch to UUID.

**Comment by bloatware** [comment]
Should be fixed by [https://github.com/textpattern/textpattern/commit/349160a5a144c7cc3cd1dae8122afb8247051d93](https://github.com/textpattern/textpattern/commit/349160a5a144c7cc3cd1dae8122afb8247051d93) to some extent, please test.

**Comment by bloatware** [comment]
Fixed by [https://github.com/textpattern/textpattern/commit/6d170b16e0e97a9a6d6d7ac452607194f546d498](https://github.com/textpattern/textpattern/commit/6d170b16e0e97a9a6d6d7ac452607194f546d498), closing.

**Comment by cara-tm** [comment]
Thank you lot ;)
