### ISSUE TITLE
Write panel: Odd behaviour of the sub-panels in the sidebar on saving

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#666]
I’m not sure if I should blame @philwareham [1] or @bloatware  [2] for this.

STR:

1. open an existing article
2. observe the state of the sidebar (for ease of testing: all sub panels in the sidebar are closed/collapsed)
3. edit the article – any type of editing will do (edit text, change status,…)
4. save
5. observe the state of the sidebar. On my Mac (tested with Safari and Firefox dev. edition), the “recent articles” sub panel is now open (and this can not be changed unless leaving the Write panel and returning – or toggling the view Text --> HTML and back) and the “comment” sub panel is open, but its heading is not displayed (again, toggling the view is enough to restore some sanity).

But open another article for editing or create a new article and the sub panels return to the state they were. Note also that this does not happen when creating a new article.

[1] https://github.com/textpattern/textpattern/commit/f0fb17f238968a79f36b80637f4632ae66c095db
[2] https://github.com/textpattern/textpattern/commit/ff1a2111efa2830dcafae3fc25a4fef4a17625db

Screenshot of the comment sub panel:
![txp-write-20160412](https://cloud.githubusercontent.com/assets/8944809/14446634/2a5d8748-0093-11e6-9d33-67ad4afa6fba.png)

**Comment by phiw13** [comment]
Thanks @rwetzlmayr.
Mostly there – I still see a small glitch in the Comment sub panel. After saving an existing article, there are 2 “Invitation” fields. As before, switching back-and-forth between views restores things to a sane state.

![txp-write-20160412-2](https://cloud.githubusercontent.com/assets/8944809/14451745/5de5d940-00c4-11e6-9b85-b953ecd83c69.png)

**Comment by philwareham** [comment]
I have no idea why this is happening, sorry - tried a couple of placeholder variations but to no avail. Hopefully @rwetzlmayr can fix it for us.

**Comment by rwetzlmayr** [comment]
@philwareham The panel would need a single embracing HTML element as a parent for `.comment-annotate` and `.comment-invite` elements as the toggle function can only show / hide one single immediate child of `#txp-comments-group-content.toggle`. 

Please suggest a proper markup, I'll patch it in.

**Comment by philwareham** [comment]
@rwetzlmayr OK, would the wrapper have to wrap the potential 'Comments expired' paragraph too, or is that not necessary?

**Comment by rwetzlmayr** [comment]
@philwareham No, they needn't. We just need a common selector for both the 'comments are open' and 'comments are closed' states of that markup. 

Which makes me wonder whether `fieldset` is still en vogue these days...
