### ISSUE TITLE
Menu item order in the 'Content' menu

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#670]
I consider it odd that 'Categories' is the top-most menu item in the 'Content' menu. The current menu item sequence is just a leftover from the tab-based navigation we shipped in earlier versions.

I propose to lift 'Write' to the top, push 'Categories' to the bottom, and leave the rest as-is.

**Comment by philwareham** [comment]
Fine by me, I'd say categories are of more importance than comments though? So second from bottom maybe?

**Comment by phiw13** [comment]
No objection from me – apart from the muscle memory issue…

@philwareham – as the last item it will have higher visibility, I think.

**Comment by Bloke** [comment]
From a workflow perspective, you can set up Categories first before publishing, so the current order is logical(ish). But since there are cats already defined out of the box and you get dropped on the Write panel by default anyway, sure, demote Categories somewhere further down the list.
