### ISSUE TITLE
Hamburger menu behavior

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#673]
Latest TXP dev branch:

On Firefox (latest desktop version), reduce the window to show the hamburger menu, then mouse hover this menu changes this entire square to white color.

**Comment by philwareham** [comment]
Confirmed in webkit too. Looks like latest Normalize.css rules have increased the focus specificity. Will fix  in my next update of the admin side.

**Comment by cara-tm** [comment]
;)
