### ISSUE TITLE
The `never_display_email` pref appears superfluous

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#677]
Background: http://forum.textpattern.com/viewtopic.php?id=46968

In 4.5.7, the `never_display_email` pref is 'no'. In 4.6-dev it's currently 'yes'. In both versions, for both preference choices, adding a `<txp:comment_email />` tag to the `comments` form will output the comment email address. The preference doesn't appear to have any effect on the front side output.

The default theme currently uses `<txp:comment_email />` in a variable to ascertain whether the comment is by the article author and style it accordingly, but does not display the email address.

Possible solutions:

* define what the preference should do in real terms, and fix it
* remove the preference

_Edit_: failures in basic English.

**Comment by bloatware** [comment]
The front-side behaviour of this preference is explained by [phiw13](http://forum.textpattern.com/viewtopic.php?pid=298790#p298790) post. Changing this could result in bws incompatibility, though I agree, hard-coded markup iznogoud.

**Comment by petecooper** [comment]
A-ha - that makes more sense. A docs explanation for the tag(s) would solve this. I'll close.

Thanks @bloatware and @phiw13 - gold star for each of you.
