### ISSUE TITLE
Languages panel

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#692]
When we look at the whole Textpacks revise as part of 4.7 (with local text files included in distribution, instead of RPC) it would also be pertinent to look at the UI for the languages panel.

At the moment it's a bit rudimentary - just a table with a few columns dedicated to various ways of installing/removing. This could be a lot nicer with some thought as to new layout.

**Comment by philwareham** [comment]
Just while I'm thinking about it - need to add info on translation contributions and also link to a page on the new textpattern.com website pertaining to that (we could also on the .com site have translation progress displayed via Crowdin's API).

**Comment by philwareham** [comment]
For reference, mockup proposal of how the languages panel could be sampled based on plans for handling languages in 4.7: http://design-patterns.textpattern.io/mockups/admin-languages-proposal.html

**Comment by phiw13** [comment]
1. did you see the discussion in [this forum thread](http://forum.textpattern.com/viewtopic.php?pid=303005#p303005)?

2. I’m really puzzled: why do set that grid to be `display: inline-flex` – which is basically an inline element, like `inline-block` ?

**Comment by philwareham** [comment]
This is merged now. Closing.
