### ISSUE TITLE
Discrepancy in encoded entity between title and body field

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#697]
1. Type `I’am` in the title field
2. repeat the same snippet in the body field

actual result (view source on the published article):
Title —> `I&#039;am`
Body —> `I&#8217;am`

Expected: `I&#8217;am`

(grammar for that snippet is intentionally wrong!)

(spin off from issue 696)

**Comment by Bloke** [comment]
See also: #676 and #672

**Comment by bloatware** [comment]
Can not reproduce

**Comment by petecooper** [comment]
I attempted to reproduce here with current 4.6-dev and cannot. I copy + pasted from OP to ensure no conversion weirdness, but no encoding took place at all. Could it be a localisation issue?

**Comment by phiw13** [comment]
Hmm, when I look at my OP again, I see that it uses a curly quote (aka U+2019) those are not encoded. Somewhere a wrong cop paste happened…

Trying again: `I'am` - using a straight ' (aka U+39 - shift-7 on an average US-EN or JIS qwerty keyboard). This reproduces the issue on my side.

**Comment by bloatware** [comment]
Straight quotes are converted by Textile, and the `Body` is generally textiled, unlike the `Title`. That has always been like this, though we could finally use `Title_html` to store the textiled `Title`. But then why not to do it for other fields? Needs some thinking.

**Comment by bloatware** [comment]
Use global `escape="textile"` where needed. Closing.
