### ISSUE TITLE
Inconsistency in pluggable_ui

### ISSUE THREAD

**Issue by gomedia-adi** [textpattern/textpattern#703]
pluggable_ui() usually provides the markup ($default) and the database information ($rs).

pluggable_ui() in the inputLabel() function doesn't feed the database info ($rs) through for plugins to access. 

It'd be useful (and consistent) to have $rs supplied when accessing pluggable_ui generated by inputLabel().

**Comment by bloatware** [comment]
@gomedia-adi , which `$rs` do you suggest to be supplied? inputLabel() being used in different places (articles, images, ...), how to do it consistently?

**Comment by gomedia-adi** [comment]
The $rs of the tab where inputLabel() is called. It already has the $event of the tab.

**Comment by petecooper** [comment]
This has languished a bit since mid-2016. @bloatware - should we label this and give it a milestone?

**Comment by bloatware** [comment]
Sorry, but I still don't see how this should be done. There is over 100 occurrences of `inputLabel()` in core, including e.g. Diagnostics tab, where no canonical `$rs` seems to exist. Or I don't understand what `$rs` is expected here. @gomedia-adi mind explaining in more details or suggesting a patch for this?

**Comment by gomedia-adi** [comment]
I think this one can be knocked on the head. Can't recall the specific issue that inspired me to raise it in the first place. Besides, TXP admin code has changed so much in the intervening couple of years that it may be irrelevant anyway. Thanks.
