### ISSUE TITLE
Shortcut for Textpattern system requirements

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#706]
Currently, `README.TXT` includes pretty links (like `http://textpattern.com/hidden-files-osx`) and not-so-pretty links (like `http://textpattern.com/about/119/system-requirements`).

The system requirements will clearly change over time, but the page should be easily accessed. The `119` part of the URL relates to the article number, and may change with an overhaul and/or URL format change.

Suggested actions: add a `.htaccess` rewrite on .com for `http://textpattern.com/about/119/system-requirements`, point `http://textpattern.com/system-requirements` at it, and update `README.TXT`to reflect the URL.

**Comment by philwareham** [comment]
Will do.

**Comment by petecooper** [comment]
Thanks, @philwareham!
