### ISSUE TITLE
Daylight Saving Time enabled? styling

### ISSUE THREAD

**Issue by gomedia-adi** [textpattern/textpattern#709]
When the "Automatically adjust Daylight Saving Time setting?" is set to Yes, "Daylight Saving Time enabled?" is disabled.

It'd be nice if:
- it was a bit more obvious that the pref is disabled - e.g. make the text a lot lighter
- it indicated whether DST is currently in progress or not

**Comment by Bloke** [comment]
This is bizarre. I don't see the point of the is_dst setting. Try this:

* Visit _Admin->Preferences_.
* Set timezone to Europe/London (because today is in June, DST is in effect) or an equivalent timezone you know is experiencing DST "today", and save.
* Switch _Automatically Adjust DST_ to No, and save.
* Set _Daylight Savings Time in effect_ to No, and save.

Expected: _Daylight Savings Time in effect_ set to No
Actual: _Daylight Savings Time in effect_ set to Yes, ignoring your chosen setting.

The offending code in `txp_prefs.php` is:

```
    // Forge $gmtoffset and $is_dst from $timezone_key if present.
    if (isset($post['timezone_key'])) {
        $key = $post['timezone_key'];
        $tzd = Txp::get('\Textpattern\Date\Timezone')->getTimeZones();

        if (isset($tzd[$key])) {
            $prefs['timezone_key'] = $timezone_key = $key;
            $post['gmtoffset'] = $prefs['gmtoffset'] = $gmtoffset = $tzd[$key]['offset'];
            $post['is_dst'] = $prefs['is_dst'] = $is_dst = Txp::get('\Textpattern\Date\Timezone')->isDst(null, $key);
        }
    }
```

Since it overrides the DST setting if you have a timezone set, what's the point of offering the option just for Txp to ignore it and use the server value? Not much of a setting! Can we do much better here, e.g. by hiding the thing altogether if a timezone has been set? Or at least honour the setting if someone wants to do it manually?

For starters I'm going to shift the timezone setting down one place so it's grouped with the other associated radios. Then can we all discuss ways to make this mess a bit less messier?

**Comment by rwetzlmayr** [comment]
I remember that I fiddled a lot to with this UI to accommodate systems with or without timezone support - we didn't even have the `DateTimeZone` class in PHP 4.x, mind you!

In Txp 4.5.7, the prefs' timezone selector had an empty option, while in Txp 4.6 it does **not** have one. See https://github.com/textpattern/textpattern/commit/90674d4ffe6eeeadc2905b12f075a88eebb8b2a3#diff-32eb7619ddf5ec5c6eb48cd2cb27aa97L370 for the relevant commit. So in theory `if (isset($post['timezone_key']))` could be `false`.

I think it is fair to assume that this code snippet does not make much sense and probably has to be re-aligned with the accompanying UI and the capabilities of PHP 5.3+.

**Comment by rwetzlmayr** [comment]
I remember that I fiddled a lot to with this UI to accommodate systems with or without timezone support - we didn't even have the `DateTimeZone` class in PHP 4.x, mind you!

In Txp 4.5.7, the prefs' timezone selector had an empty option, while in Txp 4.6 it does **not** have one. See https://github.com/textpattern/textpattern/commit/90674d4ffe6eeeadc2905b12f075a88eebb8b2a3#diff-32eb7619ddf5ec5c6eb48cd2cb27aa97L370 for the relevant commit. So in theory `if (isset($post['timezone_key']))` could be `false`.

Some JS used to prevent illogical settings, see https://github.com/textpattern/textpattern/commit/90674d4ffe6eeeadc2905b12f075a88eebb8b2a3#diff-32eb7619ddf5ec5c6eb48cd2cb27aa97L410.

I think it is fair to assume that this code snippet does not make much sense and probably has to be re-aligned with the accompanying UI and the capabilities of PHP 5.3+.

**Comment by Bloke** [comment]
Good find re: the non-empty select. That would certainly scupper things.

So, we can now assume that `DateTimeZone` exists (minimum system requirements) and probably that `date.timezone` is set in `php.ini` (or there'd be errors flying).

Past that, we need to figure out what we want to happen under the various situations, including when:

* auto dst is on /off.
* `timezone_key` is set / not set / false.
* someone manually overrides dst is in effect (if we permit that at all?)

Anyone want to make a first stab at what the various interactions ought to look like?

**Comment by Bloke** [comment]
OK, I had a first stab at it. See referenced commits and please test.

If you set auto_dst to Yes and donkey around with the server date, pushing it either side of a DST switchover period, you'll notice the is_dst radio button change to reflect the current state of DST in that timezone, even if you don't save the prefs. Just viewing them is enough to make it alter the radio value at DST changeover points.

While this is potentially misleading -- it doesn't actually reflect the value stored in the prefs database table -- as long as the rest of Txp's internals rely on the value of our \`vendor\Date\TimeZone->isDst()` method when auto_dst is set to Yes, then nobody will be any wiser.

Have I caught all corner cases or are there nuances to this I've missed?

**Comment by gomedia-adi** [comment]
Perhaps, as you mentioned before, there's no point in offering the DST pref at all if Auto is set.

Because timezones are a mental/technical minefield, I think the key thing here is that TXP indicates whether DST is in progress or not. From a diagnostic point of view it'd help us mortals greatly.

Maybe the way forward is to:
1) Hide "Daylight Saving Time enabled?" completely if Auto is set to "Yes"
2) Dynamically generate a note against the "Automatically adjust Daylight Saving Time setting?" pref - "DST in effect/DST not in effect".

And maybe localise the names according to the timezone - BST (British Summer Time), AEDT (Australian Eastern Daylight Time) etc etc.

**Comment by phiw13** [comment]
One possible UI improvement (@gomedia-adi mentioned it in the OP): apply the class `.disabled` to the labels of the row `Daylight Saving Time enabled?` when that is disabled. That will grey-out the text next to the radio controls and make more obvious that the whole thing is disabled  the radio controls themselves should already take the disabled appearance as set by the OS) . 

Also:

> And maybe localise the names according to the timezone - BST (British Summer Time), AEDT (Australian Eastern Daylight Time) etc etc.

I don’t see what the point is. I run TXP in en-gb mostly (the default), and have sites on servers located in Singapore, US, Amsterdam, Japan. The generic `Daylight Saving Time` is just fine.

**Comment by Bloke** [comment]
See https://github.com/textpattern/textpattern/commit/8e2218bdacdba854838e642965b2c416c527cfaa. Labels now dimmed too, which is much more obvious, thanks for the suggestion.

Regarding hiding the entire option, I can see the attraction, but adding an indicator label to the auto_dst setting involves:

* Two new strings, which need translating before final release.
* Potentially altering the theme layout / CSS to accommodate the indicator string. Not sure where'd be best to stick it. Under the radio? Under the label? Alongside the radio?
* Either adding the relevant indicator via jQuery, which requires these strings are added to the page, or
* Adding them via PHP and hiding/showing the strings with jQuery.
* Making the callback difficult for plugin authors as it not only impacts one input control, but two.

As it stands, the radio itself _is_ the indicator. If you set it Auto DST and hit _Save_, the radio will reflect the state of the currently in-force DST setting at your chosen locale. Further, if you visit the page the day before a DST switch it'll be set to one state. If you then visit the prefs page the day after, it will automatically indicate the other state.

If you do wish to hide the radio completely, it's a snip to write a few-line plugin hooking into the is_dst pluggable_ui callback.

**Comment by gomedia-adi** [comment]
Thanks, very happy that "Daylight Saving Time enabled?" is now going to be more informative.
