### ISSUE TITLE
"Images" page and text values

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#711]
Please, could you textilize or escape all text fields (the "alternative text" and the "caption" fields).

The better choice could be textilize: for other languages than English, the use of these datas within javascript usage cause some troubles (with non escaped values into code surrounded with simple quotes).

**Comment by rwetzlmayr** [comment]
Would you mind giving a more specific example of which "alternate text" causes your problems and in which situation you experience these problems (e.g. when you use a certain `txp:` tag, or when you visit a certain panel in the admin side, or when you run some third-party plugin et cetera)?

**Comment by cara-tm** [comment]
Here is an example:

L'Allée.

**Comment by rwetzlmayr** [comment]
> and in which situation you experience these problems

**Comment by cara-tm** [comment]
Oops...
Sorry Robert: it seems that this behaviour concerns the smd_thumbnail plugin and its <txp:smd_thumbnail_info item="title" /> tag.

**Comment by Bloke** [comment]
Are you using the latest bleeding edge code from the [smd_thumbnail github page](https://github.com/Bloke/smd_thumbnail)?

**Comment by cara-tm** [comment]
No...
Thank you lot, Stef ;)
