### ISSUE TITLE
Select active prefs tab from URL

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#716]
The [`$selected`](https://github.com/textpattern/textpattern/blob/master/textpattern/include/txp_prefs.php#L195) portion of `txp_prefs.php` isn't working as expected (ummm, at all) since the switch over to using localStorage for tracking panes. This makes it tricky to check the URL and override the localStorage value if we were to introduce, say, a `selected` URL param for the Prefs panel, or somehow harness its `#fragment`.

@bloatware Any ideas on ways to make the localStorage value overridable by the URL? All the code that deals with checking `$last_event` and setting the selected tab in `txp_prefs.php` is redundant isn't it? Or is it there for fallback in case localStorage is not available?

[see here](http://forum.textpattern.com/viewtopic.php?pid=299985#p299985) for relevant discussion.

**Comment by bloatware** [comment]
@Bloke Yes, the server storage is now mainly for initial value + fallback purpose. We could make the `localStorage` value overridable, though there is no evidence that this by-URL selection worked before the `local Storage` introduction. I will try to submit a patch for testing.

**Comment by bloatware** [comment]
Please test #717 . Usage: `textpattern/index.php?event=prefs#prefs_group_my_plugin` or `textpattern/index.php?event=prefs#something inside_prefs_group_my_plugin`

**Comment by bloatware** [comment]
In 4.7, if we decide to keep `localStorage`, the server could send a `selectedTab` value only when needed to override the locally stored one. We could actually do it in 4.6, but users would then loose their 4.5 pane settings.

**Comment by NicolasGraph** [comment]
@bloatware Thanks for the patch!

**Comment by Bloke** [comment]
Seems to work fine, thanks. Firefox is a bit picky if you try and edit a URL that already has a hash -- it doesn't see it as a new page request so you need to force refresh to get it to change the page. But there's nothing that can be done about that: browser quirk or spec limitation, I guess.

**Comment by bloatware** [comment]
I have merged the code into `master`. Selecting active tabs from URL `#hash` seems to work, including for elements "inside" a tab. Should the issue be closed now?
