### ISSUE TITLE
Function tag() can generate invalid markup

### ISSUE THREAD

**Issue by gomedia-adi** [textpattern/textpattern#723]
If an empty tag string is supplied, e.g. 

`echo tag('some text','');`

then the markup generated is:

`<>some text</>`

Would it be better if the function checks that the supplied tag is not empty, so it doesn't try out output dodgy markup?

**Comment by bloatware** [comment]
I agree, it should output just `some text` in this case. Moreover, it should be able to output `<tag></tag>` when the content (but not the tag) is empty, but I'm not sure about the bwc.

**Comment by Bloke** [comment]
+1 for just text not tag, if tag is empty: no b/c concerns here.

Not sure about the other case. There are arguments for either approach. If I supply empty content:

a) don't render the tag at all; or
b) render an empty container pair.

The only ways to deal with this with b/c in mind would be to either offer a flag that defaulted to the current approach, or to introduce a new function (e.g. `tag_wrap()`) which returned the empty container in the absence of content.

**Comment by bloatware** [comment]
Actually, sending `null` as content already outputs empty `<tag></tag>` container, so no modifications are needed here. Let us just fix the empty tag case.

**Comment by Bloke** [comment]
A while after I wrote the above comment I thought, "hey, I wonder if `null` could act as the trigger instead". Seems like we already did that... yay!
