### ISSUE TITLE
Allow AND/OR in WHERE clause of safe_upsert

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#724]
As discussed [here](https://github.com/textpattern/textpattern/pull/722).

**Comment by vanmelick** [comment]
And perhaps make it a bit more atomic by using ON DUPLICATE KEY UPDATE, if possible.

**Comment by bloatware** [comment]
@vanmelick sorry, I don't understand which fields should be updated (and how) on duplicate key. Should be closed by [https://github.com/textpattern/textpattern/commit/efe9925fbf85e6f8773a9165f7f17b426272d2a2](https://github.com/textpattern/textpattern/commit/efe9925fbf85e6f8773a9165f7f17b426272d2a2).

**Comment by Bloke** [comment]
Regarding efe9925, since we're now using mysqli, couldn't we start to migrate to parameterized queries and drop all the doSlash  nonsense?

If nothing else that should give us the ability

**Comment by Bloke** [comment]
Bah, dammed mobile...

That should give us the ability to supply custom sort orders to `sort` attributes. At the moment they get mangled by doSlash.

**Comment by bloatware** [comment]
Not sure you can use functions in prepared statements, they just remove the need for doSlash. Unless I'm wrong, or you mean something else?

**Comment by Bloke** [comment]
Ah, maybe. I haven't looked at it in detail. I presumed a prepared statement could take functions like `ORDER BY FIELD (name, '...', '...', ...)` which we could pass onto tag attributes. Maybe not.

If they can't take functions and we migrate to prepared statements, how would we do core functionality where we use `FIELD`  now? To be honest, I'd love to be able to do it in a more cross-SQL manner because the MySQL specific functions are a barrier to opening up Txp to other databases. Err, I think. Unless, ultimately, a full PDO implementation / ORM wrapper abstracts that away somehow.

**Comment by bloatware** [comment]
I mean, you can not use functions as *attributes*. You can prepare `ORDER BY FIELD (name, ?, ?, ?)` statement, but you'll need to know `name` and the number of attributes in advance, which is very restrictive.

**Comment by Bloke** [comment]
Ah yes, knowing the number of parameters you want to pass a priori is a huge barrier for parameterized queries of this nature! Hadn't thought of that.

It seems it's not possible, as prepared statements can only bind values, not column names. The only hack I can think of is to dynamically create the `ORDER BY FIELD (name, ?, ?, ?, ...)` if we detect that type of construct in a sort attribute, creating the correct number of placeholder question marks and sanitizing each passed value with `doSlash()`. Bit dangerous, but might be doable if we're careful.

**Comment by Bloke** [comment]
And, although off topic, further to my above comment about IN lists...

```
    /**
     * Create a PDO-aware construct suitable for IN clauses.
     *
     * Each PDO param created is composed of a colon, the $prefix and
     * the $key of each each item in the $set.
     *
     * @param array  $set    Tuples for creating the list
     * @param string $prefix Prepend each PDO param with this
     * @return array
     */
    public function makeInList($set, $prefix = 'val')
    {
        $inList = array();
        $params = array();

        foreach ($set as $key => $item) {
            if (is_numeric($key)) {
                $key = str_pad($key, 6, '0', STR_PAD_LEFT);
            }

            $paramName = ':' . $prefix . $key;
            $inList[] = $paramName;
            $params[$paramName] = $item;
        }

        return array($inList, $params);
    }
```

Usage:

```
list($inList, $params) = $helper->makeInList(array(5, 42, 103, 3, 11), 'ids');
$sql = "SELECT * FROM table WHERE id IN (" . ($inList ? implode(',', $inList) : "''") . ")";
...
// prepare($sql)
// bind($params)
// exec();
```

**Comment by bloatware** [comment]
It's more related to #345 now, closing.

**Comment by planeth44** [comment]
Doctrine\DBAL has a nice "parameters conversion" for this type of situation:
http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/data-retrieval-and-manipulation.html#list-of-parameters-conversion
