### ISSUE TITLE
Undefined variable: threshold_type when sort_by is not set

### ISSUE THREAD

**Issue by planeth44** [textpattern/textpattern#726]
Proposed correction in lib/txplib_publish.php
Give a default to the variable  $threshold_type to prevent PHP to throw a general error when no sort attribute is given 

function getNextPrev($id = 0, $threshold = null, $s = '')
{
    $threshold_type = 'raw';

**Comment by bloatware** [comment]
Thanks for the report, should be fixed by 0c313f7.
