### ISSUE TITLE
Translation need fixes

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#727]
In the preference pop help for _Automatically append comments to articles?_…

Here is what the [american version](http://rpc.textpattern.com/help/?item=comments_auto_append&language=en-us) says:

_The majority of the time, you will want this set to ‘No’_ […]

and that's [the french version](http://rpc.textpattern.com/help/?item=comments_auto_append&language=fr-fr):

_La plupart du temps, vous laisserez cette option active_ […]
**The majority of the time, you will keep this otpion active**

**Edit:** Of course, I could help for the translation if I would know what is the correct version.

**Comment by bloatware** [comment]
I'd say, English versions reflect changes in the default 4.5+ article form. Other locales I've tested (`fr-fr`, `de-de`, `es-es`) seem outdated.

**Comment by philwareham** [comment]
Please open an issue here to track this: https://github.com/textpattern/pophelp/issues

**Comment by cara-tm** [comment]
Yeah.
All pops help (which I updated a long time ago due to lot of missing translations) need some changes now. 
May be Nicolas could help me ;)

**Comment by NicolasGraph** [comment]
Sure, I'm moving now but I'll be probably more available in a week or two.

**Comment by philwareham** [comment]
Closing, as this issue is specifically for the pophelp repo not the core.
