### ISSUE TITLE
Variable trim attribute?

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#729]
Related to [this](http://forum.textpattern.com/viewtopic.php?id=36828): 

> The contents of a variable is not trimmed from a white-space, or modified in any other manner. If you want to test the contents against empty, then you will need to make sure that there is no extra white-space

Not so good for readibility when a variable contains tags and contional tags.

Can't we do that?
Here the `trim` attribute works on variable setting only but it can be adapted to work on reading. too. 

```
function variable($atts, $thing = null)
{
    global $variable, $trace;

    extract(lAtts(array(
        'name'  => '',
        'value' => $thing !== null ? parse($thing) : null,
+       'trim'  => 0,
    ), $atts));

    if (empty($name)) {
        trigger_error(gTxt('variable_name_empty'));

        return;
    }

    if (!isset($atts['value']) && is_null($thing)) {
        if (isset($variable[$name])) {
            return $variable[$name];
        } else {
            $trace->log("[<txp:variable>: Unknown variable '$name']");

            return '';
        }
    } else {
-       $variable[$name] = $value;
+       $variable[$name] = $trim ? trim($value) : $value;
    }
}
```

If it is that simple, I can submit a pull request, but I doubt… It would have been done for while, no?

_Code edited for clarity._

**Comment by gomedia-adi** [comment]
Good luck! ... I wanted trim with if_yield but [no way](http://forum.textpattern.com/viewtopic.php?pid=268849#p268849) apparently.

**Comment by NicolasGraph** [comment]
Ok, bad new… I'm not sure that we could have a 100% consistency between tag attributes; some tags have their own needs. Trimming could really avoid ugly code parts and it seems so easy to implement it.

It would be probably more useful for consistency to start cleaning tags like with the [txp:if_field proposal](http://forum.textpattern.com/viewtopic.php?pid=278945#p278945).

**Comment by gomedia-adi** [comment]
Yes, it is a simple thing to implement & would help greatly.  It's a shame to have to resort to plugins to do the basics, but in my toolkit I've got adi_trim if required. 

Have you seen [adi_if_content](http://forum.textpattern.com/viewtopic.php?id=46104)? It's a clever bit of kit that improves on the usual rigamarole:

`<txp:variable>SOME TAGS THAT MAY OR MAY NOT GENERATE CONTENT</txp:variable>`
`<txp:if_variable> ... </txp:if_variable>`

**Comment by Bloke** [comment]
Ruud and Oleg made some fabulous optimisations with the parser in 4.6, which we intend to build upon in later releases. The namespaced attributes that Gocom referenced in the link above are possible to be built into the parser. The question then are:

* what features do we want, i.e. what global attributes make sense for all tags; and
* do we eventually phase out the specific attributes that might be replaced by such globals? A backwards compatibility question.

Dropping the enforced txp: prefix in favour of using a plugin author's own prefix is also doable with only a minor speed penalty. The enhanced readability it offers in templates -- especially if it can be made compatible with the 'else' tag -- offset the speed, imo. Implementing it hit a road bump with regards XML compatibility, but there are ways around that, it just depends on the best approach, which is something we haven't yet decided.

**Comment by NicolasGraph** [comment]
@gomedia-adi; I saw adi_if_content some time ago but forgot it, thanks for the reminder!
@Bloke; thanks, I close the issue for now and I hope to see these fabulous optimisations soon!
