### ISSUE TITLE
Notice "Use of undefined constant Textpattern - assumed 'Textpattern'"

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#731]
In debug mode:

```
Notice "Use of undefined constant Textpattern - assumed 'Textpattern'"
in /Users/username/Sites/_txp-test/textpattern/admin-themes/hive/hive.php at line 76.
textpattern/admin-themes/hive/hive.php:76 adminErrorHandler()
textpattern/lib/txplib_head.php:137 hive_theme->header()
textpattern/include/txp_lang.php:241 pagetop()
textpattern/include/txp_lang.php:319 list_languages()
textpattern/include/txp_lang.php:49 save_language()
textpattern/index.php:211 include()
```

I *think* `$homelink = span(Textpattern);` should be `$homelink = span('Textpattern');`
(with single quote marks around the string). At least that makes the error go away.

Since this commit:
https://github.com/textpattern/textpattern/commit/5ae804c9a7dfae7295476d39be7058f1cf088d84#diff-4b30fba84816878060ba08b11eff1fdbR76

**Comment by philwareham** [comment]
Sorry, my bad! Fixed now, thanks.
