### ISSUE TITLE
Special character issue in db password on install

### ISSUE THREAD

**Issue by dinoact** [textpattern/textpattern#741]
I have a special character (specifically "<"). When I do a fresh install of 4.6 beta 2 the following happens:

1. Can get through screen where I verify db credentials
2. Get to screen where it has me populate config file. I do so with the valid information.
3. It fails to validate. Instead of the "<" in the pass, it needs "amp;lt;". If I change it to that it goes to the next page to set credentials.
4. If I try to set credentials with the pass still with "amp;lt;" it errors out when trying to save. If I set it back to "<" it works.

Seems the issue is on the page that validates the config file is set up correctly.

**Comment by bloatware** [comment]
Thanks for the report. Should be fixed, closing.
