### ISSUE TITLE
RFE: add a “clear search” button to the search form widget.

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#742]
Clearing the search would return the user to the original view – show all entries for a given panel (e.g. show all articles), starting on page 1.

This was discussed in the forums:
http://forum.textpattern.com/viewtopic.php?pid=300090#p300090
(and some previous / next posts)

**Comment by philwareham** [comment]
Agreed, will investigate good solution today.

**Comment by phiw13** [comment]
Thanks for starting to implement this!

1. You should test this with longer language strings, e.g. French: “Effacer la recherche“. (see screen shot below, Safari ~880px wide window) or Spanish (borrar búsqueda) or German (usually quite long). Persian: پاک کردن جستجو

2. instead of your `position: relative` little dance, rely on flex box behaviour:

```
 .txp-search-clear {
margin: auto 0;
}

[dir=ltr] .txp-search-clear { margin-right: 1em; }
[dir=rtl] .txp-search-clear { margin-left: 1em; }
```


![clear-search](https://cloud.githubusercontent.com/assets/8944809/17577790/cfc2508c-5fbc-11e6-92f4-59d6c5cd450f.png)

**Comment by phiw13** [comment]
Possible fixes (semi diff format), assuming no layout changes - starting from narrow screens:

```
/* prevent the flex-items from stretching vertically */
.txp-search {
+  align-items: flex-start;
}

/* keep the 2 buttons together */
+.txp-search .ui-controlgroup { 
+  -webkit-flex-wrap: nowrap;
+  flex-wrap: nowrap;
+}

.txp-search-clear {
+  -webkit-flex: 1 0 auto;
+  flex: 1 0 auto;
+  width: 100%;
+  /* keep some space below the clear link at narrow screens */
+  margin: 0 0 .5em;
}

/* medium sized screens, 2 column layout */
@media (min-width:47em) {
+.txp-search-clear {
+  text-align: right;
+}
+[dir="rtl"] .txp-search-clear {
+ text-align: left;
+}
}

/* larger screens */
@media (min-width: 60em) {
.txp-search-clear {
+  margin: auto 1em;
+  -webkit-flex: 1;
+  flex: 1;
+  width: auto;
}
```

**Comment by philwareham** [comment]
Thanks, will try out some code.

**Comment by philwareham** [comment]
This is done now, closing.
