### ISSUE TITLE
Removal of unused gTxt strings

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#743]
I'm making pophelps for non-English languages, and I've found what appears to be an unused gTxt: `archive_date_case`. There may be more, but this is the first I've found.

There are two (2) references to `archive_date_case` in this repo,  both of which are in the included text files for gTxt translations. Apparently no instances of the `archive_date_case` string in the code at all.

Options:

* remove the `archive_date_case` from the 2x text files
* leave them intact

What to do? Please advise.

**Comment by philwareham** [comment]
Hi, yes there are loads of unused text strings left over from obsolete Textpattern features. I plan a cull of those when we break away from the RPC server at Textpattern 4.7. See here https://github.com/textpattern/textpacks/issues/5
