### ISSUE TITLE
`abbreviation` Textile example/link is missing from Write panel

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#744]
There's an `abbreviation` pophelp for Textile, but it doesn't appear to be called from anywhere. 

There's no `abbreviation` reference in `textpattern/vendors/Textpattern/Textfilter/Textile.php`

Solutions:

* add an example + link in `textpattern/vendors/Textpattern/Textfilter/Textile.php` to utilise existing pophelp (will need language strings)
* zap the `abbreviation.textile` pophelp

I'm inclined to go for the first option of the two. Thoughts?

**Comment by philwareham** [comment]
As the examples in Textfilter help aren't an exhaustive list of Textile formatting, I'd be inclined to zap it. For two reasons:

1. I don't want to add any more translation strings to Textpattern 4.6 (I've already pestered the translators enough recently!).
2. It's one less pophelp doc that we need to maintain and translate.

**Comment by petecooper** [comment]
Actually, yeah - that's a valid point. I'll housekeep the files. Thanks for clarification, @philwareham.

**Comment by philwareham** [comment]
It might be worth culling any other Textile pophelps that aren't in the Textfilter list - for example `table.textile`?

**Comment by petecooper** [comment]
Three more proposals to zap, same background as above: `footnote.textile`, `span.textile` and `table.textile`.

**Comment by petecooper** [comment]
You literally beat me by 5 seconds, you swine.
