### ISSUE TITLE
[UX] Image and thumbnail replacement anomaly

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#745]
There's an anomaly between the routes when an image or thumbnail replacement fails, in this case when the directory is not writable.

STR:

* set images directory to non-writable, confirm via Diagnostics panel
* navigate to the `Edit image` panel in the admin-side (`index.php?event=image&step=image_edit`)
* upload a replacement image - it will fail and display an error
* upload a replacement thumbnail - it will fail, _take you to the image list_, and display an error

The bit about returning to the image list is the snag here. If an image or thumbnail upload fails, there shouldn't be a redirection or return to the image list, it should stay on the `Edit image` panel for the requested image.

**Comment by bloatware** [comment]
Should be closed by the above commit, please check.

**Comment by philwareham** [comment]
@petecooper can you confirm, and close it works as intended. Cheers!

**Comment by petecooper** [comment]
Please hold.

**Comment by petecooper** [comment]
Works for me - thanks, @bloatware!
