### ISSUE TITLE
References to textpattern.net

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#755]
I'm doing a docs shakedown. There's a reference to textpattern.net (wiki) - is it safe to link to http://docs.textpattern.io instead, yet?

**Comment by philwareham** [comment]
It's safe, if a little messy and unfinished. I'm hoping work gets a little quieter in next couple of weeks so I can spare a few hours to get it tidied. It's still better than the wiki though so please link to new docs site from here on.

**Comment by philwareham** [comment]
Still some to do :) I'll amend and then close again.

**Comment by philwareham** [comment]
Done now. Closing.
