### ISSUE TITLE
404 on .com latest download links

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#760]
As outlined in `README.textile`, these links are direct for the 4.6.0 release:

http://textpattern.com/latest.tar.gz
http://textpattern.com/latest.zip

Both currently throwing a 404 error. Previously worked OK with 4.5.7.

(Please close without comment if it's intentional during the release process, wanted to raise it)

**Comment by philwareham** [comment]
That's because I've just changed them to point at the (currently missing) 4.6.0 release. :)
