### ISSUE TITLE
`CONTRIBUTING.textile` needs updating

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#761]
Since we're all about the GitFlow Workflow now (see: http://forum.textpattern.com/viewtopic.php?pid=301282#p301282), the contribution guidelines in `CONTRIBUTING.textile` need an overhaul.

**Comment by Bloke** [comment]
Eeek, how to distil all the junk I wrote into something someone can make sense of...?!

**Comment by petecooper** [comment]
Proposal: ditch the current file content as it's no longer valid, and start to carve out a proper document on the docs site. Point file to doc.

Pros: not release-dependent after it's repointed, can be easily updated as new workflow is adapted.
Cons: extra hop out of code to web, but then committers will be using the web anyway.

**Comment by Bloke** [comment]
That sounds like a plan. Me likeee.

**Comment by Bloke** [comment]
@philwareham / @petecooper Would either of you care to make a start on this, please? I'm not up on how to make new docs in Jekyll so I'd probably screw it up. I don't mind writing the bulk of the document (unless someone else gets there first), I just need a starting point, perhaps with some scaffolding in place.

Also, will we link directly from `CONTRIBUTING.textile` to the new document, or via a `.com` redirect? I'm fine with either.

**Comment by philwareham** [comment]
Sure, I'll do it. I did make a start on changing the installation pages on Jekyll to Markdown and removed the downgrade instructions, but got sidetracked with the Classic theme and haven't committed yet. Will do tomorrow and make a placeholder for contributing doc.

**Comment by philwareham** [comment]
@Bloke I've put a placeholder Markdown file in place for you to fill out https://github.com/textpattern/textpattern.github.io/blob/master/development/contributing.md

I'll check the formatting once you have made progress on it, to check it is consistent with other Markdown files we are producing.

I'll also continue to convert, clean up, and style the rest of the documentation files while I await 4.6.1 release.

**Comment by Bloke** [comment]
Thanks, all. Fixed via https://github.com/textpattern/textpattern/commit/bfcdff97cb61aae555668e514e52a5e511edfb7b
