### ISSUE TITLE
Update script should not fail even if it can not delete obsolete files

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#763]
See [here](http://forum.textpattern.com/viewtopic.php?id=47268)

**Comment by bloatware** [comment]
@Bloke @vanmelick @rwetzlmayr could you take a look at this? The time I grok the update process, we'll be at 5.0

**Comment by Bloke** [comment]
Presumably the shortest path to nirvana here is to `@rmdir` and `@unlink` in `_to_4.6.0.php`. We could also check the return status and try to figure out a way to notify the user (we don't have that ability yet, afaict), but without suppressing errors, it's always gonna [raise an E_WARNING](http://php.net/manual/en/function.unlink.php).

Now that 4.6.0 is out if we retrospectively alter the update script, it's never gonna run again unless people upgrade from an earlier version. Don't really want to have another attempt at unlinking in the `_to_4.6.1.php` file, so maybe it's the best we can hope for, by fixing the behaviour for users who have yet to upgrade.

**Comment by bloatware** [comment]
Would `try/catch` help here? We could also silently ignore the errors and integrate the obsoleted files check into Diagnostics, like we do for `setup`.

**Comment by Bloke** [comment]
Gone with the [simplest option](https://github.com/textpattern/textpattern/commit/4cb72a885113b467328ac7c4c82f97b7350165e1) for now.

I don't know if PHP actually raises an exception for such warnings/errors, so not sure if `try/catch` helps. It might do in PHP 7 as a lot of the warnings and errors have been made catchable.

But even then, we do some of the deletions in a loop so if the first fails, we could report it (if we had a Flash Message system to notify people, which I intend to write), but we won't know if the next operation fails without refactoring the deletion to do it one file at a time, each in its own `try/catch` block.

I like the idea of adding checks for 'the following files should be deleted' and, maybe, 'the following files should be moved from (a) to (b)' (see https://github.com/textpattern/textpattern/commit/1d2d37f1aa37e089c23e44e14916864d1d809cba and https://github.com/textpattern/textpattern/commit/605287ab0080abf9153de1d75eada0ef0084238e) to the Diagnostics panel. Wanna have a go at that?

Not sure how to handle the i18n side of things for the 'files that should have moved' case, as each file could be moved to a different endpoint and we don't really want a new i18n string for each one. We also need to take into account that such files could be optional anyway (especially in the case of the licenses -- people often don't upload them) so the absence of such files in either old or new location isn't a concern to be flagged.

But some vital files we might legitimately move in future (e.g. `textpattern.js`) and may wish to notify people they can remove the old one if it fails to get deleted on upgrade.

**Comment by bloatware** [comment]
Great, thanks @Bloke. I will take a look at Diagnostic, but wouldn't yet (4.6.1) care about the "move" part. We don't (yet) move things programmatically, do we?

**Comment by Bloke** [comment]
Not yet! And given the amount of hassle I've caused trying to just delete a few files, I'm not inclined to try it :-)

**Comment by Bloke** [comment]
[Fixed](https://github.com/textpattern/textpattern/commit/0026905411b0526af5dc069b7e61fd8cea14c08d). So ignore everything I said above regarding notifying people about moving files. We'll only be advising them to delete.

**Comment by bloatware** [comment]
Only who is trying nothing succeeds every time  :-) We could probably supply some `obsolete` files list to be used by Setup and Diagnostics? Not sure what is the best place to store the list: file, code, db? DB has the advantage to be easily modifiable by scripts that can add their own warnings if necessary.

**Comment by Bloke** [comment]
Good idea. If you can find somewhere that makes sense then I vote for them going in the DB too. Uhhh, somewhere...

But the checksums are hard-coded; they need updating whenever we add a @.php@ file that we want tracked by a checksum. So it's no major hardship if the obsoletes need the same treatment, as long as they're in a central location somewhere.

**Comment by bloatware** [comment]
It could be just a txp table where various scripts (update, image/file upload, etc) could write their errors. Or even important warnings (article modified, etc). Kind of history. The difficult part is to keep this table in sync with the reality, i.e. automatically delete corresponding records when an error is gone. I have no clear idea yet and don't want it to delay 4.6.1, so would close this issue and postpone Diagnostics stuff to 4.7.

**Comment by bloatware** [comment]
The issue should be fixed in 4.6.1+, closing.

**Comment by Bloke** [comment]
@bloatware So it's safe to assume that if the containing folder is writable that the file(s) inside are writable -- and hence unlinkable -- too?

**Comment by bloatware** [comment]
They don't have to be writable (in my tests at least), but that needs confirmation. After 4.6.1 release ? :-)

**Comment by Bloke** [comment]
Sure, I just thought write and delete required the same permissions. Maybe not: I'm not very well versed in permissions issues. If you're happy with the code as it is now, then I'm happy.
