### ISSUE TITLE
Migrate *.textile to *.md

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#769]
There appears to be a general shift away from Textile to Markdown on GitHub.

On the grounds that `*.textile` files are largely specific to GitHub, is it safe to make Markdown versions and cull the originals?

If so, please assign me and I'll deal - I could do with some Markdown refresher experience.

**Comment by philwareham** [comment]
Ok, I've moved to Markdown in the other Textpattern project repos but I was holding off doing the main project repo - I can see no release not to though. FYI I'm also stripped my Textile from the pophelp files in due course (in favour of standard HTML (the RPC versions will stay as Textile though for backwards compatibility).

We need to also have discussions about Markdown as a core textfilter as well as Textile (hence why I'm making pophelp independent of a textfilter).

**Comment by petecooper** [comment]
I have a distant memory that it was me that made `README.textile` to pretty it up for GitHub, so it's only fair I have a crack at a revision.

Markdown textfilter: discussion -- new issue or forum?

**Comment by philwareham** [comment]
Cheers. Markdown new issue I think.

**Comment by petecooper** [comment]
OK, the main README is now Markdown in `dev` branch. What else is there to do to convert Textile to Markdown elsewhere in the repo?

The licence files are plain text, the multisite walkthrough is plain text, did I miss anything?

**Comment by philwareham** [comment]
I've converted the admin theme READMEs to plain text too in dev branch so I think I'll close this now, thanks!
