### ISSUE TITLE
txp:if_article_image Returns True on Category Page/View

### ISSUE THREAD

**Issue by craigerskine** [textpattern/textpattern#771]
On pre 4.6.0 sites <txp:if_article_image> only returned true on a page/view where there was an article image present... so individual_article pages... which makes sense.

4.6.0 now returns every article image when in a category view... which IMO it should not.

I have a site where a mast background image shows on individual article pages but on category pages it shows a default image. I used to just do this via a simple form call once in my page:

    <txp:if_article_image>
      <txp:variable name="mast-img">/i/f1200x460/images/
        <txp:images>
          <txp:image_info type="id" />
          <txp:image_info type="ext" />
        </txp:images>
      </txp:variable>
      <txp:else />
      <txp:variable name="mast-img">/i/f1200x460/img/placeholder.jpg</txp:variable>
    </txp:if_article_image>
  <txp:variable name="mast-img" />

Now I have to do this or rewrite my entire page logic:

    <txp:if_individual_article>
      <txp:if_article_image>
        <txp:variable name="mast-img">/i/f1200x460/images/
          <txp:images>
            <txp:image_info type="id" />
            <txp:image_info type="ext" />
          </txp:images>
        </txp:variable>
        <txp:else />
        <txp:variable name="mast-img">/i/f1200x460/img/placeholder.jpg</txp:variable>
      </txp:if_article_image>
      <txp:else />
      <txp:variable name="mast-img">/i/f1200x460/img/placeholder.jpg</txp:variable>
    </txp:if_individual_article>
    <txp:variable name="mast-img" />

Is the new functionality of if_article_image tag a feature or a bug? I do not see anything in the 4.6.0 release notes talking about changes to the functionality of if_article_image. Or maybe now category views have changed? Or is there something else going on?

**Comment by bloatware** [comment]
Thank you for the report. Sorry, my bad, it's a bug that will be patched in 4.6.1. As temporary fix you can edit `textpattern/publish/taghandlers.php` file, replacing
```
    return parse($thing, $thisarticle['article_image']);
```
with
```
    return parse($thing, !empty($thisarticle['article_image']));
```
on line 3137.

**Comment by bloatware** [comment]
Should be fixed by https://github.com/textpattern/textpattern/pull/773.

**Comment by craigerskine** [comment]
Ahh. Cool, thanks for the info.
