### ISSUE TITLE
Save weirdness on the Preferences Panel, but only when using the keyboard.

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#778]
STR (using the keyboard only!)

1. load the Prefs panel, take note of which sub panel is active
2. switch to another sub panel
3. modify a pref (e.g. a radio button)
4. press Return / Enter (this triggers the submit action)
5. observe which sub panel is active

The preference _is_ saved OK, but the sub panel in step 5 above is *not* the sub panel which was activated in step 2 and modified in step 3. Instead you return to the sub panel in step 1. If the same set of actions is performed using the mouse (*clicking* the Save button) , after step 4, you still have the  sub panel activated in step 2 as the active sub panel

IOW using the keyboard, the “remember last active sub panel” does’t happen. I guess because that action is triggered @onclick@ ?

(seen with both Safari 10 and Firefox dev edition, TXP 4.6 and 4.7.0-dev)

**Comment by bloatware** [comment]
Thanks for the report, should be [fixed](https://github.com/textpattern/textpattern/commit/05c662e54ed14a32503dbf0ea48d657d97da7857).

**Comment by phiw13** [comment]
Yup, does what it says. Now the correct panel is saved. Thanks.
