### ISSUE TITLE
atom and rss creating incorrect ihu links

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#786]
[See forum thread](http://forum.textpattern.com/viewtopic.php?pid=301767#p301767) for original report.

STR:

1) Edit `config.php` and add `define('ihu', '//images.example.org/');` to it.
2) Create an article that contains at least one image displayed to the visitor.
3) Visit `example.org/atom` and View Source.
4) Behold links to the image are of the form `http://example.org//images.example.org/images/42.jpg` and the image is not rendered.

I suspect this has been broken for some time and I think the `replace_relative_urls()` function in `txplib_misc.php` is to blame. Anyone got any regex-fu to fix it?

**Comment by bloatware** [comment]
Adding `(?!/)` negative lookahead at the end of the regex pattern should suffice. Want me to do it?

**Comment by Bloke** [comment]
Yes please! "Negative lookahead" is a foreign language to me ;-)

**Comment by bloatware** [comment]
Ok, will do! There is also positive lookbehind...

**Comment by bloatware** [comment]
Please test if [this](https://github.com/textpattern/textpattern/commit/43b8e6d637aacf8458537499b232973cf712e5f3) fixes it.

**Comment by Bloke** [comment]
Works for me. Nice one, Sir.
