### ISSUE TITLE
Merge `CONTRIBUTING.textile` into `README.md`?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#791]
`CONTRIBUTING.textile` is a heading and one line of text. It'd be a good fit for `README.md` now it's a hyperlink.

Anything I'm missing by doing this?

**Comment by Bloke** [comment]
You're right, go for it. One less file.

**Comment by petecooper** [comment]
Into `dev` branch, @Bloke?

**Comment by Bloke** [comment]
Might as well do it in `maint-4.6.1` and then merge to `dev`. It's not a breaking change, so no need to leave the file lying around longer than necessary.

**Comment by Bloke** [comment]
Addendum: I'm probably not going to use any 'delete file' code to remove it. Learned my lesson!

**Comment by philwareham** [comment]
The @dev@ branch README has changed to Markdown format, the 4.6.x branch still uses Textile, so I'd say this amend should be done in @dev@. Then you can either keep the Textile README in 4.6.x and amend that, or change it to use the Markdown file too. Up to you.

**Comment by Bloke** [comment]
Good call. Fine by me either way.

**Comment by philwareham** [comment]
Done.
