### ISSUE TITLE
Hide checksums.txt by default

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#796]
While there are many ways to determine which version of Txp is running on a server, should we close one simple mechanism: make `checksums.txt` inaccessible to the outside world? All it would involve is:

```
<Files checksums.txt> 
deny from all 
</Files>
```

added to `textpattern/.htaccess`. Diagnostics still runs fine because it reads the file directly. This change just makes one less essential file exposed to prying eyes. Overkill? Useful?

**Comment by bloatware** [comment]
Actually, would allowing just `index.php`, `textpattern.[js|css]` and `admin-themes` folder work?

**Comment by makss** [comment]
Maybe allow only `index.php` and static files?
```
order deny,allow
deny from all

<Files ~ "\.(js|css|svg|png|jpg|gif|ico)$">
        allow from all
</Files>

<Files ~ "^(index\.php|)$">
        allow from all
</Files>
```

Or it is possible use mod_rewrite for this.

**Comment by rwetzlmayr** [comment]
> Actually, would allowing just `index.php`, `textpattern.[js|css]` and `admin-themes` folder work?

No. Consider to add at least `css.php`.

**Comment by makss** [comment]
`css.php`  deprecated in 4.2.0 (2009-08-28) "This file is here for backwards compatibility."

It has been seven years in Textpattern's been a lot of changes. I do not know how this file can help with backward compatibility. Perhaps it is to remove.

**Comment by rwetzlmayr** [comment]
Wrong planet. Look [here](https://github.com/textpattern/textpattern/blob/dev/css.php).

**Comment by makss** [comment]
I mean `textpattern/css.php`.  [link](https://github.com/textpattern/textpattern/blob/dev/textpattern/css.php)
I fixed my post above.

**Comment by bloatware** [comment]
On second thoughts, we don't know what files plugins will need to access. So generic `deny from all` rules may be too restrictive.

**Comment by Bloke** [comment]
> On second thoughts, we don't know what files plugins will need to access. So generic deny from all rules may be too restrictive.

Yeah, it would break MLP for starters. Well, alright, it's broken anyway but you know what I mean...

**Comment by petecooper** [comment]
Putting my pen tester (white) hat on, there are a bunch of trivial ways a Textpattern site's version number can be determined.

The easiest one for me is `checksums.txt`, then the `<generator uri="http://textpattern.com/" version="x.y.z">` line in the Atom feed, then `README.txt`/`HISTORY.txt` (a lot of people just leave these in place), followed by checking the jQuery version, then follow up with the admin-side theme (which most people don't change) on the login page, and there are probably more.

I'd be inclined to leave as-is, especially if locking it down is going to break stuff.

**Comment by Bloke** [comment]
@petecooper Yeah, I did wonder if it was worth it given the number of other version leaks we have.

The only reason I raised it is because the checksums and the version string in the feed (which we could close) are the only definite indicators, because they are essential for site operation. You _could_ manually change jQuery/jQueryUI version. You _could_ omit README/HISTORY. The admin-side theme might not change much between minor versions, so the only sure-fire way would be to byte-compare the CSS file against the git version -- assuming you're not using a custom theme, as you say.

All these other methods give an indication, but not necessarily a definitive answer. As if it matters to script kiddies anyway, who fire and hope every website runs WordPress. Obfuscation isn't security, after all, hence the speculative nature of the request. If it's of limited value, I'm fine to leave it alone.

**Comment by petecooper** [comment]
I can understand the need to not be too liberal with information, especially if this is as a result of leakage, but historically Textpattern hasn't been that much of a target. Clearly things may change if more eyeballs are diverted here, and security through obscurity is not relevant.

Without giving anything away, if this is a result of a security issue/report then just ignore the above as conjecture.

**Comment by Bloke** [comment]
No security issue, just random musings from my too-oft-random brain. Perhaps we'll revisit this when we run 25% of the Internet on our platform ;-)

**Comment by bloatware** [comment]
Hide it, already ;-)

**Comment by Bloke** [comment]
Closing this, as it's a potential minefield.
