### ISSUE TITLE
Consider adding a few print media rules

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#797]
… mostly to ensure that contents prints in full, e.g. workaround a Firefox issue – content clipped due to use of flexbox.

For details, uses cases and history: see [this forum thread](http://forum.textpattern.com/viewtopic.php?id=47329)

Suggestion(s) - add this block at the end of the stylesheet:

```
@media print {
    /* de-flexify those elements for print media - Firefox clips content otherwise */
    body, .txp-layout { display: block; }
    /* avoid repeating `.txp-header` on each printed page */
    .txp-header { position: static; }
    /* try to make the tables fully visible */
    .txp-listtables { overflow: visible; max-width: 100%; }
    /* wrap pre blocks (write panel > html) */
    code[class*=language-], pre[class*=language-] { white-space: prewrap; }
}
```

**Comment by philwareham** [comment]
Or I could isolate the current rules by targeting them at screen and create a new print section - I think I'd prefer that route rather than overriding existing rules.

**Comment by phiw13** [comment]
I don’t particularly care how you do it actually. For my own stylesheet, it is convenient for me to group the needed rules in an `@media print {}` block, and saves me a couple of bytes (42 !, yay climate saving /s). Both will work, I guess.

PS - I commented about that in the forums, but the above rules also ”fix” similar issues as Firefox in MS Edge 14. I haven’t tested any Chromia, not available on my MBA.

**Comment by philwareham** [comment]
Done.
