### ISSUE TITLE
Type, `HISTORY.txt`, line 11

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#809]
https://github.com/textpattern/textpattern/blob/maint-4.6.2/HISTORY.txt

Should be:

```
* Added: Additional Latvian setup translations.
```

i would raise a PR, but there's no `maint-4.6.3` branch right now. If it's coming soon, assign this to me and I'll deal.

**Comment by philwareham** [comment]
We'll just change it in dev I think, unless a 4.6.3 branch is needed in which case we would update there too. 4.6.2 has already been released with that typo in the history.txt.

**Comment by Bloke** [comment]
I concur. Not worth a new release just for a typo in a non-essential file. When we pull HISTORY.txt into dev, we'll fix it then.

**Comment by petecooper** [comment]
Cool. Absolutely not suggesting another release is required, just flagging it for correction.
