### ISSUE TITLE
<txp:canonical /> new tag.

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#830]
According to my observations, it appears that pages with queries like "?pg=x" are generating of "Duplicate Content" for Google's bots.

Please, verifiate and, depending of your results, may be it will be useful to introduice a new tag (i.e. `<txp:canonical />`) in order to generate the canonical metas (which could prevent that annoying behavior and restricts to the parent pages). Consider all needed attributes eventually.

**Comment by philwareham** [comment]
Probably can be fixed with this: https://github.com/textpattern/textpattern-default-theme/commit/1b0c9625cf1d78705c6c843591e9b588f7512811

**Comment by cara-tm** [comment]
Not sure that can be solve things outside of the default TXP theme into only one "archive" page.
Please, re-open this issue.
Another thing to be concider: `<txp:category_list />` generates  URLs with a final slash that is incoherent with the "clean URL" set (with no final slashes).

**Comment by philwareham** [comment]
I don't really understand the issue, isn't that down to how you code your personal templates? Can you give me a usage case?

I don't want to introduce another tag that can already be done with existing tags (especially since `if_*` tags can now be used as single tags).
