### ISSUE TITLE
Drop users to Diagnostics panel on update/install

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#834]
With the proposed changes to bundling languages with Txp from 4.7, propose landing on Diagnostics by default (perhaps a little prettier). With:

* "Welcome to Textpattern version x.y.z" at the top if all went well.
* List of "installation issues" (scraped from upgrade scripts) if anything went sideways.

Then pre-fight checks as now, which highlights the 'remove setup' thing, and any server-level issues that might need addressing.

**Comment by bloatware** [comment]
> Then pre-fight checks as now, which highlights the 'remove setup' thing, and any server-level issues that might need addressing.

Or just delete all junk if possible. I've got a script.

**Comment by phiw13** [comment]
> With the proposed changes to bundling languages with Txp from 4.7, propose landing on Diagnostics by default (perhaps a little prettier).

Yes! And then tell the user to visit the Languages panel for possible updated language(s) strings (unless the update scripts will take care of that in the future?).

**Comment by Bloke** [comment]
@bloatware Yes, removing junk is a good plan. Let's do that.

@phiw13 With the languages all being shipped with the download, I'll see if we can get it to auto-update _all_ languages that you have installed, not just the active one. That's one less hurdle and one less need to visit the Languages panel. After that, with us dropping reliance on the RPC server, we're probably going to drop the 'update' feature since there are very few people that use it between releases. Those that want to can download updated packs from .com or GitHub and install them from file. If we get a flurry of translations after a new major release (instead of during the beta) we'll just issue point releases to catch more translations instead.

**Comment by Bloke** [comment]
> Or just delete all junk if possible. I've got a script.

@bloatware Care to dig this out and apply it to core, if it's not been taken care of already?

At minimum I'd like to try and auto-remove the `setup` dir after setup completes. As long as it silently fails and doesn't trip over, the worst case scenario is that the user is asked to do it when they log in.

When we move the default content out of the `setup` directory to the `themes` directory, there'll be no potential customizations in there (e.g. custom themes or tweaked content) that would be trashed by an auto-delete attempt.

**Comment by bloatware** [comment]
Theoretically it works (line 197 of `txp_diag.php`) on update, but only in final (not dev) versions. I have locally tested it with a temporary dir, it works as expected.

Should we run auto-remove on each diagnostics or only on update?

**Comment by Bloke** [comment]
Didn't spot that it tries to remove the setup directory already. Cool! I think doing it only on update is enough.

Yay! Another issue closed on the path to 4.7.0...
