### ISSUE TITLE
(4.7 dev) txp:if_search_results outputs nothing

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#835]
This is similar to [this forum thread](http://forum.textpattern.com/viewtopic.php?id=47371) with `<txp:if_section>`…

On an absolutely default TXP install, with the default article, search for something (e.g. Textpattern) brings up a search result page with the results for your search term, but something is missing. Under the main page heading “Search results”, a subheading with the text “1 item matching your search request …” (from memory…). That subheading is not there.

Similarly, when searching for non-existing string (e.g “xxx”), the search result page should show something like “no result found for {search term}”

Both of those are wrapped in a `<txp:if_search_results />` [tag](https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/forms/article.search_results.txp#L4). 

@bloatware ?

**Comment by bloatware** [comment]
Fixed by [https://github.com/textpattern/textpattern/commit/ab2683d73925d1c89fe9c3f83b463746476e614b](https://github.com/textpattern/textpattern/commit/ab2683d73925d1c89fe9c3f83b463746476e614b), thanks!
