### ISSUE TITLE
Article Count Tag

### ISSUE THREAD

**Issue by craigerskine** [textpattern/textpattern#842]
It would be wondrous if you could include a `<txp:article_count />` tag or something similar in the core of TXP to natively output article counts.

Use [mdn_count](http://forum.textpattern.com/viewtopic.php?id=4974) (which is busted now in TXP 4.6x) as a base or at the very least:

`<txp:article_count section="secA,secB" />` = gets count of all articles assigned to section(s)

`<txp:article_count category="catA,catB" />` = gets count of all articles assigned to category(s)

**Thanks you so much for all your work.**

**Comment by bloatware** [comment]
Already done [here](https://github.com/textpattern/textpattern/pull/792), just wait a little :-)

**Comment by craigerskine** [comment]
Thanks for the info. Awesome news!
