### ISSUE TITLE
`HISTORY` and `README` text files - 80 chars max or no?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#850]
This is a trivial thing. Consider it presentational.

There are a couple of text files in the Textpattern root -- `README.txt` and `HISTORY.txt`. One is 80 characters or less trimmed, the other has run-on lines.

Should `HISTORY.txt` be reformatted to 80 characters or less for uniformity?

**Comment by philwareham** [comment]
Ok, makes sense
