### ISSUE TITLE
Expiring articles and SEO

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#853]
Bots are crawling everything on the web, even articles with an expired date.
Fortunately, the "robots" meta tag offers a good and  simple solution to tell such a situation (no more article available) to bots:
`<meta name="robots" content="unavailable_after:25-Aug-2007 15:00:00 EST">`.

Because it's pretty difficult to integrate this into the core, maybe a 301 header would be simplier?

or `x-robots-tag`. i.e.

HTTP/1.1 200 Ok
Date: Tue, 25 May 2010 21:42:43 GMT
...
X-Robots-Tags: unavailable_after:25-Aug-2007 15:00:00 EST
...

**Comment by bloatware** [comment]
Would not this work?
```
<txp:if_expires>
  <meta name="robots" content="unavailable_after:<txp:expires gmt format="..." />">
</txp:if_expires>
```

**Comment by cara-tm** [comment]
Sure!

So maybe this could be added into the default template within the "archive" page:

    <meta name="generator" content="Textpattern CMS">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="noindex, follow, noodp, noydir">
    
    <txp:if_expires><meta name="robots" content="unavailable_after:<txp:expires gmt="1" format="%Y-%m-%d %T %Z" />"></txp:if_expires>

**Comment by philwareham** [comment]
Done. Note that your example was not RFC 850 compliant, I've amended in the commit.

**Comment by cara-tm** [comment]
Fine. Thank you Phil ;)
