### ISSUE TITLE
Last SEO improvement for the upcoming 4.7.0 version

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#854]
Depending of the (new and beautiful) official documention: "The page_title tag is a single tag that displays text depending on the context it is used. Its primary purpose is for outputting information suitable for the HTML <title> tag." (Source: http://docs.textpattern.io/tags/page_title)

The first occurence into the meta title is very important for Bots. Current tag always shows the site name first. Sequence into the `<txp:page_title />` tag could be improved a bit by putting the site name at the end.

So, we'll get:

* on a the home page: `Site Name`
* on a section page: `Articles · Site Name`
* on a category page: `Current Category · Site Name`
* on an individual article page: `Article's Title · Site Name`
* on a search results page: `Search results for: {q} · Site Name`

**Comment by cara-tm** [comment]
Thanks lot, Phil ;)

**Comment by cara-tm** [comment]
Sorry Phil. It seems that `$pg` (page number) isn't rendering due to the "elseif" conditioning imbrication (context never occurs).
Please, could you verify?

**Comment by philwareham** [comment]
I didn't create those conditional statements in the code, so I don't know where (or if) that context is displayed. @Bloke might know.

**Comment by Bloke** [comment]
It does exactly the same as before. The trouble is, it has never (to my knowledge) output the page number on article lists in Sections. It only does it on the front page (default).

There's an opportunity here to fix this, and to also output the page number on category and author list pages.

**Comment by cara-tm** [comment]
Yep ;)

**Comment by Bloke** [comment]
OK, I'll reopen this and look into it.

**Comment by cara-tm** [comment]
Thank you, Stef.

**Comment by cara-tm** [comment]
For your further investigations, note that the stupid query "?pg=999" displays the current page without any articles.

**Comment by Bloke** [comment]
Is this better? In order to not change the `gTxt()` string for `page` I've added the page number separated by `$separator` which is kind of odd, but the alternative is uglier / more work as it involves introducing a new string.

**Comment by cara-tm** [comment]
Yep. Cool ;)

**Comment by cara-tm** [comment]
Another thing I want to submit to your expertise: what about the use of double quotes into the meta description fields?

The rendering (TXP 4.7.0-dev) is:

`<meta name="description" content="My description here from "articles" or "categories" comes here">`

See the Ghost CMS consideration here: https://github.com/TryGhost/Ghost/issues/4328

**Comment by Bloke** [comment]
@cara-tm As far as I can see from the code, if you use `escape="html"` in the tag (which is the default anyway), double quotes in the output are escaped. What am I missing?

**Comment by cara-tm** [comment]
Oups!
Yes, you're right (sorry). It's perfect.

Another thing with the keywords field into the article page (Main menu: "Content" -> "Write"):
Writing some keywords with simple quotes puts an escaped backslashe before this sign. Each time I save, other backslashes are added.

With the latest TXP 4.6.2, I got:

`some keywords, l\\'article, l\\'escalier`

**Comment by Bloke** [comment]
> Writing some keywords with simple quotes puts an escaped backslashe before this sign. 

@cara-tm Hmmm, I can't replicate this, but my environment is 4.7.0-dev so it might be something that's been fixed. I'll spin up a 4.6.2 at some point when I test MLP some more, but in the meantime @philwareham / @bloatware is this repeatable on 4.6.2 for you guys?

**Comment by phiw13** [comment]
I can’t reproduce that on a local 4.6.2 test install. Using the `'`, aka apostrophe, in the keyword field works fine, the output is less than ideal on the front-end (`l&#039;escalier`), but that is a different matter (using `<txp:meta_keywords />`). IOW, no weird escaping.

**Comment by cara-tm** [comment]
Sorry. No more problems detected.
Maybe it was the fact noticed with the previous beta versions of the latest 4.6.2.
