### ISSUE TITLE
RFE: Consider allowing the uploading of SVG images to the Images panel

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#856]
See the discussion in this [forum thread](http://forum.textpattern.com/viewtopic.php?id=47446).

some notes from the thread:

* this should optional. OFF by default
* considerations regarding thumbnail creation (Imagemagic?) and grid display on the image list panel

**Comment by Bloke** [comment]
Judging from [this post](https://www.bjornjohansen.no/svg-in-wordpress) among others, and the fact that WP ditched support, citing:

> SVG file security isn’t some obscure bug. There’s multiple, well known SVG vulnerabilities. It isn’t a theory, an obscurity, or an unknown. There are well over 8,000 logged CVE’s that have to do with all sorts of fun and obscure SVG file security vulnerabilities.

I think we should drop this for now. If we can overcome the security, performance and thumbnailing issues, and deem it important enough to add, then we may resurrect the idea in future. But until then, don't hold your breath, sorry.
