### ISSUE TITLE
Some UX amendments

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#860]
Some UX amendments:

1.° The "View" link within the "Write" page could gain to have a `target="_blank"` attribute (or, with a javascript process) in order to open the article into a new window. Come back to the interface can be difficult for some people;

2.° Add a javascript feature in order to reorganized the blocks ("Date", "Statuses" and so on) within the "Write" page in order to offer the user capacities to organize its environement as he wants and keep the positions saved (the same in the "Prefs" tab);

3.° The "Save" button within the "Page" and "Form" tabs could be placed at the top before the "Duplicate" link, not at the bottom, for harmonisation with the "Write" page.

**Comment by philwareham** [comment]
1. Just done :)
2. Already planned for a future version of Textpattern when custom fields have been refactored.
3. Won't be done has been (discussed before and rejected).

Closing for now.

**Comment by cara-tm** [comment]
Yeah!
;)
