### ISSUE TITLE
Custom type forms

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#861]
@Devs: Did you project to introduce custom forms (and whatever)?

With some plugins (smd_privileges) we could associate privileges to back-office users in order to display only things of their interests.

**Comment by Bloke** [comment]
Custom Form types have been on the list for ages, but I never found a suitable workflow. Please suggest how you might like the feature to work, with regards:

* Selecting an existing Form type vs specifying a new one (Permanent text box on-screen? A 'new type' item on the select list, which displays a text box? A link that displays a text box when clicked? A popup modal box? Manipulate the type box directly via jQuery? Something else?) See [this thread](http://forum.textpattern.com/viewtopic.php?pid=296851#p296851) and [this one](http://forum.textpattern.com/viewtopic.php?pid=296874#p296874) for more info.
* What happens with multi-edit if you want to move all the selected Forms to a new type that has not yet been created.
* The tagbuilder.
* etc.

If you have mockup ideas for how it should work, please submit them.

With regards assigning privileges to the different Form types, well, that's not possible right now.

**Comment by petecooper** [comment]
@Bloke - is there any change in form types being assigned to privilege tiers? I'm assuming not, but I am not 100% sure.

**Comment by Bloke** [comment]
No change in this release. Nobody's suggested a suitable workflow yet for custom types, and I haven't found one that works to my satisfaction yet despite some low-level tinkering over the years. Will certainly consider this next release if anyone comes up with any good UX ideas.

**Comment by petecooper** [comment]
Thanks @Bloke - throw a 4.8 or 4.9 label on it, please and thanks?

**Comment by Bloke** [comment]
This is done now, right? With short codes and custom form types defined in prefs, you can create any groupings you like.

**Comment by petecooper** [comment]
That's my interpretation, yes.

**Comment by Bloke** [comment]
Cool. Closing.
