### ISSUE TITLE
CSS comments for the Hive Themes

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#862]
3 little CSS comments for the "Hive" & "Hive Neutral" Themes:

1.° Vertically align "select" field with others input fields (see how it renders into the "Forms" page):

    .txp-form-field {
            margin: 1em 0;
    /* new property */
    vertical-align: top;
    }

2.° Add white space arround content into select lists to show part of characters below the base line (i.e. "g" letters):

    select {
    /* new property */
    padding-top: 0.155em;
    
        padding-right:1.30769230769231em;
        background:url(...)
    }

3.° With your new very subtile effect around the fixed select list at the bottom of the pages, why do not change the black shadow below the header by a white one (this is just a visual choice)?

    .txp-header {
    box-shadow: 0 1em 1em #fff;
    }

**Comment by petecooper** [comment]
@cara-tm If this relates to the admin theme CSS, you should open an issue in its repository here: https://github.com/textpattern/textpattern-default-theme

**Comment by cara-tm** [comment]
Ok. Thank you Pete (sorry for my error. May be you can delete this issue).

**Comment by philwareham** [comment]
Actually this is admin theme related, so issue needs to be raised [here](https://github.com/philwareham/textpattern-hive-admin-theme/issues) - Textpattern core doesn't own these admin themes.
