### ISSUE TITLE
Add attribute for author_email tag

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#864]
Playing with JSON-LD in order to offer @philwareham some proposals for the default theme, the `<txp:author_email />` tag need a `format="link"` attribute to retrieve `mailto:` prefix from the author's email address (character entities).
W3C specification use `"email": "email address"` for a "Person" graph.
So `<txp:author_email link="1" format="link" />` could retrieve: `mailto:name@example.com` only.

**Comment by philwareham** [comment]
Any issues related to Textpattern default theme need to be raised [here](https://github.com/textpattern/textpattern-default-theme/issues), thanks. Closing in core.

**Comment by cara-tm** [comment]
Sorry @Phil but it seems that this issue is about a Textpattern tag not about the default theme ;)

**Comment by philwareham** [comment]
Sorry, my mistake. Reopened.

**Comment by cara-tm** [comment]
💃

**Comment by Bloke** [comment]
I don't understand. If you need a raw email address output, do examples such as the following not suffice?

```
<a href="mailto:<txp:author_email />">Mail the author</a>
<meta name="contact" content="<txp:author_email />">
```

You can use the `html` attribute to output the raw address without any character encoding.

**Comment by philwareham** [comment]
Seems to be covered by existing tag behaviour. Closing.

**Comment by cara-tm** [comment]
You are right.

With the `<txp:author_email />` I get the email address (i.e. `name@example.com`) while the W3C JSON-LD documentation, followed by Google, calls this: `mailto:name@example.com`

See more, "email" address as part of a "Person" graph here: http://jsonld.com/person/

So, maybe this issue could be reopen.

**Comment by Bloke** [comment]
Is this not viable in JSON-LD?

```
<script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "Person",
      "colleague": [
        "http://www.example.com/JohnColleague.html",
        "http://www.example.com/JameColleague.html"
      ],
      "email": "mailto:<txp:author_email />",
      "image": "janedoe.jpg",
      ...
```

**Comment by cara-tm** [comment]
Yep. Sure Stef (I knew what you were going to say :D).

The question is: Is there any problem displaying the email addresses in plain text (against spamming bots)?
I noticed that the tag can display an encrypted version of any email address which is a very usuful feature!

**Comment by Bloke** [comment]
Obfuscating the email address doesn't necessarily make it any harder for bots to scrape, but yes if you specify `link="1"` in the tag it will obfuscate the output. Note it encodes both the `mailto:` and the email address. If you want just the email address obfuscated (and not the `mailto` portion) then you're probably out of luck with this tag,

Must admit, I'm not entirely sure now what you want the tag to do!

**Comment by cara-tm** [comment]
Ok. `link="1"` give me the full HTML link tag, which isn't not expected.

Never mind. I get what I want (an obfuscated `mailto:`) with my regex (I didn't find any examples by PHP coders onto the web):

    email: "<txp:php>
	/* Extract the mailto: prefix followed by email address  
	 * (characters entities) encoded from the author_email tag
	 * or wait for a new attribute (format="link") included.
	*/
	preg_match( '/[^(<a href=")].*(?=")/', author_email(array('link'=>'1')), $matches);
	echo $matches[0];
	</txp:php>"

**Comment by Bloke** [comment]
I'm not saying we can't add a `format` attribute. It would certainly bring it in line with other similar tags. I just wasn't sure exactly what problem you were trying to solve by adding it!
