### ISSUE TITLE
Few articles and pagination

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#865]
I just noticed a strange behavior with only 2 articles

Textpattern 4.7.0-dev and the default theme: add a second article, set the `article` tag with a `limit="1"` attribute, click on the "previous" link into the public "achives" page. The second article isn't shown!

@Devs: please, verify before keeping this reporting issue.

**Comment by bloatware** [comment]
Can not reproduce with two articles in a section using "archive" page (though there are more articles in other sections).

**Comment by cara-tm** [comment]
Oleg: It seems to appear with only 2 articles into the database.
Please, could you confirm?

**Comment by bloatware** [comment]
I have tried with 2 articles, still no chance :-)

**Comment by philwareham** [comment]
Can anyone replicate this issue?

**Comment by Bloke** [comment]
Nope.

**Comment by philwareham** [comment]
Can’t reproduce. Closing for now. If reported again we can investigate once more.
