### ISSUE TITLE
A small improvement Discuss tab

### ISSUE THREAD

**Issue by makss** [textpattern/textpattern#866]
In `discuss_list` add column or simple link to search per `parentid`. It will be convenient one-click to select all comments in a single article. All necessary functionality is already there and it works.

Sample link:
`?event=discuss&step=discuss_list&search_method=parent&crit=1`  - where `crit`=`parentid`

Similar functionality is on Articles tab.
Btw there is need to replace link:
`?event=discuss&step=list&search_method=parent&crit=1`
to
`?event=discuss&step=discuss_list&search_method=parent&crit=1`

**Comment by Bloke** [comment]
The search dropdown already includes a 'parent' option. If you clear all checkboxes except 'parent' in the search widget, you can either specify an ID or (part of) an article title to find all related comments.

How would this proposal improve on that? And where would you propose to put this additional UI component? A link in the parent column alongside the current link to the article, which selects all comments with same parent ID?

**Comment by makss** [comment]
Yes, exactly.
Add some icon(with link) in `Parent` column.

![](http://lady.yesnt.com/1/discuss_link.png)
