### ISSUE TITLE
On first visit to the Preferences panel, ui is not ‘tabified’

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#867]
Clear cookies, caches, local storage (*)

1. Visit the Preferences panel, notice that all preference subgroups are visible / open. Jquery-UI has **not** done its magic… (collapse all pref panes except the first one). Check your developper tools: console logs an error (and no local storage data has been set, but that is expected at this point).
2. scroll down the (longish) list (don’t use the navigation links), modify a pref, save.
3. Visit another panel, come back to the Prefs panel. Jquery-UI still doesn’t do any of its magic to ‘tabify’ the panel. Now _click_ one of the links in the nav panel (e.g Admin). The browser scrolls down to desired section (URL is `?event=prefs#prefs_group_admin`). Check your developper tools > Storage tab, notice that there is now entry in the Local Storage. Save (you probably have to scroll back up… eh). The browser window reloads and Jquery-UI has done its job… and the selected tab is remembered.

TXP 4.6 immediately allows Jquery-UI to do its job at step 1 above.

(*) turns out that is not easy to do… particularly in Firefox. You need to open the Developper tools, make sure the “Storage” tab is enabled (in the developper tools prefs), select that tab, select local storage, delete… In Safari there are two options: through the WebInspector, Storage tab or through Preferences > Privacy > Manage website data (but that deletes everything at once, cookies, local storage, cache). For Opera, open the developper tools and go to the Applications tab.

On first visit, Opera / Safari log the following error:

```
Uncaught ReferenceError: selectedTab is not defined
    at Object.fn (textpattern.js:1883)
    at Object.<anonymous> (textpattern.js:873)
    at Function.each (jquery.js:2)
    at Object.init (textpattern.js:870)
    at HTMLDocument.<anonymous> (textpattern.js:2021)
    at j (jquery.js:2)
    at k (jquery.js:2)
```

forum thread: http://forum.textpattern.com/viewtopic.php?id=47474

**Comment by bloatware** [comment]
Just a silly mistype :-) Thanks fro the report, should be fixed now.

**Comment by phiw13** [comment]
Yup, JS error gone, Jquery UI does its magic as it should. Works fine in both Safari and Firefox (only browsers I have at hand atm). 
Fixed by [this](https://github.com/textpattern/textpattern/commit/fece00a16af09578eac9634804cc2013550ed891) commit.
