### ISSUE TITLE
article_custom and meta_keywords

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#869]
TXP 4.7.0-dev.
Calling a form with article_custom: the content of the `<txp:meta_keywords format="" />` tag do not display anything.

Is it expected?
I get the result with the help of `<txp:custom_field name="keywords" />` instead (and the deprecated `<txp:keywords />` works).

**Comment by bloatware** [comment]
This is kind of intended (and same for `<txp:meta_author />`), since the purpose of these tags is to generate HTML `<meta ... />`, so they shouldn't be used in list environments. But then why deprecate `<txp:keywords />`?

**Comment by philwareham** [comment]
@bloatware The documentation shows that the tag should be able to be used outside of a meta context, see here: http://docs.textpattern.io/tags/meta_keywords (and that is why the original keywords tag was removed, as it duplicated this function).

**Comment by bloatware** [comment]
@philwareham ok, but it looks (in the code) like the tag is populated only in the individual article context. I may be wrong, but @cara-tm seems to confirm...

**Comment by Bloke** [comment]
Oooh, you're right. Keywords are only populated in individual article context, as derived from [the url](https://github.com/textpattern/textpattern/blob/dev/textpattern/publish.php#L507). So, yep, they won't show up with the `txp:meta_keywords` tag in list context.

That's an oversight, but how to fix the `meta_keywords` tag to do it...? Presumably just an `else` branch that does similar functionality to the original `keywords` tag, grabbing the keywords from `$thisarticle` if `$id_keywords` is unset?

**Comment by bloatware** [comment]
I'd say yes, but are multiple `<meta name="keywords" />` desirable seo-wise? If not, with `format="meta"` we should still output nothing in list content. This also concerns `<txp:meta_author />` tag.

**Comment by Bloke** [comment]
Good point. What are the purpose of keywords in the Textpattern article model, if not for SEO? I know that, traditionally, some people and plugins have (ab)used them for tagging, so maybe there's a historical reason for people using them in article bodies. But from a practical viewpoint, you shouldn't have keywords on landing pages, so what Txp does is arguably "correct".

**Comment by philwareham** [comment]
In my opinion, we should still allow keywords in a list context if it's an easy thing to code. If a user wants to display keywords in this context we should let them really - regardless of any preconceived ideas of how they would use this functionality.

**Comment by Bloke** [comment]
I agree.

**Comment by bloatware** [comment]
I was not following the discussion at the moment of `<txp:meta_keywords />` introduction and don't understand why `<txp:keywords format="meta" />` was not an option. Anyway, maybe just rehab `<txp:keywords />` now?

**Comment by cara-tm** [comment]
I agree with Phil for list context support: I'm currently using it to create some sitemaps with TXP tags.

**Comment by phiw13** [comment]
@bloatware, @Bloke 

If you bring back the `<txp:keywords />` tag, please make sure that it also supports the `separator=""` attribute (added to `<txp:meta_keywords />` following [this thread](http://forum.textpattern.com/viewtopic.php?id=45792).

**Comment by bloatware** [comment]
Why not `break`, for more flexibility and consistency?

**Comment by phiw13** [comment]
> Why not `break`, for more flexibility and consistency?

In *addition* to `separator`? OK. 

The advantage of `separator` is that you can add actual *content* (e.g. a comma), where as, as far as I understand it, `break` only outputs HTML tags.

The point being that those search tools or scrapper tools (referred to in that forum thread I linked above) look at the DOM to find a comma separated list of keywords (both as `meta` of in the `body`).

**Comment by bloatware** [comment]
> `break` only outputs HTML tags

No, `break=", "` works too.

**Comment by phiw13** [comment]
> No, break=", " works too.

Oh. The works indeed, in a very quick & basic test; and it seems to work OK with other (separator) characters, like a Japanese comma (`、`). Well I learned something today.

–––
So what is the plan then?

**Comment by bloatware** [comment]
FWIW, `break` works as HTML tag only for fully alphanumeric (plus underscore) values.

> So what is the plan then?

Well, I would add `wraptag` and `break` to `<txp:keywords />` and deprecate `<txp:meta_keywords />` (and other `meta_`) in favor of
```
<txp:evaluate>
<meta name="keywords" content="<txp:keywords />" />
</txp:evaluate>
```

**Comment by phiw13** [comment]
> Well, I would add wraptag and break to <txp:keywords /> and deprecate <txp:meta_keywords />

Hmm, I’m not really clear what this shuffle is needed. You gonna have to fix `<txp:keywords />` so that the output is useful inside the `<body />` of a page, including the option to use something else as separator than the default (western) comma. Because that is one of the reasons `<txp:meta_keywords />` came to be, see the forum thread I linked to earlier.

**Comment by Bloke** [comment]
> deprecate <txp:meta_keywords /> (and other meta_)

Eh? Like `meta_description` and `meta_author`? I think in 4.6, we were trying to align all this metadata that is used in an HTML header context so it's more consistent. The fact you may elect to use some of it in a body context is immaterial. It's still metadata that you're trying to use elsewhere.

Let's take stock of what tags we have:

* meta_description: Render `<meta>` tag or raw description associated with the article/category/section.
* meta_author: Render `<meta>` tag or raw author name/realname from the associated article. But (currently) ONLY in an individual article context.
* meta_keywords: Render `<meta>` tag or raw list of article keywords, with optional custom separator. But (currently) ONLY in individual article context.
* author: Output the author name of the article, optionally linked to a landing page of articles by that author.
* if_description: Does the article, section or category have a meta description?
* if_author: Does the given author name match the author of the current content type (article, image, file).
* if_article_author: Does the article author match the one given as tag attribute?
* if_keywords: Does the article have the given (or any) keywords associated with it?

Arguably a lot of overlap! Perhaps there's an opportunity to be more clever here?

**Comment by bloatware** [comment]
> I think in 4.6, we were trying to align all this metadata that is used in an HTML header context so it's more consistent.

I don't see how we could ever embrace all possible metadata, given that

> The HTML `<meta>` element represents any metadata information that cannot be represented by one of the other HTML meta-related elements (`<base>`, `<link>`, `<script>`, `<style>` or `<title>`).

Though `author`, `description` and `keywords` are the most commonly used meta names atm, other `name` values (`robots`, `revised`, `tags`) are totally valid and can become standard one day.

**Comment by Bloke** [comment]
True. The only way to future proof it is to introduce: `<txp:meta type="author|description|keywords|robots|tags|..." />`.

But that means standard attribute across all these types, which may or may not be desirable. `separator` (or `break`) for description or robots probably doesn't make sense.

**Comment by bloatware** [comment]
We can already permit any kind of meta info:
```
<meta name="robots" content="<txp:custom_field name='robots' />" />
```
The only problem is that `content` can be empty, producing a useless `meta`. But in this case
```
<txp:evaluate>
<meta name="robots" content="<txp:custom_field name='robots' />" />
</txp:evaluate>
```
outputs nothing.

In 4.8, I suggest that every custom field db definition include a separator (possibly empty). For `keywords` that would be comma, for example. If we wanted to output cf values with different separator (say, ` | `), it would suffice to call `<txp:custom_field name='keywords' break=' | ' />`

**Comment by philwareham** [comment]
I'm all for reducing the number of tags in Textpattern (without compromising functionality), so if possible lets make a start on that.

Am I right in thinking `<txp:evaluate>` can provide the same results as all those current `<txp:if_* />` tags?

**Comment by bloatware** [comment]
> Am I right in thinking <txp:evaluate> can provide the same results as all those current <txp:if_* /> tags?

Not all, but some of them:
```
<txp:evaluate test>
  <txp:excerpt />
<txp:else />
  Section <a href="/subdirname/index.php?s=<txp:section />"><txp:section /></a>
</txp:evaluate>
```
replaces
```
<txp:if_excerpt>
  <txp:excerpt />
<txp:else />
  Section <a href="/subdirname/index.php?s=<txp:section />"><txp:section /></a>
</txp:if_excerpt>
```
Or, with a slightly different syntax:
```
<txp:evaluate query='<txp:article_id />=33'>
	<p><txp:title /></p>
</txp:evaluate>
```
can replace
```
<txp:if_article_id id="33">
	<p><txp:title /></p>
</txp:if_article_id>
```

**Comment by phiw13** [comment]
On the flip side `<txp:if_article_id id="33">` is much easier on the eyes. Code readability matters too.

**Comment by bloatware** [comment]
Sure, and `<txp:evaluate />` can not totally replace all `if_` tags anyway. What *could* be done to reduce the number of tags is to replace `<txp:if_article_id/author/etc />` with a generic and easily extensible `<txp:if_article field="id/author/etc" />`.

The main point is though: don't introduce new tags just to spare few keystrokes if you can easily amend the existing ones.

**Comment by Bloke** [comment]
> The main point is though: don't introduce new tags just to spare few keystrokes if you can easily amend the existing ones.

+1

**Comment by phiw13** [comment]
> What could be done to reduce the number of tags is to replace <txp:if_article_id/author/etc /> with a generic and easily extendable <txp:if_article field="id/author/etc" />.

Oh, sure, if there is some consolidation possible, that is certainly worth a look.

> The main point is though: don't introduce new tags just to spare few keystrokes if you can easily amend the existing ones.

Indeed.

**Comment by bloatware** [comment]
I have temporarily removed the deprecation notice and added `wraptag/break/class` attributes to `<txp:keywords />`. Does this close the issue?

**Comment by johnstephens** [comment]
I just want to make sure I'm not missing something here.

@bloatware says `break=", "` works as a surrogate for the meta_keywords attribute `separator=", "`.

But in my tests, `break` ignores the trailing space, and `separator` doesn't. So if I want to present the keywords as a human-readable comma-separated list, I have to wrap the keywords-tag output in a str_replace function, transforming `,` to `, `.

Is this intended? Is this consistent with the Textpattern team's testing?

**Comment by bloatware** [comment]
@johnstephens which txp version are you testing? Works fine in 4.7 for me.

**Comment by johnstephens** [comment]
@bloatware, I'm using 4.6.2. Apart from removing the deprecation warning, was the tag deliberately changed since then?

**Comment by bloatware** [comment]
> @bloatware says break=", " works as a surrogate for the meta_keywords attribute separator=", "

is valid for 4.7. In 4.6 `<txp:keywords />` is deprecated and has no `break` attribute.

**Comment by johnstephens** [comment]
Thank you. I see now that [txp:keywords _never_ had attributes before 4.6][wiki].

[wiki]: https://web.archive.org/web/20160325034443/http://www.textpattern.net/wiki/index.php?title=keywords
