### ISSUE TITLE
Styles for the admin-side preview

### ISSUE THREAD

**Issue by funtoosh** [textpattern/textpattern#873]
Feature request: add styles for the entry preview in _» Content » Write_ to the submenu in _» Presentation » Styles._ Thus one could easily modify basic styling, such as `font-family` or headline formatting and allow the user to preview in style.

**Comment by philwareham** [comment]
Can't the author already preview in style properly by clicking the 'View' link in Write page for an article that has been saved at least once (as a draft or whatever)?

**Comment by funtoosh** [comment]
In my experience, a lot of authors find it difficult to use the View link and to then switch between authoring and previewing. Using the entry preview tab seems to be easier, as it doesn't take you out of your authoring interface.

**Comment by funtoosh** [comment]
I just saw that there's an advanced option to define custom admin styles in config.php, cool! That just about solves it for me.
`define('admin_custom_css', 'your_custom_rules.css');`
