### ISSUE TITLE
Save/publish button incorrect on new article

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#877]
The Save/Publish button text on the Write panel only changes when the Status field is altered. It is not set correctly on first load. STR:

- Set _Preferences->Publish->Default publishing status_ to 'Draft'.
- Visit Write panel. Button text is 'Publish'.
- Select a different Status, then select Draft again. Button text is now 'Save'.

'Save' should be the button text on page load if the default status is not a publicly viewable resource.

**Comment by bloatware** [comment]
Oops, it has closed itself just by a mention, please reopen if necessary.

**Comment by phiw13** [comment]
@bloatware – your patch seems to work well. I tested both “draft” and “pending” status; both display “Save” as one would expect (and after a a save, changing the status to “live” updates the button to “Publish” correctly).
