### ISSUE TITLE
Remember which form/page/style you were last editing

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#879]
When you edit a form or page or style, then go to another panel, then back again - it would be better UX if the last item you were working on is the default when you return.

i.e. if I was working on a form called 'blah' and then saved it, went to write some article content, then returned to the form panel - it would be good if I could straight away continue working on 'blah' instead of how it always returns to the default form.

**Comment by Bloke** [comment]
That would indeed be cool, with `default` (or whatever you chose to be default in the case of Pages and Stylesheets) as the default choice.

localStorage to the rescue again?

**Comment by philwareham** [comment]
Well yes, `default` as the default choice until you start working on a different form. Then the latest edited form would be the default, if you see what I mean.

**Comment by bloatware** [comment]
Yes, that would be nice indeed. I think cookies suit better here, since localStorage normally acts only after the page (with the default form) is loaded. And the forms are loaded one per request.

**Comment by bloatware** [comment]
[Done](https://github.com/textpattern/textpattern/commit/2136eba2eaff7bfa6bd33463a82e53af9d511cf2) for the forms, please test before extending to other events.

**Comment by philwareham** [comment]
Tested and works as intended for me - thanks very much!

**Comment by phiw13** [comment]
Seems to hold fine here too. Nice little improvement, thanks.

**Comment by philwareham** [comment]
All looks good to me, I've tested fairly extensively and not found any problems. Closing now - thanks Oleg.
