### ISSUE TITLE
tiny minor issue with classes on the File panel

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#880]
The `date` column on the File panel list is currently using the`txp-list-col-description` class. Wouldn’t it be more consistent to use the `txp-list-col-created date` classes (similar to e.g. Images panel)?

That would actually reflect the content of the column.

**Comment by bloatware** [comment]
Thanks, must be some mistyping. But do we need these classes at all?

**Comment by philwareham** [comment]
Yep, that seems like a typo - I can fix if you wish.

Regarding the `.date` class (and `.category`, `.name` classes) on columns such as...

    <th class="txp-list-col-category category" scope="col"><a href="#">Category</a></th>

...they are fairly redundant to me (my admin themes don't target them. They are just leftovers from older work in the admin side. I guess theme authors could target them if they want to style a date or something, so I left them in place. Up to you guys whether you want to keep or discard.

**Comment by philwareham** [comment]
If you are referring to whether we need the column classes like `.txp-list-col-created` - they were generally how the system was before I took over work on it - I did prefix them a bit better to avoid clashes but they were kept because I assumed that is how the column show/hide widget (that you've just introduced) would target the columns directly.

Again, if that is not the case I'll leave it up to you as to whether you want to keep or discard (I don't target them with any CSS styling).

**Comment by bloatware** [comment]
The column picker only uses `txp-list-col-` classes in `<th />` as a (dirty and fragile) fallback when `data-col` is not set. But if they are needed nowhere else, I would prefer to replace them with `data-col` attributes.

**Comment by philwareham** [comment]
Sure, that sounds fine to me. Might want to also await confirmation from @phiw13 that he's happy with that route too, since he provides invaluable theme and structural suggestions too.

**Comment by bloatware** [comment]
We can keep them atm (I've seen these classes in some plugins too). We just need to decide on some markup for hideable columns and inform plugin authors.

**Comment by phiw13** [comment]
I use some of them in Sandspace theme, mostly to (try to…) control the `max-width` of the columns that contain longer strings of text or thumbnail images (applied to the `<td />`), such as `txp-list-col-title`, or `txp-list-col-description`. Scanning through my stylesheet, I don’t think I uses any other classes than the `.txp-list-col-` ones.

Hmm, I could probably just try to control those `max-width` via the the `[data-col=*]` attribute on the `<th />`. But tables are such a finicky animals. If it doesn’t hurt anybody, I think those `.txp-list-col-` classes could stay.

**Comment by bloatware** [comment]
I actually can not find these `txp-list-col-description` classes, it is `txp-list-col-created date` in my local install. Already fixed?

**Comment by philwareham** [comment]
I couldn't find it either - however in my flat mockups I use for developing the Hive themes it was indeed wrong (maybe Philippe saw it there and assumed it was the same in core)?
