### ISSUE TITLE
function callback_event(): wrong sliced array resulting in data loss

### ISSUE THREAD

**Issue by dotnull** [textpattern/textpattern#881]
Some events (for example article_ui:body) are broken because the content is not passed through the callback and therefor generated content from plugins (for example: attaching html to the body) are overwriting the default content instead of appending to the default.

I found this by testing the glz_custom_fields plugin and attaching a textarea field. These text fields are normally (as of v4.5) appended to the body in the article ui backend, but it deletes the body textfield completely, because param 3 of the callback is empty and contains no html code.

I therefor changed the current line in txplib_misc.php:

`$argv = (count($argv) > 3) ? array_slice($argv, 3) : array();`

to the following:

`$argv = (count($argv) > 3) ? array_slice($argv, 3, NULL, true) : array();`

in function callback_event() which preserves keys... [PHP:array_slice](http://php.net/manual/de/function.array-slice.php)

**Comment by bloatware** [comment]
Sorry, I either don't understand or can't reproduce your issue, a new textarea does not overwrite the body field for me:

![screen shot 2017-02-02 at 13 38 26](https://cloud.githubusercontent.com/assets/11578435/22549715/022a1694-e94d-11e6-8a4b-57367354ce56.png)

**Comment by dotnull** [comment]
I found the bug corresponding to another plugin that returns an empty string without the default string. You can close this issue, thanks!  :)
