### ISSUE TITLE
Textpattern CMS favicon is identical to Textpattern site favicon.

### ISSUE THREAD

**Issue by johnstephens** [textpattern/textpattern#883]
When browsing with multiple tabs open, many browsers I use display the favicon for each site in the tab. This is a great visual cue to distinguish between different tabs even when their titles are not visible, or not enough of the title is visible.

I often use Textpattern with several tabs open to different panels in the CMS, plus several tabs open to Textpattern documentation or forum threads. When using the official forum or official documentation, the favicon showing on those tabs is identical to the favicon used by the CMS, making it hard to rapidly distinguish between CMS browser tabs and those pointing to Textpattern's websites.

I'd suggest using a black-and-white version of the favicon for the CMS, while keeping the color version for the Textpattern sites. Or simply use the site's default favicon stored in the document root.

**Comment by philwareham** [comment]
Also see here http://forum.textpattern.com/viewtopic.php?id=47271
