### ISSUE TITLE
The “Recent community conversations” updates stuck

### ISSUE THREAD

**Issue by bici** [textpattern/textpattern#886]
The “Recent community conversations” corner on .com is stuck on Feb 22 (i.e. since day 1 on .io), BTW. posted for ULI

**Comment by philwareham** [comment]
FYI Issue created in wrong repo - but fixed in [correct repo](https://github.com/textpattern/textpattern-com-website). Thanks!

**Comment by bici** [comment]
sorry. a newbie error
