### ISSUE TITLE
txp:meta_keywords tag outputs nothing in an article form displayed on a list page—unlike txp:keywords tag

### ISSUE THREAD

**Issue by johnstephens** [textpattern/textpattern#888]
Steps to reproduce:

1. Create a fresh installation of Textpattern 4.6.2.
2. Add some keywords to the the "Welcome to your site". For example: "here, are, some, keywords".
3.   Edit the article_listing form, adding this:
  
    <txp:if_keywords>
        <dl>
            <dt>Keywords</dt>
            <dd>txp:meta_keywords - <txp:meta_keywords format="" separator=","/></dd>
            <dd>txp:keywords - <txp:keywords/></dd>
        </dl>
    </txp:if_keywords>
4. Load the archive page at /articles/.

Here's what I get:

> Keywords
> txp:meta_keywords -
> txp:keywords - here,are,some,keywords

For now, we can still use the txp:keywords tag, but [the docs say "Deprecated in Textpattern 4.6.0 (use meta_keywords tag instead)"][1].

[1]: https://docs.textpattern.io/tags/keywords

**Comment by Bloke** [comment]
An oversight, sorry. We [undeprecated the tag in 4.7.0](https://github.com/textpattern/textpattern/commit/fa163eae4673f033f602b1e688bb25b833c8039d#diff-6d342f881e1cb5d58520e5faafee233bR3056)! I'm not sure what to do about the docs, as they represent "today's world". Might just axe the 'deprecated' bit.

**Comment by johnstephens** [comment]
Thank you, Stef! Does the keywords tag now have a separator attribute like meta_keywords? That is a *very* useful feature, and saves me from using str_replace or other foolishness.

**Comment by bloatware** [comment]
> Does the keywords tag now have a separator attribute like meta_keywords?

Yes, but it's called and acts like `break`. There is `wraptag` too.

**Comment by johnstephens** [comment]
Thank you, @bloatware! I'm adding the attribute in anticipation.
