### ISSUE TITLE
A recent commit changed permissions for Jquery.js to 755

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#890]
`$ git pull` noted:

> mode change 100644 => 100755 textpattern/vendors/jquery/jquery/jquery.js

Git blames this [commit](https://github.com/textpattern/textpattern/commit/beb10f92aa8318cfc98075b43367e93d25cd1fa9).

cc @philwareham

**Comment by philwareham** [comment]
I think I've fixed this issue now. Please verify.

**Comment by philwareham** [comment]
Just checked. It is fixed. Thanks for the report.

**Comment by phiw13** [comment]
Appears to have the correct permissions now.
