### ISSUE TITLE
Safe Diagnostics copy

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#891]
Any mileage in making a button on the Diagnostics panel that'll copy the contents of the textarea but obfuscate key details like server paths? So the content can just be pasted into a forum post without having to manually do it? Fringe benefit, but perhaps a nice-to-have sometime?

**Comment by petecooper** [comment]
Other options:

* move sensitive stuff to verbose diags
* create 'safe' diagnostics mode and default to it (maybe have this behaviour set via a pref)

**Comment by Bloke** [comment]
> move sensitive stuff to verbose diags

I like this, good call. Maybe the low diags omit path names, or if we need them they could be obfscuated in low diag mode and only visible in high? Not sure of the best route really.

Bottom line we still need to be able to offer assistance if someone wants to PM full details, but the paths themselves are not necessarily useful to be published in public. We could appropach it in a number of ways.

If anyone fancies putting a PR together, by all means go for it.

**Comment by petecooper** [comment]
@Bloke -- what do you consider sensitive/key diagnostic info? First block of default diagnostics:

```
Textpattern version: 4.6.2 (8412e32468526e075446b881d13bd9ce)
Last update: 1970-01-01 00:00:00/2017-07-16 16:00:01
Document root: /var/www/vhosts/textpattern.co/release-demo/live
$path_to_site: /var/www/vhosts/textpattern.co/release-demo/live
Textpattern path: /var/www/vhosts/textpattern.co/release-demo/live/textpattern
Article URL pattern: section_id_title
Temporary directory path: /tmp
Site URL: release-demo.eu.textpattern.co
PHP version: 7.0.18-0ubuntu0.16.04.1
GD Graphics Library: 2.1.1; supported formats: GIF, JPG, PNG.
Server TZ: Europe/Berlin
Server local time: 2017-07-16 20:53:38
Daylight Saving Time enabled?: 0
Automatically adjust Daylight Saving Time setting?: 0
Time zone (GMT offset in seconds):  (-25200)
MySQL: 5.6.22-71.0
Database server time: 2017-07-16 20:53:38
Database server time offset: 1 s
Database server timezone: SYSTEM
Database session timezone: SYSTEM
Locale: en_GB.UTF-8
Server: Apache/2.4.18 (Ubuntu)
Apache version: Apache/2.4.18 (Ubuntu)
PHP server API: apache2handler
RFC 2616 headers: 
Server OS: Linux 4.4.0-83-generic
Admin-side theme: hive 4.6.2
```

My 2c:

```
Document root: /var/www/vhosts/textpattern.co/release-demo/live
$path_to_site: /var/www/vhosts/textpattern.co/release-demo/live
Textpattern path: /var/www/vhosts/textpattern.co/release-demo/live/textpattern
Site URL: release-demo.eu.textpattern.co
```

The other items excluding the 4 lines above should be reasonably safe in isolation, but situations where the forum profile includes a reference (or link) to their site, we're still going to have that same problem.

Devil's advocate: would moving the sensitive info to full-fat diags be sufficient? Conversely, with the volume of diagnostics posts in the forum, is this a problem that needs resolving?

Aside (and tagging @philwareham because reasons): since jQuery is loaded on the admin-side, would something Flash-free like [clipboard.js](https://github.com/zenorocha/clipboard.js/) be worth integrating as a diagnostics copy-paste workflow aid?

**Comment by vanmelick** [comment]
On 16/07/17 21:03, Pete Cooper wrote:
> |Document root: /var/www/vhosts/textpattern.co/release-demo/live 
> $path_to_site: /var/www/vhosts/textpattern.co/release-demo/live 
> Textpattern path: 
> /var/www/vhosts/textpattern.co/release-demo/live/textpattern Site URL: 
> release-demo.eu.textpattern.co|

The first three: if that is sensitive information, your server isn't set 
up correctly and you're waiting for an accident to happen anyway. 
Security by obscurity only leads people to believe they are more secure 
when in fact it prevents them from fixing a potential security problem 
(if any).
The last one should rarely be a problem. If it is, people usually 
obfuscate it themselves.

Regards,
--Ruud

**Comment by petecooper** [comment]
Hi @vanmelick -- the domain-in-the-path route is exactly how many shared (cheap) hosting accounts work, though, hence my reasons for including them. Where shared hosting includes >1 website hosting allowance, they're typically identified by the domain name, and this info leaks out.

I don't know the attack vector size or risk involved for diagnostics where `/textpattern/setup` still exists and the domain is shown on the same chunk of text. In isolation, either are acceptable…but together they're not ideal. That said, if all the info is bundled into verbose diagnostics and those are posted, then there's not much that can be done to mitigate that, aside from a speedy mod edit.

**Comment by vanmelick** [comment]
On 16/07/17 21:48, Pete Cooper wrote:
> I don't know the attack vector size or risk involved for diagnostics 
> where |/textpattern/setup| still exists and the domain is shown on the 
> same chunk of text. In isolation, either are acceptable…but together 
> they're not ideal. That said, if all the info is bundled into verbose 
> diagnostics and those are posted, then there's not much that can be 
> done to mitigate that, aside from a speedy mod edit. 

I'm not sure either about the risk of having those setup files around, 
but shouldn't we instead attempt to remove the /textpattern/setup files 
after the setup is completed and only if that isn't possible, hide those 
details in (full) diagnostics.

--Ruud

**Comment by phiw13** [comment]
@vanmelick 

>  attempt to remove the /textpattern/setup files

Ruud, there is already an attempt to delete `setup` post install, see [here](https://github.com/textpattern/textpattern/issues/834#issuecomment-315059039).

**Comment by philwareham** [comment]
I assume this issue is now resolved via latest commits and can be closed?

**Comment by Bloke** [comment]
Yeah, kind of. Its approach favours the "completely hide rows with path names" rather than "obfuscate the data" so it may be something we revisit in future to swap out the real paths with `/path/to/...` instead. But it's fine for now.
