### ISSUE TITLE
Date formats in Languages panel

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#895]
(Using Textpattern version: 4.7.0-dev (e79396e23e136ed4d35114fee64dd7b8))

Language panel has a column for RPC language pack and local language pack. The date format for RPC language pack is fixed: `%d %b %Y %X`. The date format for the local language pack appears to use the site's archive date preference (see attached screenshot).

As reliance on RPC is reduced with future releases, the local language packs date stamp should either follow the fixed format for uniformity (and smooth UX transition), or it should be made clear that the archive date format is also applied to the language pack.

I can see the advantages of both (not helpful, I know), but the format for front-side dates may not be relevant for admin-side dates, so I'm erring on the side of the fixed format.

![google chromescreensnapz003](https://cloud.githubusercontent.com/assets/226578/24838821/7f3527c2-1d47-11e7-8f65-131653401c19.png)

**Comment by Bloke** [comment]
Good catch. You're right, we should set a fixed date format. If we choose YYYY-MM-DD it's ugly so I guess we stick with what we have for RPC right now: DD MMM YYYY HH:II:SS. Even though it's more 'British', it fits with our en-gb default/fallback. And using the month name instead of digits means there's less likelihood of mixing up days/months with US/UK format confusion.

Acceptable, you think?

**Comment by phiw13** [comment]
+1 on DD MMM YYYY HH:II:SS. That is friendly for *any* culture.

I never know what 03/04/17 means.

(mines say `Sep 21, 05:03 pm` due to my pref settings (which I actually always override when outputting dates). What year?

**Comment by philwareham** [comment]
I'm fine with the en-gb fixed date here too.

Not necessarily for here, but going forward it would be nice if the date format input fields changed order depending on if US or other lang set for the site user pref we now have.

**Comment by petecooper** [comment]
+1 on DD MMM YYYY HH:MM:SS for this issue.

**Comment by vanmelick** [comment]
On 09/04/17 23:53, Stef Dawson wrote:
>
> Good catch. You're right, we should set a fixed date format. If we 
> choose YYYY-MM-DD it's ugly so I guess we stick with what we have for 
> RPC right now: DD MMM YYYY HH:II:SS. Even though it's more 'British', 
> it fits with our en-gb default/fallback. And using the month name 
> instead of digits means there's less likelihood of mixing up 
> days/months with US/UK format confusion.
>

If this is a date that needs to be parsed or sorted, please use ISO date 
formats.
For display purposes only, personally I prefer ISO as well, because it's 
the most neutral option, but I'd settle for something that can't be 
misintepreted.

--Ruud

**Comment by Bloke** [comment]
Actually, this might not even need fixing. The Languages panel in 4.7.0 is going to be a grid and the date isn't even displayed any more. See `languages-inclusion` branch for details.

**Comment by petecooper** [comment]
Ah, even better -- no date displayed, no issue. I'll close.
