### ISSUE TITLE
Support for nginx web server

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#897]
Background:
https://forum.textpattern.io/viewtopic.php?id=47754
https://en.wikipedia.org/wiki/Nginx

Nginx is consistently gaining traction in web server market share and has recently passed 33.3%, according to W3Techs:

https://w3techs.com/blog/entry/nginx_reaches_33_3_percent_web_server_market_share_while_apache_falls_below_50_percent

While some of this increase can be attributed to its use as a reverse proxy or similar in front of an existing Apache httpd server, anecdotally I see nginx appearing more as a web server option in hosting control panels.

To that end, nginx should be considered as a supported web server for Textpattern. The linked thread at the start of this post provides some background discussion for some of the steps required for adding nginx support, though there are likely other factors to consider.

**Comment by petecooper** [comment]
Additional things to consider:

* nginx uses PHP-PFM in place of Apache's `mod_php`

**Comment by petecooper** [comment]
@makss has kindly offered to write a patch: https://forum.textpattern.io/viewtopic.php?pid=305319#p305319

**Comment by philwareham** [comment]
I've tested @makss patch on a local Nginx server install and it seems to work fine in my (limited) testing.

![grab](https://user-images.githubusercontent.com/413665/27801459-1065e914-6016-11e7-8146-641ad87274ca.png)

**Comment by philwareham** [comment]
Merged. Docs issue here: https://github.com/textpattern/textpattern.github.io/issues/76. Closing.

**Comment by petecooper** [comment]
Thanks for the patch @makss, and thanks for the testing @philwareham.

Happy guy here -- good job!
