### ISSUE TITLE
Update to phpass 0.5

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#902]
[phpass 0.5 is available](http://www.openwall.com/lists/announce/2017/05/07/1).

**Comment by philwareham** [comment]
Cheers Robert. I've uploaded the latest version to a new branch https://github.com/textpattern/textpattern/tree/phpass-update

Needs thorough testing before merge.

**Comment by petecooper** [comment]
This can be closed as https://github.com/textpattern/textpattern/tree/phpass-update has been merged and subsequently deleted.
