### ISSUE TITLE
Plugin version numbers not adhering to semver in plugin list

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#906]
Not sure if this is an issue or not - but plugins in my installs that have semver numbering such as `0.5.0-beta` or `0.8.0` get listed in the plugins panel as `0.5.0.0-be` and `0.8.0.0` respectively. Why's that?

**Comment by Bloke** [comment]
Probably a regex bug or a DB field width issue. Or both. I'll look into it.

**Comment by Bloke** [comment]
Cannot reproduce this, sorry. On 4.7.0 (in fact, 4.6.0+) the version field in the database is `varchar(255)` so you could store a mahoosive version number in there and it'd still render. There's nothing in the plugin panel I can see which would alter the displayed version: it's just output verbatim from the database (after being sanitised).

It looks as if your version field is still 10 chars. Is it? That wouldn't explain the extra `.0` in the second example, but it'd explain the truncated `beta`.

**Comment by philwareham** [comment]
OK, I'll close this for now - but that field is definitely `archer(255)` in my database. Maybe a quirk using either Composer installations or the original database being updated over a number of years from a really old version of Textpattern initially.

I've manually edited the version numbers in the database for now.
