### ISSUE TITLE
Introduces plugin help files rendering

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#908]
As discussed [here](https://forum.textpattern.io/viewtopic.php?id=47833), the fact that the Textpattern uses Textile in restricted mode to parse plugin help files limit ways to style them. I used to apply Textile on compilation to be free to customize my files by adding tabs to avoid a too long page of text but it does not work when plugins are installed via Composer.

Following a @Bloke [recommendation](https://forum.textpattern.io/viewtopic.php?pid=306055#p306055), I worked on a way to style plugin help files on reading. It would have the advantage to simplify the help files creation and would allow to keep a nice design consistency in the future. 

For now, to keep supporting not well strutured files, the script check if the first help element is a `h1` tag and if there are 2 or more `h2` tags — we don’t need one tab… — before to change the layout. Otherwise, everything stays as is. Then, any contents between the `h1` and the first `h2` tag is displayed just under the header; it is usually a plugin description. After that, each `h2` is read as the beginning of a new section which is linked to a tab as for pref groups, and in the end, the Prism related `.language-markup` class is applied on code chunks

You can already try it with plugins such as [ied_plugin_composer](https://github.com/Bloke/ied_plugin_composer) or [smd_article_stats](https://stefdawson.com/sw/plugins/smd_article_stats) — and probably other Stef's plugins (?).

![Plugin help files rendering demo](http://g.recordit.co/qAnkcyC0o5.gif)

I'd be glad to send a pull request — should I? — if you are interested in but before, we should at least rename `.txp-prefs-group` to something more generic. Any idea @philwareham? I already changed some variable names.

Oh… yes, I also had to change the way the local storage works on the plugin tab by using plugin names as data items to keep tracks of each last visited tabs.

---

### Tested plugins

Here are some test results (checked when ok, default rendering otherwise):
- [x] _abl_droploader_
- [x] _adi_article_tab_
- [x] _adi_list_
- [x] _arc_meta_
- [x] _arc_vimeo_ (an existing table of contents would need to be removed as it display a useless tab)
- [ ] _cbe_frontauth_ (contains some styles)
- [x] _com_connect_
- [ ] _cwh_link_to_home_ (does not contain any secondary header/section)
- [ ] _cxc_templates_ (contains some javascript)
- [x] _etc_pagination_
- [ ] _etc_query_ (does not contains any `<h1>` tag + other HTML structure issues)
- [x] _ied_plugin_composer_
- [x] _jcr_export_txp_templates_
- [x] _jcr_file_custom_
- [x] _mem_self_register_
- [x] _mkp_if_amp_
- [ ] _mkp_header_link_ (contains some styles + several `<h1>` tags)
- [ ] _mta_affiliate_ (does not contains any `<h1>` tag + other HTML structure issues)
- [ ] _pat_article_social_ (contains a custom wrapper `<div>`)
- [ ] _pat_body_tweets_ (contains several `<h1>` tags)
- [x] _rah_privileges_
- [x] _smd_article_stats_
- [x] _smd_bio_
- [x] _smd_tags_
- [ ] _wet_plugout_ (does not contain any secondary header/section)
- [x] _yab_review_rating_ (an existing table of contents would need to be removed as it display a useless tab)

Of course I would make my `oui_` plugins work with this rendering feature if it would be merged.

**Comment by NicolasGraph** [comment]
I created a brand new branch [here](https://github.com/NicolasGraph/textpattern/tree/plugin-help-rendering) to store the proposed changes.

**Comment by Bloke** [comment]
@NicolasGraph Can you remember where we got to with this? I remember trying it out and it was really neat but there were a bunch of plugins that made it break. Can't find where I listed them now.

Did you manage to fix the ToC generator to catch those or, at least, fail gracefully?

**Comment by NicolasGraph** [comment]
Sorry @Bloke, my related branch does not exist anymore.
I'm going to take a look at my backups but I'm not sure this survived at my git learning some months ago… Otherwise, I guess I could rewrite it for 4.8.

**Comment by NicolasGraph** [comment]
> I'm going to take a look at my backups […]

Found. I will see how it could be improved later today.

**Comment by NicolasGraph** [comment]
[Here](https://github.com/NicolasGraph/textpattern/tree/plugin-help-rendering) is the new branch I created.

Here is what the code expects to activate the rendering:

```
<div class="txp-layout-textbox"> <!-- From Txp -->

    <h1>Title</h1>

    <p>Optional paragraph</p>

    <h2>First tab/section</h2>

    …

    <h2>Second tab/section</h2>

    … 

</div>
```

Any other case, any `<script>` or `<style>` tag, or any `style` attribute would deactivate the rendering.
Is this too strict?
Here are some test results (checked when activated, default rendering otherwise):
- [ ] abl_droploader (contains more than one paragraph as an introduction)
- [ ] cbe_frontauth (contains some styles)
- [ ] com_connect (contains more than one paragraph as an introduction)
- [ ] cwh_link_to_home (does not contain any secondary header/section)
- [ ] cxc_templates (contains some javascript)
- [ ] etc_pagination (contains more than one paragraph as an introduction)
- [ ] ied_plugin_composer (contains some styles)
- [x] jcr_export_txp_templates
- [x] jcr_file_custom
- [x] mkp_if_amp
- [ ] mkp_header_link (contains some styles)
- [ ] pat_article_social (contains a custom wrapper `div`)
- [ ] rah_privileges (contains more than one paragraph as an introduction)
- [x] smd_bio

It is not glorious but, at least, it does not break anything.
The intro length issue (4 plugins here) could probably be fixed by adding it as a section with its own tab?

**Comment by NicolasGraph** [comment]
Here are some new test results (checked when ok, default rendering otherwise):
- [x] _abl_droploader_
- [ ] _cbe_frontauth_ (contains some styles)
- [x] _com_connect_
- [ ] _cwh_link_to_home_ (does not contain any secondary header/section)
- [ ] _cxc_templates_ (contains some javascript)
- [x] _etc_pagination_
- [x] _ied_plugin_composer_
- [x] _jcr_export_txp_templates_
- [x] _jcr_file_custom_
- [x] _mkp_if_amp_
- [ ] _mkp_header_link_ (contains some styles)
- [ ] _pat_article_social_ (contains a custom wrapper `div`)
- [x] _rah_privileges_
- [x] _smd_bio_

**Comment by NicolasGraph** [comment]
Also, as noticed in [this commit](https://github.com/NicolasGraph/textpattern/commit/b8401f49f6dfdef3552c8f9382ca82feab8ba84d), `gTxt()` does not work. Not sure why. (current items are used for testing and would need to changed before any PR)

**Comment by Bloke** [comment]
In order to render `gTxt()` strings from JavaScript you need to load them onto the page. See `txplib_head.php` and look at the `gTxtScript()` array. Add your entries there and it should work.

**Comment by NicolasGraph** [comment]
Thanks @Bloke, it is working. I use existing strings for now.

**Comment by NicolasGraph** [comment]
FYI, I moved the list of tested plugins in the first post and I updated it.

**Comment by Bloke** [comment]
Nice, thanks. No need to excessively pander to plugins that do stupid things like my smd_bio help text. If a plugin doesn't use a decent structure, all we should do is render it verbatim without TOC / fallback gracefully. So don't go mad trying to cater to them all, just whatever you can within reason is perfect.

It's very nice that you've taken a cross-section of plugins and tried to enhance as many as possible out of the box. As plugins are updated/released, plugin authors (myself included) can and should take advantage of using a more standardised approach to documentation now we have some great built-in styling and handy automatic TOC generation on the way.

**Comment by NicolasGraph** [comment]
> No need to excessively pander to plugins that do stupid things like my smd_bio help text. 

In fact I thought it could be useful in other cases too, that's why I did it.

> As plugins are updated/released, plugin authors (myself included) can and should take advantage of using a more standardised approach to documentation now we have some great built-in styling and handy automatic TOC generation on the way.

Yes, That would be nice.

I'll test few more things and send a PR if you're OK.

**Comment by Bloke** [comment]
Awesome, thanks!
