### ISSUE TITLE
Show article ID on the Write panel

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#911]
Background: https://forum.textpattern.io/viewtopic.php?id=47891

Currently, there is no way to determine the current article's ID from the Write panel contents. Files and images both have their (unique) IDs shown as part of the respective panel UI.

Proposal: add the article's ID details inline in the `<small>` text under the article excerpt.

![re](https://user-images.githubusercontent.com/226578/27820512-d6be6fac-6096-11e7-893b-fa6014354f80.png)

**Comment by Bloke** [comment]
Done in 023af37b.
