### ISSUE TITLE
Use ImageMagick if available

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#913]
If a system has ImageMagick available, we should use it.

e.g. WordPress uses ImageMagick if the PHP module is available, in addition to GD Graphic Library – offering extra functionality (such as PDF thumbnails) and better image manipulation and better image quality/optimisation that ImageMagick has over GD.

This becomes more attractive when coupled with the plans we have for an image grid, see #8 - as we need to batch process existing images into usable thumbnails.

Obviously this should be part of a wider rewrite of the images code. It also opens the door to in-browser editing of images via the images edit panel (those features probably left to a plugin, apart from the basics like rotate).

The CMS can fallback to GD Graphic Library with a reduced feature set if ImageMagick not available.

**Comment by Bloke** [comment]
I concur. So let's scope out which features of ImageMagick we want to use (probably ones that have a direct fallback to GD). We can then test to see if it's available and use it if installed.

Afterwards, we can look to extend the functionality so we can unlock enhanced features (such as batch thumb recreation, maybe) if the library is available.

**Comment by petecooper** [comment]
>So let's scope out which features of ImageMagick we want to use (probably ones that have a direct fallback to GD). We can then test to see if it's available and use it if installed.

I'd respectfully counter this with a preflight suggestion: list the GD functions we use at the moment and see how viable GD/ImageMagick feature parity is first of all, then we'll have a clearer picture of what's involved.

Off the top of my head:

* thumbnail creation
* …erm…

Also, for completeness/r&d (I hold no obvious bias or opinion on the contents): https://imagetragick.com

**Comment by philwareham** [comment]
I have no great feelings either way on GD Graphic Library vs. ImageMagick but we sorely need to update the image manipulation within Textpattern to meet expectations of users in nowadays. It's one of the single-most popular gripes I see when people talk about Textpattern.

I agree we need to list the features available in each library, and see what we currently use, what we can use, and the differences between the two.

**Comment by petecooper** [comment]
Adding this to the equation if we're looking at multiple image processing libraries: http://www.graphicsmagick.org

**Comment by petecooper** [comment]
Adding for completeness, appears to have API compliance with ImageMagick: http://www.graphicsmagick.org

**Comment by petecooper** [comment]
More considerations: ImageMagick appears to have a system-wide library, and an optional [API](https://imagemagick.org/script/api.php) to glue it to PHP. The API is dependent on ImageMagick being installed. I should have a working setup in the coming days if there's any interest in exploratory testing.

**Comment by philwareham** [comment]
Closing this because it's comprehensively covered by https://github.com/textpattern/textpattern/issues/1472
