### ISSUE TITLE
How close to 4.7.0-beta are we?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#917]
So many big things in 4.7.0-dev so far, according to `HISTORY.txt`. This is _fantastic_ news.

How close or far away are we from a beta release, please? I see 28 of 48 issues closed on the 4.7 milestone right now, and I've noticed some housekeeping going on recently.

I'd really appreciate your advice/feedback on the beta situation, please and thank you.

**Comment by philwareham** [comment]
Hi Pete,

A beta wont be available until the Autumn. There are still some big features targeted for 4.7 release that are still being written. Such as theme support (which we have been back unto for a few days now) and language pack handling changes. I've haven't go the roadmap in my hands right now but I'll dig it out later this week and see what's what.

Don't worry though, things are progressing nicely.

**Comment by petecooper** [comment]
Thanks, @philwareham -- hugely helpful.
