### ISSUE TITLE
Do we still need the X-UA-Compatible header ?

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#921]
From what I understand, starting with IE 11 (lowest supported version of IE in Textpattern), document modes are deprecated. The standard HTML5 doctype enables `edge mode` by default. And I think the most recent versions of Edge ignore that header.

Some reading matter on [stackoverflow](https://stackoverflow.com/a/6771584).

I vote for removing it for a (small) performance gain and less cruft.

**Comment by Bloke** [comment]
Based on that information, I say let's get rid of it. @philwareham, does this fit with our browser support policy? Any downsides? Could earlier IE versions trigger quirks mode that cause issues?

**Comment by philwareham** [comment]
@bloke we don't support IE <11 (and nor does [Microsoft](https://www.welivesecurity.com/2016/01/12/microsoft-ends-support-for-old-internet-explorer-versions/)) and the `flexbox` stuff breaks IE10 anyway so I'm happy for X-UA-Compatible code to be deleted.

**Comment by phiw13** [comment]
@Bloke Thanks!
