### ISSUE TITLE
Enable support for WebP images

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#922]
In PHP 5.5 and later, GD graphics library [supports WebP](http://php.net/manual/en/function.imagewebp.php) - so we should allow that image format in the images section.

[ImageMagick has also supported WebP](https://www.imagemagick.org/script/webp.php) since ~2012if/when we allow that image handler in Textpattern (which [I would very much like](https://github.com/textpattern/textpattern/issues/913)).

**Comment by petecooper** [comment]
Addendum: if this is targeted at 4.8, then it's another very good reason to bump minimum PHP version to 5.5 (as per OP) for 4.8.

**Comment by petecooper** [comment]
Microsoft Edge supports WebP from build 17763.
![screen shot 2018-10-06 at 09 48 56](https://user-images.githubusercontent.com/226578/46569448-24b05200-c94d-11e8-9172-55e3bd5aa1dc.png)

**Comment by petecooper** [comment]
And Firefox is set to support it soon: https://www.cnet.com/news/firefox-to-support-googles-webp-image-format-for-a-faster-web/

**Comment by petecooper** [comment]
Diagnostics in `dev` now reports whether GD has WebP support, as of https://github.com/textpattern/textpattern/commit/b3518c8adac561b51e4af4d30104eb8a799036f9.

**Comment by bloatware** [comment]
I have quick-tested a patch, it works, but seemingly only in PHP 7.1.0+ where WebP support in [getimagesize()](http://php.net/manual/en/function.getimagesize.php) function has been added.

**Comment by petecooper** [comment]
WebP support in Firefox 65+: https://www.mozilla.org/en-US/firefox/65.0/releasenotes/

**Comment by petecooper** [comment]
18 months since https://github.com/textpattern/textpattern/issues/922#issuecomment-483404789 and we're now north of 80% browser support:

![Screenshot 2020-10-04 at 12 58 34](https://user-images.githubusercontent.com/226578/95014813-5a25ce00-0641-11eb-94ce-e70fe8610496.png)

**Comment by philwareham** [comment]
Jolly good, thanks. Although our support of WebP isn't based on browser support - rather, if the image libraries we use for image handling allow for WebP manipulation. When we hopefully start using Intervention Image for our library this will become supported.

I'm hoping to talk with @Bloke soon about how we start that process off.

**Comment by petecooper** [comment]
>Although our support of WebP isn't based on browser support - rather, if the image libraries we use for image handling allow for WebP manipulation.

Absolutely. I'm thinking about end users. WebP should be rolled into https://github.com/textpattern/textpattern/issues/1472 really, given its reach.

**Comment by philwareham** [comment]
Just a NTS on WebP (also AVIF). Would be nice if our reimagined images handling could also allow for the image to exist in multiple formats (say, you could have a JPEG, WebP, AVIF, etc.) version of the same image. Possible with the inclusion of a `mime` attribute for the image_info tag that can return `image/jpeg`, `image/webp` and so on.

You could then have better support for advanced `<picture>` tag markup.

**Comment by Bloke** [comment]
Multiple images is a great idea. We should be able to handle that, even with our numbering scheme (if we keep it) because 2.jpg and 2.webp can coexist nicely.

Hard-coding the map of extension => mime type in the code (constants.php?) makes sense, given we know what formats we support in a particular version. Then we can look that up and expose it in image_info. When we support more formats, we can just extend the map.

I know we've locked 4.8.5 but adding a mime type map and looking it up is a trivial change so if we wanted to extend image_info with a 'mime' option today, we could. We wouldn't be able to support multiple images today but it would be a stepping stone. If it's worth it, let me know. If not, 4.9 is fine.

**Comment by petecooper** [comment]
>I know we've locked 4.8.5 but adding a mime type map and looking it up is a trivial change so if we wanted to extend image_info with a 'mime' option today, we could.

+1. Do it. It's good fuel for 4.9.

**Comment by Bloke** [comment]
The only fly is that it'd only be for our currently supported image types, not avif, heic, webp, etc. I tried a branch and our thumb generation in GD chokes on webp, for example, and makes all-black thumbs so we can't support them until we use something else for image manipulation.

**Comment by petecooper** [comment]
Then we should probably leave it for 4.9 and get 4.8 wrapped up, for everyone's sanity.

**Comment by philwareham** [comment]
Yep, agreed. 4.9 work - not 4.8.x.

In the meantime I've emailed you Stef about help I need for a workaround I'm investigating for 4.8.x (involves some `trim` and maybe a hack of the `type="ext"` to turn `.jpg` into just `jpeg`). Plus trimming filenames off of `<txp:image_url />` with a regex somehow. Not the cleanest solution, but a good stopgap.

**Comment by Bloke** [comment]
Fine by me! Let's make 4.9 the Image, SMTP, Plugin, Custom Fields and UI library release :)

**Comment by Bloke** [comment]
Saw your mail, Phil. Mulling it over today.

**Comment by philwareham** [comment]
Cheers Stef. Back on topic: also [JPEG XL](https://jpeg.org/jpegxl/index.html) `.jxl` is on the horizon so it'd be good to get the aforementioned scaffold in place, and then add these newer formats in as (and if) they gain widespread support.

Apparently JPEG XL is better than AVIF but whether either take off is another matter. WebP we can agree is already here to stay (and finally well supported by latest mainstream browsers).

**Comment by philwareham** [comment]
Actually, maybe adding the mime type map in now *would* be good - speaking from a purely selfish point of view. I could at least simplify my work-in-progress <picture> tag markup. Just the current mime types we support would be fine for 4.8.5 (since I need to spit out `image/jpeg`, and `image/png` as part of it).

**Comment by petecooper** [comment]
>Just the current mime types we support would be fine for 4.8.5

This was my thinking, to be fair. No need to get whizzy with the exotic modern stuff.

**Comment by bloatware** [comment]
Okay for adding `.webp` to 4.8.5? I seem to have a working php 7.1.0+ branch, to be tested yet on php < 7.1.0.

**Comment by philwareham** [comment]
WebP is supported in GD Graphics Library in some of the newer PHP versions (but depending on your compiled build, it seems). So yes we can at least provide the mime type. We just can't say for certain the PHP version `x` supports WebP (unless you have a way to detect whether GD supports it per environment).

**Comment by Bloke** [comment]
If you can get it to work, well, why not? I had a devil of a time getting GD to auto-create thumbs when I hacked a branch in for it, but maybe that was because I was using PHP 5.6? It worked for some images, but for others it just auto-created all-black thumbs or made completely trash thumbnails. I was using `imagecreatefromwebp()`

Please test on our minimum spec.

**Comment by bloatware** [comment]
No need to test, it will not work on php<7.1.0, but then users will neither be able to upload `.webp` via txp.

**Comment by philwareham** [comment]
https://www.php.net/manual/en/function.gd-info.php will tell you if WebP is supported in your GD compile. I guess that will help. It's safe to say at PHP >=7.0 was the first time it was stable enough to actually use.

**Comment by bloatware** [comment]
Checks for https://github.com/textpattern/textpattern/issues/922#issuecomment-465777641 are done.

**Comment by Bloke** [comment]
Yes, except in the Images panel we have an 'accept' handler for the file browser that is set to `image/*` that implies we accept [all image formats](http://www.mime-type.net/image/) which is not really the case. Perhaps we should limit this to ones we do actually support? And filter that list further by the capabilities of the server?

**Comment by bloatware** [comment]
Yes, we could. Are we still supporting `.swf`?

**Comment by Bloke** [comment]
Nope, .swf has gone. There is a disconnect currently if you try, for example, to upload a .bmp image. The browser will highlight it and allow you to select it but if you proceed with the upload you get an error: "Only .jpg, .gif or .png file types allowed."

There's an archaic system in class.thumb for specifying what formats are accepted and I had to mod it to support webp, which was a pain.

**Comment by bloatware** [comment]
I've modified it a bit:
```
    $extensions = array(IMAGETYPE_GIF => '.gif', IMAGETYPE_JPEG => '.jpg', IMAGETYPE_PNG => '.png') +
        (defined('IMAGETYPE_WEBP') ? array(IMAGETYPE_WEBP => '.webp') : array());
```
The problem is the hardcoded strings
```
only_graphic_files_allowed="Only .jpg, .gif or .png file types allowed."
```

**Comment by Bloke** [comment]
Ah yes. The strings. Drat. We'll need to alter those to "Only {formats} file types allowed." and build them on the fly. Hmmmm.

And yeah, txplib_admin.php: `get_safe_image_types()`. Yuck!

So how about this in constants.php as the master list, which is overridable by anyone in config.php if they wish?

``` php
if (!defined('TEXTPATTERN_IMAGE_FORMATS')) {
    /**
     * Supported image formats.
     *
     * @since   4.8.5
     * @package Image
     */

    define('TEXTPATTERN_IMAGE_FORMATS', array(
        '.gif'  => 'image/gif',
        '.jpg'  => 'image/jpeg',
        '.jpeg' => 'image/jpeg',
        '.png'  => 'image/png',
    ));
}
```
The issue is we need to do some detection to see if webp is supported, but I don't think that can be simply done when defining constants... or maybe it can? "gd_info()" can get it but it's an array so needs further tests (in a loop?) for determining the supported types. That'd have to be done later, perhaps in `get_safe_image_types()`. Hmmm..

**Comment by Bloke** [comment]
Alternatively we don't make it a constant. Just put all the logic in `get_safe_image_types()` and ensure we use that throughout. That doesn't make it overridable unless we add a callback. That might work.

**Comment by Bloke** [comment]
Actually, I've just checked and `get_safe_image_types()` still mentions .swf even though we don't allow it. I then checked history and we've only deprecated it in 4.7. Guess it's time we ditch it entirely since it's a dead format.

**Comment by philwareham** [comment]
Yep get rid!

**Comment by petecooper** [comment]
Don't we still permit *handling* of existing SWF in 4.8? What are the ramifications of culling it on a patch release?

**Comment by bloatware** [comment]
Okay, it's on demo site in 10 minutes, please test.

**Comment by petecooper** [comment]
>Okay, it's on demo site in 10 minutes, please test.

Image uploading is disabled, I'm currently not comfortable with unsuitable or incriminating images being uploaded and served. Note also it's bleeding edge PHP 8.0.3RC1, would be more suitable to test on minimum system requirements specification.

**Comment by Bloke** [comment]
> Don't we still permit _handling_ of existing SWF in 4.8?

Yes we do. Existing assets should work (although I haven't got any files lying around to test and would have to hack it to allow me to upload them to test anyway!)

> What are the ramifications of culling it on a patch release?

I don't like it. I'd rather ditch it entirely from 4.9. But, y'know, Adobe has pulled support so it's arguably a security measure.

**Comment by bloatware** [comment]
Please admire [.webp tree](https://dev-demo.textpattern.co/dev/articles/welcome-to-textpattern)

**Comment by petecooper** [comment]
>I don't like it. I'd rather ditch it entirely from 4.9.  But, y'know, Adobe has pulled support so it's arguably a security measure.

This is a tricky one. There is still *some* way to run SWF junk in a browser, but it's esoteric and the chances are if someone's using SWF on their sites, they're not clued-in enough to be adopting 4.8.5 anyway.

If we are going to ditch it – and we need to be very careful about this – we need to find a way to handle the current assets with grace, since it's likely a site-breaker if markup stops working (and you know darned well these people won't read the release notes).

I'm in the camp of leaving the image stuff to 4.9, honestly. There's perhaps mileage in getting the commits for @philwareham's points above into `dev` so there's stuff to work with away from a production release.

**Comment by bloatware** [comment]
And Pete should delete https://github.com/textpattern/textpattern/issues/922#issuecomment-781291022

**Comment by petecooper** [comment]
@bloatware – I was waiting until you'd seen it – now done.

**Comment by philwareham** [comment]
I've just uploaded a WebP image in my `dev` local install - all working nicely. Tested in PHP 8.0.1, and 7.1.33 without issue. Created a thumbnail too. Lovely stuff!

**Comment by bloatware** [comment]
Please test in php <7.1 if you can.

**Comment by bloatware** [comment]
I have also restricted thumbnail upload to the image own extension. Otherwise the uploaded thumbnails are unusable.

**Comment by Bloke** [comment]
I'm of the mind that all this should be deferred to 4.9 - even if that support is enabled "today" by moving Oleg's lovely 4.8.5 commit there.

The changes made to class.thumb in c26feff2 are _exactly_ the same as what I did in my tests and - as I say - it worked fine for some images but not others on PHP 5.6. PHP advertised "support" for it - hence webp was allowed to be uploaded - but GD made a dog's breakfast of the thumbnails. Mind you, right now it trashes thumbnails from some transparent PNGs too, so I guess there's no issue!

I'm fine with leaving it in 4.8.5 _IF_ we're happy altering the `only_graphic_files_allowed` lang string to take a dynamic list. It is potentially only a single sweep to remove the hard-coded list and replace it with `{formats}` so myabe not that tough.

**Comment by philwareham** [comment]
> Please test in php <7.1 if you can.

I've tested in PHP 5.6 and 7.0 (upload greyed out, as expected), PHP 7.1, 7.2, 7.3, 7.4, 8.0 all working fine.

**Comment by Bloke** [comment]
Cool! Then if we're going to do this today in 4.8.5, can we expose the mime type of the image in `<txp:image_info type="mime" />`?

**Comment by bloatware** [comment]
I have restored the empty entry after your [comment](https://github.com/textpattern/textpattern/issues/922#issuecomment-781282117), but can't see what it is for.

**Comment by philwareham** [comment]
> Cool! Then if we're going to do this today in 4.8.5 ...

Yes please!

**Comment by Bloke** [comment]
> I have restored the empty entry after your [comment](https://github.com/textpattern/textpattern/issues/922#issuecomment-781282117), but can't see what it is for.

I have no idea either and I can't remember what happened exactly but it was something to do with class.thumb and I remember scratching my head and just putting it back in for a quiet life! We do need to check why it's there and if there are any ramifications for leaving an empty entry. That'll probably come out in the wash when we integrate a better thumbnail library.

**Comment by petecooper** [comment]
>Cool! Then if we're going to do this today in 4.8.5

…then we *must* stop adding stuff, otherwise we're into feature creep territory and that makes me uncomfortable.

Let's get this done, tested and get 4.8.5 out so we can have a virtual wrap party!

**Comment by Bloke** [comment]
Yes. Oooh, one more thing. The new selector will forbid images of extension `.jpeg`, which is kind of annoying. We probably need to add another entry to the `$extensions` array to handle it. *sigh*

**Comment by petecooper** [comment]
>Oooh, one more thing.

![giphy](https://user-images.githubusercontent.com/226578/108357813-dd595200-71e5-11eb-97ba-e6bffa324adc.gif)

**Comment by Bloke** [comment]
Haha. It's a potential regression, so justified :)

**Comment by philwareham** [comment]
@petecooper Yeah, sorry, this is kind of my fault! 😀 Agreed that this (and hopefully the `type="mime"` for `<txp:image_info />`) must be the final changes so we can get 4.8.5 out (albeit nice additions).

Since 4.9 is probably months away I was keen to get some kind of image improvements available.

**Comment by petecooper** [comment]
For my part, I'll add some safe WEBP into the demo site images. It'll help my blood pressure, anyway.

**Comment by bloatware** [comment]
> 
> 
> Yes. Oooh, one more thing. Unless I'm reading the code wrong, the new selector will forbid images of extension `.jpeg`, which is kind of annoying. Do we need to add another entry to the `$extensions` array to handle it?

Oops. We can't (directly), since jpeg has the same type as jpg. Needs some cheat.

**Comment by bloatware** [comment]
We could try to add it as `0 => '.jpeg'`..?

**Comment by bloatware** [comment]
Done in 4.8.5, seems to work. I guess the empty entry was there only to start index by 0.

**Comment by Bloke** [comment]
Nice. Makes sense about the 0. Let's see what happens. I'll do some tests this afternoon on 4.8.5 as a whole.

So, who wants dibs on outputting mime type from the image_info tag and wiring up the `only_graphic_files_allowed` to output a list? I can do it if nobody else wants it, then we can bat it over to Phil to do the lang string tweaks since he seems to have cornered the market in rapid multi-file edits on the strings.

**Comment by bloatware** [comment]
Any taker please do.

**Comment by Bloke** [comment]
Cool, I'll do it now.

**Comment by petecooper** [comment]
OK, we have the makings of WEBP images included in the `dev` branch demo. Firefox (with WEBP support) looks fine:

![dev firefox 85](https://user-images.githubusercontent.com/226578/108366840-b8b6a780-71f0-11eb-97e9-be1eb7d1e7ef.png)

…Safari 14, less pretty:

![dev safari 14](https://user-images.githubusercontent.com/226578/108366875-c2d8a600-71f0-11eb-8106-a2c8e8797bcb.png)

Same user, same images, we will need a fallback for thumbnails correctly created in a WEBP browser and subsequently displayed in a non-WEBP browser.

**Comment by bloatware** [comment]
Aye! You mean, the images themselves are displayed fine in Safari? I've read v14 supports them...

**Comment by Bloke** [comment]
Fallback isn't possible at the moment unless we support multiple thumbs per image or (as planned) can generate them on-the-fly and cache them.

Even then, what do we do? If we standardise on "jpg for thumbs, always" so they display on all browsers, what if people want .webp thumbs? If we always make a .jpg thumb for admin-side use alongside whatever format the file is, then we're wasting disk space. Damned if we do...

**Comment by phiw13** [comment]
> Aye! You mean, the images themselves are displayed fine in Safari? I've read v14 supports them…

webp is only supported in Safari 14 running  in iOS 14.x and macOS 11. Safari 14 running on macOS 10.14 and 10.15 do not support it.

**Comment by philwareham** [comment]
I can see them fine in Safari 14 on macOS 11, so take that as being fine.

Note we are not providing fallback solutions here. Rather, just the _ability_ for users to upload WebP images to the control panel. How they use those images is up to them.

**Comment by bloatware** [comment]
Then I wouldn't care, +1 @philwareham

**Comment by Bloke** [comment]
Spot the difference... 

![SiteWebP](https://user-images.githubusercontent.com/21252/108369056-10eea900-71f3-11eb-84ae-d06f5a4406ca.png)

:)

PHP version: 7.3.18-1+ubuntu16.04.1+deb.sury.org+1
GD Graphics Library: 2.3.0; Supported formats: GIF, JPEG, PNG, WebP.

[Sample image](https://filesamples.com/formats/webp) is the first one in the list there. Anyone else get this behaviour?

**Comment by philwareham** [comment]
Fine in my setup...

<img width="700" alt="Screenshot 2021-02-18 at 14 13 49" src="https://user-images.githubusercontent.com/413665/108369532-96725900-71f3-11eb-97b5-fe0012e04115.png">

**Comment by bloatware** [comment]
Same (fine) for me, but php8

**Comment by Bloke** [comment]
Weird, so what does your diagnostics say is the GD version? Maybe mine is too outdated.

**Comment by bloatware** [comment]
PHP version: 8.0.0
GD Graphics Library: bundled (2.1.0 compatible); Supported formats: GIF, JPEG, PNG, WebP.

**Comment by petecooper** [comment]
>Weird, so what does your diagnostics say is the GD version? Maybe mine is too outdated.

https://stackoverflow.com/questions/59621626/converting-webp-to-jpeg-in-with-php-gd-library

**Comment by Bloke** [comment]
*shrug* This is what I mean by getting weird results. Some thumbs generated fine, others were completely black, and others did this colour shift. Must just be my server, but it's not running anything out of the ordinary. 

Other variables: maybe when downloading them to macOS 10.14.6 which _doesn't_ support WebP it does some mashing of the data. I've installed https://github.com/emin/WebPQuickLook locally, but all that seems to do is throw an error every time I open Finder so I'll need to uninstall that at some point.

Maybe, as Pete's link suggests, when I rebuilt PHP to 7.3 on the server I should have rebuilt GD too independently? They imply the issue lies with LibGD but I'm not sure how to check the version of that offhand. All I know is that my Diagnostics says "GD" is on v.2.30 but whether that related to the "LibGD" versions or not, I don't know.

Baffling.

**Comment by Bloke** [comment]
Good sleuthing, but it makes no difference to my results either. Drat. I seem to recall playing with that transparency code when I first tried this a year or so ago and gave up in the end.

**Comment by philwareham** [comment]
I've tested this now in PHP 7.1.33 upwards, all worked as expected and thumbnails were all correct colouring (using Safari 14 on macOS 11).

Earliest build on my local setup:

```
PHP version: 7.1.33
GD Graphics Library: bundled (2.1.0 compatible); Supported formats: GIF, JPEG, PNG, WebP.
```

**Comment by petecooper** [comment]
>All I know is that my Diagnostics says "GD" (in PHP) is on v.2.3.0 but whether that related to the "LibGD" versions or not, I don't know.

Can you list the EXACT text you see for GD? I have some insight here, with the risk of further inflating a monster thread.

**Comment by bloatware** [comment]
```
GD Version | bundled (2.1.0 compatible)
FreeType Support | enabled
FreeType Linkage | with freetype
FreeType Version | 2.9.1
GIF Read Support | enabled
GIF Create Support | enabled
JPEG Support | enabled
libJPEG Version | 9 compatible
PNG Support | enabled
libPNG Version | 1.6.34
WBMP Support | enabled
XPM Support | enabled
libXpm Version | 30512
XBM Support | enabled
WebP Support | enabled
BMP Support | enabled
TGA Read Support | enabled
```

**Comment by Bloke** [comment]
What I posted above was the exact test. Here it is with more context from Diagnostics:

```
Textpattern version: 4.8.5-dev (77545c6924d1a4733afdfd16b569b2ad)
Last update: 2021-02-18 13:30:12/2021-02-18 13:29:57
Textpattern path: __TXP-ROOT/textpattern
Article URL pattern: section_title
Production status: debug
Temporary directory path: __TXP-ROOT/textpattern/tmp
PHP version: 7.3.18-1+ubuntu16.04.1+deb.sury.org+1
GD Graphics Library: 2.3.0; Supported formats: GIF, JPEG, PNG, WebP.
Server timezone: UTC
Server local time: 2021-02-18 14:11:07
Daylight Saving Time enabled?: 0
Automatically adjust Daylight Saving Time setting?: 1
Time zone (GMT offset in seconds): Europe/London (0)
MySQL: 5.6.47-87.0 (Percona Server (GPL), Release 87.0, Revision 9ad342b) 
```

**Comment by Bloke** [comment]
Aha! But from phpinfo():

```
GD Support | enabled
-- | --
GD headers Version | 2.3.0
GD library Version | 2.1.1
FreeType Support | enabled
FreeType Linkage | with freetype
FreeType Version | 2.6.1
GIF Read Support | enabled
GIF Create Support | enabled
JPEG Support | enabled
libJPEG Version | 8
PNG Support | enabled
libPNG Version | 1.2.54
WBMP Support | enabled
XPM Support | enabled
libXpm Version | 30411
XBM Support | enabled
WebP Support | enabled
```

Therein maybe lies the culprit. Library is outdated.

**Comment by Bloke** [comment]
So that begs the question in 4.9, can we get and show the GD library version in diagnostics too? Might be worth an extra line of code.

**Comment by petecooper** [comment]
@Bloke – check headers in `phpinfo`, might be old.

**Comment by petecooper** [comment]
Regarding 'bundled` vs not, please see https://github.com/textpattern/textpattern/issues/1546#issuecomment-746228266

**Comment by Bloke** [comment]
Okay I think we can safely say this works then, as long as you have a recent build of **GDLib** not just GD. I didn't consciously rebuild my stack `--with-external-gd` I just used apt-get to upgrade it. Lazy :)

**Comment by bloatware** [comment]
Seemingly we enter the second part of transparency treatment with WebP. Code updated in 4.8.5, please retest.

**Comment by Bloke** [comment]
Interesting. Slightly better results (top image) but still a bit... Kermit.

![WebPTransparencyComparison](https://user-images.githubusercontent.com/21252/108374019-69747500-71f8-11eb-80ad-8a8eb3ef9c8c.png)

Let's not waste any more time on this. The culprit is the system GD (runtime) library which differs from the PHP (compiletime) library. I can't find a way in PHP to extract that info from the PHP API to show opn Diagnostics, so we'll live with this anomaly and use phpinfo for diagnostic reasons if it ever crops up on someone else's production system.

**Comment by Bloke** [comment]
Okay, `<txp:image_info/>` tag now outputs `type="mime"` and the language string needs updating:

```
only_graphic_files_allowed => Only {formats} file types allowed.
```

**Comment by Bloke** [comment]
For the record, I just updated my libgd3 (system, runtime) library to 2.3.0 to match the PHP GD library and all is tickety-boo. No more weird green thumbs, yay.

**Comment by philwareham** [comment]
OK, Textpacks updated now, so I'm closing this issue. That was epic! Thanks everyone - great stuff yet again. Happy.

Apologies for the feature creep. I'd like to say it won't happen again, but it probably will 😂 (promise after 4.8.5 though).

**Comment by petecooper** [comment]
> I'd like to say it won't happen again, but it probably will

Oh, it definitely will. Gentle and persistent cajoling is the way to get releases done!
