### ISSUE TITLE
'setup' folder treatment

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#926]
Some considerations about the `setup` folder.

I know it is a good practice and you encourage users to update to the most recent release. IMHO, asking to delete the `setup` folder after installation is quite radical. What about if a user, for some good reasons (plugins compatibilities) wants to re-install its Textpattern version?
May be you could imagine a process to hide this folder in order to keep security, then add a preference option to restaure this `setup` folder integrity?

**Comment by philwareham** [comment]
The setup folder can be manually reinstalled if a user needs to (as long as they reuse the setup folder from the same version to avoid any differences between versions). I believe there are slight security risks by leaving it in place.

**Comment by cara-tm** [comment]
Your right, Phil.
But this is the reason for this consideration: what about if you haven't the original `setup` folder (which is pretty attached to a specific version)?

**Comment by philwareham** [comment]
Every release is available [here](https://github.com/textpattern/textpattern/releases). Maybe we should just document the process somewhere - would that suffice?

**Comment by cara-tm** [comment]
Yep.
(a better and simple alternative)
:D

**Comment by philwareham** [comment]
Closing here - issue opened in documentation site to track this. Cheers!
