### ISSUE TITLE
The usefulness of Ping-o-matic

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#928]
From http://pingomatic.com

> Ping-O-Matic is a service to update different search engines that your blog has updated.

I've been thinking about the integration of Ping-o-matic in core as I'm looking around the admin area on 4.7-dev. At present, there's a yes/no option in the Textpattern administration area to ping Ping-o-matic when an article is posted. This is how it's been for years.

However, there's no (visible) feedback to say whether a ping happened or was successful. There's no option to fine-tune the service settings. There's no indication whether updating a post triggers a subsequent ping to Ping-o-matic. It's a bit of a grey area all round.

There are 19 services listed at Ping-o-matic. This is the current status of each, at the time of writing:

- Weblogs.com – active, mostly (95%+) spam blogs
- Blo.gs – active
- Feed Burner – inactive since 2012
- NewsGator – inactive, domain redirect
- My Yahoo! – active
- PubSub.com – unknown, times out
- Blogdigger – unknown, 404
- Weblogalot – inactive, SEO keyword domain
- News Is Free – active, possible change in scope
- Topic Exchange – inactive, SEO keyword domain
- Google Blog Search – inactive
- Spinn3r – unknown, 404
- SkyGrid – inactive
- Collecta – inactive
- Superfeedr  – active, requires sign up
- Audio.Weblogs – unknown, 404
- RubHub – inactive, SEO keyword domain
- A2B GeoLocation – unknown, 404
- BlogShares – unknown, broken pages

Mostly inactive, broken or unknown status.

Is it time to deprecate/remove the Ping-o-matic functionality from core? One (or more) fewer things to do when a post is published, plus I'm sure some other things I haven't thought of.

**Comment by philwareham** [comment]
I've never interacted with Ping-o-matic so I'd not miss it if it were removed. So that's a yes from me.

**Comment by Bloke** [comment]
It can get the chop as far as I'm concerned.

**Comment by philwareham** [comment]
@Bloke do you want to take ownership of this change? I'd do it but not sure if prefs for this need nullifying in update scripts.

**Comment by Bloke** [comment]
Axe wielded. Closed by commit 951b9b48.
