### ISSUE TITLE
Tables update and poor bandwidth

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#931]
Just to report.

(today's TXP 4.7-dev version with Git synchronisation)

With a poor Internet bandwidth, language update shows a success message even if the corresponding table is not populated:

<img width="945" alt="language-update" src="https://user-images.githubusercontent.com/61045/30057072-9eb1f680-9235-11e7-8004-97cb34ed75bf.png">

**Comment by Bloke** [comment]
If I have my way, this functionality will be disappearing soon. No updates will be possible between version releases from the RPC server. You'll need to download the files to your lang directory first.

**Comment by cara-tm** [comment]
Super cool!
