### ISSUE TITLE
Global `atts` attribute?

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#937]
What is our policy re this one? Its purpose is to insert arbitrary HTML attributes (say, `atts="style='opacity:0.5'"`) into `wraptag`. That's handy, but error-prone. The 4.6.2 core tags do not accept it, but some plugins do, so I have added it to the global attributes in 4.7-dev. Remove or caveat utilitor?

**Comment by Bloke** [comment]
I never even knew (or didn't remember) it did that. It's horrible syntax. I'd be tempted to axe it, unlss you know of some vital plugins that use it, which cannot be refactored any other way.

**Comment by philwareham** [comment]
Yep, I've never know of it or used it. Get rid unless, as Stef says, it's vital to any existing plugins.

**Comment by bloatware** [comment]
No, plugins still can do what they want. Ok, axing.

**Comment by bloatware** [comment]
[Done](https://github.com/textpattern/textpattern/commit/de6a300a25409b1dd44ede60d28b6b5c64fecf3b). `doWrap()` function still accepts `atts` and `breakatts` arguments for plugins to play with.
