### ISSUE TITLE
Themes branch: duplicating a duplicate results in index error

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#945]
### Expected behaviour

When duplicating a theme, the duplicate should be made without error.

### Actual behaviour

The duplicate process throws a `Duplicate entry '{some-page-name}' for key 'name_skin'`.

### Steps to reproduce

* Export the default skin as a copy using the multi-edit tool.
* Note the name of the skin is appended with the date + time of export. This is good.
* Select the checkbox of this exported skin in the Themes list.
* Choose 'Duplicate' from the multi-edit tool and confirm the action.

The problem is due to the limited key length in use on the `name_skin` index. @NicolasGraph what do you think we should do? Increasing the index size is possible but at some point it'll be too large and cause errors. Where would we impose the limit? Other option is to _prepend_ the theme name with something different or put the date+time first, but that's not as friendly.

**Comment by NicolasGraph** [comment]
I can't reproduce on my localhost but I'm going to test with the main _themes_ branch.
Just to be sure: you export a theme as a copy and then duplicate this same theme (the original one), right?

**Comment by NicolasGraph** [comment]
Ok, I get it, no need to export of course, I tried to duplicate a very long theme name and the error message displayed.
One thing which could be done is to alterate the duplication process by providing a name to the copy on duplication. When we would select _Duplicate_ it would display an input to fill the copy name before to submit the multi-edit form. However, in this case, shouldn't we also provide a field for the copy title? Also, it wouldn't be consistent with the article duplication but we already use timestamps vs ID's, so… what do you think?

**Comment by Bloke** [comment]
Any of these options are fine, thanks. Whatever you feel is the most streamlined. Of course, there's always the possibility that someone'll choose the same prefix as an existing theme and if the first 20-odd characters are the same, they'll get the index error. Nothing we can do about that, I guess.

**Comment by NicolasGraph** [comment]
I should be able to fix this issue next week and I will see what I can do to check if the duplication can be proceed without any error.

**Comment by NicolasGraph** [comment]
Ouch! https://github.com/NicolasGraph/textpattern/commit/910961a7a34f60e249d349b05918050320cbb695#commitcomment-24800396

**Comment by NicolasGraph** [comment]
I re-forked the textpattern repo after failing to sync my themes branch and we lost our comments in the previous commit, sorry.

However, I started to add the changes we discussed and here is how it works now…

You can duplicate from the *multi-edit* form or from the *Edit* panel. When the duplication is done from the *Edit* panel, form data changes are used for the copy, otherwise, a suffix is added to the skin name and title.

Now that changes can be made before duplication I would suggest to: A. have the *Duplicate* link at the top (thinking that it is often a good practice to duplicate first and then make changes) but stay on the *Edit* panel after duplication to edit the copy, or B. have the *Duplicate* link at the bottom;

If we keep it at the top, should I add a `Create a new theme` link before the `Duplicate` link like for other panels?

**Comment by NicolasGraph** [comment]
As I said in our ghost discussion I kept in the skin package pattern used in rah_flat and oui_flat. It imports files with names no longer than 63 chars only but it also restrict them by ignoring the names beginning with any other character than `[a-z]` and do not allow uppercases at all.

The thing is that Txp allows to create these kind of pages/forms/styles.

I could remove this pattern but I guess @gocom has a good reason to do that; does anyone know more about the filesystem and what we should or should not allow?

**Comment by NicolasGraph** [comment]
Skin package recent changes are not ready yet, I will try to come back next week.
Have a good weekend.

**Comment by Bloke** [comment]
PHP restricts its function/class names to those rules. Maybe rah_flat does some clever stuff under the hood with registering callbacks or something that use the theme name? Either way, it's not a bad convention as it also means folder names are consistent. I'd keep it.

**Comment by NicolasGraph** [comment]
Yes, anyway skin directory names are not displayed in the import from if they are not useable as is but the problem is for pages/forms/styles. They could be created with uppercases in the admin, as for now they could also be exported, but not (re-)imported afterwards because of this regex.

**Comment by Bloke** [comment]
Right, gotcha. People could use uppercase/lowercase, spaces, hyphens, or all manner of weird characters in Page/Form/Stylesheet names. I think the only ones outlawed are angle brackets, ampersands, quotes and apostrophes. Things like square brackets, colons, `@` signs, backticks, back+forward slashes, tildes, question marks, etc are all permitted and could cause havoc on some file systems.

If we 'dumb down' for export to appease the file system, how would we 'dump up' again on import so the system knows the two assets are actually the same?!

My only thought would be to introduce a "name" column (vs "title") in the Page/Form/Style tables into which we store a dumbed-down, filesystem-safe version of the name that is given. That column could be updated every time you save an asset (and populated automatically on upgrade), but remain unused (totally for now) anywhere in the system, except when it comes to export/import. At that point, we use the name column for comparison and treat assets with the same name as equivalent.

If you import a new asset, the 'title' (that you see in the UI) is the same as the filename initially, but if you change it, the name would be re-generated (probably to the same thing unless you started adding double spaces and things).

Any better ideas?

**Comment by philwareham** [comment]
How about a HTML5 `pattern` attribute on the name to disallow special characters, like so:

    pattern="[^\\/:\x22*?<>|]+"

That regex isn't an exhaustive list of all the characters so feel free to add any more. We would need to add a suitable text to the label field and also a pophelp that specifically states that no special characters are allowed - since it is nt immediately obvious that the name will be used as the theme's directory name when exported.

**Comment by NicolasGraph** [comment]
@philwareham, we do not have any problem with the skin/theme name entered in the admin, it is cleaned. The problem is mainly for pages/forms/styles names. Txp allows to name these templates with names that are not safe for the filesystem. As for now they could be exported but not re-imported. In fact, I'm not even sure we should allow them to be exported…

**Comment by philwareham** [comment]
Ah, I see, sorry.

The `pattern` attribute I mentioned could be used on those forms/pages/styles `input` name fields to reduce the problem for any forms/pages/styles created in 4.7 onwards I guess. Doesn't solve any that have been named with problematic characters prior to 4.7 and then exported - but that is edge case I feel or at least a known issue that can be dealt with in documentation pages.

@bloke what do you think of this?

**Comment by NicolasGraph** [comment]
> Doesn't solve any that have been named with problematic characters prior to 4.7 and then exported.

Yes, that's the main problem I guess. Would it be ok from 4.7 to be more restrictive with template names @bloke? For previously named templates we could refuse to export and warn the user he should rename them…

**Comment by Bloke** [comment]
Yeah, using stupid characters in page/form/style names is potentially problematic anyway. However, as a stop-gap, and to avoid compatibility issues, how about this:

* Continue to permit all the characters we do now.
* Document that _only_ assets that confirm to a regular naming convention will be exported.
* If you try to save an existing asset in the UI and it doesn't comply, save it anyway but issue an `E_WARNING` feedback message that if they want the asset to be exported they'll need to rename it to confirm to [insert chosen regex info here].

That way, we're not making any assumptions on anyone's behalf (besides cleaning out the obvious junk chars like quotes, apostrophes, angle brackets, etc) we're telling people what they need to do to comply, we're not breaking backwards compatibility, and don't need to do much extra legwork in the code. Just add the warning if the regex is violated on save, and forbid export (or import) if the regex is violated then.

How do you like them apples?

**Comment by philwareham** [comment]
Fine by me! Let's do that.

**Comment by NicolasGraph** [comment]
Would it be possible to also warn the user via JS while is naming its template? I guess some code from the password setup could be reused (?)…

**Comment by Bloke** [comment]
I'd rather put some instruction field help in, below the name. We've reserved that for plugin/theme authors to use by adding lang strings but there's nothing to stop us using it in core. All we have to do is add a few lang strings to the DB on upgrade.

**Comment by NicolasGraph** [comment]
> I'd rather put some instruction field help in, below the label.

I would be happy with it.

**Comment by NicolasGraph** [comment]
I tried to change the skin name related fields/index in the DB to apply the length of 63 chars we discussed before but I get the following error:

```
 Fatal error: Specified key was too long; max key length is 1000 bytes in /Users/VisVerso/Sites/textpattern-4.7/textpattern/lib/txplib_db.php on line 409
```

I guess I should shorten the `name` part of `name_skin` indexes. Do I just substract the 13 more chars I added to the `skin` part  do want to suggest another length?

**Comment by Bloke** [comment]
I guess subtracting the extra chars would work. But 63 chars - even if you multiply it by 4 to take multibyte into account - shouldn't exceed 1000 bytes. Weird.

**Comment by NicolasGraph** [comment]
Yes but `name(200)` + `skin(63)` multiplied per 4 exceed 1000…
Thus, 187 should be the max. `name` length ((187 + 63) * 4 = 1000).

**Comment by NicolasGraph** [comment]
> Thus, 187 should be the max. name part length of the name_skin index

Bingo!

**Comment by Bloke** [comment]
Gotcha. Well 187 is a bit of a random value. We could reduce the name portion to something sensible here without breaking people's existing content. 63 might be pushing it a little low for Form names, as they could be quite long (maybe). But how about 127 for name columns? Or 80? What do you think?

**Comment by NicolasGraph** [comment]
Hard to say, 63 would be ideal as it would reflect the skin related file names but it is maybe too low in few rare cases as you said…

**Comment by NicolasGraph** [comment]
> 63 might be pushing it a little low for Form names […]

In fact, are we talking about the `name` fields length or just the `name` part of `name_skin` indexes?
For indexes it seems quite reasonable to me to expect the 63 first chars of each templates to be different…

**Comment by Bloke** [comment]
You're right. The indexes can be limited to 63 chars, fine. I forgot we were talking about indexes and not actual field sizes.
