### ISSUE TITLE
[dropzone branch] Chromium 62 (Opera beta) + Safari 11 no immediate feedback when uploading a file. 

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#948]
Select one or more files, click upload. The progress bar is displayed, but no more feedback.
Console reports a syntax error.

Amazingly the files are actually uploaded - that is, go elsewhere (other pane), then return to the files upload pane, the freshly uploaded file(s) is/are listed.

In [txpFileupload.js](https://github.com/textpattern/textpattern/commit/4af28d419cce19988977d9b38828537c91062ac3#diff-5afa1c12109b45ea7e26ea1551acb0fcR18), line 18, I see this:

```
messagepane = $(result.find('#messagepane noscript').html())
```

I removed the ` noscript` and all is well (maybe? or has my mac just been pwnd?)

Amazingly (to me), Firefox 56 doesn’t seem to have a problem…

```
[Error] Error: Syntax error, unrecognized expression: &lt;span class="messageflash success" role="alert" aria-live="assertive"&gt;&lt;span class="ui-icon ui-icon-check"&gt;&lt;/span&gt; File &lt;strong&gt;&lt;a title="Edit" href="?event=file&amp;amp;step=file_edit&amp;amp;id=134"&gt;test1-u.txt&lt;/a&gt;&lt;/strong&gt; uploaded.&amp;#160;&lt;a class="close" role="button" title="Close" aria-label="Close" href="#close"&gt;&amp;#215;&lt;/a&gt;&lt;/span&gt;
	error (jquery.js:2:13425)
	select (jquery.js:2:22251)
	find (jquery.js:2:24945)
	init (jquery.js:2:25435)
	r (jquery.js:2:615)
	done (txpFileupload.js:18)
	_trigger (jquery-ui.js:6:11096)
	_onDone (jquery.fileupload.min.js:1:10124)
	(anonymous function) (jquery-ui.js:6:4505)
	(anonymous function) (jquery.fileupload.min.js:1:10805)
	i (jquery.js:2:28023)
	fireWith (jquery.js:2:28785)
	A (jquery.js:4:14047)
	(anonymous function) (jquery.js:4:16325)
```

**Comment by bloatware** [comment]
Thanks @phiw13, that was a desperate attempt to merge many async responses into one. I hope have found a better way now, commit soon.

**Comment by phiw13** [comment]
@bloatware - issue is solved now, thanks to this [commit](https://github.com/textpattern/textpattern/commit/9d587e66aa9a50b041ea47dea259ad307c919f96) of yours. Closing.

PS - there is still an issue when you start with an **empty** files list (no files uploaded). After uploading one or more files, there is no listing created (list remains blank). But go to another panel and come back to the Files panel displays a list of the uploaded files (and everything works fine from then on, as far as I can see).
