### ISSUE TITLE
[dropzone branch] typo in txplib_html

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#949]
go to Images > Edit Image panel. PHP is angry :-(

```
Fatal error: Call to undefined function comact() in /Users/username/Sites/_txp47/textpattern/lib/txplib_html.php on line 385
```

`comact` should be `compact`

cc @bloatware

**Comment by bloatware** [comment]
Bloody grammar! Many thanks @phiw13, [fixed](https://github.com/textpattern/textpattern/commit/0ca66d475f9b175870020fc636bd870907e0439c).
