### ISSUE TITLE
Themes branch: manifest.json content clarification

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#950]
### Expected behaviour

The `manifest.json` that ships with a theme should populate the details in the theme panel when importing. Such as name, description, version, etc.

### Actual behaviour

The [current manifest in default theme](https://github.com/textpattern/textpattern-default-theme/blob/master/src/templates/manifest.json) (if imported from the theme directory) doesn't populate fields as I'd expect. Can you let me know the correct names of objects in that manifest?

There is also the [txp_skin.xml file](https://github.com/textpattern/textpattern/blob/themes/textpattern/setup/data/txp_skin.xml) in setup which seems to fulfil the same task. We need to remove that in favour of the manifest file for consistency with `themes` directory expectations?

**Comment by philwareham** [comment]
I'm guessing, from skimming the code, that the `website` object should actually be `homepage_url`?

**Comment by NicolasGraph** [comment]
You can create a theme and export it to see how the manifest works.
You are right about `homepage_url` but I could change it if necessary.
Maybe we should use the database field names for clarity?

```
{
    "title": "…",
    "version": "…",
    "description": "…",
    "author": "…",
    "website": "…"
}

**Comment by philwareham** [comment]
For legacy consistency I think that `homepage_url` **and** the database field `website` here should both be renamed to `author_uri` which is used also elsewhere in the CMS (i.e. admin themes, plugins).

**Comment by philwareham** [comment]
Another note: `title` doesn't seem to get included in the manifest.json file if you export a theme.

**Comment by NicolasGraph** [comment]
In fact, the `name` field contains the `title` value. The theme name is used as the theme directory name.

**Comment by philwareham** [comment]
Ah OK. Then the `name` field should really contain the name, regardless. And there should be a `title` field. Can you please amend when you get a spare moment? Cheers!

**Comment by NicolasGraph** [comment]
I can change `name` to `title` but do we really need a field for the theme name which is already use as the directory name?

**Comment by philwareham** [comment]
Hmmm, I guess not then - I'll remove 'title' from my manifest files and put that text into `name` instead. Thanks.

**Comment by NicolasGraph** [comment]
In fact, it now seems logical to me to use the table field names, so `name` should probably be changed to `title` when the `homepage_url` to `author_uri` change will be confirmed in the db.

**Comment by philwareham** [comment]
Righto! 👍

**Comment by NicolasGraph** [comment]
I changed the JSON `name` field to `title` and `website` to `author_uri` and I made the related change for the db. I could push everything with the next commit.

**Comment by Bloke** [comment]
Awesome, thank you! Looking forward to merging this into the main dev branch.

**Comment by NicolasGraph** [comment]
I threw the pull request to the _themes_ branch because that was the base branch of mine.
Let me know if that is ok for you.

**Comment by philwareham** [comment]
The latest themes branch imports/exports manifest.json files perfectly now. Closing this issue. I'm fairly happy for us to merge the themes branch into dev now and continue any theme fixes/improvements there if needed.
