### ISSUE TITLE
Adding a primary key into the "section" table

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#951]
Not an issue, just a (very) useful (and simple) feature request.

Because I didn't find any suitable value for the "sort" attribute, IMHO it could be very useful to add a primary key column (no matter the title you will choose) within the `section` table in order to sort a sections list as (manually) populated into the table. It is just a very simple improvement without any harder coding work.

I did it (TXP latest 4.7-dev version) with an `ID` column and I can sort the list as expected:

    <txp:section_list sort="ID" wraptag="ul" break="" class="menu">
        <li><a href="<txp:section url="1" />" data-tooltip="" title="<txp:section title="1" />" class="tooltip--triangle"><txp:section title="0" /></a></li>
    </txp:section_list>

**Comment by bloatware** [comment]
Isn't that what you'd get without any `ORDER BY` clause? If so, I'd rather modify `<txp:section_list sort="" />` tag behavior than add a db column.

**Comment by cara-tm** [comment]
There is no such a column among: "name", "skin", "page", "css", "description", "in_rss", "on_frontage", "searchable", "title", in order to sort the sections as populated into the table (the default sort order is `name asc` see: https://docs.textpattern.io/tags/section_list).

**Comment by bloatware** [comment]
My guess was that without `ORDER BY` clause, the records would be sorted in the order of insertion, but I was wrong. So yes, a new column is needed for what you want, but I leave the update code with our db gurus.

**Comment by cara-tm** [comment]
Fine. Thanks ;)

**Comment by cara-tm** [comment]
Please, consider to close this issue (and feature request): I didn't figure out that the section_list tag had an (pretty useful ;) ) attribute named "sections" where properties can be set in the specified order. This specified order feature was my demand to achieve such a same result with the help of a new table column:

sections="section name(s)"
    Comma-separated list of section names to include in the list, displayed in specified order (unless overridden by the sort attribute).
    Default: unset (all sections).
