### ISSUE TITLE
Callback events do not fire on async forms submission

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpattern#956]
As far as I tried, the `page_saved` callback does not fire unless I remove the `async` class of the form.
I noticed the same issue for the `form_saved` and `css_saved` events.

**Comment by bloatware** [comment]
Just in case, plugins type should be set to `admin+ajax`...

**Comment by NicolasGraph** [comment]
And the winner is… Oleg! One more time. Thanks @bloatware!

**Comment by NicolasGraph** [comment]
Just as a bookmark for anyone meeting this kind of issue: https://forum.textpattern.io/viewtopic.php?id=38434
