### ISSUE TITLE
Dev Tools

### ISSUE THREAD

**Issue by makss** [textpattern/textpattern#965]
IMHO, The development process should be convenient and enjoyable. Let's discuss this topic.

@philwareham **is a great man!** He knows a lot and remembers about everything!!!
I so precisely can not.
Sync:
```
textpattern-default-theme
textpattern-classic-admin-theme
textpattern-hive-admin-theme
compile/rebuild: UI, bootstrap, icon, sprites, etc
textpacks / langs
pophelp
... docs, wiki
... code check, PSR-2
... and a lot more about what I do not know
```
We also have a directory `/vendors/*` that uses external components and also needs synchronization.

Let's try to streamline and automate the development and synchronization process. I understand that use dependent git repository will not work. I think that we need to use separate folders from external repositories, rather than fully connect them.

[The first attempt](https://github.com/textpattern/textpattern/commit/2d40d531866068d6d17f382f3b224efba2094a0a) and execution
```
npm run get-default-theme
```
See [result](https://github.com/textpattern/textpattern/commit/166fbe6082c94c0dbec5c90a74b85969a8a2c706)

Yes ... it's a bit exotic to use `npm`(NodeJS) to run a simple `shell` script, but it's one interface for many other features.

Please check the work of this shell update script.
Linux+NodeJS - all OK.

If necessary, I'll write it on NodeJS and make it out as a package, unfortunately existing npm packages do not perform the required task.

If all goes well, I'll try to add
```
npm run get-classic-admin-theme
npm run get-hive-admin-theme
npm run get-textpacks
npm run get-pophelp
...maybe something from `vendors/*`
```
`phplint` - it seems to be added normally.
`PHP-CS-Fixer` (PSR-2) - questionable.

Creation of sprites from `svg` or inclusion of external `svg` inline `css` it will be possible to make in a theme repository.

What tasks can be simplified? What tools can I use?

---

### Done:

```
npm run get-default-theme
npm run get-classic-admin-theme
npm run get-hive-admin-theme
npm run get-textpacks

npm install
npm run phplint
```

**Comment by philwareham** [comment]
Hi. Been away from computer this weekend. Let me look over your work tomorrow - I agree there is a lot of manual tasks right now so I’m fully in favour of some automated build tasks!

**Comment by philwareham** [comment]
Hi again. OK I've tried this now - very nice so far!

I wouldn't worry about trying to include PHP-CS-Fixer - I just run than manually from time to time and fix *some* of the report only when appropriate to our coding style.

SVG is all inlined now in CSS for admin themes apart from some simple sprites that I'd rather keep as external sprites.

One thing that would be great - if it's even possible - would be to have the option of pulling either a tag release from the other repos as well as just the master. That way when we start 4.8 development but still need to pull a revised 4.7 theme into the 4.7.x branch I can do that using your method.

**Comment by makss** [comment]
You can specify the name of the branch you want to receive.
Get `master`:
```
    "get-hive-admin-theme": "rm -rf textpattern/admin-themes/hive* && curl https://codeload.github.com/philwareham/textpattern-hive-admin-theme/tar.gz/master | tar xz --strip=2 --directory=textpattern/admin-themes textpattern-hive-admin-theme-master/dist",
```
Get `4.6.x`
```
    "get-hive-admin-theme-46": "rm -rf textpattern/admin-themes/hive* && curl https://codeload.github.com/philwareham/textpattern-hive-admin-theme/tar.gz/4.6.x | tar xz --strip=2 --directory=textpattern/admin-themes textpattern-hive-admin-theme-4.6.x/dist",
```

**Comment by philwareham** [comment]
Ah I see, great thanks. We probably need to document this new stuff somewhere in the README (which doesn't get distributed with releases anyway).

**Comment by philwareham** [comment]
This works great.

If you are happy to, please close the issue. If you have other dev tools you'd like to introduce then that's great too. The less manual stuff I have to do the better!

**Comment by makss** [comment]
The main work is done. What other tools can I add?

**Comment by philwareham** [comment]
Hi. Can’t think of any more tools right now but what you have done is brilliant. Already saved me countless time! Happy to close the branch now.

There are a couple more JavaScript files which I’ll add to dependencies in time.

**Comment by philwareham** [comment]
Hi again Makss - we could also pull the pophelp files in with this dev tool. Forgot about that one. Cheers!

**Comment by makss** [comment]
Oh sure.
I changed the format of the pophelp file and its name a little bit. Now I am preparing a patch.
