### ISSUE TITLE
Reset time/expiry not updating

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#967]
### Expected behaviour

Immediately after a new article is created, the 'reset time to now' and 'expire now' should show the new date stamps in the input boxes.

### Actual behaviour

The input boxes remain at their previous as-set values until the page is refreshed. After that, the AJAX save routine functions as expected and alters the inputs when the checkboxes are used.

### Steps to reproduce

Issue 1

* Create new article.
* Save.
* Wait a few seconds.
* Select 'Reset time to now'.
* Save.
* Observe Posted date input boxes don't change.

Issue 2

* Create new article.
* Save.
* Wait a few seconds.
* Select 'expire now'.
* Save.
* Observe Expiry date input boxes don't change.

**Comment by bloatware** [comment]
Will commit this evening or tomorrow, thanks!

**Comment by makss** [comment]
IMHO, can do this functionality on javascript, without using checkbox and php.
Can place an html element, fill/clear in the onClick event with date/expires input fields.

* html element `publish_now` - onClick - fill publish_date fields current date/time
* html element `expires_now` - onClick - fill expires_date fields current date/time
* html element `expires_reset` - onClick - clean expires_date fields

**Comment by Bloke** [comment]
Although I agree that JS might be the best way in this case because it's, in general we try to avoid using JS unless it makes sense to do so, as it bloats pages (event handlers and load times, eventually). And I like a quick admin interface!

The only thing with using 'reset time to now' and 'expire now' is that if they are JS tools, then the "time now" is the time you click the button not the time you actually save the article (which is what happens now - it really means "I intend to alter the timestamp when I click the save button"). That's a subtle change. Does it matter? Probably not, but I know that I sometimes click the button in advance, knowing that I will want the article to be published "now" when I actually finish writing it.

**Comment by bloatware** [comment]
That should have been [fixed](https://github.com/textpattern/textpattern/commit/99ce906ac9026c8790a5d2b75b0662b0bc3a9b04) now, please test.
