### ISSUE TITLE
dev branch broken

### ISSUE THREAD

**Issue by makss** [textpattern/textpattern#975]
In the GitHub interface (web merge conflict editor), I mistakenly pressed a few buttons.

Branch `themes` I restored. A good `dev` branch is available in the `dev2` branch.

---

The branch `dev` is protected, first in the web interface GitHub you need to remove it:

![Image](https://cloud.githubusercontent.com/assets/5836089/9975382/f4c6a706-5eba-11e5-9456-c033d81d7c24.png)

Then in the console you need to execute the commands:
```
git checkout dev
git reset --hard cd12ed2bbc4e719222610273fd06182a21fc87f7
git push -f
```
It's all.

I apologize for my carelessness.

**Comment by makss** [comment]
Thank you, everything is fine!
Now I'll try again the changes from dev to the themes.

**Comment by philwareham** [comment]
Hi. This should be fixed now. Please test (and then you can re4move dev2 if happy that it's fine now. Cheers!

**Comment by makss** [comment]
All right, I deleted the backup branch `dev2`.
