### ISSUE TITLE
Third-party libraries: txp or cdn?

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#982]
Sorry if that has been discussed before. Should we really ship third-party `js/css` libraries with Textpattern, or can we rely on some CDN?

**Comment by philwareham** [comment]
Since Textpattern can work offline - yes the third-party libraries should be included IMO. All we use are  compatible with our licence so I can't see a problem with bundling them.

**Comment by bloatware** [comment]
I thought namely of fileupload - available on CDN and of limited use offline :-)

**Comment by philwareham** [comment]
True - but I feel we should stick to local libraries in vendors directory in this case. Seems messy to have some files served by CDN(s) are others not. Plus if CDN(s) fall over or go out of business then could pose problems. @bloke thoughts?

**Comment by bloatware** [comment]
Couldn't we pay a server to put them on? Smaller size and no need for a new txp release when some library gets updated.

**Comment by Bloke** [comment]
While I like the CDN approach in principle, many people develop sites offline in local MAMP-style environments so bundling stuff - while it is a faff and increases footprint - is desirable for full functionality. And that includes testing "Uploads" from a local Txp to its own `files` directory so people can be more comfortable that it'll work when pushed live.

**Comment by bloatware** [comment]
Yeah, no evident answer. Well, can we externalize just `zxcvbn.js` which weights 800K and is used only as password strength meter? If it's unavailable, switch to some short home-made meter and basta?

**Comment by Bloke** [comment]
That would be a good compromise for sure. It's only used during setup and when changing password anyway. Like you say, nobody would miss it if they were offline.

What provision is there when loading content from an external source on a local installation, so it doesn't sit there trying to reach the CDN for 10-30 seconds? Do we have control over that sort of thing so if it can't reach it within a few seconds, it gives up and doesn't enable the password meter JS hooks?

**Comment by bloatware** [comment]
Abort must be possible with ajax timeout, then we check if the function exists and act accordingly? Needs testing.

**Comment by Bloke** [comment]
Sounds plausible. If you can make that work, it'd be a great space saver.

**Comment by philwareham** [comment]
`zxcvbn.js` is also used in the users admin panel area, by the way.

**Comment by bloatware** [comment]
Frankly speaking, I would drop this (English) dictionary-based script at all. It labels `anniversary` as `weak`, but `anniversaire` as `strong`. Not that I'm against English...

**Comment by jools-r** [comment]
Just wanted to chip in that offline usability _is important_ for anyone who works where connections are unreliable or not always available (in the country, on a train, in other people's solid-walled offices…). I for one work regularly using a local webserver before uploading. That said, your fallback suggestion for the password strength script sounds sensible, as that is not mission-critical.

**Comment by bloatware** [comment]
OK, I have tentatively externalized `zxcvbn.js`. It should be loaded async (without page render delay) and silently enable the password strength meter as soon as loaded. If something fails, there will be no strength meter, that's all. In theory :-)

Please test, if everything is ok, we will spare 800K.

**Comment by Bloke** [comment]
I could have sworn that I read somewhere that `zxcvbn.js` could be built with international dictionaries but maybe I'm wrong. I know that you can supply your own list of additional words during setup, which I had planned to do one day to warn people using 'txp' or 'textpattern' that they are 'dictionary' words.

I agree that we need a better meter that fits with our international outlook. It's only an indicator, so arguably suprfluous though, so if the effort of doing it "properly" outweighs the benefit let's live without it.

**Comment by philwareham** [comment]
Maybe we should dump `zxcvbn.js` then. If it's giving false messages about things being strong - when they are not - it kind of defeats the whole purpose it was originally intended for.

**Comment by bloatware** [comment]
Dunno. Even with English dictionary, `Britney Spears` is a good password, `my password is weak` is a strong password. Maybe stop the indicator at `good`, not to give an impression of guarantee. And tentative load from CDN is fine by me, 800K for this is an overkill.

**Comment by philwareham** [comment]
My vote is to get rid of it. 800k is too much for something that doesn't work great. People are *usually* clued-up enough these days to use strong passwords.

**Comment by bloatware** [comment]
It's removed from the distribution now, but still available via CDN. I would keep it this way, unless the usability suffers (needs testing), since it avoids passwords like `qwerty`.

**Comment by phiw13** [comment]
How well does that play with strict CSP ?

(obviously I’d need to allow the script, but beyond that ?)

**Comment by bloatware** [comment]
Good question! We presently only filter `frame-ancestors`, but adding the CDN url to `script-src` should suffice (and probably worth doing).

**Comment by phiw13** [comment]
yes the `script-src` is what I was talking about, but I was also wondering how well your ajaxy script handles that. 

I‘ll probably upgrade one of my personal sites to 4.7 soon, and I do use a strict CSP there.

**Comment by Bloke** [comment]
`Britney Spears` isn't a good password? Damn, that's me hacked...

According to [xkcd](https://xkcd.com/936/) using 4+ multiple words is good. And I agree with that sentiment, as long as the words are unrelated. Unfortunately, most of the world's password change systems incorrectly tell me that such a scheme results in a weak password, because they see them all as 'dictionary' words chained together. That's why zxcvbn appealed, because it was one of the few (only?) libraries that seemed to treat passwords sensibly.

But given its international shortcomings I'd agree with Phil and just dump it.

**Comment by bloatware** [comment]
Dumping it, no regrets?

**Comment by philwareham** [comment]
Jolly good!

**Comment by petecooper** [comment]
(Disclosure: former librarian at https://github.com/cdnjs/cdnjs, no current affiliation)

There's also a small issue with using `zxcvbn` _anywhere_ in that the code contains a whole heap of profanity. By nature, including the list of most common passwords includes a lot of swearing. I recall snarky emails sent to me asking why cdnjs was serving up stuff that was blocked by gateway filters and the like. There was a short period where two widely-used education establishment content filters would block any site pulling in `zxcvbn` for profanity and sexual themes.

It was a fu…gosh darn mess, I tell you.

**Comment by bloatware** [comment]
Profanity axed, closing.
