### ISSUE TITLE
Admin themes: use manifest.json instead of php hardcode

### ISSUE THREAD

**Issue by makss** [textpattern/textpattern#983]
We already have everything we need.
It is necessary to improve `Textpattern/Admin/Theme` class and clean manifest() function in themes.

**Comment by bloatware** [comment]
Could `announce(_async)` functions be made a little less abstract in the parent class? They are exactly identical in three official themes. Like most parts, actually.

**Comment by bloatware** [comment]
Re `announce`, all it does atm is inject a message with a status in a template. A theme should just provide a template if not happy with the default one. This template could then also be used for client-side announces I had to introduce for async multiple files upload, though there might be a better solution for this.

**Comment by philwareham** [comment]
Done - many thanks yet again @makss. Closing.
