### ISSUE TITLE
[languages-inclusion branch] the message pane should use the full language name, not the short code when installing / deleting

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#984]
STR:
1. install (or delete) a language (example use: Français)
2. look at the message pane: the text say, e.g. “fr installed” / “fr deleted”

expected: the text string say: “Français installed”

The main dev branch does this correctly.

**Comment by Bloke** [comment]
Try b6f7ed35 and see if things improve. Thanks for the report.

**Comment by phiw13** [comment]
Yes much better for all of Install, Delete and Update, thank you.

**Comment by philwareham** [comment]
Looks fine to me too now - @phiw13 if you are happy with this fix now then please close issue. Thanks both.
