### ISSUE TITLE
[languages-inclusion branch] Textpack version string usage?

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#985]
In the Textpacks, inherited from the legacy translation files, we have first line:

    #@version 4.7.0

Does this actually have any usage? If not I'd rather move it as it implies that Textpacks are tied to a certain release (whereas my plan is to simply tie them to GitHub release branch tags).

**Comment by Bloke** [comment]
It's not used. Legacy information as a placholder for when we had timestamps tacked on that row.

BUT you can't just hack it out of the files without changing code too. `vendors\Textpattern\L10n\Lang.php` expects 5 rows of metadata and does some wrangling with the version row storing it as a `file_note`, even though it's ultimately unused.

Unless you're comfortable removing the version bits and bobs from that file and preserving `filemtime`, assign this to me and I'll do it.

**Comment by philwareham** [comment]
OK, yes please - can you amend. I've already updated the Textpacks to remove it so when you are done (and if you have Node.js installed on your system) you can either do `npm run get-textpacks` or let me know and I'll pull the Textpacks in myself. Cheers!

**Comment by Bloke** [comment]
I see you've already stripped out the version string from the textpacks repo. That's great. In which case, when we're ready to merge that into this branch or everything gets rolled into dev, this is what needs doing:

1. Change the [number of meta rows](https://github.com/textpattern/textpattern/commit/b6f7ed35e6fea6db86cc69829620a0c2831db7ad#diff-d79294d41f4c07f4da46013c5b82c8efR139) to 4.
2. Reduce all three of [the `$rows` array indices by 1](https://github.com/textpattern/textpattern/commit/b6f7ed35e6fea6db86cc69829620a0c2831db7ad#diff-d79294d41f4c07f4da46013c5b82c8efR152 to cater for the fact that the first row is missing.
3. Add the language strings noted in the [commit message](https://github.com/textpattern/textpattern/commit/b6f7ed35e6fea6db86cc69829620a0c2831db7ad).
4. Profit.

A quick test of adding/removing languages form the Languages panel using the updated lang files should prove if it works or not. I don't think there are any other changes required.

**Comment by philwareham** [comment]
Just wanted to clarify, this means 4 rows not 3 (i.e. it counts the `#@common` as a row)?

```
#@common
lang_name => جزائري عربي
lang_code => ar-DZ
lang_dir => rtl
#@admin
...
`

**Comment by Bloke** [comment]
Yep.

**Comment by philwareham** [comment]
OK, one more thing - can you provide English translations for the following strings and I'll add to Textpacks as requested in your commit message...

Requires new strings in the `lang` group:
* language_deleted (`{name}`)
* language_installed (`{name}`)
* language_not_installed (`{name}`)
* language_updated (`{name}`)

And in the `common` group:
* cannot_delete (`{thing}`)

**Comment by Bloke** [comment]
```
language_deleted => Language <strong>{name}</strong> deleted.
language_installed => Language <strong>{name}</strong> installed.
language_not_installed => Language <strong>{name}</strong> not installed.
language_updated => Language <strong>{name}</strong> updated.
```
and
```
cannot_delete => Cannot delete {thing}.
```

**Comment by philwareham** [comment]
Ta!

**Comment by philwareham** [comment]
OK - done those extra strings now. Cheers! Closing the issue.
