### ISSUE TITLE
Thank you, Team Textpattern

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#986]
Note: this isn't an issue with Textpattern CMS.

I want to thank the development and design team for all the time, efforts and extensive thought that goes into this wonderful piece of software.

I haven't been around the Textpattern ecosystem much recently thanks to various offline things, and whenever I do check in here I see evolutionary progress, improvements and measured changes that really make me proud to be a user of this software.

Thank you @Bloke, @philwareham, @bloatware, @rwetzlmayr, @makss, @NicolasGraph, @gocom, @vanmelick and everyone else I've missed for your contributions to this software. You are amazing.

(In the interests of Issue hygiene I will self-close this in 5 days.)

**Comment by Bloke** [comment]
You're welcome. I enjoy doing this.

Glad it's of use to people and the fact we don't just throw features in for the sake of it, but strive to do so in the interests of keeping the platform fast, nimble and extensible, comes across.

**Comment by bloatware** [comment]
Thanks, Pete! I want also to thank all people (they will recognize themselves) who suggest features and, especially, fearlessly test our raw code. Their contribution is essential.
