### ISSUE TITLE
Weird inline pophelp rendering bug

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#991]
### Expected behaviour

When clicking a '?' link, the pophelp dialog appears.

### Actual behaviour

Sometimes the dialog won't render properly. You get a blank dialog, a load of JS errors including "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience" and from that point forward, any click on a pophelp link launches a new browser tab with the base URL and a `#`.

### Steps to reproduce

1. Run setup.
2. Accept English language.
3. Click the pophelp topic for table prefix.
4. Mess around with the pophelp dialog. Move it, resize it, close it, open it, move it then close it using escape real soon after moving it, open it again, move it, close it, etc. Do this kind of thing a few times and occasionally you see the above behaviour.

I think jQuery is tripping up when one thread is still executing (e.g. the 'move' process) and another one (e.g. the 'close' process) fires simultaneously while it's not finished with the previous thread. Not sure.

I can't exactly nail down the circumstances it happens. Is it repeatable? Worth worrying about?

Seems to only occur using inline help (e.g. during setup).

Behaviour noted in latest Firefox.

**Comment by philwareham** [comment]
I'm getting the same behaviour (Safari 11) if you really quickly click a few pophelp links. The modal gets broken and then (in the case of setup pages at least) total breaks the page.

**Comment by bloatware** [comment]
Can't reproduce, which branch?

**Comment by philwareham** [comment]
Hmm, I'm inly seeing it on the languages branch when you are on setup 'Set database details' panel. If you click as quickly as you can between the pophelp links for 'table prefix' and 'http(s)' then you can within a few clicks break the dialog box. Once broken if you try and continue setup (or go back a step) then the setup breaks (you have to start afresh).

**Comment by makss** [comment]
Firefox 52.4.0 - can not reproduce the error.

**Comment by philwareham** [comment]
Sorry, it was actually the 'Populate database' setup page where this was happening. Click the pophelps as fast as you can and eventually this will happen...

![grab](https://user-images.githubusercontent.com/413665/32603070-50c12908-c540-11e7-81de-0355b0f7fb52.png)

Then if you either click on another pophelp or try do fill your details out and continue setup fails with error messages.

**Comment by makss** [comment]
I saw! I'll fix it now.

**Comment by makss** [comment]
[Fixed](https://github.com/textpattern/textpattern/commit/41f2ceb3758e1f33b89c6e0a9a6085d557718345), please test.

**Comment by philwareham** [comment]
Seems to be fixed for me thanks, can't break it no matter how hard I try! @bloke can you test on your system?

**Comment by Bloke** [comment]
Brilliant, can't break it any more. Thanks, makss.
