### ISSUE TITLE
Txp::get vs \Txp::get

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#992]
Does it matter that in some places we use `Txp::get()` and in some places (e.g. `txp_prefs.php`, `/vendors/Textpattern/Http/Request.php`, etc) we use `\Txp::get()`.

I don't think using the namespace root identifier makes a difference in most cases... or does it? Should we be consistent? Or leave it?

**Comment by NicolasGraph** [comment]
I use `\Txp::get()` in the _Skin_ package to get the `Txp` class from outside the `Textpattern\Skin` namespace but as there is no namespace in `txp_prefs.php`, `Txp::get()` should work, right?

**Comment by Bloke** [comment]
I think so, yes. In theory we should probably use the namespaced form with the preceding slash everywhere. Y'know, just in case. Plus it's consistent. I don't think it has any ramifications.

Whether I can be bothered to do it and increase the size of the codebase again, I don't know! Maybe we'll just remove them from prefs and keep them where we definitely need them.
