### ISSUE TITLE
CDN resources should have `integrity` attribute, possibly `crossorigin`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#995]
Now that `zxcvbn` is loaded from a CDN, it's potentially more susceptible to 3rd party tampering. To combat this, the `integrity` attribute can be added when the javascript is loaded.

I am not 100% sure how to do this as I don't speak javascript yet, but here's how I'd load it in plain HTML (the sha384 value was calculated here,):

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.4.2/zxcvbn.js" integrity="sha384-jhGcGHNZytnBnH1wbEM3KxJYyRDy9Q0QLKjE65xk+aMqXFCdvFuYIjzMWAAWBBtR"></script>
```

As a second point – is there anything preventing `crossorigin="anonymous"` being implemented, too? Any CORS stuff/restrictions on the security side of things?

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.4.2/zxcvbn.js" integrity="sha384-jhGcGHNZytnBnH1wbEM3KxJYyRDy9Q0QLKjE65xk+aMqXFCdvFuYIjzMWAAWBBtR" crossorigin="anonymous"></script>
```

**Comment by bloatware** [comment]
Thanks @petecooper. Re `zxcvbn` we are strongly inclined to dump it, but if it stays, I will do something (unsure how atm).

**Comment by bloatware** [comment]
The problem with `<script />` tag inclusion is that there seems to be no reliable way to know when it's loaded, to enable the strength meter. And jQuery.ajax loaded scripts do not check the integrity, until [this](https://github.com/jquery/jquery/issues/3028) issue is resolved. I have modified the code like I could (will commit soon), but am not happy with it.

**Comment by petecooper** [comment]
Thanks very much, @bloatware - I'll close this for now since it's relying on 3rd party issues and may get dumped anyway.
