### ISSUE TITLE
Investigate some form of automated install

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#996]
I keep coming back to Textpattern PR/marketing and I'm convinced that if were possible to automate/script the installation process, it would lower the barrier to being included in control panel 'Install App' selections. Plus it'd make re-installation much more straightforward on the demo site, too. I'm selfish, I know.

This is a marker/reminder for me that I should look into it, see if it's viable, and make it happen. I'm also very happy to receive advice, feedback or help from anyone to assist in getting this off the ground.

{PS: I don't have write access to this repo's issues – please could someone assign it to me with a 4.9 milestone.)

**Comment by makss** [comment]
Which hosting panels support automatic installation?
What are the requirements for our auto installer?

**Comment by petecooper** [comment]
Hi @makss - many (most, anecdotally) of the well-known and widely-used control panels have some form of application installation, typically popular CMSes like Wordpress, Drupal etc.

cPanel is widely used and has a popular (again, anecdotally) application installation area. My understanding is that the sources are catalog'd here:

https://applications.cpanel.net

Another is Plesk (https://www.plesk.com). I have a vague memory of an out-of-date (vulnerable) Textpattern being present on a Plesk (or similar) control panel and numerous attempts to work with them to have it updated to a newer (safer) version, without success. I recall that their approach to setting it up was pretty kludgy and it didn't look great.

From a personal point of view, the Textpattern demo site I run is a bunch of bash scripts and some known-good SQL files. The process of reinstalling every three hours is pretty rudimentary:

* delete the demo site scaffolding, file and database
* create the demo scaffolding, drop in a known-good Textpattern
* import a known-good database
* drop in configuration files
* final tweaks
* go live

I would _love_ to have a situation like this:

* delete the demo site scaffolding, file and database
* create the demo scaffolding, drop in a known-good Textpattern
* drop in configuration files
* run a shell script or PHP file that recognises a setup config file with an automated-setup flag is present, imports the core SQL, creates the Textpattern user(s) from a SQL query or similar, applies the core theme, optionally important the core content
* …and -- BOOM -- site is live.

This may well be outside the scope of the core code, and I fully understand that core cannot have everything. That said, from a deployment point of view, it would make things much more portable, and if a busy devops person can have a documented way of adding Textpattern to an app portfolio, and the net result is uniform across each control panel, this would be an amazing thing to do.

**Comment by petecooper** [comment]
Follow up: I just remembered another reason why an automated install would be great in core -- I can add the dev version directly from GitHub to the demo site, and that will attract more eyeballs.

The barrier to entry for the dev version is higher than the release version because it involves setting up a dev environment. I am happy to take the burden of building the environment, having UX eyeballs is valuable.

The only thing stopping me running a dev branch site now is the pace of change. I can't commit the time to update the known-good SQL blob every time a merge happens, but if the logic is spun on its head and specimen SQL scripts are included (extracted from the setup script), then that would be _amazing_ and much more manageable.

**Comment by makss** [comment]
The installation process for Textpattern v4.7 is much simpler, I think I'll do an auto installation.

**Comment by petecooper** [comment]
Thank you, @makss -- this is great news!

**Comment by makss** [comment]
The [patch](https://github.com/textpattern/textpattern/pull/1019) is already available in `dev`, you can test it.

**Comment by makss** [comment]
Ups, sorry, reopen issue

**Comment by petecooper** [comment]
Huge thanks, @makss -- I will set up and test, and report back.

**Comment by Bloke** [comment]
Yes, some fab work here. I'll run tests on the manual installation too, because there were a whole heap of corner cases in the setup routine that we had to kludge around to do with session usage. Since makss has (mostly) designed out the `SESSION` variables to make autoinstall possible, a lot of the kludges have been removed, which is great for usability and code cleanliness.

**Comment by petecooper** [comment]
Initial feedback on automated install - it works really well.

Thank you for your work on this @makss - it's great!

**Comment by philwareham** [comment]
Closing. We can ask beta testers to stress test this when we release the beta  version.

**Comment by makss** [comment]
> $ time sudo ./dev-demo.sh 
Cloning into ''...
remote: Counting objects: 53207, done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 53207 (delta 107), reused 102 (delta 56), pack-reused 53027
Receiving objects: 100% (53207/53207), 31.24 MiB | 10.68 MiB/s, done.
Resolving deltas: 100% (35526/35526), done.

You can use the `tar.gz` file, perhaps it will be faster than `git clone`
```
curl https://codeload.github.com/textpattern/textpattern/tar.gz/dev | tar xz --strip=1 --directory=my-output-folder textpattern-*
```

**Comment by petecooper** [comment]
Thank you - I'm _very_ happy with 11 seconds, @makss.
